### ISSUE TITLE
long container name cause breakage when deriving hostname

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1006]
````
$ weave launch && weave launch-dns && weave launch-proxy
233175e68b3f1acdb4b575365b65873bb4e6f2fdde4540ee58fb5a940fa1cc0e
eab7f5de2f66576835a4e119570304ab16b6bbae26a8f752315d46b6c5d29e53
9f22c0618999ba92de2ca1fe038ca6700470e6ee5a5c3e6b8adae7772c23deaf
$ eval $(weave proxy-env)
$ docker run --name=a123456789012345678901234567890123456789012345678901234567890 -ti ubuntu
invalid argument
Error response from daemon: 18944953c27c4ed8f71f2fbd1989e7bd8f79cbd9c1a77b23c31d6fd25f94d093 container is not running.
````

**Comment by rade** [comment]
[63 characters](https://en.wikipedia.org/wiki/Hostname) for each dotted component, is the maximum.

**Comment by awh** [comment]
What's the desired behaviour in this case? Truncation? Disable hostname synthesis?

**Comment by rade** [comment]
> What's the desired behaviour in this case?

I wish I knew.

Truncation seems prone to surprising results. Disabling synthesis less so.

I suspect the most common case for ending up with long names is that they have been auto-generated. In which case we probably don't want them in DNS, just like we don't want docker's auto-generated names in DNS.

That can still lead to surprising behaviour, e.g. consider an auto-generation scheme that produces names of different length, some of which are <63 chars while others aren't.

Perhaps we need a config option on the proxy to disable auto-generation.

**Comment by tomwilkie** [comment]
For the ECS case, we could either provide a regex to the proxy to extract a the hostname from the container name, or provide an option to read it out of the container environment vars.

If all else fails, I think it makes sense to truncate.

**Comment by tomwilkie** [comment]
Given we see the create, if hostname=container name is turned on, we could block container creation with long names, with a helpful error message.  That would stop people being surprised.

**Comment by rade** [comment]
Hmm. regexp :) That's a nice generalisation of the current scheme, and also allows for disabling.

**Comment by rade** [comment]
What this *doesn't* give us in case of ECS is for the user to *selectively* registering containers in DNS. For ordinary docker containers that choice is made by explicitly naming (or not) the container. But according to the ECS docs, the container name is mandatory. I suppose we could encode the choice in that name, e.g. "if you want your containers to be registered in DNS, then prefix their container name with some-special-symbol-tbd".

**Comment by tomwilkie** [comment]
Using the containers environment field would give the users the optionality; and you can specify the environment in the ECS api.

**Comment by rade** [comment]
re env vars... I am vary of introducing yet more ways for users to specify the hostname, and options to configure precedence, etc. "You can specify a hostname with -h. If you don't then the hostname is derived from the container name. Unless you supply a WEAVE_HOST env var, in which case that takes precedence. And if you configured the proxy with `--hostname-from-env` then hostname is *only* set through WEAVE_HOST. Unless -h was specified".

**Comment by rade** [comment]
In this issue, let's stick to fixing the breakage. I suggest that when the name is too long we don't set the hostname. In case of the proxy, we should log a warning. In case case of `weave run`, we should echo a warning to stderr (but not fail).

**Comment by squaremo** [comment]
> Hmm. regexp :) That's a nice generalisation of the current scheme, and also allows for disabling.

Now your user has two problems.

There are very few situations in which it's reasonable to ask a user to input a regular expression as an option (and even those have UX problems -- escaping for example).
