### ISSUE TITLE
Feature Requests: Clean up the docs, change the name of Proxy

### ISSUE THREAD

**Issue by Stellaverse** [weaveworks/weave#1007]
Hi folks,

Love your software, but getting started with it is very, very confusing and painful.

**When am I?**
You seem to have multiple versions of your docs mixed in with each other. For example, how do I go about `run`ing a container using Weave?

A. `sudo weave run -d ubuntu`?
B. `sudo docker run -d ubuntu`?

Which is the *proper* command to run? Please pick only one.

**Just the sandwich, I'll come back for the whole cow later**
Why am I blindly executing shell scripts that spin up resources? Leave all that crap out. Just give me the commands to run *your* software, not provision infrastructure. I end up skipping those parts in your getting started guides anyhow and then when I hit trouble I have no idea what your shell scripts did and have no ability to debug.

**Wait, what does Proxy do?**
You gotta get off this word. `Nginx` is a proxy, `node http-proxy` is a proxy, `haproxy` is a proxy. Weave proxy is not a proxy, which is what I thought its purpose was for three days. I understand that this is technically true, but in the realm of microservices `proxy` defaults to an `http proxy`, not a sidekick that talks to Docker.

**Comment by rade** [comment]
> You seem to have multiple versions of your docs mixed in with each other.

I am guessing you are referring to discrepancies between the [main docs](http://docs.weave.works) and the [guides](http://weave.works/guides/). The latter are lagging the former; we just haven't managed to update them all yet. Work in progress. Sorry.

Have you found any discrepancies *inside* the main docs alone?

> Just give me the commands to run *your* software, not provision infrastructure.

That is the key conceptual difference between the docs and guides. The former only talk about our software, and assume the reader takes care of setting up the required infrastructure. The latter are intended to be more self-contained and take a reader from a blank slate to a working system.

> Proxy - You gotta get off this word

Any suggestions? It isn't really a sidekick. "Transformer"?

**Comment by Stellaverse** [comment]
Fair enough about the guides/docs. Jus found it difficult to get the info I needed amongst everything else and there seems to be two sets of truth that was quite confusing.

I can't imagine a name change would actually make it on the Weave Proxy roadmap, but I would suggest Weave Relay.

**Comment by rade** [comment]
- guide/doc discrepancy -> https://github.com/weaveworks/guides/issues/5
- infrastructure setup obscuring weave -> https://github.com/weaveworks/guides/issues/6
- proxy rename -> #1019
