### ISSUE TITLE
more flexible container name -> hostname derivation

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1018]
See the discussion in #1006.

The idea proposed there is to derive the hostname from the container name in the proxy via a configurable regexps. Defaults to `".*"` and could be set to `"^$"` for disabling hostname derivation (i.e. if the regexps matches nothing then we shouldn't set the hostname). Should support sub-matches, e.g. `"aws-[0-9]+-\(.*\)"`.

We *could* have an env-var equivalent for `weave run`. Overkill?

**Comment by paulbellamy** [comment]
In the submatch example, what would the hostname for `aws-1234-db1` be? `aws-1234-db1` or `db1`? What if there are multiple match-groups? Or should we have them supply a replacement regexp as well?

**Comment by rade** [comment]
Assume one match group.

Re replacement regexp... yes.

**Comment by paulbellamy** [comment]
So, command-line usage will look like:
`weave launch --hostname-regexp 'aws-[0-9]+-(.*)' --hostname-replacement 'my-app-\1'`
where `--hostname-replacement` is optional. Seems a bit verbose.

Could do a sed-style replacement:
`weave launch --hostname-regexp '/aws-[0-9]+-(.*)/my-app-\1/'`
But could be less familiar for users.

**Comment by rade** [comment]
I'd got for sed style.

You mean `weave launch*-proxy*`

**Comment by rade** [comment]
`--hostname-from-container-name`?

**Comment by paulbellamy** [comment]
`--hostname-from-container-name` sounds like a boolean flag
`--hostname-default '/aws-.../'`?

**Comment by rade** [comment]
just `--hostname`?

**Comment by paulbellamy** [comment]
is this going on both `weave launch` *and* `weave launch-proxy`, or just on `weave launch-proxy`? If it's just on `launch-proxy`, then `--hostname` with a reasonable help text sounds fine, but on `launch` it seems a bit vague.

**Comment by rade** [comment]
Only on `launch-proxy`. `launch` passes args to the router only.

**Comment by squaremo** [comment]
(Cross-posted from #1006)

Now your user has two problems.

There are very few situations in which it's reasonable to ask a user to input a regular expression as an option (and even those have UX problems -- escaping for example). If container names aren't really suitable as hostnames, perhaps trying to use container names as hostnames is a mistake.

**Comment by rade** [comment]
> If container names aren't really suitable as hostnames, perhaps trying to use container names as hostnames is a mistake.

They *are* suitable in most cases. We are just making them suitable in even more cases.

> There are very few situations in which it's reasonable to ask a user to input a regular expression as an option

Yep. I would expect few users ever needing to touch this option.

**Comment by squaremo** [comment]
> There are very few situations in which it's reasonable to ask a user to input a regular expression as an option
> 
> Yep. I would expect few users ever needing to touch this option.

I think you mistook my meaning. Let me put it another way: think hard about your assumptions if you find yourself wanting to use regular expressions in a user interface.

**Comment by rade** [comment]
You don't have to use the automatic hostname derivation. It's there purely for convenience, and for the situations where the hostname cannot be specified directly (@tomwilkie ran into that on ECS, I believe).
