### ISSUE TITLE
`weave status` can contain large amounts of output

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1025]
The lists of MACs, peers, retries, routes, allocated ranges and DNS registrations can all get very big. Perhaps we should print a summary only, and then have flags or dump commands that list out these different quantities in full (preferably in machine readable form).

**Comment by rade** [comment]
I've been thinking the same. In particular it would be good if the default status output was more of a "health status", i.e. something from which it is quite easy to tell whether everything is alright or not (and why not).

re machine-readable form - that's what we have the (undocumented) json output for.

**Comment by bboreham** [comment]
When troubleshooting weave it would be nice to be able to get full information; for instance there is no way currently to get a full dump of what the IPAM Allocator thinks.

We could have options on status, e.g. short/tall/grande/venti.

**Comment by awh** [comment]
> In particular it would be good if the default status output was more of a "health status"

Referencing #908.

**Comment by awh** [comment]
> (undocumented) json output

Raised #1027.

**Comment by awh** [comment]
Referencing #1141.
