### ISSUE TITLE
Extend and document status JSON

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1027]
We have a machine readable status JSON resource but:

* It's undocumented
* It doesn't cover weaveDNS and IPAM

**Comment by rade** [comment]
I reckon documenting the existence of the status json is a first step. Devs should be able to figure out what the fields are by looking at samples and the description of the (text) status output we are giving in docs. Let's not boil the ocean here

**Comment by rade** [comment]
We could perhaps add go template support to extract fragments of status more easily.
