### ISSUE TITLE
Service export should find the address automatically

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1028]
The [service export example](http://docs.weave.works/weave/latest_release/features.html#service-export) shows `weave ps` being used to find an address; since we should know that address via weaveDNS we should provide a feature to automate that step.

**Comment by bboreham** [comment]
The (undocumented) command `weave docker-bridge-ip` can be used:

````
$ weave launch && weave launch-dns && weave launch-proxy
bbc75b5f799b9d79cfa853030bd7f79ce3d274100f9be2717b2c13c510de8ac6
4c331baeac817fb6869ee4e83221cd8a87b406b84937b22d53857e05290d4f2b
c7178da7417964026eda1249c870c7222c02a1ac5c7574bec3e25b949124245a
$ eval $(weave proxy-env)
$ docker run --name=foo -dti ubuntu
3d1b3e567329ea3bc6b5059e9f38e9733f5c441e92a2dfc6b38b3c28eedbe24f
$ dig @$(weave docker-bridge-ip) +short foo.weave.local
10.128.0.2 
````

**Comment by rade** [comment]
So the problem with `weave ps` is that it only works on the host that the container resides on. This in fact leads to awkwardness in the example, as it needs to jump between hosts. The great advantage of `weave ps` though is that it works even when containers aren't registered in weaveDNS. Though arguably for the 'service export' use case that probably doesn't matter, i.e. it's not unreasonable to expect all services to be registered in DNS.

The problem with `dig` is that it requires specifying the fully qualified name. #987 would address that.

Plus you need `dig`.

We could introduce a `weave dns-lookup <unqualified-name>`.

**Comment by rade** [comment]
> We could introduce a `weave dns-lookup <unqualified-name>`.

...which we could implement in terms of `dig` in the script, instead of widening the weavedns http api.
