### ISSUE TITLE
htop reports six processes for each one container

### ISSUE THREAD

**Issue by Stellaverse** [weaveworks/weave#1032]
Hey rade,

Run into a new issue while working on implementing Weave now that I'm working on launching containers that have a bigger footprint than a Hello World app.

**The Setup**
```
weave launch
weave launch-dns --ttl=9 --domain='stellaverse.srv.'
weave launch-proxy
eval $(weave proxy-env)

docker run -d --name app1 -h app.stellaverse.srv --restart=on-failure:9 stellaverse/app
docker run -d --name app2 -h app.stellaverse.srv --restart=on-failure:9 stellaverse/app
docker run -d --name api1 -h api.stellaverse.srv --restart=on-failure:9 stellaverse/api
docker run -d --name api2 -h api.stellaverse.srv --restart=on-failure:9 stellaverse/api
docker run -d --name proxy -h proxy --restart=on-failure:9 stellaverse/proxy
```

And then when I run `htop` I see something like this:
```
5326 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
9704 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
9706 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
9707 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
5169 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
5769 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
5763 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
5966 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
5607 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
7978 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
8008 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
5009 root 20 0 980M 73032 6244 S 0.0 7.2 nodejs /app/app.js
...
```

And then the same for `api` as well.

Essentially, I'm seeing 12 process for each container. I see the same issue when I run a single instance of any given container where `htop` reports 6 processes for each container.

I'm also seeing similar behaviour with `/home/weave/weaver` running 6 processes.

**With traffic, memory gets toasted**

And then when I run a bit of traffic through my instance (25 rps), my memory usage goes way up and stays there, even once the connections have drained. Notably, I see the following in `htop` when I focus on mem usage:
```
8318 root 20 0 980M 73032 6244 S 0.0 33.6 docker-proxy -proto udp -host-ip 172.17.42.1 -host-port 53 -container-ip 172.17.0.12 -container-port 53
8324 root 20 0 980M 73032 6244 S 0.0 33.6 docker-proxy -proto udp -host-ip 172.17.42.1 -host-port 53 -container-ip 172.17.0.12 -container-port 53
8319 root 20 0 980M 73032 6244 S 0.0 33.6 docker-proxy -proto udp -host-ip 172.17.42.1 -host-port 53 -container-ip 172.17.0.12 -container-port 53
8321 root 20 0 980M 73032 6244 S 0.0 33.6 docker-proxy -proto udp -host-ip 172.17.42.1 -host-port 53 -container-ip 172.17.0.12 -container-port 53
8322 root 20 0 980M 73032 6244 S 0.0 33.6 docker-proxy -proto udp -host-ip 172.17.42.1 -host-port 53 -container-ip 172.17.0.12 -container-port 53
8323 root 20 0 980M 73032 6244 S 0.0 33.6 docker-proxy -proto udp -host-ip 172.17.42.1 -host-port 53 -container-ip 172.17.0.12 -container-port 53
```

It's tough to see in there, but each of those `docker-proxy` processes is claiming use of `33.6%` of memory.

Any idea what could be causing this and/or how to put in a fix?

**Comment by rade** [comment]
Surely those are all just threads within a single process, and the memory usage is *virtual* memory and *shared* between those processes.

**Comment by Stellaverse** [comment]
Ah, I see. Apologies. I'm going to go learn how to read `htop` properly and get back to this.

**Comment by Stellaverse** [comment]
Ok, I'm not sure what to make of any of this. Here's a screen cap of the `docker-proxy` processes that are consuming huge amounts of memory:

![docker-proxy htop](http://static.stellaverse.com.s3.amazonaws.com/Docker-Proxy-HTOP.jpg)

That's with zero traffic running through the instance. I also have a secondary issue where I can't get `weavedns` to pick up on a container that has an explicit host port declared, but I'll post in another issue. Not sure if they're related.

**Comment by Stellaverse** [comment]
Posted a new issue describing the problem where `weavedns` does not initially recognize a newly started container with an explicit host port in [#1033](https://github.com/weaveworks/weave/issues/1033).

Is it possible that the unceremonious way that I've `docker rm -f weave weavedns weaveproxy` in order to start them back up is causing rouge processes to eat up al the memory?

**Comment by rade** [comment]
I really don't think the docker-proxy processes' memory consumption is anything to worry about. If you are concerned, perhaps ask the docker follks.

**Comment by Stellaverse** [comment]
Well, it is disabling and killing my server so I kinda have to worry about it.

To be honest, at this point I think I'm gonna go back to `--link` I've tried `Consul`, `Weave`, `docker network`, etc. and this is proving to be more trouble than it's worth.

Thanks for taking the time to consider everything.
