### ISSUE TITLE
weavedns does not detect newly started container with explicit host port declared

### ISSUE THREAD

**Issue by Stellaverse** [weaveworks/weave#1033]
hi folks,

I've come across an issue where `weavedns` does not detect and 'register' a container that has an explicit host port declared. Like so, which runs as the `User-Data` script upon launching my Ubuntu ec2 instance:

```
#!/bin/bash

su - ubuntu

wget -qO- https://get.docker.com/ | sh

sudo usermod -G docker ubuntu
newgrp docker

docker login -u 'myusername' -p 'top-secret-password' -e 'me@dockerhub.com'

sudo curl -L git.io/weave -o /usr/local/bin/weave
sudo chmod a+x /usr/local/bin/weave

weave launch
weave launch-dns --ttl=9 --domain='stellaverse.srv.'
weave launch-proxy
eval $(weave proxy-env)

docker run -d --name Hello -h hello.stellaverse.srv stellaverse/hello
docker run -d --name Proxy -h proxy.stellaverse.srv -p 3333:3333 stellaverse/hello
```

The above script runs in `User-Data` on my `ec2` instance. And then I `ssh` in and  run `weave ps`:
```
weave:expose de:43:aa:8c:ee:10
fbd3ad5060e6 46:17:bd:6e:3e:91 10.128.0.1/10 <--- weavedns
e6a79b8c6b2d 0e:3f:b6:e4:ef:33
c2ccdfa30c9e 42:b6:74:58:2c:45 10.128.0.2/10 <-- Hello
```

I've managed to do a whole lot of fancy-dancing to work around this and get `weavedns` to recognize the `Proxy` container, like so:
```
docker rm -f weave weavedns weaveproxy
docker rm -f Proxy

weave launch
weave launch-dns --ttl=9 --domain='stellaverse.srv.'
weave launch-proxy
eval $(weave proxy-env)

docker run -d --name Proxy -p 3333:3333 -h proxy.stellaverse.srv quay.io/stellaverse/proxy
```

And then it finally detects the `Proxy` container and all works as expected.

But I obviously need `weavedns` to detect my container automatically. Any ideas?

**Possible Related Issue**
This may be related to a memory issue I've also been having where `docker-proxy` seems to eat up a huge amount of memory, even when the server is idle. I've described this issue in [#1023](https://github.com/weaveworks/weave/issues/1032).

**Comment by rade** [comment]
> docker run -d --name Proxy -h proxy -p 3333:3333 -h proxy.stellaverse.srv quay.io/stellaverse/proxy

There are two `-h` in that. docker will pick the first as the hostname. Since it's not in the weaveDNS's domain, weavedns will ignore it.

**Comment by Stellaverse** [comment]
No, that was just a typo in that post. It's been fixed now.

**Comment by rade** [comment]
I see. So what evidence is there that the container doesn't get registered in weavedns?

**Comment by Stellaverse** [comment]
Doesn't show up in the `weave ps` list, when I `docker exec -it Proxy bash` into it I can't resolve any of the other `*.stellaverse.srv` domains.

Once I do all the restarting and such it picks it up and then all works fine from there.

**Comment by rade** [comment]
ok. Do you have steps to reproduce this? (considering that the ones you posted originally contained a typo I'd like to make sure I know *exactly* what you did)

**Comment by rade** [comment]
btw, not showing up in `weave ps` means the container is not on the weave network at all. Hence not in DNS either. So it's not an issue with DNS; something else must have gone wrong.

**Comment by Stellaverse** [comment]
Sure, the first block of code should reproduce the problem if you run it as `User-Data` on an `ec2` instance.

**Comment by Stellaverse** [comment]
Something went wrong, but I'm lost as to what it could be.

**Comment by rade** [comment]
The first block of code has the two `-h` in it. It would be great if you tried again and posted the steps, just to make sure it is really reproducible.

**Comment by Stellaverse** [comment]
Nope. Fixed that typo. I was just a common, every day typo.

I've been wrestling with this for three days. Trust me, it's a problem.

**Comment by Stellaverse** [comment]
Added the additional steps of installing docker and logging in to quay.io and dockerhub.

**Comment by rade** [comment]
> Added the additional steps of installing docker and logging in to quay.io and dockerhub.

But those require your credentials, don't they?

**Comment by Stellaverse** [comment]
Yeah, but this are just placeholder creds ... I mean, I'm not going to post my creds in here.

**Comment by rade** [comment]
are those images really so secret, or could you just publish them on dockerhub?

**Comment by Stellaverse** [comment]
Hello is published on Dockerhub: stellaverse/hello, but you could just as easily use any image. I've reproduced the problem with google/nodejs-hello and ubuntu as well.

**Comment by Stellaverse** [comment]
I should note that this is exactly how I launch containers currently using `--link` for a poor-man's service discovery. The only new addition is `weave`.

**Comment by rade** [comment]
ok. I haven't got an EC2 account handy, so this will have to wait until Monday/Tuesday, when my colleagues can pick this up.

**Comment by Stellaverse** [comment]
Sure, I'll check back in then.

**Comment by rade** [comment]
btw, the evidence you posted would be perfectly consistent with the proxy container having died. Was it alive when you logged in? Anything unusual in its logs?

**Comment by Stellaverse** [comment]
Which proxy container? `weaveproxy` or my `Proxy`?

In any event, both are running fine. Nothing in the logs indicating any errors. Just doesn't pick up the `Proxy` container, and the only difference is that it has a host port explicitly declared where the `Hello` container does not. Same results with multiple containers taking on random ports. Only the one with a declared port gets skipped.

**Comment by rade** [comment]
what public image can I use instead of your private proxy image?

**Comment by Stellaverse** [comment]
Anything. The image doesn't matter.

**Comment by Stellaverse** [comment]
Use `google/nodejs-hello` or just use `stellaverse/hello` for both.

My `Proxy` container has been in service for months. It's fine.

**Comment by rade** [comment]
Here's what I get on my machine:
````
$ weave launch
40f2b0744bb4931edbf18d8cf02fe37f4ee39e8aaccb30ae09db999f2b3b3a17
$ weave launch-dns --ttl=9 --domain='stellaverse.srv.'
0292b9985397e372599a4b275b6a349de688e9fc171e63939c0729322f65504d
$ weave launch-proxy
7bae305efba4288de85adfadf51be38d5fb0db7041c871be2ef80936dafba04f
$ eval $(weave proxy-env)
$ docker run -d --name Hello -h hello.stellaverse.srv stellaverse/hello
c6e3cb7bcb4041cdf4f005a09f4a15dcd3986450661b498678dd226401ec3a4d
$ docker run -d --name Proxy -p 3333:3333 -h proxy.stellaverse.srv stellaverse/hello
5cf43b6844b5c43dd790f611581871d17683be792603f1cab1085d94a232f041
$ weave ps
weave:expose ce:d6:6f:43:0e:92
5cf43b6844b5 ba:2f:f9:70:39:2f 10.128.0.3/10
c6e3cb7bcb40 46:2c:80:d0:06:6c 10.128.0.2/10
0292b9985397 aa:b1:ee:c0:77:34 10.128.0.1/10
40f2b0744bb4 f6:5e:3e:c2:0d:77
````

So it looks like this is an EC2-specific issue. Which is strange. I wonder whether it has anything to do with the execution via `User-Data`. If you instead run the same steps in a shell, does it work?

**Comment by Stellaverse** [comment]
Once sec. I'll try it manually again.

**Comment by rade** [comment]
and `ping` works in that setup on my machine:

````
$ docker exec Hello ping proxy
PING proxy.stellaverse.srv (10.128.0.3) 56(84) bytes of data.
64 bytes from proxy.stellaverse.srv (10.128.0.3): icmp_seq=1 ttl=64 time=0.094 ms
...
$ docker exec Proxy ping hello
PING hello.stellaverse.srv (10.128.0.2) 56(84) bytes of data.
64 bytes from hello.stellaverse.srv (10.128.0.2): icmp_seq=1 ttl=64 time=0.031 ms
...
````

**Comment by Stellaverse** [comment]
Yup. I get the same results. Works when done by hand, but not when part of a `User-Data` shell script.

**Comment by Stellaverse** [comment]
Also tried a second `Hello` container and it works too. Random balancing to the two weaveIPs.

**Comment by rade** [comment]
If you reverse the order of the `Hello` and `Proxy` start, is there any difference to the outcome? e.g. do you then get a proxy container hooked up to weave but not hello?

**Comment by Stellaverse** [comment]
Testing now.

Is that you looking for `docs.stellaverse.com`? Hold on, they'll be on their way soon enough.

**Comment by rade** [comment]
nope, not me.

**Comment by Stellaverse** [comment]
Order doesn't seem to matter. Started up `Proxy` first on 9999 and then `Hello` and both were picked up by `weave`.

**Comment by rade** [comment]
> both were picked up by weave.

Including when the startup is done via the `User-Data`?

**Comment by rade** [comment]
btw, I've just noticed that while your `User-Data` script installs docker, it says nothing about weave. Did you elide that bit? I want to make sure that when we do test this next week we are running *exactly* the same configuration as you, including installing weave, and only using public images.

**Comment by Stellaverse** [comment]
I did. Added it to the first block.

**Comment by rade** [comment]
cheers, but please also take out the `quay.io` references.

**Comment by Stellaverse** [comment]
And no, not when launched via `User-Data`, only manually.

**Comment by rade** [comment]
so, to be clear, when starting the proxy before hello, via `User-Data`, it is still the proxy that fails to register with weavedns, whereas hello registers fine? how did you verify that?

**Comment by Stellaverse** [comment]
Honsetly man, I haven't. I'm now in the middle of removing `weave` and reverting back to `--link`. I just don't have the time to go through all this right now.

Good luck!

**Comment by rade** [comment]
I have just tried this on EC2, and it works fine for me :(

Instance/Image: "Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-47a23a30" (t2.micro)

Here's my `User-Data` script:
````
#!/bin/bash

su - ubuntu

wget -qO- https://get.docker.com/ | sh

sudo usermod -G docker ubuntu
newgrp docker

sudo curl -L git.io/weave -o /usr/local/bin/weave
sudo chmod a+x /usr/local/bin/weave

weave launch
weave launch-dns --ttl=9 --domain='stellaverse.srv.'
weave launch-proxy
eval $(weave proxy-env)

docker run -d --name Hello -h hello.stellaverse.srv stellaverse/hello
docker run -d --name Proxy -p 3333:3333 -h proxy.stellaverse.srv stellaverse/hello
````

After ssh'ing into the instance and waiting for things to settle...
````
$ sudo weave ps
weave:expose a6:45:ee:1d:b2:70
d5cfc1a13459 a2:89:6a:fc:78:94 10.128.0.3/10
eef06764ee1f 5a:ce:a3:8e:6b:45 10.128.0.2/10
92a58059190d f6:18:19:3c:32:d8 10.128.0.1/10
d74d34b4d489 5a:3c:c1:53:a7:14
$ sudo docker exec Hello ping proxy
PING proxy.stellaverse.srv (10.128.0.3) 56(84) bytes of data.
64 bytes from proxy.stellaverse.srv (10.128.0.3): icmp_seq=1 ttl=64 time=0.061 ms
...
$ sudo docker exec Proxy ping hello
PING hello.stellaverse.srv (10.128.0.2) 56(84) bytes of data.
64 bytes from hello.stellaverse.srv (10.128.0.2): icmp_seq=1 ttl=64 time=0.028 ms
...
````

**Comment by Stellaverse** [comment]
Maybe it has something to do with the `docker login`?

**Comment by rade** [comment]
> Maybe it has something to do with the `docker login`? Try running it with logging in to your Dockerhub account and see if that throws it off.

Nope, works fine for me even then.

**Comment by rade** [comment]
btw, it seems a bit unusual to launch weave and containers from a `User-Data` script. These scripts only execute on *first* boot. So if you stop and start a VM then they won't run.

**Comment by Stellaverse** [comment]
I would think this is a commonplace way to launch weave when working with an AWS Autoscaling Group. I don't restart a VM. They're either live or dead, there is no in-between.

I am working on implementing a restart policy for the *containers* on any given instance, but when the cluster auto-scales the underlying instance resources then how else would I go about launching `weave` on the new instances if now using `User-Data`?

The reasoning why the *containers* themselves are also launched using `User-Data` is because I haven't found a scheduler that does this better with less complexity.

It feels a bit like cold-war era technology, but it works.

**Comment by rade** [comment]
> I would think this is a commonplace way to launch weave when working with an AWS Autoscaling Group. I don't restart a VM. They're either live or dead, there is no in-between.

ok. fair enough.

Anyway, I am stuck here; I cannot reproduce the symptoms you were seeing.
