### ISSUE TITLE
iprange overlap error message could be clearer

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1034]
````
network 10.128.0.0/10 would overlap with route 10.128.0.0/16
Default -iprange 10.128.0.0/10 overlaps with existing route.
Please pick another range and set it on all hosts.
````

A user reports...

> Specifying -iprange and the dynamic aspects of weave was something I'd never touched yet.  Based on the error message, I had no idea where the 10.128.x route came from - so it seemed like this was some internal weave thing.  As my boxes are all set up by ansible scripts I had no reason to believe this box had anything special on it. Perhaps this error message could suggest to check out existing routes on the system, or link to a URL that could offer more advice.

**Comment by bboreham** [comment]
Recommending somewhere to look for more advice seems like a good idea.  However, embedding specific URLs inside executables is likely to rot over time.

Maybe something along the lines of "look in the docs, in section [iprange]" ?

**Comment by rade** [comment]
The only change would make is "existing route" -> "existing route on the host".

One would hope that googling for `weave iprange` would produce some useful links. Though it looks like the docs link is only #3.
