### ISSUE TITLE
All log messages should go to stderr

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1039]
Currently, in the router and nameserver containers, Debug, Info and Warning messages go to stdout while Error and Fatal messages go to stderr.

This is unexpected for some people, and not really compatible with the off-the-shelf libraries considered in #664.

So we should just send all log messages to stderr.

**Comment by rade** [comment]
> This is unexpected for some people

Like who?

**Comment by bboreham** [comment]
@dpw, @peterbourgon
