### ISSUE TITLE
pass common `weave launch` parameters to all components

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1043]
Following #1009, three containers are started with one command.  I found it a bit surprising that extra arguments only get passed to the router, not to weavedns or proxy.

Currently, `-debug` seems to be the only one that would require this treatment, though fixing #329 would introduce another flag that needs to go to weavedns.

**Comment by rade** [comment]
it's not clear what you mean by `extra` here. We option parser complains about undefined parameters, which is reasonable. So we cannot just pass all parameters to all three containers.

We can make an exception for *common* parameters. The description of this issue should reflect that.

**Comment by rade** [comment]
Let's tackle this post #329, since log levels is the *only* common parameter.
