### ISSUE TITLE
Clarify weaveDNS behaviour around --hostname

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1046]
The docs don't sufficiently draw attention to the fact that `--hostname` disables registration unless the specified FQDN is in the `weave.local` domain.

**Comment by rade** [comment]
Has this been an issue for one of our users?

**Comment by awh** [comment]
> Has this been an issue for one of our users?

https://botbot.me/freenode/weavenetwork/2015-06-29/?msg=43180216
