### ISSUE TITLE
Retain IP address for container across restart

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1047]
[from IRC](https://botbot.me/freenode/weavenetwork/2015-06-29/?msg=43178991&page=1)

If you use `docker restart` then weave should arrange that the container retains its IP 
address.

(Note that [restart](https://docs.docker.com/docker/reference/api/docker_remote_api_v1.14/#restart-a-container) is indeed a Docker daemon command)

This could be viewed as a sub-case of #599, IP address mobility.

**Comment by rade** [comment]
Surely that's more of an IPAM issue. We free the IP when the container dies, which it does as part of restart. If it wasn't for that then this would "just work", since IPAM for a specific container & network will hand back the same address if called repeatedly.

So if we really want this feature (use case?) then IPAM needs to distinguish restarts from deaths.

Or was the idea somehow that the proxy would intercept the restart and tell IPAM to ignore the container death that follows?

**Comment by bboreham** [comment]
Yes, the proxy sees the restart command and hence could know what to do.

**Comment by rade** [comment]
IPAM cannot detect restarts from the event stream?

**Comment by rade** [comment]
Surely we should also file an issue for doing this when the container is restarted by a restart policy.

**Comment by bboreham** [comment]
If the container is restarted without weave being involved, then we can't attach an interface to the weave network.  Which is certainly an issue, but probably not this issue.

That leaves the proxy, already discussed, and the `weave` script, which doesn't have a restart command.

**Comment by bboreham** [comment]
There is a `restart` event. 

According to [this blog](http://gliderlabs.com/blog/2015/04/14/docker-events-explained/) it comes after the die and start events.

**Comment by rade** [comment]
yes, I saw. How very useful.

**Comment by bboreham** [comment]
Restoring the network interface on daemon-controlled restart is captured as #401

**Comment by rade** [comment]
> the `weave` script, which doesn't have a restart command.

Hmm. So how do we make this work for containers started with `weave run`? I suppose we could decide not to bother. Just as we didn't with #400.

And what happens when containers have been attached to weave with `weave attach`? See #688.

**Comment by bboreham** [comment]
Referencing the similar Docker issue https://github.com/docker/docker/issues/2801
