### ISSUE TITLE
Weave Docker API Proxy may broaden the set of users that can call Docker

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1055]
In the default configuration of Docker, starting the weave proxy (as root) moves you from a situation where you must be root to call docker to one where any user can call docker via the proxy's TCP address.

We should warn users of this potential weakening of security, and perhaps not listen on TCP by default.

**Comment by rade** [comment]
> We should warn users of this potential weakening of security, and perhaps not listen on TCP by default.

Ideally we would make the choice where to listen - unix socket, tcp or tls - based on how the user is talking to docker.

**Comment by bboreham** [comment]
How would that work?  You can't rely on root having the same `$DOCKER_HOST` setting an ordinary user would have.

**Comment by rade** [comment]
> How would that work? You can't rely on root having the same `$DOCKER_HOST` setting an ordinary user would have.

We can determine the DOCKER_HOST setting the weave script is getting invoked with. In fact we already do that.

Provided users launch weave as the same user as they execute `docker ...` then that has the desired effect.

**Comment by paulbellamy** [comment]
The `$DOCKER_HOST` may not match up with where the docker daemon is listening (e.g. `DOCKER_HOST=tcp://docker.mysite.com:2375`).

Most reliable way (but also a bit ugly) would be to read `/proc/<pid>/cmdline` of the docker daemon, and default to those arguments for the proxy (which would include tls, etc).

**Comment by rade** [comment]
> Most reliable way (but also a bit ugly) would be to read /proc/<pid>/cmdline of the docker daemon, 

The daemon also pays attention to `DOCKER_HOST`. Though I suspect using that to configure the daemon would be unusual.

**Comment by paulbellamy** [comment]
Could read `/proc/<pid>/environ` as well, but also quite ugly. (and depends on the host OS, possibly?).

Is a user using a different `DOCKER_HOST` on the client (i.e. with DNS) common enough (or important enough) to justify this? The other upside is it would make setting up the proxy with TLS totally automatic.

**Comment by rade** [comment]
> Is a user using a different DOCKER_HOST on the client (i.e. with DNS) common enough?

DNS perhaps not, but NAT yes.

**Comment by paulbellamy** [comment]
The whole parsing docker's cli flags won't quite work, either. Because if docker is configured to listen on a given port/socket, then of course that port is occupied and we must choose another, anyway. Feels a bit scary to auto-configure stuff that is related to security.

Perhaps the better solution is to default to only listening on `unix:///var/run/weave.sock`, and if the user wants to listen on TCP they have to pass the `-H` options.

**Comment by paulbellamy** [comment]
per f2f discussion w/ @rade:
Only listening on unix socket by default makes dev setup harder.
We'll check the docker args for any hosts it's listening on, but always use port 12375.
Any unix sockets will undergo `s/docker/weave/g`.

**Comment by bboreham** [comment]
How does this help to address the original subject of this issue?

**Comment by paulbellamy** [comment]
It means that the proxy will default listen on the same interfaces as the docker daemon, so won't listen on new interfaces. Or, if the daemon is only listening on a socket, then the proxy will only listen on a socket by default.
