### ISSUE TITLE
Proxy should not swallow any messages that weave sends to stderr

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1056]
The weave script may emit warnings or errors as it goes about its business, e.g. attaching a new container to the weave network.  Currently it seems these messages are swallowed.

At minimum they should go in the weaveproxy log.

Injecting them as output to be presented by the `docker` cli might be attractive, but potentially dangerous for users that are expecting very specific output from their containers.

Where should they go for clients that call via the Docker remote API?

**Comment by rade** [comment]
> Injecting them as output to be presented by the `docker cli` might be attractive, but potentially dangerous for users that are expecting very specific output from their containers.

Agreed; let's just put them in the logs.
