### ISSUE TITLE
fetch packages from github instead of google code

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/weave#1059]
Google Code is shutting down, and http://code.google.com/p/gopacket redirects to https://github.com/google/gopacket, so it's probably a good idea to update our imports.

**Comment by rade** [comment]
Same applies to go-bit and go.crypto.

**Comment by rade** [comment]
[go.crypto gh mirror](https://github.com/golang/crypto)

I cannot find a gh mirror for go-bit :( though there are a bunch of alternative implementations on gh.

**Comment by inercia** [comment]
Yes, I was having the same problem with go-bit. Is [this](https://github.com/andybalholm/go-bit) the same?

**Comment by rade** [comment]
> Is [this](https://github.com/andybalholm/go-bit) the same?

Looks like it.

**Comment by inercia** [comment]
It seems we have to use the crypto from `golang.org/x/crypto`...

**Comment by rade** [comment]
This issue rather failed to identify the problem, namely that the gopacket move actually breaks the build. Hence we now have #1060, since we need to fix that on the 1.0 branch, not just master.
