### ISSUE TITLE
Use request accept header to distinguish json status

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1063]
...instead of having a `status-json` url path.

**Comment by rade** [comment]
@tomwilkie @squaremo Are we ok with just matching on `.Header(“Accept”, “application/json”)`, or do we want full-blown content negotiation? Which is [hard in go](http://www.schwertly.com/2014/10/hacker-school-day-11-content-negotiation-validation-json-ttls-ugly-commits/).

**Comment by rade** [comment]
> Are we ok with just matching on `.Headers(“Accept”, “application/json”)`

**Comment by tomwilkie** [comment]
Yes I think that sufficient.  We're not expecting browsers to hit this endpoint, so full content negotiation is probably not required.

**Comment by bboreham** [comment]
The JSON endpoint was specifically written for my browser to hit.  Could you expand on what other use-cases you had in mind?

**Comment by tomwilkie** [comment]
Your browser, or an app running in your browser?

**Comment by bboreham** [comment]
Javascript running in my browser.

**Comment by tomwilkie** [comment]
The javascript has control over the headers it sends, and therefore can request json if it wants it.
