### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#107]
This seems to be where my work comes to a close tonight.  
Any ideas on how to resolve this would be appreciated.  

Thanks,
-- Hugh 

root@dessalines002:~# docker pull zettio/weave  
Pulling repository zettio/weave
ddda7b1679e2: Download complete 
c05861146876: Download complete 
   .  .  .  etc.,  .  .  .  
5e0cc65ed8cd: Download complete 
2014/10/08 19:42:53 unexpected end of JSON input

root@dessalines002:~# docker images | grep weave
zettio/weave                         git-3a9b61140086    7eade3e898cd        12 days ago         10.9 MB
zettio/weave                         latest              7eade3e898cd        12 days ago         10.9 MB
zettio/weave                         git-ada941cfcb74    ddda7b1679e2        2 weeks ago         10.9 MB
zettio/weave                         git-025315363d5e    c05861146876        2 weeks ago         10.9 MB
zettio/weave                         git-e53c54efa046    624fd20dbba4        2 weeks ago         10.82 MB
zettio/weave                         git-b5df59660fe8    19fc37fe6e3c        2 weeks ago         10.9 MB
zettio/weave                         git-33e60b75bcd4    76df37e350a8        2 weeks ago         10.9 MB

root@dessalines002:~# /usr/local/bin/weave launch 10.0.0.2/16 68.168.146.147 68.168.146.149 68.168.146.150 
2014/10/08 19:43:18 Error response from daemon: unexpected end of JSON input

**Comment by pctj101** [comment]
Here's my resolution:

sh-4.2# cd /var/lib/docker/

sh-4.2# ls -al
total 16
drwx------ 1 root root   154 Feb  9 02:28 .
drwxr-xr-x 1 root root   186 Jan 16 12:43 ..
drwx------ 1 root root    20 Jan 16 12:41 btrfs
drwx------ 1 root root   128 Feb  9 02:28 containers
drwx------ 1 root root    12 Jan 16 12:40 execdriver
drwx------ 1 root root 30216 Feb  5 09:03 graph
drwx------ 1 root root    32 Jan 16 12:40 init
-rw-r--r-- 1 root root 13312 Feb  9 02:28 linkgraph.db
-rw------- 1 root root     0 Feb  9 01:57 repositories-btrfs  # Note zero length file
drwx------ 1 root root   168 Jan 29 12:22 tmp
drwx------ 1 root root     0 Feb  9 04:13 vfs
drwx------ 1 root root   136 Jan 16 12:58 volumes

sh-4.2# rm repositories-btrfs

Normally repositories-btrfs contains:
{"Repositories":{}}
