### ISSUE TITLE
Latest public docs should be built from the release branch

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1078]
Now that we have release branches there is no need for the `latest_release_doc_updates` branch to exist.

**Comment by rade** [comment]
That is not true. `latest_release_doc_updates` contains doc updates for the *currently released* version. Release branches hold commits for the *next to be released* version.

**Comment by errordeveloper** [comment]
The workflow for the `latest_release_doc_updates` branch is crazy and take some explaining, for example it's different how you work with it when you first committing a docs change after a new release vs if you are committing on top of another docs change that had been made. The reason for this awkward workflow to come about was due to non-existance of release branches at the time, but now release branches exist and the docs workflow can be streamlined.

**Comment by errordeveloper** [comment]
> `latest_release_doc_updates` contains doc updates for the currently released version. Release branches hold commits for the next to be released version.

Ok, so a streamlined workflow would be such where only docs changes are merged into an upstream release branch before patch level version update comes along. However practically there shouldn't be any significant difference as no new features or functional changes are supposed to appear with patch level version updates.

**Comment by rade** [comment]
> practically there shouldn't be any significant difference as no new features or functional changes are supposed to appear with patch level version updates.

That is true. And indeed right now there is no difference in the docs between `latest_release_doc_updates` and `1.0`.

So I guess yes we could indeed abandon `latest_release_doc_updates`.

I am not quite sure what you are proposing though. By what magic would the the web site deployment logic know what the 'current' release branch is?

**Comment by rade** [comment]
> > practically there shouldn't be any significant difference as no new features or functional changes are supposed to appear with patch level version updates.
>
> That is true.

Except it isn't :( See #1124 for a counter example.

**Comment by awh** [comment]
Related to #1700.

**Comment by rade** [comment]
@awh Haven't we effectively got this now?

**Comment by awh** [comment]
Yes. We had the same discussion in #1700 regarding doc changes on the release branch going live immediately, and concluded that counter examples happen so infrequently we would handle them as a special case (e.g. by merging just before the release, or splitting the docs into a separate PR and merging that just after the release) => closing.
