### ISSUE TITLE
returning multiple A records

### ISSUE THREAD

**Issue by bmurphy1976** [weaveworks/weave#1091]
Our load balancers use A records wired into our dns service to distribute load across multiple machines.  As the machines go up and down our A records change and our load balancers reconfigure themselves to match our DNS records.

We cannot use this scheme today with weave dns because weave dns only returns a single A record even though there may be multiple addresses associated with that record.

More tradition DNS servers usually return multiple ip addresses in a randomized order instead of only returning a single IP address.

Are there plans in the future to support returning multiple A records when they exist?  Perhaps a flag passed to weave-dns to change the behavior.

**Comment by rade** [comment]
dup of #733.

**Comment by tomwilkie** [comment]
Hi Brya - thanks for the feedback!  We're actively work on this right now - checkout #1065

**Comment by bmurphy1976** [comment]
Thanks.  I saws the other links but had trouble finding them in search initially.  I'll keep my eye on #1065.
