### ISSUE TITLE
Smoke tests should not use ':latest' Weave images

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1100]
The Makefile generates images such as `weaveworks/weave:latest`; the smoke-tests run them.  But if you have not succeeded in building images then docker will download the 'latest' images from DockerHub, thus giving a misleading impression.

I suggest that the makefile and smoke-tests default to a different tag, such as `:dev`, which is never uploaded to DockerHub.

**Comment by bboreham** [comment]
I just hit this again.

**Comment by rade** [comment]
*how* are you hitting this? "not succeeding in building the images" is an error, so why do things progress beyond that?

**Comment by bboreham** [comment]
In our CircleCI config, the build is specified as a 'test', and CircleCI always runs all tests.

It's unclear from [the docs](https://circleci.com/docs/configuration) whether moving the build to 'pre' the tests would give the desired effect, or if we should do the build in 'dependencies', or something else.

**Comment by bboreham** [comment]
We had another instance of this at https://circleci.com/gh/weaveworks/weave/6142 where the build did succeed but part of the upload to aws failed, and it went ahead and pulled the `latest` images and confused everyone.

**Comment by bboreham** [comment]
The earliest indication of the problem is when the test script runs `weave version`:

```
# weave version
weave script (unreleased version)
Unable to find image 'weaveworks/weaveexec:latest' locally
latest: Pulling from weaveworks/weaveexec
Digest: sha256:935949603fcc38ed5f1559cc768bd5f74ddddad2835859b3838653f530f9d225
Status: Downloaded newer image for weaveworks/weaveexec:latest
Unable to find weaveworks/weave:latest image.
flag provided but not defined: -test.coverprofile
See '/home/weave/weaveproxy --help'.
Unable to find weaveworks/plugin:latest image.
```

Maybe we could have `weave version` return a failure status if it cannot find all components?

**Comment by bboreham** [comment]
I added a check that `weaveworks/weave:latest` exists in 73d7812dc520b406de1caf639cef321346b2f60c

**Comment by bboreham** [comment]
Also made the `setup.sh` script fail if a sub-task failed 37f820a168f38fab47cda39023533f9671ce33f8

**Comment by rade** [comment]
Is there anything left to do here?

**Comment by bboreham** [comment]
Closing on the basis that the main failure modes are covered.
