### ISSUE TITLE
Provide upgrade guidance

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1102]
The current release notes are quite overwhelming for users who merely want to upgrade their installation to the latest version of weave and have it Just Work As Before. Such users would benefit from upgrade guidance, which could range from a simple 'No changes in default behaviour from previous version; upgrade via rolling restart' to dealing with protocol version incompatibility and changed defaults.

**Comment by rade** [comment]
> Such users would benefit from upgrade guidance, which could range from a simple 'No changes in default behaviour from previous version; upgrade via rolling restart' to dealing with protocol version incompatibility and changed defaults.

That's something that would go into the release notes. We don't need an issue for it. Except perhaps to document the requirement in the release process?

The other thing we could do is write *generic* upgrade documentation, e.g. explain in more detail how to perform a rolling and non-rolling upgrade.

**Comment by awh** [comment]
CC @abuehrle
