### ISSUE TITLE
Investigate if its safe to reuse request for recursive DNS 

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1113]
I'm not sure you can just send the same request we get from the client to the upstream server. This could lead to a conflict if two clients send a request with the same message ID. I would make a copy...

**Comment by tomwilkie** [comment]
Just checked the dns code, and we should be making a copy and giving it a fresh id.  We can use dns.Id() to generate fresh ids.

**Comment by rade** [comment]
What would the user-visible impact of an ID clash be?

**Comment by tomwilkie** [comment]
If two clients happened to send requests to us with the same id but for different domains, and we sent the request upstream as is, there is a chance we might mix up the replies from upstream and send the wrong reply back to the wrong client.

**Comment by rade** [comment]
@tomwilkie AFAICT the DNS code does not correlate replies by ID. A fresh UDP/TCP "connection" is established for every request, so correlation happens by virtue of receiving replies on distinct ephemeral ports. The library [checks that the reply ID matches the request](https://github.com/miekg/dns/blob/a7f8fcc762bcdbf4da9dbb62c572fbd3c3d0eca2/client.go#L205) but only to error when it doesn't.
