### ISSUE TITLE
"IP Allocator with different subnet detected" error could be more helpful

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1128]
I just connected a weave 1.0 and weave-master and got the following in the latter's logs:
````
ERRO: 2015/07/14 09:15:10.658636 ->[192.168.48.11:6783|8e:70:be:57:9b:a5(host1)]: connection shutting down due to error: IP Allocator with different subnet detected
````
which would be a lot more helpful if it a) told me what the ranges were (both ours and theirs), and b) how to fix it (i.e. supply `--ipalloc-range`).

The latter might be a bit tricky, since we don't really want `ring.go`, where that error arises, to have to know about command line options.

**Comment by rade** [comment]
> told me what the ranges were

ideally in the same CIDR notation that one supplies to `--ipalloc-range`.

**Comment by bboreham** [comment]
What do you think to having the error message template passed in to `Allocator` at creation time?

Seems a bit weird, but it would keep the concerns in the right place.
