### ISSUE TITLE
unit-test mock router GossipBroadcast() is wrong

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1148]
The [implementation](https://github.com/weaveworks/weave/blob/89ad7e1ba210a2db3b093ac8a50acd830d4360af/testing/gossip/mocks.go#L124) of `GossipBroadcast()` causes every client to broadcast, not just the one that asked to broadcast.

**Comment by tomwilkie** [comment]
It also occurred to me recently, instead of dropping the messages when the channels are full, we should merge into a buffer.

**Comment by bboreham** [comment]
Related to your comment: https://github.com/weaveworks/weave/pull/1017

**Comment by bboreham** [comment]
Actually this bug report is total crap.
