### ISSUE TITLE
IPAM rejects updates with large clock skew, but it doesn't really care about the clock, whereas DNS doesn't and does

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1156]
This is a hold-over from when we had tombstones.

**Comment by rade** [comment]
Shouldn't gossipdns need this instead? Since it has tombstones that are timestamps.

**Comment by tomwilkie** [comment]
Yes please!

**Comment by tomwilkie** [comment]
After discussion with @rade, we're going to leave the timestamp in IPAM gossips (for backwards compatibility) and the check in IPAM, as we're going to need it in the future when we reintroduce tombstones to tackle ring fragmentation.
