### ISSUE TITLE
Running weave without docker

### ISSUE THREAD

**Issue by baopx** [weaveworks/weave#1160]
Is it possible to have a client join a weave network without installing docker?  (i.e, can the weave router code be run outside of docker?)
I understand that the wave router is running as a docker container, and this container is is capturing packets from the weave bridge and forward to the peer weave router.  I want to find a way to run weave without involving docker.  That leads to the next question.

Is it possible to weave on a Mac?  (https://github.com/weaveworks/weave/issues/214)  From issue #214, I see that it is possible through boot2docker and port forwarding through Virtual Box.  Is there an alternative to boot2docker/vagrant to run weave on Mac?

My goal is to be able to add my Mac machine to a weave network.  I will not be running any docker container on the Mac client.  I should be able to ping a container running on a remote host from the Mac client.  Appreciate any help or pointers, thanks.

Bao

**Comment by bboreham** [comment]
There is nothing in the core implementation of weave Net that is tied to Docker. However, all the user-interface that we ship is based on Docker. So, if you go through the same, or equivalent, actions that we do, outside of Docker, then it should work fine. 

We do make many more assumptions that the OS is Linux. Probably there are close parallels on OSX, but porting everything would take more effort. 

I would note that, when you start with Docker, everything is isolated in its own network namespace, and linking everything together takes particular effort. If you have just one extra machine to connect, you may be able to do everything you want by adding IP routing rules on the Mac side and the Linux side.
