### ISSUE TITLE
weave attach non zero exit code on success

### ISSUE THREAD

**Issue by anandkumarpatel** [weaveworks/weave#1161]
if a command run with `docker --rm` fails to remove the container after a successful run docker will return a non-zero exit.
when using weave attach I frequently see 
```
Error removing intermediate container 9b63e9a1e9bf: Driver aufs failed to remove root filesystem 9b63e9a1e9bf1aaa97d943b4c082eaa152e38d55bf1884bc28d88de1cc891f1a: rename /docker/aufs/mnt/9b63e9a1e9bf1aaa97d943b4c082eaa152e38d55bf1884bc28d88de1cc891f1a /docker/aufs/mnt/9b63e9a1e9bf1aaa97d943b4c082eaa152e38d55bf1884bc28d88de1cc891f1a-removing: device or resource busy
```
and the command return non-zero so our tools think the command failed, however the attach actually did go through.
the above error was coming from this line due to the `--rm` bug
https://github.com/weaveworks/weave/blob/master/weave#L74

docker issue https://github.com/docker/docker/issues/9665#issuecomment-121759275

info
```
root@zapdos:/home/zapdos#  sudo weave version
weave script 0.11.1
weave router 0.11.1
weave DNS 0.11.1
weave exec 0.11.1
```
```
root@zapdos:/home/zapdos# docker -D version && docker -D info
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64
Containers: 650
Images: 8317
Storage Driver: aufs
 Root Dir: /docker/aufs
 Backing Filesystem: extfs
 Dirs: 9626
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-29-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 32
Total Memory: 58.81 GiB
Name: zapdos 
ID: HHHH:IIII:MRNF:OYNJ:FZNT:X4EA:ZWQR:TF7G:EEEE:HSP6:RYBS:F3ER
Debug mode (server): false
Debug mode (client): true
Fds: 1111
Goroutines: 3753
System Time: Wed Jul 15 18:54:22 UTC 2015
EventsListeners: 1
Init SHA1: 11117501111dbf64c1111c27861111027c
Init Path: /usr/bin/docker
Docker Root Dir: /docker
WARNING: No swap limit support
```

**Comment by rade** [comment]
As you discovered already; this is a docker bug. I can't see what we can do about this. Any suggestions?

**Comment by rade** [comment]
I suggest upgrading to Docker 1.7 though.

**Comment by anandkumarpatel** [comment]
the only suggestion I have would be to do a string search on the output (this is the workaround we are currently doing). Not sure if that is something weave would want in its logic. I can make a PR for it if this is something you want. I filed this in case other people run into the same issue.

**Comment by rade** [comment]
> the only suggestion I have would be to do a string search on the output

That's horrible, especially since users may expect the stdout and stderr come to contain output from the container, so you'd somehow have to *remove* the error message.

Are you definitely seeing this in the latest 1.7.1 Docker release? Also, have you tried different storage backends than aufs?
