### ISSUE TITLE
make CircleCI more frugal on shard & VM usage

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1169]
Most of our smoke tests only require one VM. Some two, and an even smaller number need three. Yet our CI setup creates a total of 4 shards x 3 VMs = 12 VMs per test run. We could get away with a lot less if our CircleCI scheduler knew how many VMs are needed by particular tests, and got smarter about the scheduling as a result, e.g. perhaps have one shard with 3 VMs, one with 2 and two with 1.

We could suffix the test file name with `-2`, `-3`, e.g. `100_cross_host_tests-2.sh`. (I'd keep `-1` optional, since it's the common case.

**Comment by tomwilkie** [comment]
I would go even further; we shouldn't scale the test run by the number of circle shards, but rather run the tests in parallel on a single shard, and point them at different sets of VMs.  Circle shards are expensive and a fixed costs, whereas the VMs are a cheap, variable cost.  This would allow us to make the tests faster by throwing more VMs at them, and have more concurrent builds on circle.
