### ISSUE TITLE
Expose weave network to docker inspect

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#117]
I believe that the zettio-weave project needs to sort out how to use its run, attach and detach subcommands to inject and maintain  information about the weave bridge into the docker inspect <container> output.

https://github.com/hesco/hesco-weave#to-do-tasks-for-other-projects

**Comment by rade** [comment]
Container labels, introduced in docker 1.6, allow us to add weave IPs to container meta data. But only on container creation, since, unlike https://github.com/docker/docker/pull/9013, they can only be set then and are immutable.

A weave docker network plugins might also give us this functionality, depending on what, if anything, gets placed into the container metadata by the network plugin mechanism.

**Comment by bboreham** [comment]
A user (via IRC) tells us they do the 'docker-uses-weave-bridge' thing to get the weave IP to show up in `docker inspect`.
Unfortunately that takes the user into territory we don't test for...

**Comment by rade** [comment]
> A user (via IRC) tells us they do the 'docker-uses-weave-bridge' thing to get the weave IP to show up in `docker inspect`.

Did they say *why* they are doing that? In particular, why would `weave ps` not work for them?

**Comment by bboreham** [comment]
They mentioned Consul configurator using the `docker inspect` API.

**Comment by rade** [comment]
> They mentioned "configurator+consul" using the `docker inspect` API.

Hmm. Can't see it in the code, though I didn't look very hard.

If true I suspect these would work only if the weave IP *replaced* the docker IP in the result of `docker inspect`. @progrium is that true?

**Comment by enxebre** [comment]
Hi there, Similar probem here. I am using registrator for storing the container (weave) ips into consul. When using the weave bridge as the default docker bridge it just work as expected but as per https://github.com/gliderlabs/registrator/blob/583c5bd34a15c2c90448b26a3cf17188691c0cbc/bridge/util.go#L72 it won't work when weave generating ethw as container.NetworkSettings.IPAddress still will be the docker0 brdige ip.
