### ISSUE TITLE
"Received invalid state update!" error could be more helpful

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1178]
Start weave on two hosts, then connect them (breaking the rules on initpeercount):

````
host1$ sudo weave launch-router
host1$ sudo weave run -ti ubuntu
host2$ sudo weave launch-router
host2$ sudo weave run -ti ubuntu
host1$ sudo weave connect host2
````

weave logs:

````
INFO: 2015/07/17 11:01:41.893191 ->[192.168.48.11:6783|3e:b0:2f:de:5e:da(host1)]: connection added (new peer)
ERRO: 2015/07/17 11:01:41.894079 ->[192.168.48.11:6783|3e:b0:2f:de:5e:da(host1)]: connection shutting down due to error: Received invalid state update!
````

Related: https://github.com/weaveworks/weave/issues/760#issuecomment-119629652 - the message there is different but similarly unhelpful

**Comment by inercia** [comment]
In addition, it seems there is a memory leak that in the router when all these connections fail with the _"Received invalid state update!"_ error. The router took more than 1,5Gb in my Vagrant before it was killed...

**Comment by rade** [comment]
> it seems there is a memory leak

@inercia Do you see that with the exact same steps that @bboreham posted?

**Comment by inercia** [comment]
@rade Basically the same steps, while testing Discovery in my Vagrants. If I launch the router [with no -initpeercount](https://github.com/weaveworks/discovery/pull/1/files#diff-c8fdb9b64895d2121d9192e4eb72b17bR29), Discovery [sends `/connect`](https://github.com/weaveworks/discovery/pull/1/files#diff-b515b5521b68142eb7d8fe0406ef78b4R43)s  to the router, so I think it is basically the same (maybe the only different would be that `connects` would be in random order)

**Comment by rade** [comment]
Hmm. Running @bboreham's example I too see a steady memory growth. So this is rather more serious then. Please file a separate bug.
