### ISSUE TITLE
container fails to start with "[8] System error: Unit docker-<id>.scope already exists."

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#1207]
Found in https://github.com/weaveworks/weave/issues/1188

Not sure if it happens at all without the proxy. It's intermittent, so possibly a race condition.

Reproducible with:
```bash
#! /bin/bash

. ./config.sh

start_suite "Stress test container restarts"

weave_on $HOST1 launch --log-level debug

# 2 containers on each host, all with the same names
proxy docker_on $HOST1 run -dti --name=foo $SMALL_IMAGE /bin/sh
proxy docker_on $HOST1 run -dti --name=bar $SMALL_IMAGE /bin/sh

# now stop and start the containers a bunch of times
for i in $(seq 50); do
  proxy docker_on $HOST1 restart foo 1>/dev/null
  proxy docker_on $HOST1 inspect --format="{{.State.Running}}" foo | grep true 1>/dev/null
  proxy docker_on $HOST1 restart bar 1>/dev/null
  proxy docker_on $HOST1 inspect --format="{{.State.Running}}" bar | grep true 1>/dev/null
done

end_suite
```

**Comment by paulbellamy** [comment]
This goes away with docker 1.8, so probably be worth leaving.

**Comment by rade** [comment]
> This goes away with docker 1.8

says who?

**Comment by rade** [comment]
> says who?

Is your assertion based on the fact that a) https://github.com/docker/libcontainer/pull/617/files has been merged, and b) a version containing that merge has been vendored into docker?

**Comment by rade** [comment]
I would be *much* happier to leave this alone if we were able to reproduce it w/o the proxy.

**Comment by paulbellamy** [comment]
yes, and c) with that version I'm unable to reproduce the failure.
