### ISSUE TITLE
weave launch terminates with error on PPC machine

### ISSUE THREAD

**Issue by sberajaw** [weaveworks/weave#1208]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8]

goroutine 16 [running]:
github_com_docker_libcontainer_stacktrace.NewFrame
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/stacktrace/frame.go:12
github_com_docker_libcontainer_stacktrace.Capture
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/stacktrace/capture.go:18
libcontainer.newSystemError
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/generic_error.go:48
libcontainer.$nested4
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/factory_linux.go:212
github_com_docker_libcontainer.StartInitialization.pN43_github_com_docker_libcontainer.LinuxFactory
	/go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/factory_linux.go:224
native.initializer
	/go/src/github.com/docker/docker/daemon/execdriver/native/init.go:35
github_com_docker_docker_pkg_reexec.Init
	/go/src/github.com/docker/docker/pkg/reexec/reexec.go:26
main.main
	/go/src/github.com/docker/docker/docker/docker.go:29
created by main
	../../../src/libgo/runtime/go-main.c:42

goroutine 18 [finalizer wait]:
created by runtime_createfing
	../../../src/libgo/runtime/mgc0.c:2572

goroutine 19 [syscall]:
	goroutine in C code; stack unavailable
created by os_signal..import
	../../../src/libgo/go/os/signal/signal_unix.go:25

The weaveworks/weaveexec:latest image seems to have been downloaded but no container created from it. In fact, every weave command fails with this same error. This is being seen on 2 Power machines. Is weave not support on Power?

Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-24-generic ppc64le)

**Comment by squaremo** [comment]
> Is weave not support on Power?

The official images aren't compiled for ppc, no. It's not clear if Docker is crashing when it tries to run the weaveexec entrypoint or at some other time. Can you run other containers?

If you have the go toolchain set up on your machines, you might try compiling the images yourself -- I don't have much of an idea how difficult this is, I'm afraid, but e.g., https://medium.com/@ALGrendel/docker-weave-a-little-cloud-and-a-raspberry-pi-381f73a4376d (Docker and Weave on ARM) may give you an idea.

**Comment by dpw** [comment]
golang on POWER still means gccgo, right? I've never heard of anyone trying weave built with gccgo.

**Comment by sberajaw** [comment]
@squaremo, yes, I can run many other containers. I could also run weave successfully on a third machine that's intel.

@dpw, yes I believe so. Running on POWER is a must, but with the number of containers that we are running, having a technology like weave would be a huge help.

Any guidance is much appreciated.

**Comment by sberajaw** [comment]
@squaremo, sorry, let me add a bit more detail. We can run docker containers in this env. if we rebuild any docker images that we use on top of base image we've created. Sorry, didn't realize this before with this being the reason why we can run other containers in this env. So, running on POWER is certainly not straightforward.

**Comment by sberajaw** [comment]
Thank you for the timely attention to this issue. 

I suppose this "issue" is not really an issue. Call this an enhancement request for first class support for the Power architecture in addition to Intel. I think with the momentum around Spark/Hadoop/HPC in general and the arguably superior performance of the Power architecture for these workloads, I think this should push technologies like Weave even further.
