### ISSUE TITLE
FDP can't coexist with new DNS server

### ISSUE THREAD

**Issue by dpw** [weaveworks/weave#1215]
The new DNS server is integrated into the router, and binds to port 53.  FDP runs the router with `--net=host`, because it needs to perform ODP operations in the default netns.  Put them together, and the router container now tries to bind to port 53 in the default netns, and EADDRINUSE ensues.  So FDP is now likely to only work if you do `weave launch --no-dns`.

Either the DNS server needs to be run on some other port number, or it should be disentangled from the router and moved into its own container once again.  The latter seems preferable, in order to minimize the surface area of code run in a container with `--privileged --net=host`.

**Comment by rade** [comment]
> run on some other port number

It actually just needs to listen on a specific interface/ip, namely the docker bridge ip. That's what the port mappings in the script do, but they are ineffective when running with `--net=host`.

**Comment by tomwilkie** [comment]
We can add a new argument (--dns-listen-address or something) and have the weave script put the docker bridge ip in there.  Will that be enough?

**Comment by rade** [comment]
Why is this still open? I thought #1225 was meant to address this issue?

**Comment by tomwilkie** [comment]
#1225 mostly addresses the issue; @dpw will need to update the weave script in the FDP branch to launch with the new parameter.  I can do this if you like?

**Comment by rade** [comment]
I am quite sure @dpw considers this issue to be pertaining to the current weave code base only, i.e. making any changes to FDP is out of scope.
