### ISSUE TITLE
DNS only on the local node

### ISSUE THREAD

**Issue by Gingonic** [weaveworks/weave#1223]
Hi,

I'm pretty sure this is a installation specific bug, but I cannot explain it and google is no help. 
I have established a basic weave network with a fix IP range, every node has discoverd the other as the `weave status` states. The weave DNS and proxy are running, DOCKER_HOST is set. I can ping containre IP adresses from host A from host B. 

But the WeaveDNS does simply not update on host B if I start a container on host A. The DNS of A is playing along nicely. 

Any idea on what component could be the issue here?

**Comment by rade** [comment]
> But the WeaveDNS does simply not update on host B if I start a container on host A.

How did you determine that?

**Comment by Gingonic** [comment]
By viewing the logs in the weave DNS, Weave DNS got a new entry, B did not. But as I do not know the implementation details, I figured that it might be distributed, so I simply tried to call the hostname of the service A with a curl from inside a container running on host B. Could'nt find the host.

Same procedure with a container curling on host A did resolve the hostname to the weave container ip adress though.

**Comment by rade** [comment]
ok. please post the `weave status` and `weave ps` output from both hosts.

**Comment by Gingonic** [comment]
First : thanks for your support!

## Host A (called slave3)
`weave status`
```
weave router 1.0.1
Our name is ee:e1:61:90:35:a3(slave3.example.io)
Encryption off
Peer discovery on
Sniffing traffic on &{87 65535 ethwe 96:74:87:47:99:3c up|broadcast|multicast}
MACs:
Peers:
ee:e1:61:90:35:a3(slave3.example.io) (v5) (UID 7362424750674788684)
   -> 22:02:92:48:44:ca(slave4.example.io) [172.24.0.241:60043]
22:02:92:48:44:ca(slave4.example.io) (v2) (UID 12661760552124100544)
   -> ee:e1:61:90:35:a3(slave3.example.io) [172.24.0.238:6783]
Routes:
unicast:
22:02:92:48:44:ca -> 22:02:92:48:44:ca
ee:e1:61:90:35:a3 -> 00:00:00:00:00:00
broadcast:
22:02:92:48:44:ca -> []
ee:e1:61:90:35:a3 -> [22:02:92:48:44:ca]
Direct Peers:
Reconnects:

Allocator range [10.2.0.0-10.3.0.0)
Owned Ranges:
  10.2.0.0 -> ee:e1:61:90:35:a3 (slave3.example.io) (v6)
  10.2.128.0 -> 22:02:92:48:44:ca (slave4.example.io) (v3)
  10.2.255.255 -> ee:e1:61:90:35:a3 (slave3.example.io) (v0)
Allocator default subnet: 10.2.0.0/16

weave DNS 1.0.1
Listen address :53
Fallback DNS config &{[172.24.0.1] [] 53 1 5 2}

Local domain weave.local.
Interface &{91 65535 ethwe 42:ea:b2:8e:9c:3d up|broadcast|multicast}
Zone database:
8bf73be5ed43: my.test.weave.local.[10.2.0.2]


weave proxy is running
```
`weave ps`
```
weave:expose ee:e1:61:90:35:a3
8bf73be5ed43 f2:87:d6:64:bd:7c 10.2.0.2/16
2eb3bae9ae9a 42:ea:b2:8e:9c:3d 10.2.0.1/16
1e120e4868d3 96:74:87:47:99:3c
```

## Host B (called slave4)
`weave status`

```
weave router 1.0.1
Our name is 22:02:92:48:44:ca(slave4.example.io)
Encryption off
Peer discovery on
Sniffing traffic on &{13155 65535 ethwe 72:65:b2:28:c7:18 up|broadcast|multicast}
MACs:
Peers:
22:02:92:48:44:ca(slave4.example.io) (v2) (UID 12661760552124100544)
   -> ee:e1:61:90:35:a3(slave3.example.io) [172.24.0.238:6783]
ee:e1:61:90:35:a3(slave3.example.io) (v5) (UID 7362424750674788684)
   -> 22:02:92:48:44:ca(slave4.example.io) [172.24.0.241:60043]
Routes:
unicast:
22:02:92:48:44:ca -> 00:00:00:00:00:00
ee:e1:61:90:35:a3 -> ee:e1:61:90:35:a3
broadcast:
22:02:92:48:44:ca -> [ee:e1:61:90:35:a3]
ee:e1:61:90:35:a3 -> []
Direct Peers: 172.24.0.238
Reconnects:

Allocator range [10.2.0.0-10.3.0.0)
Owned Ranges:
  10.2.0.0 -> ee:e1:61:90:35:a3 (slave3.example.io) (v6)
  10.2.128.0 -> 22:02:92:48:44:ca (slave4.example.io) (v3)
  10.2.255.255 -> ee:e1:61:90:35:a3 (slave3.example.io) (v0)
Allocator default subnet: 10.2.0.0/16

weave DNS 1.0.1
Listen address :53
Fallback DNS config &{[172.24.0.1] [] 53 1 5 2}

Local domain weave.local.
Interface &{13159 65535 ethwe ea:d8:87:d1:96:5d up|broadcast|multicast}
Zone database:


weave proxy is running
```

`weave ps`
```
weave:expose 22:02:92:48:44:ca
5570412bfcd2 ea:d8:87:d1:96:5d 10.2.128.0/16
38770cfc3a46 72:65:b2:28:c7:18
``´

**Comment by rade** [comment]
So `ping my.test.weave.local` from inside a container on `slave4` fails?

If so, start dns with `weave launch-dns -debug` on both machines, run `docker logs -f weavedns` to tail the weavedns logs on both, then do the `ping -c 1 my.test.weave.local` test and post all the log entries that get generated as a result of doing that.

**Comment by Gingonic** [comment]
I'm confused. I did not touch the configuraiton today, Just to be sure I run the png again. I could ping/curl the domain name from the slave4. I still have the result of yesterdays ping in my shell, where it could not resolve it... Nothing was restart or changed, I didn't even start a new container.

I'll roll out the configuration onto the other nodes and test bit by bit if the behavior reoccurs. Right now I cannot explain why it suddenly works or why it did not before.

I'm very sorry to may be have wasted your time.

**Comment by Gingonic** [comment]
I could deploy the entire cluster. Seems it resolved itself... Sometimes magic is required. The again sorry for the time wasting and thanks for the support.

**Comment by rade** [comment]
You are welcome. Re-open this if the problem resurfaces.
