### ISSUE TITLE
Question: How many NICs are needed?

### ISSUE THREAD

**Issue by dalu** [weaveworks/weave#1226]
I've been reading Kubernetes docs and intro and weave is one of the network fabrics mentioned.

No matter which of those I view, one question remains open:

How many NICs does 1 server need for it to work and work in a secure way?

Because the only cheaper servers have 1 NIC and I end up creating an IPsec "local" network with those 1 NIC servers so they can talk to each other over an encrypted connection.

Does weave handle encryption and authentication?
Does it work with 1 NIC servers?

**Comment by errordeveloper** [comment]
> How many NICs does 1 server need for it to work and work in a secure way?

Please define what you mean by secure.

> Does weave handle encryption and authentication?

Yes, please read @awh's blog post about [crypto in Weave Net](http://blog.weave.works/2015/06/16/weave-net-cryptography-faq/).

> Does it work with 1 NIC servers?

Yes.

**Comment by dalu** [comment]
> Please define what you mean by secure.
No one without permission is to view or modify the communication content.

Thanks errordeveloper :)
Questions answered.
