### ISSUE TITLE
`weave launch` failed if `weave expose` was not undo with `weave hide`

### ISSUE THREAD

**Issue by baopx** [weaveworks/weave#1249]
This could be a work-flow issue rather a real bug... The following scenario will cause `weave launch` to fail.

`weave launch && weave expose && weave stop`
`weave launch`

network 10.128.0.0/10 would overlap with route 10.128.0.0/10
Default -iprange 10.128.0.0/10 overlaps with existing route.
Please pick another range and set it on all hosts.

In my case, I stopped docker without stopping weave.  Then, my rerun of `weave launch` failed.  To work around, I did:

`ip link set weave down`
`brctl delbr weave`

When we `weave stop`, should we hide exposed weave bridge?

Bao

**Comment by rade** [comment]
dup of #/1076
