### ISSUE TITLE
Proxy fails to start containers from scratch or where user is non root

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#1252]
Fails on rewriting /etc/hosts. From scratch has no /etc/hosts, and non-root users have no permission to rewrite it.

Options:
1) Leave /etc/hosts alone if it fails.
2) Output a warning, but continue
3) Fail with a more informative message

**Comment by rade** [comment]
> From scratch has no /etc/hosts

Surely that implies name resolution isn't working at all; neither for a plain docker container nor a weaved container. Since docker attempts to (re)write /etc/hosts, yet can start containers derived from scratch, presumably it chose option 1. In which case we should do so too.

> and non-root users have no permission to rewrite it.

What does that have to do with anything? Firstly, if, as you say, there is no file, then there is nothing to be rewritten. Secondly, weavewait is executing as root, surely.

**Comment by paulbellamy** [comment]
> Secondly, weavewait is executing as root, surely.

Not in this case:
```Dockerfile
FROM gliderlabs/alpine
RUN adduser -D -s /bin/sh user
ENV HOME /home/user
USER user
CMD true
```

**Comment by paulbellamy** [comment]
Ah, right. You are correct, in the `FROM scratch` case, docker *does* still create /etc/hosts.

In the non-root case (and in general) libnetwork modifies the file from outside the container (e.g. `/var/lib/docker/containers/<container-id>/hosts` on the host), so it doesn't matter if the container is running as root or not.

**Comment by rade** [comment]
> libnetwork modifies the file from outside the container

could we do the same?

**Comment by paulbellamy** [comment]
We can. It involves finding and mounting the dir from the host when we launch the proxy, which is a bit messy. But, yes, it works.

It being even vaguely reliable will depend on docker having a predictable placement of host files, in `/<daemon-containers-path>/<container-id>/hosts` (which the code seems to, afaict), so that we can mount the daemon-containers-path. Afaict from the docker code, the way it manages the container root and symlinks it into place is fairly predictable, and "should work fine".

**Comment by rade** [comment]
Is there perhaps something in inspect/info/some-other-docker-command that would tell us where the container fs is?

**Comment by paulbellamy** [comment]
```bash
$ someContainer=$(docker ps -q | head -n1)
$ hostspath="$(docker inspect -f {{.HostsPath}} $someContainer)"
$ containerspath="$(dirname $(dirname "$hostspath"))"
$ echo $containerspath
/var/lib/docker/containers
```
Then you can mount that, and hope that they're all in the same location. Which afaict from the code, is always the case.

**Comment by rade** [comment]
So why not simply take the `HostsPath` of the container we are interested in?

**Comment by paulbellamy** [comment]
We can, but we have to mount the `$containerspath` volume into the weaveproxy so we have access to that. I suppose I'm just a bit worried about the relationship between `$containerspath` and `$hostspath`, changing (e.g. between host OSes, or in the future). But that would be a somewhat backwards-incompatible docker daemon change, so possibly it's not worth worrying about.

Example code may be helpful here: https://github.com/weaveworks/weave/commit/1b2f35f5f04124cd8aac73dbdd8c75b82c67fc29
In particular: https://github.com/weaveworks/weave/commit/1b2f35f5f04124cd8aac73dbdd8c75b82c67fc29#diff-ed6579eaedd0e67b3ed51c7ee7071044R1132

**Comment by rade** [comment]
I see. I am not keen on the `someContainer` thing.

**Comment by paulbellamy** [comment]
We could check the `weaveexec` container, which we're running in, but `--net=host` resets our hostname, so I'm not sure how to find our own container ID. That would also break `--local`.

Or we can run another container specifically to find the HostsPath:
```
docker run --rm \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --entrypoint /bin/sh \
  $EXEC_IMAGE -c 'docker inspect -f {{.HostsPath}} $HOSTNAME'
```

**Comment by rade** [comment]
> `docker run --rm ...`

Surely that needs to be a named container.
