### ISSUE TITLE
`weave connect` timed out.  remote protocol header not recognised.

### ISSUE THREAD

**Issue by baopx** [weaveworks/weave#1264]
node1:
`weave launch && weave launch-dns && weave launch-proxy`
`weave expose`

node2:
`weave launch && weave launch-dns && weave launch-proxy`
`weave connect $NODE1`
`weave expose`

The two nodes failed to connect with "remote protocol header not recognized" message on node1.

node1:
weave 2015/08/06 00:04:45.349461 Sniffing traffic on &{20 65535 ethwe a2:d3:b0:0e:f8:2d up|broadcast|multicast}
weave 2015/08/06 00:04:45.349526 Discovered our MAC a2:d3:b0:0e:f8:2d
weave 2015/08/06 00:04:45.466639 Discovered local MAC 6a:24:cd:77:b7:9f
weave 2015/08/06 00:04:48.221140 Discovered local MAC 2e:fc:94:e4:3f:8a
weave 2015/08/06 00:04:53.929151 Discovered local MAC 72:c5:41:6c:45:d4
weave 2015/08/06 00:08:42.413337 ->[172.31.29.163:54682] connection accepted
weave 2015/08/06 00:08:44.317251 ->[172.31.29.163:54682] connection shutting down due to error during handshake: remote protocol header not recognised: [13 10 13 10 13 10 13]
weave 2015/08/06 00:14:45.365506 Expired MAC a2:d3:b0:0e:f8:2d at 2e:fc:94:e4:3f:8a(bao-dev-lighthouse)
weave 2015/08/06 00:15:45.372228 Expired MAC 6a:24:cd:77:b7:9f at 2e:fc:94:e4:3f:8a(bao-dev-lighthouse)
weave 2015/08/06 00:15:45.372248 Expired MAC 2e:fc:94:e4:3f:8a at 2e:fc:94:e4:3f:8a(bao-dev-lighthouse)
weave 2015/08/06 00:15:45.372257 Expired MAC 72:c5:41:6c:45:d4 at 2e:fc:94:e4:3f:8a(bao-dev-lighthouse)

node2:
weave 2015/08/06 00:07:16.854305 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 00:09:24.153382 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out
weave 2015/08/06 00:09:27.101436 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 00:11:34.329368 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out
weave 2015/08/06 00:11:36.911792 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 00:13:44.249386 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out
weave 2015/08/06 00:13:48.665797 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 00:15:55.961416 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out
weave 2015/08/06 00:16:01.824088 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 00:17:10.655477 Expired MAC 8e:a1:b3:0c:e6:e9 at fa:2c:a4:7f:04:c5(bao-dev)
weave 2015/08/06 00:18:09.081365 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out
weave 2015/08/06 00:18:10.655847 Expired MAC 16:64:52:28:62:2e at fa:2c:a4:7f:04:c5(bao-dev)
weave 2015/08/06 00:18:10.655868 Expired MAC fa:2c:a4:7f:04:c5 at fa:2c:a4:7f:04:c5(bao-dev)
weave 2015/08/06 00:18:22.306239 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 00:20:29.497372 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out
weave 2015/08/06 00:20:49.140537 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 00:22:56.441381 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out
weave 2015/08/06 00:23:22.652713 ->[172.31.27.67:6783] attempting connection

**Comment by rade** [comment]
> weave 2015/08/06 00:08:42.413337 ->[172.31.29.163:54682] connection accepted
> weave 2015/08/06 00:08:44.317251 ->[172.31.29.163:54682] connection shutting down due to error during handshake: remote protocol header not recognised: [13 10 13 10 13 10 13]

That looks like somebody telnetting to the weave port and hitting 'return' three times.

> weave 2015/08/06 00:07:16.854305 ->[172.31.27.67:6783] attempting connection
> weave 2015/08/06 00:09:24.153382 ->[172.31.27.67:6783] error during connection attempt: dial tcp4 172.31.27.67:6783: connection timed out

This, plus the fact that none of these attempts show up in the other node's logs, suggests that the connections aren't getting through. Might be some firewall in the way.

**Comment by baopx** [comment]
I believe I telnet into the weave port when the connection timed-out. (Node2 -- telnet --> Node1)

**Comment by rade** [comment]
As I said, none of the node2 weave connection attempts show up in the node1 weave logs. node2 weave simply cannot reach node1 weave.

**Comment by rade** [comment]
if you really can telnet from node2 to node1:6783 (please do double check that), then next thing to try would be to run the same telnet from inside a container on node2.

**Comment by baopx** [comment]
telnet from node2 to node1 works.

telnet from node2's container to node1 did not.  I ran docker with --iptablels=false, which caused containers not able to access the network.  removed --iptables=false fixed this.

Now I'm getting a different error messages from both logs:

Node1:
weave 2015/08/06 18:03:50.530274 ->[172.31.29.163:57528|76:e7:66:04:17:6b(bao-dev)]: connection deleted
weave 2015/08/06 18:03:50.530345 Removed unreachable peer 76:e7:66:04:17:6b(bao-dev)
weave 2015/08/06 18:03:50.531391 ->[172.31.29.163:57529] connection accepted
weave 2015/08/06 18:03:50.532000 ->[172.31.29.163:57529|76:e7:66:04:17:6b(bao-dev)]: completed handshake; using protocol version 1
weave 2015/08/06 18:03:50.532098 ->[172.31.29.163:57529|76:e7:66:04:17:6b(bao-dev)]: connection added (new peer)
weave 2015/08/06 18:03:50.533072 ->[172.31.29.163:57529|76:e7:66:04:17:6b(bao-dev)]: connection shutting down due to error: Received new version for entry I own!
weave 2015/08/06 18:03:50.533175 ->[172.31.29.163:57529|76:e7:66:04:17:6b(bao-dev)]: connection deleted
weave 2015/08/06 18:03:50.533247 Removed unreachable peer 76:e7:66:04:17:6b(bao-dev)
weave 2015/08/06 18:03:50.534400 ->[172.31.29.163:57530] connection accepted
weave 2015/08/06 18:03:50.535100 ->[172.31.29.163:57530|76:e7:66:04:17:6b(bao-dev)]: completed handshake; using protocol version 1
weave 2015/08/06 18:03:50.535186 ->[172.31.29.163:57530|76:e7:66:04:17:6b(bao-dev)]: connection added (new peer)
weave 2015/08/06 18:03:50.544945 ->[172.31.29.163:57530|76:e7:66:04:17:6b(bao-dev)]: connection shutting down due to error: Received new version for entry I own!
weave 2015/08/06 18:03:50.547069 ->[172.31.29.163:57530|76:e7:66:04:17:6b(bao-dev)]: connection deleted


Node2:
ouse)
weave 2015/08/06 18:03:26.470532 ->[172.31.27.67:6783] attempting connection
weave 2015/08/06 18:03:26.482966 ->[172.31.27.67:6783|ce:ee:fa:ec:fb:68(bao-dev-lighthouse)]: completed handshake; using protocol version 1
weave 2015/08/06 18:03:26.483138 ->[172.31.27.67:6783|ce:ee:fa:ec:fb:68(bao-dev-lighthouse)]: connection added (new peer)
weave 2015/08/06 18:03:26.687464 ->[172.31.27.67:6783|ce:ee:fa:ec:fb:68(bao-dev-lighthouse)]: connection shutting down due to error: read tcp4 172.31.27.67:6783: connection reset by peer
weave 2015/08/06 18:03:26.687531 ->[172.31.27.67:6783|ce:ee:fa:ec:fb:68(bao-dev-lighthouse)]: connection deleted
weave 2015/08/06 18:03:26.687549 Removed unreachable peer ce:ee:fa:ec:fb:68(bao-dev-lighthouse)

**Comment by rade** [comment]
That is because you defer the `connect`. You either need to tell the 2nd weave to connect to the first as part of `weave launch`, or you need to specify a `-initpeercount 2`. From [our docs](http://docs.weave.works/weave/latest_release/ipam.html#subnets): "you must either supply the list of all peers in the network to `weave launch` or add the `-initpeercount` flag to specify how many peers there will be."

**Comment by baopx** [comment]
Hi Matthias,

Thanks for your help, I got two nodes connected.  This is what I did, with a couple clarification questions hope you can help me with.

1) on node1:
weave launch -initpeercount 2
weave launch-dns
Container e38f75ea55ffe35e9a4d1a82eeb30762c9a7226deaf163856cde7ccd92beb44f not running.

Question: This is because weaver is waiting for its peer?  `weave launch-dns && weave launch-proxy` cannot be run until the weave cluster has quorum?

2) on node1:
weave launch -initpeercount 2

on node2:
weave launch -initpeercount 2
weave connect $NODE1

node1:
weave launch-dns && weave launch-proxy

node2:
weave launch-dns && weave launch-proxy

node1 & 2:
weave expose

The weave network is connected.

Question: If I want to add a 3rd node (possibly up to 32 nodes or more), what is the work-flow I should follow?

Thank you,
Bao

**Comment by rade** [comment]
re 1) yes, it's failing due to the lack of quorum. The error message could be better, but actually in weave 1.1 weavedns will no longer require an IP address, so that will no longer be an issue.

> If I want to add a 3rd node, what is the work-flow I should follow

See the ["More on -initpeercount"](http://docs.weave.works/weave/latest_release/ipam.html#initialisation) section of our docs.

The following sequence should work:
````
host0: weave launch && weave launch-dns && weave launch-proxy
host1: weave launch -initpeercount 2 host0 && weave launch-dns && weave launch-proxy
host2: weave launch -initpeercount 3 host0 && weave launch-dns && weave launch-proxy
host3: weave launch -initpeercount 4 host0 && weave launch-dns && weave launch-proxy
...
````
Be careful though: "The one thing you have to watch is if the early ones get restarted, you must restart them with the current number of peers - if they use the smaller number that was correct when they first started then they could form an independent set again."

**Comment by baopx** [comment]
Thanks for the help Matthias
