### ISSUE TITLE
Weave DNS resolves some entries but not others

### ISSUE THREAD

**Issue by conorcurlett** [weaveworks/weave#1270]
I'm attempting to use Weave, DNS and Proxy across 2 EC2 Instances with docker-compose, and I'm getting some puzzling results. The weave network appears to be correctly connected, the containers are launched by the proxy and entered into DNS, however containers on the second host seem to only be able to resolve a subset of the containers launched (and registered in DNS) on the first host.
Sometimes, if left unmodified for some time, the DNS entries that didn't resolve at first start resolving. 

We're launching weave with `weave launch && weave launch-dns 10.1.1.1/24 && weave launch-proxy`, then setting the DOCKER_HOST to the weave proxy, then `docker-compose up`.

weave status on Host 1 returns 
`weave router 1.0.1
Our name is 26:6c:04:77:0f:f4(ip-172-12-2-98)
Encryption off
Peer discovery on
Sniffing traffic on &{1989 65535 ethwe 3a:87:16:15:08:8b up|broadcast|multicast}
MACs:
7a:79:c6:8b:6d:7d -> ca:44:fa:22:0d:c7(ip-172-12-2-153) (2015-08-07 02:57:37.689082419 +0000 UTC)
6e:a7:af:f2:c7:bf -> ca:44:fa:22:0d:c7(ip-172-12-2-153) (2015-08-07 02:57:36.675672734 +0000 UTC)
aa:33:90:4b:dd:1b -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:57:37.690195828 +0000 UTC)
7a:7e:8b:5a:43:3c -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:57:36.677318614 +0000 UTC)
ca:d4:39:77:e7:47 -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:53:15.433712441 +0000 UTC)
8e:72:62:c6:8a:d2 -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:57:36.676760408 +0000 UTC)
f2:72:e2:27:50:be -> ca:44:fa:22:0d:c7(ip-172-12-2-153) (2015-08-07 02:57:36.676829204 +0000 UTC)
Peers:
ca:44:fa:22:0d:c7(ip-172-12-2-153) (v6) (UID 15402863920030111511)
   -> 26:6c:04:77:0f:f4(ip-172-12-2-98) [172.12.2.98:6783]
   -> 02:82:41:f0:95:b2(ip-172-12-2-67) [52.2.187.75:6783]
26:6c:04:77:0f:f4(ip-172-12-2-98) (v4) (UID 5469332163782811364)
   -> 02:82:41:f0:95:b2(ip-172-12-2-67) [52.2.187.75:48440]
   -> ca:44:fa:22:0d:c7(ip-172-12-2-153) [172.12.2.153:38406]
02:82:41:f0:95:b2(ip-172-12-2-67) (v12) (UID 796717417450408725)
   -> 26:6c:04:77:0f:f4(ip-172-12-2-98) [52.3.44.61:6783]
   -> ca:44:fa:22:0d:c7(ip-172-12-2-153) [54.174.168.196:36796]
Routes:
unicast:
26:6c:04:77:0f:f4 -> 00:00:00:00:00:00
02:82:41:f0:95:b2 -> 02:82:41:f0:95:b2
ca:44:fa:22:0d:c7 -> ca:44:fa:22:0d:c7
broadcast:
26:6c:04:77:0f:f4 -> [02:82:41:f0:95:b2 ca:44:fa:22:0d:c7]
02:82:41:f0:95:b2 -> []
ca:44:fa:22:0d:c7 -> []
Direct Peers:
Reconnects:

Allocator range [10.128.0.0-10.192.0.0)
Owned Ranges:
  10.128.0.0 -> 26:6c:04:77:0f:f4 (ip-172-12-2-98) (v152)
  10.160.0.2 -> 02:82:41:f0:95:b2 (ip-172-12-2-67) (v41)
  10.176.0.0 -> ca:44:fa:22:0d:c7 (ip-172-12-2-153) (v188)
  10.191.255.255 -> 26:6c:04:77:0f:f4 (ip-172-12-2-98) (v0)
Allocator default subnet: 10.128.0.0/10

weave DNS 1.0.1
Listen address :53
Fallback DNS config &{[172.12.0.2] [] 53 1 5 2}

Local domain weave.local
Interface &{1993 65535 ethwe 7a:7e:8b:5a:43:3c up|broadcast|multicast}
Zone database:
dcf822aa7596: osdb.weave.local.[10.128.0.1]
0feae81295de: os.weave.local.[10.128.0.2]
e0b24b669294: adb.weave.local.[10.128.0.3]
7822797cc62e: multihost_fluent_1.weave.local.[10.128.0.4]
eb5b01d0a6f1: hdb.weave.local.[10.128.0.5]
37976425a033: apdb.weave.local.[10.128.0.6]
weave:remote: 

weave proxy is running`

and on Host 2
`weave router 1.0.1
Our name is ca:44:fa:22:0d:c7(ip-172-12-2-153)
Encryption off
Peer discovery on
Sniffing traffic on &{365 65535 ethwe 96:78:c3:82:5d:ea up|broadcast|multicast}
MACs:
7a:7e:8b:5a:43:3c -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:59:36.846583165 +0000 UTC)
ca:d4:39:77:e7:47 -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:53:15.435071342 +0000 UTC)
f2:72:e2:27:50:be -> ca:44:fa:22:0d:c7(ip-172-12-2-153) (2015-08-07 02:59:36.84556752 +0000 UTC)
8e:72:62:c6:8a:d2 -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:59:36.846687732 +0000 UTC)
6e:a7:af:f2:c7:bf -> ca:44:fa:22:0d:c7(ip-172-12-2-153) (2015-08-07 02:59:36.844237176 +0000 UTC)
7a:79:c6:8b:6d:7d -> ca:44:fa:22:0d:c7(ip-172-12-2-153) (2015-08-07 02:59:37.86159191 +0000 UTC)
aa:33:90:4b:dd:1b -> 26:6c:04:77:0f:f4(ip-172-12-2-98) (2015-08-07 02:59:37.863260605 +0000 UTC)
Peers:
ca:44:fa:22:0d:c7(ip-172-12-2-153) (v6) (UID 15402863920030111511)
   -> 26:6c:04:77:0f:f4(ip-172-12-2-98) [172.12.2.98:6783]
   -> 02:82:41:f0:95:b2(ip-172-12-2-67) [52.2.187.75:6783]
26:6c:04:77:0f:f4(ip-172-12-2-98) (v4) (UID 5469332163782811364)
   -> 02:82:41:f0:95:b2(ip-172-12-2-67) [52.2.187.75:48440]
   -> ca:44:fa:22:0d:c7(ip-172-12-2-153) [172.12.2.153:38406]
02:82:41:f0:95:b2(ip-172-12-2-67) (v12) (UID 796717417450408725)
   -> 26:6c:04:77:0f:f4(ip-172-12-2-98) [52.3.44.61:6783]
   -> ca:44:fa:22:0d:c7(ip-172-12-2-153) [54.174.168.196:36796]
Routes:
unicast:
ca:44:fa:22:0d:c7 -> 00:00:00:00:00:00
26:6c:04:77:0f:f4 -> 26:6c:04:77:0f:f4
02:82:41:f0:95:b2 -> 02:82:41:f0:95:b2
broadcast:
ca:44:fa:22:0d:c7 -> [26:6c:04:77:0f:f4 02:82:41:f0:95:b2]
26:6c:04:77:0f:f4 -> []
02:82:41:f0:95:b2 -> []
Direct Peers: 172.12.2.98
Reconnects:

Allocator range [10.128.0.0-10.192.0.0)
Owned Ranges:
  10.128.0.0 -> 26:6c:04:77:0f:f4 (ip-172-12-2-98) (v152)
  10.160.0.2 -> 02:82:41:f0:95:b2 (ip-172-12-2-67) (v41)
  10.176.0.0 -> ca:44:fa:22:0d:c7 (ip-172-12-2-153) (v188)
  10.191.255.255 -> 26:6c:04:77:0f:f4 (ip-172-12-2-98) (v0)
Allocator default subnet: 10.128.0.0/10

weave DNS 1.0.1
Listen address :53
Fallback DNS config &{[172.12.0.2] [] 53 1 5 2}

Local domain weave.local
Interface &{369 65535 ethwe f2:72:e2:27:50:be up|broadcast|multicast}
Zone database:
db7638cb3220: ng.weave.local.[10.176.0.1]
ec76bea90cbd: an.weave.local.[10.176.0.5]
weave:remote: adb.weave.local.[10.128.0.3]/TTL:30, apdb.weave.local.[10.128.0.6]/TTL:30
0e1fb84a964f: ci.weave.local.[10.176.0.6]
2f73dde7a4f1: nx.weave.local.[10.176.0.7]
9154eca82f19: mm.weave.local.[10.176.0.0]
4872d0d40200: apiplatform.weave.local.[10.176.0.2]
5d739d5abb28: hybridrest.weave.local.[10.176.0.3]
15f859dfce4d: multihost_fluent_1.weave.local.[10.176.0.4]

weave proxy is running`

From container ec76bea90cbd a ping to hdb.weave.local resolves, but apdb.weave.local and db.weave.local do not. Pinging those containers' IP addresses does resolve, however.

Weave 1.0.1, Docker 1.6.2.

**Comment by rade** [comment]
> 2 EC2 instances

The `weave status` output shows *three* peers.

> `weave launch-dns 10.1.1.1/24`

Do you give each weavedns a different IP? You need to.

> From container ec76bea90cbd a ping to hdb.weave.local resolves, but apdb.weave.local and db.weave.local do not.

Please enable debug logging on all weavedns instances by launching them with `-debug`. Then, when you are in the above situation, run `docker exec ec76bea90cbd ping hdb.weave.local` and `docker exec ec76bea90cbd ping apdb.weave.local` and post the weavedns log output here.

**Comment by conorcurlett** [comment]
Whoops - a mild typo. There are indeed 3 hosts (the third is a replica of host 2).
We make sure to give each a different DNS entry - `10.1.1.1/24`, `10.1.1.2/24`, `10.1.1.3/24`.

Weave DNS Host 2:
`DEBUG: 2015/08/07 07:26:02.922795 [dns msgid 23135] Query: {Name:hdb.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/07 07:26:02.922817 [cache msgid 23135] addind in pending state
DEBUG: 2015/08/07 07:26:02.922825 [zonedb] Looking for name 'hdb.weave.local.' in local(&remote) database
DEBUG: 2015/08/07 07:26:02.922833 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922836 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922840 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922843 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922846 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922849 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922852 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922855 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.922859 [zonedb] 'hdb.weave.local.' not in local database... trying with mDNS
DEBUG: 2015/08/07 07:26:02.923311 [mdns] srv: mDNS query from local host ('10.1.1.2:53827'): ignored
DEBUG: 2015/08/07 07:26:02.924822 [mdns] Got response name for A-query about name 'hdb.weave.local.': name 'hdb.weave.local.', addr '10.128.0.5'
DEBUG: 2015/08/07 07:26:02.924923 [zonedb] adding '[hdb.weave.local.[10.128.0.5](TTL:30)]' (obtained with mDNS) to 'hdb.weave.local.'
DEBUG: 2015/08/07 07:26:02.924969 [zonedb] Touching name hdb.weave.local.
DEBUG: 2015/08/07 07:26:02.925033 [zonedb] Creating new immediate refresh request for 'hdb.weave.local.'
DEBUG: 2015/08/07 07:26:02.925078 [sched-q] Adding call at 2015-08-07 07:26:02.925029935 +0000 UTC
DEBUG: 2015/08/07 07:26:02.925129 [dns msgid 23135] Sending response: A/1 answers [code:NOERROR]
DEBUG: 2015/08/07 07:26:02.925450 [zonedb] Refreshing name 'hdb.weave.local.' with mDNS...
DEBUG: 2015/08/07 07:26:02.925956 [mdns] srv: mDNS query from local host ('10.1.1.2:53827'): ignored
DEBUG: 2015/08/07 07:26:02.928563 [mdns] Got response name for A-query about name 'hdb.weave.local.': name 'hdb.weave.local.', addr '10.128.0.5'
DEBUG: 2015/08/07 07:26:03.425888 [zonedb] Obtained 1 IPs for name 'hdb.weave.local.' with mDNS: 0 added, 0 removed
DEBUG: 2015/08/07 07:26:03.425928 [zonedb] Rescheduling update for 'hdb.weave.local.' in 29.499530716s
DEBUG: 2015/08/07 07:26:03.531854 [zonedb] 'adb.weave.local.' seem to be irrelevant now: removing any remote information
DEBUG: 2015/08/07 07:26:03.531873 [zonedb] Notifying 2 observers of 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.531882 [cache] removing A-response for 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.576549 [dns msgid 37046] Query: {Name:adb.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/07 07:26:03.576571 [cache msgid 37046] addind in pending state
DEBUG: 2015/08/07 07:26:03.576579 [zonedb] Looking for name 'adb.weave.local.' in local(&remote) database
DEBUG: 2015/08/07 07:26:03.576586 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576589 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576592 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576596 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576599 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576602 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576605 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576608 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.576612 [zonedb] 'adb.weave.local.' not in local database... trying with mDNS
DEBUG: 2015/08/07 07:26:03.576663 [dns msgid 37486] Query: {Name:adb.weave.local. Qtype:28 Qclass:1}
DEBUG: 2015/08/07 07:26:03.576673 [cache msgid 37486] expired: removing
DEBUG: 2015/08/07 07:26:03.576681 [dns msgid 37486] Unsupported query type AAAA
DEBUG: 2015/08/07 07:26:03.577381 [dns msgid 33833] Query: {Name:adb.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/07 07:26:03.577405 [zonedb] Looking for name 'adb.weave.local.' in local(&remote) database
DEBUG: 2015/08/07 07:26:03.577412 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577416 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577419 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577423 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577426 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577429 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577432 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577435 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.577439 [zonedb] 'adb.weave.local.' not in local database... trying with mDNS
DEBUG: 2015/08/07 07:26:03.577488 [dns msgid 49893] Query: {Name:adb.weave.local. Qtype:28 Qclass:1}
DEBUG: 2015/08/07 07:26:03.577506 [dns msgid 49893] Returning reply from cache: NXDOMAIN/0 answers
DEBUG: 2015/08/07 07:26:03.577701 [mdns] srv: mDNS query from local host ('10.1.1.2:53827'): ignored
DEBUG: 2015/08/07 07:26:03.579659 [mdns] Got response name for A-query about name 'adb.weave.local.': name 'adb.weave.local.', addr '10.128.0.3'
DEBUG: 2015/08/07 07:26:03.579750 [zonedb] adding '[adb.weave.local.[10.128.0.3](TTL:30)]' (obtained with mDNS) to 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.579775 [zonedb] Touching name adb.weave.local.
DEBUG: 2015/08/07 07:26:03.579789 [zonedb] Creating new immediate refresh request for 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.579808 [sched-q] Adding call at 2015-08-07 07:26:03.579787191 +0000 UTC
DEBUG: 2015/08/07 07:26:03.579831 [dns msgid 37046] Sending response: A/1 answers [code:NOERROR]
DEBUG: 2015/08/07 07:26:03.579959 [mdns] Got response name for A-query about name 'adb.weave.local.': name 'adb.weave.local.', addr '10.128.0.3'
DEBUG: 2015/08/07 07:26:03.580030 [zonedb] adding '[adb.weave.local.[10.128.0.3](TTL:30)]' (obtained with mDNS) to 'adb.weave.local.'
WARNING: 2015/08/07 07:26:03.580062 [zonedb] 'adb.weave.local.[10.128.0.3](TTL:30)' insertion for adb.weave.local. failed: Tried to add a duplicate entry
INFO: 2015/08/07 07:26:03.580076 [dns msgid 33833] No results for type A query for 'adb.weave.local.' [caching no-local]
DEBUG: 2015/08/07 07:26:03.580270 [zonedb] Refreshing name 'adb.weave.local.' with mDNS...
DEBUG: 2015/08/07 07:26:03.580712 [mdns] srv: mDNS query from local host ('10.1.1.2:53827'): ignored
DEBUG: 2015/08/07 07:26:03.581462 [dns msgid 57383] Query: {Name:adb.weave.local.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/07 07:26:03.581493 [dns msgid 57383] Cached no-local-replies
DEBUG: 2015/08/07 07:26:03.581712 [dns msgid 42098] Query: {Name:adb.weave.local.weave.local. Qtype:28 Qclass:1}
DEBUG: 2015/08/07 07:26:03.581735 [cache msgid 42098] expired: removing
DEBUG: 2015/08/07 07:26:03.581742 [dns msgid 42098] Unsupported query type AAAA
DEBUG: 2015/08/07 07:26:03.582409 [mdns] Got response name for A-query about name 'adb.weave.local.': name 'adb.weave.local.', addr '10.128.0.3'
DEBUG: 2015/08/07 07:26:04.080909 [zonedb] Obtained 1 IPs for name 'adb.weave.local.' with mDNS: 0 added, 0 removed
DEBUG: 2015/08/07 07:26:04.080953 [zonedb] Rescheduling update for 'adb.weave.local.' in 29.499327956s
DEBUG: 2015/08/07 07:26:08.211072 [dns msgid 44689] Query: {Name:adb.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/07 07:26:08.211094 [dns msgid 44689] Cached no-local-replies
DEBUG: 2015/08/07 07:26:08.211613 [dns msgid 45732] Query: {Name:adb.weave.local.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/07 07:26:08.211652 [dns msgid 45732] Cached no-local-replies`

Weave DNS host 2 Logs:
`DEBUG: 2015/08/07 07:26:02.925489 [mdns msgid 39729] srv: trying to answer to mDNS query 'hdb.weave.local.'
DEBUG: 2015/08/07 07:26:02.925509 [zonedb] Looking for name 'hdb.weave.local.' in local database
DEBUG: 2015/08/07 07:26:02.925529 [mdns msgid 39729] srv: found local answer to mDNS query 'hdb.weave.local.'
DEBUG: 2015/08/07 07:26:02.925687 [mdns msgid 39729] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:26:02.928202 [mdns msgid 1024] srv: trying to answer to mDNS query 'hdb.weave.local.'
DEBUG: 2015/08/07 07:26:02.928215 [zonedb] Looking for name 'hdb.weave.local.' in local database
DEBUG: 2015/08/07 07:26:02.928243 [mdns msgid 1024] srv: found local answer to mDNS query 'hdb.weave.local.'
DEBUG: 2015/08/07 07:26:02.928380 [mdns msgid 1024] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:26:03.580347 [mdns msgid 58226] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.580364 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:26:03.580383 [mdns msgid 58226] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.580519 [mdns msgid 58226] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:26:03.583007 [mdns msgid 41568] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.583019 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:26:03.583047 [mdns msgid 41568] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:03.583180 [mdns msgid 41568] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:26:33.626034 [mdns msgid 52402] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:33.626052 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:26:33.626070 [mdns msgid 52402] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:33.626227 [mdns msgid 52402] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:26:33.630408 [mdns msgid 65216] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:33.630420 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:26:33.630444 [mdns msgid 65216] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:26:33.630608 [mdns msgid 65216] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:26:33.631386 [mdns msgid 50575] srv: trying to answer to mDNS query 'adb.weave.local.weave.local.'
DEBUG: 2015/08/07 07:26:33.631401 [zonedb] Looking for name 'adb.weave.local.weave.local.' in local database
DEBUG: 2015/08/07 07:26:33.631410 [mdns msgid 50575] srv: no local answer for answering mDNS query 'adb.weave.local.weave.local.'
DEBUG: 2015/08/07 07:27:03.676808 [mdns msgid 64337] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:03.676826 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:27:03.676845 [mdns msgid 64337] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:03.676959 [mdns msgid 64337] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:27:03.682098 [mdns msgid 59226] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:03.682111 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:27:03.682141 [mdns msgid 59226] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:03.682266 [mdns msgid 59226] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:27:33.723549 [mdns msgid 9300] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:33.723615 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:27:33.723641 [mdns msgid 9300] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:33.723821 [mdns msgid 9300] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:27:33.729886 [mdns msgid 53319] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:33.729900 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:27:33.729913 [mdns msgid 53319] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:27:33.730030 [mdns msgid 53319] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:27:33.731637 [mdns msgid 17390] srv: trying to answer to mDNS query 'adb.weave.local.weave.local.'
DEBUG: 2015/08/07 07:27:33.731671 [zonedb] Looking for name 'adb.weave.local.weave.local.' in local database
DEBUG: 2015/08/07 07:27:33.732715 [mdns msgid 17390] srv: no local answer for answering mDNS query 'adb.weave.local.weave.local.'
DEBUG: 2015/08/07 07:28:03.773630 [mdns msgid 58766] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:03.773649 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:28:03.773668 [mdns msgid 58766] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:03.773799 [mdns msgid 58766] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:28:03.776599 [mdns msgid 30917] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:03.776613 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:28:03.776637 [mdns msgid 30917] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:03.776806 [mdns msgid 30917] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:28:33.816766 [mdns msgid 26704] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:33.816831 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:28:33.817204 [mdns msgid 26704] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:33.817579 [mdns msgid 26704] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:28:33.824855 [mdns msgid 1333] srv: trying to answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:33.824868 [zonedb] Looking for name 'adb.weave.local.' in local database
DEBUG: 2015/08/07 07:28:33.824882 [mdns msgid 1333] srv: found local answer to mDNS query 'adb.weave.local.'
DEBUG: 2015/08/07 07:28:33.825001 [mdns msgid 1333] srv: response sent: 1 answers
DEBUG: 2015/08/07 07:28:33.825063 [mdns msgid 63436] srv: trying to answer to mDNS query 'adb.weave.local.weave.local.'
DEBUG: 2015/08/07 07:28:33.825074 [zonedb] Looking for name 'adb.weave.local.weave.local.' in local database
DEBUG: 2015/08/07 07:28:33.825083 [mdns msgid 63436] srv: no local answer for answering mDNS query 'db.weave.local.weave.local.'`

It may not be 100% relevant, but given the "duplicate entry" message in the debug log, I should also add that in the docker compose .yml files we are setting `hostname: adb.weave.local` and `hostname: hdb.weave.local` for those containers. We do this consistently for all containers.

**Comment by rade** [comment]
According to the logs you pinged hdb and adb, right? And the first succeeded whereas the 2nd didn't?

**Comment by conorcurlett** [comment]
That's correct, yes.

**Comment by rade** [comment]
I suspect this is a bug in weavedns. Looks like there are two concurrent queries going on for 'adb', which both triggered an mDNS query, since we had no local information. We store the result of the first mDNS query, but when the 2nd result arrives we trip over the existing record, which causes us to return an NXDOMAIN, which, moreover, we then cache as an answer.

I reckon we should ignore `DuplicatError` [here](https://github.com/weaveworks/weave/blob/v1.0.1/nameserver/zone_lookup.go#L105).

Will try to get this fixed for 1.0.2. @inercia please take a look.

**Comment by rade** [comment]
@conorcurlett how reproducible is this for you? Would you be able to test a fix?

**Comment by conorcurlett** [comment]
While it's a little intermittent/unpredictable, it happens > 75% of the time, so I would definitely be able to test a fix.

**Comment by rade** [comment]
I have managed to reproduce this by introducing a `time.Sleep(10 * time.Second)` just before [this line](https://github.com/weaveworks/weave/blob/v1.0.1/nameserver/zone_lookup.go#L89) and then following these steps:
````
host1$ weave launch && weave launch-dns && weave launch-proxy
host1$ eval $(weave proxy-env)
host1$ docker run --name=foo -dti ubuntu
host2$ weave launch $HOST1 && weave launch-dns && weave launch-proxy
host2$ eval $(weave proxy-env)
host2$ docker run --name=bar -dti ubuntu
host2$ docker exec bar getent hosts foo
````
The 'getent' fails. Here is the relevant portion of the dns logs:
````
DEBUG: 2015/08/08 20:48:17.658644 [dns msgid 31573] Query: {Name:foo.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/08 20:48:17.658681 [cache msgid 31573] addind in pending state
DEBUG: 2015/08/08 20:48:17.658700 [zonedb] Looking for name 'foo.weave.local.' in local(&remote) database
DEBUG: 2015/08/08 20:48:17.658708 [zonedb] Touching name foo.weave.local.
DEBUG: 2015/08/08 20:48:17.658712 [zonedb] 'foo.weave.local.' not in local database... trying with mDNS
DEBUG: 2015/08/08 20:48:22.659240 [dns msgid 31573] Query: {Name:foo.weave.local. Qtype:1 Qclass:1}
DEBUG: 2015/08/08 20:48:22.659264 [cache msgid 31573] expired: removing
DEBUG: 2015/08/08 20:48:22.659271 [zonedb] Looking for name 'foo.weave.local.' in local(&remote) database
DEBUG: 2015/08/08 20:48:22.659277 [zonedb] Touching name foo.weave.local.
DEBUG: 2015/08/08 20:48:22.659281 [zonedb] 'foo.weave.local.' not in local database... trying with mDNS
DEBUG: 2015/08/08 20:48:27.659259 [mdns] srv: mDNS query from local host ('10.160.0.1:47933'): ignored
DEBUG: 2015/08/08 20:48:27.662170 [mdns] Got response name for A-query about name 'foo.weave.local.': name 'foo.weave.local.', addr '10.128.0.2'
DEBUG: 2015/08/08 20:48:27.662336 [zonedb] adding '[foo.weave.local.[10.128.0.2](TTL:30)]' (obtained with mDNS) to 'foo.weave.local.'
DEBUG: 2015/08/08 20:48:27.663410 [zonedb] Touching name foo.weave.local.
DEBUG: 2015/08/08 20:48:27.663437 [zonedb] Creating new immediate refresh request for 'foo.weave.local.'
DEBUG: 2015/08/08 20:48:27.663458 [sched-q] Adding call at 2015-08-08 20:48:27.663434659 +0000 UTC
DEBUG: 2015/08/08 20:48:27.663489 [dns msgid 31573] Sending response: A/1 answers [code:NOERROR]
DEBUG: 2015/08/08 20:48:27.663742 [dns msgid 24457] Fallback query: {Name:foo. Qtype:1 Qclass:1} [UDP, max:512 bytes]
DEBUG: 2015/08/08 20:48:27.664160 [zonedb] Refreshing name 'foo.weave.local.' with mDNS...
DEBUG: 2015/08/08 20:48:27.664385 [mdns] srv: mDNS query from local host ('10.160.0.1:47933'): ignored
DEBUG: 2015/08/08 20:48:27.668460 [mdns] Got response name for A-query about name 'foo.weave.local.': name 'foo.weave.local.', addr '10.128.0.2'
DEBUG: 2015/08/08 20:48:27.687757 [dns msgid 24457] Given answer by 10.0.2.3 for query foo.
DEBUG: 2015/08/08 20:48:28.164629 [zonedb] Obtained 1 IPs for name 'foo.weave.local.' with mDNS: 0 added, 0 removed
DEBUG: 2015/08/08 20:48:28.164658 [zonedb] Rescheduling update for 'foo.weave.local.' in 29.499503788s
DEBUG: 2015/08/08 20:48:32.659910 [mdns] srv: mDNS query from local host ('10.160.0.1:47933'): ignored
DEBUG: 2015/08/08 20:48:32.663366 [mdns] Got response name for A-query about name 'foo.weave.local.': name 'foo.weave.local.', addr '10.128.0.2'
DEBUG: 2015/08/08 20:48:32.663564 [zonedb] adding '[foo.weave.local.[10.128.0.2](TTL:30)]' (obtained with mDNS) to 'foo.weave.local.'
WARNING: 2015/08/08 20:48:32.663667 [zonedb] 'foo.weave.local.[10.128.0.2](TTL:30)' insertion for foo.weave.local. failed: Tried to add a duplicate entry
INFO: 2015/08/08 20:48:32.663722 [dns msgid 31573] No results for type A query for 'foo.weave.local.' [caching no-local]
````
It looks like the container's name resolver re-issues the query after 5 seconds. The answer for that query runs into the 'duplicate entry' error, which causes NXDOMAIN to be returned (and cached - subsequent queries instantly fail).
