### ISSUE TITLE
Docker breaks while stopping weaveproxy

### ISSUE THREAD

**Issue by miztiik** [weaveworks/weave#1272]
Docker 1.7.1
Weave 1.0.1

I was just trying to restart weave containers using docker stop but it abruptly exists after trying to stop weaveproxy, Is there a particular order of stops that i should be using?

```
[root@dockerHostCentOS7 ~]# docker stop weaveproxy weavedns weave
Post http://127.0.0.1:12375/v1.19/containers/weaveproxy/stop?t=10: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Error: failed to stop containers: [weaveproxy weavedns weave]
[root@dockerHostCentOS7 ~]# docker ps
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[root@dockerHostCentOS7 ~]# docker info
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[root@dockerHostCentOS7 ~]#
```

**Comment by rade** [comment]
since you have done an `eval $(weave proxy-env)` earlier, your `DOCKER_HOST` will be pointing at the proxy. So when you stop the proxy, any subsequent `docker` commands will fail. You need to unset `DOCKER_HOST`.

**Comment by miztiik** [comment]
so i do something like , `env -u DOCKER_HOST` before i stop weave?
better question is what is the best way to recycle weave containers?

**Comment by rade** [comment]
> so i do something like , `env -u DOCKER_HOST` before i stop weave?

no, `unset DOCKER_HOST`.

> better question is what is the best way to recycle weave containers?

I don't know what you mean by 'recycle'.

**Comment by rade** [comment]
There is a `weave stop`; is that what you are looking for? The `DOCKER_HOST` unsetting applies there too.

**Comment by rade** [comment]
I have filed #1288 for the improving the stop sequence.

**Comment by miztiik** [comment]
I was looking for a more graceful stop weave-start weave cycle, rather than i have to unset -stop-start to avoid breaking my session. I notice that you have filed a improvement, but no milestone?

**Comment by rade** [comment]
> I notice that you have filed a improvement, but no milestone?

correct.

**Comment by rade** [comment]
Note that instead of the `weave proxy-env` route, which modifies the environment, you could explicitly tell docker to use the weave proxy on a per-invocation basis with `docker $(weave proxy-config) ...`. As per the [proxy setup docs](http://docs.weave.works/weave/latest_release/proxy.html#setup).
