### ISSUE TITLE
proxy interferes with `weave run`

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1279]
````
$ weave launch && weave launch-proxy
553f250f448d25225e4f618138c3a7a1eacfc345e0412fb1ba88d75c71e25445
f334cd166c63ff0b93ee3755cbb9e47d77c8a70f1df2b05ac1dd68cc77b9d397
$ eval $(weave proxy-env)
$ weave run 10.2.0.1/24 --name=foo -it gliderlabs/alpine /bin/sh
ddf0f24dc7892155b359ca566572a95881ff3590419c13028a90b4fc34599b35
matthias@xps:~/go/src/github.com/weaveworks/weave$ weave ps foo
foo 12:c2:7d:04:88:b1 10.128.0.1/10 10.2.0.1/24
````

So we have two IP addresses.

I suspect there's interference for DNS as well, e.g. a container started with `--without-dns` will nevertheless have its resolver pointed at weavedns by the proxy.

The proxy really shouldn't do anything when containers are launched with `weave run/start`.

**Comment by rade** [comment]
@paulbellamy Is the fix here to simply add `-e WEAVE_CIDR=none` in the `docker run` the script issues for the container? Just as we do for various `docker run` invocations that launch infrastructure containers.

That wouldn't fix `weave start` but I think we can live with that (and file a separate bug for it).

**Comment by paulbellamy** [comment]
How wouldn't it fix `weave start` also?

**Comment by rade** [comment]
`docker start` doesn't accept `-e`.

**Comment by paulbellamy** [comment]
But assuming the container was created with `weave create ...`, it will already have the env var. So what it won't fix is:
```
docker create --name foo ...
weave start foo
```
Which seems like an edge-case.

**Comment by rade** [comment]
there is no such thing as `weave create`.

**Comment by rade** [comment]
`weave start` turns out to be working just fine...
````
$ docker run --name=foo -dit gliderlabs/alpine /bin/sh
$ weave launch && weave launch-dns && weave launch-proxy
4ba9f7bfa099523517eaafdc9b471273bdde554a964add35e1b4157d532491d3
744010e854945d97496b35d738ebe2eecbc6a62e556a32ee7b66c3507f579afb
0cda49fd8c97eb6470ba4949d2eac2eb617a251d14ff14269e5efe42d6962cb5
$ eval $(weave proxy-env)
$ weave start 10.2.0.1/24 foo
foo
$ weave ps foo
foo 46:81:f9:30:f6:3e 10.2.0.1/24
````

The reason is that for `weave start` the `docker run` executes inside the weavexec container and consequently speaks to docker over the unix domain socket.
