### ISSUE TITLE
stopping weave results in error and breaks subsequent docker invocations

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1288]
Technically not a bug, but most users will see it that way. Certainly annoys the hell out of me...

````
$ weave launch
$ eval $(weave env)
...do some weaving...
$ weave stop
error deleting container: Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
$ docker ps
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
````

The fix is to `export DOCKER_HOST=<previous value>` prior to `weave stop`, which a) is non-obvious, and b) somewhat difficult if you don't know / didn't save the previous value.

**Comment by rade** [comment]
I suggest `weave env` also exports a `DOCKER_HOST_ORIG`. and `weave env --restore` (or `weave restore-env`?) uses that to restore the original settings.

@errordeveloper is there an equivalent command in boot2docker/machine/swarm that could serve as inspiration?

**Comment by inercia** [comment]
Maybe it would be easier to print a warning on `weave stop` when `DOCKER_HOST` was pointing to the proxy...

**Comment by rade** [comment]
A warning that tells the user to a) expect an error,  and b) run `weave env --restore`, would indeed be helpful.
