### ISSUE TITLE
publish latest images from CI

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1295]
Currently, we publish snapshot builds once in a while manually, however it would be much easier if this was done via CI once tests passed. This way some of our users as well as members of the team could test latest code quicker.

**Comment by tomwilkie** [comment]
The relevant code exists in the scope repo: https://github.com/weaveworks/scope/blob/master/circle.yml#L56

**Comment by awh** [comment]
:+1:

**Comment by rade** [comment]
#1337 got reverted because of #1353. -> re-opening.
