### ISSUE TITLE
improve intro section to Github for weave project

### ISSUE THREAD

**Issue by davkal** [weaveworks/weave#1304]
@monadic said
> This currently says "Weave creates a virtual network that connects Docker containers deployed across multiple hosts and enables their automatic discovery."

> Let's update this to something that also mentions Service Discovery, Load Balancing, Address Management, as well as networking, and links back to weave.works for more info.

**Comment by squaremo** [comment]
Let's not.

**Comment by rade** [comment]
That opening sentence is quite hard to improve on.

I suggest we look at improving the *entire* intro section. Without making it (much) longer.
