### ISSUE TITLE
Stop trying to connect to yourself and spamming the logs

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1305]
I start weave and pass every peer the same set of IPs, which happens to include their own.  The logs are full of messages like this:

```
INFO: 2015/08/16 10:28:26.594151 ->[172.31.13.96:6783] attempting connection
INFO: 2015/08/16 10:28:26.594664 ->[172.17.42.1:50625] connection accepted
ERRO: 2015/08/16 10:28:26.595323 ->[172.31.13.96:6783|fe:09:5f:88:03:b4(ip-172-31-13-96)]: connection shutting down due to error: Cannot connect to ourself
ERRO: 2015/08/16 10:28:26.595593 ->[172.17.42.1:50625|fe:09:5f:88:03:b4(ip-172-31-13-96)]: connection shutting down due to error: Cannot connect to ourself
INFO: 2015/08/16 10:33:44.324598 ->[172.31.13.96:6783] attempting connection
INFO: 2015/08/16 10:33:44.324989 ->[172.17.42.1:50638] connection accepted
ERRO: 2015/08/16 10:33:44.325565 ->[172.31.13.96:6783|fe:09:5f:88:03:b4(ip-172-31-13-96)]: connection shutting down due to error: Cannot connect to ourself
ERRO: 2015/08/16 10:33:44.325803 ->[172.17.42.1:50638|fe:09:5f:88:03:b4(ip-172-31-13-96)]: connection shutting down due to error: Cannot connect to ourself
```

Could we either remember that the IP pointed to ourself, and stop trying to connect to it, or only log errors if they are different from last time?

**Comment by bboreham** [comment]
As noted at #611, the weave router is running inside a container and containers do not generally know their externally-visible address.  And NAT mappings can change so it is dangerous to cache the results of a particular connection.  Although perhaps a mapping to ourself is unlikely to change.

Only logging errors when they change is an interesting idea.

**Comment by rade** [comment]
> perhaps a mapping to ourself is unlikely to change.

That.

> Only logging errors when they change is an interesting idea.

We need the error log message in order to 'close' the connection lifecycle in the logs.
