### ISSUE TITLE
"cannot unmarshal DNS message" using weavedns to resolve email-smtp.us-east-1.amazonaws.com

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1306]
This bug shows a similar problem existed with consul dns:

https://github.com/golang/go/issues/11070

Looks like the following is happening:
- recursive dns is responding with a compressed answer, to fit in 512bytes
- miekg dns is uncompressing the answer transparently for us (https://github.com/miekg/dns/issues/216)
- we send the uncompresses answer on to the client, which then fails to parse it as its truncated.

**Comment by rade** [comment]
Is this issue present in the old weavedns too? If so it would be good to get a fix in for 1.0.2, assuming it is easy.

**Comment by rade** [comment]
> Is this issue present in the old weavedns too?

Pretty sure it is. @inercia?

**Comment by inercia** [comment]
Yes, that seems to be the cause. Not sure about the solution, though. Some people suggest setting `Compress = true` for all messages to clients, maybe as a temporary solution...

**Comment by rade** [comment]
> Not sure about the solution, though.

What's wrong with [this](https://github.com/weaveworks/weave/pull/1307/files#diff-7277a554bb2705f94ae32e58839b3a75R244)? Can't we perform the same test in the old code?

**Comment by inercia** [comment]
I'm backporting #1307 for 1.0.2
