### ISSUE TITLE
curl -L git.io/weave -o in guides pulling old script?

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#1308]
curl -L git.io/weave -o     is getting the old 1.0.1 version of the script. 

should there be a 1.0.2 in git.io, which I'm able to pull directly from the Weaveworks repo and copy over to my working directory (diff'ed the curl file from git.io and the one in the repo and they are different)

split into 2 issues.

**Comment by abuehrle** [comment]
FYI: seems to be an issue with 1.8.1 "Layer already being pulled by another client. Waiting." #15603

https://github.com/docker/docker/issues/15603

The weave script version is another matter, however.

**Comment by rade** [comment]
1.0.1 is the most recent release. So the behaviour is as expected.
