### ISSUE TITLE
weave setup returns error when getting new images 

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#1309]
Seems to hang when I run 'weave setup' here: 

4a5724cea5e5: Error pulling dependent layers 
Error pulling image (latest) from docker.io/weaveworks/weaveexec, Server error: Status 0 while fetching image layer (4a5724cea5e5c297148019f084a1c98125d791c3ea986cedbcbe3edf1dec654c)

or is this a docker github issue:

'weave setup'

Unable to find image 'weaveworks/weaveexec:latest' locally
latest: Pulling from weaveworks/weaveexec
4a5724cea5e5: Verifying Checksum 
e22d9bbedd38: Layer already being pulled by another client. Waiting. 
e92868fcb4b9: Layer already being pulled by another client. Waiting. 
2b20bbd0e3b8: Layer already being pulled by another client. Waiting. 
0c1c7b6f47b1: Layer already being pulled by another client. Waiting. 
06ef00beeac8: Layer already being pulled by another client. Waiting. 
06ef00beeac8: Layer already being pulled by another client. Waiting. 
a5b60fe97da5: Already exists 
16be31c9facc: Already exists 
209c90b77f33: Already exists 
6f8b93615288: Already exists 
Pulling repository docker.io/weaveworks/weaveexec

waits.....forever!

**Comment by abuehrle** [comment]
FYI: seems to be an issue with 1.8.1 "Layer already being pulled by another client. Waiting." #15603

https://github.com/docker/docker/issues/15603

**Comment by abuehrle** [comment]
also: 

https://github.com/docker/docker/issues/12823

**Comment by rade** [comment]
This happens sometimes with Docker. It's not a weave issue.

Try bouncing your docker daemon. Or rebooting the VM on which it is running.

**Comment by abuehrle** [comment]
what does this mean? 
in docker logs weaveproxy

Ignoring container due to --net option: "host"

**Comment by abuehrle** [comment]
Oops wrong thread, sorry.
