### ISSUE TITLE
bad message on incorrect flag

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#1316]
When setting the incorrect number of dashes in a flag, ie `-init-peer-count 3` instead of `--init-peer-count`

returns, 

```
The weave container has died. Consult the logs with 'docker logs weave' for further details.
```

**Comment by rade** [comment]
How is this a "bad message"?

It would certainly be more helpful to show the root cause. That is covered by #1280. Is there more to this?

**Comment by abuehrle** [comment]
Didn't see that other one. Is there a duplicate label?

**Comment by rade** [comment]
> Is there a duplicate label

Yes, `resolution/duplicate`; right there in the drop-down ;)
