### ISSUE TITLE
message should be more helpful when default subnet is out of bounds

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#1317]
When running 
`weave launch-router --ipalloc-default-subnet 10.53.1.0/8 --init-peer-count 3`

`The weave container has died. Consult the logs with 'docker logs weave' for further details.`

Anyway to let me know what the 'boundary' might be?

`docker logs weave`

```
FATA: 2015/08/17 19:23:45.045185 Default subnet 10.48.0.0/12 out of bounds: 10.32.0.0/12

```

**Comment by rade** [comment]
> Anyway to let me know what the 'boundary' might be?

The log message does contain the boundary. But it doesn't say so, and doesn't say where it comes from. It should.
