### ISSUE TITLE
weave --help should be more helpful when Docker is inaccessible

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1322]
$ weave --help
    Post http:///var/run/weave.sock/v1.19/containers/create: dial unix /var/run/weave.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?

I think at some point in the past it used to say "weave must be run as root"

**Comment by rade** [comment]
We used to check whether we are root. But that is just wrong since things can be configured s.t. weave can be run w/o root.

Also, there is no such thing as `weave --help`.

**Comment by bboreham** [comment]
I thought `weave --help` is something that a user might try after the message in #1321
