### ISSUE TITLE
Are docker & weave versions tied together?

### ISSUE THREAD

**Issue by miztiik** [weaveworks/weave#1323]
When i did a pull from docker 1.8.1 i got weave 1.0.2, 
I imported those images to my docker 1.7.1, but weave tries to pull 1.0.1 and start it?

Is this supposed to happen?

**Comment by rade** [comment]
The version is determined by the weave script. Presumably on your docker 1.8.1 install you were using a 1.0.2 weave script, and on your 1.7.1 install a 1.0.1 script.

**Comment by miztiik** [comment]
I am not running any script, just type the weave start command. The [script](https://github.com/miztiik/cloudera-On-Docker/blob/master/docker-dns-build/docker-weavedns-setup.sh) that i sometimes use also does pretty much the same thing
##### OS Version
```
[root@dockerHostCentOS7 cloudera-On-Docker]# uname -a
Linux dockerHostCentOS7 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
##### Docker Info
```
[root@dockerHostCentOS7 cloudera-On-Docker]# docker info
Containers: 0
Images: 73
Storage Driver: btrfs
 Build Version: Btrfs v3.16.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.11.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 1.066 GiB
Name: dockerHostCentOS7
ID: HG6Q:X74X:HAL7:WQXG:TEB7:EL3I:WGUY:BC65:GE6T:GFQP:4YL6:GDJO
```
##### Docker version - 1.7.1
```
[root@dockerHostCentOS7 cloudera-On-Docker]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```
##### List of docker imags ( no weave yet )
```
[root@dockerHostCentOS7 cloudera-On-Docker]# docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
mystique/cloudera-on-docker   latest              f5622c92917e        2 days ago          1.045 GB
local/clouderamgrnode         v1                  acc83001106b        13 days ago         2.002 GB
httpd                         latest              a2ceb9245c63        5 weeks ago         162 MB
```
##### Docker pull using the weave command to get v1.0.2 but it attempts to pull 1.0.1
```
[root@dockerHostCentOS7 cloudera-On-Docker]# weave launch && weave launch-dns && weave launch-proxy
Unable to find image 'weaveworks/weaveexec:1.0.1' locally
```

**Comment by rade** [comment]
> I am not running any script, just type the weave start command. 

Running any `weave` command does run a script. The `weave` script. You must have downloaded and installed it somehow, presumably by following [the instructions](https://github.com/weaveworks/weave#installation). In order to get the latest version of weave you must re-download the script.

**Comment by miztiik** [comment]
Thanks for that. I `re-installed v1.0.2` using the script from the docs page. Is the upgrade method documented elsewhere? The [release notes] (https://github.com/weaveworks/weave/releases) doesn't have this info

**Comment by rade** [comment]
> Is the upgrade method documented elsewhere?

We'll try to remember mentioning it in the release notes next time.
