### ISSUE TITLE
`weave status <garbage>` produces 404

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#1328]
I don't think this command exists, but say I have a swarm as setup in the following example:

http://weave.works/guides/weave-and-docker-platform/chapter3/machine-and-swarm-with-weave-proxy.html

And I run `weave status weave-1`  or weave status `weave-2`

weave returns: `404 page not found`

(the last VM I configured was `weave-3` and from there I can issue weave commands directly. )

I am aware that this is not the correct command and that I have to go through Docker, but maybe the message should tell me something to that effect.

**Comment by abuehrle** [comment]
I thought that was pretty intuitive.  This was not very intuitive: 

docker `docker-machine config --swarm weave-1` info

**Comment by rade** [comment]
I don't understand that last comment. What does that have to do with `weave status`?

**Comment by abuehrle** [comment]
I'm on the client talking to the VM's, I've provisioned 3 machines and then connected them.  The last one I provisioned was weave-3, how do I go back to weave-1 without going through docker? i guess I can't is the answer.  To me, doing a "weave status weave-1" kind of made sense, but to you it probably doesn't.

Anyway, probably I would return "this is an invalid argument" rather than a 404 error of which I thought something was happening, since this is normally an http error and not something I would expect in this case.

**Comment by rade** [comment]
>  how do I go back to weave-1

What are you trying to do? What does "go back" mean? Do you want to run `weave status` on weave-1?

```
DOCKER_CLIENT_ARGS="$(docker-machine config weave-1)" weave status
```

should do the trick.

**Comment by abuehrle** [comment]
Yes, I can do that.  But what happens when I want to switch VMs, do I have to re-set my env each time to recognize the new host?  or is there a way to put all three VMs in my env so I don’t have to swap environments each time.  Forgive my naive question.

**Comment by rade** [comment]
I really struggle to understand what you are trying to do accomplish. When you say "I have to re-set my env each time", what exactly are you referring to?

**Comment by abuehrle** [comment]
Never mind.  Just pointing out something as someone new coming to Weave.

**Comment by rade** [comment]
> Just pointing out something as someone new coming to Weave.

Well, I'd quite like to understand what it is that you are pointing out :)
