### ISSUE TITLE
panic: invalid argument to Intn in ipam test

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1336]
https://travis-ci.org/weaveworks/weave/builds/76423596
```
ok  	github.com/weaveworks/weave/ipam/paxos	2.985s
Ring [10.0.0.0, 10.0.0.255)
  10.0.0.0 -> 01:00:00:00:02:00 (v0)
--- FAIL: TestFuzzRingHard-4 (0.00s)
panic: invalid argument to Intn [recovered]
	panic: invalid argument to Intn
```

**Comment by rade** [comment]
Here's the stack trace:
```
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
math/rand.(*Rand).Intn(0xc20802c1b0, 0x0, 0xce2790)
	/usr/local/go/src/math/rand/rand.go:95 +0x74
math/rand.Intn(0x0, 0x0)
	/usr/local/go/src/math/rand/rand.go:195 +0x34
github.com/weaveworks/weave/ipam/ring.func·016()
	/home/travis/gopath/src/github.com/weaveworks/weave/ipam/ring/ring_test.go:712 +0xb7c
github.com/weaveworks/weave/ipam/ring.TestFuzzRingHard(0xc208068cf0)
	/home/travis/gopath/src/github.com/weaveworks/weave/ipam/ring/ring_test.go:726 +0x344
testing.tRunner(0xc208068cf0, 0xcc94d8)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b
```

ring_test.go:712 is `ring1 := ringsWithEntries[rand.Intn(len(ringsWithEntries))]`

The panic arises when calling `rand.Intn(0)`: http://play.golang.org/p/NdVk3xYFnj

**Comment by bboreham** [comment]
So, no peers had any entries at all.  I think this can happen if it (randomly) removes peer 0 straight off the bat.

**Comment by rade** [comment]
I doubt `peers` is empty, since that would make `randomPeer` explode. I reckon we have some peer(s) but all with empty rings.

**Comment by bboreham** [comment]
That's what I said.

**Comment by bboreham** [comment]
Actually, my explanation doesn't work - when it removes a peer it transfers its entries.  So I'm re-opening because we don't know how it crashed.

**Comment by bboreham** [comment]
I think I found the correct fix now.
