### ISSUE TITLE
router.MaxUDPPacketSize constant has wrong value

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1340]
Value should be `65535` not `65536`

**Comment by rade** [comment]
What impact does that have? need a description for the release notes.

**Comment by awh** [comment]
It's negligible - we allocate buffers one byte bigger than needed, and could try to send a UDP packet that's one byte too big instead of dropping a frame.

**Comment by rade** [comment]
> could try to send a UDP packet that's one byte too big instead of dropping a frame.

Is this at all observable by applications?

**Comment by awh** [comment]
@dpw has just pointed out that the non-DF UDP sender probably doesn't catch the EMSGSIZE error - investigating...

**Comment by awh** [comment]
He's right - IP packets of exactly 65522 bytes in length will cause the connection to be torn down; this affects master/1.0 and fdp-prep...

**Comment by awh** [comment]
OK have tested further and master/1.0 are NOT affected - they limit frame size by using the DefaultPMTU constant, which has the correct value of 65535.

**Comment by awh** [comment]
Closed by 086ab9d12614e6dc50cd7d622dbd4f08002656eb.
