### ISSUE TITLE
DNS crashes if host resolv.conf contains docker0 bridge ip

### ISSUE THREAD

**Issue by jakolehm** [weaveworks/weave#1343]
We are trying to resolve container dns names from host by adding weavedns ip (docker0 ip) to /etc/resolv.conf. This seems to create circular dependency inside weavedns because it sees docker0 ip as an upstream server.

**Comment by tomwilkie** [comment]
As a work around, try ```WEAVEDNS_DOCKER_ARGS=--dns=8.8.8.8 weave launch-dns``` (```WEAVE_DOCKER_ARGS=--dns=8.8.8.8 ./weave launch``` for master)

**Comment by jakolehm** [comment]
That seems to help, thanks! But I don't like to use this as a permanent solution because upstream servers should most likely come from dhcp. Would it be possible to remove "own" ip from upstream servers list (this is how we are currently doing it in kontena)?

**Comment by tomwilkie** [comment]
Yes we can do that.  Out of interest, whats the contents of your ```/etc/resolv.conf```?

**Comment by jakolehm** [comment]
I was just testing this in Vagrant so nothing special:
```
nameserver 172.17.42.1
nameserver 192.168.0.1
```

First nameserver is docker0 ip.

**Comment by tomwilkie** [comment]
Ideas for fixing:
(1) filter out the docker bridge ip from the weave containers revolvers in the weave script, when launching weave
(2) filter out the docker bridge ip in the weavedns code, when parsing resolv.conf
(3) detect when we are our own recursive resolver (by tracking inflight request ids) and error those requests.

(1) would mean docker wouldn't automatically update the weave containers resolv.conf when the host's changes; also, it would add complexity to the weave script, which we probably don't want
(2) would be hard to detect the docker bridge ip in weavedns; we could make an explicit flag for it, or we could filter on the weave containers default gateway (no no no)
(3) would be a little messy to implement, but it probably the most general.

@rade @inercia Thoughts? Alternatives?

**Comment by tomwilkie** [comment]
@rade suggests using iptables to stop us talking to ourselves.  This would manifest as a timeout, and we don't want the delay before trying the next server.

**Comment by tomwilkie** [comment]
Lets got with (2), and call the flag --dns-effective-listen-address

**Comment by inercia** [comment]
@tomwilkie I also think (2) is our best option...
