### ISSUE TITLE
Waiting for IPAM to sort itself out is mysterious

### ISSUE THREAD

**Issue by squaremo** [weaveworks/weave#1346]
We have reports of people running into trouble when starting weave on more than one host (sometimes just on one host!) because IPAM must wait for a consensus to initialise itself. Assuming there's no way around the consensus, one major difficulty is that there's no indication of why nothing is happening (or *that* nothing is happening).

However, it would be difficult to output indications of progress (or lack thereof) without interfering with the running of containers, since we would need to output them on the container's stderr. At best this is inelegant, and in many cases it would break apps.

Another approach would be to make weave launch synchronous with respect to initialisation. There's no particular problem with outputting progress indications while starting weave. We can give the user an option not to wait, and also provide a command to wait explicitly. This way people at least have a tool to determine when it is OK to start using weave, which they can use in whichever way suits them.

**Comment by rade** [comment]
See also #1267.

**Comment by rade** [comment]
> Another approach would be to make weave launch synchronous with respect to initialisation.

IPAM initialisation is deferred until an IP is requested. That way one can run `weave launch` across multiple machines w/o having to introduce any forking/backgrounding.

So I think a separate `weave wait` command is the way to go. It could show incremental progress, but imo that's best left to a follow-on issue.

**Comment by squaremo** [comment]
> So I think a separate weave wait command is the way to go.

Choosing between the default being to synchronise and the default being to defer initialisation is a user experience issue.

I'd lean towards the default being to wait, since that means a new user will be more likely figure out what the problem is -- weave will not return control until it's ready, and ideally will say something like "waiting for other hosts".

If the default is not to wait .. well, that's basically what gives rise to this bug.

**Comment by rade** [comment]
One reason for the current behaviour (of not waiting) is backward compatibility. You can happily run `weave launch

**Comment by squaremo** [comment]
> One reason for the current behaviour (of not waiting) is backward compatibility

Right: people might be used to starting weave on one host of many, then launching containers straight away (if not relying on allocated IP addresses, it'll even work!); and those people will be surprised that they have to do things in a different order. If doing so from a console, we can hope they'd see a message "waiting for other <n> hosts to start; use --no-wait-for-init to skip when starting".

If we add a `weave wait-for-init`, we would have to go and change documentation to recommend its use. And to make sure people don't trip themselves up by not quite understanding the circumstances in which it has to be called, we'd have to recommend its use every time you're using weave on multiple hosts, or even just every time you're using weave. In other words, we'd just replace `weave launch ...` with `weave launch ... && weave wait-for-init` for most circumstances.

So: is it worse to behave mysteriously for some new users; or, to introduce a surprising change of behaviour for some existing users? I lean towards the latter, since existing users will at least have an mental model of what's going on, and we have the opportunity to tell them about new behaviour in release notes.

**Comment by bboreham** [comment]
Note that the 1.0 release _does_ wait at `weave launch`, because it needs an IP address for weaveDNS.  Since then we have removed that need, so current master version does not wait.

So, I imagine re-introducing the wait will not confuse very many people.  And it would definitely be nicer to tell users what's going on.

Version 1.0 `weave launch-router` does not wait.  But I think if we change `weave launch` to wait, for consistency we should change `launch-router` also, and add a `--no-wait` option for people that really want it.

**Comment by rade** [comment]
Please explain how you'd script the startup of an n-node cluster. Surely a
very common scenario. A blocking launch seems massively inconvenient here,
having to spawn n sub-processes and dealing with the associated error
handling nightmares.

More generally, I suggest that before we make any changes here we go
through all the scenarios of cluster formation and write down the ideal
steps we'd like to see for these.

**Comment by bboreham** [comment]
That seems to be a different issue.  The people having trouble are starting weave with very simple, independent scripts on each host.

**Comment by rade** [comment]
Yes, it is a different scenario. We don't want to optimise one scenario at
the expense of others. At least not unintentionally. Hence the need to
examine all scenarios. I doubt there are very many.

**Comment by bboreham** [comment]
We have added `weave prime` in version 1.5, which seems to address the main item in this issue.

**Comment by bboreham** [comment]
We have documented various ways to initialize and scale a cluster; is there anything left to do here?

**Comment by rade** [comment]
I am struggling to think of improvements to the current situation.
