### ISSUE TITLE
container start HostConfig breaks container configuration

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1368]
As noted in #1258, the Docker remote API allows the HostConfig attributes to be set when _starting_ a container. (They are supposed to be set when _creating_)

The specific case there (Kubernetes) uses `--net=container:(another container)`, so is fixed by #1314, but if someone did the same thing and specified `--net=host` in the start request then `weavewait` would hang because there is no `ethwe` interface.

**Comment by rade** [comment]
> `--net=(another container)` is fixed by #1314 

...iff another container is attached to weave.

> specified `--net=host`

or `--net=(another container that is not attached to weave)`

**Comment by rade** [comment]
We've just had a user run into this. Specifically, their client is posting the following
```
POST /v1.15/containers/f1e8b4e4c692e70b4cae1c2aa6afe22f10c3550af7da340a2f623a58d582555f/start HTTP/1.1
Host: 127.0.0.1:12375
User-Agent: Go 1.1 package http
Content-Length: 632
Content-Type: application/json
Accept-Encoding: gzip

{"Binds":["769f6375-b847-4182-bd5e-c0ed9430c5fb:/root"],"ContainerIDFile":"","LxcConf":null,"Memory":0,"MemorySwap":0,"CpuShares":0,"CpuPeriod":0,"CpusetCpus":"","CpusetMems":"","CpuQuota":0,"BlkioWeight":0,"OomKillDisable":false,"Privileged":false,"PortBindings":null,"Links":[],"PublishAllPorts":false,"Dns":null,"DnsSearch":null,"ExtraHosts":null,"VolumesFrom":null,"Devices":null,"NetworkMode":"","IpcMode":"","PidMode":"","UTSMode":"","CapAdd":null,"CapDrop":null,"RestartPolicy":{"Name":"","MaximumRetryCount":0},"SecurityOpt":null,"ReadonlyRootfs":false,"Ulimits":null,"LogConfig":{"type":"","config":null},"CgroupParent":""}
```

Note in particular the null values for `Dns` and `DnsSearch`. These end up stomping on the values injected by the proxy on container creation; a subsequent `inspect` of the container returns the null values.

**Comment by rade** [comment]
TBH, I am not that bothered about the `--net` issue. I suggest we don't worry about it unless some users bump into it.

The issue with DNS settings needs fixing. And should be easy to fix too. Presumably the weavewait volume mount can get stomped on too. I wonder why that didn't cause any problems for the user. Perhaps Docker only pays attention to some fields in a 'start' HostConfig? Or has some merge semantics for some of them?

**Comment by paulbellamy** [comment]
Binds in HostConfig are merged.

**Comment by paulbellamy** [comment]
Fixing in 1.2, as the /start handler has changed quite a bit from 1.1 to 1.2, and I don't want to do it twice.
