### ISSUE TITLE
`weave dns-add/remove` IP addresses should be optional

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1369]
One should be able to invoke

```
$ weave dns-add container1 -h foo.weave.local
```
which should add DNS records for all the weave IP addresses of that container.

Ditto for removal.

This is actually made painfully obvious by the current `dns-add` example in the [docs](http://docs.weave.works/weave/latest_release/weavedns.html#add-remove):
> If you want to give the container a name in DNS *other* than its hostname, you can register it using the `dns-add` command. For example:
> ```bash
> $ C=$(docker run -e WEAVE_CIDR=10.2.1.27/24 -ti ubuntu)
> $ weave dns-add 10.2.1.27 $C -h pingme2.weave.local
> ```

which really should be

```bash
$ C=$(docker run -ti ubuntu)
$ weave dns-add $C -h pingme2.weave.local
```

@awh

**Comment by awh** [comment]
> @awh

You rang?

**Comment by rade** [comment]
> You rang?

Just in case you fancy working on this :)

**Comment by awh** [comment]
> Just in case you fancy working on this :)

:) Yep will take a look after I've worked out this niggle with the release script.
