### ISSUE TITLE
We shouldn't be modifying unintended fields when creating containers/execs

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#1371]
The side effect of decoding/encoding the request body with go-dockerclient, is that it can encode it differently than the client had meant to. This caused a failure in https://github.com/weaveworks/weave/pull/1367, and could generally cause mangling of requests (e.g. if the fields present in go-dockerclient disagree with the docker server).

We should use a less invasive way of modifying the incoming requests.

Specific instance of this bug is the failure in [test_valid_no_config_specified ](https://github.com/docker/docker-py/blame/db1a93fd27a7627300c1fd54040d2f727ada78a4/tests/integration_test.py#L305)

**Comment by rade** [comment]
I am reluctant to make such a significant change in 1.1 so close to a release, though I see you are already half-doing that in #1376.

Would updating the go docker client to the latest version - which iirc happens anyway during the release process - ameliorate this issue?

**Comment by paulbellamy** [comment]
I agree it's a bit big for 1.1.

Updating the go docker client may temporarily help, but won't solve other issues (like with volume drivers). The client makes a few simplifying assumptions about the format of the data which are approriate for a client, but not specific enough for the server.

**Comment by rade** [comment]
> won't solve other issues (like with volume drivers)

Oh. Really? The most recent go docker client ignores the volume driver settings?

**Comment by paulbellamy** [comment]
Ah, no, looking again, it does handle them. It's more that longer-term when the API changes the go client (being stricter) will break more often.

**Comment by rade** [comment]
could somebody please check that #1378 gets fixed when running with a proxy built with the latest golang docker client?

**Comment by bboreham** [comment]
On it.

**Comment by bboreham** [comment]
It does not get fixed; go-dockerclient does not yet know anything about the new `VolumeDriver` parameter.

**Comment by bboreham** [comment]
So I submitted https://github.com/fsouza/go-dockerclient/pull/367

**Comment by peter-edge** [comment]
@bboreham let me know if there's anything else missing on the volumes side of go-dockerclient, I think we might be both trying to accomplish similar things https://github.com/fsouza/go-dockerclient/pull/362

**Comment by bboreham** [comment]
@peter-edge ok, but we're reacting to a user issue #1378; I eyeballed the Docker change to look for other missing fields but don't have any good basis to know for sure.

**Comment by errordeveloper** [comment]
From testing latest change (32a82f2d0e83) on Kubernetes, one rather [critical issue popped-up](https://gist.github.com/errordeveloper/a13b33a342bed5a9652e#file-inspect-diff).

**Comment by rade** [comment]
@errordeveloper Please open a separate bug for that!

**Comment by errordeveloper** [comment]
> Please open a separate bug for that!

#1390
