### ISSUE TITLE
volume driver api set to local

### ISSUE THREAD

**Issue by baopx** [weaveworks/weave#1378]
volume driver does not work when `docker run` talks to weave proxy.

btrfs is a docker volume driver.
i.e.)

```
# Start docker run busybox
VOL_ID=<btrfs volume ID>

docker run -ti --volume-driver=btrfs -v $VOL_ID:/data busybox
$ docker inspect 2141a814ea4f
....
    "Mounts": [
        {
            "Name": "e51109fd-c79e-483d-849a-cddab773d796",
            "Source": "/var/lib/osd/mounts/e51109fd-c79e-483d-849a-cddab773d796",
            "Destination": "/data",
            "Driver": "btrfs",
            "Mode": "z",
            "RW": true
        }
    ],
...
```

With weave:
```
$ echo $DOCKER_HOST
tcp://127.0.0.1:12375
docker run -ti --volume-driver=btrfs -v $VOL_ID:/data busybox
$  docker inspect 42fb56cd4ee4
    "Mounts": [
        {
            "Name": "e51109fd-c79e-483d-849a-cddab773d796",
            "Source": "/var/lib/docker/volumes/e51109fd-c79e-483d-849a-cddab773d796/_data",
            "Destination": "/data",
            "Driver": "local",
            "Mode": "z",
            "RW": true
        },
....
```

Differences is with weave, Driver is set to local and the specified driver is not invoked.

**Comment by bboreham** [comment]
Suspected to be related to #1371

**Comment by bboreham** [comment]
I managed to recreate this issue using the 'convoy' driver, following the installation instructions [here](https://github.com/rancher/convoy#quick-start-guide)

The reason it is not working is because we don't pass through the `VolumeDriver` parameter in the JSON, basically the same issue as #1371.

**Comment by rade** [comment]
@bboreham now that https://github.com/fsouza/go-dockerclient/pull/367 is merged, this *should* go away when we build with the latest go-dockerclient, right? Have you tested that?

**Comment by bboreham** [comment]
Yes, I tested it with my local copy of `go-dockerclient` before the merge, and the symptom of `docker inspect` saying "Driver: local" went away.

**Comment by baopx** [comment]
Thanks guys, should I expect this to be in 1.1.0?  When will 1.1.0 be available?

**Comment by rade** [comment]
> should I expect this to be in 1.1.0?

yes. hence the milestone. :)

> When will 1.1.0 be available?

next week, hopefully. no promises.
