### ISSUE TITLE
load-balancing breaks at >13 containers

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1382]
Using `weavedns` 1.0.2 I can see that once there more then 13 containers with the same name I start getting negative results.

**Comment by errordeveloper** [comment]
However, I can see all records in `weave status`.

**Comment by errordeveloper** [comment]
This can be reproduced by following the [Mesos guide](weave.works/guides/platform/mesos-marathon/os/centos/cloud/vagrant/index.html) and modifying the `outyet.json` file (difference is that the value of `cpus` attribute is lower and `instances` is higher).

```javascript
{
  "id": "outyet",
  "cpus": 0.02,
  "mem": 20.0,
  "instances": 13,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "docker.io/goexample/outyet",
      "network": "BRIDGE",
      "parameters": [
        { "key": "hostname", "value": "outyet.weave.local" }
      ]
    }
  }
}
```

Once that deployed, I ran an interactive container with `while true; do ping -c1 outyet; done` and observe `ping: bad address 'outyet'` shortly after 14th instance gets started.

**Comment by errordeveloper** [comment]
I confirm that this doesn't relate to Mesos, i.e. using `docker run -d --hostname=outyet.weave.local docker.io/goexample/outyet`.

**Comment by errordeveloper** [comment]
I am not able to reproduce it with dig.

**Comment by inercia** [comment]
@errordeveloper I'll try to follow your Mesos guide and take a look at this problem...

**Comment by rade** [comment]
> I'll try to follow your Mesos guide

@errordeveloper says he has reproduced that w/o mesos. I.e. simply by starting 14 containers with the same hostname. All on a single host.

**Comment by inercia** [comment]
Oh, ok, I'll start 14 containers with the same name then... maybe it has to do with UDP packet truncation...

**Comment by rade** [comment]
> maybe it has to do with UDP packet truncation...

but this is all one one host. and we only ever return one record to clients.

**Comment by inercia** [comment]
@errordeveloper can you reproduce this error with less than 13 containers?

**Comment by errordeveloper** [comment]
@inercia no, it's only at 14 or more that I have determined it breaks.

**Comment by errordeveloper** [comment]
We also still need to test this agains new DNS implementation in master, which haven't had the time for.

**Comment by tomwilkie** [comment]
Master has integration tests for this; we know it works.

**Comment by rade** [comment]
> Master has integration tests for this; we know it works.

In which case let's not bother fixing this.

**Comment by tomwilkie** [comment]
"we know it works" on master; I can believe there is a problem on 1.0.x

**Comment by rade** [comment]
>  I can believe there is a problem on 1.0.x

yes, but it's not worth fixing.
