### ISSUE TITLE
Release process should only update DockerHub `latest` images when releasing from master

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1383]

**Comment by awh** [comment]
@rade how do you feel about `bin/release publish` switching its 'latest' update behaviour based on detecting an vX.Y.Z version string where Z != 0?

**Comment by rade** [comment]
Fine by me. But I haven't given this much thought. @squaremo?

**Comment by awh** [comment]
In that case... does it make sense to drive the `--pre-release` behaviour from the same inference, and remove that flag too?

**Comment by rade** [comment]
maybe :)

**Comment by awh** [comment]
It is a bit prescriptive, but it removes opportunities for human error...

**Comment by rade** [comment]
> it removes opportunities for human error...

That's a good thing indeed. Less to think about and get wrong.
