### ISSUE TITLE
CLI for adding/removing non-container DNS records

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1385]
The weaveDNS API permits the addition/removal of records that are not associated with containers. But this functionality is not available in the CLI - `weave dns-add|remove` require a container name/id.

We should remove that restriction. Quite how to express that in the CLI is tbd.

This has been requested by a user.

**Comment by inercia** [comment]
Would this mean that users could be able to add arbitrary A-records in the distributed database?

**Comment by rade** [comment]
> Would this mean that users could be able to add arbitrary A-records in the distributed database?

No, only records in the weavedns domain. I am hoping(!) that is what the current `weave dns-add` enforces.

**Comment by inercia** [comment]
But that wouldn't be a good idea once we have the gossip-dns in the production release, right? I mean that populating the distributed database with entries like `srv-<SOME-NUMBER>.weave.local.` = `<SOME-IP>` wouldn't be the ideal scenario for gossiping...

**Comment by rade** [comment]
What's the issue?

I can see one fundamental problem: weavedns entries are necessarily associated with a peer, and when that peer disappears the entries too disappear.

Is that the problem you were forseeing?

**Comment by inercia** [comment]
My concern is that, if the distributed database becomes a general DNS database where a user could introduce thoushands of A-records (even if they are in the weavedns domain), it would potentially increase latency to the database propagation...

**Comment by tomwilkie** [comment]
There is no performance problems associated with this; individual records
are gossiped when they are added and removed, the whole databases is only
gossiped periodically.

Matthias does point out an issue though; records are owned by a host and
their failure domains are assumed to align. I'll give a little thought to
what might happen if a record is not owned by a host; I suspect 'all' we'd
need to do is increase the tombstone timeout on those records.

**Comment by dpw** [comment]
There is a substitute suggested by @errordeveloper a few days ago.  Although you have to supply a container name to `dns-add`, you can supply any container name, including e.g. `weave` for the weave router container.  So:

    weave dns-add 8.8.8.8 weave -h foo.weave.local

works.

That name will be lost if the weave router is stopped, but that would also be the case for the simple fix to address this issue anyway.
