### ISSUE TITLE
with `--rewrite-inspect` proxy modifies how integers are marshalled

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1390]
From testing latest change (32a82f2d0e83) on Kubernetes, one rather [critical issue popped-up](https://gist.github.com/errordeveloper/a13b33a342bed5a9652e#file-inspect-diff). Essentially what happens is that we somehow end-up marshalling integers in scientific notation and the parser on the other end fail with `json: cannot unmarshal number 5.24288e+07 into Go value of type int64`.

**Comment by rade** [comment]
[looks like](http://stackoverflow.com/questions/22343083/json-marshaling-with-long-numbers-in-golang-gives-floating-point-number) we need [UseNumber()](http://golang.org/pkg/encoding/json/#Decoder.UseNumber).
