### ISSUE TITLE
fix sleeve wire compatibility with 1.1

### ISSUE THREAD

**Issue by dpw** [weaveworks/weave#1396]
#991 broke wire compatibility with 1.1.  Fixing that in itself will be fairly straightforward.  But fast datapath will introduce much trickier compatibility issues, so we probably want to fix them all at once.

Details: In 1.1, `LocalConnection handleProtocolMessage` dispatches some UDP-forwarding message types directly.  Post #991, these are combined into a `ProtocolOverlayControlMsg` message type, which gets handed to the forwarder to deal with them.  To restore compatibility, we'll have to reintroduce those legacy message types, and pass the message code down to the forwarder so `sleeveForwarder` can dispatch on it.  And similarly for the control message send side.

**Comment by dpw** [comment]
Some notes about the 1.1 -> 1.2 -> 1.3 compatibility path I envisage, while I have the details in mind.

In 1.1, the sleeve messages on the TCP connection look like:

|Tag|Payload|
|---|-------|
|ConnectionEstablished, FragmentationReceived or PMTUVerified|...|

Post-#991, there is also the hypothetical possibility of other Overlays, which get to define their own message type codes within the payload under a single OverlayControlMsg tag:

|Tag|Payload|
|---|-------|
|OverlayControlMsg|...|

The target state is to use the post-#991/pre-#1451 approach.  But, OverlaySwitch (in #1438) will be used in order to multiplex multiple Overlays.  OverlaySwitch puts a "overlay index" byte at the start of the message, so:

|Tag|Payload|
|---|-------|
|OverlayControlMsg|overlay index, ...|

And in terms of the code in `overlay.go` and `sleeve.go`, the target state is to return things to more or less as they were before #1451.  So in the case of sleeve, the control messages begin with a message type byte.  (fastdp also has a message type byte, even though it only has one message type.)

|Tag|Payload|
|---|-------|
|OverlayControlMsg|overlay index, message type, ...|

In 1.2, `sleeve.go` will need to operate in two modes, as shown in the first and last illustrations above. Which mode is in operation will depend on whether OverlaySwitch is intervening, which is determined by the presence of the `Overlays` feature during connection initiation (no `Overlays` feature indicates a 1.1 router). As a transitional stage, OverlaySwitch will implement the message type byte, passing it to/from the subsidiary Overlay as the `tag` parameter.

In 1.3, we can drop compatibility with 1.1, and restore the `sleeve.go` code back to its pre-#1451 state, moving responsibility for the message type byte out of OverlaySwitch.  The code will be tidier, but the protocol will not actually change from 1.2.

**Comment by awh** [comment]
Closed by #1451.
