### ISSUE TITLE
script, images and release name have wrong version tag (vX.Y.Z instead of X.Y.Z)

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1397]
Released weaves used to embed a version number of the form `X.Y.Z` in the script, and that is also how the docker images were tagged, and the release was named ("Weave X.Y.Z"). With the 1.1.0 release, the embedded version number, image tag and release name are of the form `vX.Y.Z`, i.e. there is now a `v` prefix.

Looks like this is an unintended (or at least unmentioned!) consequence of #1372.

I am not immediately aware of any disastrous consequences, but a quick look around Dockerhub confirms that the convention is to tag with "naked" version numbers, sans "v" prefix. Which is why we did it that way until now.

**Comment by awh** [comment]
The removal of the special 'v' handling is mentioned in the caveats section of #1372, but the fact that it extended to the docker tags wasn't explicitly called out. I removed it to support pre-release tags, however since the addition of branch type inferencing in #1383 it can easily go back in...
