### ISSUE TITLE
`weave report` example rendered incorrectly

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1398]
The [docs](http://docs.weave.works/weave/latest_release/troubleshooting.html#weave-report) show
```
$ weave report -f ''
```

The source says
```
$ weave report -f '{{{.DNS.Domain}}'
```

which is a) wrong (notice the unbalanced curly braces), and b) evidently doesn't render properly.

I would fix this myself, but first a) latest_release_doc_updates needs to be brought up to date with the 1.1.0 release, and b) we need a 1.1 branch.

**Comment by awh** [comment]
http://a5anka.github.io/escaping-double-curly-braces-in-jekyll/

**Comment by awh** [comment]
Closed by 676127893f19bb26d0beaf538f03b1c2487cb00c.
