### ISSUE TITLE
Fix the "tlsargs" thing on the Mac

### ISSUE THREAD

**Issue by Crazee** [weaveworks/weave#1407]
Tried the new 1.1.0 version of Weave and found that, contrary to promises, that "weave launch" doesn't do everything for you.  You don't actually get the proxy part.  Then found the hand-waving in the docs about "You've got OSX, well you've got to do this hack":

tlsargs=$(docker-machine ssh weave-1 \
  "cat /proc/\$(pgrep /usr/local/bin/docker)/cmdline | tr '\0' '\n' | grep ^--tls | tr '\n' ' '")
weave launch-proxy $tlsargs

Etc.  "weave launch" is just a shell script, right?  Why can't it do this itself. ("docker-machine active" tells you the name of the current host (Unless you've already got weaveproxy running, at which point it just tells you "Error getting active host: Active host not found" (another bug).)

**Comment by rade** [comment]
dup of #1285

**Comment by Crazee** [comment]
It's only a dup if you're actually gonna fix the code in 1285 and not just point to a hack workaround.

**Comment by rade** [comment]
> It's only a dup if you're actually gonna fix the code in 1285 and not just point to a hack workaround.

Notice the PR attached to #1285.
