### ISSUE TITLE
proxy launch fails with `use of closed network connection` error

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1410]
Launching the weave proxy fails with `Error response from daemon: use of closed network connection`

Broken by [this commit](https://github.com/fsouza/go-dockerclient/commit/edc2bd38d8fa79581371ea78b3c09935877a1ade)

**Comment by rade** [comment]
Presumably this is a bug on go-dockerclient, in which case we should file a bug there. On the off chance that it isn't, we need to get a fix into 1.1.1.

**Comment by awh** [comment]
You can configure the proxy to use `tcp://` instead of `unix://` as a workaround whilst we wait for the issue to be addressed upstream...

**Comment by awh** [comment]
Fixed upstream by https://github.com/fsouza/go-dockerclient/commit/c9ad0ce23f68428421adfc6ced9e6123f54788a5.
