### ISSUE TITLE
`weave version` broken unless built with Go 1.5

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1412]
#1386 contains https://github.com/weaveworks/weave/pull/1386/files#diff-b67911656ef5d18c4ae36cb6741b7965L46, which broke this.

From https://golang.org/cmd/link/
> -X importpath.name=value
	Set the value of the string variable in importpath named name to value.
	Note that before Go 1.5 this option took two separate arguments.
	Now it takes one argument split on the first = sign.

The = notation does not work in 1.4; just gets ignored.

**Comment by rade** [comment]
Because of the impact this has on snapshot releases we need to fix this urgently. @tomwilkie @dpw

**Comment by dpw** [comment]
I've reverted the relevant commit.  @rade, please verify.
