### ISSUE TITLE
Not discovering containers

### ISSUE THREAD

**Issue by slde-gorillaman** [weaveworks/weave#1416]
Hi,

I have just followed the readme, however only on one host. When I start I container, weave status does not show any entries. Am I missing something?

**Comment by rade** [comment]
`weave status does not show any entries`

It is not clear what you mean by that. Please post the output of `weave status` and explain what you think is wrong with it.

**Comment by rade** [comment]
@slde-gorillaman if you have any more info on this, please re-open.
