### ISSUE TITLE
Can't create container on new version

### ISSUE THREAD

**Issue by nichliu** [weaveworks/weave#1417]
After I upgrade to newest version of weave, can't create any container after I execute 
eval $(weave env), it will froze.

I wait long time and I have to use Ctrl + c to stop the process and get this error 
Error response from daemon: invalid CIDR address: Allocate

If I run weave launch and don't run  eval $(weave env), I can create container as normal

**Comment by nichliu** [comment]
After I upgrade to newest version of weave, can't create any container after I execute 
eval $(weave env), it will froze.

I wait long time and I have to use Ctrl + c to stop the process and get this error 
Error response from daemon: invalid CIDR address: Allocate

If I run weave launch and don't run eval $(weave env), I can create container as normal

**Comment by rade** [comment]
I suspect your weave network is lacking IPAM consensus, presumably because some peers are not connected. Check `weave status`.

This is *not* a new behaviour in 1.1.

**Comment by nichliu** [comment]
Thank you. I fixed it.

I am upgrading old weave to new version, that caused this issue, if there's peer connected to the new weave server used older version of weave, this will happen.

After I start all the new sever, all working. 

Thanks

**Comment by rade** [comment]
>  if there's peer connected to the new weave server used older version of weave, this will happen.

Right. See #1419.
