### ISSUE TITLE
mangled error when `weave attach` is cancelled

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1418]
```
$ weave launch --init-peer-count=2
$ eval $(weave env)
$ docker run -ti ubuntu
^CError response from daemon: invalid CIDR address: Allocate
```

Instrumenting the proxy's `weave attach` invocation yields

```
...
+ curl --connect-timeout 3 -s -S -X POST http://172.17.0.10:6784/ip/db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab?check-alive=true
+ IPAM_CIDRS=Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled
+ [ Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled = 404 page not found ]
+ ALL_CIDRS=Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled
+ [ 0 -gt 0 ]
+ [ -n 1 ]
+ command_exists weavehosts
+ command -v weavehosts
+ docker inspect -f {{.HostsPath}} {{.Config.Hostname}} db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab
+ PATH_AND_NAME=/var/lib/docker/containers/db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab/hosts db1bb81e6866
+ weavehosts /var/lib/docker/containers/db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab/hosts db1bb81e6866 Allocate request for db1bb81e68660dda3bd19e501fec236ff1da6e1d6a63a067a457468ea7492dab cancelled
```

i.e. the IP allocation request returns a message which we subsequently attempt to parse as a CIDR.

Deduced from #1417.

**Comment by bboreham** [comment]
Any idea how that cancellation is happening?  If you control-c the `curl` then `weave` will see the socket close and cancel the request, but (a) you're not doing that and (b) that would leave no path for the response to come back.

**Comment by rade** [comment]
> Any idea how that cancellation is happening?

I was wondering that too. Certainly ^C-ing a `weave attach` directly does not produce this behaviour.

**Comment by bboreham** [comment]
What's happening is that the container has started, and is waiting for its weave network interface to appear.  So when you <kbd>ctrl-C</kbd> the docker client, the docker daemon kills the container, weave sees a "die" event, and weave cancels the address allocation request for that container.

Currently, cancellation is reported as a `400` "bad request" error (as is every other unsuccessful attempt).  It strikes me that `204` "no content" might be a good way to indicate there is no response, but nothing has gone wrong inside IPAM or in the request.
