### ISSUE TITLE
Docker weave network plug-in refresh

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1420]
Refresh the weave Docker network plug-in to account for changes in Docker 1.9+.

**Comment by awh** [comment]
Probably requires #676.

**Comment by rade** [comment]
I've moved this out of 1.2.

**Comment by rade** [comment]
@squaremo you have done this, haven't you?

**Comment by squaremo** [comment]
I have done "to account for changes in Docker 1.9+" but I have not done "to account for changes in Weave 1.2+", specifically fast data path. See https://github.com/weaveworks/docker-plugin/issues/35

**Comment by rade** [comment]
This was done as part of the general plug-in work in weave 1.4.
