### ISSUE TITLE
Identify Docker 1.9 blockers

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1422]
Docker 1.9 introduces further changes to networking and plugins that impact weave's existing features. These must be identified and filed as issues for resolution in the 1.2 milestone. This involves:

* Test with experimental Docker and record issues. There is an `experimental_docker` branch in the main repo that adjusts the build and smoketest Vagrantfiles to use the experimental docker repo for such testing
* Investigate other features planned for Docker 1.9

Issues identified so far:

- [x] #1374 - Docker 1.9 breaks resolution of unqualified names
- [x] #1565 - `666_abuse_start_of_test.sh` fails due to  docker/docker#17026 (`docker inspect` issue in 1.9.0-rc1)

**Comment by awh** [comment]
I have run the smoke tests using our `experimental_docker` branch and they all pass, despite #1374 (none of our tests attempt unqualified resolution of container named derived hostnames).

**Comment by rade** [comment]
https://github.com/docker/docker/pull/16645 provides a glimpse of what is coming up.

**Comment by mavenugo** [comment]
@rade @awh pls feel free to jump in #docker-network IRC channel and we can discuss on any of the 1.9 related changes.

**Comment by rade** [comment]
@mavenugo https://github.com/docker/libnetwork/issues/519 causes us major headaches.

**Comment by rade** [comment]
@awh do the tests pass now, modulo the `docker inspect` issue?

**Comment by awh** [comment]
> @awh do the tests pass now, modulo the docker inspect issue?

They do.

**Comment by awh** [comment]
That's with 1.9-rc1

**Comment by rade** [comment]
afaict the inspect issue only affects our tests. and we could "fix" that by moving the dns items first in the inspect format.
