### ISSUE TITLE
Update GCE images to use Docker 1.8.2

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1433]

**Comment by tomwilkie** [comment]
Need to update here: https://github.com/weaveworks/weave/blob/master/test/gce.sh#L68, generate a new image, and then update here: https://github.com/weaveworks/weave/blob/master/test/gce.sh#L14

**Comment by tomwilkie** [comment]
This is needed to fix https://github.com/weaveworks/weave/issues/1437

**Comment by awh** [comment]
> generate a new image

Wat.

**Comment by awh** [comment]
Also we are lacking the requisite credentials I think?

**Comment by tomwilkie** [comment]
I'll do it next week.  Credentials are checked in, you just need the password to decrypt them.  IM me for it.

**Comment by rade** [comment]
#1467 incorporated this same change into 1.1.
