### ISSUE TITLE
make weave build & work with go 1.5

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1436]
See  #1386 for a failed attempt.

**Comment by tomwilkie** [comment]
Relevant: https://github.com/weaveworks/scope/pull/488

**Comment by rade** [comment]
ah! "The old format still works in 1.5, just spits a warning.". I'd be happy with that, at least for the time being. so it seems we could just resurrectt #1386 minus that change.

**Comment by rade** [comment]
> so it seems we could just resurrectt #1386 minus that change.

Actually @dpw only reverted the Makefile change, so there is even less to do here (if anything?)

**Comment by dpw** [comment]
I've reinstated the other Makefile changes that weren't responsible for the problems with 1.4: https://github.com/weaveworks/weave/commit/a67b9f566a376fcf4da3f3e3c164a064c9be7365

So now we have all of #1386 back, except for the `-X` change, which just means we get a warning with go-1.5.
