### ISSUE TITLE
IP allocator and DNS should not depend on Docker

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1443]
...as user should be able to control IP addresses deallocation and removal of DNS record out of band.

**Comment by rade** [comment]
You *can* add/remove DNS records out of band. *and* allocate/deallocate IP addresses out of band.

**Comment by squaremo** [comment]
> user should be able to control IP addresses deallocation and removal of DNS record out of band

They can already, but that's beside the point.

The router, DNS, and IPAm shouldn't assume an integration with Docker; e.g., it should be possible to run weave using rkt (if you are prepared to do some work yourself)

**Comment by rade** [comment]
Umm. So simply an option to disable to docker interaction would work?

**Comment by errordeveloper** [comment]
> Umm. So simply an option to disable to docker interaction would work?

Yes.

**Comment by squaremo** [comment]
> Umm. So simply an option to disable to docker interaction would work?

That would work. Would it be a good design?

**Comment by rade** [comment]
It would be a good-enough design, and something that might actually have a chance to get done this year.

**Comment by rade** [comment]
Are we aware of any immediate need for this?

**Comment by squaremo** [comment]
> Are we aware of any immediate need for this?

No; it was suggested by Ilya when thinking about using weave to provide networking for rkt containers.

It can also be considered an item of technical debt.
