### ISSUE TITLE
Proxy volume mount of /var/run prevents netns cleanup

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1455]
The weaveproxy volume mount of `/var/run` captures references to extant Docker network namespaces in `/var/run/docker/netns` due to Docker's use of `MS_REC` (`mount --rbind`) on bind mount creation. This prevents associated veths from being cleaned up on container exit, potentially resulting in duplicate IP address use and other mayhem.

Reproducible on Docker 1.7.1 but not Docker 1.8.2 (**Edit** - no longer true - see below)

**Comment by dpw** [comment]
I've found the relevant code difference between docker 1.7.1 and 1.8.2 that causes 1.7.1 to bind-mount the netns handles into `/var/run/docker/netns` and 1.8.2 not.  It's dispersed, so hard to point to.  There doesn't appear to be anything we can do to prevent this in behaviour in 1.7.1.

**Comment by rade** [comment]
do we know which version of docker introduced the change?

**Comment by awh** [comment]
> do we know which of 1.8.0, 1.8.1 or 1.8.2 introduced the change?

I can't reproduce it in 1.8.0, 1.81 or 1.8.2.

**Comment by rade** [comment]
iirc @dpw said that older versions of docker don't suffer from this. So which version introduced the problem?

**Comment by dpw** [comment]
I *don't* see the problem with docker-1.5.0 on ubuntu 15.04. But Adam testing suggest that the problem might not only be dependent on the docker version.

**Comment by dpw** [comment]
Confirming Adam's finding: With docker-1.7.1 on ubuntu 15.04 the dangling veth disappears within a minute, and even immediately after container creation, there are no `/var/run/docker/netns/*` entries in `/proc/mounts`.  That differs from the behaviour of docker-1.7.1 on ubuntu 14.04 in both respects.  `docker version` and `apt-cache show lxc-docker` confirm that it is exactly the same version of docker.

**Comment by awh** [comment]
My current results:

Docker 1.7.1, 1.8.0, 1.8.1, 1.8.2 all unaffected on Ubuntu 15.04
Docker 1.7.1 affected on 14.10

Test of 1.8.2 + 15.04 in progress...

**Comment by awh** [comment]
> older versions of docker don't suffer from this. So which version introduced the problem?

Ubuntu :smile:

Docker 1.8.2 + Ubuntu 14.10 has the same issue - netns entries in `/proc/mounts` and persistent dangling veth. Confirmed the other end of the veth is trapped inside the weaveproxy mount namespace with David's improved scan script.

**Comment by awh** [comment]
Ubuntu 14.10 is 3.16.0-37
Ubuntu 15.04 is 3.19.0-21

**Comment by fermayo** [comment]
I assume Ubuntu 14.04 is also affected?

**Comment by awh** [comment]
> I assume Ubuntu 14.04 is also affected?

Yes, same problem with 14.04 + 1.7.1. We're currently trying to understand why Docker behaves differently on 15.04.

**Comment by dpw** [comment]
I have got to the bottom of why on ubuntu 15.04 the net namespace handles from `/var/run/docker/netns` don't show up in `/proc/mounts`.

On ubuntu 15.04, the docker daemon is started by systemd.

`/lib/systemd/system/docker.service`:

    MountFlags=slave

`man systemd.exec`:

> MountFlags=
> Takes a mount propagation flag: shared, slave or private, which control whether mounts in the file system namespace set up for this unit's processes will receive or propagate mounts or unmounts. [...] Use slave to run processes so that none of their mounts and unmounts will propagate to the host.

So the docker daemon is in its own private mount namespace, and its mounts (including those in `/var/docker/netns`) do not propagate to the host namespace, and do not show up in the `/proc/mounts` of the host namespace.

But... when the docker daemon starts a container with `-v /var/run:/var/run`, it bind-mounts the `/var/run` from its own mount namespace, and the container snapshots the netns handle mounts under `/var/docker/netns`.  So this does not prevent the netns capture issue!

So why does the lingering `vethweplNNNNN` netdev disappear before 60 seconds passes?  I'm still not sure about that, but I have an idea which I will test tomorrow.

Note that if you edit `docker.service` and comment out that `Mount` line, then the `/var/docker/netns` mounts for containers do appear in `/proc/mounts`.  But the lingering `vethweplNNNNN` still disappears.  This demonstrates that the two phenomena are independent.

**Comment by dpw** [comment]
> So why does the lingering vethweplNNNNN netdev disappear before 60 seconds passes? I'm still not sure about that, but I have an idea which I will test tomorrow.

This one *is* due to a difference in kernel behaviour.

Docker 1.7.1 has similar "garbage collection" code to 1.8.x in `libnetwork/sandbox/namespace_linux.go`, which once a minute deletes unused files from `/var/run/docker/netns`. Note that the unmount of the netns mounts happens when the container is stopped, which usually allows the netns to go away. Garbage collection is just about deleting the mount point files that get left behind. (So it's unclear to me what the rationale for this arrangement is - why not delete the files immediately? Anyway...)

We can replicate this process with a netns created by `ip netns add`. Under docker 1.7.1 and ubuntu 14.04, first we create a netns and a container to capture it:

    # ip netns add foo
    # docker run -itd -v /var/run:/var/run --name=test ubuntu
    742bc8fca0f0d15df095f78039768018a5350b25c0363b70689e04143699d121
    # grep foo /proc/mounts
    proc /run/netns/foo proc rw,nosuid,nodev,noexec,relatime 0 0
    # docker exec test grep foo /proc/mounts
    proc /run/netns/foo proc rw,nosuid,nodev,noexec,relatime 0 0

Now if we try to delete the netns:

    # ip netns del foo
    Cannot remove namespace file "/var/run/netns/foo": Device or resource busy

`ip netns del` first unmounts the netns mount, then deletes the mount point file.  The unmount actually succeeded, it's the deletion that failed, as we can confirm:

    # rm /var/run/netns/foo
    rm: cannot remove ‘/var/run/netns/foo’: Device or resource busy

We can see that the netns mount is gone from the host, but it's still there in the container's mount ns:

    # grep foo /proc/mounts
    # docker exec test grep foo /proc/mounts
    proc /run/netns/foo proc rw,nosuid,nodev,noexec,relatime 0 0

It's that mount in the container that is preventing the deletion.  The container mount ns is independent of the host mount ns, so unmounting on the host does not affect the container.  But the underlying file system for `/var/run` is shared.  If we could delete the file, it would create an anomalous situation inside the container where a mount exists but its mount point is gone.  The kernel version in 14.04 (3.16.0-49 for me) avoids this by disallowing the deletion.

If you look at docker's `namespace_linux.go`, you'll see that the error value returned from the `os.Remove`  of the mount point files gets ignored.  So it tries to garbage collect them, but doesn't notice if it can't.

We can repeat the experiment on ubuntu 15.04 (still docker 1.7.1; kernel 3.19.0-28).  Except that the same `Mount=slave` issue that prevents docker's netns mounts showing up in the host `/proc/mount` prevents the netns created by `ip netns add foo` on the host showing up in containers.  So you have to restart the docker service with the `Mount` setting commented out to perform the same experiment.

If you do that, with the same setup as before, the `ip netns del foo` succeeds.  The mount is gone, both on the host and in the container:

    # grep foo /proc/mounts
    # docker exec test grep foo /proc/mounts

So this kernel version uses a different approach to prevent the mount-without-a-mount-point anomaly: when you delete a file that is a mount point in some other mount ns, it automatically unmounts them.

So under ubuntu 15.04, the garbage collection successfully removes the mount points, zapping any captured netns mounts, and so releasing netdevs in them.

Here's the relevant kernel commit: https://github.com/torvalds/linux/commit/8ed936b5671bfb33d89bc60bdcc7cf0470ba52fe

**Comment by dpw** [comment]
(Wrong button)

**Comment by dpw** [comment]
> I've found the relevant code difference between docker 1.7.1 and 1.8.2 that causes 1.7.1 to bind-mount the netns handles into /var/run/docker/netns and 1.8.2 not.

No I hadn't.

**Comment by awh** [comment]
@dpw fantastic piece of detective work, well done!

@fermayo there is a `linux-image-3.19.0-28-generic` package for trusty; I've just confirmed that it fixes the netns capture issue with the weave proxy, a result which should extend to other containers that volume mount `/var/run`.

**Comment by rade** [comment]
so is the overall conclusion that one needs to run a kernel >= 3.19 to fix this problem?

I reckon we should still prevent the proxy from mounting `/var/run`; in many setups it will be the only container doing this and hence the only reason why running on older kernels wouldn't work.

**Comment by awh** [comment]
> so is the overall conclusion that one needs to run a kernel >= 3.19 to fix this problem?

The commit David tracked down first appears in 3.18.0, but yes it is looking that way.

**Comment by rade** [comment]
so kernel >= 3.18.0?

**Comment by awh** [comment]
> so kernel >= 3.18.0?

````
awh@terraqueous:~/workspace/github.com/torvalds/linux [master] $ git tag --contains 8ed936 | grep -v rc
v3.18
v3.19
v4.0
v4.1
v4.2
````

**Comment by dpw** [comment]
The commit that introduced the libnetwork "garbage collection" thing, in case anyone else wants to try to figure out what it is intended to achieve: https://github.com/docker/libnetwork/commit/05462c27b2d9ea9574549bbc8ddcfd83b06ebd0e

**Comment by rade** [comment]
> The commit that introduced the libnetwork "garbage collection" thing, in case anyone else wants to try to figure out what it is intended to achieve: docker/libnetwork@05462c2

I [have asked](https://github.com/docker/libnetwork/pull/223#issuecomment-142628796)

**Comment by awh** [comment]
I have created a script that reproduces the scenario where the captured network namespace prevents a client container ('loadbalancer') from getting an updated MAC address when a service container ('frontend') is destroyed and recreated with a different MAC but the same IP (NB requires kernel prior to 3.18.0 as described above):

````
#!/bin/sh

echo ">>> Resetting environment"
docker rm -f $(docker ps -aq)
./weave launch

echo ">>> Launching loadbalancer container"
./weave run 10.2.0.1/24 -tid --name lb ubuntu
docker exec lb ip addr show dev ethwe
echo; echo; echo

echo ">>> Launching frontend container"
docker run --name fe -tid ubuntu
./weave attach 10.2.0.2/24 fe
docker exec fe ip addr show dev ethwe
echo; echo; echo

echo ">>> Pinging frontend from loadbalancer"
docker exec lb ping -c 1 10.2.0.2
docker exec lb ip neigh show
echo; echo; echo

echo ">>> Capturing frontend namespace with /var/run volume mount"
docker run -v /var/run:/var/run --name binder -tid ubuntu
echo; echo; echo

echo ">>> rm/run/attach frontend container"
docker rm -f fe

docker run --name fe -tid ubuntu
./weave attach 10.2.0.2/24 fe
docker exec fe ip addr show dev ethwe
echo; echo; echo

echo ">>> Pinging frontend from loadbalancer again"
docker exec lb ping -c 1 10.2.0.2
docker exec lb ip neigh show
echo; echo; echo
````
Here is a run where you can see the second ping succeeds but the neighbour cache has the old MAC:
````
>>> Launching loadbalancer container
b4b8ee07c863133e30f3b07774f939b0fdbc093b67b59325d02ca3e4985dbff4
374: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether c2:fe:14:ff:0c:24 brd ff:ff:ff:ff:ff:ff
    inet 10.2.0.1/24 scope global ethwe
       valid_lft forever preferred_lft forever
    inet6 fe80::c0fe:14ff:feff:c24/64 scope link tentative 
       valid_lft forever preferred_lft forever



>>> Launching frontend container
53b12a884b24cd0becf06486e5dcca7e5ebefd507c0eb4d3247c6fb5b3c1a517
10.2.0.2
378: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 82:74:61:8d:19:86 brd ff:ff:ff:ff:ff:ff
    inet 10.2.0.2/24 scope global ethwe
       valid_lft forever preferred_lft forever
    inet6 fe80::8074:61ff:fe8d:1986/64 scope link tentative 
       valid_lft forever preferred_lft forever



>>> Pinging frontend from loadbalancer
PING 10.2.0.2 (10.2.0.2) 56(84) bytes of data.
64 bytes from 10.2.0.2: icmp_seq=1 ttl=64 time=0.077 ms

--- 10.2.0.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.077/0.077/0.077/0.000 ms
10.2.0.2 dev ethwe lladdr 82:74:61:8d:19:86 REACHABLE



>>> Capturing frontend namespace with /var/run volume mount
3a006d17183abf86df0561f848b5fa05c28de632796f3b4b01a73b0c02f072b4



>>> rm/run/attach frontend container
fe
0ff07b8c8f0608fd0558f619e26d43b2c30071be9ee0ae0133bfd831e9ecf61c
10.2.0.2
384: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 96:18:68:4f:88:02 brd ff:ff:ff:ff:ff:ff
    inet 10.2.0.2/24 scope global ethwe
       valid_lft forever preferred_lft forever
    inet6 fe80::9418:68ff:fe4f:8802/64 scope link tentative 
       valid_lft forever preferred_lft forever



>>> Pinging frontend from loadbalancer again
PING 10.2.0.2 (10.2.0.2) 56(84) bytes of data.
64 bytes from 10.2.0.2: icmp_seq=1 ttl=64 time=0.052 ms

--- 10.2.0.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.052/0.052/0.052/0.000 ms
10.2.0.2 dev ethwe lladdr 82:74:61:8d:19:86 DELAY
````
This is the corresponding tcpdump of the weave bridge from the host:
````
$ sudo tcpdump -e -n -i weave arp or icmp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on weave, link-type EN10MB (Ethernet), capture size 262144 bytes
15:30:00.471053 c2:fe:14:ff:0c:24 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.1 (ff:ff:ff:ff:ff:ff) tell 10.2.0.1, length 28
15:30:01.515307 82:74:61:8d:19:86 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.2 (ff:ff:ff:ff:ff:ff) tell 10.2.0.2, length 28
15:30:02.227823 c2:fe:14:ff:0c:24 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.2 tell 10.2.0.1, length 28
15:30:02.227845 82:74:61:8d:19:86 > c2:fe:14:ff:0c:24, ethertype ARP (0x0806), length 42: Reply 10.2.0.2 is-at 82:74:61:8d:19:86, length 28
15:30:02.227853 c2:fe:14:ff:0c:24 > 82:74:61:8d:19:86, ethertype IPv4 (0x0800), length 98: 10.2.0.1 > 10.2.0.2: ICMP echo request, id 21, seq 1, length 64
15:30:02.227872 82:74:61:8d:19:86 > c2:fe:14:ff:0c:24, ethertype IPv4 (0x0800), length 98: 10.2.0.2 > 10.2.0.1: ICMP echo reply, id 21, seq 1, length 64
15:30:03.438629 96:18:68:4f:88:02 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.2 (ff:ff:ff:ff:ff:ff) tell 10.2.0.2, length 28
15:30:04.235245 82:74:61:8d:19:86 > c2:fe:14:ff:0c:24, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.1 tell 10.2.0.2, length 28
15:30:04.235275 c2:fe:14:ff:0c:24 > 82:74:61:8d:19:86, ethertype ARP (0x0806), length 42: Reply 10.2.0.1 is-at c2:fe:14:ff:0c:24, length 28
15:30:04.244479 c2:fe:14:ff:0c:24 > 82:74:61:8d:19:86, ethertype IPv4 (0x0800), length 98: 10.2.0.1 > 10.2.0.2: ICMP echo request, id 30, seq 1, length 64
15:30:04.244508 82:74:61:8d:19:86 > c2:fe:14:ff:0c:24, ethertype IPv4 (0x0800), length 98: 10.2.0.2 > 10.2.0.1: ICMP echo reply, id 30, seq 1, length 64
15:30:06.247825 c2:fe:14:ff:0c:24 > 82:74:61:8d:19:86, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.2 tell 10.2.0.1, length 28
15:30:06.247846 82:74:61:8d:19:86 > c2:fe:14:ff:0c:24, ethertype ARP (0x0806), length 42: Reply 10.2.0.2 is-at 82:74:61:8d:19:86, length 28
````
It's not 100% reproducible however - here is the output of the next script run where you can see the neighbour cache has been updated to the new MAC:
````
>>> Launching loadbalancer container
723168dcee827fb72f998db42ffd7f856b57c2a67a0794c70c31f0abc4db9b55
414: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether ce:d0:80:c0:96:20 brd ff:ff:ff:ff:ff:ff
    inet 10.2.0.1/24 scope global ethwe
       valid_lft forever preferred_lft forever
    inet6 fe80::ccd0:80ff:fec0:9620/64 scope link tentative 
       valid_lft forever preferred_lft forever



>>> Launching frontend container
2ce754ed6caff94acfd164cd920678ba570fdf80343cf7feb97bc30485c4abf6
10.2.0.2
418: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether d2:09:ac:90:3e:dc brd ff:ff:ff:ff:ff:ff
    inet 10.2.0.2/24 scope global ethwe
       valid_lft forever preferred_lft forever
    inet6 fe80::d009:acff:fe90:3edc/64 scope link tentative 
       valid_lft forever preferred_lft forever



>>> Pinging frontend from loadbalancer
PING 10.2.0.2 (10.2.0.2) 56(84) bytes of data.
64 bytes from 10.2.0.2: icmp_seq=1 ttl=64 time=0.001 ms

--- 10.2.0.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.001/0.001/0.001/0.000 ms
10.2.0.2 dev ethwe lladdr d2:09:ac:90:3e:dc REACHABLE



>>> Capturing frontend namespace with /var/run volume mount
155a9a6767d2694f917151f0091668d12a73cf29032ee25a5172010c65d4a9bd



>>> rm/run/attach frontend container
fe
3d803b594cfdcc335ddb63ac814cdcaae11d22c80fe066ecc993ad0b7214f3e4
10.2.0.2
424: ethwe: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65535 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether d6:ec:6d:d2:9f:27 brd ff:ff:ff:ff:ff:ff
    inet 10.2.0.2/24 scope global ethwe
       valid_lft forever preferred_lft forever
    inet6 fe80::d4ec:6dff:fed2:9f27/64 scope link tentative 
       valid_lft forever preferred_lft forever



>>> Pinging frontend from loadbalancer again
PING 10.2.0.2 (10.2.0.2) 56(84) bytes of data.
64 bytes from 10.2.0.2: icmp_seq=1 ttl=64 time=0.081 ms

--- 10.2.0.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.081/0.081/0.081/0.000 ms
10.2.0.2 dev ethwe lladdr d6:ec:6d:d2:9f:27 STALE
````
Corresponding tcpdump output:
````
15:44:34.594849 ce:d0:80:c0:96:20 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.1 (ff:ff:ff:ff:ff:ff) tell 10.2.0.1, length 28
15:44:35.635886 d2:09:ac:90:3e:dc > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.2 (ff:ff:ff:ff:ff:ff) tell 10.2.0.2, length 28
15:44:36.316816 ce:d0:80:c0:96:20 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.2 tell 10.2.0.1, length 28
15:44:36.316816 d2:09:ac:90:3e:dc > ce:d0:80:c0:96:20, ethertype ARP (0x0806), length 42: Reply 10.2.0.2 is-at d2:09:ac:90:3e:dc, length 28
15:44:36.316817 ce:d0:80:c0:96:20 > d2:09:ac:90:3e:dc, ethertype IPv4 (0x0800), length 98: 10.2.0.1 > 10.2.0.2: ICMP echo request, id 24, seq 1, length 64
15:44:36.316817 d2:09:ac:90:3e:dc > ce:d0:80:c0:96:20, ethertype IPv4 (0x0800), length 98: 10.2.0.2 > 10.2.0.1: ICMP echo reply, id 24, seq 1, length 64
15:44:37.528198 d6:ec:6d:d2:9f:27 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.2 (ff:ff:ff:ff:ff:ff) tell 10.2.0.2, length 28
15:44:38.217009 ce:d0:80:c0:96:20 > d6:ec:6d:d2:9f:27, ethertype IPv4 (0x0800), length 98: 10.2.0.1 > 10.2.0.2: ICMP echo request, id 34, seq 1, length 64
15:44:38.217043 d6:ec:6d:d2:9f:27 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.1 tell 10.2.0.2, length 28
15:44:38.217056 ce:d0:80:c0:96:20 > d6:ec:6d:d2:9f:27, ethertype ARP (0x0806), length 42: Reply 10.2.0.1 is-at ce:d0:80:c0:96:20, length 28
15:44:38.217064 d6:ec:6d:d2:9f:27 > ce:d0:80:c0:96:20, ethertype IPv4 (0x0800), length 98: 10.2.0.2 > 10.2.0.1: ICMP echo reply, id 34, seq 1, length 64
15:44:38.319814 d2:09:ac:90:3e:dc > ce:d0:80:c0:96:20, ethertype ARP (0x0806), length 42: Request who-has 10.2.0.1 tell 10.2.0.2, length 28
15:44:38.319844 ce:d0:80:c0:96:20 > d2:09:ac:90:3e:dc, ethertype ARP (0x0806), length 42: Reply 10.2.0.1 is-at ce:d0:80:c0:96:20, length 28
````
The tcpdump traces hold the answer. In both cases you can see the arping ethernet broadcast packets for the new frontend container (time indices `15:30:03.438629` and `15:44:37.528198` respectively) - these update the ARP cache in the loadbalancer to the new MAC. You can also see that in both instances there is a unicast ARP probe *from the old frontend container captured netns to the loadbalancer* (time indices `15:30:04.235245` and `15:44:38.319814`), which will update the ARP cache in the loadbalancer back to the old MAC. The difference is that in the first trace this unicast ARP probe happens before the second ping, whereas in the second trace it happens after.

Immediately after the second script run:
````
$ docker exec lb ip neigh show
10.2.0.2 dev ethwe lladdr d2:09:ac:90:3e:dc STALE
````
The unicast ARP probe at `15:44:38.319814` has flipped the MAC back to the old value again.

**Comment by rade** [comment]
Back to the ostensible subject of this issue, i.e. the proxy mounting `/var/run`...

One cannot [create domain sockets in advance and then listen on them]( http://serverfault.com/questions/358866/create-unix-named-socket-from-the-command-line), so I guess we'll have to create a sub-dir (`/var/run/weave`) and mount that instead.

Any better suggestions? Because if that is the best we can come up with then it can't go into 1.1.1 since the location of the weave socket is likely hard-coded in some apps.

**Comment by dpw** [comment]
> Any better suggestions? Because if that is the best we can come up with then it can't go into 1.1.1 since the location of the weave socket is likely hard-coded in some apps.

If we care enough about it, we could make the proxy umount all undesirable mounts.  That's not a trivial fix, but it would be suitable for 1.1.1.

**Comment by rade** [comment]
could we create a symlink from `/var/run/weave.sock` to `/var/run/weave/weave.sock`?

**Comment by paulbellamy** [comment]
Possibly, we could also, `touch /var/run/weave.sock` before launching, and mount just that file into the proxy, and replace it with a unix socket...

**Comment by awh** [comment]
For posterity - David's improved netns scanning script:
````sh
#!/bin/sh

netns_seen=" "
mntns_seen=" "

do_netns () {
    if [ -n "$1" ] && ! echo "$netns_seen" | grep -qF " $1 "; then
        netns_seen=" $1$netns_seen"
        echo === $2 ===
        nsenter --net=$2 ip addr show
    fi
}

for p in $(find /proc/[0-9]* -path '*/ns/net' -print) ; do
    do_netns "$(readlink $p 2>/dev/null)" $p
done

for p in $(find /proc/[0-9]* -path '*/ns/mnt' -print) ; do
    l=$(readlink $p)
    if ! echo "$mntns_seen" | grep -qF " $l "; then
        mntns_seen=" $l$mntns_seen"
        p=${p%/ns/mnt}
        grep "^proc " $p/mounts | while read dev mntpt fstype rest ; do
            n="$p/root$mntpt"
            do_netns "$(nsenter --net=$n readlink /proc/self/ns/net 2>/dev/null)" $n
        done
    fi
done
````
