### ISSUE TITLE
DNS shouldn't be case sensitive

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1461]
"Note that while upper and lower case letters are allowed in domain
names, no significance is attached to the case.  That is, two names with
the same spelling but different case are to be treated as if identical."

https://www.ietf.org/rfc/rfc1035.txt

**Comment by tomwilkie** [comment]
@rade do you think I should target 1.1 with a fix?

**Comment by rade** [comment]
> do you think I should target 1.1

No. Even though it's a bug, it is also conceivably behaviour some existing apps depend on.
