### ISSUE TITLE
Weave 1.0.3 crash during AWS Outage

### ISSUE THREAD

**Issue by colebrumley** [weaveworks/weave#1475]
During that AWS us-east outage on Aug 25, Weave v1.0.3 running on CoreOS crashed with the following error (full trace [here](https://gist.github.com/colebrumley/31a22a11eb5e4c3e6ca9)):

```
panic: runtime error: growslice: cap out of range [recovered]
	panic: runtime error: growslice: cap out of range

goroutine 4780681 [running]:
encoding/gob.catchError(0xc2328b3350)
	/usr/local/go/src/encoding/gob/error.go:38 +0x96
encoding/gob.encUint8Array(0xc2092d3e60, 0xc24016a600, 0x892760, 0xc21cf60fc0, 0x57)
	/usr/local/go/src/encoding/gob/encode.go:238 +0x17b
encoding/gob.(*Encoder).encodeSingle(0xc2328b32c0, 0xc2328b32f8, 0xc2092db960, 0x892760, 0xc21cf60fc0, 0x57)
	/usr/local/go/src/encoding/gob/encode.go:294 +0x17b
encoding/gob.(*Encoder).encode(0xc2328b32c0, 0xc2328b32f8, 0x892760, 0xc21cf60fc0, 0x57, 0xc208036280)
	/usr/local/go/src/encoding/gob/encode.go:694 +0x20f
encoding/gob.(*Encoder).EncodeValue(0xc2328b32c0, 0x892760, 0xc21cf60fc0, 0x57, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/encoder.go:241 +0x613
encoding/gob.(*Encoder).Encode(0xc2328b32c0, 0x892760, 0xc21cf60fc0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/encoder.go:168 +0x7f
github.com/weaveworks/weave/router.GobEncode(0xc209461e88, 0x3, 0x3, 0x0, 0x0, 0x0)
	/home/matthias/go/src/github.com/weaveworks/weave/router/utils.go:80 +0x130
github.com/weaveworks/weave/router.func·016(0x7fbcd81a1198, 0xc21cf60ba0)
	/home/matthias/go/src/github.com/weaveworks/weave/router/gossip_channel.go:151 +0x290
github.com/weaveworks/weave/router.(*GossipSender).run(0xc2341d2d20)
	/home/matthias/go/src/github.com/weaveworks/weave/router/gossip.go:59 +0xf6
created by github.com/weaveworks/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/weaveworks/weave/router/gossip.go:49 +0xac
...
```

I was having trouble recovering the first crashed node because Weave was not happy that there were existing bridges present on the host.  Even running `weave reset` and then attempting to rejoin the cluster failed because the other nodes had stale data about the failed node and wouldn't accept it.  I found out later that I was attempting this recovery while the outage was ongoing, so it's not terribly surprising that the other nodes eventually also crashed with the same message.  I ended up having to scrap the cluster and start over because I couldn't get any crashed node to nicely rejoin.

My questions are:
1. Are there docs anywhere for the preferred method of recovering crashed nodes?
2. What could have caused this?
3. Will the same thing occur in Weave 1.1 or above?

I noticed that issue #1450 has roughly the same error and that you mentioned that it might be related to slice funcs in go 1.4 that were updated  for 1.5.  Is that likely to be the case here too?

I'd like to get as close to root-cause as possible, thanks in advance for the help.

**Comment by rade** [comment]
> Weave v1.0.3

Are you sure? The stack trace mentions

> /home/matthias/go/src/github.com/weaveworks/weave/releases/v1.0.2/prog/weaver/main.go:170

which indicates 1.0.2. Also, the stack trace shows a large number of `GossipSenders`, the sole known cause for which was fixed in 1.0.3.

> Weave was not happy that there were existing bridges present on the host.

How did this unhappiness manifest itself? Weave is meant to be perfectly ok with re-using a `weave` bridge from a previous incarnation.

> attempting to rejoin the cluster failed because the other nodes had stale data about the failed node

What error did you get?

> Are there docs anywhere for the preferred method of recovering crashed nodes?

Simply re-launching weave should work. It might take a minute or so for stale information to be purged and connectivity to get re-established.

> What could have caused this?

Not running 1.0.3, and possibly #1450.

>  Will the same thing occur in Weave 1.1 or above?

Impossible to tell until we figure out what causes #1450.

Do you happen to have complete logs from any of the nodes that died with the above error?

**Comment by bboreham** [comment]
@colebrumley could I ask what kernel this was running on please?

**Comment by colebrumley** [comment]
@bboreham This was on a coreos 766 box: `4.1.6-coreos-r1`
@rade Sadly I am going to be completely unhelpful with regards to logs, the connectivity issues and flurry of `STUFF'S DOWN!!!1!` messages caused my logs to roll over before they could be successfully forwarded to the remote log stash.  I spent a good deal of time yesterday trying to duplicate the issue with no success.  You are correct though, this _was_ 1.0.2, apologies for the bad info.  I'm going to keep trying to duplicate the issue in the hopes that I can give you something more to go on.

**Comment by rade** [comment]
I am marking this as a dup of #1450. @colebrumley when you have some new data, please add it there.
