### ISSUE TITLE
  Test ./320_claim_3_test.sh is still flaky

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1482]
e.g. https://circleci.com/gh/weaveworks/weave/3031

previous attempted "fix" is #1268.

**Comment by bboreham** [comment]
Note test 160 was renamed to 320

**Comment by bboreham** [comment]
Latest failure: https://circleci.com/gh/weaveworks/weave/5745

(this seems different to the earlier report)

**Comment by bboreham** [comment]
Going to close this as we haven't seen the original failure in four weeks.
