### ISSUE TITLE
weave interface as the primary interface of the container

### ISSUE THREAD

**Issue by melton14** [weaveworks/weave#1493]
Hi, 

 I would like to ask if I can run a container using weave as it's primary network interface?
because when i run a container using weave it will have two interface but the primary is still the docker interface.

**Comment by rade** [comment]
What problems does the docker-created interface cause?

Weave application containers depend on the docker-created interface for external connectivity (#1394) and accessing weaveDNS (#1301).

**Comment by melton14** [comment]
I see. I'm clustering tomcat containers. It configured to automatically use the ip add of the main interface(docker), now, i need to know if there is a way where I can use weave interface as it's primary? example: when you run "docker run -h <hostname> tomcat". then, when you check hosts
 file it is something like this:
![screen shot 2015-10-02 at 8 36 01 am](https://cloud.githubusercontent.com/assets/13516496/10237157/a4eeaff0-68e0-11e5-9cd8-f83dea520d94.png)

now i instead of 172.17.0.13 i need to use to the ip addr given by the weave intrface. thanks!

**Comment by melton14** [comment]
my problem was solved. i found an interesting article. you can close this issue. Thank you very much!.  
Adventures with Weave and Docker - http://sttts.github.io/docker/weave/mesos/2015/01/22/weave.html

**Comment by rade** [comment]
> i found an interesting article.

There are [significant problems](http://blog.weave.works/2015/07/16/bridge-over-troubled-weavers/) with that approach.

What version of weave are you using? And are you starting containers via the proxy? Because in weave 1.1.0 the proxy rewrites `/etc/hosts` to give you the desired result. See the bottom of [the relevant section in the docs](http://docs.weave.works/weave/latest_release/proxy.html#ipam).

Here's an example:
```
$ weave launch
$ eval $(weave env)
$ docker run -ti ubuntu
$ docker run --name=foo -ti ubuntu
root@foo:/# cat /etc/hosts
# modified by weave
10.32.0.1	foo
127.0.0.1	localhost
::1	ip6-localhost ip6-loopback localhost
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
root@foo:/# 
```

**Comment by melton14** [comment]
Cool! it worked. Thanks!. the weird thing is i already tried this one before.

**Comment by melton14** [comment]
Hi again, Now I'm Trying to deploy it on mesos. The problem is that when you deploy it using marathon it will use normal docker commands and it will not use the weave env. I was wondering if i can setup that on the marathon json to use the weave env.

**Comment by dpw** [comment]
Hi @melton14,

Did you take a look at our mesos-marathon guide at http://weave.works/guides/platform/mesos-marathon/os/centos/cloud/vagrant/ yet?

You can find the files behind it at https://github.com/weaveworks/guides/tree/master/mesos-marathon/centos .  In particular, https://github.com/weaveworks/guides/blob/master/mesos-marathon/centos/mesos-slave-containerizers.conf

If you have further questions, you might want to ask on our mailing list / forum at https://groups.google.com/a/weave.works/forum/#!forum/weave-users

**Comment by sheerun** [comment]
it's still an issue when using docker plugin
