### ISSUE TITLE
weave hide failed, unable to restart weave

### ISSUE THREAD

**Issue by baopx** [weaveworks/weave#1501]
Docker hang after some time, then our watchdog kick docker by:

`systemctl restart docker`

Then, since weave depends on docker, systemd also stop weave and then start.

Stop weave:
weave hide
weave stop

weave hide hung, subsequently, weave start also did not come up.  I manually did a weave stop, then weave start.  Now, the weave node is not able to join.

Attached is the weave logs/inspect *after* I manually start up the weave containers (with weave start)

**Comment by rade** [comment]
@baopx any update on this?

**Comment by rade** [comment]
@baopx ping

**Comment by baopx** [comment]
I haven't seen this problem for a long time.  When I switched to separating weave components into different services (router.service, proxy.service, expose.service), restarting docker at random does not effect weave.

I have a test script that run this case from time to time.
