### ISSUE TITLE
document or automate pushing of changes during the release process

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1506]
When I followed the [release process](https://github.com/weaveworks/weave/blob/master/docs/release-process.md) for the 1.1.1 release, I noticed that my `CHANGELOG.md` didn't show up on github. I had to do a manual `git push upstream 1.1`, plus the usual "merge 1.1. into master" dance. This should be documented, or automated.

**Comment by bboreham** [comment]
Fixed by #1800
