### ISSUE TITLE
Weaveproxy error on restart: "status.sock: bind: address already in use"

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1519]
Running `weaveproxy` with `--restart=always` and then killing it leads to an endless sequence of errors:

    FATA: 2015/10/09 16:07:08.381199 ListenAndServeStatus failed: listen unix /home/weave/status.sock: bind: address already in use

**Comment by rade** [comment]
This got broken in #1474, so it's not present in any release.
