### ISSUE TITLE
docker/weave restart cause Failed to connect to 172.17.0.1 port 6784

### ISSUE THREAD

**Issue by baopx** [weaveworks/weave#1521]
stop weave, stop docker, then start docker, start weave.
The issue happen with the following steps:

1) systemctl start docker   ## Basically start docker -d
2) systemctl start weave    ## does a couple more things, but the git is launch router  then launch proxy, stop if 1st or 2nd command returns non-zero.
   /usr/local/bin/weave launch-router --dns-domain portworx.io --init-peer-count 1
    /usr/local/bin/weave launch-proxy --rewrite-inspect
    curl: (7) Failed to connect to 172.17.0.1 port 6784: Connection refused
    Call to weave failed.

weave router `docker logs weave`:
INFO: 2015/10/09 16:32:44.260332 Command line options: map[dns-effective-listen-address:172.17.42.1 iface:ethwe init-peer-count:1 ipalloc-range:10.32.0.0/12 name:76:2f:0e:33:f6:45 nickname:bao-dev port:6783 dns-domain:portworx.io]
INFO: 2015/10/09 16:32:44.260417 Command line peers: []
INFO: 2015/10/09 16:32:44.260529 Communication between peers is unencrypted.
INFO: 2015/10/09 16:32:44.260590 Our name is 76:2f:0e:33:f6:45(bao-dev)
INFO: 2015/10/09 16:32:44.261529 [docker] Using Docker API on unix:///var/run/docker.sock: &[Version=1.8.2 ApiVersion=1.20 GitCommit=82b59c9-dirty GoVersion=go1.4.2 Os=linux Arch=amd64 KernelVersion=3.19.3-1.el7.elrepo.x86_64 BuildTime=Wed Sep 30 23:32:04 UTC 2015]
INFO: 2015/10/09 16:32:44.293490 Sniffing traffic on &{3303 65535 ethwe 86:56:9b:bd:a7:05 up|broadcast|multicast}
INFO: 2015/10/09 16:32:44.293546 Discovered our MAC 86:56:9b:bd:a7:05
INFO: 2015/10/09 16:32:45.168212 Discovered local MAC 96:95:26:c5:ab:ef

**Comment by baopx** [comment]
F=/var/tmp/weave-launch-router.$(date +%Y%m%d%H%M%S)

            echo "Starting $WEAVE launch-router $WEAVE_DNS_DOMAIN"\
                 "--init-peer-count $peer_count $WEAVE_NODES"
            WEAVE_DEBUG=1 $WEAVE launch-router $WEAVE_DNS_DOMAIN \
                --init-peer-count $peer_count $WEAVE_NODES >$F 2>&1
            chk_retval $? "$WEAVE launch-router $WEAVE_DNS_DOMAIN" \
                          "--init-peer-count $peer_count $WEAVE_NODES"

            sleep 30

            echo "$WEAVE launch-proxy --rewrite-inspect"
            $WEAVE launch-proxy --rewrite-inspect $DOCKER_DAEMON
            chk_retval $? "$WEAVE launch-proxy --rewrite-inspect $DOCKER_DAEMON"

I enable debug and re-run...The $F is empty.  The "Failed to connect" to port 6784 is in systemd log.

Oct 09 17:41:38 bao-dev weave.sh[15185]: curl: (7) Failed to connect to 172.17.0.1 port 6784: Connection refused
Oct 09 17:41:38 bao-dev weave.sh[15185]: Call to weave failed.

**Comment by rade** [comment]
> The $F is empty

You are saying the file `/var/tmp/weave-launch-router.<timestamp>` exists but is empty?

**Comment by baopx** [comment]
Let me try to get this in a more control environment… Hang on, will get back soon..

**Comment by rade** [comment]
@baopx any update on this?

**Comment by wilkins-meister** [comment]
The "Failed to connect" to port 6784 is due to my 'weave expose'.

I am able to reproduce the issue with these steps:
1) weave launch-router ....
2) weave launch-proxy ... (as in above systemd script)
3) weave expose

Then I change the service from 1 service to 3 (router, proxy, and expose command) services.  With this service change, I may have mask the problem.

Looking at 172.17.0.1 port 6784, this is the router's docker I address, and port 6784 is the port its listening on.  I believe if we run `weave expose` right after `weave launch-router`.  We will hit it.  it will happen with just 2 nodes.

**Comment by baopx** [comment]
Above comment (wilkins-meister) is mine.  Bao

**Comment by rade** [comment]
> it will happen with just 2 nodes

I would expect to see it happening with one node.

Have you managed to get `WEAVE_DEBUG` to work?

**Comment by baopx** [comment]
Since I move to the 3 systemd units model, I haven't seen this problem.  Let me revert the change and re-test.

**Comment by baopx** [comment]
I got my hands on a system with the issue.  Then, turn WEAVE_DEBUG=1 and restarted weave service (in this systemd unit, I have weave router, proxy, expose running together).  With debug on, weave started OK.

1) WEAVE_DEBUG=0; hit the issue everytime, once weave got into this state
2) WEAVE-DEBUG=1; not able to hit the issue.

Any suggestions?

**Comment by rade** [comment]
> 1) WEAVE_DEBUG=0; hit the issue everytime, once weave got into this state

Are you saying you repeatedly run it, it initially succeeds, but then it goes wrong and after that always fails? If so, set `WEAVE_DEBUG=1` only once it has gone wrong.

**Comment by wilkins-meister** [comment]
"Are you saying you repeatedly run it, it initially succeeds, "
Yes

"but then it goes wrong and after that always fails?"
Yes

"If so, set WEAVE_DEBUG=1 only once it has gone wrong."
But once I set WEAVE_DEBUG=1 after it fails, it does not fail anymore.

**Comment by errordeveloper** [comment]
Could you please demonstrate what the unit definitions are exactly?

**Comment by baopx** [comment]
Sent service units in an email.  Please close the bug until it arises again?
