### ISSUE TITLE
weaveproxy can overwrite port bindings from docker-compose

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1531]
To recreate using `docker-compose`, create a file `docker-compose.yml`:

    foo:
      image: gliderlabs/alpine
      command: sleep 100
      ports:
       - "1234:1234"

Start this container via `weaveproxy`:

    DOCKER_HOST=unix:///var/run/weave/weave.sock docker-compose up -d

Check for the published port:

    $ docker inspect -f '{{.HostConfig.PortBindings}}' test_foo_1
    map[]

Cause is that `docker-compose` is sending in an empty JSON request on `start`; we are setting our HostConfig fields on that request, and hence overwriting the `PortBindings`.

This does not happen if you try via `docker create` and `docker start`, since `docker start` does not send any content at all in the request and `startContainerInterceptor.InterceptRequest()` detects that and bypasses setting the HostConfig.

**Comment by rade** [comment]
Is this issue present in 1.1.x?

**Comment by bboreham** [comment]
No.
