### ISSUE TITLE
weaveproxy doesn't handle HostConfig json on start request named "HostConfig"

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1532]
We handle a `HostConfig` structure passed unnamed at top level, i.e.

````
{
   "Memory":0
}
````

, but not something like:

````
"HostConfig": {
   "Memory":0
}
````

Docker appears to handle either, in `ContainerConfigWrapper.getHostConfig()`, but I haven't tested it yet.

**Comment by rade** [comment]
Is this problem present in 1.1.x?

**Comment by bboreham** [comment]
In the sense that passing any kind of HostConfig on `start` broke the proxy, yes.  That was #1368, which is not fixed on the 1.1 branch.

**Comment by rade** [comment]
Fixed by #1534
