### ISSUE TITLE
signal mismatches between WEAVE_NO_FASTDP and the bridge type

### ISSUE THREAD

**Issue by dpw** [weaveworks/weave#1533]
Someone might reasonably do:
```
weave launch
weave stop
WEAVE_NO_FASTDP=1 weave launch
```
and be surprised that they are still using fastdp.  So we should validate in `create_bridge` that the bridge type and WEAVE_NO_FASTDP match up, and fail if they don't (or just warn?).

**Comment by rade** [comment]
I reckon we should *fail*, and the message should indicate what to do (e.g. "run `weave reset`").
