### ISSUE TITLE
Proxy doesn't detect TLS settings if told where to listen

### ISSUE THREAD

**Issue by squaremo** [weaveworks/weave#1539]
If you supply a `-H` argument to launch-proxy, it will forget about setting up TLS. This is a pain, for example, if you want to listen on a unix socket (so containers can be given access to docker) as well as a TCP socket.

Suggestion from @paulbellamy: An argument `--detect-tls` which forces it to detect TLS settings and use them, whatever other arguments you supply.

**Comment by paulbellamy** [comment]
Or, add `--no-tls`, and always auto-detect unless specified.

**Comment by rade** [comment]
> Or, add `--no-tls`

Would have to be `--no-detect-tls`

**Comment by paulbellamy** [comment]
I was thinking it would be opposed to setting `--tls` or `--tlsverify`

**Comment by rade** [comment]
but it turns off auto-detection; a user would still be able to specify tls options manually. No?

**Comment by paulbellamy** [comment]
Whichever colour the bikeshed should be, is fine.
