### ISSUE TITLE
use of same port for http control i/f and fastdp is confusing

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1545]
Since fastdp landed, the router is running in the host network namespace. It will therefore listen on localhost:6784/tcp for http. And vxlan will presumably listens on *:6784/udp. While that is not actually a clash, it is a tad confusing.

Perhaps we should pick a different port for vxlan... 6785? 6782?

**Comment by dpw** [comment]
How is this any worse than the dual use of 6783 for tcp and udp?

**Comment by rade** [comment]
The dual use on 6783 is more closely related. e.g. you'd generally open the firewall for both.

**Comment by dpw** [comment]
In my experience, firewall products require you to specify whether you want to open a TCP port or UDP port, it's not just a matter of opening a port number.

At the moment, we are only taking up 2 port numbers.  With your suggestion, we will unnecessarily take up 3.  That doesn't seem worth it to me to avoid a small risk of confusion (but I don't find it at all confusing, so maybe I am underestimating this risk).

**Comment by dpw** [comment]
> In my experience, firewall products require you to specify whether you want to open a TCP port or UDP port, it's not just a matter of opening a port number.

I.e., whether we say "open 6783 for TCP and UDP and 6782 for UDP" or "open 6783 for TCP and UDP and 6784 for UDP" makes no difference in terms of firewall configuration.

**Comment by rade** [comment]
Right, and it's possible that I am overestimating the risk. Let's canvas opinions.

Note that even if people did accidentally open 6783/TCP, the http control channel would still be out of reach, since it only listens on localhost. But I still worry that users will get the wrong idea into their heads about what ports/protocols do what.

**Comment by rade** [comment]
> Let's canvas opinions.

Both @bboreham and @awh say that this is a non-issue. -> invalid
