### ISSUE TITLE
proxy shouldn't kill containers when it restarts

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#1547]
![image](https://cloud.githubusercontent.com/assets/444037/10539414/4c8a44ce-73f7-11e5-8a7d-ebb33d3b4b05.png)

**Comment by tomwilkie** [comment]
To reproduce:
- start weave, and containers
- stop weave
- start proxy

**Comment by rade** [comment]
This is on master, right?

**Comment by tomwilkie** [comment]
@bboreham will know more, but yes, I think this is just on master

**Comment by bboreham** [comment]
The killing started in #932, however it was limited to situations where the container had just started.

It was extended to happen on proxy restart in #1210, which is not in any release yet.

To fix this issue, we want to remove `--or-die` when the attach is called from `AttachExistingContainers()`.  But this then exposes a race on reboot: if, when `weaveproxy` comes up, `weaver` is not ready, we will fail the attach and leave application containers stuck in `weavewait`.  So we need some kind of re-try on failed attaches.

**Comment by rade** [comment]
>  But this then exposes a race on reboot: if, when `weaveproxy` comes up, weaver is not ready, we will fail the attach and leave application containers stuck in `weavewait`

Whereas right now it kills them?

>  So we need some kind of re-try on failed attaches.

I'd treat that as a separate issue.

**Comment by bboreham** [comment]
> Whereas right now it kills them?

Indeed.  No witnesses, no loose ends.

**Comment by rade** [comment]
Ha ha.
