### ISSUE TITLE
Weave multicast

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#1553]
Is there a quick way to see if multicast works across (latest) weave?

I did use https://github.com/neilellis/weave_multicast_tutorial/blob/master/blog_post.md in the past, but couldn't get it to run anymore.

**Comment by dpw** [comment]
I think there is a problem with the `run.sh` shell script in that demo container.  If I bypass it, and start the mcsend and mcreceive programs directly, they work fine across the weave network.

E.g., on one host

    docker $(weave config) run -it --rm neilellis/weave-multicast-tutorial /mcsend 239.1.2.3 1234

and on the other

    docker $(weave config) run -it --rm neilellis/weave-multicast-tutorial /mcreceive 239.1.2.3 1234
