### ISSUE TITLE
 weave launch <hostname> gives " lookup <hostname>: no such host" 

### ISSUE THREAD

**Issue by liuyunsh** [weaveworks/weave#1555]
I just want to test the example from https://www.youtube.com/watch?v=kihQCCT1ykE&feature=youtu.be

When I launch the weave it give out the following errors:
```
[root@weave1 ~]# docker logs weave
INFO: 2015/10/19 06:44:14.968158 Command line options: map[dns-effective-listen-address:172.17.42.1 iface:ethwe ipalloc-range:10.32.0.0/12 name:d2:55:74:ac:3e:d7 nickname:weave1.novalocal port:6783]
INFO: 2015/10/19 06:44:14.968311 Command line peers: [weave-2-1.novalocal]
INFO: 2015/10/19 06:44:14.968501 Communication between peers is unencrypted.
INFO: 2015/10/19 06:44:14.968947 Our name is d2:55:74:ac:3e:d7(weave1.novalocal)
INFO: 2015/10/19 06:44:14.970794 [docker] Using Docker API on unix:///var/run/docker.sock: &[BuildTime=Mon Oct 12 06:06:01 UTC 2015 Version=1.8.3 ApiVersion=1.20 GitCommit=f4bf5c7 GoVersion=go1.4.2 Os=linux Arch=amd64 KernelVersion=3.10.0-229.14.1.el7.x86_64]
INFO: 2015/10/19 06:44:14.970823 Assuming quorum size of 2
INFO: 2015/10/19 06:44:15.030887 Sniffing traffic on &{11 65535 ethwe 0e:0f:dc:b2:b2:50 up|broadcast|multicast}
INFO: 2015/10/19 06:44:15.030959 Discovered our MAC 0e:0f:dc:b2:b2:50
FATA: 2015/10/19 06:44:15.109561 lookup weave-2-1.novalocal: no such host
```
By the way, The weave-2-1.novalocal can be accessed by 'ping' command.
```
[root@weave1 ~]# ping weave-2-1.novalocal
PING weave-2-1.novalocal (9.114.192.31) 56(84) bytes of data.
64 bytes from weave-2-1.novalocal (9.114.192.31): icmp_seq=1 ttl=64 time=6.99 ms
64 bytes from weave-2-1.novalocal (9.114.192.31): icmp_seq=2 ttl=64 time=0.430 ms
64 bytes from weave-2-1.novalocal (9.114.192.31): icmp_seq=3 ttl=64 time=1.34 ms
64 bytes from weave-2-1.novalocal (9.114.192.31): icmp_seq=4 ttl=64 time=1.78 ms
^C
--- weave-2-1.novalocal ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 0.430/2.636/6.990/2.560 ms
```

**Comment by liuyunsh** [comment]
This issue is the same as https://github.com/weaveworks/weave/issues/296#issue-52807246
My system is RHEL 7.0

**Comment by rade** [comment]
Can you ping `weave-2-1.novalocal` from inside an ordinary container?

**Comment by liuyunsh** [comment]
@rade ， Thanks for your quick response. No ,I haven't launch other container.

**Comment by rade** [comment]
Please try that. i.e. forget weave for a moment and just launch any container and check that you can resolve `weave-2-1.novalocal` in that container.

**Comment by liuyunsh** [comment]
I just launch a ubuntu, and try to ping weave-2-1.novalocal. but failed. 
[root@weave1 ~]# docker run --name a1 -ti ubuntu
root@795ba8680b76:/# ping weave-2-1.novalocal
ping: unknown host weave-2-1.novalocal
root@795ba8680b76:/# ping weave-2-1.novalocal
ping: unknown host weave-2-1.novalocal
root@795ba8680b76:/#

**Comment by rade** [comment]
Right, so name resolution isn't working from inside docker containers. That is not a weave problem.

Check your name resolution configuration on the host, and perhaps play with https://docs.docker.com/reference/commandline/daemon/#daemon-dns-options. If that doesn't work, check the Docker docs / ask the Docker people.

As a workaround you could use IP addresses in `weave launch`.

**Comment by liuyunsh** [comment]
ok, thanks for your kindly reply. I will try it . by the way, which country are you come from ? :）

**Comment by liuyunsh** [comment]
@rade ,Thanks very much, it works using ip address. :)
