### ISSUE TITLE
Proxy should retry attaching containers, after restarting

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#1556]
In case attaching them fails.

**Comment by rade** [comment]
Why would it fail, and subsequently succeed?

**Comment by paulbellamy** [comment]
This is what I'm wondering. Is there a case where something else (weave? weavedns?) is not ready?

**Comment by paulbellamy** [comment]
It could fail if weave/ipam is not ready to assign an IP address, then succeed once those are available.

**Comment by rade** [comment]
https://github.com/weaveworks/weave/issues/1547#issuecomment-148679616

**Comment by rade** [comment]
> It could fail if weave/ipam is not ready to assign an IP address

That is not true. IPAM blocks when it is not ready.

**Comment by paulbellamy** [comment]
By "not ready" I mean the weave container is not running yet, or does the ipam allocation at that stage hang?

**Comment by rade** [comment]
"weave container is not running yet" could indeed trigger this.

But then you have to wonder why we'd only do this on restarts. i.e. perhaps we should also make

```
$ weave launch-proxy
$ docker -H $(weave config) run -dti ubuntu
$ weave launch
```

work?

**Comment by paulbellamy** [comment]
Could do. That would also mean that:
```
$ weave launch-proxy
$ docker -H $(weave config) run -ti ubuntu
```
... will hang (unless we handle detached and foreground different), and could make attachment errors harder to display to the user.

**Comment by rade** [comment]
> will hang

Right now it silently fails. See #1542.

> could make attachment errors harder to display to the user.

why?

**Comment by awh** [comment]
> ""weave container is not running yet" could indeed trigger this."

I've just run into this investigating #1588. The tests hang occasionally because `/w/w` is blocking the `grep` of `/sys/class/net/ethwe/carrier`; `docker logs weaveproxy` reveals

````
INFO: 2015/11/03 11:31:26.875121 === received SIGINT/SIGTERM ===
*** exiting
INFO: 2015/11/03 11:31:37.783904 weave proxy git-77c7963bde87
INFO: 2015/11/03 11:31:37.784198 Command line arguments: -H tcp://0.0.0.0:12375
INFO: 2015/11/03 11:31:37.839801 [docker] Using Docker API on unix:///var/run/docker.sock: &[ApiVersion=1.21 GitCommit=e6f5a3c GoVersion=go1.4.2 Os=linux Arch=amd64 KernelVersion=3.19.0-21-generic BuildTime=Sat Oct 31 05:35:20 UTC 2015 Version=1.9.0-rc4]
INFO: 2015/11/03 11:31:37.893056 proxy listening on tcp://0.0.0.0:12375
INFO: 2015/11/03 11:31:37.940509 Attaching container 3ac20436583cbe11aadf66608f5e557a7ef4d4ef08f901443160327ea91c4f46 with WEAVE_CIDR "10.2.0.78/24" to weave network
WARN: 2015/11/03 11:31:38.066796 Attaching container 3ac20436583cbe11aadf66608f5e557a7ef4d4ef08f901443160327ea91c4f46 to weave network failed: curl: (7) Failed to connect to 127.0.0.1 port 6784: Connection refused

INFO: 2015/11/03 11:31:38.080381 Attaching container 2c22528f9c7ca3603f11b6b135a261562e40a42a58b2431885a9cf515067010f with WEAVE_CIDR "10.2.0.34/24" to weave network
WARN: 2015/11/03 11:31:38.115593 Attaching container 2c22528f9c7ca3603f11b6b135a261562e40a42a58b2431885a9cf515067010f to weave network failed: curl: (7) Failed to connect to 127.0.0.1 port 6784: Connection refused
````
`3ac20436583c`/`2c22528f9c7c` are `c1`/`c2` respectively.
