### ISSUE TITLE
`make update` changes git branch to master

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1564]
If you are trying to build a patch release, you need to switch back to the appropriate branch after running `make update`, because it switches the git branch to master.

This fact should be included in the [release instructions](https://github.com/weaveworks/weave/blob/master/docs/release-process.md)

**Comment by rade** [comment]
Well, ideally we'd fix it.

**Comment by awh** [comment]
> This fact should be included in the release instructions

It is implicit in the ordering:

````
Prerequisites
    Update all dependencies with make update

...

Build Phase
Update CHANGELOG.md

    Checkout the branch from which you wish to release
````

You could call it out specifically, but the other prerequisites are just as important - it's why they're in a section at the start named prerequisites :wink:

**Comment by awh** [comment]
> Well, ideally we'd fix it.

I don't think this is possible - it's a consequence of Go's stance on versioning dependencies...

**Comment by bboreham** [comment]
OK, I agree the instructions do tell you to switch branch.
