### ISSUE TITLE
Print out info on upstream servers for weaveDNS debugging

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1571]
When remote troubleshooting it can be useful to know what weave thinks its upstream servers are.

**Comment by bboreham** [comment]
And it would be useful to log out that there are zero upstream servers, especially if we get asked to resolve an upstream name.

**Comment by rade** [comment]
> it would be useful to log out that there are zero upstream servers, especially if we get asked to resolve an upstream name.

No. Except perhaps at debug log level.

**Comment by awh** [comment]
`weave report` all the things

**Comment by rade** [comment]
I think it's perfectly reasonable to have the upstreams reported in `weave status`, not just `weave report`. I am opposed to logging "there are zero upstream servers" every time we attempt to resolve a name upstream.

**Comment by darabi** [comment]
As a user, I would appreciate a message during startup which clearly states that there are zero upstream servers, making me aware of my mis-configuration. That would have made my life easier and saved @bboreham from my stupid questions on IRC.

In debug mode, I would also appreciate a message like 'cannot resolve name …. in local database and as I don't have upstreams configured, I return a ServFail'.
