### ISSUE TITLE
weave launch-proxy -H unix:///*.sock only works for mounted dirs (e.g. /var/run/weave)

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#1579]
We only mount `/var/run/weave` into the proxy container, so only sockets under that dir will work, at the moment.

**Comment by rade** [comment]
Due to the dangers of mounting `/var/run` we should warn when the users specifies a `-H` that points there, with a suggestion of alternatives, e.g. "create a symlink to /var/run/weave/weave.sock".
