### ISSUE TITLE
work with dockers on domain sockets other than unix:///var/run/docker

### ISSUE THREAD

**Issue by shanmugakarna** [weaveworks/weave#1586]
`weave launch` is not detecting docker socket if `DOCKER_HOST` is set to non-default unix socket 

Docker daemon is listening on `unix:///var/run/docker-real.sock` and `$DOCKER_HOST=unix:///var/run/docker-real.sock`

`docker` commands works fine as expected. But `weave lauch` returns
`Cannot connect to the Docker daemon. Is 'docker -d' running on this host?`

**_Note:_**
_This is to achieve something similar here https://github.com/rancher/rancher/issues/2398 to integrate weave into Rancher_

**Comment by rade** [comment]
`weave launch` *is* detecting the `DOCKER_HOST`. So, for example, it is possible to set it to the tcp port of a remote docker. However, it does expect docker to always (also) listen on `unix:///var/run/docker`.

I see from the referred bug that you want to make the weave proxy listen on `unix:///var/run/docker`. That doesn't actually work either atm. See #1579.

**Comment by paulbellamy** [comment]
Most of this is actually just getting the weave script to work when docker is not listening on `unix:///var/run/docker.sock`, which is quite tricky due to the "running in two places" aspect of the weave script.

**Comment by bboreham** [comment]
Fixed by #1740 and #1689
