### ISSUE TITLE
fastdp broke multiweave

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1589]
```
$ NUM_WEAVES=3 bin/multiweave launch
65fd3e8d118f35599fa5b033a88ab6f374fcba73c6921f9485d4dfabc860387c
1ac7cca04cdc1ee5713a741cb5177f49f31c738f13f77e50e6536ea087ba24ea
ff804a0d2ddf22d5b2cf42da5a4d884293510538f5cb8fb098001bf82eed938e
connecting weave3 to false
weave3 container is not running.
$ docker logs weave3
...
FATA: 2015/10/25 15:55:39.786639 listen udp4 :6783: bind: address already in use
```

**Comment by rade** [comment]
Setting `WEAVE_NO_FASTDP=1` fixes this.

But I also tried to get this working without supplying this flag...

- got multiweave to set `--datapath ''`
- don't create a sleeve overlay unless fdp or ordinary capture is happening

Then I came unstuck on the http control port. Since weave is running in the host netns, the control ports need to be different for each instance. (As an aside, I was surprised to discover that weave is running in its own netns when fastdp is disabled; this feels like an unnecessary complication - any reason for doing this that I've missed?)

This is obviously fixable, but requires some script surgery. Before I embark on this, I just wanted to check first though whether there might be further problems. Will the weaves be able to fully establish connections, considering that doing so (presumably) involves some communication over the overlay? @dpw @awh

**Comment by dpw** [comment]
> Then I came unstuck on the http control port. Since weave is running in the host netns, the control ports need to be different for each instance. (As an aside, I was surprised to discover that weave is running in its own netns when fastdp is disabled; this feels like an unnecessary complication - any reason for doing this that I've missed?)

Simply an abundance of caution. I'm relieved that no one has told us that running weave in the host netns is a show-stopper for something important so far.  But it is still early days.  If all goes well, we could change that for 1.3.

> This is obviously fixable, but requires some script surgery. Before I embark on this, I just wanted to check first though whether there might be further problems. Will the weaves be able to fully establish connections, considering that doing so (presumably) involves some communication over the overlay?

Can't you set the ports for each router you start, so that they don't clash (for http or the vxlan port)? Apart from that and distinct datapath names, I think it should work.

**Comment by rade** [comment]
> Can't you set the ports for each router you start

As I said, this is fixable but requires some script surgery. And getting the likes of `WEAVE_CONTAINER_NAME=weave1 weave status` to work is tricky.
