### ISSUE TITLE
Add fast datapath miss counter to `weave report`

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1592]

**Comment by inercia** [comment]
We currently show these stats when using _pcap_:

```
        "CaptureStats": {
            "PacketsDropped": 0,
            "PacketsIfDropped": 0,
            "PacketsReceived": 44
        },
```

From my understanding of the problem, we could only show the _upcall_ packets counter. Should we try to make the report the same, regardless of whether _FDP_ is being used or not?
