### ISSUE TITLE
Containers get stuck on weavewait when NetworkMode=host is provided at start

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/weave#1600]
Specific case of https://github.com/weaveworks/weave/issues/1258 which is closed but may be worth reviewing (it was closed with *It's too intrusive a change for 1.0.2.*)

Spawning a container which provides `NetworkMode=host` at start results in weavewait waiting indefinitely.

To reproduce:

```
$ DOCKER_HOST=unix:///var/run/weave/weave.sock docker create --name foo busybox echo foo
$ curl -v --unix-socket /var/run/weave/weave.sock -XPOST http:/v1.15/containers/foo/start -H "Content-Type: application/json" --data-binary '{"HostConfig": { "NetworkMode": "host"} }'
$ ps auxf | grep 'echo foo'
root     16605  0.0  0.0   4880  1808 ?        Ssl  14:41   0:00  \_ /w/w echo foo
```

The weave proxy seems to recognize the host network mode ...
```
INFO: 2015/10/28 14:39:44.275603 POST /v1.15/containers/foo/start
INFO: 2015/10/28 14:39:44.343674 Leaving container c8af2e50a472eaf274b2e2fbd0b468debb814f4fde90634e161c78ad16ca71df alone because the container was created with the '--net=host'
```

... but it doesn't really *leave the container alone*.

In an offline discussion, @paulbellamy mentioned this happens because by the time the container starts it was already created with the weavewait entrypoint.

I experienced this when trying to run Kubernetes with Weave (which may not be a sane thing to do but that's besides the point).

Related: https://github.com/kubernetes/kubernetes/issues/12263

**Comment by rade** [comment]
>  #1258 which is closed but may be worth reviewing (it was closed with *It's too intrusive a change for 1.0.2.*)

That's not true. It was closed because we put a fix in 1.1.0, namely #1314. But it's a partial fix, as per https://github.com/weaveworks/weave/issues/1258#issuecomment-131068891. I am curious what was wrong with my analysis there.

**Comment by paulbellamy** [comment]
Options discussed:

1) We could insert a socket into the container filespace, and communicate with weavewait that way.
2) We could modify the HostConfig passed at start, to "smuggle" some data into weavewait to tell it to bypass waiting.
3) We could pass the host mac address into weavewait at container creation (env var or something), and have weavewait check if we are in the host network namespace.

Of these options, 3 seems the cleanest.

**Comment by rade** [comment]
Not sure what the "correct" way to do option 3 is, given that the host can have multiple network interfaces. We could grab the macs of all, and if weavewait finds any of the macs on any of the container's interfaces, then it assumes it is running in the host netns.

@dpw or @awh might know of some neater mechanism for determining from inside a container whether it is running in the host netns.

**Comment by rade** [comment]
> Spawning a container which provides `NetworkMode=host`

NB: @2opremio revealed that actually the mode is `container:...`, and it's that container in turn which is running with `host` mode.

**Comment by dpw** [comment]
> @dpw or @awh might know of some neater mechanism for determining from inside a container whether it is running in the host netns.

I don't think there is.  There is no fundamental hierarchy to network namespaces, so I don't think that's a way to find out if the netns is the "root" one.  Even if there was a way to identify the initial netns, it is conceptually wrong:  You could in principle run docker within a container, so there is no distinguished "host" netns. I think you'll have to go for 1 or 2.

(I take it that the whole crux of this issue is that `--net=` information can be passed with the "start container" operation, but things like the entrypoint are passed with the "create container" operation, so we can't make the latter depend on the former.)

**Comment by dpw** [comment]
> There is no fundamental hierarchy to network namespaces, so I don't think that's a way to find out if the netns is the "root" one.

Matthias comments that the question is not whether the netns is the root one, but rather whether it is the same netns that weaveproxy is using.

If you do `ls -l /proc/self/ns/net` you will see something like `net:[4026531969]`.  That is a unique identifier for the netns.  So perhaps weaveproxy could `readlink("/proc/self/ns/net")`, and pass the result into weavewait, which then does `readlink("/proc/self/ns/net")` and compares (the weave script does something like this).  This raises the question of whether `/proc` inside a docker container is always the container's own proc filesystem.  It seems that docker always mounts `/proc` when creating a container.  But what if you do `docker run -v /proc:/proc ...`.  Answer:

```
Timestamp: 2015-10-28 18:06:06.17102756 +0000 GMT
Code: System error

Message: "/var/lib/docker/aufs/mnt/a09da29ec4ce9ca4a1609fc383ee9edb7f46899a981ab49b164ed04fda5e7cd7/proc" cannot be mounted because it is located inside "/proc"

Frames:
---
0: setupRootfs
Package: github.com/docker/libcontainer
File: rootfs_linux.go@37
---
1: Init
Package: Error response from daemon: Cannot start container a09da29ec4ce9ca4a1609fc383ee9edb7f46899a981ab49b164ed04fda5e7cd7: [8] System error: "/var/lib/docker/aufs/mnt/a09da29ec4ce9ca4a1609fc383ee9edb7f46899a981ab49b164ed04fda5e7cd7/proc" cannot be mounted because it is located inside "/proc"
```

**Comment by 2opremio** [comment]
> If you do `ls -l /proc/self/ns/net` you will see something like `net:[4026531969]`.  That is a unique identifier for the netns.  So perhaps weaveproxy could `readlink("/proc/self/ns/net")`, and pass the result into weavewait, which then does `readlink("/proc/self/ns/net")` and compares (the weave script does something like this). 

Are namespace inodes persistent? Otherwise this won't work in conjunction with system restarts.

**Comment by rade** [comment]
> Are namespace inodes persistent? Otherwise this won't work in conjunction with system restarts.

More to the point; restarts will produce new network namespaces.

So I reckon that's a problem. It's also a problem for the original proposal of checking MAC addresses if the host has no "real" network devices (i.e. things with an unchanging MAC).

**Comment by dpw** [comment]
> Are namespace inodes persistent? Otherwise this won't work in conjunction with system restarts.

Nope.

I guess weavewait could, as the first thing it does, check whether it is in the host netns, and if so record the fact somehow in the container filesystem (to be checked upon restart).  But that will leave a small window for restarts before it records the netns status.  So it's not ideal.

I see the proxy does `addWeaveWaitVolume` for container starts. If docker actually pays attention to that, why can't it specify a different volume depending on whether `--net=host` is there or not?  That seems like it would be a form of option (2) that is no worse than what the proxy already does.

Hmm, from my reading of the docker code it looks like you can even mess with the entrypoint at container start time (`docker/daemon/start.go` calls `setHostConfig`, same as `create.go`). No?

**Comment by rade** [comment]
> why can't it specify a different volume depending on whether `--net=host` is there or not?  That seems like it would be a form of option (2) that is no worse than what the proxy already does.

Yes, that should work! i.e. we'd mount a no-op program into `/w/w`.

>  from my reading of the docker code it looks like you can even mess with the entrypoint

The `Entrypoint` is part of the `Config`, not `HostConfig`. `start` [only accepts the latter](https://docs.docker.com/reference/api/docker_remote_api_v1.21/#start-a-container).

(As an aside, if rewriting the entrypoint at start was possible we'd have another problem at our hands)
