### ISSUE TITLE
Not sorted DNS data in outbound gossip merge

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1610]
While investigating #1603, a similar issue was found:

- If gossip data is queued outbound, and we have more to send, `GossipData.Merge()` gets called.  This checks that `g.Entries` is sorted case-sensitively, then calls `g.Entries.merge()` which checks that it is sorted case-insensitively.  With entries of mixed case, it is impossible to satisfy both checks.

(not seen in the wild - requires blocking-back of outbound data together with mixed-case names)

**Comment by bboreham** [comment]
Updated description; this code will fail faster than I thought.

**Comment by rade** [comment]
Fixed by #1615.
