### ISSUE TITLE
testNameservers unit test is quite slow

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1614]
It was timing out in CI, so I investigated where all the time went.

Around 60-80% of the time is in case-insensitive string comparisons; evidently Go's handling of Unicode makes this expensive.

The total number of entries managed by nameservers in the test goes up linearly with the number of iterations.  For each iteration there is then a linear function of comparisons in `IsSorted()` and `merge()` and an n log n function in `Sort()`, although the test only ever sorts nontrivial arrays in the periodic gossip.  For low-thousands numbers of iterations the `IsSorted()` and `merge()` ones are more expensive.

Thoughts on ways to speed it up:

- We could cache the `ToLower` output, trade memory for CPU.
- `merge()` could use binary search to find the insertion points; generally the incoming data is far smaller than the existing data.
- Since DNS has special considerations for Unicode characters, it may be that the full generality of case-insensitive handling is unnecessary.

The next-highest impact seems to be garbage collection, but I didn't investigate that.

**Comment by bboreham** [comment]
Actually I think the timeouts are caused by https://github.com/miekg/dns/issues/282 which is causing a lot of allocation of error objects and hence garbage-collection.

**Comment by rade** [comment]
That miek/dns issue is resolved now. But CircleCI is still failing on #1615.

**Comment by bboreham** [comment]
Addressed by holding on to the `ToLower` output in 609d45867593ef73824bcf446e250ce1ca2a6222
