### ISSUE TITLE
Weave proxy --rewrite-inspect incorrectly populates `.NetworkSettings.IPAddress` in API

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1618]
Related to #1601, docker/docker#17494.

**Comment by rade** [comment]
Options:
- don't set `.NetworkSettings.IPAddress` unless there's one there already
- don't set `.Networksettings.IPAddress` in new versions of API

The first of these is easier but means containers started with `--net=none` even on older docker api versions, will not report an `IPAddress`. Don't know how much of a problem that is.

Of course this then begs the question of where we should put the information instead.

- add an entry to the list in `.NetworkSettings.Networks` for weave. As discussed on #1601.
- rewrite the "bridge" entry in `.NetworkSettings.Networks`
- both

The decision here very much depends on how the new API ends up getting used. I suspect the 2nd or 3rd option will be the one we have to go for.

**Comment by awh** [comment]
Docker have restored `.NetworkSettings.IPAddress` in accordance with their deprecation policy, so there is no immediate need for this.

**Comment by bboreham** [comment]
I can't see an explicit deprecation of `NetworkSettings.IPAddress` by Docker, so can we close this issue and leave the possible extensions in #1601?
