### ISSUE TITLE
with FASTDP, application containers can control weave

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1632]
```
$ weave reset
$ weave launch
$ weave docker-bridge-ip
172.17.42.1
$ docker $(weave config) run -ti ubuntu
root@cc4d33557cc4:/# nc 172.17.42.1 6784
foo
HTTP/1.1 400 Bad Request
```

Now, the same is possible w/o FASTDP...

```
$ weave reset
$ WEAVE_NO_FASTDP=1 weave launch
$ docker inspect -f '{{.NetworkSettings.IPAddress}}' weave
172.17.0.29
$ docker $(weave config) run -ti ubuntu
root@c0197cdff032:/# nc 172.17.0.29 6784
foo
HTTP/1.1 400 Bad Request
```

but that can be disabled by running docker with `-icc=false`:

```
$ weave reset
$ WEAVE_NO_FASTDP=1 weave launch
$ docker inspect -f '{{.NetworkSettings.IPAddress}}' weave
172.17.0.1
$ docker $(weave config) run -ti ubuntu
root@e98d44350b9c:/# nc 172.17.0.1 6784
foo
(no response)
```

whereas with FASTDP we still get the same result

```
$ weave reset
$ weave launch
$ docker $(weave config) run -ti ubuntu
root@2fc245e5bd53:/# nc 172.17.42.1 6784
foo
HTTP/1.1 400 Bad Request
```

We should document the importance here of setting `-icc=false` (we already do that for other reasons), but more importantly we need to find a way of preventing access to weave from container when running with FASTDP. I am guessing a couple of iptable rules that prevent access from the docker bridge to local weave control. And data port, since otherwise containers can inject traffic on unsecured weaves.

**Comment by dpw** [comment]
Could we get away with binding the HTTP listener to 127.0.0.1?

**Comment by rade** [comment]
> Could we get away with binding the HTTP listener to 127.0.0.1?

I think that would work, and would prevent access even when `-icc=true`.

That still leaves the 6783 access, which can't be restricted to 127.0.0.1. Let's file a separate issue for that because a) I suspect this was always accessible from containers, with our without icc, and b) it can be mitigated by enabling crypto.

**Comment by awh** [comment]
> That still leaves the 6783 access, which can't be restricted to 127.0.0.1. Let's file a separate issue for that because a) I suspect this was always accessible from containers, with or without icc, and b) it can be mitigated by enabling crypto.

There's also 6784 UDP now, which can't be mitigated by crypto...
