### ISSUE TITLE
inclusive start + exclusive end IP address interval notation is confusing

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1635]
e.g. we show ranges like `[10.32.0.0-10.48.0.0)` in `weave status`.

It would be better to display inclusive intervals, e.g. `[10.32.0.0-10.47.255.255]`.

**Comment by squaremo** [comment]
I recommend using the inclusive figures, and dropping the braces altogether.

**Comment by awh** [comment]
> I recommend using the inclusive figures, and dropping the braces altogether.

:bento:

**Comment by awh** [comment]
Fixed by #1636.
