### ISSUE TITLE
lack of diagnostics when IPAM is stuck but does have consensus

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1639]
IPAM can get stuck even though it does have consensus, because a) the entire range is owned by a node which is currently dead, or b) the entire range is allocated.

This is hard to diagnose at present. `weave status` reports on the consensus state only. `weave report` has the info, but a) it's not something we expect users to have to look at, b) the info is not particularly digestable, and c) it's not showing nicknames, which, if an entry belongs to a dead node, is crucial for identifying what node is the problem.

See #1638 for an example.

Suggestions:

1. annotate the ipam entries list in the `weave report` with nicknames. Alternatively, include the nickname map as a separate item (though this is noisy and less helpful in the typical case)
2. introduce a `weave status ipam` that shows *summarised* information about IPAM:
    - the allocation range
    - the total number of IPs in the range, the total number of free IPs, the total number of allocated IPs, and some free/allocated percentage figures - yes, these are not necessarily accurate
    - the same figures, for every peer mentioned in the ring
    - NB: I don't think we should list ring entries

**Comment by bboreham** [comment]
Note `weave status` used to print the nicknames against IPAM ranges, but this was lost in #1248

**Comment by rade** [comment]
> - the total number of IPs in the range, the total number of free IPs, the total number of allocated IPs, and some free/allocated percentage figures

Perhaps that figure should go into the main ipam section in `weave status`.

Generally though the free/used info is not particularly useful when dealing with subnets. Hmm. Is it still worth showing?

Also, perhaps when showing the peer names we should indicate whether they are currently alive. And perhaps go further and show free/allocated figures for "all live peers" and "all dead peers". Or something like that. Basically we want to make it obvious when all free IPs are owned by dead peers.

**Comment by inercia** [comment]
What do you think about this?

```
$ weave status ipam
         Range: 10.32.0.0-10.47.255.255
 DefaultSubnet: 10.32.0.0/12
         Local: owned: 10.32.85.87+1 free: 10.32.85.88+21844 
    Ownerships:
             (local) -> 10.32.170.172,10.32.85.87,10.33.85.87,10.34.170.172,10.38.170.171,10.40.0.0,10.43.85.85,10.44.0.0,10.45.85.85
               host3 -> 10.32.0.0
               host2 -> 10.37.85.86
               host1 -> 10.42.170.171,10.47.255.255

    Containers:
                e55b6b09bb3a521b27192e79648f2b210e77785ec6ed4f16441787068ceca146: [10.32.85.87]
        Claims:
```

Would it be better to use the number of IPs? Where can I get information whether a peer is alive or not?

**Comment by bboreham** [comment]
Are you asking how you can find whether a peer is believed to be reachable ?  By design, we don't try to guess whether a peer is temporarily unavailable or truly dead. 

It's plausible that reachability could be on the Gossip interface; we already infer it from an error return from a unicast. (On phone; sorry if some names are wrong)

**Comment by rade** [comment]
Dead peers are those peers mentioned in ring/nicknames which are not in `Peers`.

**Comment by bboreham** [comment]
> those peers mentioned in ring/nicknames which are not in Peers.

They're unreachable but not necessarily dead. 

Network partition is indistinguishable from node failure.

**Comment by rade** [comment]
yes, yes, yes. Please examine what problem this issue is actually trying to address. And what we did in #1624, which is directly related to this issue.

**Comment by bboreham** [comment]
Ah yes, forgot `IsKnownPeer`

**Comment by bboreham** [comment]
#897 also related

**Comment by inercia** [comment]
What about this?

```
$ weave status ipam
      Universe: 10.32.0.0-10.47.255.255 (1048576 IPs)
 DefaultSubnet: 10.32.0.0/12
    Containers:
                8e68d256f83bd31317c51687704e8b751afde0d9cd846e6ccd37c028d1279936: [10.34.170.171]
    Ownerships:
             (local): owned:   699051 IPs (66.7% of universe) in   3 ranges- used:        3 IPs 
               host1: owned:   174763 IPs (16.7% of universe) in   1 ranges- used:        1 IPs 
               host2: owned:   174762 IPs (16.7% of universe) in   1 ranges- used:        1 IPs - unreachable!
```
