### ISSUE TITLE
Authenticated encryption for fast datapath

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1644]
The current AE implementation operates in userspace and is therefore incompatible with the fast datapath overlay - an alternative (almost certainly IPsec) is required.

**Comment by DanielDent** [comment]
I'd like to express my +1 for this issue.

I have a small test deployment of weave (10 machines), and I'm quite disappointed by the CPU utilization. Right now there is only background cluster management traffic. It's at most 0.25 megabits/second.

Half of the machines have TrustedSubnets which allow them to use the fast datapath. They have negligible CPU utilization (hovering in the 0.3-1% range).

A machine outside the trusted subnets uses a consistent 10% CPU. And that's with very little traffic.

I'm concerned that right now Weave might not actually be usable if you do anything which uses bandwidth over the internet.

**Comment by rade** [comment]
@DanielDent please conduct some actual measurements of non-fastdp performance. The figures you are reporting are a few orders of magnitude below what we have seen.

**Comment by bboreham** [comment]
That CPU usage sounds high.  For comparison, I ran a 3-host weave network on VMs on my desktop, and set two of the hosts pinging the third with `ping -s 64000 10.40.0.0`, so around 1Mbit/sec, then measured `weaver` cpu on the ping-ed host using `top`.
Using master it hovers between 1.0% and 1.3%, occasionally jumping to 2.0%
Using Weave Net 1.4.2 it floats between 0.7% and 1.7%.

@DanielDent if you run with `--log-level=debug` you should see something logged for each packet (so don't run like that for long), but it may help to judge whether there is more going on than you expect. And/or you could file that log as a new issue and we'll take a look.

**Comment by dpw** [comment]
Did anyone look into using a gre tunnel rather than vxlan, and then wrap that in espinudp? It might work.

**Comment by awh** [comment]
@Punkbob I'd be very interested to hear your results - I did some experiments a few months ago (Libreswan and ip xfrm) and was unable to get the kernel to apply IPsec to UDP traffic originating from the ODP VXLAN vport. Please keep me apprised!

**Comment by Punkbob** [comment]
So I've tested it between some instances in AWS and it seems to work over IPsec as no traffic at all (both TCP/UDP) is passing when it's enabled globally enabled but the other side isn't peered. But I haven't verified that all traffic is encrypted yet as I haven't had a chance to setup an environment that would let me dump all network traffic to inspect it.

**Comment by awh** [comment]
Some experimental stuff here:

https://github.com/awh/weave/commits/ipsec-experiment
https://github.com/awh/weave/commits/ipsec-experiment2

**Comment by awh** [comment]
Also

https://github.com/awh/netlink/tree/xfrm-algo-aead

**Comment by 2opremio** [comment]
Good job! \o/
