### ISSUE TITLE
Integration tests fail in 604_proxy_docker_py_test.sh

### ISSUE THREAD

**Issue by inercia** [weaveworks/weave#1675]
Integration tests fail with:

```
>>> Test ./604_proxy_docker_py_test.sh finished after 137.7 secs with error: exit status 1
Run docker-py test suite against the proxy
ERROR: file not found: tests/integration_test.py
```

See https://circleci.com/gh/weaveworks/weave/3658 , https://circleci.com/gh/weaveworks/weave/3656 ...
Broken in docker/docker-py#851

**Comment by bboreham** [comment]
Fixed by 804e6ba5860552f41f513d2b674ee76f48bc8181
