### ISSUE TITLE
weave's `docker pull` will stop working on December 7

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1683]
and hence `weave setup` and `weave launch[-*]`. Because we embed a Docker 1.3 client...

From https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/

> * On November 19, 2015 Docker clients version 1.5 and earlier will not be able to push images to Docker Hub. They will still be able to pull images. And of course the repositories are fully accessible via newer versions of the Docker client.
* On December 7, 2015, pulls via clients 1.5 and earlier will be disabled. Only version 1.6 or later will be supported.

I believe Bryan has seen some deprecation warnings already, so we should upgrade soon so that users aren't bombarded with these confusing messages (which will refer to a docker version they themselves aren't running).

**Comment by bboreham** [comment]
As a work-around users can run `weave setup --local`.

Indeed I could see an argument for handling `weave setup` locally always, like we do `weave version`. It ends up pulling `weaveexec` locally anyway, and by the time that's done there's not much left to do.

**Comment by bboreham** [comment]
The deprecation warning I saw was for a `start` api call with config that should go in `create`, so affects 3rd-party tools that do that.

**Comment by rade** [comment]
Note that we pin the API version in the proxy to v1.15, which corresponds to 1.3. I *don't think* that will cause any problems, but we should probably update that too.
