### ISSUE TITLE
Upgrade embedded Docker client

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1684]
I received an email from Docker stating:

> This is a second reminder about the upcoming deprecation for support of clients versioned 1.5 earlier in Docker Hub. 
>   * On December 7, 2015, pulls via clients 1.5 and earlier will be disabled. Only version 1.6 or later will be supported

Weave bundles Docker client 1.3, so this must be upgraded.

**Comment by rade** [comment]
dup of #1683
