### ISSUE TITLE
dns questions when upgrad to 1.3 

### ISSUE THREAD

**Issue by jkwebster** [weaveworks/weave#1685]
Hi  guys:
I can run these commads well with 1.1,but when I  upgraded to 1.3 ,it gave me an exception "The 'launch-dns' command has been removed; DNS is launched as part of 'launch' and 'launch-router'.",what could I do?Thanks
--------------------------------------------------------
weave launch -iprange 10.2.3.0/24   
weave launch-dns 10.9.1.1/24 -debug
weave launch-proxy --with-dns
eval $(weave proxy-env)
------------------------------------------------------------

**Comment by rade** [comment]
> I can run these commads well with 1.1

Are you sure you don't mean 1.0? The warning you are seeing was introduced in 1.1

> gave me an exception ""The 'launch-dns' command has been removed; DNS is launched as part of 'launch' and 'launch-router'."

That's a warning, not an exception.

> what could I do?

See the "installation and upgrading" notes in https://github.com/weaveworks/weave/releases/tag/v1.1.0

Essentially, instead of your four commands, simply run
```
weave launch --ipalloc-range 10.2.3.0/24
eval $(weave env)
```
