### ISSUE TITLE
allocation address range across multiple servers

### ISSUE THREAD

**Issue by jkwebster** [weaveworks/weave#1686]
Hi  there, I wanna make sure every docker container in different servers can communicate each other,I have tested "weave launch --ipalloc-range" ,containers on ServerA could be assigned with 10.2.3.x ip address,but containers on ServerB could not obtain 10.2.3.x address , how coudl I do?
docker version:1.9
weave version:1.3

ServerA(10.139.0.1)
weave launch --ipalloc-range 10.2.3.0/24
eval $(weave env)

ServerB(10.139.0.2)
weave launch --ipalloc-range 10.2.3.0/24 10.139.0.1
eval $(weave env)

**Comment by bboreham** [comment]
Hi, when you say "could not obtain", what exactly did you see?  Was there an error message?

Can you show how the container was started?

**Comment by jkwebster** [comment]
yes,containers were all started,but there was some warning information like this: 
![snip20151116_126](https://cloud.githubusercontent.com/assets/12273980/11172778/ae31a416-8c47-11e5-8c4c-d8537297a19a.png)

**Comment by bboreham** [comment]
OK, so the second half of that is saying that you won't be able to use 10.2.3.0/24 inside Weave Net because something else on your host or network is already configured to use the wider range 10.0.0.0/8.

**Comment by jkwebster** [comment]
Thanks，but because I wanna make sure every containers on different hosts could be communicated with each other,so I have to keep the same ip range.
![snip20151116_128](https://cloud.githubusercontent.com/assets/12273980/11176767/d6d4fffc-8c7a-11e5-8729-3d8731000814.png)

**Comment by bboreham** [comment]
Ok, but something else got to that particular range first. 

If you do `ip route` on that host you should see how the 10.0.0.0/8 range is configured. That may help you to decide whether the 10.0.0.0/8 range is truly needed. 

It's also possible that rebooting the host will clear it out and let you proceed.

**Comment by jkwebster** [comment]
oops,you are right,10.0.0.0,127.0.0.0 and 192.168.0.0 had been ocupied by our CLOUD COMPUTING provider,  so if I want to establish docker over cloud virture machines,what shoud I do?Should  I change the ip range 10.0.0.0/8 to 12.0.0.0/8?
PS,above network settings were ok with weave 1.0 version,but now is 1.3,everything is breakdown.
-----------------------with 1.0 version-----------------------
weave launch -iprange 10.2.3.0/24 10.139.97.78
weave launch-dns 10.9.1.2/24 -debug
weave launch-proxy --with-dns
eval $(weave proxy-env)

**Comment by jkwebster** [comment]
@bboreham thanks much,I have deleted that iptable rule and reboot host,now every container can obtain correct ip address and also can communicate with each other cross hosts!
