### ISSUE TITLE
Improve branching process for updating release docs

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1700]
The current process around `latest_release_doc_updates` is poorly understood and error prone, and the circular merging a concern (at the very least it leads to a confusing commit history). I propose a new scheme:

* When the documentation for a specific release needs to be corrected, we create on demand a branch `X.Y.Z_doc_updates` from the release tag `vX.Y.Z`. The desired updates are made on this branch; pushing to the branch triggers the CI to build and update the documentation for release `X.Y.Z`.
* `X.Y.Z_doc_updates` is then immediately merged into the `X.Y` bugfix branch and from there into `master`, so that the updates are incorporated into the next bugfix and mainline releases
* Periodically remove old `_doc_updates` branches

This has the following benefits and characteristics:

* The circular merging is eliminated. All changes flow from the most specialised branches in towards `master`
* It is possible to correct the documentation for arbitrary historic documentation versions (the current process only supports updating the latest release)

Tasks:

* [ ] Update CI/site build and release script to pattern match and process `$TAG_doc_updates` branches
* [ ] Document process

**Comment by rade** [comment]
Do we ever actually make doc changes on a X.Y branch that cannot go live straight away? It would have to be something quite exceptional.

So perhaps we could do away with the X.Y.Z_doc_updates branches and simply publish whatever is on the X.Y branch.

**Comment by awh** [comment]
Indeed, the branches are mainly required to allow you to publish updates in advance of a bugfix release (they have the side effect of letting you correct historic versions too, but I don't think we've ever needed that really). We would lose the ability to document changes that only made sense in conjunction with an as yet unreleased change of functionality, but we are talking about maintenance branches so it's probably not a big deal - it's a big win in terms of process simplicity though, so I'm for it. Any thoughts @bboreham?

**Comment by bboreham** [comment]
Yes, I think we can assume we won't queue up a behavioural change that needs doc changes on a patch version branch; we'll either release it immediately or queue it up on a major release.

**Comment by rade** [comment]
In the exceptional event that we do want to queue up a doc change for a patch release, we can create a branch for that, and merge it into X.Y just before the release. Much as we have been doing for README changes.

**Comment by awh** [comment]
Closed by #2212.
