### ISSUE TITLE
Weave with Marathon Issue

### ISSUE THREAD

**Issue by mehiar** [weaveworks/weave#1705]
Hi,

I have a Mesos cluster that runs Marathon as a framework for scheduling docker containers on the Mesos Slaves. I am running Weave on all Mesos Slaves and connecting them to each other. When I launch a new docker using the "docker run" command from one of the Mesos Slaves, I am able to get the "ethwe" interface for the created container. But when I submit a request to Marathon using the CURL command, it creates a docker container on one of the Mesos Slaves but without getting the "ethwe" interface for the created container. 

I was wondering if you know how I can get Marathon to use the Weave interface by default for the docker containers that it creates over the Mesos Slaves.

P.S. I have seen this problem reported before in another blog (https://groups.google.com/forum/#!topic/marathon-framework/w2mFNs0tkL4) without seeing an answer and also I took a look on the documentations in (http://weave.works/guides/platform/mesos-marathon/os/centos/cloud/vagrant/) but did not find how to solve this.

Thanks,
Mehiar

**Comment by errordeveloper** [comment]
@mehiar have you set `MESOS_DOCKER_SOCKET=/var/run/weave/weave.sock` environment variable for the slave process?

**Comment by mehiar** [comment]
No I have not. Could you please tell me where I need to set that environment variable?
Should I just execute the command: "export MESOS_DOCKER_SOCKET=/var/run/weave/weave.sock" on the Mesos Slaves?

**Comment by mehiar** [comment]
Thank you for your help.
I set the env variable that you mentioned using the documentation in (http://mesos.apache.org/documentation/latest/configuration/) and that did work!
