### ISSUE TITLE
weave fast data path with weave router container

### ISSUE THREAD

**Issue by AdoHe** [weaveworks/weave#1713]
weave now use `fdp` by default, so the `weave` bridge is actually an OVS bridge. I feel confused about the current weave workflow, in the old version, the weave router will capture Ethernet packets from its bridge-connected interface in promiscuous mode, using 'pcap’. But for the `fdp`, I think weave router will not do any packet capture or packet encapsulation, I don't know whether this is right, I am not familiar with `odp`, besides whether the data packet will flow through the weave router container?

**Comment by dpw** [comment]
Did you already look at the blog post at http://blog.weave.works/2015/11/13/weave-docker-networking-performance-fast-data-path/ ? It gives a high-level overview of how fast data path works.  There was a paragraph that got cut from that blog post that might help to answer your question:

 > Fast data path takes advantage of the kernel's Open vSwitch datapath (ODP) subsystem, which allows the weave router to tell the kernel how to process packets, rather than processing them itself.  ODP operates in terms of "flow rules", which say how to handle packets with certain header field values.  ODP reports a "miss" event to the weave router when it encounters a packet that doesn't match a flow rule.  This  happens, for example, for the first packet between a specific source container  and destination container.  But the weave router then adds an appropriate flow rule, so that further packets can be handled entirely within the kernel.

Does that help a bit?

Unfortunately, there's not much documentation for the openvswitch kernel module to point to.  It's mostly necessary to read its source code to understand its functionality (and by extension, how weave net fdp works).

To some extent, the mechanism by which the weave router arranges for packets to be encapsulated shouldn't really matter to users of weave.  But I can understand that it is of interest.  @awh was working on some documentation that might be relevant, so I'll see what happened to that.

Other than that, are there specific questions or concerns you have about fdp, or are you asking out of general interest?

**Comment by AdoHe** [comment]
@dpw, thanks very much, I am quite interested in the `fdp` approach, I also had a look at other `vxlan` approach, like `flannel`, I just found it is hard to understand the `fdp` approach of weave. I am trying to figure out the packer flow, and I guess it should be this: `container[ethwe] -> weave[vethwe*] -> weave router container -> host[eth0]`, is this right? where does the packet encapsulation take place?

**Comment by AdoHe** [comment]
@dpw after read this blog, I think I know  how fdp works. Thanks very much. Besides I think the weave document should be updated.

**Comment by dpw** [comment]
> I am trying to figure out the packer flow, and I guess it should be this: container[ethwe] -> weave[vethwe*] -> weave router container -> host[eth0], is this right? 

There are two paths for a packet, depending on whether a matching flow rule has been created in odp or not:

```
container[ethwe] -> ODP [weave datapath] -> vxlan driver -> host[eth0]
                     |          ^
                   (miss)       |
                     |          |
                     v          |
                     weave router
```

> where does the packet encapsulation take place?

Encapsulation always takes place in the kernel (in the kernel's vxlan driver).  If the weave router already defined a flow rule that matches the packet, then this occurs without any involvement from the weave router.  If there is no matching flow rule for the packet, then ODP reports a miss to the weave router, then the weave router defines an appropriate flow rule (and also re-injects the packet that caused the miss).

**Comment by AdoHe** [comment]
@dpw I think this approach is similar to other `vxlan` based approaches, just link in `flannel`, the `flanneld` daemon will handle miss. Thanks very much.

**Comment by dpw** [comment]
> @dpw I think this approach is similar to other vxlan based approaches, just like flannel, the flanneld daemon will handle miss. Thanks very much.

It's a bit different.  Flannel's vxlan backend does not use ODP, but rather works on the basis of route cache miss events.  These events do not include the packet, so it's not possible to implement the fallback to userspace encapsulation that weave does. And ODP is in general a more versatile mechanism, as it's the basis for openvswitch.

**Comment by AdoHe** [comment]
@dpw exactly, it's a bit different. I looked the flannel source code again, the `flanneld` daemon will just handle L3 route miss, there is no fallback to userspace encapsulation. What's more have you ever did any tests about flow rule miss for packet?  does this miss happens frequently? You know user-space promiscuous capture is obscenely slow.

**Comment by dpw** [comment]
> @dpw exactly, it's a bit different. I looked the flannel source code again, the flanneld daemon will just handle L3 route miss, there is no fallback to userspace encapsulation. What's more have you ever did any tests about flow rule miss for packet? does this miss happens frequently?

It depends on the use.  But in realistic scenarios, the miss rate is very low.

> You know user-space promiscuous capture is obscenely slow.

Well, that's how weave net worked before 1.2.  And while that is slow, it's not actually much slower than normal network performance on Amazon EC2.  I'm sure many people would consider that very slow, but many people are quite happy with it (the application is often the bottleneck).  For those people, the main benefit of fast data path is lower CPU use rather than higher network throughput.

**Comment by AdoHe** [comment]
@dpw Ok, I think I am more clear about weave, you guys did amazing job. Thanks very much! And keep in touch.

**Comment by dpw** [comment]
You are welcome.
