### ISSUE TITLE
`weave connect` for a known peer should act immediately

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1714]
Although #499 was closed, my recent observations say it isn't working now.

**Comment by bboreham** [comment]
The reason it isn't working, in my case, is that `cm.targets` has an entry `192.168.48.11:6783` but the code is looking for `192.168.48.11:0`

**Comment by rade** [comment]
Ah, I was wondering whether that is the problem. There's code in `checkStateAndAttemptConnections` that constructs a `completeAddr` that we should probably (re)use here.

**Comment by bboreham** [comment]
The code in `checkStateAndAttemptConnections` is using a cached copy of `ourInboundIPs`; are you saying `InitiateConnection` should re-compute the connections?

I could argue that check is inappropriate if the user has *told* us to connect to that address.

**Comment by rade** [comment]
that part of the is irrelevant to the `completeAddr` computation.

**Comment by bboreham** [comment]
Well, yes, but the code gets about twice as big if you have to repeat the if-statement.  It isn't a great example of code re-use.

**Comment by rade** [comment]
to be precise, I think *this* is the code you want:
```
		completeAddr := *addr
		if completeAddr.Port == 0 {
			completeAddr.Port = cm.port
        }
		address := completeAddr.String()
```
