### ISSUE TITLE
[solved] How to connect from office machine to private network in datacenter via weave?

### ISSUE THREAD

**Issue by nodkz** [weaveworks/weave#1717]
I have old openVZ network `10.0.0.0/24` and want to pass it to weave (which runs on `10.32.0.0/12`), that docker containers can communicate with old ovz containers for migration purposes.

How I can create one more interface in docker containers via weave with network `10.0.0.0/24`?

PS. I spent several hours to find solution, but can not solve it. Please help.

**Comment by bboreham** [comment]
Weave only connects containers to its own network.

I'm unclear why you talk about creating another interface, rather than setting up a route from the Docker containers to 10.0.0.0/24.  Maybe I misunderstood what you are trying to do.  Can you explain a bit more?

**Comment by nodkz** [comment]
![img_20151125_013712](https://cloud.githubusercontent.com/assets/1946920/11378515/c724f5b6-9315-11e5-9e78-bb29e1bbe387.jpg)

I have network `10.0.0.0/24 in datacenter` with mongo hosts. And with `weave` I want to have ability connect from `dev docker ubuntu` (at office dev-machine) to mongo hosts (at private network in DC). 

PS. Weave own network `10.32.0.0/12` works perfectly. I can ping all docker containers from dev machine with docker containers at datacenter and vice versa.

**Comment by errordeveloper** [comment]
It looks like you need to do `weave launch` on each of the mongo boxes, followed by `weave expose -h mongo-xx.weave.local`.

**Comment by nodkz** [comment]
@errordeveloper thx for your solution. But it can not be implemented.

`Mongo hosts` run under `Ubuntu14.04` under RHEL6 OpenVZ containers with kernel `2.6.32-34-pve`. So I can not install there docker for weave installation.

So I can pass `10.0.0.0/24` network only via `CentOS host` (top left corner).

**Comment by bboreham** [comment]
OK, thanks for the picture and the extra details.

One way to go is to NAT the Mongo addresses into the 10.32 weave network - we show an example of this under [service import](http://docs.weave.works/weave/latest_release/features.html#service-import).  You would run the `weave expose` and `iptables` commands on the CentOS host top-left in your diagram.

We also talk about running weave outside of Docker at #1566, but that's a much more difficult approach and we have no idea how well it will work on your specific RHEL kernel.

**Comment by nodkz** [comment]
@bboreham thank you for your answer.

Try `service import`, for me it does not work. May be I do something wrong. Also I am newbie in iptables.
So I did't find way how FORWARD network 10.0.0.0/24 via `weave` interface on `CentOS host`. I think that firewall in the weave container block this.

**From office dev host: ping works, but when connect to service it produce error:**
```
root@default:~# ping 10.0.0.7
PING 10.0.0.7 (10.0.0.7): 56 data bytes
64 bytes from 10.0.0.7: seq=0 ttl=63 time=6.124 ms
64 bytes from 10.0.0.7: seq=1 ttl=63 time=4.914 ms

root@default:~# telnet 10.0.0.7 27031
telnet: can't connect to remote host (10.0.0.7): No route to host

root@default:~# traceroute 10.0.0.7
traceroute to 10.0.0.7 (10.0.0.7), 30 hops max, 46 byte packets
 1  10.32.0.1 (10.32.0.1)  3.564 ms  5.295 ms  7.982 ms
 2  10.32.0.1 (10.32.0.1)  7.863 ms !C  5.590 ms !C  3.093 ms !C
```

So I found solution, it's a little bit redundantly and provided at the following comment.

**Comment by nodkz** [comment]
## Solution: how to connect from office machine to private network in datacenter via weave. 
### 1. On Server (CentOS host, which in datacenter on ip 76.13.1.9) this host can connect to private networks which not under weave:

#### 1.1 On host machine:
```
$ weave launch --password paSSword
$ weave expose
$ weave run 10.32.0.10/12 --privileged -it ubuntu
```
arg `--password` must be provided, because we will work via internet
flag `--privileged` gives ability to work with nat tables inside container. Without it it produce error `iptables v1.4.21: can't initialize iptables table nat': Permission denied (you must be root)`

#### 1.2 On docker container:
In my case it was created under id `1a0caabadc40`. For login use `docker attach 1a0c`.
```
root@1a0caabadc40:/# echo "nameserver 8.8.8.8" >> /etc/resolv.conf
root@1a0caabadc40:/# apt-get update && apt-get install -y iptables
root@1a0caabadc40:/# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
root@1a0caabadc40:/# iptables -A FORWARD -i ethwe -j ACCEPT
```
This iptables rules give ability to use this host like a proxy (gateway to host machine). When some traffic comes via weave network `ethwe`, it will be pass to docker host via `eth0`. And docker host have ability to connect another private networks, in my case to 10.0.0.0/24.
For detaching from container press `CTRL+p and CTRL+q`, otherwise `exit` cmd kill container.

### 2. Desktop machine at the office.
#### 2.1 On docker host machine.
This machine does not have white ip, it hidden under office gateway. It is not problem for weave, because connection will be established when we provide docker host ip at datacenter (in my case 76.13.1.9)
```
weave launch 76.13.1.9 --password paSSword
weave run 10.32.0.11/12 --cap-add=NET_ADMIN -it ubuntu
```
We should tune routing in container, so must provide arg `--cap-add=NET_ADMIN`. It is subset of flag `--privileged`, which we use on server (step 1.1). So you can use any of them. 

#### 2.2 On docker container
In my case container id is `b5ff89f69d043e28`, so run `docker attach b5`.
We must add gateway ip of docker container at server (step 1.2, In my case its ip `10.32.0.10`), which will proxied our requests to docker host (CentOS, private network in DC is 10.0.0.0/24 which works on this host).
```
root@b5ff89f69d04:/# ip route add 10.0.0.0/24 via 10.32.0.10
```
That's all. Now you can connect from office machine to private network in datacenter via weave.

**Comment by awh** [comment]
> May be you can provide better solution.

It's possible to simplify the office configuration by installing a single route on the *host* (instead of in each application container) and then adding a permissive forwarding rule to iptables:

```
dev-machine$ sudo ip route add 10.0.0.0/24 via 10.32.0.10
dev-machine$ sudo iptables -I FORWARD -i docker0 -o weave --dest 10.0.0.0/24 -j ACCEPT
```

All containers launched on `dev-machine` should now be able to reach anything on 10.0.0.0/24 with no further modification. Packets destined for that subnet will egress the container via it's docker provided `eth0` interface (due to the default route) and then be routed by the host kernel back into the weave interface.

It should also be possible to eliminate the masquerading from the datacentre configuration if you have a way to supply a route to 10.32.0.0/12 to your openvz containers. You could (in descending order of preference):

* Install the route (to 10.32.0.0/12 via CentOS `eth1` 10.0.0.10) on whatever is functioning as the default router for your openvz containers
* Install the route on each openvz *host*, mirroring what we've done for the office side configuration above
* Install the route in each container, mirroring your solution above

Once this routing is in place you should be able to get rid of the masquerading container and instead point your office side route at the exposed address of the weave interface in the datacentre.

If that's not possible you will need to keep the masquerading, but even that can be simplified. Again if you adjust your office side route to point to the exposed address of the weave interface in the datacentre, you should be able to do

```
centos$ sudo iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
```

on the datacentre CentOS host - no intermediary container required.

**Comment by awh** [comment]
It occurs to me that it may already be the case that 10.0.0.10 is the default route for your openvz subnet, as that CentOS machine appears to be acting as an internet gateway. If that's true you can just ditch the masquerading container and adjust the office side route as described above.

**Comment by nodkz** [comment]
@awh thanks for your advice. Really good solution! Thanks a lot!

Btw, how it would be great if you become a part of coreOS team. Weave and flannel rocks! Go away old-school port-mapping, ssh tunneling and vpn-networks!

**Comment by awh** [comment]
Thanks, you're welcome :smile:
