### ISSUE TITLE
"weave connect" doesn't.  sometimes.

### ISSUE THREAD

**Issue by Crazee** [weaveworks/weave#1720]
Tried to set up a weave network with 3 hosts.  Two ended up together and one by itself.  I had done "weave connect"s to join them all together but they didn't all work.  On the lone host "weave status connections" says

-> 172.86.160.2:6783     failed      IP allocation was seeded by different peers (received: [aa:8a:db:6a:b8:5e(host1)], ours: [da:98:1f:46:54:9d(host2)]), retry: 2015-11-25 21:38:30.450088251 +0000 UTC

Is the weave architecture broken?  It should just "make it so", right?

**Comment by rade** [comment]
From [the IP address allocation docs](http://docs.weave.works/weave/latest_release/ipam.html#initialisation):

> Just once, when the first automatic IP address allocation is requested in the whole network, weave needs a majority of peers to be present in order to avoid formation of isolated groups, which could lead to inconsistency, i.e. the same IP address being allocated to two different containers. Therefore, you must either supply the list of all peers in the network to `weave launch` or add the `--init-peer-count` flag to specify how many peers there will be.

**Comment by Crazee** [comment]
But I don't really know all the nodes in advance,  I'll want to grow them when I need to add capacity.
Isn't that what "weave connect" is for -- to add peers later?

Does adding peers on "weave launch" behave differently than on "weave connect"?

Maybe I'll try "--init-peer-count 2" everywhere to avoid the lone wolfs.

**Comment by rade** [comment]
> Isn't that what "weave connect" is for -- to add peers later?

Not necessarily. From [the dynamic topologies docs](http://docs.weave.works/weave/latest_release/features.html#dynamic-topologies):
> To add a host to an existing weave network, one simply launches weave on the host, supplying the address of at least one existing host.
> ...
> In some situations all existing weave hosts may be unreachable from the new host due to firewalls, etc. However, it is still possible to add the new host, provided inverse connections, i.e. from existing hosts to the new hosts, are possible.

`weave connect` caters for the latter situation.

> Does adding peers on "weave launch" behave differently than on "weave connect"?

Yes. Though perhaps more so than should be the case. See #1721.

> Maybe I'll try "--init-peer-count 2" everywhere to avoid the lone wolfs.

That could still result in "cliques". See the section on `--init-peer-count` in [the IP address allocation initialisation docs](http://docs.weave.works/weave/latest_release/ipam.html#initialisation).

**Comment by Crazee** [comment]
However it seems "No IP Addresses were harmed(tm)".  No one actually gave out any conflicting addresses.  Why not just stick on a band-aid and heal yourself instead of going off into a corner to pout?

**Comment by rade** [comment]
> No one actually gave out any conflicting addresses.

The conflict that weave is complaining about can only arise when IP address allocation was initialised in independent "cliques". And, as the docs I quoted say, initialisation only happens when the first automatic IP address allocation is requested. So in other words, there must have been at least two allocation requests, one in each of the cliques, prior to them coming into contact with each other. And those requests may well have handed out the same IP address.

Now, there are certainly situations where there may not be any conflict in allocated addresses, yet weave would complain. However, the lack of such conflicts would likely be down to luck.

**Comment by Crazee** [comment]
Your IPAM is being extremely difficult.  Does not want to play well with its peers.

I tried giving everyone the same global subnet with '--ipalloc-range' and each individual weave host a portion of that with '--ipalloc-default-subnet' -- I can make up a unique slice of addresses for each docker host -- and hoped the weave router can manage giving out addresses to containers on that host.  But nooo.

INFO: 2015/11/30 23:40:56.967900 ->[172.86.160.10:6783] attempting connection
INFO: 2015/11/30 23:40:57.473893 ->[172.86.160.10:6783|1a:55:7d:49:f3:57(host1)]: connection ready; using protocol version 2
INFO: 2015/11/30 23:40:57.474217 overlay_switch ->[1a:55:7d:49:f3:57(host1)] using fastdp
INFO: 2015/11/30 23:40:57.474319 ->[172.86.160.10:6783|1a:55:7d:49:f3:57(host1)]: connection added (new peer)
ERRO: 2015/11/30 23:40:57.558787 ->[172.86.160.10:6783|1a:55:7d:49:f3:57(host1)]: connection shutting down due to error: IP allocation was seeded by different peers (received: [1a:55:7d:49:f3:57(host1)], ours: [72:00:b4:f2:a0:c4(host2)])
INFO: 2015/11/30 23:40:57.559232 ->[172.86.160.10:6783|1a:55:7d:49:f3:57(host1)]: connection deleted
INFO: 2015/11/30 23:40:57.559345 Removed unreachable peer 1a:55:7d:49:f3:57(host1)
INFO: 2015/11/30 23:40:57.559403 [nameserver 72:00:b4:f2:a0:c4] peer 1a:55:7d:49:f3:57 gone

**Comment by Crazee** [comment]
Well I didn't actually try for "initialisation only happens when the first automatic IP address allocation is requested" by creating a "meaty" container that needed a weave DNS address.  My initialization scripts generate:
 weave launch-router --ip-alloc-range ...
 weave launch-proxy --tlsstuff ...
 weave connect [if other nodes already] 
 eval $(weave env)
 docker run --rm swarm create
 ...

The Swarm stuff is sort of an optional add-on which now runs after the basic weave stuff and doesn't really need weave addresses.  In fact when I had the '--init-peer-count 2' on the "weave launch-router" the "docker run --rm swarm create" command would just hang forever while weave was just sitting on the toybox with all the toys.

Navigating all the little constraints of weave has become a challenge and doesn't speak well for future maintainability.  If I get it to work at all.

**Comment by berlic** [comment]
I recently had "connection shutting down due to error: IP allocation was seeded by different peers" error.
I guess that I caught the error when started container attached to weave network **before** weave managed to connect to other peers.
I relaunched weave on this host to "clear" IP allocation history.
Everything went fine afterwards.

To sum it up: don't start any weave-attached containers before weave plugin is connected to other peers.
