### ISSUE TITLE
Make veth settings closer to those produced by the weave script

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1726]
The `weave` script does a few things like `ethtool tx off` that the plugin doesn't currently do.

Most of these are not relevant to FDP, only the "slow" path.

Replaces weaveworks/docker-plugin#53; see there for additional commentary.

**Comment by bboreham** [comment]
Also the `weave` script adds a multicast route for each container

**Comment by bboreham** [comment]
Multicast route covered by #1776; `ethtool tx off` less important now we're mostly not using pcap.

**Comment by rade** [comment]
> `ethtool tx off` less important now we're mostly not using pcap.

See #1788 for why that is the case.

**Comment by rade** [comment]
So what is left to do here?

**Comment by bboreham** [comment]
The predecessor issue noted "The arp stuff is relevant".

The `ethtool` point also relates to #1255

**Comment by bboreham** [comment]
The Docker plugin is not given direct access to the container's namespace, so adjusting its arp settings requires an indirect approach.  We could do it in the same place we add DNS names, i.e. after the container has started.

Note #2030 adds a utility function to do the arp settings.

**Comment by bboreham** [comment]
`tx off` now implemented by #2307; only arp settings and gratuitous arp remain.

These would have to be done asynchronously by the plugin, after the container starts, because they need to be done in the container's namespace.  Docker does not provide a hook to do this.
