### ISSUE TITLE
restricted electorate to help initial consensus

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1743]
Bootstrapping the data-structure used for IPAM communication between peers requires a consensus, to avoid multiple cliques forming independent data structures.  Currently we have a simple majority election - if you have 10 peers then 6 of them must vote to initialize - but this is unhelpful in situations where the number of peers may fluctuate.

As extension of this scheme, designate some peers as _electors_, and say others cannot vote.  Now it suffices to:
* designate a number of electors, say 3-5, for redundancy.
* have the electorate run an election at initial start-up, using the existing scheme.
* ensure that every other peer connects to at least one of the electors at start-up.

This scheme requires some additional administrative burden - the administrator must designate electors, and must keep them in the cluster.  But it retains the fundamental feature of being partition-tolerant once bootstrapped.

**Comment by bboreham** [comment]
Next question: how to specify the electorate?

Saying `--elector` to some peers would be simple but break backwards-compatibility; we'd need to add a `--not-elector` option on the rest.

Administrators may prefer to start every peer with the same set of arguments, in which case specifying the set of electors works - `--electorate=anne,fred,kim`.  Should these names be hostnames?  Nicknames?  Something else?

**Comment by rade** [comment]
> Should these names be hostnames? Nicknames? Something else?

Neither hostname nor nickname uniquely identify a peer, and generally are not things we should ever expect a user to specify.

We could go for "whichever peers live at these addresses". We'd need to cope with inbound connections from such peers somehow - perhaps just assume that if a peer connects from an address on the list then it is an elector. Lots of ways this could break, but meh.

**Comment by bboreham** [comment]
I was going to say that the one thing that is really difficult for a peer to know is its own address, but this changed when we started running the router in `--net=host`.  Except we don't always do that.

Note we currently allow users to specify nickname to `rmpeer`, and do not allow an address.

**Comment by rade** [comment]
Users *have* to know the address of the electors. Requiring them to know anything else is onerous.

**Comment by bboreham** [comment]
Further thought suggests that any scheme which changes the electorate will not be "backwards-compatible" in the sense that it would survive a large-scale restart part-way through the upgrade.  Users must shut down the entire cluster and restart it under the new regime.

To expand on a couple of ideas from earlier, suppose we have 5 peers and we want 3 of them to be electors.  One scheme would use a new flag to tell those peers which are not part of the electorate:

host1: `weave launch --init-peer-count=3 host1 host2 host3 host4 host5`
host2: `weave launch --init-peer-count=3 host1 host2 host3 host4 host5`
host3: `weave launch --init-peer-count=3 host1 host2 host3 host4 host5`
host4: `weave launch --init-peer-disabled host1 host2 host3 host4 host5`
host5: `weave launch --init-peer-disabled host1 host2 host3 host4 host5`

an alternative would tell all peers who is in the electorate:

host1: `weave launch --electorate=host1,host2,host3 host1 host2 host3 host4 host5`
host2: `weave launch --electorate=host1,host2,host3 host1 host2 host3 host4 host5`
host3: `weave launch --electorate=host1,host2,host3 host1 host2 host3 host4 host5`
host4: `weave launch --electorate=host1,host2,host3 host1 host2 host3 host4 host5`
host5: `weave launch --electorate=host1,host2,host3 host1 host2 host3 host4 host5`

**Comment by rade** [comment]
It makes no sense to specify an initial peer count for a non-elector. So we could make `--init-peer-count=0` the non-elector indicator.

The `--electorate` option is nice in that it allows all nodes to be started with the same command line. And it doesn't burden the user with counting :) The chief difficulty, as pointed out earlier, is that identifying peers by their address is problematic.

**Comment by bboreham** [comment]
> host1: `weave launch --electorate=host1,host2,host3 host1 host2 host3 host4 host5`

This leaves the problem "how do I know I am host1?"
