### ISSUE TITLE
`weave ps` does not show containers connnected by plug-in / double allocation of IPs and loss of DNS entries on restart

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1745]
Because it's looking for an interface called `ethwe`, and Docker+plugin ends up with `ethwe0`, or possibly some other number if you attach the container to multiple networks.

**Comment by rade** [comment]
when you say "break", you mean "doesn't show the weave addresses", right?

**Comment by bboreham** [comment]
Doesn't show addresses or IDs of connected containers. 

No diagnostic message is output.

**Comment by bboreham** [comment]
We could use `docker network inspect weave`, or API equivalent thereof, which gives us a nice list of the IP addresses we are missing.  Noting (#1803) that MAC addresses are currently absent from that data.

Docker recently added a `-f` option to this command which would be even more handy, although it is not released yet.  And we probably want to support Docker 1.9.0, which doesn't have `-f`.

**Comment by bboreham** [comment]
Given that users can use `docker network inspect weave`, I suggest we should just note this in the documentation and close this issue.

**Comment by bboreham** [comment]
I think the root cause of this will also cause IPAM allocations made via the plugin to be lost on `weaver` restart, because they are not reclaimed. Which can lead to double-allocation.

**Comment by bboreham** [comment]
Also DNS entries for plugin containers are lost on `weaver` restart.
