### ISSUE TITLE
unused vars in 'weave' script

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1748]
according to [shellcheck](http://www.shellcheck.net/) the following vars are unused:

- PROXY_PORT
- WITH_DNS
- IPAM_CIDRs
- CLIENT_TLS_ENABLED

IPAM_CIDRs is just a typo. PROXY_PORT and CLIENT_TLS_ENABLED are probably leftovers. @paulbellamy? WITH_DNS is suspicious, since it corresponds to a documented `weave run` option.

**Comment by paulbellamy** [comment]
I believe that `PROXY_PORT` and `CLIENT_TLS_ENABLED` are leftovers, yes.

**Comment by rade** [comment]
I have fixed the IPAM_CIDRs complaint in 20a48f05b and the PROXY_PORT issue in 3909936cc.

**Comment by rade** [comment]
The use of CLIENT_TLS_ENABLED got removed in https://github.com/weaveworks/weave/pull/1679/files. @awh @paulbellamy. So it's not on 1.3, so not part of this issue. Closing.

**Comment by rade** [comment]
> Closing.

oops, forgot about WITH_DNS. -> re-opening.

**Comment by rade** [comment]
`--with-dns` on `weave run` became non-functional when we merged the dns server into the router container. Yet we still have code and docs for it. We should fix that. NB: doc fix should go on latest_release_doc_updates.

Note that the *proxy* `--with-dns` *does* still do something atm, namely configuring containers to use weavedns even when weave may not be running at the time. I am not convinced this is all that useful. Covered by #1754.
