### ISSUE TITLE
SurrogateGossiper can accumulate infinite amounts of data

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1763]
SurrogateGossiper does not (and cannot) know how to merge GossipData, so instead it just stashes it in a queue. That is potentially unbounded since downstream connections in gossip propagation may not be able to accept data at the same rate it is received.

**Comment by bboreham** [comment]
Should move issue to the mesh repo?

**Comment by bboreham** [comment]
Moved to https://github.com/weaveworks/mesh/issues/68
