### ISSUE TITLE
make DNS listen address properly configurable

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1770]
as an enabler to #1301...

The weave script and proxy should
- pay attention to any `--dns-listen-address` passed in on `weave launch`, and use that instead of the docker bridge ip for configuring the DNS server
- obtain the DNS listening address from weave (via an HTTP call, just as we do for the domain) when configuring the resolver of containers and running `weave dns-lookup`, instead of always using the docker bridge ip

And we should document `--dns-listen-address`.

**Comment by gucki** [comment]
I just noticed that weave dns is not creating any dns records when passing `--dns-listen-address` to `weave launch`. So after starting a few containers `weave status` still reports 0 dns entries. Would be great if this could be fixed asap. Please let me know if I could help. Thanks.

**Comment by rade** [comment]
> I just noticed that weave dns is not creating any dns records when passing `--dns-listen-address` to weave launch.

Please file a separate issues, with steps to reproduce. It does seem somewhat unlikely since entry creation and query processing (which is all that the listen address is needed for) have very little to do with each other.

**Comment by gucki** [comment]
Sorry, I just figured out that it's was an error of me. I set hostname to a fqdn not ending in "weave.local" and then no dns entry is created, as documented.
