### ISSUE TITLE
documentation: standalone mode for scope returns a 404 error (weave.works main www)

### ISSUE THREAD

**Issue by v1k0d3n** [weaveworks/weave#1779]
it looks like there's an error on the main website for Scope Standalone documentation found at: http://weave.works/guides/weave-scope/weave-scope-alone.html

i can use the GitHub documentation for now at: https://github.com/weaveworks/guides/tree/master/weave-scope

but i wanted to make you guys aware of it (just to keep things tidy).

**Comment by bboreham** [comment]
Where exactly did that first link come from?  

It looks like it should be http://weave.works/guides/weave-scope/weave-scope-alone-monitor-containers.html

**Comment by v1k0d3n** [comment]
a google search for weave standalone scope returns the error (first two reference links). https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=weave%20scope%20standalone%20containers

i found it in the docs while drilling down too, but i will have to look again when i have a little more time. i remember it was pretty easy to find when drilling down into the scope docs (looking for stand-alone, docker-only scope instructions).

**Comment by bboreham** [comment]
OK, I found a couple.  Thanks for the report!

**Comment by bboreham** [comment]
Believe this is fixed now.
