### ISSUE TITLE
`weave launch|launch-router` tickles NetworkManager

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1783]
On master...

Running either `weave launch` or `weave launch-router` causes my Ubuntu NetworkManager to see new ethernet interfaces

I do not see this when running with `WEAVE_NO_FASTDP=1`

And, more importantly, I do not see this on the 1.3 branch.

**Comment by rade** [comment]
the culprits are `link-weave` and `datapath-link`.

**Comment by rade** [comment]
change the naming to
```
BRIDGE_IFNAME=veth-l-${BRIDGE}
DATAPATH_IFNAME=veth-${DATAPATH}-l
```
appears to solve the problem. Note that `link` is too long. I don't remember what the length restrictions are; we may need to give up some readability here in order to prevent obscure breakages when `$BRIDGE` or `$DATAPATH` are longer. So perhaps just `veth$BRIDGE` and `veth$DATAPATH`. Or constant names?

**Comment by awh** [comment]
> So perhaps just veth$BRIDGE

This naming is only possible now that I have removed the pcap optimisation in #1758 - if you remember there was already an interface named `veth-weave` in the host netns if encryption was in use.
