### ISSUE TITLE
proxy is lacking configurability of docker args

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1784]
The router launch pays attention to `WEAVE_DOCKER_ARGS`, so one can set resource limits, etc, etc.

The proxy doesn't.

Should it have its own env var or just use the same?

**Comment by bboreham** [comment]
@rade does `WEAVEPROXY_DOCKER_ARGS` meet the requirement?

**Comment by rade** [comment]
Clearly I was blind.
