### ISSUE TITLE
While building weave on ARM (scaleway)

### ISSUE THREAD

**Issue by faddat** [weaveworks/weave#1786]
![image](https://cloud.githubusercontent.com/assets/7142025/11782047/01739296-a2a1-11e5-8f96-8583f4f4b720.png)
![image](https://cloud.githubusercontent.com/assets/7142025/11782055/08f6a706-a2a1-11e5-9aef-e7b0cc4fff68.png)

**Comment by tomwilkie** [comment]
The alpine image is for x86; you'll need to use miek/alpine-armv6l (update docker/Dockerfile).

If this works, we can look at some way of making this work by default.

**Comment by tomwilkie** [comment]
You'll also need a way of embedding an arm-compatible docker build (we embed the docker binary).

**Comment by tomwilkie** [comment]
And you might want to join weave-users@weave.works, a chap there is trying to build scope for ARM too: https://groups.google.com/a/weave.works/forum/#!topic/weave-users/ITJDqMDJOEI

**Comment by faddat** [comment]
aha, got it.  Shouldn't be too tough :).  I'll let you know how it goes.  Okay, so I should replace:

1) the current alpine with miek/alpine-armv6l
2) the docker binary.... hmmmm I'll need to look into that part:  The best ARM docker I know of is the hypriot version, and I think it's only distributed in .deb-- which is harder:  Adapting the dockerfile to use ARM ubuntu, or making alpine install a .deb?

Thanks!

**Comment by tomwilkie** [comment]
re: (2), I'd just copy in your local docker binary and hope for the best...

**Comment by faddat** [comment]
:)

**Comment by faddat** [comment]
Back at it now, should be able to push something or another to Docker hub in a bit... Any chance that we can automate builds for ARM after we've got something working?  There are builds out there-- just a tad on the dated side.

**Comment by faddat** [comment]
So I can get this running, "dirty" without too much difficulty.  That said, I think the better path would be adapting the build chain so that it can support ARM.

**Comment by tomwilkie** [comment]
Once you get something running, submit a PR with the changes and I'll work
with you to try and get it built automatically.

**Comment by faddat** [comment]
I didn't do this myself, but...

https://github.com/armhf-docker-library/weave

**Comment by bboreham** [comment]
Are there actually two separate issues between this one and #1787?  Can I close this one?

**Comment by faddat** [comment]
Totally, no problem, in fact....
