### ISSUE TITLE
Build process is  intel oriented

### ISSUE THREAD

**Issue by faddat** [weaveworks/weave#1787]
Currently the Makefile and its attendant scripts / infrastructure is oriented around x86 builds.  Should be made generic through use of env vars or a separate build script.  Currently trying to work out the best way to "switch" things.  At least with regard to ARM, it seems best to use the docker binary from Alpine (though I am not yet 100% certain there is one).  The other option is downloading the hypriot docker binary, and extracting (at least that I've thought up so far)

**Comment by bboreham** [comment]
Fixed in #2713
