### ISSUE TITLE
expose isn't working for me

### ISSUE THREAD

**Issue by MSF-Jarvis** [weaveworks/weave#1789]
root@teamredux:~# weave expose
This is WEAVE, Version 4.4 (TeX Live 2015/Debian)
weave: fatal: web file `expose.web' not found.
root@teamredux:~# 

requested logs will be provided

**Comment by awh** [comment]
You're not actually running our script - you've got another package installed (probably `texlive-binaries`) that contains an executable named `weave` that is completely unrelated (as far as I am aware, it's part of Knuth's literate programming system used to implement TeX). You probably don't want it, in which case you can remove it:

```
sudo apt-get remove texlive-binaries
```

If that's not an option you can adjust your `$PATH` to prefer the location in which you installed the weave script that you downloaded.

**Comment by MSF-Jarvis** [comment]
Sorry for being n00by, you were right about texlive.
