### ISSUE TITLE
Fast datapath MTU limited to 1500 on CoreOS 877 (Linux 4.3)

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1853]
Symptoms are that if you `weave launch-router` with WEAVE_MTU set to anything over 1500 (on a network which supports it), the connection falls back to sleeve.

tcpdump shows the first heartbeat packet (which is sized to the MTU) doesn't get as far as the network device.

Although CoreOS 877 is a beta release, this is the first version with Docker 1.9, needed for Docker Network plugin support.

**Comment by bboreham** [comment]
Fastdp with large MTU works on CoreOS 870, which has kernel 4.2.2.

Interesting change: https://github.com/torvalds/linux/commit/614732eaa12dd462c0ab274700bed14f36afea5e

This puts the function we use to create the vxlan device inside an `#ifdef`'d section that is commented "Compat code for old userspace."

**Comment by dpw** [comment]
http://thread.gmane.org/gmane.linux.network/393878

**Comment by bboreham** [comment]
Removed from the 1.4.2 milestone as it seems this will need a kernel fix.

**Comment by rade** [comment]
> Removed from the 1.4.2 milestone as it seems this will need a kernel fix.

Surely we should detect & report this better. The issue isn't going to go away until the entire world has moved off the 4.3 kernel.

**Comment by rade** [comment]
So on further thought, a user will typically only run into this when setting the WEAVE_MTU. Which should establish a clear cause-effect relationship in their head. And the 4.3 breakage is just one of many ways things can go wrong when increasing the MTU. So, in conclusion, I don't think it is worth detecting this special case.

We may want to keep the issue open in order to track the kernel fix.

**Comment by dpw** [comment]
http://thread.gmane.org/gmane.network.openvswitch.devel/59076

**Comment by dpw** [comment]
http://article.gmane.org/gmane.network.openvswitch.devel/59097

**Comment by rade** [comment]
AFAICT the patches are included in the 4.5 kernel. We should re-test with that.

**Comment by rade** [comment]
Lots of fixes get backported by vendors, so kernel versions aren't a perfect guide. Still, issuing a warning would probably save a few folks some head scratching.

**Comment by brb** [comment]
> detect when users set a WEAVE_MTU>1500 on a 4.3 and 4.4 kernel and complain.

Maybe we could try to set >1500 MTU on a dummy vxlan vport and see whether it fails with EINVAL instead? In a case of the failure, we could issue a warning.

**Comment by rade** [comment]
> Maybe we could try to set >1500 MTU on a dummy vxlan vport and see whether it fails with EINVAL instead? In a case of the failure, we could issue a warning.

If setting a high MTU results in an error, why would we not simply catch that error when setting the MTU on the *real* vxlan port?

Also, has anybody checked that this issue is indeed solved in 4.5?

**Comment by brb** [comment]
> Also, has anybody checked that this issue is indeed solved in 4.5?

It is resolved at least in CoreOS 1010.5.0 (stable) which kernel is `4.5.0-coreos-r1`

**Comment by brb** [comment]
> If setting a high MTU results in an error, why would we not simply catch that error when setting the MTU on the real vxlan port?

Because we don't set a MTU when creating vxlan vport, see https://github.com/weaveworks/weave/blob/ec167554c50fc48c9cfffe9de464919356a59c8f/router/fastdp.go#L419

Setting >1500 MTU results in error (the 4.4.0-24-generic kernel on 16.04 LTS):

```
host:~$ sudo ip link set vxlan-6784 mtu 1400
host:~$ sudo ip link set vxlan-6784 mtu 6000
RTNETLINK answers: Invalid argument
```

**Comment by rade** [comment]
So how come `ip link set dev $DATAPATH mtu $MTU` in the script succeeds?

**Comment by brb** [comment]
It sets a MTU on the datapath interface which underlying implementation is different from vxlan netdev.  We use the interface as a bridging device.

Prior to 4.3, vxlan was not represented as netdev, therefore we could implement the following check in weave script:

1. Create a dummy vxlan vport.
2. Check if an interface for the vport exists.
3. If yes, set >1500 MTU.
4. If the op fails, issue a warning.

**Comment by rade** [comment]
I see. We could make all this part of `weaveutil create-datapath` by passing the MTU; `init_fastdp` would become a no-op.

**Comment by bboreham** [comment]
I'm going to close this as I can only remember one person ever complained, and #2376 covers the most likely change we would make.
