### ISSUE TITLE
make `weave launch` idempotent and start existing containers

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1859]
Currently, `weave launch` always does a `docker rm` on any previous containers.

If, instead, we did `docker start` on that container, this would fix #1757, and give a straightforward way to fix #901 and #678, by persisting the state into a file inside the container.

Users who wanted to change the launch options would need to do something to make that happen; perhaps `weave reset` before `weave launch-xxx`.

We might want to worry about log-file size too, since Docker carries on the same log-file after a stop/start.

**Comment by rade** [comment]
I suggest a separate set of commands for this: `weave start` and `weave start-{router,proxy,plugin}`. These would not take any arguments.

However, I am at a complete loss how any of this is supposed to interact with init systems. Seems to me that there is an underlying assumption here that restart is treated completely differently to start. What would yout put into your init script? `weave start || weave launch <args>`?

**Comment by bboreham** [comment]
> Seems to me that there is an underlying assumption here that restart is treated completely differently to start.

I can see that by separating `launch` from `start`, you made that assumption. But I don't see a problem with `weave launch` either starting or restarting depending on what it finds.

**Comment by rade** [comment]
>  I don't see a problem with weave launch either starting or restarting depending on what it finds. 

There is a very fundamental problem with that. When I say `weave launch --init-peer-count=2 --ip-alloc-range=10.2.0.0/32 --password foo` and that returns successfully, I do expect to be left with a router that has been configured with an init-peer-count of 2, an ip allocation range of 10.2.0.0 and and using encryption with the password 'foo'. Simply starting any existing stopped weave container is not guaranteed to give me that.

It is for that very reason that `weave launch` currently does not return success when there already is a container running.

Or are you perhaps suggesting that `weave launch` should start any existing container (if there is one) *and then alter its configuration s.t. it matches the provided options*? That effectively requires the router and proxy and plugin to start into a dormant state where they cannot do anything that can be affected by configuration, and only become fully functional when such configuration has been supplied.

However, this runs completely counter to the idea of restart policies, where you expect a container to be restart and become functional with the same settings as it had before.

**Comment by rade** [comment]
Hmm. How about a way to to start an existing container *only if it had been created with the same options*? Then we need a way to get back the existing behaviour, since `weave reset` is too harsh. Which brings us back to a `launch`/`start` distinction. `launch` would work as now (which is good for backward compatibility too), whereas `start` would behave like `launch` when there is no stopped or running container, and otherwise check that the container has the same args as supplied, and, if it's stopped, start it.

**Comment by bboreham** [comment]
I explicitly said that my proposal needed something extra for users who wanted to change the launch options.

**Comment by rade** [comment]
> I explicitly said that my proposal needed something extra for users who wanted to change the launch options.

I saw that. But my point is that if there is a command that accepts options, starts a fresh container when there isn't one, and restarts an existing container when there is, then that command *must only do the latter if the given options are the same as that of the existing container*.

Or in other words, we must not have a command that looks like it is starting weave with certain options but may actually end up restarting an existing container with completely different options.

**Comment by rade** [comment]
>  check that the container has the same args as supplied

We could compare `docker inspect -f '{{.Args}}'` of any existing container against the arguments we have computed for the prospective new container. We also need to compare the password. `fetch_router_args` already extracts both these pieces of information.

**Comment by rade** [comment]
> `fetch_router_args` already extracts both these pieces of information.

It [no longer](https://github.com/weaveworks/weave/commit/799160c5c2158683793b98540a62258a0387cf7e) extracts the password.

**Comment by DanielDent** [comment]
Rather than using a persistent container, what about storing state in a docker volume?

**Comment by rade** [comment]
> Rather than using a persistent container, what about storing state in a docker volume?

That's something to look at in the future. For now we aren't actually planning to store any state in the container.

> How about a way to to start an existing container *only if it had been created with the same options*? Then we need a way to get back the existing behaviour, since `weave reset` is too harsh.

How about this behaviour for `weave launch`...

- when there is a running/restarting container, using the correct image, and the same args, it succeeds
- when there is a running/restarting container, using the wrong image or different args it fails with an error message suggesting to run `weave stop`
- when there is a stopped container, using the correct image, and the same args, it starts it
- when there is a stopped container, using the wrong image or different args, it removes it and starts a new one
- when there is no container, it starts a new one

**Comment by bboreham** [comment]
> we aren't actually planning to store any state in the container.

To be fair, storing state is called out in the original description; it's more of a follow-up thing to fix those other issues.

**Comment by rade** [comment]
we should probably also make `weave stop` idempotent at the same time, i.e. it should only fail if there is a running container and it fails to stop it.

**Comment by rade** [comment]
cunning plan for argument comparison, which avoids escaping issues: create (but not start) a temporary container with all the supplied args. Then simply compare the output of `docker inspect -f '{{.Args}}` of both that and any existing container.

In order to detect password changes, we can pass a hash of the password as a dummy parameter.

The arg comparison, and general "is it already running?" detection can happen right before we attempt to start the container, which simplifies things a fair bit since at that point we know all the args. The downside is that `weave launch` might subsequently trip over a proxy container running with different than expected args.

Another consideration is what we should do about restarting containers. Above I said that they should be treated as running. But arguably that is not correct / most useful. Perhaps we should wait for them to start.

**Comment by bboreham** [comment]
Also need a strategy for weave upgrades.  "If the container we would start has the same image-ID as the existing one and the same arguments ..." ?

(Upgrades also represent a problem for the idea of persisting state inside the container)

**Comment by rade** [comment]
>  same image-ID

I included that in "correct image".
