### ISSUE TITLE
DNS entries can leak when a peer restarts quickly

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1867]
When a peer restarts quickly, not all other peers necessarily see the peer go away, since topology gossip data merging may combine the removal and addition, or the events get re-ordered in transit, with the removal being skipped (since it will have an earlier version) - both of these effectively just end up updating the peer UID and version. If that happens on just a single peer then the DNS entries of the restarted peer are all retained. This is problematic in two ways:

- if any containers died on the peer while the weave router was down, their entries are leaked.
- for surviving containers, the version of the re-created entry may well be lower than the existing one, e.g. if previously the entry had been tombstoned and resurrected a few times. If the last version of the entry known by surviving peers was a tombstone, then this will effectively wipe out the re-created entry.

Steps to reproduce
```
host1$ weave launch --no-discovery
host2$ weave launch --no-discovery $HOST1
host3$ weave launch --no-discovery $HOST2

host1$ weave run --name=foo -ti alpine /bin/sh
host3$ weave dns-lookup foo
10.32.0.1

host3$ sudo iptables -A INPUT -s $HOST2 -j DROP
host1$ weave stop; docker rm -f foo; weave launch --no-discovery $HOST3
host3$ sudo iptables -D INPUT -s $HOST2 -j DROP

host3$ weave dns-lookup foo
10.32.0.1
```

**Comment by rade** [comment]
Possible fix: `Peers` could invoke the `OnGC` callbacks when the UID of a peer changes.

**Comment by bboreham** [comment]
Another possible fix: peers could watch for incoming messages that differ from what they currently see in their own live state, and issue updates that contradict them.  These updates would have a higher version number than the incoming message, hence would dominate.

**Comment by rade** [comment]
> Another possible fix

That [doesn't work](https://github.com/weaveworks/weave/issues/2023#issuecomment-193009872)
