### ISSUE TITLE
docs say the plugin is started with a 'on-failure:3 policy' but it isn't

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1870]
http://docs.weave.works/weave/latest_release/plugin.html - see "Restarting" section at the end.

I don't know whether the docs or code are wrong.

**Comment by bboreham** [comment]
The docs give the right info at the top. `--on-failure:3` was tried but doesn't restart on reboot so no good for this purpose.

**Comment by rade** [comment]
Right, that's what I thought. So this is a docs bug then. Though we should probably file an issue for the lack of error reporting / failure status on plugin launch.

**Comment by bboreham** [comment]
You mean like "the weave container has died"?

#1814 was a step on that path.

**Comment by rade** [comment]
> You mean like "the weave container has died"?

Yes.

**Comment by bboreham** [comment]
Fixed in 9a4adccec64d31bd7b1ed218cb275449d1a3478a

**Comment by bboreham** [comment]
> we should probably file an issue for the lack of error reporting / failure status on plugin launch.

#1873
