### ISSUE TITLE
conflict subnet range when 'weave launch'

### ISSUE THREAD

**Issue by novice79** [weaveworks/weave#1871]
I try weave on Aliyun ubuntu14.04 server, when exec 'weave launch' I got:
Unable to find image 'weaveworks/weave:1.4.1' locally
1.4.1: Pulling from weaveworks/weave
9169fcce814f: Pulling fs layer
125d612ff28d: Pulling fs layer
6cb65287d390: Pulling fs layer
8b05dbda47f6: Pulling fs layer
ba2ba7a02d38: Pulling fs layer
9169fcce814f: Verifying Checksum
9169fcce814f: Download complete
9169fcce814f: Pull complete
ba2ba7a02d38: Verifying Checksum
ba2ba7a02d38: Download complete
6cb65287d390: Verifying Checksum
6cb65287d390: Download complete
8b05dbda47f6: Verifying Checksum
8b05dbda47f6: Download complete
125d612ff28d: Verifying Checksum
125d612ff28d: Download complete
125d612ff28d: Pull complete
6cb65287d390: Pull complete
8b05dbda47f6: Pull complete
ba2ba7a02d38: Pull complete
Digest: sha256:1d16f94e97c3b21cf9ceeb42c2acbc8201c680ceb244f3429d82cde68c0e4be3
Status: Downloaded newer image for weaveworks/weave:1.4.1
Network 10.32.0.0/12 overlaps with existing route 10.0.0.0/8 on host.
ERROR: Default --ipalloc-range 10.32.0.0/12 overlaps with existing route on host.
You must pick another range and set it on all hosts.
root@iZ94txhw7wwZ:~# ifconfig
datapath  Link encap:Ethernet  HWaddr 22:7e:4e:8b:9c:c6  
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker0   Link encap:Ethernet  HWaddr 02:42:e1:21:f7:a8  
          inet addr:192.168.0.1  Bcast:0.0.0.0  Mask:255.255.240.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:1924 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1682 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:291740 (291.7 KB)  TX bytes:1230072 (1.2 MB)

eth0      Link encap:Ethernet  HWaddr 00:16:3e:00:18:7d  
          inet addr:10.170.112.155  Bcast:10.170.119.255  Mask:255.255.248.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:16574207 errors:0 dropped:0 overruns:0 frame:0
          TX packets:82098 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:786128337 (786.1 MB)  TX bytes:6551888 (6.5 MB)

my question is how to pickup another range like 172.x.x.x, and so other weave peer launch cmd affected?

**Comment by rade** [comment]
See [the docs](http://docs.weave.works/weave/latest_release/ipam.html#range).

**Comment by bboreham** [comment]
See also #1872, where we try to explain a bit more.  Interested in your feedback @novice79.
