### ISSUE TITLE
[Docs: http://weave.works/] Links at bottom of the page of Weave Run are incorrect...

### ISSUE THREAD

**Issue by v1k0d3n** [weaveworks/weave#1887]
@bboreham; looking at some more docs from the main website, and wanted to let you know about a discrepancy I'm seeing; no rush, just making you aware.

If you navigate to the following url (Weave Run): http://www.weave.works/products/weave-run/

...and then click on the links towards the very bottom left of the page:
  - Documentation: 
  - Guides: 
  - DockerHub: 
  - GitHub: 

They all circle back to the same page: http://www.weave.works/products/weave-run/

I'm assuming you guys want them to go to the following:
  - Documentation: http://www.weave.works/docs/
  - Guides: http://www.weave.works/guides/
  - DockerHub: https://hub.docker.com/u/weaveworks/
  - GitHub: https://github.com/weaveworks/weave

Just wanted to make you all aware....that's all.

**Comment by rade** [comment]
Thanks for reporting this. We've just switched our web site to a new platform, which has broken a few things. We shall get them fixed asap.

**Comment by rade** [comment]
Fixed.
