### ISSUE TITLE
Why does `make` try to build tools/runner?

### ISSUE THREAD

**Issue by dpw** [weaveworks/weave#1893]
With #1861, it is almost possible to checkout weaveworks/weave in an arbitrary location (i.e. not under your GOPATH) and do `make`.

Almost, but not quite, because it fails while doing `make -C tools/runner`.  But it's not obvious to me why the `all` target needs to do that anyway (if one considers the point of the default target to be to satisfy the instructions in `site/building.md`).  `tools/runner` looks like something for circleci, and surely circleci can invoke make with some other target to get what it needs?

If I remove `$(RUNNER_EXE)` as a dependency of `all`, then a build succeeds when not under GOPATH.

**Comment by dpw** [comment]
CC @tomwilkie

**Comment by tomwilkie** [comment]
Yup we can remove that, but we we surely get complaints for people who try to run the tests manually (@rade).  I could add it to the run-smoketests target?

**Comment by rade** [comment]
>  I could add it to the run-smoketests target?

Fine, but I don't normally run that; I tend to run `./setup.sh` and individual or groups of tests manually. So perhaps also add a pseudo-target for building all that is required to run the smoketests, so I get something more memorable than `make tools/runner/runner`.

**Comment by awh** [comment]
> So perhaps also add a pseudo-target for building all that is required to run the smoketests

And make `run-smoketests` depend on that, as I frequently use `make all tests run-smoketests`.

**Comment by rade** [comment]
> And make `run-smoketests` depend on that

Exactly. that was the idea.
