### ISSUE TITLE
(weave panic) attempt to create negative fragment due to MTU of 8 (!)

### ISSUE THREAD

**Issue by kawaja** [weaveworks/weave#1905]
I'll start by saying that this is a play environment which I haven't really got working yet and there's probably lots wrong with it - so I understand if this report doesn't go far.

Having said that, I did experience a weave panic (go crash) so I didn't want to just ignore it.

I have five VMs in a weave network.  Four of them are at home (`cfmaster`, `d01`, `d02`, `d03`) and one of them is in AWS (`awsd01`) on the other side of the planet.  The VMs at home are behind a single public IP address, and they're all trying to build tunnels to the AWS VM through my home router NAT (my first potential problem).  All are ephemeral (they get destroyed and recreated fairly often).

At the AWS end, I start weave with this command line (it's actually via a `systemd` unit, but this is the command that gets run):

    weave launch --no-discovery --ipalloc-default-subnet=10.119.38.0/23 --ipalloc-range=10.119.38.0/24 --init-peer-count 5

I use `--no-discovery` so the AWS VM doesn't try to connect back to the VMs at home (since they can't get through the firewall/NAT).  I allocate manually out of the range `10.119.39.0/24`.  The VMs at home use the same command line without `--no-discovery`.

Other info (AWS VM):

    core@awsd01 ~ $ weave version
    weave script 1.4.2
    weave router 1.4.2
    weave proxy  1.4.2
    weave plugin 1.4.2

    core@awsd01 ~ $ cat /etc/lsb-release 
    DISTRIB_ID=CoreOS
    DISTRIB_RELEASE=899.3.0
    DISTRIB_CODENAME="Red Dog"
    DISTRIB_DESCRIPTION="CoreOS 899.3.0"

    core@awsd01 ~ $ weave status

            Version: 1.4.2

            Service: router
           Protocol: weave 1..2
               Name: e2:15:25:1d:a8:ef(awsd01)
         Encryption: enabled
      PeerDiscovery: disabled
            Targets: 0
        Connections: 4 (3 established, 1 pending)
              Peers: 5 (with 18 established, 2 pending connections)
     TrustedSubnets: none

            Service: ipam
             Status: ready
              Range: 10.119.38.0-10.119.38.255
      DefaultSubnet: 10.119.38.0/23

            Service: dns
             Domain: weave.local.
           Upstream: 172.31.0.2
                TTL: 1
            Entries: 18

            Service: proxy
            Address: unix:///var/run/weave/weave.sock

            Service: plugin
         DriverName: weave

    core@awsd01 ~ $ weave status connections
    <- 120.148.66.159:45572  established encrypted   sleeve 5a:37:f6:3d:1b:24(cfmaster)
    <- 120.148.66.159:43178  pending     encrypted   sleeve e6:1f:2a:3f:3c:1c(d01)
    <- 120.148.66.159:47280  established encrypted   sleeve ae:47:4c:52:fa:09(d02)
    <- 120.148.66.159:44790  established encrypted   sleeve 3e:83:f0:18:2a:b3(d03)

The logs show some difficulty with what I assume is the NAT at my home router (I've replaced my home IP address with `REM.OTE.IPA.DDR` and it looks like `d02` was down at the time of this snippet):

    Jan 16 16:33:13 awsd01 docker[1560]: INFO: 2016/01/16 16:33:13.120724 Discovered remote MAC ae:9e:80:08:35:18 at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:15 awsd01 docker[1560]: INFO: 2016/01/16 16:33:15.748704 Discovered remote MAC da:62:85:93:1d:3c at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:16 awsd01 docker[1560]: INFO: 2016/01/16 16:33:16.787019 Discovered remote MAC 76:ca:e3:f4:b2:1b at ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:23 awsd01 docker[1560]: INFO: 2016/01/16 16:33:23.561916 Discovered remote MAC a6:4c:d4:ca:50:08 at ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:24 awsd01 docker[1560]: INFO: 2016/01/16 16:33:24.916184 Discovered remote MAC 4a:13:c5:15:28:14 at ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:25 awsd01 docker[1560]: INFO: 2016/01/16 16:33:25.588220 Discovered remote MAC ce:12:2d:a0:0f:d2 at ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:27 awsd01 docker[1560]: INFO: 2016/01/16 16:33:27.838520 Discovered remote MAC da:b3:b5:d5:76:4b at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:28 awsd01 docker[1560]: INFO: 2016/01/16 16:33:28.136157 overlay_switch ->[92:8b:88:d5:6d:eb(d03)] sleeve timed out waiting for UDP heartbeat
    Jan 16 16:33:28 awsd01 docker[1560]: ERRO: 2016/01/16 16:33:28.136295 ->[REM.OTE.IPA.DDR:42950|92:8b:88:d5:6d:eb(d03)]: connection shutting down due to error: no working forwarders to 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:28 awsd01 docker[1560]: INFO: 2016/01/16 16:33:28.136467 ->[REM.OTE.IPA.DDR:42950|92:8b:88:d5:6d:eb(d03)]: connection deleted
    Jan 16 16:33:28 awsd01 docker[1560]: INFO: 2016/01/16 16:33:28.612206 ->[REM.OTE.IPA.DDR:43476] connection accepted
    Jan 16 16:33:28 awsd01 docker[1560]: INFO: 2016/01/16 16:33:28.704592 Discovered remote MAC 92:0d:aa:7a:35:db at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:28 awsd01 docker[1560]: INFO: 2016/01/16 16:33:28.847148 ->[REM.OTE.IPA.DDR:43476|92:8b:88:d5:6d:eb(d03)]: connection ready; using protocol version 2
    Jan 16 16:33:28 awsd01 docker[1560]: INFO: 2016/01/16 16:33:28.847268 overlay_switch ->[92:8b:88:d5:6d:eb(d03)] using sleeve
    Jan 16 16:33:28 awsd01 docker[1560]: INFO: 2016/01/16 16:33:28.847334 ->[REM.OTE.IPA.DDR:43476|92:8b:88:d5:6d:eb(d03)]: connection added
    Jan 16 16:33:34 awsd01 docker[1560]: INFO: 2016/01/16 16:33:34.601317 overlay_switch ->[42:63:e3:98:36:a8(cfmaster)] sleeve timed out waiting for UDP heartbeat
    Jan 16 16:33:34 awsd01 docker[1560]: ERRO: 2016/01/16 16:33:34.601452 ->[REM.OTE.IPA.DDR:59554|42:63:e3:98:36:a8(cfmaster)]: connection shutting down due to error: no working forwarders to 42:63:e3:98:36:a8(cfmaster)
    Jan 16 16:33:34 awsd01 docker[1560]: INFO: 2016/01/16 16:33:34.601623 ->[REM.OTE.IPA.DDR:59554|42:63:e3:98:36:a8(cfmaster)]: connection deleted
    Jan 16 16:33:35 awsd01 docker[1560]: INFO: 2016/01/16 16:33:35.071689 ->[REM.OTE.IPA.DDR:59848] connection accepted
    Jan 16 16:33:35 awsd01 docker[1560]: INFO: 2016/01/16 16:33:35.307816 ->[REM.OTE.IPA.DDR:59848|42:63:e3:98:36:a8(cfmaster)]: connection ready; using protocol version 2
    Jan 16 16:33:35 awsd01 docker[1560]: INFO: 2016/01/16 16:33:35.307898 overlay_switch ->[42:63:e3:98:36:a8(cfmaster)] using sleeve
    Jan 16 16:33:35 awsd01 docker[1560]: INFO: 2016/01/16 16:33:35.307940 ->[REM.OTE.IPA.DDR:59848|42:63:e3:98:36:a8(cfmaster)]: connection added
    Jan 16 16:33:37 awsd01 docker[1560]: INFO: 2016/01/16 16:33:37.178006 Discovered remote MAC b2:07:f2:89:40:e7 at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:38 awsd01 docker[1560]: INFO: 2016/01/16 16:33:38.208089 Discovered remote MAC 42:63:e3:98:36:a8 at 42:63:e3:98:36:a8(cfmaster)
    Jan 16 16:33:38 awsd01 docker[1560]: INFO: 2016/01/16 16:33:38.706275 Discovered remote MAC 1a:36:62:53:79:e5 at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:39 awsd01 docker[1560]: INFO: 2016/01/16 16:33:39.854634 Discovered remote MAC 5a:0e:85:40:66:dd at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:42 awsd01 docker[1560]: INFO: 2016/01/16 16:33:42.118129 overlay_switch ->[ae:6f:42:04:45:2e(d01)] sleeve timed out waiting for UDP heartbeat
    Jan 16 16:33:42 awsd01 docker[1560]: ERRO: 2016/01/16 16:33:42.118206 ->[REM.OTE.IPA.DDR:51928|ae:6f:42:04:45:2e(d01)]: connection shutting down due to error: no working forwarders to ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:42 awsd01 docker[1560]: INFO: 2016/01/16 16:33:42.118276 ->[REM.OTE.IPA.DDR:51928|ae:6f:42:04:45:2e(d01)]: connection deleted
    Jan 16 16:33:42 awsd01 docker[1560]: INFO: 2016/01/16 16:33:42.599067 ->[REM.OTE.IPA.DDR:52342] connection accepted
    Jan 16 16:33:42 awsd01 docker[1560]: INFO: 2016/01/16 16:33:42.835480 ->[REM.OTE.IPA.DDR:52342|ae:6f:42:04:45:2e(d01)]: connection ready; using protocol version 2
    Jan 16 16:33:42 awsd01 docker[1560]: INFO: 2016/01/16 16:33:42.835618 overlay_switch ->[ae:6f:42:04:45:2e(d01)] using sleeve
    Jan 16 16:33:42 awsd01 docker[1560]: INFO: 2016/01/16 16:33:42.835674 ->[REM.OTE.IPA.DDR:52342|ae:6f:42:04:45:2e(d01)]: connection added
    Jan 16 16:33:43 awsd01 docker[1560]: INFO: 2016/01/16 16:33:43.772785 Discovered remote MAC 1a:c3:1e:7b:94:44 at ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:44 awsd01 docker[1560]: INFO: 2016/01/16 16:33:44.576684 Discovered remote MAC 9e:41:f8:3f:e6:00 at 92:8b:88:d5:6d:eb(d03)
    Jan 16 16:33:52 awsd01 docker[1560]: INFO: 2016/01/16 16:33:52.946988 Discovered remote MAC d6:71:80:18:6f:1a at ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:53 awsd01 docker[1560]: INFO: 2016/01/16 16:33:53.650959 Discovered remote MAC 02:3c:f5:f2:e2:ae at ae:6f:42:04:45:2e(d01)
    Jan 16 16:33:54 awsd01 docker[1560]: INFO: 2016/01/16 16:33:54.602713 Discovered remote MAC 8a:89:4f:5c:1c:a2 at ae:6f:42:04:45:2e(d01)

Despite this, I do get traffic over this link most of the time, I assume because all the heartbeat-fails don't happen at the same time.

Now, here's the panic:

    Jan 17 07:32:43 awsd01 docker[2700]: INFO: 2016/01/17 07:32:43.950443 overlay_switch ->[5a:37:f6:3d:1b:24(cfmaster)] using sleeve
    Jan 17 07:32:43 awsd01 docker[2700]: INFO: 2016/01/17 07:32:43.950504 ->[REM.OTE.IPA.DDR:59530|5a:37:f6:3d:1b:24(cfmaster)]: connection added
    Jan 17 07:33:03 awsd01 docker[2700]: INFO: 2016/01/17 07:33:03.742423 ->[REM.OTE.IPA.DDR:59530|5a:37:f6:3d:1b:24(cfmaster)]: connection fully established
    Jan 17 07:33:03 awsd01 docker[2700]: INFO: 2016/01/17 07:33:03.783122 EMSGSIZE on send, expecting PMTU update (IP packet was 60052 bytes, payload was 60044 bytes)
    Jan 17 07:33:03 awsd01 docker[2700]: INFO: 2016/01/17 07:33:03.799297 EMSGSIZE on send, expecting PMTU update (IP packet was 8981 bytes, payload was 8973 bytes)
    Jan 17 07:33:25 awsd01 docker[2700]: INFO: 2016/01/17 07:33:25.332424 overlay_switch ->[e6:1f:2a:3f:3c:1c(d01)] sleeve timed out waiting for UDP heartbeat
    Jan 17 07:33:25 awsd01 docker[2700]: ERRO: 2016/01/17 07:33:25.332585 ->[REM.OTE.IPA.DDR:35776|e6:1f:2a:3f:3c:1c(d01)]: connection shutting down due to error: no working forwarders to e6:1f:2a:3f:3c:1c(d01)
    Jan 17 07:33:25 awsd01 docker[2700]: INFO: 2016/01/17 07:33:25.332804 ->[REM.OTE.IPA.DDR:35776|e6:1f:2a:3f:3c:1c(d01)]: connection deleted
    Jan 17 07:33:25 awsd01 docker[2700]: INFO: 2016/01/17 07:33:25.822053 ->[REM.OTE.IPA.DDR:35988] connection accepted
    Jan 17 07:33:26 awsd01 docker[2700]: INFO: 2016/01/17 07:33:26.073063 ->[REM.OTE.IPA.DDR:35988|e6:1f:2a:3f:3c:1c(d01)]: connection ready; using protocol version 2
    Jan 17 07:33:26 awsd01 docker[2700]: INFO: 2016/01/17 07:33:26.073167 overlay_switch ->[e6:1f:2a:3f:3c:1c(d01)] using sleeve
    Jan 17 07:33:26 awsd01 docker[2700]: INFO: 2016/01/17 07:33:26.073204 ->[REM.OTE.IPA.DDR:35988|e6:1f:2a:3f:3c:1c(d01)]: connection added
    Jan 17 07:33:31 awsd01 docker[2700]: INFO: 2016/01/17 07:33:31.860985 sleeve ->[REM.OTE.IPA.DDR:6783|5a:37:f6:3d:1b:24(cfmaster)]: Effective MTU verified at 8
    Jan 17 07:33:32 awsd01 docker[2700]: INFO: 2016/01/17 07:33:32.725748 Sending ICMP 3,4 (10.119.38.86 -> 10.119.38.129): PMTU=8
    Jan 17 07:33:57 awsd01 docker[2700]: panic: runtime error: slice bounds out of range
    Jan 17 07:33:57 awsd01 docker[2700]: goroutine 21 [running]:
    Jan 17 07:33:57 awsd01 docker[2700]: github.com/weaveworks/weave/router.fragment(0x7fa1e4000d60, 0xe, 0x14a, 0x7fa1e4000d6e, 0x13c, 0x13c, 0x7fa1e4000d66, 0x6, 0x144, 0x7fa1e4000d60, ...)
    Jan 17 07:33:57 awsd01 docker[2700]: /home/vagrant/src/github.com/weaveworks/weave/router/sleeve.go:573 +0x6d9
    Jan 17 07:33:57 awsd01 docker[2700]: github.com/weaveworks/weave/router.curriedForward.Process(0xc209186dc0, 0xc208062720, 0xc2092c0b40, 0xffff9ff4f83cba3e, 0xffffffff, 0xc20a223760, 0x14a, 0x14a, 0xc20912e000, 0x1)
    Jan 17 07:33:57 awsd01 docker[2700]: /home/vagrant/src/github.com/weaveworks/weave/router/sleeve.go:527 +0xb48
    Jan 17 07:33:57 awsd01 docker[2700]: github.com/weaveworks/weave/router.(*curriedForward).Process(0xc20a19b7a0, 0xc20a223760, 0x14a, 0x14a, 0xc20912e000, 0xc209183b01)
    Jan 17 07:33:57 awsd01 docker[2700]: <autogenerated>:264 +0xd4
    Jan 17 07:33:57 awsd01 docker[2700]: github.com/weaveworks/weave/router.(*MultiFlowOp).Process(0xc209f7c600, 0xc20a223760, 0x14a, 0x14a, 0xc20912e000, 0x100)
    Jan 17 07:33:57 awsd01 docker[2700]: /home/vagrant/src/github.com/weaveworks/weave/router/flow.go:73 +0xdf
    Jan 17 07:33:57 awsd01 docker[2700]: github.com/weaveworks/weave/router.(*Pcap).sniff(0xc2090b0450, 0xc2090ab780, 0xc2090f6ac0)
    Jan 17 07:33:57 awsd01 docker[2700]: /home/vagrant/src/github.com/weaveworks/weave/router/pcap.go:145 +0x3f8
    Jan 17 07:33:57 awsd01 docker[2700]: created by github.com/weaveworks/weave/router.(*Pcap).StartConsumingPackets
    Jan 17 07:33:57 awsd01 docker[2700]: /home/vagrant/src/github.com/weaveworks/weave/router/pcap.go:64 +0x215
    Jan 17 07:33:57 awsd01 docker[2700]: goroutine 1 [chan receive, 321 minutes]:
    Jan 17 07:33:57 awsd01 docker[2700]: github.com/weaveworks/weave/common.SignalHandlerLoop(0xc209553db0, 0x1, 0x1)
    Jan 17 07:33:57 awsd01 docker[2700]: /home/vagrant/src/github.com/weaveworks/weave/common/signals.go:20 +0x2a4
    Jan 17 07:33:57 awsd01 docker[2700]: main.main()
    Jan 17 07:33:57 awsd01 docker[2700]: /home/vagrant/src/github.com/weaveworks/weave/releases/v1.4.2/prog/weaver/main.go:330 +0x4039

Line 573 in `sleeve.go` is trying to build a fragment and I assume it's attempting a negative index due to the `mtu` being set to 8.

I've captured two full traces of the crash and there's a few other places where the `Effective MTU verified at 8` comes up, but it looks like the UDP heartbeat takes out the connection before a packet send is attempted.

The only other useful piece of information I can think of at the moment is that my home link was saturated at the time - I was uploading files into S3.

Perhaps similar fix to #1107?

I've attached the full weave log at
[weave-log.txt](https://github.com/weaveworks/weave/files/93332/weave-log.txt)

**Comment by dpw** [comment]
Thanks. This does indeed seem like a bug.

> Line 573 in sleeve.go is trying to build a fragment and I assume it's attempting a negative index due to the mtu being set to 8.

Seems so.

In fact, the minimum IPv4 MTU is 68 bytes, while the maximum header length is 60 bytes.  If we implement those constraints properly, this case should never happen.

> I've captured two full traces of the crash and there's a few other places where the Effective MTU verified at 8 comes up, but it looks like the UDP heartbeat takes out the connection before a packet send is attempted.

It looks like, in the search for a working MTU, the code tries lower and lower values until it decides that 8 byte works.  But that's below the IPv4 minimum MTU of 68.  We should probably initialize `mtuHighestGood` to 68,  not 8. (And perhaps 68 is still lower than necessary.  IIRC, Linux uses a value of 576.  And https://tools.ietf.org/html/rfc4821#page-16 suggests 1024.)

But that will make weave more robust, rather than fixing the problem in your environment. It would take more investigation to figure out what the underlying problem led to such a low "MTU".  If you can reproduce it, what does `traceroute --mtu` produce for the relevant path?
 
> The only other useful piece of information I can think of at the moment is that my home link was saturated at the time - I was uploading files into S3.

It's possible that a very high rate of packet loss could cause the problem, but it seems unlikely.  More likely, it's due to a static condition of your network environment at the time.

**Comment by bboreham** [comment]
#1107 found that Linux' minimum is 552

**Comment by rade** [comment]
steps to reproduce:
```
host1$ sudo iptables -I INPUT -p udp --destination-port 6784 -j DROP
host1$ sudo iptables -I INPUT -p udp --destination-port 6783 -m length '!' --length 0:70 -j DROP
host1$ weave launch
host2$ weave launch $HOST1
host2$ docker logs -f weave |& grep "Effective MTU"
[wait for "Effective MTU verified at 8"]
host2$ weave run --name=mcast -ti bboreham/mcast /home/mcsend 224.0.0.1 2233
1d28c1018198586437821a59cd9d2d556eb1d60caf3f605d0fd59fbbdbffde70
host2:~$ docker attach mcast
foo
[weave on host2 is now dead]
```

Ordinary communication, e.g. using ping or nc, starts with an ARP, which doesn't go through the exploding code path, and since it won't succeed we never hit that. However, multicast 
doesn't require a successful ARP, which is why we are using that above.
