### ISSUE TITLE
document FDP in "How it Works"

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#1908]
There is no mention of FDP in [`how-it-works.md`](https://github.com/weaveworks/weave/blob/master/site/how-it-works.md#encapsulation).

**Comment by awh** [comment]
Thanks @errordeveloper. There is `docs/fastdp.md`, but that's more internal maintainer documentation...

**Comment by rade** [comment]
Let's please keep this issue focused. -> changing summary.

**Comment by rade** [comment]
Let's just take `docs/fastdp.md` and incorporate/reference that in how-it-works. And then iterate on that.

**Comment by abuehrle** [comment]
I have added a couple of topics for this:  
What is fast data path?  
Configuring fast data path
Encryption and fast data path.  

The 'parent topic' is called Configuring Network Performance with Fast Datapath.  I would like to make this its own section. 

See the content outline, which I won't publish here.
