### ISSUE TITLE
Running weave controller in a VM

### ISSUE THREAD

**Issue by davedoesdev** [weaveworks/weave#1923]
How much work would it be to make the weave controller run in a VM rather than a container?

**Comment by DanielDent** [comment]
I'm curious what changes you see being made with this request. Couldn't you already run weave in a container in a VM?

**Comment by davedoesdev** [comment]
I'd like to try running it on [rumprun](https://github.com/rumpkernel/rumprun).

**Comment by DanielDent** [comment]
Interesting! I'm not a developer on weave, merely a user that has now spent some time working with it.

My suspicion is that it would take quite a lot of work. Taking the weave router and/or weave proxy applications and running them on rumprun is probably relatively straightforward, although I'm not familiar with their internals, so I might be wrong there. But that wouldn't actually be the hard part in my view.

The hard part would be that weave assumes a linux userland and kernel. It manipulates lots of kernel parameters. It interacts with iptables, sets up bridges, deals with ARP, etc. The fast datapath would likely also require rethinking. Basically, all the stuff that is in the "weave" shell script would need to be ported. And that's actually quite a lot.

**Comment by tomwilkie** [comment]
I'm not aware of any serious Golang unikernel projects, best I could find is:

https://www.reddit.com/r/golang/comments/2w2f67/what_does_the_future_look_like_for_golang/

@avsm might know of some.  I'm sure thats something he'll be working on soon, given the recent Docker news.

**Comment by davedoesdev** [comment]
https://github.com/deferpanic/gorump

**Comment by tomwilkie** [comment]
Nice, I wasn't aware of that.  Have you tried compiling weave using it?

**Comment by dpw** [comment]
> I'd like to try running it on rumprun.

Do you have some particular benefit in mind from doing this?

> The hard part would be that weave assumes a linux userland and kernel. It manipulates lots of kernel parameters. It interacts with iptables, sets up bridges, deals with ARP, etc. The fast datapath would likely also require rethinking. Basically, all the stuff that is in the "weave" shell script would need to be ported. And that's actually quite a lot.

Again, it all depends what outcome you have in mind.

The relationship of the weave router to containers has two aspects:

First, weave net delivers an overlay network for containers.  To a first approximation, the router provides the "overlay network" part, but the weave script does the "for containers" part.  That involves persuading the network stack of the kernel hosting the containers to behave as we want.  So the weave script cannot be run in a VM, the whole point of it is to integrate with the kernel acting as a container host.  But maybe you aren't interested in the "for containers" part, and want weave's overlay network for some other purpose.  In which case, you might not need the weave script at all.

Secondly, the weave router is packaged into a container image.  This is largely incidental: We are targeting scenarios featuring docker, we have to package the router somehow, so it is natural to package it as a docker image.  There's nothing stopping you running the weaver binary on the host, except that if you want to get something useful from doing that (even just the equivalent of "weave expose") you'll need to replicate some of the functionality of the weave script.

**Comment by davedoesdev** [comment]
@dpw just playing around. I guess not having to run the Docker daemon is a positive.

Thanks for the info, it sounds promising. I was going to try to use [fold](https://github.com/davedoesdev/fold) (or some modification) to do the script part.

**Comment by davedoesdev** [comment]
This is going to be tricky without netlink (on rumprun/netbsd)! Think I might look for an alternative.

**Comment by davedoesdev** [comment]
Will probably just run weave router on host
