### ISSUE TITLE
CPU utilization & network performance debugging

### ISSUE THREAD

**Issue by DanielDent** [weaveworks/weave#1925]
I ran iperf twice on the same two hosts. The first time for a minute, the second time only for 20 seconds (I didn't want to max out the network for too long)

When I ran this over the weave IP, I got 50-60% CPU utilization on each host. You mentioned seeing much lower CPU utilization in your own tests - have you tried traffic with a higher PPS? My real world traffic in this test network is lots of small packets. Ping with a 64 kilobyte packet size is not going to reflect that.

+------------------------------------------------------------
Client connecting to XXXX.weave.local, TCP port 5001
TCP window size: 45.0 KByte (default)
+------------------------------------------------------------
[  3] local 10.x.x.x port 43337 connected with 10.x.x.x port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-60.0 sec   300 MBytes  41.9 Mbits/sec

For comparison's sake, I ran iperf again over the public IP. I ran a shorter test because I didn't see the need to use 400 megabits/second of internet bandwidth for an extended period of time. On this test iperf was actually using about 15% CPU on one of the hosts.
+------------------------------------------------------------
Client connecting to PUBLICIP, TCP port 5001
TCP window size: 85.0 KByte (default)
+------------------------------------------------------------
[  3] local PUBLICIP port 38249 connected with PUBLICIP port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-20.0 sec   980 MBytes   410 Mbits/sec

Next I'll look at getting some debug logs for you.

**Comment by rade** [comment]
> 41.9 Mbits/sec

That is roughly in line with what we'd expect to see with crypto and no fastdp. And you are getting that at 50-60% CPU utilisation. These figures are a lot better than what you [reported previously](https://github.com/weaveworks/weave/issues/1644#issuecomment-174346752).

**Comment by DanielDent** [comment]
iperf with a nice big TCP flow is kind to weave. My test cluster is where I was seeing that.

Here's a test I found which illustrates the issue. It looks like where weave's performance breaks down is when it has to handle lots of packets:
iperf -b 3M -l 64 -u -c 10.32.0.1 -t 30 
WARNING: option -b implies udp testing
WARNING: option -b is not valid for server mode
------------------------------------------------------------
Client connecting to 10.32.0.1, UDP port 5001
Sending 64 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 10.40.0.0 port 37250 connected with 10.32.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-30.0 sec  3.75 MBytes  1.05 Mbits/sec
[  3] Sent 61477 datagrams
[  3] Server Report:
[  3]  0.0-30.0 sec  3.75 MBytes  1.05 Mbits/sec   0.084 ms    0/61476 (0%)
[  3]  0.0-30.0 sec  1 datagrams received out-of-order

Running that was using about 30% CPU on the sending side and 20% on the receiving side.

**Comment by DanielDent** [comment]
Also, I think it's worth pointing out: In the first test I did, not using weave was literally 10x the performance, under less favourable test conditions (a longer test when using TCP is a more favourable test - it provides time for TCP windows to grow).

**Comment by DanielDent** [comment]
Attached a debug log for starting weave on a fresh machine, and running the above test. Again, 30% CPU with about 1 megabit/second of traffic (64 byte packets).
[iperf-weave.log.gz](https://github.com/weaveworks/weave/files/103158/iperf-weave.log.gz)

**Comment by rade** [comment]
How high can you push the bandwidth before seeing significant packet loss?

**Comment by DanielDent** [comment]
Clearly packets as small as below are a degenerate case, but I do think they do provide a hint that this is about packets per second. The higher I make the packet size, the better performance gets.

70-80% CPU, 37% packet loss:
iperf -c 10.32.0.1 -b 2000000 -l 1 -u  -t 10
WARNING: option -b implies udp testing
WARNING: the UDP buffer was increased to 12 for proper operation
WARNING: option -l has implied compatibility mode
+------------------------------------------------------------
Client connecting to 10.32.0.1, UDP port 5001
Sending 12 byte datagrams
UDP buffer size:  208 KByte (default)
+------------------------------------------------------------
[  3] local 10.40.0.0 port 46682 connected with 10.32.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  2.38 MBytes  2.00 Mbits/sec
[  3] Sent 208309 datagrams

60-80% CPU, 17% packet loss:
iperf -c 10.32.0.1 -b 1500000 -l 1 -u  -t 10
WARNING: option -b implies udp testing
WARNING: the UDP buffer was increased to 12 for proper operation
WARNING: option -l has implied compatibility mode
+------------------------------------------------------------
Client connecting to 10.32.0.1, UDP port 5001
Sending 12 byte datagrams
UDP buffer size:  208 KByte (default)
+------------------------------------------------------------
[  3] local 10.40.0.0 port 54181 connected with 10.32.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.79 MBytes  1.50 Mbits/sec
[  3] Sent 156231 datagrams

50-70% CPU, 4.3% packet loss:
iperf -c 10.32.0.1 -b 1000000 -l 1 -u  -t 10
WARNING: option -b implies udp testing
WARNING: the UDP buffer was increased to 12 for proper operation
WARNING: option -l has implied compatibility mode
+------------------------------------------------------------
Client connecting to 10.32.0.1, UDP port 5001
Sending 12 byte datagrams
UDP buffer size:  208 KByte (default)
+------------------------------------------------------------
[  3] local 10.40.0.0 port 60431 connected with 10.32.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.19 MBytes  1000 Kbits/sec
[  3] Sent 104165 datagrams

40% CPU, 1.1% packet loss:
iperf -c 10.32.0.1 -b 500000 -l 1 -u  -t 10
WARNING: option -b implies udp testing
WARNING: the UDP buffer was increased to 12 for proper operation
WARNING: option -l has implied compatibility mode
+------------------------------------------------------------
Client connecting to 10.32.0.1, UDP port 5001
Sending 12 byte datagrams
UDP buffer size:  208 KByte (default)
+------------------------------------------------------------
[  3] local 10.40.0.0 port 52572 connected with 10.32.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   610 KBytes   500 Kbits/sec
[  3] Sent 52084 datagrams

20% CPU, 0% packet loss:
iperf -c 10.32.0.1 -b 250000 -l 1 -u  -t 10
WARNING: option -b implies udp testing
WARNING: the UDP buffer was increased to 12 for proper operation
WARNING: option -l has implied compatibility mode
+------------------------------------------------------------
Client connecting to 10.32.0.1, UDP port 5001
Sending 12 byte datagrams
UDP buffer size:  208 KByte (default)
+------------------------------------------------------------
[  3] local 10.40.0.0 port 49873 connected with 10.32.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   305 KBytes   250 Kbits/sec
[  3] Sent 26043 datagrams

**Comment by bboreham** [comment]
I have mostly duplicated this; I used the container https://hub.docker.com/r/moutten/iperf/ .

I confirm a rise in CPU usage as the packets get very small, although I got better packet-drop rates.  almost all of the CPU usage is system CPU, i.e. likely the overheads of kernel-to-userspace traversal involved in the "sleeve" transport. See #51 for detailed discussion of some of these overheads.

We can even curve-fit the figures to derive an approximate 80μs cost per packet; when the total cost goes above 100% of a CPU it starts dropping packets. 

My test run:

````
$ docker run  -it --rm --net=weave moutten/iperf -c 10.40.0.0 -b 2000000 -l 1 -u -t 10
WARNING: option -b implies udp testing
WARNING: the UDP buffer was increased to 12 for proper operation
WARNING: option -l has implied compatibility mode
------------------------------------------------------------
Client connecting to 10.40.0.0, UDP port 5001
Sending 12 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local 10.32.0.1 port 43808 connected with 10.40.0.0 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  2.33 MBytes  1.96 Mbits/sec
[  3] Sent 203900 datagrams
````

on the server:

    [  4]  0.0-10.0 sec  2.20 MBytes  1.84 Mbits/sec   0.034 ms 11918/203899 (5.8%)

**Comment by bboreham** [comment]
Interestingly, Weave performs much better on these tests if you set `WEAVE_NO_FASTDP`.  I can get it up above 5Mbit/sec before packet loss hits 5%.  Conclusion: pcap is much more efficient than the ODP-based mechanism used when we support mixed FDP/encrypted paths.

**Comment by rade** [comment]
I don't see how we can get significant performance improvements here w/o #1644. -> closing
