### ISSUE TITLE
Misleading error on second router launch on kernels with no ODP support

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#1929]
The first time you launch the router without specifying `WEAVE_NO_FASTDP` on such a kernel `create_bridge` silently falls back to creating a default bridge netdev for use with PCAP. On the second launch, the following error is received due to the extant bridge:
```
WEAVE_NO_FASTDP is not set, but there is already a bridge present of
the wrong type for fast datapath.  Please do 'weave reset' to remove
the bridge first.
```
This is confusing, because the first launch works without specifying `WEAVE_NO_FASTDP`. The initial launch should probably fail with a recommendation to try again with `WEAVE_NO_FASTDP`, so that the user knows from the outset that it needs to be supplied in future.

**Comment by rade** [comment]
> The initial launch should probably fail with a recommendation to try again with `WEAVE_NO_FASTDP`, so that the user knows from the outset that it needs to be supplied in future.

Well, ideally the 2nd launch wouldn't complain. But that's trickier.

**Comment by rade** [comment]
> Well, ideally the 2nd launch wouldn't complain. But that's trickier.

On reflection, we really should do this. The automatic fallback to sleeve when fdp isn't supported is a heavily advertised feature of weave.
