### ISSUE TITLE
Containers created after attaching weave-ip has a stale entry in output of df -h command.

### ISSUE THREAD

**Issue by djain13** [weaveworks/weave#1947]
I am using docker 1.9 and weave 1.3. After attaching weave-ip to the docker container I see a stale entry added to the containers df -h output. 
[root@bi-paygobm-prod-033 dharjain]# docker exec -it bi-hadoop-prod-4033-bi-hadoop-prod-4033 df -h
**df: `/etc/hosts (deleted)': No such file or directory**
Filesystem            Size  Used Avail Use% Mounted on
rootfs                 30G  5.8G   25G  20% /
/dev/mapper/docker-8:17-4298781828-7888b9674faaa566e011a5ea4a31327c9bf1015a4f49376af8bda9cc05d0fd41
                       30G  5.8G   25G  20% /
tmpfs                 126G     0  126G   0% /dev
tmpfs                 126G     0  126G   0% /sys/fs/cgroup
/dev/loop10           9.8G   70M  9.2G   1% /meta
/dev/loop11            99G   93M   94G   1% /log
/dev/loop12            99G   63M   94G   1% /data
/dev/sdb1             1.9T   29G  1.8T   2% /w
/dev/sdb1             1.9T   29G  1.8T   2% /etc/resolv.conf
/dev/sdb1             1.9T   29G  1.8T   2% /etc/hostname
shm                    64M     0   64M   0% /dev/shm
tmpfs                 126G     0  126G   0% /proc/kcore
tmpfs                 126G     0  126G   0% /proc/timer_stats

This stale entry is causing other scripts dependent on df -h output break.
How can I go about this?

**Comment by djain13** [comment]
Here is how I am creating containers and attaching weave-ip:
export DOCKER_HOST=unix:///var/run/weave/weave.sock ORIG_DOCKER_HOST=
docker run -it -e WEAVE_CIDR=172.16.203.6/25 --name test-data -v /opt/ibm/bluemix/rcs/:/rcs bi_v41001_data /bin/bash

**Comment by djain13** [comment]
**/usr/local/bin/weave version**
weave script 1.3.1
weave router 1.3.1
weave proxy  1.3.1

**docker version**
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

**Comment by rade** [comment]
I cannot reproduce this, using the same versions of weave (1.3.1) and docker (1.9.1):

```
$ weave launch
$ eval $(weave env)
$ docker run -dti --name=foo ubuntu
fae44911dafc593b1873c95ca2af9d75b804746d35e6eb139da6548ebb712f41
$ docker exec -it foo df -h
Filesystem                                              Size  Used Avail Use% Mounted on
overlay                                                 227G  178G   38G  83% /
tmpfs                                                   3.9G     0  3.9G   0% /dev
tmpfs                                                   3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/disk/by-uuid/f4fd51fd-3c3a-4f13-9fb8-61c33639b875  227G  178G   38G  83% /w
shm                                                      64M     0   64M   0% /dev/shm
tmpfs                                                   3.9G     0  3.9G   0% /proc/kcore
tmpfs                                                   3.9G     0  3.9G   0% /proc/timer_stats
```

Can you reproduce this with some standard images, like ubuntu or alpine?

**Comment by djain13** [comment]
I see the same error for an alpine image too. 
[root@bi-paygobm-prod-037 dharjain]# docker run -it --name test-cont alpine df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/docker-8:17-6501502242-eddf4fe069afa74abc241c5d7a8b024a57fc0421c72d6f719fa58a07c298a477
                         30.0G     37.6M     29.9G   0% /
tmpfs                   125.8G         0    125.8G   0% /dev
tmpfs                   125.8G         0    125.8G   0% /sys/fs/cgroup
/dev/sdb1                 1.8T     19.9G      1.8T   1% /w
/dev/sdb1                 1.8T     19.9G      1.8T   1% /etc/resolv.conf
/dev/sdb1                 1.8T     19.9G      1.8T   1% /etc/hostname
**df: /etc/hosts\040(deleted): No such file or directory**
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   125.8G         0    125.8G   0% /proc/kcore
tmpfs                   125.8G         0    125.8G   0% /proc/timer_stats
[root@bi-paygobm-prod-037 dharjain]#

**Comment by rade** [comment]
> /dev/mapper/

I think that is the clue. You are running with the devicemapper Docker storage driver. That is highly inefficient and full of bugs. I recommend switching to the `overlay` driver.

**Comment by rade** [comment]
I don't see this with devicemapper either:
```
$ docker run --rm -it alpine df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/docker-8:1-489540-69af31a6d6489d5161adaa8cf5333b4fa148e726a7f0de0a86049a68c88d6a5e
                          9.7G     27.5M      9.2G   0% /
tmpfs                   181.5M         0    181.5M   0% /dev
tmpfs                   181.5M         0    181.5M   0% /sys/fs/cgroup
/dev/sda1                38.8G      2.4G     36.4G   6% /w
/dev/sda1                38.8G      2.4G     36.4G   6% /etc/resolv.conf
/dev/sda1                38.8G      2.4G     36.4G   6% /etc/hostname
/dev/sda1                38.8G      2.4G     36.4G   6% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   181.5M         0    181.5M   0% /proc/kcore
tmpfs                   181.5M         0    181.5M   0% /proc/timer_stats
```
That's with weave 1.3.1 and Docker 1.10.0. So upgrading to Docker 1.10 might be another option that possibly solves the problem.
