### ISSUE TITLE
Docker - Is it possible to connect containers in the same host using weave

### ISSUE THREAD

**Issue by shyamchandranmec** [weaveworks/weave#1950]
I am trying to connect multiple containers in the same host (aws server) using weave. But the docker run command doesn't give any output if I give

    weave launch <aws-public-ip>
    eval $(weave env)

I tried this with and without docker-compose..

I tried connecting multiple containers in different hosts using virtual box in my mac. That was working perfectly.

Is this possible using weave?

I know that we can achieve it using links in docker.. But I read somewhere that links will be removed in future and networking is the preferred way

**Comment by rade** [comment]
> `weave launch <aws-public-ip>`

Why are you specifying an `<aws-public-ip>` here? That will tell weave to a) attempt to connect to that IP, looking for another weave peer, and b) require consensus with that peer for initialising the IP address allocator. In the absence of such consensus, actions that require an IP address, such as launching a container, will hang, which is probably what you are seeing.

**Comment by shyamchandranmec** [comment]
Hi @rade 
Thanks for the quick reply
So should I just do

    weave launch

and how can I refer to my containers

    containerName.weave.local  ?

**Comment by shyamchandranmec** [comment]
I tried with just 

    weave launch

and it works.

Closing the issue... 
Thanks for the help.
