### ISSUE TITLE
Set IP address manually

### ISSUE THREAD

**Issue by hapiben** [weaveworks/weave#1952]
Hi,

I wonder if this is possible. I tried to look into the documentation and issues and nothing says about setting the IP address manually.

One reason is that one of my Rails docker container check the request remote IP. The IP address should be on the list, otherwise the app will return 404.

I can put all the IP addresses (10.32.0.x) that weave generates, but is there a very efficient way to do this?

Cheers!

**Comment by rade** [comment]
>  I tried to look into the documentation and issues and nothing says about setting the IP address manually.

 ["Instead of getting weave to allocate IP addresses automatically, it is also possible to specify an address and network explicitly, ..."](http://docs.weave.works/weave/latest_release/features.html#addressing)

**Comment by hapiben** [comment]
Cheers!
