### ISSUE TITLE
Weave overlay networking on container naming

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#1953]
There appear to be different ways in identifying containers. Weave uses the -h option to set the container (host)name, whereas the default docker overlay driver uses the --name option. Also I need to add ".weave.local" to the hostname, and add a dns-search option. This makes it hard to write uniform docker-compose files that I can use with the different drivers.
This really should be harmonised across the different network drivers.

Any short term work-around/solution for this?

**Comment by rade** [comment]
> Weave uses the -h option to set the container (host)name, whereas the default docker overlay driver uses the --name option.

We could do this differently, but what Docker is doing here will in all likelihood change.

>  Also I need to add ".weave.local" to the hostname, and add a dns-search option.

Docker network plugins do not have an opportunity to alter these settings.

> Any short term work-around/solution for this?

Use the weave proxy. It derives the container hostname from the container name by default, and that in turn ends up in DNS. It also sets the dns search path.

>  This really should be harmonised across the different network drivers.

Perhaps. The more one pins down how a particular type of plug-in should behave, the less opportunity there is for plugins to do something different and interesting, which rather weakens the raison d'être for plug-ins.

**Comment by bergtwvd** [comment]
Thanks for the answers.

As such the issue could be closed, since it is more a clarification / feasture request than problem.

-- Tom
