### ISSUE TITLE
Can't connect a container to two weave plugin networks

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1960]
````
$ docker network create --driver=weavemesh weave2
$ docker run --name=foo -tdi --net=weave alpine /bin/sh
c4a6967fd9e80a32e6c37df6c045c349db7a868fe7e45606de62eba7dbfe9a76
$ docker network connect weave2 foo
Error response from daemon: failed to add interface vethwg89e21 to sandbox: error setting interface "vethwg89e21" routes to ["224.0.0.0/4"]: file exists
````

This is because the plugin asks Docker to set up the multicast route, and Linux doesn't let you add the same route pointing in two directions.

The plugin isn't given enough context to know there is already a multicast route.

**Comment by rade** [comment]
Is there a way to pass some config information ("don't create routes") to the plugin as part of 'create', and for that information then to be accessible at attach time?

**Comment by rade** [comment]
> Is there a way to pass some config information ("don't create routes") to the plugin as part of 'create'?

Looks like that wouldn't be sufficient for at least one user:

> I have multiple apps/sites running in a docker swarm. Each app is distributed over multiple containers and has it's own weave network. The containers need multicast. I also want to have 1 ip-adress for the entire cluster, with a HAProxy that routes traffic to the proper app. This HAProxy is the only container connected to multiple weave networks. The HAProxy does not need multicast.

**Comment by bboreham** [comment]
> Is there a way to pass some config information to the plugin as part of 'create'

Yes:

    docker network create --driver=weavemesh --opt=[foo=bar] mynet

> and for that information then to be accessible at attach time?

It's available via `docker network inspect <network_id>`, which would avoid us needing to persist it.

**Comment by bboreham** [comment]
There is no similar interface for `docker network connect` or for connecting as part of `docker run`, to specify parameters per-container.

**Comment by sheerun** [comment]
Launching plugin with `weave launch-plugin --no-multicast-route` is sufficient workaround for me now.

**Comment by sheerun** [comment]
@bboreham @rade Could I get confirmation the docket network with `weavemesh` driver need to be created manually on each host? This is different behavior from native overlay network as it needs to be created only on single host and then is automatically propagated. If no then I'll open an issue.

**Comment by awh** [comment]
> Could I get confirmation the docker network with weavemesh driver need to be created manually on each host?

It does need to be created on each host, but not manually as it's done for you by `weave launch`/`weave launch-plugin`

> This is different behavior from native overlay network as it needs to be created only on single host and then is automatically propagated

If you want that behaviour configure Docker with a cluster store and use the `weave` driver instead. The entire point of the `weavemesh` driver is to let you use weave without having to have a centralised strongly consistent store, with some caveats such as the one you describe - see our [blog article](https://www.weave.works/docker-networking-without-cluster-store-plugin) for more details.

> If no then I'll open an issue.

Please don't open a weave issue for this, we can't fix it - it's a consequence of Docker's plugin API and they have made it pretty clear that they're not going to change it e.g. docker/libnetwork#139, docker/libnetwork#486.

**Comment by sdurrheimer** [comment]
Hello, is the `weave launch-plugin --no-multicast-route` the official workaround for now ?

**Comment by bboreham** [comment]
@sdurrheimer yes, I think that's the only option apart from digging into the code.

**Comment by sdurrheimer** [comment]
Do you have any plans to fix this issue ?

**Comment by rade** [comment]
@sdurrheimer what is wrong with the "workaround"?

**Comment by sdurrheimer** [comment]
@rade not having to disable the multicast route.

**Comment by rade** [comment]
@surrheimer What is the intended behaviour for multicast when a container is part of multiple networks? Is a multicast from container A supposed to reach all containers on all networks to which A is connected? That is technically dubious, since multicast usually does not cross networks.

Or are you perhaps looking for a way to attach containers to multiple networks where only *one* network is used for multicast?

**Comment by sdurrheimer** [comment]
@rade I have no plan to use multicast for now. It was just a simple question given that the current workaround was proposed by a user and that this issue is still open.

**Comment by rade** [comment]
@sdurrheimer  thanks for the clarification

@bboreham with the changes in #2327, I wonder whether the most-likely-to-work-for-most-users-most-of-the-time configuration is to have no multicast route by default (and perhaps even remove the `--no-multicast-route` option from the plugin) but to enable it for the 'weave' network we create.
