### ISSUE TITLE
various `weave --local` functions are broken

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#1965]
$ sudo weave --local ps
    weave:expose 26:09:9e:a0:d6:a5
    no such file or directory

because it is running

    docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc -e PROCFS=/hostproc --entrypoint=/usr/bin/weaveutil weaveworks/weaveexec:latest container-addrs /proc weave weave:expose f438f9a36b72

because `$PROCFS` is `/proc`, correct for non`--local` case and `--local` with `weaveutil` accessible, but incorrect for `--local` which has to run `weaveutil` via Docker

**Comment by rade** [comment]
> various `weave --local` functions

Any others than `ps`?

**Comment by rade** [comment]
> Any others than `ps`?

I guess all commands that invoke `with_container_addresses`, correct?

**Comment by bboreham** [comment]
Indeed.
