### ISSUE TITLE
weave on mesos using ubuntu

### ISSUE THREAD

**Issue by hodiapa** [weaveworks/weave#1980]
documentation guides is missing critical support for the ubuntu based weave deployment for mesos.
As the guide contains only the Centos version, systemctl is missing on the Ubuntu based systems.

**Comment by rade** [comment]
> systemctl is missing on the Ubuntu based systems.

Modern Ubuntus do run systemd and hence have systemctl. What Ubuntu version are you running? Could you perhaps upgrade?

**Comment by rade** [comment]
Actually, this is a dup of weaveworks/guides#38.

**Comment by hodiapa** [comment]
I am using ubuntu 14.04 LTS and systemctl is an unknown command on this machine

**Comment by rade** [comment]
right. 14.04 pre-dates the introduction of systemd.

**Comment by hodiapa** [comment]
is there an upstart script for the WEAVE service?

**Comment by rade** [comment]
> is there an upstart script for the WEAVE service?

Not an official one. It might be worth asking on the [mailing list](https://groups.google.com/a/weave.works/forum/#!forum/weave-users).
