### ISSUE TITLE
depend on official plugin helper interfaces instead of docker internal APIs

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1986]
As per https://github.com/weaveworks/weave/pull/1985#issuecomment-185910220, our network and ipam drivers should depend on https://github.com/docker/go-plugins-helpers/, not the likes of  libnetwork/ipamapi.

**Comment by awh** [comment]
We agreed IRL to close this as the Docker plugins-helpers framework is incompatible with using a single socket.
