### ISSUE TITLE
following plugin docs can easily lead to using both proxy and plugin

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#1988]
Several users have ended up creating containers using both the weave proxy and and specifying `--net=weave`. This is rarely (ever?) a good idea.

The [plugin docs](http://docs.weave.works/weave/latest_release/plugin.html) talk about running `weave launch` "the usual way", which could easily lead folks to thinking they should follow [our introductory example](https://github.com/weaveworks/weave#example), including the `eval $(weave env)` bit.

As a minimum we should amend the plugin docs, perhaps with a prominent note warning against `eval $(weave env)` or otherwise using the proxy.

But we should also consider whether using both the proxy and plugin is in fact a legitimate use case. If not we should either refuse to do it and log a suitable error, or prefer one over the other.

If we do the latter, which should be preferred? It is actually tricky for both the proxy and plugin to detect the other. The proxy won't know for sure which networks are weave networks. And the plugin doesn't even know what container it is dealing with, since docker won't tell it.

I suppose the proxy could ignore all containers created with a network other than `default`, `bridge`, `none` or unset.

**Comment by rade** [comment]
I have tweaked the docs.

**Comment by berlic** [comment]
I've followed the docs today. Everything is straightforward, but one thing...
I used `weave setup` and `weave launch` on docker 1.10 host.
After that I got tree containers running:

```
IMAGE                        COMMAND                  NAMES
weaveworks/plugin:1.4.4      "/home/weave/plugin"     weaveplugin
weaveworks/weaveexec:1.4.4   "/home/weave/weavepro"   weaveproxy
weaveworks/weave:1.4.4       "/home/weave/weaver -"   weave
```
Do I really need weaveproxy in my setup?
I don't use `eval $(weave env)`, only `--net=weave` and `dns-args` things.

There is a hint in documentation to use alternative way to start wave plugin:

```
$ weave launch-router
$ weave launch-plugin
```

Is it actually the preferred way in case of plugin setup?

**Comment by rade** [comment]
There is no harm in having the proxy running.
