### ISSUE TITLE
weave container is not picking nameserver from host's resolv.conf

### ISSUE THREAD

**Issue by sunilganatra** [weaveworks/weave#1993]
kernel version :
uname -a
Linux 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

weave version:
[root@hostname]# weave version
weave script 1.3.1
weave router 1.3.1
weave proxy  1.3.1

docker --version
Docker version 1.9.1, build a34a1d5

OS version centos 7

On host following are the entries
[root@hostname]# cat /etc/resolv.conf
nameserver 10.0.80.11
nameserver 10.0.80.12
options single-request

On container it is not picking entries of host's /etc/resolv.conf
[root@test-contaiiner /]
nameserver 172.17.0.1
options single-request

Facing this issue while creating container in weave network.

**Comment by rade** [comment]
This is the expected behaviour. The 172.17.0.1 is [weaveDNS](http://docs.weave.works/weave/latest_release/weavedns.html). That in turn will relay requests to the nameservers configured in the host.

Is this behaviour causing you problems somehow?

**Comment by sunilganatra** [comment]
I am facing issue in particular environment where it isn't able to resolve nameservers. is there any way to confirm what all nameservers weaveDNS is resolving. any log?

**Comment by rade** [comment]
> is there any way to confirm what all nameservers weaveDNS is resolving. any log?

See [the weaveDNS troubleshooting docs](http://docs.weave.works/weave/latest_release/weavedns.html#troubleshooting).

**Comment by bboreham** [comment]
@sunilganatra did you find anything out from the logs?

**Comment by bboreham** [comment]
Please re-open if there is more information.
