### ISSUE TITLE
weave launch issue of pending

### ISSUE THREAD

**Issue by igenyar** [weaveworks/weave#2007]
I have one weave server accessible in public internet (C, i.e., a machine starts "weave launch"), and two machines (A and B) in the same private network behind firewall. (Please don't ask why A and B needs outside weave server in this case, we just end up needing it somehow. If this is a limitation, please let me know as I don't seem to find the mentioning of it in the doc.)

On A,

    $ weave launch C
    $ weave status
            Version: 1.4.3

            Service: router
           Protocol: weave 1..2
               Name: 12:34:56:78:9a:bc(xxxxx)
         Encryption: disabled
      PeerDiscovery: enabled
            Targets: 1
        Connections: 1 (1 established)
              Peers: 2 (with 2 established connections)
     TrustedSubnets: none

            Service: ipam
             Status: ready
              Range: 10.32.0.0-10.47.255.255
      DefaultSubnet: 10.32.0.0/12

            Service: dns
             Domain: weave.local.
           Upstream: 127.0.0.1
                TTL: 1
            Entries: 0

            Service: proxy
            Address: unix:///var/run/weave/weave.sock

Then on B,

    $ weave launch C
    $ weave status
            Version: 1.4.3

            Service: router
           Protocol: weave 1..2
               Name: fe:dc:ba:98:76:54(yyyyy)
         Encryption: disabled
      PeerDiscovery: enabled
            Targets: 1
        Connections: 2 (1 pending, 1 connecting)
              Peers: 3 (with 2 established, 2 pending connections)
     TrustedSubnets: none

            Service: ipam
             Status: ready
              Range: 10.32.0.0-10.47.255.255
      DefaultSubnet: 10.32.0.0/12

            Service: dns
             Domain: weave.local.
           Upstream: 127.0.0.1
                TTL: 1
            Entries: 0

            Service: proxy
            Address: unix:///var/run/weave/weave.sock

            Service: plugin
         DriverName: weave

In the connections, A is established while B pending even after waiting pretty long time. I can reverse the order of execution to get B established and A pending. In some rare cases, I can get both of them established but they are not really "connected" (below).

As a result, I can continue "weave expose" which seems getting weave address, but they still cannot ping each other.

If needed, I can supply more information for diagnosis.

Thanks for the help.

**Comment by igenyar** [comment]
Just found one, looks like my problem is similar to this:

https://groups.google.com/a/weave.works/forum/#!topic/weave-users/GzQnbHBNbgE

which is also pretty recent.

**Comment by fyy919** [comment]
Hi  igenyar,
How did you solve the problem？
Regards!
