### ISSUE TITLE
non-existent volume host path /var/run/weave

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2011]
Docker 1.10 logs this:

```
Mar 01 13:05:43 ip-172-20-0-188 docker[2200]: time="2016-03-01T13:05:43.888266602Z" level=warning msg="Auto-creating non-existent volume host path /var/run/weave, this is deprecated and will be removed soon"
```

Would be good to stay on top of this, and figure out the fix before it breaks.

**Comment by rade** [comment]
I don't see this warning in Docker 1.11.2 with weave 1.6. @errordeveloper do you?

**Comment by bboreham** [comment]
Closing due long period with no evidence of an issue.
