### ISSUE TITLE
Add underlay network implementation based on AWS VPC

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2017]
In a case when all Weave peers run on AWS within the same VPC, we could rely on AWS VPC for packet routing instead of using custom overlays.

Most of the work is done, the following is missing:

- [x] Cleanup VPC route table upon peer termination.
- [x] Change the block donation algo strategy to the one which tries to find such block that its donation would require minimal amount of changes in the route table.
- [x] Simplify grouping of IP ranges: merge ranges before calling `HandleUpdate`, match only those ranges which differ.
- [x] Error handling for special situations: the 50 routes limit has been reached, etc.
- [x] System tests on the AWS infra.
- [ ] Write docs, guides, etc.
- [x] Simplify system setup (route table detection, setting proxy_arp, etc.)
- [ ] Consider subnet isolation: no container can be reached from a host running it.
- [x] Avoid using `fatal` loglevel when possible.

Nice to have:

- [ ] Make update ops of the route table asynchronous (i.e., move to a separate goroutine).
- [ ] Improve semantics for choosing a peer for donations.

This issue does not cover changes which would be required in order to make the AWS VPC overlay compatible with the existing overlay implementations (in particular, with `sleeve` and `fastdp`).

**Comment by bboreham** [comment]
Enhancements moved to #2322
