### ISSUE TITLE
ERROR: Unable to determine docker version

### ISSUE THREAD

**Issue by voobscout** [weaveworks/weave#2022]
Looks like docker 1.10.2 is not supported yet.
```
$ weave launch

level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header"
ERROR: Unable to determine docker version
```

```
$ docker version

Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Thu Feb 25 09:29:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.6
 Git commit:   c3959b1
 Built:        Tue Feb 23 00:53:12 2016
 OS/Arch:      linux/amd64
```

**Comment by awh** [comment]
@voobscout 

Works for me:
```
vagrant@vagrant-ubuntu-wily-64:~$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64
vagrant@vagrant-ubuntu-wily-64:~$ weave version
weave script 1.4.5
weave router 1.4.5
weave proxy  1.4.5
weave plugin 1.4.5
vagrant@vagrant-ubuntu-wily-64:~$ weave launch
vagrant@vagrant-ubuntu-wily-64:~$ weave status

        Version: 1.4.5

        Service: router
       Protocol: weave 1..2
           Name: ce:20:0b:44:fa:3b(vagrant-ubuntu-wily-64)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 0
    Connections: 0
          Peers: 1
 TrustedSubnets: none

        Service: ipam
         Status: idle
          Range: 10.32.0.0-10.47.255.255
  DefaultSubnet: 10.32.0.0/12

        Service: dns
         Domain: weave.local.
       Upstream: 10.0.2.3
            TTL: 1
        Entries: 0

        Service: proxy
        Address: unix:///var/run/weave/weave.sock

        Service: plugin
     DriverName: weave

vagrant@vagrant-ubuntu-wily-64:~$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
a44247e2045e        weaveworks/plugin:1.4.5      "/home/weave/plugin"     6 seconds ago       Up 6 seconds                            weaveplugin
025fbbdfb3f7        weaveworks/weaveexec:1.4.5   "/home/weave/weavepro"   6 seconds ago       Up 6 seconds                            weaveproxy
7c7cb0ef9cb9        weaveworks/weave:1.4.5       "/home/weave/weaver -"   7 seconds ago       Up 7 seconds                            weave
```
Your docker looks suspect - compare the go version and build times to mine, which was installed from the official repository. What is the provenance of yours? Note there is a known backwards compatibility issue when compiling docker with go 1.6 docker/docker#20865.

**Comment by julianxhokaxhiu** [comment]
Help, I'm having the same issue right now:

```
~ # weave launch
time="2016-05-17T11:22:44Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header"

~ # docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64
```

**Comment by bboreham** [comment]
@julianxhokaxhiu Same answer as last time - your Docker is not the official release, and you are likely falling foul of the known backwards-compatibility issue docker/docker#20865.

**Comment by julianxhokaxhiu** [comment]
Sorry but it's the one in the Mainline on Arch Linux, what does it mean is not official?

**Comment by bboreham** [comment]
@julianxhokaxhiu well, I guess it may be "official" for Arch Linux; you should ask them whether they intend to be compatible with products using down-level components.

Weave Net bundles a copy of the docker 1.6 client, in order to perform certain actions inside a container.  Docker built with Go 1.6 is not compatible with earlier Docker clients before 1.10.

There is a possible work-around at https://github.com/weaveworks/weave/issues/2234#issuecomment-215359266; bind-mounting your Arch Linux `docker` binary on top of the one that Weave ships. 

Docker are working on https://github.com/docker/docker/pull/22000; when that is merged they will move to Go 1.6 and this problem will have an official work-around.

**Comment by julianxhokaxhiu** [comment]
Trying to do so gives me this:

```
~ # WEAVEEXEC_DOCKER_ARGS="-v /usr/bin/docker:/usr/local/bin/docker" weave launch
/home/weave/weave: line 319: docker: not found
ERROR: Unable to parse docker version
```

**Comment by brb** [comment]
@julianxhokaxhiu alternatively, you can recompile the [Docker](https://www.archlinux.org/packages/community/x86_64/docker/) package with go < 1.6.

**Comment by julianxhokaxhiu** [comment]
The workaround is just fine, I looking forward to that. I only would like to understand why it gives that error, while for the others work :\ Is the path inside the Docker maybe wrong?

if I try

```
~ # WEAVEEXEC_DOCKER_ARGS="-v /usr/bin/docker:/usr/bin/docker" weave launch
time="2016-05-17T12:28:47Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header"
```

then I get this

**Comment by bboreham** [comment]
@julianxhokaxhiu in

    WEAVEEXEC_DOCKER_ARGS="-v /usr/bin/docker:/usr/local/bin/docker" ...

the first path has to be where your `docker` client is located.  The second path has to be `/usr/local/bin/docker` to overwrite where our copy is located.

Most likely your `docker` was not at `/usr/bin`.

**Comment by julianxhokaxhiu** [comment]
Tryed both as written up there and still doesn't work...I cannot understand why. For others it worked and my path is definitely `/usr/bin/docker` on the host machine. Where it located on your Docker image?

**Comment by bboreham** [comment]
@julianxhokaxhiu this `docker: not found` problem will also happen if your Docker binary is dynamically linked to libraries we don't have inside the container.

At which point it is getting easier to recompile Docker, or fetch Docker's release from get.docker.com

Sorry about this.

**Comment by julianxhokaxhiu** [comment]
Ok, thank you very much for all the help then :) I'll try to figure out a solution
