### ISSUE TITLE
Preventing an attack on electorate

### ISSUE THREAD

**Issue by sheerun** [weaveworks/weave#2027]
Hey, as you may already know I'm playing with idea of making a public network of weave hosts.

I can imagine a network of `n` nodes and an attacker that joins this network with modified `n+1` electing nodes that vote only within their group and performs a DDOS attack on one of existing electing nodes.

Am I right that this way he would steel electorate one by one and could destroy such network?

Is that a way to prevent such attack? I think there are is one compelling solution:

- If some host wants to become electing node he needs a consensus of current electorate. Electorate could dismiss electing node by consensus as well. One possible voting rule would would be `--electing-networks` flag, so only hosts from specific network / addresses could become electing nodes. There could be other pluggable indicators, like entry on external consensus system, maximum number of electors possible, password-based authentication etc.

**Comment by rade** [comment]
If an attacker manages to connect to the weave network, disrupting IP address allocation is only one of the ways they can cause difficulties. There are far more direct ways, e.g. flood the network with broadcasts, claim ownership of MAC addresses, etc.

**Comment by sheerun** [comment]
Well, we could start somewhere :) Broadcasts could be disabled for public network, or there could be bandwidth limit per ip address.

**Comment by sheerun** [comment]
By the way this can happen in private network as well, even if one host is exposed.

**Comment by rade** [comment]
> By the way this can happen in private network as well, even if one host is exposed.

Yes, and my point is that it is massive challenge to change weave's security model s.t. the impact of compromising a single host is limited. IPAM is but one small part of that and compromising that has strictly limited impact, e.g. it cannot disrupt communication between any existing containers. MAC spoofing and other network-centric attacks can though.

**Comment by sheerun** [comment]
I meant that this feature is worth implementing even if weave is runned in vpn, not public. Exposing even one host in vpn (e.g. bastion host) could lead to successful attack all the hosts using weave.

I think this is fair feature to implement even if you don't plan releasing public cloud.

**Comment by rade** [comment]
> I meant that this feature is worth implementing even if weave is runned in vpn

Yes, I got that. But IPAM isn't the main weak point.
