### ISSUE TITLE
Cannot attach to multiple weavemesh networks

### ISSUE THREAD

**Issue by sheerun** [weaveworks/weave#2041]
### Weave version:

```
weave script (unreleased version)
weave router git-05a7024b885d
weave proxy  git-05a7024b885d
weave plugin git-05a7024b885d
```

### Steps to reproduce:

```
weave launch-router
weave launch-plugin
docker network create --driver weavemesh --internal --subnet 10.40.0.0/16 net1
docker network create --driver weavemesh --internal --subnet 10.50.0.0/16 net2
docker create --name busybox -ti --net net1 --ip 10.40.1.0 busybox ifconfig
docker network connect --ip 10.50.1.0 net2 busybox
docker start -ai busybox
```

### Result:

> Error response from daemon: Cannot start container 9e26eb8b02face676279db8ee4e97876bc06dbe197bb8c50693987cbe3958254: [9] System error: failed to add interface vethwg8fa68 to sandbox: error setting interface "vethwg8fa68" routes to ["224.0.0.0/4"]: file exists

### Expected result:

Container starts connected to two network interfaces.

### Additional notes:

This method works perfectly well with docket's native overlay network.

**Comment by rade** [comment]
dup of #1960.
