### ISSUE TITLE
Ability to rotate weave password without shutting down network

### ISSUE THREAD

**Issue by sheerun** [weaveworks/weave#2043]
Hey,

In case the password for my weave network is exposed (or I just want to rotate passwords as a security measure), I'd like to change it without disrupting the networks as a whole. Is itpossible to set multiple passwords at once, so I can perform following scenario?

1. The password for all nodes is "alpha"
2. I change password on each node to both "alpha,beta", one by one
3. As each node accepts "beta" as a password, remove "alpha" password from each node, one by one

**Comment by awh** [comment]
Duplicate of #39.
