### ISSUE TITLE
Static IP doesn't work with with extra weavemesh network with IPAM driver

### ISSUE THREAD

**Issue by sheerun** [weaveworks/weave#2046]
### Steps to reproduce:

```
docker network create --driver weavemesh --ipam-driver weavemesh --subnet 10.41.0.0/16 net
docker run --name ubuntu --net net --rm -ti --ip 10.41.0.5 ubuntu ifconfig
```

### Result:

```
docker: Error response from daemon: IpamDriver.RequestAddress: 404 Not Found: 404 page not found.
```

### Expected result:

Container is created with 10.41.0.5 IP address attached.

### Additional notes:

Assigning static IP works perfectly well when leaving default IPAM driver, but it doesn't maintain consistency across hosts (I can assing the same IP twice). `weavemesh` IPAM driver works only for default `weave` network that launch-plugin creates.

**Comment by bboreham** [comment]
Could you say which version of Weave you are using?  If < 1.5.0 (which we haven't released yet) then this is fixed by #1916.

**Comment by sheerun** [comment]
I use weave:latest container and weave script from master branch.

**Comment by rade** [comment]
please post the output of `weave version`

**Comment by sheerun** [comment]
weave script (unreleased version)
weave router git-05a7024b885d
weave proxy  git-05a7024b885d
weave plugin git-05a7024b885d

**Comment by rade** [comment]
`docker version`?

**Comment by sheerun** [comment]
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.6
 Git commit:   c3959b1
 Built:        Tue Feb 23 21:11:36 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

**Comment by sheerun** [comment]
But it's the same on coreos server with 1.10.2 as both server and client.

**Comment by rade** [comment]
reproduced (btw, there was a typo in the OP's instructions):
```
$ weave launch --log-level=debug
$ docker network create --driver weavemesh --ipam-driver weavemesh --subnet 10.40.0.0/16 net
99e36747b988a6a349789b7cb507b2fde0bddd33d7c57897b2da66ca785551d4
$ docker run --name ubuntu --net net --rm -ti --ip 10.41.0.5 ubuntu ifconfig
docker: Error response from daemon: Invalid preferred address 10.41.0.5: It does not belong to any of this network's subnets.
$ docker run --name ubuntu --net net --rm -ti --ip 10.40.0.5 ubuntu ifconfig
docker: Error response from daemon: IpamDriver.RequestAddress: 404 Not Found: 404 page not found.
$ docker logs weaveplugin
...
DEBU: 2016/03/14 15:36:48.902157 RequestAddress weave-10.40.0.0/16-10.40.0.0/16 10.40.0.5 map[]
DEBU: 2016/03/14 15:36:48.902211 weave PUT to http://127.0.0.1:6784/ip/_/10.40.0.5 with map[]
DEBU: 2016/03/14 15:36:48.902531 allocateIP returned <nil> 404 Not Found: 404 page not found
```

**Comment by bboreham** [comment]
Ah, sorry, this got broken by #2012.  

The URL should be http://127.0.0.1:6784/ip/_/10.40.0.5/16
