### ISSUE TITLE
errors returned by weave http api are ignored by weave script

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2052]
curl returns a 0 exit status for HTTP errors (as opposed to connectivity, etc errors):
```
$ curl --connect-timeout 3 -s -S -X POST -d peer=1 http://127.0.0.1:6784/connect
lookup 1: invalid domain name
$ echo $?
0
```
And just to check that we are indeed returning an error code:
```
$ curl -D - --connect-timeout 3 -s -S -X POST -d peer=1 http://127.0.0.1:6784/connect
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 16 Mar 2016 22:38:50 GMT
Content-Length: 30

lookup 1: invalid domain name
```

The curl behaviour can be changed with `-f`, but that doesn't print the returned response:
```
$ curl -f --connect-timeout 3 -s -S -X POST -d peer=1 http://127.0.0.1:6784/connect
curl: (22) The requested URL returned error: 400 Bad Request
$ echo $?
22
```

**user impact**

- claiming individual IP addresses in `ipam_cidrs` (called from `weave run|start|attach|expose`; `weave attach` is also called by the proxy)

    ```
    $ weave run ip:10.32.0.1/24 -ti alpine /bin/sh
    978c65ca3593a33a28eafc48029a331949a0033d4ae177326bb7eeb27615485a
    $ weave run ip:10.32.0.1/24 -ti alpine /bin/sh
    Unable to claim: address 10.32.0.1/24 is already owned by 978c65ca3593a33a28eafc48029a331949a0033d4ae177326bb7eeb27615485a
    9a59bd62937a5448770c0c7d553a041a51f23b3a06287a7543897355377d70dc
    $ echo $?
    0
    ```
- reclaiming IP addressed in `weave restart`. This will fail in the same way as the example above if the IP got pinched by another container during the restart.
- `weave rmpeer`

    ````
     $ weave rmpeer foo
     Cannot find peer 'foo'
     $ echo $?
     0
    ````
- `weave connect|forget`

    ````
     $ weave connect 1
     lookup 1: invalid domain name
     $ echo $?
     0
    ````
- `weave report`

    ````
    $ weave report -f '{{'
    template: format:1: unexpected unclosed action in command
    $ echo $?
    0
    ````

**unaffected**

- `weave status` - we handle invalid sub-commands specially, and this really shouldn't fail for other reasons
- `weave consense` - can't fail
- reclaiming individual IP addresses for all containers, and the bridge, when the router (re)starts. This generally shouldn't fail with an HTTP error, so this is fine.
- waiting for router|proxy|plugin status on launch. The status call generally shouldn't fail with an HTTP error, so this is fine.
- obtaining proxy address for the likes of `weave env|config`. The status call generally shouldn't fail with an HTTP error, so this is fine.
- allocating IP addresses through `ipam_cidrs` (called from `weave run|start|attach|expose`; `weave attach` is also called by the proxy) and looking up IP addresses through ipam_cidrs (called from `weave detach|hide`). We catch errors here by checking that the output is a CIDR. So this is fine.
- releasing IP addresses in `weave detach|hide` - this should not go wrong, since we first perform a lookup, and hence should only be releasing owned addresses.

I am tentatively putting this into 1.4.6, since this is pretty bad for scripting weave, though I doubt we can think of a low-risk fix for this. @awh suggested replacing curl with a weaveutil function. Or perhaps do the replacement at the slightly higher level of `call_weave`, `wait_for_status` et al.

**Comment by rade** [comment]
A related problem here is that error messages appear on stdout, not stderr.

**Comment by bboreham** [comment]
There are a couple of places where we do detect errors by checking the output is exactly `"404 page not found"`

It pains me to think it, but `curl` is just not up to the job we want it to do.

**Comment by rade** [comment]
Here's a possibly not-too-horrific way of fixing this...

```
curl --connect-timeout 3 -s -S -w '%{http_code}\n' -X POST -d peer=foo http://127.0.0.1:6784/connect
lookup foo on 127.0.1.1:53: no such host
400
```
Then it's just a matter of extracting the status code from the end, checking whether it is != 2xx, and if so output everything that came before on stderr and return an error.
