### ISSUE TITLE
IPAM status documentation out of date

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2061]
The documentation of the IPAM status is completely out of date.

http://docs.weave.works/weave/latest_release/troubleshooting.html#weave-status says
> Consensus: achieved

but the field is now called `Status` and there is no such value as `achieved`.

http://docs.weave.works/weave/latest_release/ipam.html#initialisation talks about three states - deferred, waiting, achieved. What gets actually displayed is one of the following:

- `all IP ranges owned by unreachable peers - use 'rmpeer' if they are dead`
- `waiting for IP range grant from peers`
- `ready`
- `awaiting consensus (quorum: X, known: Y)`
- `idle`

This got broken in #1702, where the above status display was introduced but none of the wording in the docs was changed. So this has been wrong since 1.4.0.

**Comment by awh** [comment]
Is this a dup of #1876?

**Comment by rade** [comment]
> Is this a dup of #1876?

No. #1876 is about `weave status ipam`, which is conspicuously absent from our docs. This issue is about the ipam `Status` field reported in `weave status`.
