### ISSUE TITLE
Rationalise seeding, consensus and observers

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2065]
Now that we have augmented the IPAM consensus mechanism (in a somewhat piecemeal fashion) with observers and seeding, there is an opportunity to step back and attempt to reverse engineer an encompassing user model that can be used to streamline the overall command syntax, status output and documentation.

Whilst from an implementation perspective there are two 'modes' of initialisation (seeding, and consensus with electors and observers) @rade speculates that it might make more sense to elevate observation for use with either consensus or seeding, resulting in three modes:

* Seeded
* Consensed
* Observed

It is technically possible to mix all three of these in a cluster, but for the sake of sanity we should probably recommend seeded XOR consensus, with optional observers in either case.

Some considerations:

* We need a replacement name for `weave consense` - it does not make sense if it is used on an observer which is connected to seeded peers
* Determine whether `weave consense` should guarantee that a piece of the ring is owned by the calling peer in addition to obtaining a copy of the existing ring. This would make it more useful when adding a new seeded peer which is itself not part of the seed
* Determine whether `--observer` is appropriately named
* Determine whether `--ipam-seed` is appropriately named
* Determine a name for the state in which an observer has made a ring request (#2063) but has yet to receive one - analagous to 'awaiting consensus' for an elector
* Consider a unified argument to `weave launch` that selects one of the three modes
* Consider whether we use IPAM specific terminology (e.g. `--ipam-observer`) or leave things generic in case we have other uses for consensus at a later date

Things that will need updating:

* Documentation
    * IPAM troubleshooting status explanations
* Log messages (e.g. "Unable to parse IPAM seed")
* Flag help (e.g. `--observer` flag help mentions paxos)

**Comment by awh** [comment]
Suggestions for renaming `weave consense`:
`weave sync-ipam`
`weave init-ipam`
`weave join-ipam`

**Comment by paulbellamy** [comment]
maybe, `weave init-ipam-cluster`. It says we're doing initialization, and that it will/may involve all nodes
Or some indicator that this is doing some allocation/assignment of the ipam space.

Cassandra uses the terminology of "initializing a cluster", or possibly "rebalancing the partitioner" if you're already running.

**Comment by paulbellamy** [comment]
`weave reify...`

**Comment by awh** [comment]
@rade thoughts on a mode selector:

Consensed mode (default for backwards compatibility):
`weave launch --mode=consensed [--init-peer-count=n]`
Observed mode:
`weave launch --mode=observed`
Seeded mode (`<seed list>` defaults to `<peername>`):
`weave launch --name <peername> --mode=seeded [--init-peers=<seed list>]`

**Comment by rade** [comment]
- we want all options to obviously relate to IPAM, perhaps even IPAM initialisation
- we want the peer count option and consensus mode to be obviously related
- we want the seed list option and seed mode to be obviously related.

Perhaps:
```
--ipalloc-init=consense[:count]
--ipalloc-init=seed:<list>
--ipalloc-init=observe
```

(and deprecate `--init-peer-count`)

And we still need a better name for `consense`.

**Comment by awh** [comment]
> And we still need a better name for consense.

`--ipalloc-init=vote`?

**Comment by rade** [comment]
agree? negotiate?

**Comment by awh** [comment]
decide?

**Comment by rade** [comment]
In terms of meaning, we still haven't found anything that beats `consense` :(

**Comment by paulbellamy** [comment]
`consense` maps closely to *the internal implementation*, but `--ipalloc-init=<mode>` maps closer to *why the user wants to do the thing*

**Comment by rade** [comment]
@paulbellamy I don't understand your comment. The proposal is `--ipalloc-init=consense[:count]`.

**Comment by paulbellamy** [comment]
had misread a previous comment.

I guess my proposal is `--ipalloc-init=consensus[:count]`, or maybe `--ipalloc-init=quorum[:count]`

**Comment by rade** [comment]
The other two modes are `seed` and `observe`, which are both verbs (well, one of them definitely is). I guess we could switch to nouns all round...

```
--ipalloc-init=consensus[:count]
--ipalloc-init=seed:<list>
--ipalloc-init=observer
```

**Comment by rade** [comment]
We could call the command `weave ipalloc-init`. Or just `weave init`. Neither are perfect by any stretch.

**Comment by awh** [comment]
@bboreham would be good to get your input on this!

**Comment by bboreham** [comment]
What about 'quorum' instead of agree/consense?  We do talk about that concept already.

```
--ipalloc-init=quorum[:count]
--ipalloc-init=seed:<list>
--ipalloc-init=observe
```

**Comment by bboreham** [comment]
and the command `weave ipalloc-init`

**Comment by bboreham** [comment]
`weave ready` for the command?

**Comment by awh** [comment]
`weave prime`?

verb: to prepare or make ready for a particular purpose or operation.

**Comment by brb** [comment]
`weave force-init` ?

**Comment by awh** [comment]
> What about 'quorum' instead of agree/consense? We do talk about that concept already.
> --ipalloc-init=quorum[:count]
> --ipalloc-init=seed:<list>
> --ipalloc-init=observe

I think the thinking is that the word after the equals is the name of the mode - that would mean we would refer in the documentation to the three modes as quorum, seeding and observation - consensus would disappear. I'm not necessarily adverse to that, just pointing it out.

**Comment by bboreham** [comment]
Right now my preferred set are:

````
--ipalloc-init=consensus[:count]
--ipalloc-init=seed:<list>
--ipalloc-init=observer
weave prime
```

**Comment by rade** [comment]
+1
