### ISSUE TITLE
proxy can fail to re-attach restarted containers (640_proxy_restart_reattaches_test failure)

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2090]
The output from the build https://circleci.com/gh/weaveworks/weave/5115 :
```
>>> Test ./640_proxy_restart_reattaches_test.sh finished after 84.4 secs with error: exit status 1
Proxy restart reattaches networking to containers
59f0768f7c59fe50b7c231aca844983f724cd75ed1aff57c48287b344ddc7621
f32c5b5654850e6424b3619dcb7fac44dbad3e8b0d63b50f6dfa6173f0cbe22b
c2
weave
sudo: systemctl: command not found
host4-5115-0.us-central1-a.positive-cocoa-90213> docker stop/waiting
host4-5115-0.us-central1-a.positive-cocoa-90213> docker start/running, process 18202
Waiting for proxy to start
Waiting for proxy to start
120348873ce8f40d196db51c4a8457684320a401bcc082460e09fd875280223b
e313062d93bd0638d3bf9943659aad4d15004d76b3d8905e02101c3fa4e21e0d
test #7 "exec_on host4-5115-0.us-central1-a.positive-cocoa-90213 c2 grep ^1$ /sys/class/net/ethwe/carrier" failed:
	program terminated with code 1 instead of 0
test #8 "exec_on host4-5115-0.us-central1-a.positive-cocoa-90213 c1 getent hosts seetwo.weave.local | grep -q '10.32.0.1'" failed:
	program terminated with code 1 instead of 0
test #9 "exec_on host4-5115-0.us-central1-a.positive-cocoa-90213 c1 getent hosts 10.32.0.1 | tr -s ' ' | tr '[:upper:]' '[:lower:]'" failed:
	expected "10.32.0.1 seetwo.weave.local"
	got nothing
3 of 14 tests failed in 83.633s.
```

The test script has a check for the existence of the `systemctl` command. However, for some reasons `systemctl` gets executed regardless the check.

**Comment by rade** [comment]
I think the systemcl issue is a red herring. I reckon on our test VMs that *always* gets printed. Looks like there is something weird going on with user vs sudo envs, which makes systemctl available to the user but not in sudo. BUT it falls back to upstart, which still works, as evidenced by the "docker stop" and "docker start" lines.

I've just committed a change that should get rid of the "command not found" message.

The real cause of the test failure is the failing tests, as indicated.

**Comment by bboreham** [comment]
Now seems to be consistently failing:

````
>>> Test ./640_proxy_restart_reattaches_test.sh finished after 14.1 secs with error: exit status 1
Proxy restart reattaches networking to containers
5c1ec8f480ef0827115d104504931b60cd84c678f134f22dfdc2617b627c934e
14b1f1ddbc2bb11e08ab7c010c5dd777e4d5464beede1175a35b31add56d770c
c2
weave
bash: systemctl: command not found
stop: Rejected send message, 1 matched rules; type="method_call", sender=":1.56" (uid=1003 pid=13893 comm="stop docker ") interface="com.ubuntu.Upstart0_6.Job" member="Stop" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.57" (uid=1003 pid=13887 comm="start docker ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
````

**Comment by brb** [comment]
My first guess is that increasing sleep time at line 51 might fix the failures of tests 7-9.

**Comment by bboreham** [comment]
Note the sleep used to be 10 seconds, e.g. at #1609 (which also noted the `systemctl` problem), and we still had trouble.

**Comment by rade** [comment]
@bboreham has figured out what is going on here. It's another docker event issue...

The proxy sees the killed container (re)start and attempts a `weave attach --or-die`. IPAM checks whether the container is alive but because the 'start' event gets issued before the container has transitioned out of the 'restart' to the 'running' state (see #1775), and we deliberately treat 'restarting' as 'not running', IPAM can consider the container dead and cancel the request.
