### ISSUE TITLE
default eth0 route breaks kube-proxy in iptables mode

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2094]
Since Kubernetes v1.2, the `kube-proxy` is running in `iptables` mode by default, this in combination with the default route on `eth0` make service IPs unreachable.

This doesn't affect the CNI plugin, as there we own `eth0`. It also somehow doesn't affect `kube-proxy --mode=userspace`, perhaps because NAT rules are written somehow differently.

_ref https://github.com/weaveworks/weave-kubernetes-anywhere/issues/47_

**Comment by errordeveloper** [comment]
This can be worked-around by addition of an explicit route for service IPs:
```
sudo nsenter -t <pid> -n ip route add <service-ip-cidr> via <weave_expose_ip>
```

Please note that `ip route add <service-ip-cidr>  dev ethwe` is not suffiecent, for some reason...

**Comment by errordeveloper** [comment]
Alternatively, I'd be happy to say that if I have to use Docker API proxy, I must run `kube-proxy --proxy-mode=userspace`, otherwise I must use the CNI plugin.

**Comment by rade** [comment]
We could add some extra options to `weave attach` to add extra routes, and get the proxy to use that via another per-container env var like WEAVE_CIDR. That's all really quite gross though.

Since the CNI plugin just works, let's stick with that. -> WONTFIX.

**Comment by bboreham** [comment]
CNI doesn't work if you want to expose a port.  See https://github.com/kubernetes/kubernetes/issues/23920

**Comment by rade** [comment]
According to @errordeveloper the "correct" way to expose is via a `NodePort` type service.
