### ISSUE TITLE
outdated and dangerous advice for reboots

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2108]
From troubleshooting.md#reboots

> because the process of getting everything re-started and re-connected via restart policies is not entirely reliable, the router and proxy containers do not have Docker restart policies set. Until that changes, we recommend that you create appropriate startup scripts to launch Weave Net and run application containers from [your favourite process manager](/site/systemd.md).
>
> If you are shutting down or restarting a host deliberately, run `weave reset` to clear everything down.
> 
> The Weave Net Docker plugin does restart automatically because it must always start with Docker, as described in [its documentation](/site/weave-docker-api/using-proxy.md).

This is all complete nonsense now that we a) *do* configure restart policies for everything, and b) have permanent peer IDs and persistence (so you most certainly do not want to run `weave reset` on restarts.)

**Comment by koboltmarky** [comment]
Hi,

From what version do you use permanent peer IDs ?

Greets
Marc

**Comment by rade** [comment]
1.5

**Comment by koboltmarky** [comment]
thx
