### ISSUE TITLE
[ipam] automatic IP assignment in combination with Kubernetes

### ISSUE THREAD

**Issue by slintes** [weaveworks/weave#212]
Hi,

as discussed via mail with Bryan it would be nice to have automatic IP assignment when using weave in combination with Kubernetes, like it is done here: https://github.com/errordeveloper/weave-demos/tree/master/poseidon. The current configuration (writing configuration files with cloud config for each cluster node) is not scalable.
A nice option for providing the basic configuration and coordinating individual configurations of the cluster nodes would be using etcd.

This is related to #22, but another usecase.

Kind regards, Marc

**Comment by slintes** [comment]
Hi. Am I right that the latest weave release with IPAM is not useful for this issue? Just wanted to upgrade and give it a try, but I saw that @errordeveloper also didn't update his "poseidon" example (yet?).

**Comment by errordeveloper** [comment]
@slintes I am planning to work on this after https://github.com/GoogleCloudPlatform/kubernetes/pull/9646 is merged.

**Comment by slintes** [comment]
ok, thx!

**Comment by rade** [comment]
@paulbellamy @errordeveloper does #1199 address this issue?

**Comment by errordeveloper** [comment]
I am quite sure it does, Matthias. Please close this one.
