### ISSUE TITLE
Containers hang when peers set to self

### ISSUE THREAD

**Issue by mkocikowski** [weaveworks/weave#2136]
Ubuntu 15.10 running on Vagrant, with ip set to `10.0.1.10`. Weave 1.4.6 with Docker 1.10.3. Launching weave with peers set to `10.0.1.10` results in no errors. However, launching any docker containers (either via proxy or with network plugin) will hang.

**Comment by brb** [comment]
If you want to run weave on a single host, no peer should be provided, i.e. `weave launch` should do the job.

**Comment by rade** [comment]
dup of #1881
