### ISSUE TITLE
TestAllocatorFuzz fails from time to time with "panic: Error doing gossip broadcast: IP allocation was seeded by different peers <..>"

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2139]
```bash
panic: Error doing gossip broadcast: IP allocation was seeded by different peers (received: [00:00:00:02:00:00(nick-00:00:00:02:00:00) 03:00:00:02:00:00(nick-03:00:00:02:00:00) 04:00:00:02:00:00(nick-04:00:00:02:00:00)], ours: [00:00:00:02:00:00(nick-00:00:00:02:00:00) 01:00:00:02:00:00(nick-01:00:00:02:00:00) 02:00:00:02:00:00(nick-02:00:00:02:00:00) 03:00:00:02:00:00(nick-03:00:00:02:00:00) 04:00:00:02:00:00(nick-04:00:00:02:00:00)])

goroutine 75 [running]:
github.com/weaveworks/weave/testing/gossip.(*TestRouter).run(0xc8203cab80, 0x40000020000, 0x7f4f09e7b090, 0xc8203e4500, 0xc820319b00)
	/go/src/github.com/weaveworks/weave/testing/gossip/mocks.go:126 +0x4aa
created by github.com/weaveworks/weave/testing/gossip.(*TestRouter).Connect
	/go/src/github.com/weaveworks/weave/testing/gossip/mocks.go:161 +0xa2

<..>

goroutine 81 [chan receive]:
github.com/weaveworks/weave/ipam.(*Allocator).Allocate(0xc8203e4140, 0xc82041e2a0, 0x8, 0xa000107, 0x16, 0xb35200, 0xa34100, 0x0, 0x0)
	github.com/weaveworks/weave/ipam/_test/_obj_test/allocator.go:267 +0x1f9
github.com/weaveworks/weave/ipam.TestAllocatorFuzz.func4(0xc82041e2a0, 0x8)
	/go/src/github.com/weaveworks/weave/ipam/allocator_test.go:451 +0x15e
github.com/weaveworks/weave/ipam.TestAllocatorFuzz.func9(0x320)
	/go/src/github.com/weaveworks/weave/ipam/allocator_test.go:556 +0x146
github.com/weaveworks/weave/ipam.TestAllocatorFuzz.func8.1(0xc8203f5dd0, 0xc8, 0xc8203f5dc0, 0x4)
	/go/src/github.com/weaveworks/weave/ipam/allocator_test.go:546 +0x77
created by github.com/weaveworks/weave/ipam.TestAllocatorFuzz.func8
	/go/src/github.com/weaveworks/weave/ipam/allocator_test.go:548 +0x103

FAIL	github.com/weaveworks/weave/ipam	0.517s
```

Spotted in:

* https://circleci.com/gh/weaveworks/weave/5309
* https://circleci.com/gh/weaveworks/weave/5299
* https://circleci.com/gh/weaveworks/weave/5298

**Comment by rade** [comment]
I can reproduce this reliably with
```diff
diff --git a/ipam/allocator_test.go b/ipam/allocator_test.go
index 300a147..d050451 100644
--- a/ipam/allocator_test.go
+++ b/ipam/allocator_test.go
@@ -582,6 +582,12 @@ func TestAllocatorFuzz(t *testing.T) {
        })
 }
 
+func TestAllocatorFuzz1000(t *testing.T) {
+       for i := 0; i < 1000; i++ {
+               TestAllocatorFuzz(t)
+       }
+}
+
 func TestSpaceRequest(t *testing.T) {
        const (
                container1 = "cont-1"
```
and running `GO15VENDOREXPERIMENT=1 go test -test.run TestAllocatorFuzz1000 ./ipam`

I had some theory that `paxos.Consensus()` can be called when no quorum has been set, and erroneously creates a ring based on a proposal that has been accepted by just a single peer. But adding some debug output to `paxos.Consensus()` ruled that out.

**Comment by rade** [comment]
I've added some debug code to `paxos.Consensus()`...
```diff
diff --git a/ipam/paxos/paxos.go b/ipam/paxos/paxos.go
index fe10775..6f32398 100644
--- a/ipam/paxos/paxos.go
+++ b/ipam/paxos/paxos.go
@@ -1,6 +1,7 @@
 package paxos
 
 import (
+       "fmt"
        "github.com/weaveworks/mesh"
 )
 
@@ -249,6 +250,7 @@ func (node *Node) Consensus() (bool, AcceptedValue) {
                        count := counts[origin] + 1
                        counts[origin] = count
                        if count >= node.quorum {
+                               fmt.Printf("%s consensus, proposal by %s containing %d nodes\n", node.id.Name, claims.AcceptedVal.Origin.Proposer.Name, len(claims.AcceptedVal.Value))
                                return true, claims.AcceptedVal
                        }
                }
```
```
03:00:00:02:00:00 consensus, proposal by 04:00:00:02:00:00 containing 3 nodes
01:00:00:02:00:00 consensus, proposal by 02:00:00:02:00:00 containing 5 nodes
```

**Comment by rade** [comment]
btw, to reproduce this more quickly, set `secondpass = 0` in `TestAllocatorFuzz`.

**Comment by rade** [comment]
> I had some theory that `paxos.Consensus()` can be called when no quorum has been set, and erroneously creates a ring based on a proposal that has been accepted by just a single peer. But adding some debug output to `paxos.Consensus()` ruled that out.

Turns out I was exactly right! I hadn't noticed is that we initialise the paxos.quorum to 1 - I thought it was 0 - which is why my assertions didn't fire.

So I think the fix here is...

1. initialise paxos.quorum to 0
2. make `paxos.Consensus()` return false when the quorum is 0. In effect this means that only a node on which an allocation/claim/'consense' has been requested gets to initialise the ring. All others learn about the ring through gossip.

Making these changes gets the test to pass for me.

**Comment by bboreham** [comment]
I need to add `-cpu=2` to the `go test` command to see it fail on my machine.  Which seems odd, because apparently it ought to have used that number by default.

**Comment by bboreham** [comment]
> make paxos.Consensus() return false when the quorum is 0

I considered an alternative route, of calling `paxos.SetConsensus()` when an unsolicited proposal comes in.  

I concluded that your way is less dangerous, in that only nodes which actively want something from IPAM will need to compute a correct quorum.

**Comment by rade** [comment]
> I considered an alternative route, of calling `paxos.SetConsensus()` when an unsolicited proposal comes in. 

I think you mean `paxos.SetQuorum()`

> I concluded that your way is less dangerous, in that only nodes which actively want something from IPAM will need to compute a correct quorum.

Exactly, I considered the above and came to the same conclusion. The calculation of the quorum should only happen as the result of a user action, e.g. starting a container or running `weave consense`. Otherwise it is impossible for users to ensure that the quorum is correct.
