### ISSUE TITLE
"invalid character 'T' looking for beginning of value" in test setup with Docker 1.11.0

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2152]
I've seen the following a few times with docker 1.11.0-rc4

```
$ ./setup.sh 
Copying weave images, scripts, and certificates to hosts, and
  prefetch test images
08940f706be1: Loading layer 3.539 MB/19.66 MB
08940f706be1: Loading layer 15.34 MB/19.66 MB
08940f706be1: Loading layer 19.66 MB/19.66 MB
08940f706be1: Loading layer 19.66 MB/19.66 MB
08940f706be1: Loading layer 19.66 MB/19.66 MB
invalid character 'T' looking for beginning of value
```

**Comment by rade** [comment]
same with 1.11.0-rc5

**Comment by rade** [comment]
I removed all the weave images from the VMs and re-ran setup, and it all works fine. Several times. :(

**Comment by bboreham** [comment]
This is what the error looks like to `strace`:

````
[pid  9460] read(5, "HTTP/1.1 200 OK\r\nContent-Length: 167\r\nContent-Type: application/json\r\nDate: Tue, 12 Apr 2016 10:25:27 GMT\r\nServer: Docker/1.11.0-rc5 (linux)\r\n\r\nThe image weaveworks/weave:latest already exists, renaming the old one with ID sha256:8a1f2f5f008334b625425659bab9ebdd2ffaea7dae6821d57bf9e0c2e9ad0c69 to empty string\n", 4096) = 311
[pid  9460] write(2, "invalid character 'T' looking for beginning of value\n", 53invalid character 'T' looking for beginning of value
````

In other words the server is claiming to send json, but actually sends a text string, which doesn't parse as json.

**Comment by bboreham** [comment]
The comparable reply from Docker 1.10.3 is:

````
HTTP/1.1 200 OK
Server: Docker/1.10.3 (linux)
Date: Tue, 12 Apr 2016 10:29:53 GMT
Content-Length: 167
Content-Type: text/plain; charset=utf-8

The image weaveworks/weave:latest already exists, renaming the old one with ID sha256:3cb08e6d141a1545e066e4e3f4873e4869bc62752a01e8c4342176ac252dcaca to empty string
````

**Comment by bboreham** [comment]
Reported to Docker at https://github.com/docker/docker/issues/21957

**Comment by bboreham** [comment]
Fixed in https://github.com/docker/docker/pull/21959

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oWjqRu

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>VtoeSX

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>r60qwn

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oVHpLi

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>DLrnCH

**Comment by dody200411** [comment]
'"><div rNnTRbt=roann>yonYwA

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>mNNmFP

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1XLRS3

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1cT1Gh

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>nt0rrq

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>MekE9r

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>8SjGIc

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>fbenM4

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>jJNfh0

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oPDjtc

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lqw1JK

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>p4eV8N

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>FzCAe6

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>gUeyz0

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>wDrTZq

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>cgoXGZ

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>BQ8Aby

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>kLnQD3

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>I1WuBE

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>TaMgZM

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>09NSTa

**Comment by dody200411** [comment]
'"></script><div rNnTRbt=roann>SjJZfc

**Comment by dody200411** [comment]
'" rNnTRbt="roannATTR" x=yP2JRD0

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>mSqNkv

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>nMi4ke

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>9JntUT

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>q9W8pI

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>XcpKP0

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oVnJhk

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>BbRAFp

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>PWqRMv

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Nl1E7C

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>nz2gqD

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>HdE2zy

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>xM5Wyl

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>cbwQrj

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1VOuzi
