### ISSUE TITLE
Docker DNS overrides WeaveDNS and fails to correctly reverse resolve container's IP address

### ISSUE THREAD

**Issue by amarouni** [weaveworks/weave#2157]
Using Docker 1.10.3 :
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
```
and the latest version of weave : 
```
        Version: 1.4.6

        Service: router
       Protocol: weave 1..2
           Name: 3e:57:c8:85:32:58(e6430)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 0
    Connections: 0
          Peers: 1
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 10.2.1.0-10.2.1.255
  DefaultSubnet: 10.2.1.0/24

        Service: dns
         Domain: weave.local.
       Upstream: 127.0.1.1
            TTL: 1
        Entries: 4

        Service: plugin
     DriverName: weave
```

I'm starting the following simple docker-compose : 
```
networks:
  weave:
    external:
      name: weave
services:
  mongodb:
    dns: 172.17.0.1
    dns_search: weave.local.
    entrypoint:
    - /nonsecure-entrypoint.sh
    hostname: mongodb.weave.local
    image: enterprisemongo:3.03
    networks:
    - weave
version: '2'
```
From inside the running container I have the following :
```
root@mongodb:/# ifconfig -a
eth1      Link encap:Ethernet  HWaddr 02:42:ac:12:00:02  
          inet addr:172.18.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1682 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1510 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4181395 (4.1 MB)  TX bytes:115737 (115.7 KB)

ethwe0    Link encap:Ethernet  HWaddr 06:1e:c2:38:7e:ff  
          inet addr:10.2.1.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::41e:c2ff:fe38:7eff/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:429 errors:0 dropped:0 overruns:0 frame:0
          TX packets:429 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10718526 (10.7 MB)  TX bytes:10718526 (10.7 MB)
```

```
root@mongodb:/# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.2.1.1	mongodb.weave.local mongodb
172.18.0.2	mongodb.weave.local mongodb
```

```
root@mongodb:/# cat /etc/resolv.conf 
search weave.local.
nameserver 127.0.0.11
options ndots:0
```

Now, when I try to do a reverse DNS on the 10.2.1.1 address : 
```
root@mongodb:/# dig -x 10.2.1.1      

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> -x 10.2.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37756
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;1.1.2.10.in-addr.arpa.		IN	PTR

;; ANSWER SECTION:
1.1.2.10.in-addr.arpa.	1800	IN	PTR	mongodb_1.weave.

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Wed Apr 13 07:22:56 UTC 2016
;; MSG SIZE  rcvd: 100

```
**I'm getting back the container's name mongodb_1.weave. instead of mongodb.weave.local**
This issue breaks Kerberos which relies on reverse DNS resolution.

Also :
```
09:19 $ weave status dns
host         10.2.1.254      weave:expose 3e:57:c8:85:32:58
mongodb      10.2.1.1        3c5ba2b92166 3e:57:c8:85:32:58
scope        10.2.1.254      1f64e423084b 3e:57:c8:85:32:58
scope        10.42.20.134    1f64e423084b 3e:57:c8:85:32:58
scope        10.42.30.49     1f64e423084b 3e:57:c8:85:32:58
```

**Comment by rade** [comment]
The answer is coming from Docker's DNS, not weaveDNS.

Docker's DNS cannot be disabled, ....unless you run without Docker networking. See https://github.com/weaveworks/guides/issues/178 for how to do that, e.g. your compose file would end up looking something like...

```
version: '2'

services:
  mongodb:
    entrypoint: /nonsecure-entrypoint.sh
    container_name: mongodb
    image: enterprisemongo:3.03
    network_mode: bridge
```

**Comment by bboreham** [comment]
I suspect you can work around this by naming the Docker network "weave.local" and naming your containers.

@amarouni could you try 

    docker network create --driver=weavemesh --ipam-driver=weavemesh weave.local

then in the compose file change the network to `weave.local` and add lines like:

    container_name: mongodb

This way, Docker's DNS should hold names that match the names you want.

**Comment by amarouni** [comment]
@rade Can we still use the weavemesh network ? You can specify either network_mode or network.

What's weird is that we're specifying ```dns: 172.17.0.1``` so that containers use the weaveDNS instead of the DockerDNS but we keep getting the following in resolv.conf :
```
root@mongodb:/# cat /etc/resolv.conf 
search weave.local.
nameserver 127.0.0.11
options ndots:0
```

any idea ??

**Comment by bboreham** [comment]
The 127.0.0.11 address is Docker interposing its DNS server in front of the one you asked for (i.e. ours).  Some discussion at https://github.com/docker/docker/issues/19474.

**Comment by rade** [comment]
> What's weird is that we're specifying `dns: 172.17.0.1` so that containers use the weaveDNS instead of the DockerDNS but we keep getting the following in resolv.conf

yes, that is just how docker dns works. you cannot replace it. It *always* inserts itself first in the chain. So in this case it will in turn to talk to weaveDNS if it cannot resolve something, but since it *can* resolve the IP that won't happen.

**Comment by bboreham** [comment]
On the other point, I believe @rade is suggesting to use the Weave proxy instead of the plugin.

This is what happens when you run the `eval $(weave env)` part before calling `docker-compose`.  Then you get the same network as you would with `weavemesh`, but without Docker being involved in setting it up, interposing a DNS listener, etc.

**Comment by rade** [comment]
We've switched to the compose v2 syntax in weaveworks/guides#178, and are going to make further improvements in weaveworks/guides#187. I don't think there is anything further to do here.

**Comment by bboreham** [comment]
The Docker DNS overriding behaviour is said to be fixed in Docker 1.13. 
Via https://github.com/docker/docker/pull/29891

**Comment by ftom** [comment]
Nice ! looking forward to it.

**Comment by olegabr** [comment]
I' m using weave with nginx/openresty/lua. In order to make lua code connect to the database from another container, I've added this line to `nginx.conf` file:

```
resolver 172.17.0.1;
```

then I can specify database in Lua code like this:

```Lua
host = "db.weave.local"
```

the question is is it safe to use the `172.17.0.1` for resolver? is this IP stable, or I should obtain it with some command and inject to my nginx config?

**Comment by bboreham** [comment]
@olegabr please open a new issue; your question has nothing to do with this one.

Basically, Docker picks that address; it should be fairly stable but we cannot govern what they do.
See also #1770
