### ISSUE TITLE
"How it works" doc states that we always use pcap

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2159]
At the time of writing, the doc is at http://docs.weave.works/weave/latest_release/how-it-works.html

It seems to have moved to https://github.com/weaveworks/weave/blob/master/site/router-topology.md

Should be updated.

**Comment by rade** [comment]
isn't this a dup of #1908?

**Comment by bboreham** [comment]
Arguably the re-org addresses the "we don't mention fdp" part; updating the statement that we use pcap is not covered by #1908.
