### ISSUE TITLE
Design notes for WeaveDNS in the public build

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#2167]
I thought that we were leaving this document in github and not putting it on the website: 

https://github.com/weaveworks/weave/blob/master/docs/weavedns-design.md

It's appearing underneath Using WeaveDNS, and has two titles, so if we do want to include it, then it should be reformatted.

**Comment by bboreham** [comment]
The problem file is https://github.com/weaveworks/weave/blob/master/site/weavedns/weavedns-design.md

**Comment by awh** [comment]
I intend to use this as a test case for proving the wordepress/circleci integration - fix coming soon. In the meantime I manually removed the offending page from the published docs via the wordpress admin UI.

**Comment by awh** [comment]
Fixed by #2212.
