### ISSUE TITLE
cannot ping 2 containers y 2 different hosts RHEL7.3 WEAVE 1.4.6 DOCKER 1.9

### ISSUE THREAD

**Issue by joserivca** [weaveworks/weave#2179]
hello there !
im using red hat 7.3 
docker 1.9
weave 1.4.6

i follow the tutorial but i cant ping the pinger with the pingme
when i do weave status dns and nothing appears

i send my status by server

**Host 1**
sudo /database/weave/weave status

        Version: 1.4.6

        Service: router
       Protocol: weave 1..2
           Name: 92:e8:bb:13:32:78(pmbrklnxd01)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 0
    Connections: 1 (1 established)
          Peers: 2 (with 2 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 10.32.0.0-10.47.255.255
  DefaultSubnet: 10.32.0.0/12

        Service: dns
         Domain: weave.local.
       Upstream: 130.1.40.10, 131.1.20.41
            TTL: 1
        Entries: 0

        Service: proxy
        Address: unix:///var/run/weave/weave.sock

Host 2
[S56490@pmbrklnxd02 ~]$ sudo /database/weave/weave status

        Version: 1.4.6

        Service: router
       Protocol: weave 1..2
           Name: e6:54:37:ee:1a:c5(pmbrklnxd02)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 1
    Connections: 1 (1 established)
          Peers: 2 (with 2 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 10.32.0.0-10.47.255.255
  DefaultSubnet: 10.32.0.0/12

        Service: dns
         Domain: weave.local.
       Upstream: 130.1.40.10, 131.1.20.41
            TTL: 1
        Entries: 0

        Service: proxy
        Address: unix:///var/run/weave/weave.sock

        Service: plugin
     DriverName: weave

[S56490@pmbrklnxd02 ~]$ sudo /database/weave/weave status dns
[S56490@pmbrklnxd02 ~]$
[S56490@pmbrklnxd02 ~]$ sudo /database/weave/weave status dns
[S56490@pmbrklnxd02 ~]$ sudo /database/weave/weave status connections
-> 10.80.197.58:6783     established fastdp 92:e8:bb:13:32:78(pmbrklnxd01)
[S56490@pmbrklnxd02 ~]$

[S56490@pmbrklnxd02 ~]$ sudo /database/weave/weave status peers
e6:54:37:ee:1a:c5(pmbrklnxd02)
   -> 10.80.197.58:6783     92:e8:bb:13:32:78(pmbrklnxd01)        established
92:e8:bb:13:32:78(pmbrklnxd01)
   <- 10.80.132.244:58264   e6:54:37:ee:1a:c5(pmbrklnxd02)        established
[S56490@pmbrklnxd02 ~]$

please help me

**Comment by rade** [comment]
what does `weave ps` say?

**Comment by joserivca** [comment]
[S56490@pmbrklnxd01 ~]$ sudo /database/weave/weave ps
weave:expose 92:e8:bb:13:32:78 10.32.0.1/12
[S56490@pmbrklnxd01 ~]$ 

[S56490@pmbrklnxd02 ~]$ sudo /database/weave/weave ps
weave:expose e6:54:37:ee:1a:c5
[S56490@pmbrklnxd02 ~]$

**Comment by joserivca** [comment]
i ve tried in Centos 7 works perfect but in RHEL 7 not working!

**Comment by rade** [comment]
Please post a complete transcript, i.e. everything from `weave launch` to the failed ping.

**Comment by joserivca** [comment]
i did the same stuff from the tutorial, 
HOST 1
 sudo /database/weave/weave launch
 eval $(sudo /database/weave/weave env)
HOST 2
sudo /database/weave/weave launch 10.80.197.58
eval $(sudo /database/weave/weave env)
host 1
sudo docker run -d --name=pingme \
        gliderlabs/alpine nc -p 4000 -ll -e echo 'Hello, Weave!'
host 2
sudo docker run --name=pinger2 -ti \
        gliderlabs/alpine sh -l

ping -c1 pingme

i did the same in centos and its works but rhel 7 is my problem! something can be with rhell 7?

**Comment by rade** [comment]
There are no sudos in our tutorial.

Try running the example from inside `sudo -s`.

**Comment by rade** [comment]
btw, note the warning at https://github.com/weaveworks/weave#example:

> run the above and all subsequent commands in a *single* root shell (e.g. one created with `sudo -s`). Do *not* prefix individual commands with `sudo`, since some commands modify environment entries and hence they all need to be executed from the same shell.

**Comment by joserivca** [comment]
so, i can execute if i dont root user?, cannot execute a user can do sudo?

**Comment by rade** [comment]
sorry, I don't understand the question. Running the example from a `sudo -s` shell should work just fine.

**Comment by joserivca** [comment]
dude im sorry for my bad english! and my low skills in linux! LOL, Thanks really so much!
