### ISSUE TITLE
doc structure is illogical

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2183]
The top level doc structure is illogical, and contains a few other niggles. Here it is
```
    Introducing Weave Net
    Weave Features
    Installing Weave Net
    Operational Guide
    Using Weave Net – Example
    IP Addresses, Routes and Networks
    Setting Up The Weave Net Docker API Proxy
    Using Fast Datapath
    Using the Weave Net Docker Network Plugin
    Encryption and Weave Net
    How Weave Net Works
    Address Allocation with IP Address Management (IPAM)
    Using WeaveDNS
    Using Weave with Systemd
    Weave Net FAQ
    Troubleshooting Weave Net
    Building Weave Net
```
Issues:
- `Introducing Weave Net` should just be `Introduction`
- `Weave Features` should just be `Features`
- `Installing Weave Net` should just be `Installation`
- `Operational Guide` should be `Operation`
- `Using Weave Net - Example` should be just `Using Weave Net`
- `IP Addresses, Routes and Networks` does not belong at the top level; not sure where it should go; perhaps the Ops Guide or How It Works
- `Using Fast Datapath` should not be at the top level; not sure where it should go; perhaps the Ops Guide
- `Setting Up the Weave Net Docker API Proxy` should just be `Docker API Proxy`
- `Using the Weave net Docker Nework Plugin` should just be `Docker Network Plugin`
- `Encryption and Weave Net` should just be `Encryption` and it should not be at the top level; not sure where it should go; perhaps the Ops Guide
- `How Weave Net Works` should come later
- `Address Allocation with IP Address Management (IPAM)` should just be `IP Address Allocation`
- `Using WeaveDNS` should be `Naming and Discovery`
- `Using Weave with Systemd` does not belong at the top level; Ops Guide is probably the right place for it
- `Weave Net FAQ` should just be `FAQ`
- `Troubleshooting Weave Net` should just be `Troubleshooting`

So, with all the above changes applied, here's how the top level would look like
```
    Introduction
    Features
    Installation
    Operation
    Using Weave Net
    Docker API Proxy
    Docker Network Plugin
    IP Address Allocation
    Naming and Discovery
    How Weave Net Works
    FAQ
    Troubleshooting
    Building Weave Net
```

**Comment by abuehrle** [comment]
Convention for titles is to be action orientated, hence the change: 

http://writers.stackexchange.com/questions/1545/verb-tense-for-technical-document-titles

**Comment by rade** [comment]
> Convention for titles is to be action orientated

Ok, but a) 7 of the 17 titles weren't like that, and b) it looks really clumsy to have a whole bunch of "Using ..." titles.

**Comment by abuehrle** [comment]
This is a bit late to be talking about this now, i.e. two days before the release.  Change it, then.

**Comment by bboreham** [comment]
Is this a mis-match between what the menu should say and what the doc titles should say?

When you're looking at a "Weave Net" page, it's obvious what the "FAQ" is about, but once you navigate to that page you need the full context.

**Comment by rade** [comment]
The pages still have the Menu at the left, so I think context is fairly obvious. Though I've just noticed that it says "Net 1.5 Documentation" instead of "Weave Net 1.5 Documentation".

**Comment by abuehrle** [comment]
This is all fine, but I wished you had looked at that extensive planning document that I did about four months ago when I began this, and commented on that before we started re-jigging the entire structure  two days before a release.

**Comment by rade** [comment]
Action-oriented titles for all but one...
```
    Introducing Weave Net
    Exploring Weave Net Features
    Installing Weave Net
    Operating Weave Net
    Using Weave Net
    Integrating with Docker through the Docker API Proxy
    Integrating with Docker through the Docker Network Plugin
    Allocating IP Addresses
    Naming and Discovering Containers and Services
    Understanding how Weave Net Works
    FAQ
    Troubleshooting Weave Net
    Building Weave Net
```
(far too many `Weave Net`s in that for my liking, but at least there is only one "Using")

**Comment by abuehrle** [comment]
That looks good.  I think you have a long technical writing career ahead of you   :+1: 

(Agree there are too many 'Using'.)   I think those Integrating titles might be a bit long, and won't look great in the menu, so perhaps we could shorten those a bit.  Keep in mind that changing the titles will change URLs, so we'll have to fix the links again.

**Comment by rade** [comment]
> (Agree there are too many 'Using'.)

I think you mean 'Weave Net', of which, sadly, there are eight; there is only one 'Using' left.

> those Integrating titles might be a bit long, and won't look great in the menu, so perhaps we could shorten those a bit.

Done

> Keep in mind that changing the titles will change URLs, so we'll have to fix the links again. 

That is not the case. URLs are based on the file/directory names, not the titles.

**Comment by abuehrle** [comment]
For SEO reasons, it's good to have the product name in your titles, but I see your point.  

In Wordpress, the urls are based on the titles of the doc, but yes, we're doing it differently with the plugin by transforming .md file names to a URL. 

And personally I'm not sure that "naming and discovery" is something a user is going to search on with regards to Weave. 

They will search for 'WeaveDNS' or "weave and DNS", so what's the problem with calling the feature what it is? That was one of the things I was trying to achieve. Same with IPAM, it's a thing that people know and understand, so I don't understand the rationale in shrouding it in an euphemism.

**Comment by rade** [comment]
> They will search for 'WeaveDNS' or "weave and DNS"

They will only do that if they know something about Weave already. DNS is just one of many ways to do service discovery. So "naming and discovery" is what you want to do, and "weaveDNS" is the component in weave that deals with it, but there is no for you to know that unless you *already* know about weaveDNS.

> Same with IPAM, it's a thing that people know and understand

It's a very obscure term, actually.

We could have something like
```
    Allocating IP Addresses with IPAM
    Naming and Discovering Containers and Services with weaveDNS
```
but a) that is rather long, and b) IMO it just adds jargon that will confuse novices.

**Comment by abuehrle** [comment]
How about "Naming and Discovery with WeaveDNS"?  It's implied that we are talking about containers and services. 

And then, "Address allocation with IP Address Management (IPAM)"  <--- this is still an active sentence which is what we're going for here.

**Comment by abuehrle** [comment]
>They will only do that if they know something about Weave already. DNS is just one of many ways to       do service discovery. 

What other methods are there besides DNS to discover services?

**Comment by rade** [comment]
> How about "Naming and Discovery with WeaveDNS"? It's implied that we are talking about containers and services.

No, it is not implied. We could be talking about peers, for example.

Also, the above is not "active".

>  "Address allocation with IP Address Management (IPAM)" <--- this is still an active sentence which is what we're going for here. 

I don't see how that is "active", based on the definition you linked to earlier. And the duplication of "Address" is awkward.

As I said, "IPAM" is jargon. So much so that went out of our way to not mention it in commands/options (e.g. we have `--ipalloc-init` not `--ipam-init`). I see no benefit in referring to it in the heading. In fact I would be happy if *none* of our docs mentioned it.

> I don't think it's entirely necessary to say, "Exploring Weave Net Features", since there isn't anything that the user needs to do

True. That is also the case for "Introducing Weave Net" - it is not the reader that is doing the introducing.

> "Feature Overview" is ok in this instance. 

That is not active. Anyway...

```
    Introducing Weave Net
    Feature Overview
    Installing Weave Net
    Operating Weave Net
    Using Weave Net
    Integrating Docker via the API Proxy
    Integrating Docker via the Network Plugin
    Allocating IP Addresses
    Naming and Discovering Containers and Services
    Understanding how Weave Net Works
    FAQ
    Troubleshooting Weave Net
    Building Weave Net
```

> What other methods are there besides DNS to discover services? 

- Links and injecting environment variables; which is what Docker used to do.
- Service registries based on the likes of etcd or consul; there are plenty of articles extolling the virtues of that.
