### ISSUE TITLE
weave dns-args missing equal sign after --dns

### ISSUE THREAD

**Issue by modia** [weaveworks/weave#2197]
In weave 1.5.0 running on Ubuntu 14.04 the command weave dns-args returns:

--dns 172.17.0.1 --dns-search=weave.local.
but docker run 1.11.0 expects: --dns=[]
the equal sign is missing.

**Comment by bboreham** [comment]
I'd agree it's inconsistent, but generally Docker will accept either form.  

Did you get an error message?

**Comment by modia** [comment]
I got an error message but I'm unable to reproduce it.
