### ISSUE TITLE
Documentation section about MTU configuration is missing

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#2198]
```
Ensure that WEAVE_MTU fits with the MTU of the intermediate network (see below)
```

There's nothing below.

**Comment by bboreham** [comment]
@anita it looks like you added this line in bdc9eae000748776aaf25e87f68a7a61c36a2ca0 - can you say what it was supposed to refer to?

**Comment by rade** [comment]
Well, as a minimum it should state that the WEAVE_MTU must be lower than the MTU on *any path* between peers. Bonus points for providing some hints on how to work that out.

**Comment by abuehrle** [comment]
think there was going to be a drawing there that didn't make it.  Anyway, that line shouldn't be there.

**Comment by bboreham** [comment]
> WEAVE_MTU must be lower than the MTU

as in, must be at least 50 bytes lower, for VXLAN overhead?

**Comment by rade** [comment]
> as in, must be at least 50 bytes lower, for VXLAN overhead?

Umm. That too. I was more thinking of the *whole path* requirement. It's not enough to look at interface MTUs at either end.
