### ISSUE TITLE
Is it possible to specify the route so that traffic can through internal network?

### ISSUE THREAD

**Issue by tangyouze** [weaveworks/weave#2201]
I have two machines M1, M2, M3

- M1 has a public IP address x.x.x.x, and an internal IP address 10.0.0.2
- M2 has a public IP address y.y.y.y, and an internal IP address 10.0.0.3
- M3 has a public IP address z.z.z.z, and is not in the same subnet with M1 and M2.

M1 and M2 are able to communicate with each other through 10.0.0.* and the public IP.

But the issue is that the bandwidth going though the public IP is limited, so I want the traffic  from M1 to M2 is through the internal network, i.e. 10.0.0.*

I start weave on M1 by
```
weave launch --init-peer-count 2
```
and on M2
```
weave launch --init-peer-count 3 x.x.x.x
```
and on M3
```
weave launch --init-peer-count 3 x.x.x.x
```

And I find that the communication between M1 and M2 is through the public IP, where the bandwidth is limited. May I know is it possible to configure the weave network so the traffic between M1 and M2 can go through internal network? 

Thanks.

**Comment by bboreham** [comment]
This has been discussed before, at #646.

There is a flag `--no-discovery` which restricts peers to using only the addresses they have explicitly been given.

Also (unrelated), please note the same `--init-peer-count` should be given to each peer.

**Comment by tangyouze** [comment]
Thanks bboreham, I'm now able to use --no-discovery to control the network topology.
