### ISSUE TITLE
IPAM hangs if persisted data does not match ipalloc-range

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2209]
To reproduce:

    $ weave reset
    $ weave launch --ipalloc-range 10.2.0.0/16
    $ weave prime
    $ weave stop
    $ weave launch --ipalloc-range 10.32.0.0/16
    $ weave run -ti alpine /bin/sh

It hangs because `Ring.ChoosePeersToAskForSpace()` returns nothing, so `allocate.Try()` does nothing; there is not even a diagnostic in the logs at debug level.

`weave status` says:

         Status: waiting for IP range grant from peers

**Comment by awh** [comment]
Fixed by #2249
