### ISSUE TITLE
odd syntax in docs on encryption

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2210]
We are currently referring user to generate the token with: `< /dev/urandom tr -dc A-Za-z0-9 | head -c9 ; echo`

Of course it's perfectly valid to specify stdin redirect at the start of the line, but it's not the kind of syntax people see very often. Is there any particular reason we have it written this way?

Also, `; echo` adds some extra confusion. I think something with sub-shell would look more readable, e.g.:
```
echo $(tr -dc A-Za-z0-9 < /dev/urandom | head -c9)
```
or actually this seems sufficient:
```
head -c9 /dev/urandom | base64
```

**Comment by rade** [comment]
> Is there any particular reason we have it written this way?

The data flows from left to right.

I got it from http://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/

>  sub-shell

Yuck.

> `head -c9 /dev/urandom | base64`

This does something slightly different, but I quite like it.
