### ISSUE TITLE
Link to CNI plugin doc is broken

### ISSUE THREAD

**Issue by MikeSpreitzer** [weaveworks/weave#2214]
https://github.com/weaveworks/weave/blob/master/plugin/README.md refers to https://github.com/weaveworks/weave/blob/master/site/plugin/cni-plugin-how-to.md --- and I get a 404 when I try to follow that link.

**Comment by abuehrle** [comment]
Thanks for this. We've been changing the docs around quite a bit. The file in github is here: 

https://github.com/weaveworks/weave/blob/master/site/cni-plugin.md

and you can also view it on the web here: 

https://www.weave.works/documentation/net-1-5-0-cni-plugin/

**Comment by rade** [comment]
I have changed the links in the README to point to the GH files, as a temporary workaround.
