### ISSUE TITLE
make it easier to debug CNI plugin calls

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2215]
It's fairly simple already, comparing to the Docker plugin, but we could make it somewhat better or at least document it.

I think the best option would be one that lets the user temporarily enable extra logging at runtime without having to restart.

**Comment by bboreham** [comment]
The way CNI plugins work is to start a process, do their work, and finish. By default the Weave CNI plugin runs as a shell script which runs a `--rm`-flagged Docker container, so there are no logs left at the end. We would need special extra features to send debug info to a running `weaveplugin` container.

An option to take off the `--rm` flag so you can look in the dead container's logs might be a good first step.

What about sending to `syslog` ?

**Comment by errordeveloper** [comment]
> An option to take off the `--rm` flag so you can look in the dead container's logs might be a good first step.

Yes, that's what I ended-up doing, as well as `env | grep CNI_`.
```
#!/bin/sh
(env | grep CNI_) > /tmp/weave_net
tee -a /tmp/weave_net | \
docker run --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -i \
 -e WEAVE_DEBUG=1 \
 -e CNI_VERSION -e CNI_COMMAND -e CNI_CONTAINERID -e CNI_NETNS \
 -e CNI_IFNAME -e CNI_ARGS -e CNI_PATH -v /etc/cni:/etc/cni -v /opt/cni:/opt/cni \
 weaveworks/plugin:1.5.0  --cni-net
```

> What about sending to `syslog`?

That sounds plausible. I'd suggest that `libcni` should do that too.
