### ISSUE TITLE
Docs: Link to "Weave Net Docker API Proxy" does not exist

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2216]
The link to [Weave Net Docker API Proxy](https://www.weave.works/documentation/net-1.5.0-weave-docker-api/net-1.5.0-set-up-proxy) is broken in https://www.weave.works/documentation/net-1-5-0-troubleshooting/

**Comment by awh** [comment]
I'm going to use this to test the CI integration once it is merged.

**Comment by awh** [comment]
Closed by #2221.
