### ISSUE TITLE
Test CNI plugin with rkt in CI

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2225]
This should fairly simple to implement and much quicker to test then Kubernetes.

I've got provisioning scripts in [weaveworks-guides/weave-net-docker-and-rkt](https://github.com/weaveworks-guides/weave-net-docker-and-rkt/tree/master/examples/google-compute-engine), which can be adapted.

**Comment by bboreham** [comment]
We do have https://github.com/weaveworks/weave/blob/master/test/830_cni_plugin_test.sh which tests at the pure CNI level.

I guess it would be nice to test with rkt as a parallel to _Docker_.
