### ISSUE TITLE
Weave giving "Unable to claim" error

### ISSUE THREAD

**Issue by alex-sherwin** [weaveworks/weave#2232]
This started to occur after upgrading to weave 1.5.0, launching two hosts like this:

```
CHECKPOINT_DISABLE=true weave launch --ipalloc-range 192.99.0.0/16 10.10.200.162 10.10.200.160
```

And then trying to launch a container in that range:

```
docker -H unix:///var/run/weave/weave.sock run -dt --hostname=mycontainer.weave.local -e WEAVE_CIDR=192.99.10.112/16 ubuntu bash
```

Causes an error:
```
docker: Error response from daemon: Unable to claim: 192.99.10.112/16 is in the range 192.99.0.0/16, but the allocator is not initialized yet.
```

**Comment by rade** [comment]
reproduced:
```
$ weave launch 192.168.0.2
$ docker $(weave config) run -e WEAVE_CIDR=10.32.1.1/24 -ti alpine /bin/sh
docker: Error response from daemon: Unable to claim: 10.32.1.1/24 is in the range 10.32.0.0/12, but the allocator is not initialized yet.
```

**Comment by bboreham** [comment]
@rade is `192.168.0.2` running Weave?  

If not, this is not a recent change: https://github.com/weaveworks/weave/commit/647b755b64bce7a48396395ae40405817bcac3bc#diff-d8d9198aa154e9723c9b1ecf5d6576c3R51

**Comment by rade** [comment]
no, it's not running anything.

**Comment by bboreham** [comment]
@rade then this is not really a repro, or at least what you did produced the expected behaviour that hasn't changed since version 1.1.

@alex-sherwin can you supply `docker logs weave` from the machine where you get the error please?

**Comment by rade** [comment]
> then this is not really a repro, or at least what you did produced the expected behaviour that hasn't changed since version 1.1.

wrong.

```
$ ./weave1.4.6 reset
$ ./weave1.4.6 launch 192.168.0.2
$ docker $(./weave1.4.6 config) run --rm -e WEAVE_CIDR=10.32.1.1/24 -ti alpine /bin/true
$ echo $?
0
$ ./weave1.4.6 reset
$ weave launch 192.168.0.2
$ docker $(weave config) run --rm -e WEAVE_CIDR=10.32.1.1/24 -ti alpine /bin/true
docker: Error response from daemon: Unable to claim: 10.32.1.1/24 is in the range 10.32.0.0/12, but the allocator is not initialized yet.
$ echo $?
125
```

**Comment by bboreham** [comment]
> wrong

Aha.  Perhaps a side-effect of #2096 

@alex-sherwin as you were; no need to supply logs.

**Comment by brb** [comment]
In both cases (v1.4.6 and v1.5.0), the claim request fails. However, the error is returned via cli only in the second case.

**Comment by rade** [comment]
No, the claim request does not fail (at least in 1.4.6) in the "failed to do what it is supposed to" sense; the container *does* end up with the requested IP address.

**Comment by brb** [comment]
Yes, you are right.

**Comment by rade** [comment]
@alex-sherwin Do *all* your containers get started with a pre-defined IP address supplied in WEAVE_CIDR? If so then you don't really need weave's IPAM and could disable it or at least set its allocation range s.t. it does not overlap with the range in which you are manually setting IPs.

**Comment by alex-sherwin** [comment]
@rade, I have leveraged IPAM for some containers but I don't need to.  I can work around by not using IPAM for now at least

**Comment by brb** [comment]
> Aha. Perhaps a side-effect of #2096

@bboreham Yep, you're right.
Prior to #2096, HTTP status code was ignored and therefore, the claim op is successful in the case of 1.4.6 (regardless of `PUT /ip/CONTAINER_ID/IP_ADDR` returning 400).
