### ISSUE TITLE
Docs say plugin can be launched with "--mesh-network-name", plugin says otherwise

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#2243]
From https://www.weave.works/documentation/net-1.5.0-plugin/net-1.5.0-plug-in-command-line/:

> --mesh-network-name=<name> — set <name> to blank to disable creation of a default network, or include a name of your own choice.

From reality:

```
Toms-MacBook-Pro:scope twilkie$ weave launch-plugin --log-level=debug --mesh-network-name=
...
Status: Downloaded newer image for weaveworks/plugin:1.5.0
66d7c3400e0ebf43b8be3f5d63f095312d356ce7178be61fcc5600ba1399072e
The weaveplugin container has died. Consult the container logs for further details.
Toms-MacBook-Pro:scope twilkie$ docker logs weaveplugin
flag provided but not defined: -mesh-network-name
Usage of /home/weave/plugin:
  -cni-ipam
    	act as a CNI IPAM plugin
  -cni-net
    	act as a CNI network plugin
  -log-level string
    	logging level (debug, info, warning, error) (default "info")
  -meshsocket string
    	socket on which to listen in mesh mode (default "/run/docker/plugins/weavemesh.sock")
  -no-multicast-route
    	do not add a multicast route to network endpoints
  -socket string
    	socket on which to listen (default "/run/docker/plugins/weave.sock")
  -version
    	print version and exit
```

**Comment by tomwilkie** [comment]
See https://groups.google.com/a/weave.works/forum/#!topic/weave-users/92CjMkE0Ov0 and https://weaveworks.slack.com/archives/scope-public/p1461954486000088 for user confusion.

**Comment by bboreham** [comment]
I fixed the worst of it in 393fa3a333ab44e8ae86208342fe349b99a987a6

**Comment by bboreham** [comment]
I think the page should perhaps point up to the higher level so a beginner who starts at that page can find the more useful instructions.  Thoughts @abuehrle ?

**Comment by abuehrle** [comment]
Yes, agreed. I think that's the way it was before.  Usually, I like to read about how it works before diving in, since it gives me an overview of what's happening.  

I wonder if in this case we should include the command line arguments as a section on the "Integrating Docker via the Network Plugin"  It does seem a bit disjointed as a standalone file, since we explain how to launch it in a different file. I think those instructions belong with the other file.

**Comment by MikeSpreitzer** [comment]
@bboreham: Do you mean https://www.weave.works/documentation/net-1-5-0-plugin/ as the higher level at which to start?  I see it just says I should `weave launch`.  I want the router and the plugin but not the proxy.  Is `weave launch` really the right way to get that?

**Comment by bboreham** [comment]
@mikespreitzer yes, that's the page I meant. 

The two lines at the top of https://www.weave.works/documentation/net-1-5-0-plugin/net-1-5-0-plug-in-command-line/ will get you what you asked for. The only required arguments are the peer host(s) on `weave launch-router`

However, I'm not aware of any particular problem with running the proxy and not using it; unless you set `DOCKER_HOST` it will just sit there quietly.
