### ISSUE TITLE
AAAA query returns NXDOMAIN instead of NOERROR+NODATA

### ISSUE THREAD

**Issue by ogni90** [weaveworks/weave#2244]
As this [article](http://www.blackmoreops.com/2014/10/29/ipv6-issues-localized-denial-of-service-caused-by-incorrect-nxdomain-responses-from-aaaa-queries/) points out pretty good it's a bad idea to reply to a AAAA Request with NXDOMAIN (RCODE 3) like requested and implemented in #588. Instead a NOERROR (RCODE 0) should be delivered. The NXDOMAIN will be cached by a lot of DNS Servers and then also be delivered in case of an A request.

In my case I use a Windows DNS Server with a delegation to resolve my weave DNS names. At some point it caches the NXDOMAIN of the AAAA record and stops resolving the Domain Name of my conainer properly. The behavior described above can be reproduced:

At first I ask my local DNS server for an A record for one of my containers

> dig demo-wl-integ.auto.xxxx.de
> 
> ; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> demo-wl-integ.auto.xxxx.de
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23292
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4000
> ;; QUESTION SECTION:
> ;demo-wl-integ.auto.xxxx.de.   IN      A
> 
> ;; ANSWER SECTION:
> demo-wl-integ.auto.xxxx.de. 0  IN      A       10.40.13.8
> 
> ;; Query time: 1 msec
> ;; SERVER: 10.40.9.1#53(10.40.9.1)
> ;; WHEN: Mon May 02 11:49:56 CEST 2016
> ;; MSG SIZE  rcvd: 72

The result is OK and as it should be.

Then I ask for a AAAA Record:

> dig AAAA demo-wl-integ.auto.xxxx.de
> 
> ; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> AAAA demo-wl-integ.auto.xxxx.de
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56022
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4000
> ;; QUESTION SECTION:
> ;demo-wl-integ.auto.xxxx.de.   IN      AAAA
> 
> ;; Query time: 1 msec
> ;; SERVER: 10.40.9.1#53(10.40.9.1)
> ;; WHEN: Mon May 02 11:50:23 CEST 2016
> ;; MSG SIZE  rcvd: 56

I get NXDOMAIN as an answer.

Then I ask again for the A record:

> dig demo-wl-integ.auto.xxxx.de              
> 
> ; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> demo-wl-integ.auto.xxxx.de
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 60409
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4000
> ;; QUESTION SECTION:
> ;demo-wl-integ.auto.xxxx.de.   IN      A
> 
> ;; Query time: 0 msec
> ;; SERVER: 10.40.9.1#53(10.40.9.1)
> ;; WHEN: Mon May 02 11:51:01 CEST 2016
> ;; MSG SIZE  rcvd: 56

Now this request returns NXDOMAIN as well.

---------------
**Addition:**

Example for what a correct response for a non-existent AAAA record looks like if an A record actually exists:

> 
> dig AAAA witz.de
> 
> ; <<>> DiG 9.9.5-9+deb8u6-Debian <<>> AAAA witz.de
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58682
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4000
> ;; QUESTION SECTION:
> ;witz.de.                       IN      AAAA
> 
> ;; AUTHORITY SECTION:
> witz.de.                0       IN      SOA     ns1.parklogic.com. hostmaster.witz.de. 2016041700 16384 2048 1048576 2560
> 
> ;; Query time: 123 msec
> ;; SERVER: 10.40.9.1#53(10.40.9.1)
> ;; WHEN: Mon May 02 15:25:51 CEST 2016
> ;; MSG SIZE  rcvd: 100

**Comment by rade** [comment]
Relevant RFCs:

[rfc4047](https://tools.ietf.org/html/rfc4074)
> Suppose that an authoritative server has an A RR but has no AAAA RR for a host name.  Then, the server should return a response to a query for an AAAA RR of the name with the response code (RCODE) being 0 (indicating no error) and with an empty answer section

[rfc6147](http://tools.ietf.org/html/rfc6147#section-5.1.2)
> some servers respond with RCODE=3 to a AAAA query even if there is an A record available for that owner name.  Those servers are in clear violation of the meaning of RCODE 3

**Comment by timcharper** [comment]
I just tracked down poorly behaving DNS queries where processes were simultaneously querying A and AAAA, and the incorrect AAAA winning the race was causing the lookup host failure.

Glad to see this fixed!

**Comment by bboreham** [comment]
Note we just released version 1.5.1 with this fix included.

**Comment by timcharper** [comment]
Thank you!
