### ISSUE TITLE
[dns] caching for local domain

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#225]
At present, weavedns first attempts to resolve names against the records from local containers. If that fails then it asks other peers and returns the first answer. This has some significant shortcomings...

1. every query for a name that belongs to a remote container requires a broadcast, network round trip, which introduces latency and increases network and CPU load, and doesn't scale.

2. the same occurs for a name that doesn't resolve at all

3. if the name is recorded more than once, we are entirely at the mercy of underlying network conditions etc, as to what answer we return, or even if we return an answer at all

The obvious solution is to introduce caching.

In its most basic form a dns peer would:

- remember all answers returned from a broadcast query, including their ttls
- if no answers are returned (based on some timeout), remember that too, again with a ttl
- expire entries based on their ttl
- answer queries from the cache if possible

The shortcomings of this basic approach are principally around the danger of returning stale entries vs achieving good performance and scalability. Still, I reckon it's good enough for starters, and even with a short ttl an improvement over the present situation.

**Comment by rade** [comment]
One possible model is to use a mixture of push & pull. Essentially we take the pull+cache approach from #429 and add a mechanism by which peers a) monitor each other, and b) inform each other when names that have been queried have disappeared. The former would remove entries from the cache when the peer on which the associated containers reside disappears. The latter would remove entries from the cache for containers that have stopped. The latter could use s.t. like a bloom filter for compactly recording which names have been asked for by which peers, so that we don't end up in effect broadcasting container lifecycle events to all peers.

With that in place we can increase the TTL significantly. Except we can't...

We'd also need to find a way to flush cache entries when new name associations are created, e.g. when containers are started.

So perhaps the thing to do is to gossip the information about which peer is interested in which names.

**Comment by inercia** [comment]
So what do you think about this?

* when a WeaveDNS instance _X_ receives a mDNS query from _Y_ for a local name `name1`, it answers the query with a 30s TTL, and registers this information as (eg, _"Y is an observer of name1"_). It could be useful to also register the TTL sent to _Y_  (eg, _"Y is an observer of name1 and it will not ask us again before now+30s"_)
* when `name1` disappears, _X_ will update its local cache and send an update to _Y_ (and any other observers) about that name being removed (maybe with a DNS `UPDATE` message #265 ??). If the TTL was registered and that answer was too long ago, _X_ will skip this message as the answer cached at _Y_ is too old anyway, so it will need to ask _X_...

**Comment by inercia** [comment]
What do you mean when you say _"flush cache entries when new name associations are created, e.g. when containers are started"_. A new local cache entry will be created/overwritten through the HTTP API when a container is started, so...

**Comment by rade** [comment]
> So what do you think about this?

Yep, that's roughly what I was describing :) With the potential optimisation of using a bloom filter to record the information about which peer asked for which name - on the grounds that it is ok to have a small % of false positives.

> What do you mean when you say _"flush cache entries when new name associations are created, e.g. when containers are started"_. A new local cache entry will be created/overwritten through the HTTP API when a container is started, so...

The issue is caching on other peers. If a container on host X has asked for name A, and has a cached answer for that, then when a new container is started on host Y that registers name A, then we want to update/invalidate the cached entry on X.

**Comment by inercia** [comment]
So if a mapping in X exists for that name, `X["A"] -> Z`, and `Y` registers that name, you are saying that `Y` should broadcast the new mapping `X["A"] -> Y` (equivalent to the _please remove `X["A"]`_ but with added information), but would be using a _push model_ then, with the _all peers broadcasting all mappings_ problem, right? Wouldn't it be better to stick to relatively short TTLs and let peers ask for `X["A"]` when they are asked by a client?

**Comment by rade** [comment]
> Wouldn't it be better to stick to relatively short TTLs and let peers ask for X["A"] when they are asked by a client?

The whole point of doing something more complicated is to be able to use a longer TTL. The shorter the ttl the more DNS traffic there is on the network.

> We would be using a push model then, with the all peers broadcasting all mappings problem

Peers can just broadcast "I am interested in name A" when resolving A and the cache misses. In fact this is what happens now; the mdns broadcast contains just that information. But we need more than that:

- recipient peers should remember that association, so that they can subsequently inform interested peers when a name is added/removed locally

- the "I am interested in name A" information needs to be transmitted more reliably; gossip communication between peers can take care of that.

- new peers need a way of obtaining the "I am interested in name A" map from all existing peers; gossip communication can take care of that.

- cache entries need to be removed/invalidated when peers disappear.

All of this is very similar to what we are doing in #390 for communicating IP reservations between peers.

**Comment by inercia** [comment]
> The whole point of doing something more complicated is to be able to use a longer TTL. The shorter the ttl the more DNS traffic there is on the network.

Obviously we want to increase the TTL, but I think we both agree that mDNS is a clearly limited solution and we must use short TTLs until we have a better solution...

> All of this is very similar to what we are doing in #390 for communicating IP reservations between peers.

That would be a nice change but it would involve a lot of work, and I'm a bit concerned about this extra communication step between WeaveDNS and the router, but it can be done...

**Comment by inercia** [comment]
@squaremo "caching" to "cache local RRs"? why only the local RRs? don't we want to cache replies obtained recursively?

**Comment by squaremo** [comment]
> "caching" to "cache local RRs"? why only the local RRs?

Because that's what the issue actually describes and the subsequent comments discuss.
(By local I mean "in .weave.local" of course)

**Comment by inercia** [comment]
Maybe we could create another issue for moving WeaveDNS to gossip communications, then we could start discussing how to do it... (and @rade would probably be the right person for filling the issue).

**Comment by rade** [comment]
We could, but that is quite a long way down the road. And gossiping is an implementation detail - issues should describe features/problems.

**Comment by rade** [comment]
@alvaro I think this is resolved by #429 provided there is some clarification on the following part of this issue's description: "In its most basic form a dns peer would:   remember all answers returned from a broadcast query, including their ttls". We are not doing that, are we? i.e. if we get responses from multiple servers, the cache entries get overwritten, so we only keep the response from one server.

 I am ok with that, but please point out (and if necessary create) the issues were that is addressed. #226 is a possible candidate, but looks quite broad.

**Comment by inercia** [comment]
@rade Current implementation does not cache _all_ responses it gets from the network, but only the first one. When WeaveDNS is asked about a local name it will

1) send a mDNS query and wait for up to 500ms for an answer
2) get the first answer
3) store that answer in the cache and
4) return that answer to the client

Following answers to the mDNS query will be simply ignored. The answer will be always cached for 30 seconds (we are currently using a hardcoded TTL for local answers). So we are caching the response from the fastest peer...

Multiple responses from peers will be processed and remembered when #338 is addressed (I'm working on that) (and, as a side effect, we will have an initial solution for #226).

**Comment by rade** [comment]
ok. #338 is about a *single* peer returning multiple responses, i.e. when there are multiple containers with the same name on that peer.

**Comment by rade** [comment]
Closed by #429.
