### ISSUE TITLE
Plugin silent on unsupported option(s)

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2251]
Repro:

    docker network create --driver=weave --subnet=172.19.0.0/16 --gateway=172.19.0.1 mynet

`--gateway` is not supported by the Weave plugin, but it doesn't tell anyone at this point.

**Comment by bboreham** [comment]
It looks to me as if Docker always supplies a gateway address at network creation; if you don't put one explicitly on the command line then it will ask IPAM for one:

    $ docker network create --driver=weavemesh --subnet=172.19.0.0/16 --gateway=172.19.0.1 mynet

    DEBU: 2016/05/04 13:48:16.619539 [net] CreateNetwork &{NetworkID:c2141f827e7bf927678007b44800da87c7c0b8ad9829d1be956c94676a8a3fd9 Options:map[com.docker.network.generic:map[] com.docker.network.enable_ipv6:false] IPv4Data:[{AddressSpace: Pool:172.19.0.0/16 Gateway:172.19.0.1/16 AuxAddresses:map[]}] IPv6Data:[]}

    $ docker network create --driver=weavemesh --subnet=172.19.0.0/16  mynet2

    DEBU: 2016/05/04 13:48:45.694125 [net] CreateNetwork &{NetworkID:2112a095b830eb0aefc2a9b21a6be4def85638b1074ce87b9decd06cd01d88f4 Options:map[com.docker.network.enable_ipv6:false com.docker.network.generic:map[]] IPv4Data:[{AddressSpace: Pool:172.19.0.0/16 Gateway:172.19.0.2/16 AuxAddresses:map[]}] IPv6Data:[]}

So this is not something we can particularly report with a diagnostic at network creation time.

Docker does allow a plugin to assert that it has no gateway functionality, but only later, at `Join` time : https://github.com/docker/libnetwork/pull/778/files

**Comment by bboreham** [comment]
Worse, even when I attempt to request _no_ gateway, I get one: https://github.com/docker/libnetwork/issues/1151

**Comment by rade** [comment]
What does the docker overlay network do with the gateway param?

**Comment by bboreham** [comment]
> What does the docker overlay network do with the gateway param?

It accepts it, and returns it in `docker network inspect`, however it does not set it as a gateway.

In the non-internal case, the container gets an additional interface on `docker_gwbridge` which has the default route and its own gateway.

Here is the `--internal` case, that has no gateway at all:

````
$ docker network create --driver overlay --subnet=10.0.11.0/24 --gateway=10.0.11.1 --internal m
y-net3
$ docker run -ti --net=my-net3 alpine /bin/sh
/ # ip route
10.0.11.0/24 dev eth0  src 10.0.11.2
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
15: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 02:42:0a:00:0b:02 brd ff:ff:ff:ff:ff:ff
    inet 10.0.11.2/24 scope global eth0
       valid_lft forever preferred_lft forever
/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.0.11.0       *               255.255.255.0   U     0      0        0 eth0
````

The address is pingable:

````
/ # ping 10.0.11.1
PING 10.0.11.1 (10.0.11.1): 56 data bytes
64 bytes from 10.0.11.1: seq=0 ttl=64 time=0.063 ms
/ # arp
? (10.0.11.1) at 56:d9:74:28:8e:4d [ether]  on eth0
````

but that Mac address is not on any visible device inside or outside the container.

On the same network on another machine, 10.0.11.1 resolves to a different Mac address.

**Comment by rade** [comment]
> On the same network on another machine, 10.0.11.1 resolves to a different Mac address.

Doesn't that cause problems?

**Comment by bboreham** [comment]
> Doesn't that cause problems?

Via tcpdump, I see that an arp request for a real container is conveyed across the network, but arp requests for the .1 address specified as `--gateway`, also for a non-existent .5 address, are not conveyed.

Open to suggestions for other ways this could cause problems.

**Comment by rade** [comment]
>  arp request ... are not conveyed

Is that a feature of how Docker's Overlay works? Does it know which IPs live where any only conveys arps for known IPs?

**Comment by bboreham** [comment]
I don't think we can do anything about this, with current Docker behaviour.  If you don't specify a gateway address, Docker allocates one before creating the network; there is no way (when using Docker's IPAM, as in the original report) of telling the difference when control enters the plugin.

I have confirmed from the code and log files this also happens with Docker's overlay network in `--internal` mode, when no gateway is wanted or used.
