### ISSUE TITLE
bin/publish-site should ensure that release branch is the most recent

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2256]
The CI script currently updates the live `www.weave.works/docs/$PRODUCT/latest` docs for any merges to any release branch (e.g. matching X.Y) _without checking that X.Y really is the most recent_. We tend not to push to historic release branches, but if we did we would end up publishing old docs as latest. The script should analyse all release branches in GH and only publish to latest if the target branch really is the most recent.

**Comment by bboreham** [comment]
Closing: we don't use `publish-site` any more.
