### ISSUE TITLE
[dns] basic load balancing for services

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#226]
There is a rather obvious opportunity for weave to facilitate basic load balancing and fault resilience... when, using weavedns, multiple containers are entered into dns under the same name, weave could implicitly treat these as a load balance group, returning all the addresses in a random order.

This requires [caching](225).

**Comment by awh** [comment]
Scope of this issue has been reduced to load balancing only for 0.11.0. The implementation will return a single randomly chosen address from the possible set of addresses for a name.
