### ISSUE TITLE
Improve doc publishing CI

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2273]
* [ ] Don't run tests if PR contains only /site changes
* [ ] ~~Don't publish feature branch doc previews if PR does not change /site~~ (this doesn't make sense, because circle will start running a build for a new branch _before_ a PR is created, and without the target branch from the PR we can't tell what has changed)
* [ ] Post a comment back the to PR issue with links to preview URLs & CC Anita

**Comment by rade** [comment]
closed by #2274.
