### ISSUE TITLE
reproducible builds

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#228]
Right now our builds take in a lot of stuff from the environment. In particular the various go libraries. So two developers building and publishing weave images can get different, and sometimes non-working, results. We have been caught out by this already.

Tasks identified so far:
- [x] Vendor Go dependencies #1656
- [ ] Pin versions of weaver and weaveproxy base images
- [x] Pin version of build container image
- [ ] Pin versions of images used by smoke tests
- [x] Update release process to use containerised build

**Comment by rade** [comment]
See http://0x74696d.com/posts/go-get-considered-harmful/, the [associated HN thread](https://news.ycombinator.com/item?id=9508022) and [gb](https://github.com/constabulary/gb).

**Comment by monadic** [comment]
btw https://groups.google.com/forum/#!topic/golang-dev/nMWoEAG55v8%5B1-25%5D

**Comment by bboreham** [comment]
See https://github.com/golang/go/commit/183cc0cd41f06f83cb7a2490a499e3f9101befff

**Comment by paulbellamy** [comment]
This (specifically go version) caused: https://github.com/weaveworks/weave/issues/1514, then the libraries not being vendored made it much harder to debug.

**Comment by rade** [comment]
Vendoring libs is the tip of the iceberg. As we discovered, we can also be affected by differences in go versions. And probably base image versions. And I wouldn't be surprised if build-time docker version and host OS (and dynamic libs) also play a role.

**Comment by dpw** [comment]
> As we discovered, we can also be affected by differences in go versions. And probably base image versions. And I wouldn't be surprised if build-time docker version and host OS (and dynamic libs) also play a role.

The containerized builds can address these parts, no?

**Comment by rade** [comment]
> The containerized builds can address these parts, no?

Up to a point. Building the weaveexec image would still drag in whatever `alpine` image is current at the time. We could of course pin that.

**Comment by bboreham** [comment]
> Pin versions of images used by smoke tests

This is contradicted by https://github.com/weaveworks/weave/pull/1360#issuecomment-135317693

Which is preferred?

**Comment by bboreham** [comment]
I think we have pinned as much as we ever expect to.
