### ISSUE TITLE
claiming IP owned by down peer fails

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2285]
```
host1$ weave launch
host1$ weave prime
host2$ weave launch $HOST1
host2$ weave prime
host1$ weave stop
host2$ weave run 10.32.0.1/24 -ti alpine /bin/sh
Unable to claim: address 10.32.0.1/24 is owned by other peer 0e:2a:9b:8e:23:fd (host1)
```

by contrast, allocation hangs, and succeeds when the down peer restarts...

```
host2$ $ weave run net:10.32.0.0/24 -ti alpine /bin/sh
(hangs)
host1$ weave launch
host2$
6f2b088df05b823e4e85106ed32b1a41c7f288d9d138d507ae644a9640477172
```

**Comment by bboreham** [comment]
Agreed the current behaviour is inconsistent, though not obviously _wrong_.  And it's been that way for a long time.

We wouldn't normally change the behaviour like this in a point release.

**Comment by bboreham** [comment]
Having thought about this again, this behaviour is by design.  There is a big difference between trying to get one specific IP address, which is at most owned by one peer, and anything in a range of addresses which can be owned by multiple peers that may come and go.
