### ISSUE TITLE
lost connection to VM after running weave connect peerB

### ISSUE THREAD

**Issue by elianka** [weaveworks/weave#2289]
steps:
0. ssh to VM1(peerA) and VM2(peerB) which are built on KVM using virtio_net driver
1. weave launch peerA
2. weave launch peerB
3. weave connect peerB (from peerA)

Result:
1. lost connection to peerA and peerB
2. check status, connection will be established, and then failed very soon.
    check docker logs weave, tcp connection error, cannot reach each peer.
![image](https://cloud.githubusercontent.com/assets/4158830/15203332/1d20ae66-1835-11e6-90cc-21b61c6ae774.png)
3. console to peerA, no arp to peerB. 
    manually add arp entry to peerB, ping peerB,
    then print: “ping: sendmsg: No buffer space available”
4. after reboot or "re-insert virtio_net, restart network", peerA could reach peerB.

weave script 1.5.0
weave router 1.5.0
VM-OS: CentOS Linux (3.10.0-123.4.4.el7.x86_64) 7 (Core)
net driver: virtio_net

**Comment by awh** [comment]
Hi @elianka 

To be honest this is much more likely to be a problem with your VM networking than a problem with Weave Net. The CentOS 7 kernel you're using as guest is very old and possibly impacted by virtio drivers bugs [such as this one](https://bugzilla.kernel.org/show_bug.cgi?id=42829).

Can you try with a more recent guest kernel? What are you using for the host out of interest?

**Comment by elianka** [comment]
i have used the more recent kernel to test, everything is ok. 
so that is possible be a problem with kernel version. i will check the bugs, that's very useful, thanks!

i was using weave on my cloud platform, and encountered this problem. I tried to resolve it and checked all the guest and host information because i doubt the kernel issue but not know why. That's it.

**Comment by elianka** [comment]
it's really a bug for linux. And weave may send big UDP packets using SOCKET_RAW.
https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/commit/?id=8a0cafc9a8131cc545dc9924aed38f7176ee4ad7

**Comment by rade** [comment]
Well spotted! Looks like the fix landed in the 4.4 kernel.

**Comment by elianka** [comment]
actually, kernel 3.13 has fixed this.
