### ISSUE TITLE
explain that weave launch-plugin cannot create network when weave router is down

### ISSUE THREAD

**Issue by crockpotveggies** [weaveworks/weave#2293]
Running the following on an Ubuntu host OS, firewall disabled:

```
ubuntu@ubuntu2950:~$ weave launch-plugin
e37d9a767e481859130e699e3e0cb32329e8eb65babfe94cbc78b18903c8e207
unable to create network: API error (500): IpamDriver.RequestPool: Get http://127.0.0.1:6784/ipinfo/defaultsubnet: dial tcp 127.0.0.1:6784: getsockopt: connection refused
```
 and when I try to launch a container I get: `docker: Error response from daemon: network weave not found.`

Weave versions:
```
weave version
weave script 1.5.1
weave router 1.5.1
weave proxy  1.5.1
weave plugin 1.5.1
```

Bug or fixable?

**Comment by crockpotveggies** [comment]
Nevermind, apparently this is an intended behavior.

**Comment by bboreham** [comment]
What's happening is that the plugin relies on the `weave` container for IP address management, so Docker requests info about the IP address range it gets an error.
I guess we could detect this condition before trying to create the network.

**Comment by rade** [comment]
I think the error is coming from `util_op create-plugin-network weave weavemesh`.

>  I guess we could detect this condition before trying to create the network.

And do what?

**Comment by bboreham** [comment]
Print a more useful diagnostic on stderr.

**Comment by crockpotveggies** [comment]
Agreed as a brand new user to weave my Google-fu skills failed to find discover the actual problem to this error message, so a more useful diagnostic message would be very helpful :)
