### ISSUE TITLE
Docker moving to Go 1.6 will break Weave

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2308]
As seen in #2022, changes in Go 1.6 cause the Docker server to reject calls from earlier versions, including the version we bundle in weavexec.

Via https://github.com/docker/docker/pull/22000 we infer that Docker is preparing to move to Go 1.6 with a workaround controlled by an environment variable. It would be better if Weave did not require users to set environment variables in their Docker daemon.

Things we use the docker client for:
 - version
 - inspect
 - run (weaver/proxy/plugin container only; see below)
 - run (to overwrite /etc/hosts)
 - create & rm for checking args match
 - create of weavedb & weavewait data containers
 - start
 - stop
 - kill
 - restart
 - rm for `weave reset`
 - exec (for http_call_unix)
 - ps
 - pull (for setup)

Note we do not use `docker run` to run the user's container, e.g. in `weave run`, or to invoke the weave script inside `weaveutils`; the user's local `docker` client is used in those cases.

**Comment by bboreham** [comment]
According to https://github.com/docker/docker/issues/20865#issuecomment-200120560 the oldest official Docker client we could move to is 1.10.

**Comment by rade** [comment]
By far the simplest would be to move to 1.10. Users with older servers can employ the "mount docker binary" trick.

**Comment by rade** [comment]
We are safe! [Docker have changed their mind](https://github.com/docker/docker/pull/22888).
