### ISSUE TITLE
augment dire warning when `weave stop`ing and there are containers attached via the plugin

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2320]
```
$ weave stop
unable to remove network: API error (500): network weave has active endpoints

WARNING: docker may hang in this state; re-launch weave and remove attached containers before shutting down
```

Firstly, iirc docker no longer completely hangs in this state. Furthermore, all is well if you restart weave. That is kinda implied by the warning, but could be made clearer. In particular, it is perfectly ok to `weave stop`, perhaps upgrade, and then `weave launch` with some tweaked options. As it stands, the error and warning may put off users from doing exactly that.

**Comment by bboreham** [comment]
How about `WARNING: docker network commands may fail in this state, until you re-launch weave`

**Comment by rade** [comment]
Is that actually what happens?

Also, we probably still want to leave a clue that the user should stop/remove attached containers before `weave stop|reset` if they are not intending to relaunch weave.

**Comment by bboreham** [comment]
A simple example would be `docker run --net=weave` will hang for 15 seconds then fail. 

A complicated example would be stopping an existing weave-connected container, which will hang for 15 seconds and not fail.

**Comment by rade** [comment]
Do any operations *not* involving weave networks pause or fail?

**Comment by bboreham** [comment]
> Do any operations not involving weave networks pause or fail?

I don't think so.  But it may not be clear to a user which operations involve weave networks, e.g. rebooting the machine while an endpoint is active will cause a delay in Docker startup.
