### ISSUE TITLE
Error response from daemon: 400 Bad Request: malformed Host header

### ISSUE THREAD

**Issue by jcassee** [weaveworks/weave#2324]
This may be the same problem as #2022, but I do not see the message "ERROR: Unable to determine docker version".

Weave 1.5.2 installed as `/usr/sbin/weave` on Ubuntu 16.04 (`Linux stevens 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`) and Docker Docker version 1.10.3, build 20f81dd.

```
$ DOCKER_CLIENT_ARGS=-D /usr/sbin/weave launch
DEBU[0000] framesize: 114
time="2016-05-30T18:55:08Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header"
DEBU[0000] Corrupted prefix: []
DEBU[0000] [hijack] End of stdout
```

Syslog:
```
May 30 20:55:08 stevens kernel: [27201.936261] aufs au_opts_verify:1597:docker[32173]: dirperm1 breaks the protection by the permission bits on the lower branch
May 30 20:55:08 stevens kernel: [27201.971903] aufs au_opts_verify:1597:docker[32173]: dirperm1 breaks the protection by the permission bits on the lower branch
May 30 20:55:08 stevens docker[32162]: time="2016-05-30T20:55:08.537788677+02:00" level=warning msg="could not find endpoint count key docker/network/v1.0/endpoint_count/44d4149519a39358debaccc5271faec17dfc1831b76526de88e74859c72bb0e7/ for network bridge while listing: Key not found in store"
May 30 20:55:08 stevens kernel: [27202.019228] aufs au_opts_verify:1597:docker[32173]: dirperm1 breaks the protection by the permission bits on the lower branch
May 30 20:55:08 stevens docker[32162]: time="2016-05-30T20:55:08.747539835+02:00" level=warning msg="[5] Container is not running: container not running"
May 30 20:55:08 stevens docker[32162]: time="2016-05-30T20:55:08.747994846+02:00" level=warning msg="[6] Container is not paused: container not paused"
May 30 20:55:08 stevens docker[32162]: time="2016-05-30T20:55:08.763651522+02:00" level=warning msg="could not find endpoint count key docker/network/v1.0/endpoint_count/44d4149519a39358debaccc5271faec17dfc1831b76526de88e74859c72bb0e7/ for network bridge while listing: Key not found in store"
```

**Comment by jcassee** [comment]
Sorry, after close reading this *is* the same problem as #2022. Because the issue was closed I had expected the problem to have been fixed. However, it was closed because the problem was not determined to be in Weave.

Yet, no solution for running Weave on Ubuntu 16.04 without installing a non-repository Docker...

**Comment by rade** [comment]
> Yet, no solution for running Weave on Ubuntu 16.04 without installing a non-repository Docker

Are you saying you are running into this problem with a stock Ubuntu distribution? What repository is that downloading docker from? And what does `docker version` report?

**Comment by bboreham** [comment]
I did a couple of experiments with freshly-minted Ubuntu 16.04 VMs:

If you install Docker using the instructions at `https://docs.docker.com/engine/installation/linux/ubuntulinux/`, you get Docker 1.11.1 compiled with go1.5.4.

If you install Docker by `sudo apt install docker.io`, which is what Ubuntu itself suggests if you type `docker` without having installed it, you get Docker 1.10.3 compiled with go1.6.1.

**Comment by jcassee** [comment]
What @bboreham said. 😄

**Comment by rade** [comment]
@jcassee so the workaround for the moment is to install docker from the docker repository, not the ubuntu repository.

**Comment by jcassee** [comment]
Yes, exactly. (I was unclear in my post yesterday, sorry.)

**Comment by bboreham** [comment]
Actually the Ubuntu maintainers [have fixed this problem](https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1574904), but not released that version of the package for 16.04.

**Comment by rade** [comment]
@jcassee Resolving #2308 will likely fix this too, though it is too intrusive a change to go into a bug fix release.

On a related note, the workaround in https://github.com/weaveworks/weave/issues/2022#issuecomment-219703261 does not work here for the reasons explained in https://github.com/weaveworks/weave/issues/2022#issuecomment-219707935, i.e. the docker from the docker.io repo is dynamically linked.

Until there is a resolution, perhaps we should add a note to our docs highlighting the issue and recommending that users install docker from the Docker Inc provided repos.

**Comment by bboreham** [comment]
Closing this as Docker have [reversed their position](https://github.com/docker/docker/pull/22888) so that code will make its way into downstream packages.
