### ISSUE TITLE
`weave reset` silently skips freeing IPAM if router is down

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2326]
We should print a warning as per https://github.com/weaveworks/weave/pull/1978#discussion_r64896561

**Comment by bboreham** [comment]
I couldn't find that comment easily, so reproduced here:

> Do we want to warn a user if weave reset is called after weave stop, i.e. when the weave container is not running?
> Because the implied rmpeer is skipped silently? Well spotted! 
> Well spotted indeed. We should output a warning, with some clues what to do (e.g. call rmpeer elsewhere, or re-launch the router and then re-reset).

**Comment by bboreham** [comment]
Are we saying warn in every case, or only if it's clear that there are other peers we could have given the space to?  The latter is non-trivial.
