### ISSUE TITLE
WARN - Security options with `:` as a separator are deprecated

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#2328]
I am frequently seeing this warning when I run weave operations, though I suspect it may be coming from the docker engine, but I am not sure and leaving this note here in case this is weave code, or weave's interaction with docker which is throwing the advise at me.  

WARN[0325] Security options with `:` as a separator are deprecated and will be completely unsupported in 1.13, use `=` instead.

**Comment by hesco** [comment]
https://github.com/docker/docker/issues/23186

**Comment by bboreham** [comment]
I've already reported this at https://github.com/docker/docker/issues/22413 and fixed it at https://github.com/opencontainers/runc/pull/793

**Comment by bboreham** [comment]
Duplicate of #2241
