### ISSUE TITLE
plugin docs should explain how to create multiple networks

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2335]
https://www.weave.works/docs/net/latest/plugin/ makes no mention of how to create multiple networks. That info is hidden away in https://www.weave.works/docs/net/latest/plugin/plugin-how-it-works/, and not especially clear.

NB: This needs to point out that creating multiple networks *does* require a cluster store.

Related, https://www.weave.works/docs/net/latest/plugin/#cluster-store makes no sense. Bypassing the cluster store is something that happens for the default network; it's not something a user has to configure, or indeed *can* configure as outlined in that section (which seems to be aimed at network plugin *authors* not users).

**Comment by rade** [comment]
> Related, https://www.weave.works/docs/net/latest/plugin/#cluster-store makes no sense

Removed in aa4980bb.

**Comment by bboreham** [comment]
> creating multiple networks does require a cluster store.

or manually specifying disjoint subnets within the Weave IPAM range.

**Comment by bboreham** [comment]
Closed by #2369
