### ISSUE TITLE
Weave docker container won't auto start when reboot host machine

### ISSUE THREAD

**Issue by netroby** [weaveworks/weave#2343]
While weave launch, we restart host machine. the dock engine started. but the weave , weaveproxy, weaveplugin won't auto start.
we should start these container by hand.

**Comment by bboreham** [comment]
The plugin has always had `--restart=always`, and we added it to the router and proxy containers in version 1.5.

Do you get any error messages in the Weave container logs or in Docker's logs?

**Comment by netroby** [comment]
I am trying as the guide told me how to do:
https://www.weave.works/guides/part-3-creating-and-scaling-multi-host-docker-deployment-with-swarm-and-compose-using-weave/

After i restart docker machine one by one weave-1, weave-2, weave-3.

The weave container won't auto start

**Comment by bboreham** [comment]
OK, looks like that guide has a copy of the Weave script at version 1.4.1.  I'll raise this issue over there.
