### ISSUE TITLE
document `--host`

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2347]
`--host` is currently not mentioned in the usage, and not documented. See https://github.com/weaveworks/weave/issues/810#issuecomment-224620109 for why that is useful.

**Comment by bboreham** [comment]
Struggling to find a good place for it.  Maybe we should introduce a page which lists all the documented options for the router in one place, linking to existing documentation where it exists.

**Comment by rade** [comment]
> Struggling to find a good place for it. 

https://www.weave.works/docs/net/latest/using-weave/#peer-connections
or
https://www.weave.works/docs/net/latest/using-weave/#launching
?
Not perfect, but good enough, IMO.

**Comment by bboreham** [comment]
That page is the first place a new user comes to after installation; not a good place for rarely-used config.

www.weave.works/docs/net/latest/using-weave/configuring-weave/ seems like a much better URL, but we'd need to change the title (and various links)

**Comment by abuehrle** [comment]
I think we should document all of the flags in one place, as a reference, either alphabetically or by task.  But that doesn't solve this issue immediately.  After dockerCon, I can start working on that. 

Having a page with all of the router options is a good idea, IMO.  We can then migrate these pages into a reference when we have more time.

**Comment by rade** [comment]
> I think we should document all of the flags in one place, as a reference

That is #959, isn't it?

Let's please not turn this issue into a re-org of the docs.
