### ISSUE TITLE
weave run interprets container args

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2351]
Arguments after the image name are meant for the container; they should not be interpreted by `weave run`.
To illustrate:

```
weave run -ti alpine /bin/sh --name=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Container name too long to be used as hostname
45f745308a532a1b0c3c351741c64a64318860a107dc0e049789fe34fcfe215d
```

Unfortunately it is hard to know where the image name appears; it depends on exactly which `docker run` flags take a following parameter.

**Comment by rade** [comment]
I think we were aware of that.
