### ISSUE TITLE
ditch 'weave run|start|restart'

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2353]
I doubt very many users are using `weave run|start|restart`, and instead are using the proxy or plugin. The lack of "waiting for the interface" in `weave run` is an achilles heel (which is one reason we introduced the proxy), and it suffers from other issues such as #2351.

Is there anything `weave run|start|restart` can do that the proxy cannot?

**Comment by bboreham** [comment]
I use `weave run` as the quickest way to get something going when testing.

It leaves your container's command-line unaltered, without `/w/w` at the beginning.

But on the whole I would be ok with removing it (perhaps after one release cycle with a deprecation message).

**Comment by rade** [comment]
> I use `weave run` as the quickest way to get something going when testing.

Interesting. I use `docker $(weave config) run` for that because I typically want to attach to the container, and/or --rm it, neither of which is possible with `weave run`.
