### ISSUE TITLE
--init-peer-count warning message is misleading

### ISSUE THREAD

**Issue by chaneylc** [weaveworks/weave#2355]
I've adapted the weaveworks guide slightly from: [weaveworks](https://github.com/weaveworks/guides/tree/30afe999265ad18494f3a88064f70cac1edc9607/weave-and-docker-platform/scripts)

After creating the machines a la ./machine_create and running ./weave-launch I noticed 
Warning: --init-peer-count is deprecated; please use --ipalloc-init

So here is my edited script: 

```
#!/bin/bash -e

find_tls_args="cat /proc/\$(pgrep /usr/local/bin/docker)/cmdline | tr '\0' '\n' | grep ^--tls | tr '\n' ' '"

for i in $(seq 3) ; do
  ## This environment variable is respected by Weave script,
  ## hence it needs to be exported
  export DOCKER_CLIENT_ARGS="$(docker-machine config weave-${i})"

  tlsargs=$(docker-machine ssh "weave-${i}" "${find_tls_args}")

  ## We are going to use IPAM, hence we supply estimated cluster size
  ./weave launch-router --ipalloc-init 5
  ## Proxy will use TLS arguments we just obtained from Docker
  ./weave launch-proxy ${tlsargs}

  ## Let's connect-up the Weave cluster by telling
  ## each of the nodes about the head node (weave-1)
  if [ ${i} -gt 1 ] ; then
    ./weave connect $(docker-machine ip 'weave-1')
  fi
done

unset DOCKER_CLIENT_ARGS
```

When I run this, the weave container breaks:
`The weave container has died. Consult the container logs for further details.`

docker logs ....

INFO: 2016/06/09 18:51:31.475430 Command line options: map[datapath:datapath dns-listen-address:172.17.0.1:53 http-addr:127.0.0.1:6784 ipalloc-init:5 port:6783 dns-effective-listen-address:172.17.0.1 ipalloc-range:10.32.0.0/12 name:a6:8e:fd:3b:ac:fd nickname:thunder-1]
INFO: 2016/06/09 18:51:31.517443 Communication between peers is unencrypted.
INFO: 2016/06/09 18:51:31.524766 Our name is a6:8e:fd:3b:ac:fd(thunder-1)
INFO: 2016/06/09 18:51:31.524780 Initial set of peers: []
INFO: 2016/06/09 18:51:31.525742 Docker API on unix:///var/run/docker.sock: &[KernelVersion=4.4.12-boot2docker BuildTime=2016-06-01T21:20:08.558909126+00:00 Version=1.11.2 ApiVersion=1.23 GitCommit=b9f10c9 GoVersion=go1.5.4 Os=linux Arch=amd64]
FATA: 2016/06/09 18:51:31.525792 Unable to parse --ipalloc-init: unknown mode: 5
INFO: 2016/06/09 18:51:31.981073 Command line options: map[dns-listen-address:172.17.0.1:53 http-addr:127.0.0.1:6784 ipalloc-range:10.32.0.0/12 nickname:thunder-1 port:6783 datapath:datapath dns-effective-listen-address:172.17.0.1 ipalloc-init:5 name:a6:8e:fd:3b:ac:fd]
INFO: 2016/06/09 18:51:32.019558 Communication between peers is unencrypted.
INFO: 2016/06/09 18:51:32.023137 Our name is a6:8e:fd:3b:ac:fd(thunder-1)
INFO: 2016/06/09 18:51:32.023166 Initial set of peers: []
INFO: 2016/06/09 18:51:32.039871 Docker API on unix:///var/run/docker.sock: &[BuildTime=2016-06-01T21:20:08.558909126+00:00 Version=1.11.2 ApiVersion=1.23 GitCommit=b9f10c9 GoVersion=go1.5.4 Os=linux Arch=amd64 KernelVersion=4.4.12-boot2docker]
FATA: 2016/06/09 18:51:32.039899 **Unable to parse --ipalloc-init: unknown mode: 5**

But if I keep the original script, everything works fine :)

Let me know if you need any more information, I hope this is useful.

**Comment by chaneylc** [comment]
I noticed that --ipalloc-init accepts a mode not an integer, it would be nice to see available modes in the weave usage.

**Comment by chaneylc** [comment]
I was incorrectly reading the usage.
My problem was that I thought ipalloc-init accepted an integer. 
It actually accepts a 'mode' defined as:  <mode>     = consensus[=<count>] | seed=<mac>,... | observer

**Comment by rade** [comment]
The modes *are* shown in the usage:
```
$ weave help
Usage:
...
                      [--no-restart] [--ipalloc-init <mode>]
...
where <peer>     = <ip_address_or_fqdn>[:<port>]
      ...
      <mode>     = consensus[=<count>] | seed=<mac>,... | observer
```

but the warning should be clearer, e.g. "... --ipalloc-init consensus=<count>" -> re-opening.
