### ISSUE TITLE
work nicely with 'docker service ...'

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2396]
Does weave work "nicely" with the new Docker 1.12 `docker service ...` functionality?

In particular...
- does it work when using the proxy?
- does it work when using the default 'weave' plugin network?
- does it work when using custom networks created from 'weave' driver?
- does it work when the service is using VIPs (a feature of docker services)

The objective of this issue is to:
- answer the above
- write a blog post, provided some things do work
- tweak docs, if necessary, to explain how to make things work
- file issues, if necessary, to make things work

**Comment by ccatlett2000** [comment]
Going to comment here instead of making a new issue. Is there any progress on this? As far as I can tell weave doesn't work **at all** with services in swarm mode.

```
root@localhost:~# docker service create --replicas 1 --name nginx --network weave nginx
Error response from daemon: network weave is not eligible for docker services
```

Is there any way to use docker services and weave, or is it currently impossible?

**Comment by rade** [comment]
From https://docs.docker.com/engine/extend/plugins_network/#/network-driver-plugins-and-swarm-mode
> Docker Engine running in swarm mode currently only supports the built-in overlay driver for networking. Therefore existing networking plugins will not work in swarm mode.

**Comment by ccatlett2000** [comment]
@rade Thanks, that's what I suspected. I guess it's time to consider kubernetes.

**Comment by bboreham** [comment]
Note #2727 made most of this work with a new "v2" plugin; we still have to document it.
