### ISSUE TITLE
work as a 'docker plugin' ('V2 plugin')

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2397]
Docker introduces an experimental 'docker plugin ...' set of commands for managing plugins implemented as containers. We should make weave work in that way, though details are sketchy atm.

I imagine this issue will become a tracker for existing/new more specific issues that need to be resolved to pull this off.

**Comment by brb** [comment]
Moved from #2652:

Docker Engine has introduced a new way to distribute plugins. It's called plugin-v2 and docs can be found [here](https://github.com/docker/docker/blob/1.13.x/docs/extend/index.md).

In short:

* A plugin is distributed as a Docker image which is hosted at Docker Hub.
* Image should contain plugin configuration files which, in addition, include run-time parameters.

If Plugin is distributed in the plugin-v2 way, a user will be able to install and use it by:
```bash
$ docker plugin install weaveworks/plugin
$ docker plugin set weaveworks/plugin args="host1 host2 host3"
$ docker network create -d weavemesh <...>
```

One way to make it happen is to bundle Router with Plugin, as Plugin-v2 expects only a single executable.

Please note that _"there is an ongoing effort in getting plugin-v2 work in swarmkit as well"_, so Weave Plugin (v2) won't work with Docker Swarmkit.

More to follow up after getting responses from Docker.

/cc @lukemarsden

**Comment by Multiply** [comment]
Is there any progress on this ticket? I think it would be much easier to install and use Weave in dev environments, if the only requirement is docker (ie. not having to run `weave install` every time we reset out dev envs).

Ideally, I assume all this can be added to our `docker-compose.yml`-files, and it'll auto install the plugins when needed.

**Comment by bboreham** [comment]
See #2727; plugin support was broken in the Docker 1.13.0 release so we are stalled.

**Comment by Multiply** [comment]
Thanks @bboreham - I subscribed to it now to keep track on the progress. :)
