### ISSUE TITLE
weave interactions complain: docker-containerd-shim not installed on system

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#2401]
I am running `Docker version 1.9.1, build a34a1d5`

```
root@dessalines014:~/docker-helper-scripts/lib/sh# weave status 
Error response from daemon: rpc error: code = 2 desc = "docker-containerd-shim not installed on system"
root@dessalines014:~/docker-helper-scripts/lib/sh# weave ps 
Error response from daemon: rpc error: code = 2 desc = "docker-containerd-shim not installed on system"
```

Any ideas what is required to restore services here?  Any thoughts would be appreciated.  

-- Hugh

**Comment by bboreham** [comment]
I believe containerd came in after 1.9.1, so perhaps your Docker installation is confused?

**Comment by bboreham** [comment]
@hesco did you check your installation?  Any more info?

**Comment by hesco** [comment]
root@dessalines014:~/docker-helper-scripts/lib/sh# docker version 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        2016-06-01T21:23:39.714800648+00:00
 OS/Arch:      linux/amd64

**Comment by hesco** [comment]
root@dessalines014:~/docker-helper-scripts/lib/sh# ps aux | grep docker 
root      8874  0.0  0.0 972464 48456 pts/1    Sl+  Jun24  11:32 docker daemon
root      8879  0.0  0.0 438260 12928 ?        Ssl  Jun24   1:14 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc --start-timeout 2m
root      8973  0.0  0.0 341440  4120 ?        Sl   Jun24   0:00 docker-containerd-shim a88d32e9c558392fc01e1c219fd8fa1373a01fa29f8b8541bfa787946af7d860 /var/run/docker/libcontainerd/a88d32e9c558392fc01e1c219fd8fa1373a01fa29f8b8541bfa787946af7d860 docker-runc
root      8979  0.0  0.0 200348  3124 ?        Sl   Jun24   0:00 docker-containerd-shim c2a1abf7362dcb4bd904ba0c14a4c9462cdd66c36df515180db65139efaf0146 /var/run/docker/libcontainerd/c2a1abf7362dcb4bd904ba0c14a4c9462cdd66c36df515180db65139efaf0146 docker-runc
root     10409  0.0  0.0 275648  3320 ?        Sl   Jun24   0:09 docker-containerd-shim 29d4467edeee4777b8755264ac134d6688ee9601255fb323f623c8c8fe359927 /var/run/docker/libcontainerd/29d4467edeee4777b8755264ac134d6688ee9601255fb323f623c8c8fe359927 docker-runc
root     10683  0.0  0.0 275648  3296 ?        Sl   Jun24   0:00 docker-containerd-shim 103e755b31e8d23f99b97ee4136a4b4cbd7268ba7c69ee4fb9eef6c173089a04 /var/run/docker/libcontainerd/103e755b31e8d23f99b97ee4136a4b4cbd7268ba7c69ee4fb9eef6c173089a04 docker-runc
root     10867  0.0  0.0 275648  3324 ?        Sl   Jun24   0:00 docker-containerd-shim 572d92d0b1685d2ab8638b258c95ee77b5e784e773a12e6101c1a9678e7a5201 /var/run/docker/libcontainerd/572d92d0b1685d2ab8638b258c95ee77b5e784e773a12e6101c1a9678e7a5201 docker-runc
root     11756  0.0  0.0 275648  3364 ?        Sl   Jun24   0:00 docker-containerd-shim aa5aab679e5cfb4ed3f5edd93df6d50cd804d869b949112d5d2e6cd93d9ab208 /var/run/docker/libcontainerd/aa5aab679e5cfb4ed3f5edd93df6d50cd804d869b949112d5d2e6cd93d9ab208 docker-runc
root     29233  0.0  0.0  12732  2252 pts/7    S+   16:40   0:00 grep docker

**Comment by hesco** [comment]
So I see multiple 9 day old processes running docker-containerd-shim, plus a mismatch between the client and server versions.  I do not know if that is an issue or not.  Yet, no sign of containerd, except 

```
root@dessalines014:~/docker-helper-scripts/lib/sh# which docker-containerd-shim 
root@dessalines014:~/docker-helper-scripts/lib/sh# locate docker-containerd-shim  
root@dessalines014:~/docker-helper-scripts/lib/sh# find / -name docker-containerd-shim
root@dessalines014:~/docker-helper-scripts/lib/sh# find / -name containerd
/run/containerd
root@dessalines014:~/docker-helper-scripts/lib/sh# tree /run/containerd/103e755b31e8d23f99b97ee4136a4b4cbd7268ba7c69ee4fb9eef6c173089a04/                                
/run/containerd/103e755b31e8d23f99b97ee4136a4b4cbd7268ba7c69ee4fb9eef6c173089a04/
├── init
│   ├── control
│   ├── exit
│   ├── log.json
│   ├── pid
│   ├── process.json
│   └── shim-log.json
└── state.json

1 directory, 7 files
```
seems to be the only sign of containerd, that and five other parrallel paths with the same structure.

**Comment by hesco** [comment]
Never mind.  

This issue was resolved by purging and re-installing docker on the server.  All better now.
