### ISSUE TITLE
weave --no-dns not works when weave-plugin is used

### ISSUE THREAD

**Issue by aksentyev** [weaveworks/weave#2406]
Weave router was started with --no-dns option.When I run a docker container using weave socket everything is OK. Host dns is used there. When docker container has been run with --net=weave (using plugin) host dns settings are not appeared and weave dns is used.

**Comment by bboreham** [comment]
Can you give a few more details of how you came to this conclusion?  I checked the code, and we don't create the struct that manages DNS if you say `--no-dns`.

Docker's own DNS is pretty similar these days, and is forced on everybody using a network via `--net=`.

If you still think you are getting Weave DNS, please supply the output of `docker logs weave` and also the contents of `/etc/resolv.conf` inside the container.

**Comment by rade** [comment]
Closing this since we cannot reproduce it; if new information comes to light, please re-open.

**Comment by aksentyev** [comment]
Hello,

**Comment by aksentyev** [comment]
Hello, I run weave-router with this command
`weave launch-router --no-dns $PEER_IPs`,
then I get:

**Comment by rade** [comment]
Update from @aksentyev via #2429:

I run weave-router with this command
weave launch-router --no-dns $PEER_IPs,

then I get in the container:

`/home/weave/weaver --port 6783 --name 42:8d:c2:87:2a:37 --nickname some_name --datapath datapath --ipalloc-range 10.32.0.0/12 --dns-effective-listen-address 172.17.0.1 --no-dns --http-addr 127.0.0.1:6784 --resolv-conf /var/run/weave/etc/resolv.conf --no-dns some_peers_ips`.

According to the weave sources `--dns-effective-listen-address` means:

    if config.EffectiveListenAddress != "" {
        listenAddr = config.EffectiveListenAddress
    }
    Log.Println("Listening for DNS queries on", listenAddr)
    return ns, dnsserver
}
So, the problem is in the shell script that runs weave router.

Sorry for long time waiting my answer.

**Comment by rade** [comment]
The fact that the `--dns-effective-listen-address` is specified does not mean DNS will be listening; `--no-dns` makes that option ineffective.

Do you actually see a log line saying "Listening for DNS queries on..." in your weave logs? If not then DNS isn't listening.

**Comment by rade** [comment]
There is actually a tiny bug here in that `--no-dns` appears twice in the command line. But that is harmless.

**Comment by aksentyev** [comment]
Ok, maybe.
With weave plugin my resolv.conf looks like this:
```
nameserver 127.0.0.11
options ndots:0
```

With these iptables rules
```
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DNAT       udp  --  anywhere             127.0.0.11           udp dpt:domain to:127.0.0.11:56576
DNAT       tcp  --  anywhere             127.0.0.11           tcp dpt:domain to:127.0.0.11:34463

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
SNAT       udp  --  127.0.0.11           anywhere             udp spt:56576 to::53
SNAT       tcp  --  127.0.0.11           anywhere             tcp spt:34463 to::53
```

When I use weave proxy resolv.conf looks normal:
```
nameserver 10.220.2.106
nameserver 10.220.2.100
nameserver 10.220.1.103
nameserver 10.220.2.106
```
Is it OK?

**Comment by rade** [comment]
When you are using the plugin (*any* network plugin), docker alters the resolv.conf to point at its own internal DNS server, which in turn will forward queries to any system-configured DNS servers for any queries it cannot answer directly.

**Comment by aksentyev** [comment]
Thanks, so I guess that the problem is not with weave.

**Comment by rade** [comment]
> I guess that the problem is not with weave.

*What* problem? Is DNS resolution inside your containers not returning the expected answers?
