### ISSUE TITLE
Container network segregation/isolation via policy

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2408]
At the moment, we explain how sets of containers may be isolated on the same Weave network by placing them in different subnets.  Customers often ask for a more sophisticated scheme, e.g. limiting the ports that a connection can be opened on.

I see various possible ways forward:
1. implement Kubernetes NetworkPolicy (currently in alpha)
2. implement some simple rules around ports
3. implement a superset of Kubernetes NetworkPolicy, but independent of Kubernetes concepts (i.e. a more generic way to specify sets of containers)

Discussions to date have focused on iptables as the low-level mechanism on each host.

**Comment by rade** [comment]
See #179. Which has some CLI suggestions.

**Comment by rade** [comment]
Minimal CLI and incremental step from what we have now:
- `weave allow <cidr1> <cidr2>` - allow connections from containers in subnet `<cidr1>` to `<cidr2>`; CIDRs must be disjoint
- `weave deny <cidr1> <cidr2>` - inverse
- `weave policies` - list policies

Obvious improvement on that is the ability to name subnets (somewhat related to #676). In case of docker networking, we could use the network names from that.

@mjlodge suggested that we should have something like AWS Security Groups underneath that, and allow users to fiddle with that for more fine-grained control. We'd need a CLI to manage these groups, and associate them with subnets. I rather suspect this will stretch the limits of what is reasonable to do in a CLI; especially given that ordering of rules is probably important. So creating/updating security groups may well require feeding in a config file.

A rule like the above `weave allow ...` would be compiled into security groups by:
- creating a group with an inbound rule allowing all traffic from <cidr1>, and associating that with <cidr2>
- creating a group with an outbound rule allowing all traffic to <cidr2>, and associating that with <cidr1>

We could flip the above around - do security groups first and associated CLI first, and then add the simpler interface later.

**Comment by bboreham** [comment]
On the k8s-sig-network call there was an interesting suggestion to avoid "deny" rules and the ordering issues they bring:

All rules are "allow", but the specification includes subtraction.
E.g. I can say `allow 10.0.0.0/8-10.1.0.0/16`

Are there cases where "deny" is required that do not fit the above pattern?

**Comment by rade** [comment]
I am totally for not having negation. And yes, that would make the rules order invariant.

Btw, The `deny` I mentioned at the beginning above is just a retraction of an `allow`, not a 'deny' as such.

**Comment by bboreham** [comment]
OK, I would interpret "deny" as meaning "regardless of what other rules are in place, don't allow this traffic".  "retract" would be better, given what you meant.

Minor thought on the syntax: `weave policy allow` and `weave policy ls` would avoid using up top-level verbs and be more like Docker.

`weave policy-allow` would be more like what we did with `weave dns-add`

**Comment by bboreham** [comment]
Some sub-cases of "what am I trying to refer to":
 - a subnet within the Weave network
 - an IP range outside of the Weave network (e.g. where my payment processor service resides)
 - a service virtual IP address created by Flux, Kubernetes, etc

**Comment by rade** [comment]
I was trying to avoid the sub-command model.

Re controlling ingress/egress from/to the "outside world" I do not have a good idea how this would work, given that presently we rely on "the platform" to provide it. In any case I suggest tackling this separately.

**Comment by bboreham** [comment]
> allow connections from ... to ...

presumably meaning (at least) TCP connections and bidirectional UDP conversations (as understood by `conntrack`?)

**Comment by rade** [comment]
yes

**Comment by mjlodge** [comment]
To be clear, the container version of security groups would specify inbound and outbound rules based on ports (traditional firewall 5-tuple rules). You'd then be allowed to apply that to a container by name/ID. That would be the "lowest level primitive".

Applying to a subnet would then be the next higher level primitive.

Users are going to want to control which ports are blocked/allowed using a traditional tuple.

Not allowing Deny rules is going against the grain of 30 years of crafting firewall rules, and it's just likely to annoy users who are used to being able to use it.

**Comment by rade** [comment]
Applying rules to containers by name/ID is a non-starter, imo. Container lifecycles are far too dynamic for that. Some form of grouping is imperative.

**Comment by awh** [comment]
> Not allowing Deny rules is going against the grain of 30 years of crafting firewall rules

Interestingly:

* "Security group rules are always permissive; you can't create rules that deny access." - from [Amazon EC2 Security Group Rules](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html#security-group-rules)
* "Firewall rules are only "allow" rules. You cannot create "deny" rules." - from [GCP Networks & Firewall Rules](https://cloud.google.com/compute/docs/networking#firewall_rules)

**Comment by awh** [comment]
Regarding `weave allow <cidr1> <cidr2>` and friends (or whatever) we should consider persistence from the outset, even if we don't implement it initially.

**Comment by bboreham** [comment]
We implemented Kubernetes NetworkPolicy in #2585
