### ISSUE TITLE
Weave containers failed to start on a Centos7 host with Docker version 1.10.3 installed.

### ISSUE THREAD

**Issue by kcao3** [weaveworks/weave#2424]
I have a Centos7 host with Docker 1.9.1 installed. On this machine, I was able to launch the weave (version 1.6.0) containers without any problem. Today, on this machine I just updated Docker from version 1.9.1 to version 1.10.3. 
Now the weave launch command returns with the following error messages:

**cannot locate running docker daemon
Unable to auto-detect proxy TLS configuration; you must launch the proxy with
'weave launch-proxy' and supply '--no-detect-tls' or TLS options.**

Does anyone know how to resolve this problem?

The following are the complete output I received when running the weave launch command:
[root@ip-192.168.10.5 ~]# weave launch
cannot locate running docker daemon
Unable to auto-detect proxy TLS configuration; you must launch the proxy with
'weave launch-proxy' and supply '--no-detect-tls' or TLS options.
[root@ip-192.168.10.5 ~]#
[root@ip-192.168.10.5 ~]#
[root@ip-192.168.10.5 ~]# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64
[root@ip-192.168.10.5 ~]#
[root@ip-192.168.10.5 ~]#
[root@ip-192.168.10.5 ~]# systemctl status -l docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-07-05 16:43:29 UTC; 8min ago
     Docs: http://docs.docker.com
 Main PID: 3437 (sh)
   Memory: 22.6M
   CGroup: /system.slice/docker.service
           ├─3437 /bin/sh -c /usr/bin/docker-current daemon            --exec-opt native.cgroupdriver=systemd            $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $ADD_REGISTRY            $BLOCK_REGISTRY            $INSECURE_REGISTRY            2>&1 | /usr/bin/forward-journald -tag docker
           ├─3439 /usr/bin/docker-current daemon --exec-opt native.cgroupdriver=systemd --selinux-enabled --log-driver=journald --storage-opt dm.basesize=20G
           └─3440 /usr/bin/forward-journald -tag docker

Jul 05 16:51:47 ip-192.168.10.5 docker-current[3439]: INFO: 2016/07/05 16:51:47.431669 Sniffing traffic on datapath (via ODP)
Jul 05 16:51:47 ip-192.168.10.5 docker-current[3439]: INFO: 2016/07/05 16:51:47.467757 Listening for HTTP control messages on 127.0.0.1:6784
Jul 05 16:51:47 ip-192.168.10.5 docker-current[3439]: cannot locate running docker daemon
Jul 05 16:51:47 ip-192.168.10.5 docker-current[3439]: Unable to auto-detect proxy TLS configuration; you must launch the proxy with
Jul 05 16:51:47 ip-192.168.10.5 docker-current[3439]: 'weave launch-proxy' and supply '--no-detect-tls' or TLS options.
Jul 05 16:51:47 ip-192.168.10.5 forward-journal[3440]: time="2016-07-05T16:51:47.893362869Z" level=info msg="{Action=wait, ID=b4bf980410d4db68dd7e81043752d43d34479ff794f0be6ebf6ec86ba1831811, Username=centos, LoginUID=1000, PID=21721}"
Jul 05 16:51:47 ip-192.168.10.5 forward-journal[3440]: time="2016-07-05T16:51:47.990459814Z" level=info msg="{Action=remove, ID=b4bf980410d4db68dd7e81043752d43d34479ff794f0be6ebf6ec86ba1831811, Username=centos, LoginUID=1000, PID=21721}"
Jul 05 16:51:49 ip-192.168.10.5 docker-current[3439]: INFO: 2016/07/05 16:51:49.972845 Discovered local MAC 3a:b9:ca:70:c6:67
Jul 05 16:51:50 ip-192.168.10.5 docker-current[3439]: INFO: 2016/07/05 16:51:50.340731 Discovered local MAC 8e:61:11:b2:d5:b6
Jul 05 16:51:50 ip-192.168.10.5 docker-current[3439]: INFO: 2016/07/05 16:51:50.756746 Discovered local MAC 0e:81:c6:6d:52:96
[root@ip-192.168.10.5 ~]# docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
f6c17d0b0a45        weaveworks/weave:1.6.0   "/home/weave/weaver -"   2 minutes ago       Up 2 minutes                            weave

**Comment by bboreham** [comment]
It looks like the system has a non-standard Docker daemon binary, so Weave was unable to examine it to check for TLS options.  

Since you aren't using TLS (as far as I can see) you can launch weave as:

    weave launch-router
    weave launch-proxy --no-detect-tls

instead of the single `weave launch` command.

**Comment by bboreham** [comment]
Actually I should say `weave launch` does three things, so you really need:

    weave launch-router
    weave launch-proxy --no-detect-tls
    weave launch-plugin

But typically you will only need one of the last two commands, depending on whether you use the Proxy or Plugin approach to connect your containers to Weave Net.

**Comment by bboreham** [comment]
@kcao3 we are thinking to change the default behaviour to assume no TLS is in use, if we cannot find the Docker daemon.  Would be helpful to know whether forcing this enabled Weave Net to work for you, or whether there is a further issue.  Thanks.

**Comment by kcao3** [comment]
Sure. This change will work fine for us.
