### ISSUE TITLE
Weave is broken on Docker For Mac 1.12.0-rc3-beta18 (build: 9996)

### ISSUE THREAD

**Issue by pidster** [weaveworks/weave#2432]
Launching `weave` 1.6.0 is partially successful.

    user@host:/ $ WEAVE_VERSION=1.6.0 weave launch
    unable to create network: API error (500): invalid ipam driver: "weave mesh"
    
    user@host:/ $ docker ps
    CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
    97e7fadd4ee7        weaveworks/plugin:1.6.0      "/home/weave/plugin"     8 seconds ago       Up 7 seconds                            weaveplugin
    f9c69a6a8938        weaveworks/weaveexec:1.6.0   "/home/weave/weavepro"   8 seconds ago       Up 7 seconds                            weaveproxy
    3e6c9ab4eae3        weaveworks/weave:1.6.0       "/home/weave/weaver -"   9 seconds ago       Up 8 seconds                            weave

Launching `weave` using `:latest` is less successful:

    user@host:/ $ WEAVE_VERSION=latest weave launch
    cannot locate running docker daemon
    Unable to auto-detect proxy TLS configuration; you must launch the proxy with 'weave launch-proxy' and supply '--no-detect-tls' or TLS options.
    
    user@host:/ $ docker ps
    CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS               NAMES
    fcefb9ce8555        weaveworks/weave:latest   "/home/weave/weaver -"   4 seconds ago       Up 3 seconds                            weave

**Comment by rade** [comment]
The first one is #2403; waiting for a new docker 1.12 RC for the fix.

The second one is strange - I thought we put in a fix that does the opposite, i.e. detect *more* running dockers, not less.

**Comment by rade** [comment]
Also, what happens if you follow the instructions displayed in the error message? I suspect you'll run into the first error.

**Comment by pidster** [comment]
As you surmise, launching them separately:
- the router succeeds
- the proxy with `--no-detect-tls` succeeds
- the plugin fails with: `unable to create network: API error (500): invalid ipam driver: "weave mesh"`

**Comment by rade** [comment]
The `cannot locate running docker daemon` is perplexing, especially since you are not seeing that in 1.6.0. The code involved hasn't changed since then!

**Comment by pidster** [comment]
Updating `weaveexec` fixes part of this issue. The image was 3 weeks old; my mistake! 

`weave launch` now only reports the IPAM error above.
