### ISSUE TITLE
CNI setup is only run in `weave setup` not `weave launch`

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#2435]
This is weird; we don't advertise `weave setup` as something you *have to* run.

**Comment by rade** [comment]
I suggest we add this to launch_router.

**Comment by bboreham** [comment]
> we don't advertise

It is clearly stated on the CNI docs page https://www.weave.works/docs/net/latest/cni-plugin/

**Comment by rade** [comment]
Yes, I know that. It still breaks the model.

**Comment by rade** [comment]
We should ask the inverse question: is there any *downside* to running setup_cni in launch_router?
