### ISSUE TITLE
Multicast traffic is flooding to ALL containers, which joins the same Weave network

### ISSUE THREAD

**Issue by kcao3** [weaveworks/weave#2438]
I have three Docker host machines. On these machines, I run the following Docker containers 
as the following:

1. Docker Host 1 (A bare metal machine)
   Weave Container/Router   
   Container C1:
      Run a multicast sender app to send UDP traffic to a multicast group address:port.
      In my test, the multicast address and port I used is 230.255.255.5:9000
          
2. Docker Host 2  (A cloud instance)   
   Weave Container/Router   
   Container C2:
      Run a multicast receiver app that joins the multicast address 230.255.255.5, port 9000      
   
 Test Result:
   As expected, my multicast receiver application receives UDP traffic, which is sent by my 
      multicast sender application running in container C1 :-)
     
3. Docker Host 3  (A cloud instance)
   Weave Container/Router   
   Container C3   
   Container C4
   
   The is no application running in Container C3 and C4 that JOINs the multicast group 
   230.255.255.5:9000
   
   From in side container C3 and C4, I run tcpdump command on interface ethwe 
   device:
        tcpdump -nvi ethwe proto UDP 
   
   The tcpdump output indicates container C3 and C4 running on the DOcker Host 3 are flooded with multicast traffic although there is NO application in these two containers has joined such multicast group address and port  :-(
   
   Is there a way to stop or prevent the multicast traffic from flooding into container C3 and C4 on the Docker Host 3?

**Comment by rade** [comment]
> Is there a way to stop or prevent the multicast traffic from flooding into container C3 and C4 on the Docker Host 3?

Is your concern here about performance? If there is nothing listening then the overhead should be pretty low. Except for the cost of sending the packets to the host in the first place, when it doesn't have any containers which are recipients of the specific multicast packets. That is covered by #178.
