### ISSUE TITLE
Arch Linux: Unable to determine docker version

### ISSUE THREAD

**Issue by faddat** [weaveworks/weave#2440]
Here's the full error message:

time="2016-07-12T04:18:48Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header" 
ERROR: Unable to determine docker version

The problem being htat weave doesn't start.

**Comment by rade** [comment]
This is most likely due to Arch shipping with a broken Docker, namely one compiled with go 1.6. See #2022.

**Comment by faddat** [comment]
Ah, like the one in ubuntu.  Thanks!

**Comment by bboreham** [comment]
It looks like Ubuntu merged the fix: https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1574904
