### ISSUE TITLE
Weave 1.6.0 only one connection possible

### ISSUE THREAD

**Issue by gw0** [weaveworks/weave#2451]
In Weave 1.4.5 one could prepare a VM image with Docker and Weave inside that could be deployed anywhere and join the weave network with encrypted sleeve data path to a master server. Although all the images would have the same hostname, each one would use a different IP range, and everything would work as expected (even hosts could be exposed on the weave network).

```
WEAVE_NO_FASTDP=true
WEAVE_PASSWORD="foobar"
PEERS="11.22.33.10"
```

With Weave 1.6.0 this does not work anymore and in case you start the same image multiple times, only the last node stays connected to the weave network, others get the connection dropped with EOF. Same happens even if after a fresh `weave reset --force` on all nodes and bringing them up one by one. Logs on the master server contain:

```
# docker logs weave
INFO: 2016/07/20 14:32:40.669340 ->[11.22.33.131:17628] connection accepted
INFO: 2016/07/20 14:32:40.672749 ->[11.22.33.131:17628|aa:bb:cc:69:74:84(docker-vm2)]: connection ready; using protocol version 2
INFO: 2016/07/20 14:32:40.672824 overlay_switch ->[aa:bb:cc:69:74:84(docker-vm2)] using sleeve
INFO: 2016/07/20 14:32:40.672850 ->[11.22.33.131:17628|aa:bb:cc:69:74:84(docker-vm2)]: connection shutting down due to error: Multiple connections to aa:bb:cc:69:74:84(docker-vm2) added to aa:bb:cc:ba:10:86(master)
INFO: 2016/07/20 14:32:40.680709 sleeve ->[11.22.33.131:6783|aa:bb:cc:69:74:84(docker-vm2)]: Failed to decode packet: UDP packet decryption failed
```

Is there any flag to enable this again? Or is there another recommended approach to setup a cluster from the same VM image?

**Comment by awh** [comment]
Hi @gw0 

In 1.5 we started using product & hypervisor UUIDs as a method of generating peer names that would be stable across reboots:
* #1866 Derive peer name from product_uuid
* #2037 fall back to hypervisor uuid for mac derivation
* [Operational Guide - Concepts - Peer Name](https://www.weave.works/docs/net/latest/operational-guide/concepts/)

As you have noticed the consequences of _different_ peers having the _same_ peer name are quite severe - for that reason we undertook a fair amount of research into VM providers and cloning tools as can be seen [in this comment](https://github.com/weaveworks/weave/pull/1866#issuecomment-171237155).

Unfortunately it seems that we were not thorough enough. Could you tell us about the VM tools that you are using, and confirm that the contents of `/sys/class/dmi/id/product_uuid` and `/sys/hypervisor/uuid` are identical in different VMs booted from the same image?

In the meantime you can work around this to a certain extent by specifying different peer names yourself at launch e.g. `weave launch --name ::1` - that will fix the connectivity issue. Unfortunately it will still result in all the `weave` bridges on the different hosts having the same MAC address, which will break `weave expose` (everything else should work though).

See also #2427 and commentary.

**Comment by gw0** [comment]
@awh Thank you for the detailed reply.

I am using VirtualBox 5.0.2 on Windows (same with 4.3.36 on Debian) with a freshly installed Debian 8.5 guest. Unfortunately `/sys/class/dmi/id/product_uuid` is the same on all machines (same as VirtualBox machine UUID) and `/sys/hypervisor` is just an empty directory.

I found a workaround: Remove the machine from VirtualBox, manually edit its' XML file (`docker-vm2.vbox`) to change the machine UUID `<Machine uuid="{6abb4b74-b382-22c7-a927-e78891b3d7cc}"` to something else, import the modified machine back to VirtualBox, and run it. Now `/sys/class/dmi/id/product_uuid` is different and Weave successfully connects and exposing hostsalso works. Note that just removing the VirtualBox machine UUID from XML prevents it from being imported.

**Comment by gw0** [comment]
Maybe the best solution would be a hash of `/sys/class/dmi/id/product_uuid`, `/sys/hypervisor/uuid` and `/etc/machine-id`. First for convenient use on bare metal, second for VM and cloud providers that provide id, and third for all other use cases (user can setup a run-once script to initialize it at boot time).

How to reinitialize `/etc/machine-id`:

```bash
$ rm /etc/machine-id /var/lib/dbus/machine-id
$ dbus-uuidgen --ensure
$ systemd-machine-id-setup 
Initializing machine ID from D-Bus machine ID.
```

**Comment by gw0** [comment]
The workaround to randomize the VirtualBox machine UUID on Windows:

```cmd
copy docker-vm2.vbox docker-vm2.vbox-orig || powershell -Command "(Get-Content docker-vm2.vbox-orig) | ForEach-Object { $_ -replace '(?<=Machine uuid=.{)[0-9a-zA-Z-]+',[guid]::NewGuid().ToString() } | Set-Content docker-vm2.vbox"
```

**Comment by rade** [comment]
dup of #2427.
