### ISSUE TITLE
Are Weave's control and data ports configurable?

### ISSUE THREAD

**Issue by kcao3** [weaveworks/weave#2463]
Hello,
I have a question. If I am not mistaken, Weave uses port TCP 6783 for control and ports UDP 6783/6784 for data. I am currently running Weave in an environment where these ports are NOT opened. I would like to know if there is a way to configure Weave to use another ports as alternatives. 
Thank you in advance!

**Comment by rade** [comment]
Set `WEAVE_PORT`, as [described in our docs](https://www.weave.works/docs/net/latest/using-weave/multi-cloud-multi-hop/).

**Comment by kcao3** [comment]
Thank you for your support.
