### ISSUE TITLE
'weave create-bridge' should work with fastdp

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2464]
It was disabled in #1562, but could be re-enabled now that we (typically) use a real Linux bridge in conjunction with the fastdp bridge.

**Comment by bboreham** [comment]
I now realise that the motivation behind disabling it was the need to run a `docker` command as part of setting up fastdp; since the main expected uses of `create-bridge` are before Docker is up this creates a catch-22.

However, you can work round this by extracting `weaveutils` so it can be run outside Docker, and my current use-case is in Kubernetes where I don't need to give the bridge to Docker at start-up.

**Comment by brb** [comment]
> since the main expected uses of create-bridge are before Docker is up this creates a catch-22.

This might confuse a user (although the cmd is marked as deprecated):

```bash
$ ./weave --local create-bridge
WARNING: 'weave create-bridge' is deprecated. Instead use 'weave attach-bridge'
to link the docker and weave bridges after both docker and weave have been
started.
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
```

**Comment by bboreham** [comment]
@brb that was exactly my point at https://github.com/weaveworks/weave/issues/2464#issuecomment-237218436

Maybe the right approach is `weave create --force` to signify you know what you are doing.
