### ISSUE TITLE
How to remove Failed Connections from the target list

### ISSUE THREAD

**Issue by maven2016** [weaveworks/weave#2472]
Create a new weave net and specify multiple targets to create a quorum:
weave launch --ipalloc-range x.x.x.x/x --ipalloc-default-subnet x.x.x.x/x y.y.y.y z.z.z.z
y.y.y.y & z.z.z.z are the targets.

Lets say y.y.y.y is unresponsive, is there a way to disable/reduce connections retrys to it? 
When I execute "weave status connections" I see it as "failed connection", no way to remove it manually or specify a parameter -no-retry.

**Comment by bboreham** [comment]
You can remove a host that was specified on the command-line list using `weave forget y.y.y.y`.

**Comment by maven2016** [comment]
i've tried to execute weave forget y-y-y-y, it does not remove the failed connections from:
weave status connections.

**Comment by rade** [comment]
It should remove the connection at the next retry. Is that not happening?

**Comment by bboreham** [comment]
I just tried it on my machine and the entry disappeared after the next 'retry' time.

I guess we could action that faster, to save confusion.
