### ISSUE TITLE
Cannot connect 2 containers by hostname using weave in 2 different servers

### ISSUE THREAD

**Issue by joserivca** [weaveworks/weave#2484]
Hi guys,

i can´t connect 2 containers in 2 differents servers by hostname , but using ip address it works

see below the actions:
**Server 1**
[root@d01 S50]# /database/weave/weave status dns
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
config-server-01 10.40.0.10      c720ea87911f c6:10:e8:6e:90:0b
config-server-02 10.40.0.9       253f267d5040 c6:10:e8:6e:90:0b
config-server-03 10.32.0.6       6fb0a3ad2f93 56:c5:1e:e8:ce:3d
mongos-active 10.40.0.3       96ac8ae007ea c6:10:e8:6e:90:0b
mongos-pasive 10.32.0.1       621bdbc3ca62 56:c5:1e:e8:ce:3d
replica-set-ps01 10.32.0.5       9cf1ab0fff0c 56:c5:1e:e8:ce:3d
replica-set-ps02 10.40.0.6       833f02599153 c6:10:e8:6e:90:0b
replica-set-ps03 10.32.0.2       bfbc808e2288 56:c5:1e:e8:ce:3d
replica-set-s1s01 10.40.0.8       da46a9e9b044 c6:10:e8:6e:90:0b
replica-set-s1s02 10.32.0.4       6a718b61c912 56:c5:1e:e8:ce:3d
replica-set-s1s03 10.40.0.5       362418bdf993 c6:10:e8:6e:90:0b
replica-set-s2s01 10.40.0.7       df151c35a1a0 c6:10:e8:6e:90:0b
replica-set-s2s02 10.32.0.3       61cfcf74733a 56:c5:1e:e8:ce:3d
replica-set-s2s03 10.40.0.4       3512ba9d2fae c6:10:e8:6e:90:0b

**Server2**

[root@config-server-02 /]# nc  config-server-03 26001
hello
Ncat: Could not resolve hostname "config-server-03": Name or service not known. QUITTING.
[root@config-server-02 /]# nc 10.32.0.6 26001
hello

_____________________________________________________

Regards 
joserivca

**Comment by brb** [comment]
Thanks for the report.

Could you provide the following:

* Output of the `weave report` cmd from the **Server2** host.
* Output of the `iptables-save` cmd from the **Server2** host.
* Output of `dig config-server-03` or `nslookup config-server-03` from the `config-server-02` container.

**Comment by brb** [comment]
ping @joserivca

**Comment by brb** [comment]
Closing the issue as relevant info is missing.
