### ISSUE TITLE
Broken link to "Plugin Command-line Arguments" in docs

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2487]
https://www.weave.works/docs/net/latest/plugin/plugin-how-it-works/ -> "Plugin Command-line Arguments" -> 404

**Comment by abuehrle** [comment]
I fixed this manually on the website in the interim.

**Comment by abuehrle** [comment]
Also, the same link on the bottom of this page was redirected to 'Integrating Weave Via the Docker Plugin" https://www.weave.works/documentation/net-latest-ipam/

**Comment by awh** [comment]
Fixed by 3fc7efa5365b56da60205dab09c2a3508c74b083
