### ISSUE TITLE
Multicast doesn't work with weave driver for docker when specify a subnet

### ISSUE THREAD

**Issue by erandu** [weaveworks/weave#2496]
I have created a docker network using this commad :
'docker network create -d weave  --subnet=192.168.1.0/24 --opt=works.weave.multicast weave1'

And then, I launch some containers in this docker network.
After that, multicast doesn't work on container (test with iperf), whereas containers can ping each other.

**Comment by brb** [comment]
Thanks for the report.

A few questions:

0. Which Weave Net / Docker version?
1. Do you have an external kv cluster store up and running as you use the `weave` [driver](https://www.weave.works/docs/net/latest/plugin/plugin-how-it-works/)?
2. Could you provide output of `weave ps` executed on each host? Output of `docker logs weave` (of each host) might be useful as well.

**Comment by erandu** [comment]
I have clean my environment and it looks like it works well after that. The problem doesn't come from weave.

Weave : 1.6.1
Docker : 1.12.1

I use etcd for the cluster, and this one works fine (when I create the docker network on node 1, I see this one on node 2)

Weave ps node 1 :
```core@weave-01 ~ $ weave ps
weave:expose 1e:e1:2d:16:e0:4d
82cef084ae5a 4e:ba:0b:9c:02:95 192.168.1.2/24
```

Weave ps node 2 : 
```
core@weave-02 ~ $ weave ps
weave:expose 46:3f:63:05:38:08
275a84cd51aa 0e:be:10:00:7b:39 192.168.1.3/24
```

So the configuration seems to be normal, sorry for the disagreement.
