### ISSUE TITLE
ability to start weave-networked containers in foreground, and auto-remove them

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#251]
It's somewhat inconvenient, and inconsistent with established docker behaviour, that `weave run` always detaches from the container. Ideally we'd like to mirror `docker run` behaviour, i.e. attach unless `-d` is specified.

The reason we always detach is that we need to perform most of the weave container networking configuration after the container has started (until #47 is resolved).

**Comment by errordeveloper** [comment]
I'd like to note that there one additional limitation of Docker that comes to play:
```
  --rm=false                 Automatically remove the container when it exits (incompatible with -d)
```
