### ISSUE TITLE
CoreOS Weave & Fleet

### ISSUE THREAD

**Issue by vmatekole** [weaveworks/weave#2514]
I have weave running on 2 CoreOS nodes:

When running 
```  weave run   --name postgres -e POSTGRES_PASSWORD=password postgres:9.5.4 ```
The container is created and ran as expected.

When running it as a systemd unit with fleet the container starts and then ends. When I have it configured to restart on failure it constantly restarts. Furthermore when I start postgres with docker, without weave via Fleet container starts as expected:
```
[Unit]
Description=Postgres service

# Requirements
Requires=docker.service

# Dependency ordering
After=docker.service

[Service]
# Let processes take awhile to start up (for first run Docker containers)
User=core
TimeoutStartSec=0

# Change killmode from "control-group" to "none" to let Docker remove
# work correctly.
KillMode=none

# Get CoreOS environmental variables
EnvironmentFile=/etc/environment

# Pre-start and Start
## Directives with "=-" are allowed to fail without consequence
ExecStartPre=-/usr/bin/docker kill postgres
ExecStartPre=-/usr/bin/docker rm -v postgres
ExecStartPre=-/usr/bin/docker pull postgres:9.5.4
ExecStart=/opt/bin/weave run --name postgres -e POSTGRES_PASSWORD=password -v /var/lib/pg3:/var/lib/postgresql/data postgres:9.5.4

# Stop
ExecStop=/usr/bin/docker stop postgres

#Restart=always
#RestartSec=10

[X-Fleet]
# Don't schedule on the same machine as other nginx instances
Global=true
MachineMetadata="name=coreos.backend.0"
```

**Comment by bboreham** [comment]
`weave run` starts the container in 'daemon' mode, so that script will exit very quickly.

One approach we have used in a similar situation is to put `weave run` as another `ExecStartPre` then put `docker attach` as the `ExecStart` command which will wait as long as the postgres container is running.

Another approach is to use the [Weave Docker Proxy](https://www.weave.works/documentation/net-latest-weave-docker-api/net-latest-using-proxy/) instead of `weave run`.

**Comment by vmatekole** [comment]
@bboreham is there a place where I can document this on Weave site and or Github. As it is hard to find any documentation on Weave and Fleet.

**Comment by vmatekole** [comment]
@bboreham lastly, does the ExecStartPre work in all cases? Previously, I have had units with ExecStartPost performing a ``` docker exec ``` for only the step to be unsuccessful as the service hadn't finished starting.

**Comment by bboreham** [comment]
The documentation suggesting to use `ExecStartPre` is at https://www.weave.works/documentation/net-latest-installing-weave/net-latest-systemd/ . It's not specific to Fleet - just systemd.

Or were you asking about how to use the Proxy with Fleet?  I'd have to research that.

`ExecStartPost` will not run until service has notified systemd it has started, and most programs do not do this.  But `ExecStartPre` does not have this requirement.
