### ISSUE TITLE
Containerizer agnostiv weave

### ISSUE THREAD

**Issue by juwi** [weaveworks/weave#2515]
Hi,

I've asked on IRC a couple of days ago wether weave could run without Docker. The answer was no.
The way I understand it though, the only thing weave really needs docker for is the user-facing parts.

My aim is to be able to run Weave as an overlay with a Containerizer other than Docker, like rkt or Mesos (http://mesos.apache.org/documentation/latest/mesos-containerizer/) using the CNI Interface.

Maybe this also fits the scope of #1566 which is about running dockerless all the way.

**Comment by brb** [comment]
@juwi Thanks for the report. I think that your use-case is fully covered by #1566 (see https://github.com/weaveworks/weave/issues/1566#issuecomment-215101434), so I'm closing this issue. Feel free to add any input to #1566 issue.

**Comment by errordeveloper** [comment]
@juwi from reading #1566 it looks this wouldn’t be very hard to implement. We might not have the time to work on this start-to-finish, but if you would like to make a contribution, we will help you out to get it working!
