### ISSUE TITLE
Leftover bridge after installing weave CNI kubernetes plugin

### ISSUE THREAD

**Issue by timcharper** [weaveworks/weave#2519]
After we installed weave (1.6.2) on a 4-node kube cluster, the weave CNI plugin failed to clean up existing conflicting routes for the `cbr0` bridge.

Once deleting the route for `cbr0`, inter-node connectivity worked as expected.

@bboreham

**Comment by bboreham** [comment]
I looked into this, and I think the resolution is to make Kubernetes stop creating the cbr0 bridge and routes.  I have submitted https://github.com/kubernetes/kubernetes/pull/33438 to fix

**Comment by bboreham** [comment]
Also I [moved the address range back to the Weave default](https://github.com/weaveworks/weave-kube/commit/0541a072f1d9554beecbfd45e3a9a89954762cb8), so it won't clash with the Kubernetes routes

**Comment by timcharper** [comment]
Thank you, @bboreham !!!
