### ISSUE TITLE
Weave Net should raise an event when a connection drops

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2523]
"raise an event" meaning something that can be captured by, e.g., Prometheus

**Comment by rade** [comment]
See also #2535

**Comment by awh** [comment]
This is problematic because its only worth notifying for applications where 'connection drop' is a sign of some abnormal condition.

**Comment by bboreham** [comment]
I am interpreting "connection" as "control-plane connection between two Weave Net peers"

**Comment by brb** [comment]
Fixed by #2547
