### ISSUE TITLE
when execute weave reset i can´t run any containers

### ISSUE THREAD

**Issue by joserivca** [weaveworks/weave#2525]
Hi rade,
i execute the weave command 
**Weave reset**
and  inyect all my containers with "/w/w",
now , i cant start any container
how can roll back this "/w/w" in all my containers??

example

[root@p sysconfig]# docker start nginx
Error response from daemon: Cannot start container nginx: [8] System error: exec: "/w/w": stat /w/w: no such file or directory
Error: failed to start containers: [nginx]

**Comment by awh** [comment]
Dup of #2526.
