### ISSUE TITLE
when execute weave reset i can´t run any containers

### ISSUE THREAD

**Issue by joserivca** [weaveworks/weave#2526]
Hi @rade,
i execute the weave command 
**Weave reset**
and  inject all my containers with "/w/w",
now , i can´t start any container
how can roll back this "/w/w" in all my containers??

example:
[root@p sysconfig]# docker start nginx
Error response from daemon: Cannot start container nginx: [8] System error: exec: "/w/w": stat /w/w: no such file or directory
Error: failed to start containers: [nginx]

now my containers looks like this:

**AFTER**
fcf5e3260d90        bcp-mbrk-favoritecreate:v1.0.1             " /bin/bash"         9 weeks ago         Exited (0) 47 hours ago                           create
63b1994f3b2c        bcp-mbrk-favoritelist:v1.0.1               "/bin/bash"         9 weeks ago         Exited 

**BEFORE**
fcf5e3260d90        bcp-mbrk-favoritecreate:v1.0.1             "/w/w /bin/bash"         9 weeks ago         Exited (0) 47 hours ago                           create
63b1994f3b2c        bcp-mbrk-favoritelist:v1.0.1               "/w/w /bin/bash"         9 weeks ago         Exited 
b546068e249f        weaveworks/weaveexec:1.4.6                 "/home/weave/sigproxy"   3 months ago        Exited (0) 3 weeks ago                            thirsty_hodgkin
f3ea51c463e6        PMBRKLNXD01:4000/nginx:1.4                 "/w/w /usr/bin/bash"     3 months ago        Exited (127) 2 hours ago                          nginx-loadbalancer-one

**Comment by joserivca** [comment]
Somebody help me! , i got this issue in production enviroment!

**Comment by awh** [comment]
Hi @joserivca 

Since you've apparently uninstalled weave, you're going to need to relaunch the affected containers I'm afraid.

**Comment by bboreham** [comment]
@joserivca the `/w/w` is added by the Weave proxy, and it points to a directory that is volume-mounted inside the containers.  Unfortunately, `weave reset` blows away that volume, so the file is no longer accessible.

As @awh says the only reasonable thing to do is to `docker rm` your containers and re-create them.

**Comment by joserivca** [comment]
Thanks guys,
is this issue fixed in a new version of Weave Net?

**Comment by bboreham** [comment]
Which direction would you expect such a fix to take?

- If you would prefer an approach that does not inject files into your containers, you can try our [Docker Plugin](https://www.weave.works/docs/net/latest/plugin/) .  There are various pros and cons between the proxy and the plugin.
- If you would like `weave reset` to warn that there exist containers using the volume before deleting it, we can consider that as a future enhancement.
- If you want Weave to re-create files in Docker volumes which have been deleted, we have no way to do that.
