### ISSUE TITLE
cannot start weave launch-plugin

### ISSUE THREAD

**Issue by joserivca** [weaveworks/weave#2528]
Hi guys,
 @rade @bboreham 
Accidentally im erase manually  a container folder cause i had a docker error ,
 now when launch weave plugin
appears this:
```
 weave launch-plugin
time="2016-09-27T22:58:07Z" level=fatal msg="Error response from daemon: Could not find container for entity id 0f069ce2a95d930e31454e503ceecf2882069a6149cc89289ef6f9d680c13d5a"
```
and i can´t start weave plugin, 

any ideas to fix this problem???

please need help!!

**Comment by bboreham** [comment]
Hi @joserivca ; can you please repeat with debug on:

    WEAVE_DEBUG=1 weave launch-plugin

**Comment by bboreham** [comment]
Closing for now; please re-open if you have further information.
