### ISSUE TITLE
Unable to pass --log-opt via WEAVE_DOCKER_ARGS

### ISSUE THREAD

**Issue by rvandegrift** [weaveworks/weave#2534]
I'm trying to customize the logging options for weave router:
```sh
 WEAVE_DOCKER_ARGS="--log-opt=awslogs-stream=weave-router" weave launch-router --no-discovery --no-dns
flag provided but not defined: --log-opt
See 'docker run --help'.
```

Should this work?

**Comment by bboreham** [comment]
I think you have hit #582, sorry

We embed an older Docker client, currently version 1.6.2, and the options get passed to that version.

Updating it is slated for Weave Net 1.8 - #2395

**Comment by rvandegrift** [comment]
Yep, that's right.  Closing as duplicate.
