### ISSUE TITLE
weave attach --rewrite-hosts sporadically fails

### ISSUE THREAD

**Issue by SpComb** [weaveworks/weave#2559]
There seems to be some race condition with the the implementation of `weave attach --rewrite-hosts` in the following [system configuration](https://gist.github.com/SpComb/f56d21c75507a13c22889eea7611ba21#file-docker-info):
- Ubuntu xenial Linux 4.4
- Weave 1.7.2
- Docker 1.12 (both Ubuntu `docker.io=1.12.1-0ubuntu13~16.04.1` and upstream `docker-engine=1.12.2-0~xenial`)
  - Storage Driver: overlay

The `weave attach --rewrite-hosts` operation will sometimes succeed, and sometimes fail with an error:

```
Error response from daemon: Driver overlay failed to remove root filesystem cc8482b244b5066b1d42f3a4e7a4352abba5bb79f431a2620806b993934f8938: remove /var/lib/docker/overlay/ea588807154a1a3b04c5ff3db248f9055695fca5fe21df8341e40b11104fff90/merged/sbin: directory not empty
```

This causes the container to remain detached from weave (no `ethwe` interface), and leaves large numbers of dead weaveexec containers in [`docker ps -a`](https://gist.github.com/SpComb/f56d21c75507a13c22889eea7611ba21#file-docker-ps).

This happens fairly consistently for me on a three-node cluster of DigitalIOcean nodes using their ubuntu-16-04-x64 image, leaving the majority of containers detached.

More detailed [debugging](https://gist.github.com/SpComb/f56d21c75507a13c22889eea7611ba21#file-docker-logs-a2213cd16023-L226) shows that this errors happens in `rewrite_etc_hosts()`:

```
+ docker run --rm --net=none -e WEAVE_CIDR=none --privileged -v /var/lib/docker/containers/2b39aafa954c370e4f950cac2ed4114197809d77c254570bcebf10281736dc05:/container --entrypoint=sh weaveworks/weaveexec:1.7.2 -c echo '# created by Weave - BEGIN ... > /container/hosts && rm -f /container/hosts && echo '# created by Weave - BEGIN ... END' > /container/hosts
time="2016-10-25T13:46:50Z" level=fatal msg="Error response from daemon: Driver overlay failed to remove root filesystem e58b019d3e9bd44580e01607422cff527275621243046e25263844117ef90522: remove /var/lib/docker/overlay/96cf34987cc5b1c9d07de939c33726d7364f4e0927a5d9a51083349b5e81f02b/merged/sbin: directory not empty" 
```

It's not exactly the same error, but this may be related to sharing mounts between namespaces: https://github.com/docker/docker/issues/26372

>  This error is returned from the kernel when trying to remove container rw layers and/or the container config root... typically due to mounts leaked into other namespaces.

**Comment by SpComb** [comment]
BTW it seems like the `--rewrite-hosts` is not the only case that's failing with this error, even the top-level `weaveexec` container that we're running is failing with that error when deleting it via the Docker API:

```
Oct 26 11:36:17 terom-xenial-node3 docker[4970]: Docker::Error::ServerError: Driver overlay failed to remove root filesystem 8a39ea400ec0b919edda8e3786097a5b257569f07c0ae57aaac672072cbc763b: remove /var/lib/docker/overlay/55fbeb6a0a0845fffed1d4fb380f5f417c63a779fd6d4f9b9c0a064927288348/merged/sbin: directory not empty
Oct 26 11:36:17 terom-xenial-node3 docker[4970]:         /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:50:in `rescue in request'
Oct 26 11:36:17 terom-xenial-node3 docker[4970]:         /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:38:in `request'
Oct 26 11:36:17 terom-xenial-node3 docker[4970]:         /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
Oct 26 11:36:17 terom-xenial-node3 docker[4970]:         /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.26.2/lib/docker/container.rb:213:in `remove'
Oct 26 11:36:17 terom-xenial-node3 docker[4970]:         /app/lib/kontena/network_adapters/weave.rb:191:in `exec'
Oct 26 11:36:17 terom-xenial-node3 docker[4970]:         /app/lib/kontena/network_adapters/weave.rb:244:in `connect_peers'
Oct 26 11:36:17 terom-xenial-node3 docker[4970]:         /app/lib/kontena/network_adapters/weave.rb:232:in `start'
```

This error happens when using the `DELETE /containers/...` API - adding in `?force=1` silences it, but leaves the dead Docker container/overlayfs mounts hanging around on the system.

Not entirely sure how the Docker Engine implementation works, but looking at the overlayfs mount point in question after the fact looks weird:

```
$ ls -la /var/lib/docker/overlay/55fbeb6a0a0845fffed1d4fb380f5f417c63a779fd6d4f9b9c0a064927288348/merged/
total 0
$ ls -la /var/lib/docker/overlay/55fbeb6a0a0845fffed1d4fb380f5f417c63a779fd6d4f9b9c0a064927288348/merged/sbin
total 2424
drwxr-xr-x  2 root root   4096 Oct 24 12:07 .
drwxr-xr-x  1 root root      0 Oct 26 11:36 ..
lrwxrwxrwx  1 root root     12 Sep 22 23:30 acpid -> /bin/busybox
lrwxrwxrwx  1 root root     12 Sep 22 23:30 adjtimex -> /bin/busybox
-rwxr-xr-x  7 root root  43872 Jun 17 16:40 agetty
-rwxr-xr-x 15 root root 202240 May 27 09:25 apk
lrwxrwxrwx  1 root root     12 Sep 22 23:30 arp -> /bin/busybox
...
```
The `sbin` subdir in question is missing from the the top-level mountpoint?

**Comment by awh** [comment]
@SpComb thanks!

**Comment by awh** [comment]
Original report via Slack: https://weaveworks.slack.com/archives/weave-users/p1477404926002570

**Comment by SpComb** [comment]
This has also started to happen recently on my CoreOS Beta 1235.2.0 vagrant node, when using the default Docker overlayfs volume driver.

**Comment by bboreham** [comment]
@SpComb I tried to replicate your symptoms: I created a CoreOS 1235.2.0 node [via Vagrant](https://coreos.com/os/docs/latest/booting-on-vagrant.html), and then ran a bunch of containers attached to Weave Net, using both `weave run` and the Weave Proxy.  I did not observe any errors.

Any ideas how I can get closer to the set-up you are using?

**Comment by SpComb** [comment]
Did you specifically test with `attach --rewrite-hosts?` I need that flag to repro this, it doesn't happen without it.

Other than that I'm not at all sure. It happens fairly consistently (30-50%) on those nodes where it does happen, but it doesn't happen on all nodes. It must be some Docker overlayfs driver that is specifically tickled by how weave's `--rewrite-hosts` is implemented.

I'll try wiping out `/var/lib/docker` and see if it continues.

**Comment by bboreham** [comment]
> Did you specifically test with `attach --rewrite-hosts`?

That is what the Proxy does by default.  However I went back and ran a bunch of those too, and did not observe any error messages.

**Comment by jnummelin** [comment]
I'm not sure yet how, but somehow it seems that cAdvisor messes things up and causes `weave attach` also to fail. If I run plain weave on `CoreOS 1235.2.0` everything seems to work ok. But when I start cAdvisor, things get messed up like @SpComb has reported. (I'm also from team Kontena :))

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /:/host --net host --pid host --privileged weaveworks/weaveexec:1.7.2 launch-router --ipalloc-range '' --password foobar

docker run -d --name redis redis

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /:/host --net host --pid host --privileged weaveworks/weaveexec:1.7.2 attach 10.81.128.111/16 --rewrite-hosts 1757647bf879
```

Everything works as expected.

But now when I launch cAdvisor using:
```
docker run -d -v /:/host:rw --net host --pid host --privileged --name cadvisor kontena/cadvisor:0.23.2 --docker_only --listen_ip=127.0.0.1 --port=8989 --storage_duration=2m --housekeeping_interval=30s
```

And after that run the attach again:
```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /:/host --net host --pid host --privileged weaveworks/weaveexec:1.7.2 attach 10.81.128.111/16 --rewrite-hosts 1757647bf879
time="2016-12-16T09:13:32Z" level=fatal msg="Error response from daemon: Driver overlay failed to remove root filesystem 5af457e9a86b3f14a20aec4627a2f140d669ca1c2fd20b54300c3802a702a247: remove /var/lib/docker/overlay/0e101f21de8757d705dd68b8549a0f83a49eb8b180a32a37345833292deb3d9d/merged/media: directory not empty"
```
I get this pretty much 100% on attach now.

If I run the attach without `--rewrite-hosts` everything works as expected.

Any idea why and how cAdvisor messes this up?

**Comment by bboreham** [comment]
My sense is it has to do with recursive mounts - all the Docker files are under `/var/lib/docker/containers`, so when you bind-mount / under there the kernel gets confused.

See [some](https://github.com/docker/libnetwork/pull/223#issuecomment-142628796) [previous](https://github.com/weaveworks/weave/issues/1455) [investigations](https://github.com/weaveworks/weave/issues/1846) (with different symptoms, but all involving cAdvisor)

**Comment by brb** [comment]
@SpComb Was cAdvisor running when you experienced the problem?

@SpComb / @jnummelin Once you have experienced it again, could you run `sudo lsof $TROUBLE_PATH` from the host as it is described [here](https://docs.docker.com/engine/admin/troubleshooting_volume_errors/)?

**Comment by SpComb** [comment]
> @SpComb Was cAdvisor running when you experienced the problem?

Yes, it was. I should have already known better to include cAdvisor in this issue when reporting it, it's related to all of these mountns shenanigans.

**Comment by jnummelin** [comment]
@brb 
```
core@jussi-weave-test ~ $ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /:/host --net host --pid host --privileged weaveworks/weaveexec:1.7.2 attach 10.81.128.111/16 --rewrite-hosts 1757647bf879
time="2016-12-19T09:53:18Z" level=fatal msg="Error response from daemon: Driver overlay failed to remove root filesystem 0f87393df1875a6221c52320784d13316abb6967697c9b2b7df3a3ac30dcc006: remove /var/lib/docker/overlay/f2670ec17ce1cbaed1f4f783d9fd725005c713a7c5fd924729fb6a68dfcdd1f6/merged/media: directory not empty" 
core@jussi-weave-test ~ $ sudo lsof /var/lib/docker/overlay/f2670ec17ce1cbaed1f4f783d9fd725005c713a7c5fd924729fb6a68dfcdd1f6/merged/media
core@jussi-weave-test ~ $  sudo ls -lah /var/lib/docker/overlay/f2670ec17ce1cbaed1f4f783d9fd725005c713a7c5fd924729fb6a68dfcdd1f6/merged/media
total 40K
drwxr-xr-x. 5 root root 4.0K Dec 16 08:51 .
drwxr-xr-x. 1 root root    0 Dec 19 09:53 ..
drwxr-xr-x. 2 root root 4.0K Sep 22 23:30 cdrom
drwxr-xr-x. 2 root root 4.0K Sep 22 23:30 floppy
drwxr-xr-x. 2 root root 4.0K Sep 22 23:30 usb
```

`lsof` doesn't report anything to be hanging on that path but it's really not empty either. :/

If you want to debug further, it's really easy to reproduce with the steps in my previous comment. Or I can do some further digging also if needed.

**Comment by brb** [comment]
I'm closing this.

If you still experience the problem, please re-open it. Thanks.
