### ISSUE TITLE
Scope: show containers per user defined network

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#2571]
With many containers the scope overview easily gets cluttered up. In my situation the containters are partitioned in different user defined networks and I am often just interested in one network and associated containers. So, a feature request to add the (filter) option to Scope.

**Comment by awh** [comment]
Hi @bergtwvd - please refile at https://github.com/weaveworks/scope/issues - thanks!

**Comment by bboreham** [comment]
However, look at https://www.weave.works/wp-content/uploads/Screen-Shot-2016-08-12-at-12.42.53-PM.png, bottom left - there is a button 'Networks' which I think does what you are asking for.

**Comment by bboreham** [comment]
OK; it doesn't _filter_; it just highlights the ones attached to a network and dims the rest.

**Comment by bboreham** [comment]
You can type the name of a network into the search box at top left, e.g. `network:secure`.  That acts as a filter.

Example from our demo: http://cloud.weave.works/demo/#!/state/{"controlPipe":null,"topologyViewMode":"topo","nodeDetails":[],"pinnedMetricType":null,"pinnedSearches":["network:secure"],"searchQuery":"","selectedNodeId":null,"gridSortBy":null,"gridSortedDesc":null,"topologyId":"containers","topologyOptions":{"processes":{"unconnected":"hide"},"containers":{"system":"application","stopped":"running","pseudo":"hide"}},"showingNetworks":true}

**Comment by bergtwvd** [comment]
This version seems to be different from what I am using (from the website link Install Weave Scope),
Another version, called WeaveCloud version?

**Comment by rade** [comment]
The demo is running a [hosted version of Weave Scope on Weave Cloud](https://www.weave.works/guides/using-weave-scope-cloud-service-to-visualize-and-monitor-docker-containers/). The search functionality is present in the downloadable version of Weave Scope too.

How are you creating the "different user defined networks"?

**Comment by bergtwvd** [comment]
I use the standard docker overlay networking. Or do I need to use Weave overlay for this?

Sent from my Android phone using TouchDown (www.symantec.com)

-----Original Message-----

**Comment by rade** [comment]
> standard docker overlay networking.

That is fine. Can you post a screenshot of what you are seeing?

**Comment by bergtwvd** [comment]
Not needed anymore. For some reason I pulled an old version of scope using the launch script. I just pulled latest and get the same as you have now. Thanks.

**Comment by bergtwvd** [comment]
Just a final note: the Scope output looks great. Compliments!
