### ISSUE TITLE
host and internet connectivity in combination with Kubernetes

### ISSUE THREAD

**Issue by slintes** [weaveworks/weave#260]
Hi. I'm evaluating using weave in combination with docker, and have a setup running based on https://github.com/errordeveloper/weave-demos/tree/master/poseidon.
I have to issued with this setup:
1. I can not reach other hosts (e.g. for using etcd running on an other CoreOS instance. Workaround: run another etcd in a docker container)
2. I can not reach "the internet" (usecase: run an own docker registry in a container, which also builds the images itself, based on Dockerfiles hosted on github...)

I discussed this already with Ilya, and he pointed me to https://github.com/GoogleCloudPlatform/kubernetes/issues/15. While on the one hand that sounds somewhat reasonable to me (I'm not an network expert), I only can say that with flannel I have access to other hosts and to the internet...?

**Comment by alwansm** [comment]
Hello I am facing the same problem is there any update the previous solution didn't work
