### ISSUE TITLE
Go from sleeve to fastdp

### ISSUE THREAD

**Issue by cwolfinger** [weaveworks/weave#2600]
I have seen a few nodes that have connections which are in "sleeve" but all others are in "fastdp".  This seems to occur somewhat randomly and the node never goes back to fastdp - is it possible to force a connection back to "fastdp"?

**Comment by awh** [comment]
Hi @cwolfinger this is a known issue (#1737) - the only workaround available at the moment is to stop and restart the router I'm afraid.

**Comment by Cryptophobia** [comment]
This is a known issue and further debugging can be found here:

https://github.com/weaveworks/weave/issues/3252
