### ISSUE TITLE
weave-kube: document how to run 'weave status' command

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2603]
EDIT: For ease of finding, the process is:

1. find the name of a weave pod, e.g. `kubectl get pods -n kube-system`
2. `kubectl exec --n kube-system  <weave pod name> /home/weave/weave --local status`

_From @lukemarsden on September 15, 2016 11:6_

Given a k8s cluster with weave-kube installed, I'd like to be able to run `weave status` on each of the peers in the cluster, to inspect the health of the weave network. I believe this is possible with some `docker exec` or similar incantation, but it would be nice if this was documented in the README.

_Copied from original issue: weaveworks/weave-kube#5_

**Comment by awh** [comment]
_From @bboreham on September 27, 2016 13:1_

I think it's `kubectl exec <weave pod name> /home/weave/weave --local status`

Alternatively, you can hit the /status url on any of the weave pods.  But I don't know how to do that via kubectl.

**Comment by awh** [comment]
_From @Bregor on September 27, 2016 14:0_

`kubectl exec <weave pod name> --namespace=kube-system ...`

**Comment by awh** [comment]
_From @bboreham on September 27, 2016 14:3_

Thanks @bregor !

**Comment by bboreham** [comment]
From a discussion on weave-community Slack, other ways to go include:

* install the `weave` script
* use Weave Cloud (or Scope)

**Comment by bboreham** [comment]
Fixed in #3055

**Comment by brb** [comment]
Shall we close the issue?
