### ISSUE TITLE
Have Weave restrict itself to internal IP addresses

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2608]
_From @bboreham on October 5, 2016 11:0_

Some users report Weave connecting on hosts' external IPs when they would prefer it used internal IPs only.

placeholder pending more details

_Copied from original issue: weaveworks/weave-kube#23_

**Comment by bboreham** [comment]
Closing: kube-peers [only looked at internal IPs](https://github.com/weaveworks/weave/blame/402fe094f4c8c75f52bdc828f17cd17c456c3541/prog/kube-peers/main.go#L39) at the time this was filed, and currently will use an external only if no internal IP is known.
