### ISSUE TITLE
Improve persistence of IPAM data

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2610]
_From @bboreham on October 6, 2016 9:30_

Currently weave-daemonset.yaml specifies an `emptyDir` volume which is deleted when the pod is deleted. Since upgrading `weave-kube` require deleting the pods, this is unsafe.

Reading http://kubernetes.io/docs/user-guide/volumes/, I don't see an obviously better choice.

_Copied from original issue: weaveworks/weave-kube#27_

**Comment by awh** [comment]
_From @Bregor on October 6, 2016 10:5_

I think regular `hostPath` will suit this as well.
Example:

          volumeMounts:
            - mountPath: /weave_data
              name: data
    ...
      volumes:
        - name: data
          hostPath:
            path: /var/lib/weave-kube

**Comment by awh** [comment]
_From @bboreham on October 6, 2016 10:7_

Sure, but is there a `hostPath` we can guarantee to be able to write to on every Linux distro?

CoreOS, for instance, mounts loads of things read-only.

**Comment by awh** [comment]
_From @Bregor on October 6, 2016 10:9_

CoreOS mounts `/usr` for read-only, but `/var` and `/opt` are available to be overwritten.

**Comment by awh** [comment]
These may be of use:

http://kubernetes.io/docs/user-guide/petset/
http://kubernetes.io/docs/user-guide/persistent-volumes/

**Comment by awh** [comment]
_From @Bregor on October 12, 2016 9:38_

Petset without "normal" network fs is bloody hell. Regular `hostPath` will be much better for this task I mean.

**Comment by bboreham** [comment]
I changed this from a feature to a bug because we have more reports of trouble after deleting all Weave pods.

Note that we need to give some thought to whether a user would ever need to really clear out the data, after we made it more persistent, and if so how they would do that.  I.e. what is the equivalent of `weave reset` on Kubernetes?
