### ISSUE TITLE
`Element cannot be added` caused by delayed deletion of Succeeded/Failed pods

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2632]
_From @awh on October 28, 2016 10:12_

Pods which enter a phase of `Succeeded` or `Failed` are [not immediately destroyed](http://kubernetes.io/docs/user-guide/pod-states/#pod-lifetime):

> In general, pods which are created do not disappear until someone destroys them. This might be a human or a ReplicationController, or another controller. The only exception to this rule is that pods with a PodPhase of Succeeded or Failed for more than some duration (determined by the master) will expire and be automatically reaped.

Since such pods also appear to retain their podIP attribute, they are not withdrawn from any matching label selector ipsets; consequently, if that podIP is reissued to a new container it will cause an error:

```
add pod: ipset [add weave-3a)<C}f{Y(gA%7g3kj(imRlSe 10.36.0.4] failed: ipset v6.29: Elem    ent cannot be added to the set: it's already added
```

The above was deduced from the following logs, supplied by @davidchua (thanks!):

[weave-net.log.txt](https://github.com/weaveworks/weave-npc/files/558064/weave-net.log.txt)
[weave-npc.log.txt](https://github.com/weaveworks/weave-npc/files/558063/weave-npc.log.txt)

_Copied from original issue: weaveworks/weave-npc#26_

**Comment by awh** [comment]
GC of terminated pods is controlled by the `--terminated-pod-gc-threshold` argument to kube-controller-manager ([docs](http://kubernetes.io/docs/admin/kube-controller-manager/)) - these things can potentially hang around for a long time:

> Number of terminated pods that can exist before the terminated pod garbage collector starts deleting terminated pods. If <= 0, the terminated pod garbage collector is disabled. (default 12500)

**Comment by awh** [comment]
I have reproduced the podIP attribute retention, playing around with the following commands: 

```
root@k8s-01:~# kubectl run true --image alpine --restart=Never --command -- true
pod "true" created
root@k8s-01:~# kubectl run false --image alpine --restart=Never --command -- false
pod "false" created
root@k8s-01:~# kubectl get pods -o wide -a
NAME      READY     STATUS      RESTARTS   AGE       IP          NODE
false     0/1       Error       0          12s       10.32.0.3   k8s-01
true      0/1       Completed   0          18s       10.32.0.3   k8s-01
```

Sometimes the IPs are removed after a while, sometimes they seem to persist. I have yet to figure out why.

**Comment by bboreham** [comment]
I investigated the Kubernetes behaviour; I find that the 'succeeded' behaviour is just a more obvious instance of the general pattern that it releases the IP address via CNI before removing the pod and therefore before `weave-npc` sees any change. Any new request for an IP can therefore get that just-released one.

**Comment by cdupont** [comment]
Hi,
I have this issue on deis (see https://github.com/deis/workflow/issues/612).
How can I use the fix? Should I compile weave from the source?

**Comment by ikatson** [comment]
@cdupont until the upstream is updated and the core devs can help you, here's what I did on a totally clean system

```
make
IMAGE=YOURIMAGE:$(git describe) 
docker tag weaveworks/weave-kube:latest "${IMAGE}"
docker push "${IMAGE}"
```

And then changed the image reference in the yaml file (i use a modified version of the one downloaded from ```curl -L https://git.io/weave-kube```)

**Comment by ikatson** [comment]
Did not help me, here's an excerpt:

```
root@master.somecluster [~] # kc logs weave-net-gy4xl -n kube-system -c weave-npc -p | tail -n 2
time="2016-11-23T00:27:23Z" level=info msg="adding entry 10.40.0.0 to weave-*******"
time="2016-11-23T00:27:23Z" level=fatal msg="add pod: ipset [add weave-******* 10.40.0.0] failed: ipset v6.29: Element cannot be added to the set: it's already added\n: exit status 1"
root@master.somecluster [~] # kc get pods --all-namespaces -o wide --show-all | grep 10.40.0.0
default               pod-37e316b27e76                                            0/2       Completed           0          1h        10.40.0.0       node-02.somecluster
```

**Comment by ikatson** [comment]
I'm sorry, did not test correctly. I only changed the "weave-net" image, but forgot to change the "weave-npc" one, so I take back the message above

**Comment by cdupont** [comment]
@ikatson Thanks, what is the value of YOURIMAGE?

**Comment by ikatson** [comment]
@cdupont the image in a docker registry, that you are going to use. In my case it was ```ikatson/weave-npc```. It resulted in ```ikatson/weave-npc:v1.8.0-45-gc3a2539```. You can use that image easily, but depending on how concerned you are about running arbitrary docker images, it might be easier to build your own one using the steps above

**Comment by cdupont** [comment]
I see, and once the image name replaced in weave-kube.yaml, I have to do:
```
kubectl delete -f weave-kube.yaml
kubectl apply -f weave-kube.yaml
```
Is that correct?

**Comment by awh** [comment]
@cdupont 

> Is that correct?

Not quite - you don't need the `delete`, and you need to do some things after - the upgrade procedure is documented here https://www.weave.works/docs/net/latest/kube-addon/.

**Comment by awh** [comment]
BTW we are doing an official 1.8.1 release today that will include this fix.

**Comment by cdupont** [comment]
Thanks, so I just need to do the "Upgrading" section (apply file then delete pods)?

**Comment by awh** [comment]
Yes.

**Comment by keontang** [comment]
It seems i still have ipset error：

```
INFO: 2017/02/09 10:21:17.411430 adding entry 192.168.64.178 to weave-iuZcey(5DeXbzgRFs8Szo]<@p
FATA: 2017/02/09 10:21:17.414638 add pod: ipset [add weave-iuZcey(5DeXbzgRFs8Szo]<@p 192.168.64.178] failed: ipset v6.29: Element cannot be added to the set: it's already added
: exit status 1
```

weave version:

```
cargo.caicloudprivatetest.com/caicloud/weave-npc                          git-c1023eaf184c    f6c2948496b4        2 weeks ago         58.08 MB
cargo.caicloud.io/caicloud/weave-kube                                     git-c1023eaf184c    c20e4e8d6139        2 weeks ago         153.2 
```

**Comment by bboreham** [comment]
@keontang could you (a) open your own issue, not tag along to a closed one and (b) post the whole log-file ? It is intentionally verbose so we can figure out what went wrong.

**Comment by bboreham** [comment]
I'm going to assume #2779 is the same issue.
