### ISSUE TITLE
segmentation fault using weave 1.8.0

### ISSUE THREAD

**Issue by girishramnani** [weaveworks/weave#2638]
I am using weave 1.8.0 to deploy a 3 node cluster. The weave application is started using `systemd` ( its a unit file ).  This is the unit 
``` 
    - name: weave-net.service
      command: start
      content: |
        [Unit]
        Description=Weave Network
        Documentation=https://weave.works/
        After=docker.service
        Requires=docker.service
        After=install-weave.service
        Requires=install-weave.service

        [Service]
        Environment="WEAVE_DOCKER_ARGS=--env='LOGSPOUT=ignore'"
        Restart=always
        RestartSec=30s
        ExecStartPre=/opt/bin/weave launch --http-addr 0.0.0.0:6784
        ExecStart=/usr/bin/docker attach weave
        ExecStop=/opt/bin/weave reset ; /opt/bin/weave stop
```
I am using a coreos instance and using `userdata` to start all the unit files on Digital Ocean. A segmentation error happens. this the journalctl output

```
 systemd[1]: Starting Weave Network...
 weave[1544]: Segmentation fault (core dumped)
 systemd[1]: weave-net.service: Control process exited, code=exited status=1
 systemd[1]: Failed to start Weave Network.
 systemd[1]: weave-net.service: Unit entered failed state.
 systemd[1]: weave-net.service: Failed with result 'exit-code'.
 systemd[1]: weave-net.service: Service hold-off time over, scheduling restart.
 systemd[1]: Stopped Weave Network.
 systemd[1]: Starting Weave Network...
 weave[1711]: Inconsistent bridge state detected. Please do 'weave reset' and try again.
 systemd[1]: weave-net.service: Control process exited, code=exited status=1
 systemd[1]: Failed to start Weave Network.
 systemd[1]: weave-net.service: Unit entered failed state.
 systemd[1]: weave-net.service: Failed with result 'exit-code'.
 systemd[1]: weave-net.service: Service hold-off time over, scheduling restart.
 systemd[1]: Stopped Weave Network.
 systemd[1]: Starting Weave Network...
 weave[1856]: Inconsistent bridge state detected. Please do 'weave reset' and try again.
 systemd[1]: weave-net.service: Control process exited, code=exited status=1

```

## Docker info - 

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64
```

### Expected outcome

the weave system should have started successfully without any segmentation fault.

**Comment by awh** [comment]
Hi @girishramnani 

Thanks for the report. Can you try adding `WEAVE_DEBUG=1` to the environment, reboot the machine and paste the journalctl output?

Also bear in mind that when starting weave with systemd, we recommend that you pass the `--no-restart` flag to avoid fighting with Docker - see https://www.weave.works/docs/net/latest/operational-guide/tasks/#start-on-boot

**Comment by bboreham** [comment]
@girishramnani do you have any more data to help us analyze this failure?

**Comment by girishramnani** [comment]
Actually this error doesn't happen in every case, I am trying to reproduce it using `WEAVE_DEBUG=1` and will provide the data ASAP.

**Comment by girishramnani** [comment]
hello, so i was able to replicated the error. this is the error log
https://gist.github.com/158d92537c5da2b6a83ab11b9e05ba32

**Comment by brb** [comment]
Thanks for the logs. A few questions:

* Which OS / Kernel do you run on?
* Do you have the following kernel modules on your nodes: `openvswitch`, `vxlan`, `vport_vxlan`?
* Maybe you have the coredump?

**Comment by girishramnani** [comment]
I am using coreos stable 1185.3.

This is the release note which gives info about the kernel and docker
versions.
https://coreos.com/releases/#1185.3.0.

I am not sure about which kernel modules are installed. Would output of
`lsmod` give that info?

**Comment by brb** [comment]
`lsmod` shows you only loaded modules. You could try to load them manually and see if any fails: `modprobe openvswitch`, `modprobe vxlan`, `modprobe vport_vxlan` (order is important).

Also, maybe you have a kernel log (`dmesg`)?

**Comment by awh** [comment]
@brb it seems to me that if https://github.com/weaveworks/weave/blob/master/common/odp/odp.go#L23 returns `NetlinkError(syscall.EEXIST)`, the function will continue until it reaches https://github.com/weaveworks/weave/blob/master/common/odp/odp.go#L40 which will segfault due to a null `dpif` field inside the datapath handle.

**Comment by awh** [comment]
Specifically here: https://github.com/weaveworks/go-odp/blob/master/odp/vport.go#L197

**Comment by brb** [comment]
From the logs it seems that the datapath didn't exist at the time of creation:

```
 weave[1819]: + detect_bridge_type
 weave[1819]: + BRIDGE_TYPE=
 weave[1819]: + [ -d /sys/class/net/datapath ]
 weave[1819]: + [ -d /sys/class/net/weave ]
 weave[1819]: + return 1 # <--- no bridge detected
 weave[1819]: + BRIDGE_TYPE=bridge
 weave[1819]: + [ -z  ]
 weave[1819]: + BRIDGE_TYPE=bridged_fastdp
 weave[1819]: + [ -n  ]
 weave[1819]: + util_op create-datapath datapath
 weave[1819]: + command_exists weaveutil
 weave[1819]: + command -v weaveutil
 weave[1819]: + weaveutil create-datapath datapath
 weave[1819]: Segmentation fault (core dumped)
```

So, it might have failed with some other error than `EEXIST`.

**Comment by awh** [comment]
In that case we would return without a segfault https://github.com/weaveworks/weave/blob/master/common/odp/odp.go#L25

**Comment by awh** [comment]
Hi @girishramnani 

It looks like this bug is a race condition triggered by Docker and systemd competing to start the router at the same time, due to the aforementioned `--no-restart` issue. To fix it, perform the following steps on each node:

* Add the `--no-restart` flag to the `weave launch` command in your systemd unit file
* Manually issue `weave reset` to remove the existing weave containers from Docker as they will have a restart policy of always
* Reboot

**Comment by girishramnani** [comment]
hello,
this is how my `weave-net.service` file looks like 

```

[Unit]
Description=Weave Network
Documentation=https://weave.works/
After=docker.service
Requires=docker.service
After=install-weave.service
Requires=install-weave.service

[Service]
Environment="WEAVE_DOCKER_ARGS=--env='LOGSPOUT=ignore'"
Environment="WEAVE_DEBUG=1"
Restart=always
RestartSec=30s
ExecStartPre=/opt/bin/weave launch --no-restart --http-addr 0.0.0.0:6784
ExecStart=/usr/bin/docker attach weave
ExecStop=/opt/bin/weave reset ; /opt/bin/weave stop

[Install]
WantedBy=multi-user.target

```

even after adding the no restart I am getting the seg fault.
this is the log.
https://gist.github.com/e6f858318c23cf272e45958386c62619

**Comment by awh** [comment]
@girishramnani can you paste me the output of `docker inspect weave` on that node? Thanks.

**Comment by girishramnani** [comment]
also i did 

```
sudo modprobe openvswitch
sudo modprobe vxlan
sudo modprobe vport_vxlan

```
This is the dmesg output
https://gist.github.com/1a7bc01b4cd65c95293f107286e62f43

**Comment by girishramnani** [comment]
```

[]
Error: No such image or container: weave

```

**Comment by girishramnani** [comment]
i mean the container fails as it starts, so can we `inspect` it?

**Comment by brb** [comment]
@girishramnani thanks. Is the dmesg output after the reboot? if not, could you include such?

**Comment by girishramnani** [comment]
the servers were online since 3 hrs for the logs that i sent. i am sharing this output which i took after a reboot.
https://gist.github.com/girishramnani/e6b07df2f4eb73e6fe3b629ba1db230c

**Comment by brb** [comment]
Another similar bug report: https://gist.github.com/jakolehm/72ed5feca99f8a90e7fccc4b1fc05a93

**Comment by SpComb** [comment]
We're continuing to see `Segmentation fault (core dumped)` -> `Inconsistent bridge state detected. Please do 'weave reset' and try again.` during inital startup with Weave 1.7.2 on Kontena 1.0.2, which includes the fix for https://github.com/kontena/kontena/issues/1530 that lead to multiple concurrently running weave startup commands.

```
E, [2016-12-20T09:36:11.201456 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "...", "--trusted-subnets", ""]
weave is already running; you can stop it with 'weave stop-router'.
I, [2016-12-20T09:36:11.264815 #1]  INFO -- Kontena::NetworkAdapters::Weave: attaching router
E, [2016-12-20T09:36:12.553573 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "attach-router"]
Segmentation fault (core dumped)
E, [2016-12-20T09:36:13.681063 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 7: ["--local", "connect", "--replace", "..."]
curl: (7) Failed to connect to 127.0.0.1 port 6784: Connection refused
I, [2016-12-20T09:36:13.714326 #1]  INFO -- Kontena::NetworkAdapters::Weave: router connected to peers ...
I, [2016-12-20T09:36:13.714466 #1]  INFO -- Kontena::NetworkAdapters::Weave: using trusted subnets:
E, [2016-12-20T09:36:14.466956 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "expose", "ip:10.81.0.3/16"]
Inconsistent bridge state detected. Please do 'weave reset' and try again.
E, [2016-12-20T09:36:14.571925 #1] ERROR -- Kontena::NetworkAdapters::Weave: Failed to expose host node at cidr=10.81.0.3/16
```

In this case I'm fairly sure there was only one `weaveexec launch-router` -> `weavexec attach-router` command series running.

**Comment by bboreham** [comment]
@SpComb it would be good to get some more information about what is core-dumping and why.

Most of Weave Net is written in Go which tends to produce a goroutine dump on crashes, so I'm wondering if it is one of the ancilliary processes.

**Comment by bboreham** [comment]
I'm going to close this as we merged a fix to the only bug we found so far; please re-open if more information comes up that points to a different bug.
