### ISSUE TITLE
Weave Net can create looping flow rules when hairpin is turned on on the bridge veth

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2650]
Analysis from @awh:

Consider the following simple configuration with two containers A and B connected to the weave bridge:
````
  A                     B
  +                     +
  |                     |
  |                     |
+-+---------------------+-+
| 2                     3 |
|                weave    |
| 1                       |
+-+-----------------------+
  |
  |
  |
  |
+-+-----------------------+
| vport1                  |
|               datapath  |
| vxlan vport             |
+-------------------------+

````

Furthermore, imagine that there are no flow rules, and that neither the weave bridge nor the fastdp bridge implementation have learnt any MAC addresses yet. Then:

1. A sends a packet to B
2. The weave bridge learns A=2, and floods the packet out of 1 & 3
3. B receives the packet but does not respond
4. The router miss handler receives the packet on vport1, learns that A=vport1, and floods the packet out of the vxlan vport
5. The weave bridge A=2 entry expires
6. B sends a packet to A
7. The weave bridge learns that B=3, and floods the packet out of 1 & 2
8. The router miss handler receives the packet on vport1, learns that B=vport1, installs a flow 'B->A in vport1 send to vport1', and sends the packet out of vport1
9. The weave bridge receives the B->A packet on 1, and learns that B=1. Depending on whether A responded after 7, it may have learnt A=1 or not; it either floods 1 & 3 or sends to 1 (it doesn't actually matter)
10. A responds to B
11. The weave bridge learnt in 9 that B=1, so it sends to 1
12. The router miss handler receives the packet on vport1, installs a flow 'A->B in vport1 send to vport1', and sends the packet out of vport1
13. The weave bridge receives the A->B packet on 1, and learns that A=1. Forwards packet out of 1
14. The weave bridge now thinks A and B are associated with port 1, and the router thinks (both in terms of MAC table and installed flow rules) that A and B are associated with vport1. Packets circulate continuously.

Step 13 requires hairpin to be turned on; one possible cause of this is https://github.com/kubernetes/kubernetes/issues/19766

**Comment by brb** [comment]
Fixed by https://github.com/weaveworks/weave/pull/2674
