### ISSUE TITLE
Docker Engine Plugin-v2

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2652]
Docker Engine has introduced a new way to distribute plugins. It's called plugin-v2 and docs can be found [here](https://github.com/docker/docker/blob/1.13.x/docs/extend/index.md).

In short:

* A plugin is distributed as a Docker image which is hosted at Docker Hub.
* Image should contain plugin configuration files which, in addition, include run-time parameters.

If Plugin is distributed in the plugin-v2 way, a user will be able to install and use it by:
```bash
$ docker plugin install weaveworks/plugin
$ docker plugin set weaveworks/plugin args="host1 host2 host3"
$ docker network create -d weavemesh <...>
```

One way to make it happen is to bundle Router with Plugin, as Plugin-v2 expects only a single executable.

Please note that _"there is an ongoing effort in getting plugin-v2 work in swarmkit as well"_, so Weave Plugin (v2) won't work with Docker Swarmkit.

More to follow up after getting responses from Docker.

/cc @lukemarsden

**Comment by rade** [comment]
This is a dup of #2397.
