### ISSUE TITLE
use a pid0 wrapper in the containers

### ISSUE THREAD

**Issue by chrislovecnm** [weaveworks/weave#2654]
So we use dumb-init, and I would recommend that you weave uses something like that.  

We believe that `ulogd` was left hanging by a parent pid, and the risk of that happenning may be lessened by using a wrapper like dumb-init.  I am not a docker / container expert, so please let me know if I am wrong.

https://github.com/weaveworks/weave/issues/2653 <- issue that nail me.

**Comment by chrislovecnm** [comment]
We need this in.  Did an upgrade on a cluster last night 1.8 -> 1.8.1 and none of the pods would terminate.  I had to delete process by hand, docker kill would not work.

I assume that this change would help, and probably am going to need to test. What technology would you guys like to use?  dumb-init?  tini?

cc: @bboreham @errordeveloper

**Comment by awh** [comment]
@chrislovecnm I'm not convinced this will help (or is even appropriate) - the weave-kube containers from in the host PID space - see https://github.com/weaveworks/weave/issues/2653#issuecomment-263624014

**Comment by chrislovecnm** [comment]
Are you saying that this is resolved in 1.8.1?  Sorry kinda confused.

> Further analysis: weave-kube runs with hostPID: true, in which case docker should clean up any leftover containers in the container cgroup when the main process exits unexpectedly (see https://github.com/opencontainers/runc/blob/f59ba3cdd76fdc08c004f42aa915996f6f420899/libcontainer/state_linux.go#L41-L45).

The main process is not exiting.  `weaver` is not being killed, and `docker kill` is even failing.

**Comment by awh** [comment]
> Are you saying that this is resolved in 1.8.1?

**Comment by awh** [comment]
> The main process is not exiting. weaver is not being killed, and docker kill is even failing.

Thanks - this is a different symptom to the original issue, where we had an orphaned ulogd left over - investigating further.

**Comment by bboreham** [comment]
Just to emphasise the point about weave-kube running in the host namespace:

````
# kubectl apply -f https://git.io/weave-kube
daemonset "weave-net" created
root@host1-7312-0:~# docker ps | grep launch
91810cd20f68        weaveworks/weave-kube:1.8.1                                     "/home/weave/launch.s"   1 seco
nds ago        Up Less than a second                       k8s_weave.507dacf8_weave-net-pdx0b_kube-system_72447991-
b7df-11e6-8086-42010af00008_25e554de
# docker exec -ti 91810cd20f68 ps -eaf | grep weave
 7215 root       0:00 {launch.sh} /bin/sh /home/weave/launch.sh
 7562 root       0:00 /home/weave/weaver --port=6783 --datapath=datapath --http
 7749 root       0:00 /usr/bin/weave-npc
 8886 root       0:00 grep --color=auto weave
````

The Weave Net process is not pid 1 inside the container, so we would not anticipate any issues or any benefit from adding an init.

**Comment by chrislovecnm** [comment]
well if I have time I will write up instructions to recreate :)

**Comment by awh** [comment]
I have filed #2684 to cover the new symptom introduced here https://github.com/weaveworks/weave/issues/2654#issuecomment-263913191, and am closing this because it's not appropriate to introduce an init process in a container running in the host PID space.
