### ISSUE TITLE
docker container versioning in weave-kube.yaml

### ISSUE THREAD

**Issue by chrislovecnm** [weaveworks/weave#2655]
So I am noticing that you are using `latest` tag in the yaml, and I have had production outages with other yaml, where it downloaded incompatible versions.

I would ask that you have a release process that versions the containers :)  Or am I using the wrong yaml?

**Comment by awh** [comment]
> I would ask that you have a release process that versions the containers :)

We do that, dating back to weave 0.7.0.

https://github.com/weaveworks/weave/blob/master/docs/release-process.md
https://github.com/weaveworks/weave/blob/master/bin/release

> Or am I using the wrong yaml?

You're using the wrong YAML - the one at https://github.com/weaveworks/weave/blob/master/prog/weave-kube/weave-daemonset.yaml is the development version for master continuous builds. Check here:

https://github.com/weaveworks/weave/releases

for versioned `weave` script and YAML files; these refer to specific tagged image versions that are guaranteed to be immutable. The following URLS

https://git.io/weave
https://git.io/weave-kube

always point to the files under https://github.com/weaveworks/weave/releases/tag/latest_release, which is updated whenever we do a release.

**Comment by chrislovecnm** [comment]
CLOSING :)
