### ISSUE TITLE
IP subnet clashes in weave-kube are hard to diagnose

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2669]
User had machines on 10.43.154.128/26 which resulted in the following routing table after starting Weave:

````
default via 10.43.154.129 dev eth0  proto dhcp  src 10.43.154.180  metric 1024
10.32.0.0/12 dev weave  proto kernel  scope link  src 10.32.0.2
10.43.154.128/26 dev eth0  proto kernel  scope link  src 10.43.154.180
10.43.154.129 dev eth0  proto dhcp  scope link  src 10.43.154.180  metric 1024
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
````

this blocked all traffic from leaving the machine, with sad consequences.

**Comment by bboreham** [comment]
This is (another) consequence of running a cut-down initialization; the weave script checks this and refuses to start if there is a clash.

**Comment by janwillies** [comment]
The issue is quite hard to debug, because there are many side-effects. Also it's kind of hidden at the moment, which CIDR weave uses, because the `weave-net.yaml` doesn't mention it. I'm running on kubernetes btw
