### ISSUE TITLE
Update documentation for Prometheus Endpoint /metrics

### ISSUE THREAD

**Issue by mmethner** [weaveworks/weave#2677]
Hi,

thanks for releasing the prometheus endpoint in 1.8.0.
Today my team tried to configure prometheus to scrape weave for metrics, but at first we were only able to scrape from localhost. After searching this repo we found, that its the WEAVE_STATUS_ADDR environment variable, which defaults to 127.0.0.1:6782, what makes weave only serve on localhost.

We set it to serve on eth0 as well to publish our metrics to the underlaying machine and scrape it throughout our cluster. That works fine.

Did we miss the documentation for that?
I only found https://www.weave.works/docs/net/latest/metrics/, were its not mentioned.
If missing yet, wouldnt it be a good idea to update the docs? Can I help with that?

Mathias

**Comment by bboreham** [comment]
Hi @mmethner, I agree 100% with your analysis.

Note that `weave-kube` has a different default, to listen on all interfaces.  We're a little more conservative with the `weave` script.

We'd love it if you added it into the docs - just submit a PR.

Also if you have any thoughts on improvements to the metrics please comment on #2557 or raise a new issue.

**Comment by mmethner** [comment]
@bboreham Ok, thanks for your reply.

I already forked the Repo and found metrics.md. I will submit the PR in the next days.

**Comment by brb** [comment]
Fixed by https://github.com/weaveworks/weave/pull/2680
