### ISSUE TITLE
Graph/table button doesn't resize nicely

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/weave#2681]
For presentation/demos I get a better result by zooming in (<kbd>⌘</kbd>+<kbd>+</kbd>) rather than using contrast mode.

However, when doing that the Graph/table buttons get a strange vertical alignment, with an odd surrounding border.

<img width="1256" alt="screen shot 2016-12-05 at 14 09 38" src="https://cloud.githubusercontent.com/assets/2362916/20886097/9b5bf6c0-baf4-11e6-916a-36f7a66e2517.png">

**Comment by bboreham** [comment]
@2opremio did you mean to file this in the Scope project?

**Comment by 2opremio** [comment]
Crap, yes, sorry
