### ISSUE TITLE
weave-kube weaver process does not always terminate cleanly

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2684]
Mentioned here https://github.com/weaveworks/weave/issues/2654#issuecomment-263913191:

> The main process is not exiting. weaver is not being killed, and docker kill on the weave contianer is even failing.

One possibility is that the `launch.sh` script is not propagating the kill signal from docker to its children under certain circumstances, leaving the weaver process running but unreachable by `docker kill`. If that is the case, we may investigate the possibility of `exec /home/weave/weaver` in the launch.sh, somehow arranging the expose & reclaim steps to be done afterwards.

**Comment by bboreham** [comment]
> One possibility is that the `launch.sh` script is not propagating the kill signal

I think that was badly phrased.  No process gets to do anything on a `SIGKILL`.

It's possible that the OS is propagating the signal because all the processes are in the same process group, or the shell may have set `PR_SET_PDEATHSIG` to kill the child.
