### ISSUE TITLE
Kubernetes > WeaveNet > use MAC address

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#2690]
When I use Docker Compose I can specify the MAC address of a container. This is needed because some containers require a specific MAC address for e.g. license purposes.

This is currently not possible to do via a Kubernetes Deployment yaml file. There is a discussion thread on this topic at https://github.com/kubernetes/kubernetes/issues/2289. The thread mentions on the end ``It is not something we support directly. It's possible that some network drivers support this via annotations, but I have not heard about it.``

Is this possible for WeaveNet?

**Comment by rade** [comment]
No. See #21.

**Comment by bergtwvd** [comment]
if / when would this be supported?

**Comment by rade** [comment]
Not anytime soon unless demand increases; you are the first person to ask for this, ever. That said... PRs welcome :)

**Comment by bboreham** [comment]
@bergtwvd do you need a _specific_ MAC address, or just a _consistent_ one?  I think #2691 would give you the latter, if you specified an IP address (which Weave already lets you do).

**Comment by bergtwvd** [comment]
In need to have a specific MAC address. In my situation the software license is checked-out against a given MAC address.

**Comment by CorneAussems** [comment]
Same situation here. 
With Docker mac-address option it is possible but k8s or weave its not.
So you got my vote !

**Comment by madhurnawandar** [comment]
I am also facing the same issue. Software licence is dependent on MAC and that's why looking for static MAC

**Comment by colek42** [comment]
I need this for a project as well.  Using docker-compose for now

**Comment by rafacuest** [comment]
The solution pointed by @colek42 works  but only with one replica and in bare metal environment and weave-net addon 
In EKS dosen't works.
Looking for a solution :(
