### ISSUE TITLE
Effect a 1:1 mapping between IP address and MAC address

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2691]
This will eliminate most "new container / stale arp entry" problems.

It seems to be standard practice for container overlay networks, e.g. https://github.com/containernetworking/cni/pull/196

**Comment by rade** [comment]
I am deeply suspicious of this. Duplicate IPs can happen. The sky won't fall down. With duplicate MACs it will.

**Comment by bboreham** [comment]
CNI is now backing this behaviour out, because it does not port to IPv6, so closing this.
