### ISSUE TITLE
The MAINTAINER keyword in Dockerfiles is deprecated

### ISSUE THREAD

**Issue by luxas** [weaveworks/weave#2705]
ref: https://github.com/docker/docker/pull/25466

It's straightforward to fix this; we just need to decide if we want to remove it completely or move to `LABEL maintainer "help@weave.works"` or similar.

cc @bboreham

**Comment by bboreham** [comment]
We might also want to follow this scheme: https://microbadger.com/labels

**Comment by luxas** [comment]
That sounds good

What does the chore label mean? low-hanging-fruit?

**Comment by bboreham** [comment]
chore: something that has to be done, but is neither a bugfix nor a feature
