### ISSUE TITLE
able to resolve dot-com, but not dot-org names, what?

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#2717]
This is very bizarre behavior.  Actually I seem to have at least these couple of issues at play:

* all the .org names I try to resolve with host or ping, yield:  `Host perlmonks.org not found: 2(SERVFAIL)`, but same message and error regardless of which dot-org name I try to resolve.  

* I get `Host puppet.mydomain.com not found: 3(NXDOMAIN)` for anything listed in my own domain, which is displayed by `weave status` with these results:  

```
        Service: dns
         Domain: mydomain.com.
       Upstream: $ip.for.providers.ns1, $ip.for.providers.ns2
            TTL: 1
        Entries: 1
```

I get this:
```
# weave status dns
nfs          10.0.1.25       20f6c15aa4b6 7a:2b:e2:33:29:74
```

but neither mtr (Failed to resolve host: Name or service not known), ping (unknown host), nor host (not found: 3(NXDOMAIN)) give me any joy finding containers on my network with either host names or fqdn's.  

What is working:  containers hosted on distinct docker hosts are able to ping one another by my assigned IPs.  I am able to resolve dot-com addresses in DNS using the tools mentioned above.  

Anyone here have any idea what I am looking at?  Is this related to my weave usage or my docker usage?  

-- Hugh

**Comment by bboreham** [comment]
Hi @hesco,

There is nothing in the Weave DNS code to prefer `.com` over `.org`; I have to guess that these replies are coming from your upstream DNS service.

**Comment by hesco** [comment]
Thanks.  Except that my host can resolve the .org names just fine.  Very strange.

**Comment by bboreham** [comment]
You could try `weave launch --log-level=debug` to see more detail about the DNS requests and responses.

**Comment by bboreham** [comment]
Closing.  If you get any information about Weave Net's involvement please re-open.
