### ISSUE TITLE
bug: kubernetes delete all weave pods cause duplicate IPs for differenetes pods

### ISSUE THREAD

**Issue by peiqi-caicloud** [weaveworks/weave#2719]
we use weave to provide networking service for kubernetes;

when we use kubectl delete pod --all --namespace=kube-system; It can easily cause duplicate IPs allocation. e.x: 192.168.67.0 for two different pods. 

after we delete one of the duplicated pods; the status of weave pod will recover to running from CrashBackOff.

We think this is a bug in IPAM, which may lack considering of IP allocation sync after weave restart.

**Comment by bboreham** [comment]
I think this is a duplicate of #2610.

Could you say a bit more about what prompted you to delete all the pods and/or why you expected things to work fine after you did that?

**Comment by bboreham** [comment]
I'm going to add a warning to the docs.
