### ISSUE TITLE
weave-kube does not work with `dockerd --iptables=false`

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#2726]
This configuration of docker is recommended in https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-worker.md; the problem is that we rely on docker to load the `br_netfilter` module, and it doesn't do so when `--iptables=false`.

On further investigation it turns out that loading the module from inside the weave-kube container is pretty straightforward; Alpine's busybox already implements `modprobe`, and other than that we need `-v /lib/modules:/lib/modules` and one of `--privileged` or `--cap-add SYS_MODULE`:

```
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine rmmod br_netfilter
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine lsmod|grep br_netfilter
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine modprobe br_netfilter
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine lsmod|grep br_netfilter
br_netfilter           24576  0 
bridge                126976  1 br_netfilter
```

**Comment by chrislovecnm** [comment]
I assume this is still open?

**Comment by marccarre** [comment]
Hi Chris, yes, still something to be resolved as far as I know.
