### ISSUE TITLE
Error launching weave from NixOS: chroot: can't execute 'readlink': No such file or directory

### ISSUE THREAD

**Issue by roberth** [weaveworks/weave#2733]
Steps to reproduce:

 - Run NixOS
 - Download the launch script as instructed by https://www.weave.works/docs/net/latest/installing-weave/
 - (Add set -x to top of script)
 - `$ weave launch --log-level=debug`

Actually I did not install to /usr/local/bin but to a user directory, but that does not seem to be the cause.

Error:

    + docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -v /:/host -e HOST_ROOT=/host -e DOCKERHUB_USER=weaveworks -e WEAVE_VERSION -e WEAVE_DEBUG -e WEAVE_DOCKER_ARGS -e WEAVEPROXY_DOCKER_ARGS -e WEAVEPLUGIN_DOCKER_ARGS -e WEAVE_PASSWORD -e WEAVE_PORT -e WEAVE_HTTP_ADDR -e WEAVE_STATUS_ADDR -e WEAVE_CONTAINER_NAME -e WEAVE_MTU -e WEAVE_NO_FASTDP -e WEAVE_NO_BRIDGED_FASTDP -e WEAVE_NO_PLUGIN -e DOCKER_BRIDGE -e DOCKER_CLIENT_HOST= -e DOCKER_CLIENT_ARGS -e PROXY_HOST=127.0.0.1 -e COVERAGE -e CHECKPOINT_DISABLE -e AWSVPC weaveworks/weaveexec:1.8.2 --local launch --log-level=debug
    chroot: can't execute 'readlink': No such file or directory

**Comment by roberth** [comment]
Working on it. Can't currently assign to myself.

**Comment by bboreham** [comment]
Why is this affected by the host?  It ought to be running inside a container at that point, which does contain the `readlink` executable.

> Add set -x to top of script

You can achieve this by setting `WEAVE_DEBUG` to nonblank before running.

**Comment by roberth** [comment]
The script chroots into the host to determine the right path as a one-liner. So it is actually inside a chroot inside a container.
It works quite well when it does, but it does not work on my machine, hence the fallback.
Alternatively, we can avoid the duplicate logic and always determine the link using some string processing, but I did not want to take that risk for a first contribution. It would make the container less dependent on the host.
Thanks for the hint!

**Comment by bboreham** [comment]
Ah, thanks, I had failed to spot that subtlety.
