### ISSUE TITLE
Weave using IPs from Terminated Pods before they're gone

### ISSUE THREAD

**Issue by dolsen-handy** [weaveworks/weave#2744]
We're using the latest (1.8.2) weave with kubernetes acting as Jenkins slaves. We've hit an issue where if we fire off many simultaneous jobs, weave will eventually assign an IP that's already in use.

kubectl output from an occurrence:
`jenkins                         kubernetes-2a1399f18ac344aeb03b9cb88ba86f51-1bf4b275bd071c   1/1       Terminating         0          1m        10.38.0.31    ip-10-6-8-109.ec2.internal`

`jenkins                         kubernetes-2a1399f18ac344aeb03b9cb88ba86f51-1bf4b97148a82e   1/1       Terminating         0          1m        10.38.0.44    ip-10-6-8-109.ec2.internal`

`jenkins                         kubernetes-2a1399f18ac344aeb03b9cb88ba86f51-1bf4c755811445   1/1       Running             0          24s       10.38.0.30    ip-10-6-8-109.ec2.internal`

`jenkins                         kubernetes-2a1399f18ac344aeb03b9cb88ba86f51-1bf4c75768d4e9   1/1       Running             0          24s       10.38.0.32    ip-10-6-8-109.ec2.internal`

`jenkins                         kubernetes-2a1399f18ac344aeb03b9cb88ba86f51-1bf4c75ad7d187   1/1       Running             0          24s       10.38.0.31    ip-10-6-8-109.ec2.internal`

The moment this happens, weave-npc (on all members of the cluster) will crash with an ipset dupe error:
`time="2017-01-19T23:06:21Z" level=fatal msg="add pod: ipset [add weave->6D5jc_ahi2?fJ^N;K(dAGv<S 10.38.0.31] failed: ipset v6.29: Element cannot be added to the set: it's already added\n: exit status 1"`

The issue is reproducible as soon as we apply significant load to the cluster. Let me know if I can provide any other information.

**Comment by bboreham** [comment]
Hi, can you supply the full logs from one of the `weave-npc` containers that crashes please?

**Comment by bboreham** [comment]
@dolsen-handy are you able to supply the logs? 

One other question: do the `weave-npc` containers restart just once and then keep going, or do they restart continuously?

**Comment by dolsen-handy** [comment]
The logs were in ES and tough for me to pull. Unfortunately we had a time crunch and decided to switch to flannel for our networking.

If time permits, I will try to spin up a dev cluster and re-create this issue.

**Comment by bboreham** [comment]
OK, I'll close this for now; if you get more information please re-open.

**Comment by bboreham** [comment]
#2795 will stop this being a problem

**Comment by dolsen-handy** [comment]
Nice, looking forward to trying weave again. Thanks!
