### ISSUE TITLE
Weave failed to setup network in our kubernetes productive env

### ISSUE THREAD

**Issue by peiqi-caicloud** [weaveworks/weave#2745]
Hello, we deployed weave with kubernetes in our production env. However weave failed to setup network.

I verified in container pause and there is no "eth0" inside as well as brctl show.

I saw logs in kubelet:

SetUpNetwork failed as follows:
cni unable to allocate IP address: Post http://127.0.0.1:6784/ip/6e2ef93b58f72b333164875c61f2d4623b0d253f9ebf9d4a5410d4  connection refused.

I think our configuration is good. 

The problem to me is that in our 40nodes cluster, there is 8nodes suffered such situations. the other 32 nodes are good.  the binary as well as the config are all same!

**Comment by peiqi-caicloud** [comment]
@rade

**Comment by bboreham** [comment]
Hi, could you post the log from the container running the `weave-kube` Image on that node please.

**Comment by peiqi-caicloud** [comment]
[logs-kube-weave.pdf](https://github.com/weaveworks/weave/files/721845/logs-kube-weave.pdf)

Hello, what surprised me is that kubelet even don't call SetUpNetwork method when creating a pod in these nodes.  
only report this: 

8    2177 summary.go:352] Missing default interface "eth0" for node:kube-node-16
2    2177 summary.go:352] Missing default interface "eth0" for pod:kube-system_fluentd-elasticsearch-v0.0.1-4reh5
0    2177 summary.go:352] Missing default interface "eth0" for pod:kube-system_monitoring-server-hjs3r
7    2177 summary.go:352] Missing default interface "eth0" for pod:kube-system_kube-push-v0.0.1-75wxp
0    2177 summary.go:352] Missing default interface "eth0" for pod:kube-system_peiqidebug
8    2177 summary.go:352] Missing default interface "eth0" for pod:kube-system_weave-net-m1wja
3    2177 summary.go:352] Missing default interface "eth0" for pod:kube-system_kube-proxy-kube-node-16

**Comment by peiqi-caicloud** [comment]
cc  @mqliang @reAsOn2010

**Comment by bboreham** [comment]
Thanks; that excerpt doesn't quite nail what happened; is the whole log available?  

Alternatively, can you supply the log from 192.168.16.111 at 17:47:24 so I can see why it dropped the connection. 

Also, that log doesn't look like it matches the original issue of "connection refused"; can you show the timestamp on that line so I can see how they match up?

As a work-around, try deleting that pod so it gets recreated. But I still want to understand why it failed.

**Comment by bboreham** [comment]
I'm confused by these statements:

> I saw logs in kubelet: SetUpNetwork failed

and

> kubelet even don't call SetUpNetwork method

Are you looking at different nodes?

**Comment by peiqi-caicloud** [comment]
At first it says SetUpNetwork failed cause cni config failed, but I verified the config is good. then I tested by create pod but I did not see any info about SetUpNetwork step.  only network status and return failed to find eth0, which is normal because weave have not setup the network.

I also added veth pair manually by ip link add test1 type veth peer name test2. and put test2 in the pause container, named it eth0 and give it an IP,  who's network should be setup by weave, and plugin test1 in weave bridge.  all work.

The problem to me is that I am not very familiar with weave code and architecture. 

I used launch.sh to launch the service, I am not sure if the CNI env parameters are take effect.
@bboreham

**Comment by bboreham** [comment]
Ok, if you are trying to debug this yourself, some pointers: 

This message: `Post http://127.0.0.1:6784/ip/6e2ef93b58f72b333164875c61f2d4623b0d253f9ebf9d4a5410d4 connection refused.` suggests the `weaver` process had crashed. Next step is to find out why it crashed. 

This message: `connection shutting down due to error ... connection reset by peer` means the other peer it was connected to did not like it - maybe due to incorrect password, mid-matched IP range, or some other issue. Next step is to find the message where a peer positively decides to reject a connection.

**Comment by brb** [comment]
I am closing this.

@peiqi-caicloud If you experience the problem again, please re-open the issue.
