### ISSUE TITLE
delete datapath interface, RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by peiqi-caicloud** [weaveworks/weave#2746]
Hello,

Someone has any idea of this error, it seems that the datapath interface is created directly by the kernel.

How can I configure the kernel to support the deletion directly by  "ip link delete  $1"command

**Comment by peiqi-caicloud** [comment]
I saw the driver is openvswitch, but apparently I have not installed the ovs and there is no daemon neither.
@dpw @bboreham 
[root@c7v204 ~]# ethtool -i datapath
driver: openvswitch
version:
firmware-version:
expansion-rom-version:
bus-info:
supports-statistics: no
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

**Comment by bboreham** [comment]
Weave Net provides the `weave reset` command to clear everything down and remove the `datapath` device. 

If you originally installed via `kubectl add` you would need to install the `weave` command as described at
