### ISSUE TITLE
Change log-level to DEBUG for proxy access

### ISSUE THREAD

**Issue by carlpett** [weaveworks/weave#2748]
Currently weave-proxy logs every request on INFO level. Unless the proxy is restarted, over time this builds up quite a large log. We're using a docker orchestrator (Helios) which polls the socket every few seconds, and loops for every container running. This equates to 11 GB over three months on our systems.

As per discussions on Slack (https://weaveworks.slack.com/archives/weave-users/p1485192505001247), this logging can probably be lowered to DEBUG level.

**Comment by bboreham** [comment]
I believe the line in the code is https://github.com/weaveworks/weave/blob/master/proxy/proxy.go#L228
