### ISSUE TITLE
Launch generator for weave-kube

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2754]
Currently, if a user wants to configure some parameter of weave-kube, such as the IP allocation range, we advise that they download a copy of the standard config, edit it and run from that edited copy. This is complex, error-prone and risks falling out of sync with changes in the standard config. 

Instead, we could generate the desired config on demand from a cloud service.

**Comment by brb** [comment]
Issue to track: https://github.com/weaveworks/launch-generator/issues/43
