### ISSUE TITLE
Weave Net daemonset not appearing in list

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/weave#2769]
When I run the ```weave-daemonset.yaml``` file locally from the Master on Kubernetes,  Weave Net runs (and it returns ```daemonset "weave-net" created```), but then it does not show up in the daemonset list.  As a result, it makes it a bit awkward for the user to disable weave net and troubleshoot problems without being able to delete the daemonset and re-running it: 

```kubectl get ds```

Returns the ```scope-agent``` just fine, but doesn't list ```weave-net```

I think some attributes are missing from the .yaml file to make it appear in the ds list properly.

**Comment by bboreham** [comment]
Can you try `--namespace=kube-system` or `--all-namespaces` ?

**Comment by abuehrle** [comment]
That works. I will update the list command in the docs for Scope.
