### ISSUE TITLE
Kubernetes: How to use WeaveDNS in name lookup

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#2776]
In issue https://github.com/weaveworks/weave/issues/2718 I attempt to do a DNS lookup from a non-Kubernetes container to a Kubernetes service.

But what about the other way around?

I.e. a Kubernetes container that wants to lookup the IP of a non-Kubernetes container on the same Weave Network. SkyDNS cannot resolve the name, thus the request should then go to WeaveDNS, and after that to the Google DNS. How can I make this work?

**Comment by bergtwvd** [comment]
While scanning some of the man pages I came across https://www.weave.works/docs/net/latest/cni-plugin.

At the bottom there is the statement:
````
Caveats

    The Weave Net router container must be running for CNI to allocate addresses
    The CNI plugin does not add entries to weaveDNS.
````

But what about containers that are started outside Kubernetes with the usual `docker run` command? These won't use the CNI interface, correct? And are therefore registered in DNS?

**Comment by bboreham** [comment]
I believe `kube-dns` could be given the address of `weave-dns` on the local host as an upstream provider. However I do not currently know how.

Also `kube-dns` is running `dnsMasq` which has the capability to route different domains to different upstream DNS.

For the second part, containers started outside of Kubernetes via the Weave Proxy or Plugin will be added to weave-dns, yes.

**Comment by brb** [comment]
I am closing this.

@bergtwvd if there are more unanswered questions, please re-open the issue. thanks.
