### ISSUE TITLE
DOCKER_HOST seems to be ignored by docker-compose

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#2778]
I have a weave network going (see https://github.com/weaveworks/weave/issues/2718), and have done
````
weave launch-proxy
eval $(weave env)
````

- I do the following
````
root@app-docker11:~/pitchcrc# docker run -it --rm alpine ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:258 (258.0 B)  TX bytes:258 (258.0 B)

ethwe     Link encap:Ethernet  HWaddr 2A:7E:DB:01:90:03
          inet addr:10.40.0.6  Bcast:0.0.0.0  Mask:255.240.0.0
          inet6 addr: fe80::287e:dbff:fe01:9003/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:90 (90.0 B)  TX bytes:132 (132.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
````

- Next, I create the following compose file
````
root@app-docker11:~/pitchcrc# more docker-compose-alpine.yml
version: '2'

services:
 alpine:
  image: alpine
  command: sleep 3600
````

And I do the following
````
root@app-docker11:~/pitchcrc# docker-compose -f  docker-compose-alpine.yml up -d
Creating network "pitchcrc_default" with the default driver
Creating pitchcrc_alpine_1
root@app-docker11:~/pitchcrc# docker exec -it pitchcrc_alpine_1 ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:12:00:02
          inet addr:172.18.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1296 (1.2 KiB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

root@app-docker11:~/pitchcrc# echo $DOCKER_HOST
unix:///var/run/weave/weave.sock
````

Note sure where the problem is, but docker-compose appears not to use the DOCKER_HOST setting.

````
root@app-docker11:~/pitchcrc# docker-compose -v
docker-compose version 1.10.0, build 4bd6f1a
````

**Comment by bboreham** [comment]
@bergtwvd I think what is happening is by default docker-compose creates a new network for your services, and this causes the Weave proxy to step back and not override that.

In #2402 you had a `networks` stanza in the docker-compose.yml file which requested to use the Weave network.  This would also cause the Weave proxy to step back - i.e. there would be no difference with or without the `DOCKER_HOST` setting.

I'm not sure if there is any way to request that docker-compose specify nothing about networking for the containers it creates, which would allow the Weave proxy to do its thing.

**Comment by bergtwvd** [comment]
So, to make this work for docker-compose I need to use the launch-plugin option in https://github.com/weaveworks/weave/issues/2718, correct?

> If you want the interface to be created as part of docker run you have two options:
> 
> Plugin: run weave launch-plugin then docker run --net=weave ...
> 
> Proxy: run weave launch-proxy then eval $(weave env) then docker run ...

I have not tried that option yet, since in that case I need to re-install my complete Kubernetes environment. I try to follow the standard steps as much as possible.

**Comment by bboreham** [comment]
OK, so you are using Weave Net with both Kubernetes and docker-compose?

You don't need to change what you are doing with Kubernetes; there is only one Weave network underneath everything, whether you join to it via proxy, plugin or `weave attach`.  Just try changing your docker-compose.yml file.

**Comment by bergtwvd** [comment]
I need to run a couple of containers outside Kubernetes (on WeaveNet) in order to use the mac-address option in docker-run.  I like to start those with with docker-compose (ultimately via a webbrowser UI).

What do you suggest that I change in the compose file?

**Comment by bboreham** [comment]
```
networks:
  default:
    external:
      name: weave
```

**Comment by bergtwvd** [comment]
I am still puzzling how to get this to work with docker-compose.

Above you refer to an external network; this needs to refer to the network that Kubernetes uses and that is created during the Kubernetes installation process. If I start my container on e.g. the  Kubernetes master node, I do not see a weave network listed with `docker network ls`, and this will therefore not work.

Using the following snippet in the docker-compose file
````
networks:
  default:
   driver: weave
````
does not work either: `plugin not found`. But this is what I actually expected since I did not install the plugin on this Kubernetes master node.

Thus, should I use the Weave plugin option?
Should I create a standard docker host node for this and somehow extend the weave network to that host, and not re-use one of the kubernetes nodes to run flat containers?

**Comment by bboreham** [comment]
Sorry, I had forgotten some of the history here.  I think I'm now repeating https://github.com/weaveworks/weave/issues/2718#issuecomment-270381077

My understanding is that docker-compose in "version 2" mode can only attach networks via a plugin.

The plugin would refuse to run because the (non-Kubernetes) `weave` container is not running; you would need to start that via `weave launch`.  You have talked about re-installing Kubernetes, but that should not be necessary; just remove the `weave-kube` daemonset and reboot all hosts, then install Weave as per https://www.weave.works/docs/net/latest/cni-plugin/

One random thought: perhaps it would be an option to use the "version 1" format, then the Weave Net proxy (via `DOCKER_HOST`) should work?

**Comment by bergtwvd** [comment]
I did the quick test with the "version 1" compose file: that works, a weave interface is created in each container.

I will try the other option later (I am constrained by time at the moment), which has my preference over v1 format compose files.

**Comment by bboreham** [comment]
I think everything is now covered or duplicating #2718, so I'l close this issue.

If you think something is outstanding please re-open.

**Comment by bergtwvd** [comment]
Yep, thanks!
