### ISSUE TITLE
Feature request: option to hide environment variables

### ISSUE THREAD

**Issue by mikebryant** [weaveworks/weave#2783]
We'd like to make weave scope available to all of our developers.
Many of the pods have secrets injected as environment variables. We'd like to be able to either have the scope app not show these, or have the probe not report them in the first place.

**Comment by bboreham** [comment]
Hi @mikebryant ; would you mind re-raising in https://github.com/weaveworks/scope ?

**Comment by mikebryant** [comment]
Sorry, that was dumb of me. I do know they're different things! :p
