### ISSUE TITLE
weave-net pod should not report ready if it fails to connect to any of the peers

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#2791]
I've had a firewall configuration issue where none of the peers where able to talk to each other, yet all pods reported ready. It would be much better UX if `kubectl get pods -n kube-system -l name=weave-net` reported that pods aren't ready.  This would need to be accoplished with `readinessProbe`.

 Additionally, I've discovered that this failure mode cause CNI plugin to block on IPAM and this wasn't indicated in container event log in any way, it just said that it got scheduled and is being created. Something to discussed upstream, I supposed.

**Comment by bboreham** [comment]
I'm not sure that a readiness probe would make it any easier to discover what is really wrong.  The broader issue is covered in #2612 .

We wanted to have Kubernetes directly aware of network readiness state - see https://github.com/kubernetes/kubernetes/pull/34398 for instance - but did not reach agreement on the approach.

**Comment by brb** [comment]
I'm closing this.

@errordeveloper could you move the proposal to #2612? thanks!
