### ISSUE TITLE
Document how to run weave-kube in 'guaranteed' mode

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2794]
Currently it is in 'burstable' mode.  [Link to description of modes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md)

Background: we set CPU "requests" in the Yaml, and we set them very low. If we set them higher then the pod won't start at all on a typical test cluster where api-server, kube-dns, etc., take up so much of the available resource.

But now the pod is classed as "burstable", and on a big cluster using more than we asked for, it's a favourite for Kubelet to kill ("evict").

It seems the Launch generator would be a good place to provide options for this, but in the short term we should at least document the issue and consider raising the default.  We could tell people it needs a 2-core master minimum.

**Comment by rade** [comment]
The main problem here is that it is so darn difficult to notice this is happening. In Scope, we and our users have lost many days to this :(

**Comment by bboreham** [comment]
It is raised as a Kubernetes event:

    anager: pod weave-net-4ozht_kube-system(546acee0-ee25-11e6-8965-068f417b4097) evicted successfully

The "main problem" for me is I didn't realise playing fast and loose with `requests` would make it more likely to get killed.

**Comment by rade** [comment]
The event is one of many, and gives no indication that something bad has happened.

**Comment by bboreham** [comment]
Raised in https://github.com/weaveworks/launch-generator/issues/86; this issue should be just to update the docs

**Comment by bboreham** [comment]
Closed by #2884
