### ISSUE TITLE
Segfault in fastdp.go

### ISSUE THREAD

**Issue by mikebryant** [weaveworks/weave#2824]
2/5 of the weave nodes in my cluster have started crashing.

This was on 1.9.0, upgrading to 1.9.2 hasn't helped.

We're using weave-kube, with additional options `CHECKPOINT_DISABLE`, `IPALLOC_RANGE`, and `WEAVE_PASSWORD`
We're also mounting `weavedb` as a `hostPath` instead of `emptyDir`, to provide consistency on whole-cluster reboots

```
core@kubernetes-kubernetes-az1-0-1487773414 ~ $ uname -a
Linux kubernetes-kubernetes-az1-0-1487773414 4.7.3-coreos-r2 #1 SMP Thu Feb 2 02:26:10 UTC 2017 x86_64 Intel Core Processor (Haswell) GenuineIntel GNU/Linux
```

[weave-crash-logs-1.9.2.txt](https://github.com/weaveworks/weave/files/811306/weave-crash-logs-1.9.2.txt)
[weave-crash-logs-1.9.0.txt](https://github.com/weaveworks/weave/files/811305/weave-crash-logs-1.9.0.txt)

**Comment by mikebryant** [comment]
The 1.9.2 pod, after 8 restarts it successfully started and has now been running for 2 minutes.

Possible race in the timer reset at `/go/src/github.com/weaveworks/weave/router/fastdp.go:861` - it's not being checked to see if the `fwd.heartbeatTimer` is nil. Maybe a packet came in and triggered handling before it's properly been initialised?

On line 839 there's this ```
		if fwd.heartbeatTimer != nil {
			fwd.heartbeatTimer.Reset(fwd.heartbeatInterval)
		}
```
Maybe the same logic should be applied here, and possibly other places the timer's referenced?

**Comment by brb** [comment]
Thanks for the report.

The crash happens due to resetting non-initialized `fwd.heartbeatTimer`. You experience this on 2/5 nodes due to timing. We will fix it soon.

**Comment by brb** [comment]
> The 1.9.2 pod, after 8 restarts it successfully started and has now been running for 2 minutes.

@mikebryant Could you provide logs for this case?

**Comment by mikebryant** [comment]
That run has, apparently, crashed again, and been restarted a few times since.

This is the latest run to crash:
[prev-crash.txt](https://github.com/weaveworks/weave/files/811502/prev-crash.txt)

This current run has been going on for 20 minutes:
[current.txt](https://github.com/weaveworks/weave/files/811501/current.txt)

**Comment by brb** [comment]
Thanks. Could you provide the logs from any other node (!=10.34.67.113)?

**Comment by mikebryant** [comment]
[weave-net-sn00d.txt](https://github.com/weaveworks/weave/files/811621/weave-net-sn00d.txt)
[weave-net-rqf55.txt](https://github.com/weaveworks/weave/files/811622/weave-net-rqf55.txt)
[weave-net-m653r.txt](https://github.com/weaveworks/weave/files/811623/weave-net-m653r.txt)
[weave-net-lzvp5.txt](https://github.com/weaveworks/weave/files/811624/weave-net-lzvp5.txt)

**Comment by brb** [comment]
Thanks for the logs. I see a lot of failing control plane connections (unrelated to the reported segfault). Have you tried running in the unencrypted mode, i.e. w/o setting `WEAVE_PASSWORD`?

**Comment by mikebryant** [comment]
We used to run unencrypted several weeks ago, and that was working, we didn't notice any problems

**Comment by brb** [comment]
@mikebryant We have released 1.9.3 which fixes the bug. Could you give a try?

**Comment by mikebryant** [comment]
Bah, I forgot to mention, once it was merged it into master and built in Circle, I switched to running `git-fa74d1b9bba6`, and that hasn't been crashing.
I'll upgrade to the 1.9.3 release today :)

**Comment by mikebryant** [comment]
1.9.3 release looks good, I've seen no crashes.
Thanks for the quick fix :)
