### ISSUE TITLE
Improve documentation on howto setup weave on Kubernetes

### ISSUE THREAD

**Issue by weitzj** [weaveworks/weave#2826]
I struggled a few days to get Weave attached to Kubernetes on BareMetal by following the Weave Documentation for 1.9.2 ("Integrating Kubernetes via the Addon"), and I think there are some certain points to smooth the onboarding for other users, since `kubctl apply -f https://git.io/weave-kube` might not be enough.

These are my suggestions:

#### Ensure Kubernetes loads CNI Plugins

Weave is used as a CNI plugin. Therefore, prior to `kubectl apply -f https://git.io/weave-kube` one has to ensure that the `kubelet` is running in with the additional CLI flags, so the Weave plugin is actually used by Kubernetes:

`--network-plugin=cni  --network-plugin-dir=/etc/cni/net.d`

#### Ensure the loopback CNI plugin is installed

After installing the Weave CNI plugin via `kubectl apply -f https://git.io/weave-kube` all Kubernetes Nodes will contain the Weave-Plugin in directory `/opt/cni/bin`. Since the containers launched by Kubernetes need a loopback device as well, one has to ensure that the CNI-Loopback plugin is installed as well, as mentioned in the Kubernetes documentation:

> In addition to the CNI plugin specified by the configuration file, Kubernetes requires the standard CNI lo plugin, at minimum version 0.2.0 (https://kubernetes.io/docs/admin/network-plugins/#cni)

To install the CNI-loopback plugin, go to the https://github.com/containernetworking/cni/releases and get your appropiate release, e.g. for Gnu Linux/amd64:

`curl -fsSL 'https://github.com/containernetworking/cni/releases/download/v0.4.0/cni-amd64-v0.4.0.tgz' | tar xvz -C /opt/cni/bin/`

#### Howto configure kube-proxy proxmode

You can use the default proxy mode for kube-proxy, `--proxy-mode=iptables`

#### Howto configure the Docker Daemon using Weave and Kubernetes

Since you are using Kubernetes with Weave, there is no need for Docker to wrangle with your iptables. Therefore you can launch the docker daemon with the options:

`/usr/bin/dockerd --iptables=false --ip-masq=false`

#### KubeDNS

The weave DNS is disabled. To ensure you have DNS, you have to install kube-dns **after** installing weave-net so that the `kube-dns` is reachable via weave-net.

**Comment by bboreham** [comment]
@weitzj great to hear it's working for you!  We'll take a look through the points you made and review how they can be added or made clearer in our docs.

**Comment by weitzj** [comment]
It seems like, if I add a new worker-node to an existing Kubernetes cluster, the weave-net DaemonSet will not propagate the CNI Plugin installation to the worker-node, i.e. `error updating cni config: No networks found in /etc/cni/net.d/10-weave.conf` is missing as well as `/opt/cni/bin/weave-*`

**Comment by weitzj** [comment]
Ah. Ok. It might have to with the following error:

`Failed to list *v1beta1.NetworkPolicy: Get https://172.16.0.1:443/apis/extensions....`

Since I run the Apiserver on port 6444

**Comment by bboreham** [comment]
Weave Net won't start if it cannot contact the apiserver, and if it fails that early it doesn't create the CNI config file `/etc/cni/net.d/10-weave.conf`.

The port mapping for Kubernetes services is handled by kube-proxy.

**Comment by weitzj** [comment]
Do the Kubelets of the Kubernetes worker nodes also need:

```
--network-plugin=cni
--network-plugin-dir=/etc/cni/net.d 
```
Or only the masters?

**Comment by bboreham** [comment]
Yes, all nodes need the same `--network-plugin`

The directory ought to default to `/etc/cni/net.d` but I'm not in a position to check.

**Comment by weitzj** [comment]
Thank you. I was missing the kube-proxy on the worker nodes

**Comment by deitch** [comment]
@weitzj : which log is the following line from?

```
Failed to list *v1beta1.NetworkPolicy: Get https://172.16.0.1:443/apis/extensions....
```

**Comment by RRAlex** [comment]
I would also suggest people make sure their InternalIP var are set to their private LAN ones, or at least to a non firewalled interface.
If you use the "kubernetes the hard way" guide, without a cloud integration, this might not be the case, I had to add `--node-ip` to kubelet.

One can check with:
`kubectl get nodes -o jsonpath='{ .items[*].status.addresses[?(@.type=="InternalIP")].address }'`

But from there, though `weave status {peers, connections}` seems happy, pods will not get deployed, and I'm still confused as to why.

**Comment by deitch** [comment]
I also really have been struggling. Sometimes it works great, sometimes not, and for the life of me, I cannot tell if it is kubernetes misbehaving, weave, or just how I strung the two together.

> To ensure you have DNS, you have to install kube-dns after installing weave-net so that the kube-dns is reachable via weave-net.

Really? I wonder if I have tripped on that one. How do you tell if that is an/the issue? In any case, if you start master nodes without any workers, e.g., there is nowhere for weave to install, yet dns is running. How do you handle those timing issues?

> pods will not get deployed, and I'm still confused as to why.

I actually have pods deployed, but they seem unable to reach anything or resolve anything.

> The directory ought to default to /etc/cni/net.d but I'm not in a position to check.

I am pretty sure it does, but I always do it explicitly anyways because kubernetes handles apps really well, but it itself seems exceedingly fragile.

**Comment by rambo45** [comment]
UPDATE:
Weavenet still does not install the required CNI plugins for kube-dns to start. The required plugins have been removed from https://github.com/containernetworking/cni/releases. Instead you have to download the plugins repo https://github.com/containernetworking/plugins and run the 'build.sh' script. This will build all the plugins under 'bin' folder after which you can copy all those plugins under /opt/cni/bin. kube-dns will start after this if you are stuck with it using kubeadm.

This worked for me

**Comment by johscheuer** [comment]
@rambo45 actually you can also download the prebuilt binaries: https://github.com/containernetworking/plugins/releases for the plugin

**Comment by bboreham** [comment]
Sorry this is sitting here unanswered for so long.

I'll go through the points one at a time.  I assume users have found https://www.weave.works/docs/net/latest/kubernetes/kube-addon/ which is our main documentation page for using Weave Net with Kubernetes.  We don't seek to explain everything about installing Kubernetes itself: (a) it's far too complicated and (b) we created `kubeadm` so you wouldn't have to know all that.

1. Ensure Kubernetes loads CNI Plugins

This is said three times at the top of the page.

2. Ensure the loopback CNI plugin is installed

No Kubernetes install will work without the loopback CNI plugin.  I guess we can put this in "things to watch out for" ?

3. Howto configure kube-proxy proxmode

I'm not aware of any reason why we should talk about configuring this.  Why would you want to ask for something that is the default anyway?

4. Howto configure the Docker Daemon using Weave and Kubernetes

Again, I have no basis to accept this point. We don't do this in our smoke-tests.

5. KubeDNS
We do now say "WeaveDNS is disabled when using the Kubernetes addon".  Kube-dns is an essential part of any Kubernetes install, so I don't think we need to describe that.  And "install after" in bold is simply false - Kubernetes will not start the kube-dns pods until the CNI config is found.

6. " the weave-net DaemonSet will not propagate the CNI Plugin installation to the worker-node"

The whole point of a DaemonSet is that it runs on every node.  OP had some specific config issue on one node, which led to a failure.

7. "If you use the "kubernetes the hard way" guide" ... [you have to ask for CNI]

Again, the need to configure Kubernetes to use CNI is mentioned at the top of our documentation.

8. "If you use the "kubernetes the hard way" guide" ... "the default weave cidr overlaps with the 10.32.0.0/24 service one"

Good one.  Can go in "things to watch out for".

9. Weavenet still does not install the required CNI plugins for kube-dns to start.

I think this must be the loopback again - point 2.
