### ISSUE TITLE
Zombie apocalypse with kubernetes and weave-kube

### ISSUE THREAD

**Issue by Bregor** [weaveworks/weave#2836]
Kubernetes:

    $ kubectl version --short
    Client Version: v1.5.4
    Server Version: v1.5.4

Weave:

    $ kubectl get ds -n kube-system weave-net -o jsonpath='{.spec.template.spec.containers[*].image}'
    weaveworks/weave-kube:1.9.3 weaveworks/weave-npc:1.9.3

Zombies:

    $ knife ssh "role:kubernetes_node" "sudo ps aux|grep [l]aunch.sh"|sort
    kube01 root      2230  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    kube02 root      7411  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    kube03 root      5007  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    kube04 root      6274  0.0  0.0      0     0 ?        Z    19:19   0:00 [launch.sh] <defunct>
	...

`uname -a`:

    $ knife ssh "role:kubernetes_node" "uname -a"|sort
    kube01 Linux kube01 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    kube02 Linux kube02 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    kube03 Linux kube03 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    kube04 Linux kube04 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Maybe it is connected with following issue in kubernetes: https://github.com/kubernetes/kubernetes/issues/39334
We experience this cluster-wide.

**Comment by Bregor** [comment]
I found it!

Attention to node `web05`
I downgrade weave version to one version at the time on this host.

weave-1.9.2:

    $ knife ssh "role:kubernetes_node" "sudo ps aux|grep [l]aunch.sh"|sort
    web01 root       639  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web02 root      2863  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web03 root     27055  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web05 root     17381  0.0  0.0      0     0 ?        Z    21:49   0:00 [launch.sh] <defunct>

weave-1.9.1:

    $ knife ssh "role:kubernetes_node" "sudo ps aux|grep [l]aunch.sh"|sort
    web01 root       639  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web02 root      2863  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web03 root     27055  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web05 root     22508  0.0  0.0      0     0 ?        Z    21:54   0:00 [launch.sh] <defunct>

weave-1.9.0:

    $ knife ssh "role:kubernetes_node" "sudo ps aux|grep [l]aunch.sh"|sort
    web01 root       639  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web02 root      2863  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web03 root     27055  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web05 root     26266  0.0  0.0      0     0 ?        Z    21:57   0:00 [launch.sh] <defunct>

weave-1.8.2:

    $ knife ssh "role:kubernetes_node" "sudo ps aux|grep [l]aunch.sh"|sort
    web01 root       639  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web02 root      2863  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web03 root     27055  0.0  0.0      0     0 ?        Z    Mar07   0:00 [launch.sh] <defunct>
    web05 root      4712  0.0  0.0   1524  1016 ?        Ss   22:01   0:00 /bin/sh /home/weave/launch.sh --host=10.83.8.203 --status-addr=10.83.8.203:6782

Tadaaa!
No zombies with 1.8.2.

**Comment by marccarre** [comment]
Many thanks for reporting this @Bregor!
I confirm: 

1. I can systematically see `defunct` processes for `launch.sh`;
2. this behaviour seems to have been introduced by [this](https://github.com/weaveworks/weave/commit/bf59a003bbee14438e43163fafb3745b55f1e2cf) change;
3. that although not a proper fix, applying a patch removing `exec` to the `1.9.3` branch removes the symptoms;
4. [we're internally discussing](https://weaveworks.slack.com/archives/net/p1489401047279615) a proper fix/refactoring to resolve this issue.
