### ISSUE TITLE
CNI ADD: weave bridge and the first connected container get the same IP addr

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2839]
When doing CNI ADD, we allocate and assign an IP addr not only to a container, but also to the weave bridge, if it does not have any IP addr (https://github.com/weaveworks/weave/blob/1.9/plugin/net/cni.go#L77).

A function which calls IPAM allocate might not use ContainerID from `args` passed to the function (https://github.com/weaveworks/weave/blob/1.9/plugin/net/cni.go#L51), and instead it will use the one from `CNI_CONTAINERID` env var which contains the container id.

As a result, we will end up calling IPAM allocate with the same container id twice (instead of the container id and `weave:expose`),  which will allocate the same IP addr to the weave bridge.

This might explain the weave-kube bug reports from the past, where the weave bridge and some container ended up having the same IP addr. However, to make this happen, the first CNI allocation should have happened before executing https://github.com/weaveworks/weave/blob/1.9/prog/weave-kube/launch.sh#L115 .

**Comment by bboreham** [comment]
Note this does not happen if you use the default CNI config generated by the `weave` script; only if you edit it to name an IPAM provider.  So I do not think it is responsible for many bug reports.

**Comment by bboreham** [comment]
Trying to fix this I ran across another bug: https://github.com/containernetworking/cni/issues/410

**Comment by marccarre** [comment]
Fixed by #2856.
