### ISSUE TITLE
PKI instead of passwords for encrypted connections

### ISSUE THREAD

**Issue by andrew-t-l** [weaveworks/weave#2849]
I love that fastdp connections are now wrapped in IPsec. However I'd love even more to not use a password. I already pretty extensively deploy host certificates and rotate them every 30 days for IPsec connections between hosts. I'd prefer to extend this to weave as well.

**Comment by brb** [comment]
Unfortunately, the current crypto implementation does not support certificate based authentication, and thus additional works is required. https://www.weave.works/docs/net/latest/how-it-works/encryption-implementation/ provides some details of Weave Net encryption implementation.

I'm closing the issue, as it duplicates #206. Could you list your requirements in #206? Thanks.
