### ISSUE TITLE
How many ports are weavev daemon used for communication and DNS search?

### ISSUE THREAD

**Issue by ghostplant** [weaveworks/weave#2869]
I need to control the firewall and open some ports that `weave launch` will use. Which ports (tcp/udp/..) are needed to be opened?

**Comment by brb** [comment]
**_Q: Which ports does Weave Net use (e.g. if I am configuring a firewall) ?_**

_You must permit traffic to flow through TCP 6783 and UDP 6783/6784, which are Weave’s control and data ports._

_The daemon also uses TCP port 6782 for metrics, but you would only need to open up this port if you wish to collect metrics from another host._

_The Weave Net daemon listens on localhost (127.0.0.1) TCP port 6784 for commands from other Weave Net components. This port should not be opened to other hosts._

_When using encrypted fast datapath, make sure that underlying network does not block ESP traffic (IP protocol 50). For instance on Google Cloud Platform a firewall rule for allowing ESP traffic has to be installed._

https://www.weave.works/docs/net/latest/faq/
