### ISSUE TITLE
Service resolution between clusters

### ISSUE THREAD

**Issue by chrislovecnm** [weaveworks/weave#2875]
I am following https://github.com/weaveworks-experiments/demo-weave-kube-hybrid to span a k8s cluster between regions.  

Cluster Alpha has dns on 10.32.0.20
Cluster Beta has dns on 10.32.0.40

Should a pod in cluster Alpla be able to reach the service ip 10.32.0.40 in Beta.

Cluster A is setup with:

nonMasqueradeCIDR: 10.32.0.0/12
serviceClusterIPRange: 10.32.0.0/14
clusterCIDR: 10.32.0.0/12
serverIP: 10.32.0.20
clusterDNS: 10.32.0.20

Cluster B is setup with:

nonMasqueradeCIDR: 10.32.0.0/12
serviceClusterIPRange: 10.32.0.0/14
clusterCIDR: 10.32.0.0/12
serverIP: 10.32.0.40
clusterDNS: 10.32.0.40

Currently, I am even having problems within the same cluster.

**Comment by bboreham** [comment]
`serviceClusterIPRange` must not overlap with the pod IP range.  The demo files only specify this in one file - `config/deployments/federation-apiserver.yaml`

By extension the `serverIP` and `clusterDNS` want to be outside of the pod IP range too.

`clusterCIDR` is used by Kubernetes cloudproviders but would not be used in a Weave Net context.

**Comment by chrislovecnm** [comment]
when you are referring to pod IP range, are you referring to the range that weave uses?   Is this a weave thing or a CNI thing?

**Comment by bboreham** [comment]
Kubernetes [requires](https://kubernetes.io/docs/concepts/cluster-administration/networking/) that all pods can talk to each other without going through NAT.  One way to achieve this is to put all pods on the same IP subnet, e.g. by default Weave Net puts them all on 10.32.0.0/12.  So this is "the pod IP range" I was referring to.  It could be a set of ranges, for some other pod network implementation.

Bottom line: packets addressed to a Kubernetes service need to follow a different route than packets to a pod, so the CIDR which defines the set of pod addresses and the CIDR which defines the set of service addresses need to be non-overlapping.

CNI does not define any standardised way for callers to request a particular subnet or range of addresses.

When using Weave Net installed via `weave-kube` the pod address range can be specified by setting the environment variable `IPALLOC_RANGE` at launch time.

**Comment by chrislovecnm** [comment]
I got this working ;) Wahoo.  It did not like me installing weave twice.  Once with weave in standalone mode and once with --ipalloc-init=observer
