### ISSUE TITLE
Docker plugin-v2 can be started before /var/run/docker.sock is ready

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#2906]
If `/var/run/docker.sock` is not ready, plugin-v2 will fail silently to start:

```
16:07:48+01:00" level=info msg="Starting launch.sh" plugin=d4429df88c47efe094b7dd3c471aa7f4f61612e378814ad706c7b7d0
...
16:08:26.948417772+01:00" level=info msg="API listen on /var/run/docker.sock"
```

Worse than this is Docker reporting that the plugin is enabled:

```
$ docker plugin ls
ID                  NAME                           DESCRIPTION                   ENABLED
d4429df88c47        weaveworks/net-plugin:latest   Weave Net plugin for Docker   true
```

Reproduced with Docker 17.04.0-ce after restarting `docker.service`.

**Comment by brb** [comment]
The first problem is that after restarting the Docker engine, `docker.sock` becomes ready only after Docker tries to launch the enabled plugin.

This could be easily fixable by adding a `wait_for_docker_sock` statement to launch.sh of plugin-v2. However, I just discovered another problem (and filled https://github.com/moby/moby/issues/32789) which is that Docker kills a plugin if its initialization takes too long (= the plugin socket becomes ready to serve).

Also, I am not sure (need to investigate) whether listening on `docker.sock` happens after Docker tried to re-launch all enabled plugins. If it is so, then we will need to make the plugin socket ready before using Docker API.

**Comment by brb** [comment]
I could not reproduce the problem (the plugin does not start after Docker Engine restarts) with Docker 1.13.1, while it is reproducible with Docker 17.04.0-ce.

**Comment by brb** [comment]
https://github.com/moby/moby/issues/32815

**Comment by bboreham** [comment]
We were relying on the Docker socket for two things:
1. to find the options set on the network, which we use to avoid #1960
2. to know when the interface exists in the container's namespace, so we can set arp options on it - see #2374 

We can have a working plugin that does neither of these things; it's just a bit suboptimal for some users.

**Comment by justincormack** [comment]
If you share `/var/run:/var/run` rather than the socket, you should at least see the new inode when it comes back up. If you can wait if it is not available and retry it should be workable (until we get a better fix)

**Comment by bboreham** [comment]
We have rather an aversion to that - see #1455

**Comment by justincormack** [comment]
ah, ugh. We should really have the socket it in its own directory...

**Comment by bboreham** [comment]
More discussion at https://github.com/moby/moby/issues/21109
