### ISSUE TITLE
exploring work-arounds to persistent dns issues in docker cluster, using weave

### ISSUE THREAD

**Issue by hesco** [weaveworks/weave#2908]
I'm sure this is all looking pretty silly about now.  
Seemed to work the first couple of times I tried it.  
Every time one of my builds would fail due to a name resolution issue, 
I would harvest the results of `host -t ns cannot.find.this.domain`
and add it to my `docker run` invocation with `--dns=x.x.x.x`
but I seem to have overwhelmed the resolvers inclination to care.  

Still having fits with dns inside my docker cluster, using weave.  

partial output of docker inspect container_id:

            "Dns": [
                "68.64.241.98",
                "68.64.241.102",
                "8.8.8.8",
                "8.8.4.4",
                "64.90.62.230",
                "208.97.182.10",
                "216.92.61.171",
                "66.39.65.254",
                "205.251.197.3",
                "64.90.62.230",
                "208.97.182.10",
                "216.92.61.171",
                "66.39.65.254",
                "205.251.197.3",
                "205.251.193.165",
                "205.251.197.3",
                "205.251.194.8",
                "205.251.198.171",
                "172.17.0.1"
            ],
            "DnsOptions": [],
            "DnsSearch": [
                "yourmessagedelivered.com",
                "zone1.weave.local"
            ],

My next work-around is to refactor my kludge as a new function in my stdlib.sh script of functions to support a new parameter so I can set these additional name servers on a container by container basis.  

The one after that would be to install and configure a BIND9 server and see if I can get this behind me.  

Would certainly appreciate any guidance from folks on this.  Seems absurd to me.

**Comment by brb** [comment]
Thanks opening the issue.

I don't have enough context about your build setup, but maybe it'd make more sense to retry a build step if it fails due to name resolution issues?

Adding many entries to `/etc/resolv.conf` might slow down the name resolution for any domain name. Same applies if you pass a long list of upstream DNS servers to Weave DNS.

**Comment by bboreham** [comment]
I also get occasional issues from DNS resolution failures on my development machine at home - I'm using VirtualBox and it sets up some local DNS resolver that seems to fail.  If I overwrite `/etc/resolv.conf` with 8.8.8.8 it never fails.

Just my 2 cents ^^
