### ISSUE TITLE
Can't restart weave-npc because of ipset error "Set cannot be destroyed"

### ISSUE THREAD

**Issue by yannrouillard** [weaveworks/weave#2915]
Hi,

We currently encountered an issue on our Kubernetes cluster v1.4 where we weren't able to restart the weave-net pod because the weave-npc container were always failing with the following error message:
```
ipset [destroy weave-ct?g{Ln1Djp[:;d;4OhuoU$cJ] failed: ipset v6.29: Set cannot be destroyed: it is in use by a kernel component
```

Complete logs are:
```
INFO: 2017/04/27 03:53:22.845217 Starting Weaveworks NPC 1.9.4
INFO: 2017/04/27 03:53:22.846795 Serving /metrics on :6781
Thu Apr 27 03:53:22 2017 <5> ulogd.c:843 building new pluginstance stack: 'log1:NFLOG,base1:BASE,pcap1:PCAP'
DEBU: 2017/04/27 03:53:22.892522 Got list of ipsets: [weave-ct?g{Ln1Djp[:;d;4OhuoU$cJ weave-viMd_3{ytI{fsqkGEq>hQZj0E weave-uryNoZWn|qTJOXF5L7Rq1:CqC weave-Lb5cDl39gCzYJ4CZ9N;UFY[/o weave-]j}tH1hV{.pj>EQSy7|]of9uH weave-E0_C&$DB[j.JV_Y[u[S2(Elug weave-k?Z;25^M}|1s7P3|H9i;*;MhG weave-k^ECI/NRo6zq5ZWEdpMk?{lDi weave-XwzO78vI{0XK#vHrdH;M*@%M_ weave-fk/~8ml5jU/KNi7yrO<ux9Jys weave-}VOW.2vMv;dOx<11<i*8Z$9yi weave-hVDldOfE<%;@Y&^7d52k1Px|K weave-ep3/r<H%.JRG<#/a)kg66<3qf weave-]2^zFy(_q?M2Q}vavlH0ij{|6 weave-~8f>?yo$hQ^}|veb/Jy;9|Lt) weave-JJai@G2zdWbZjQO(uvd]qtI7v weave-nn;DA}.Sqh*tCD6yB*P97u#TY weave-OXze2|dZ.m@4lTf8p>#&1/kc<]
DEBU: 2017/04/27 03:53:22.892550 Destroying ipsets 'weave-ct?g{Ln1Djp[:;d;4OhuoU$cJ'
ERRO: 2017/04/27 03:53:22.893761 Failed to destroy ipset 'weave-ct?g{Ln1Djp[:;d;4OhuoU$cJ'
FATA: 2017/04/27 03:53:22.893793 ipset [destroy weave-ct?g{Ln1Djp[:;d;4OhuoU$cJ] failed: ipset v6.29: Set cannot be destroyed: it is in use by a kernel component
: exit status 1
```

The listed ipset were not used at all in all iptables tables (default, filter, mangle, nat, raw, security)

After some investigation, it appears that weave was not able to destroy the ipset because the first ipset that weave tried to destroy was referenced in another weave ipset:
```
Name: weave-ct?g{Ln1Djp[:;d;4OhuoU$cJ
Type: hash:ip
Revision: 1
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 17632
References: 1
Members:
172.100.96.12
[...]

Name: weave-nn;DA}.Sqh*tCD6yB*P97u#TY
Type: list:set
Revision: 1
Header: size 8
Size in memory: 128
References: 0
Members:
weave-ct?g{Ln1Djp[:;d;4OhuoU$cJ
```

Looking at that issue it seems weave resetIPSets function should be updated to destroy ipsets by taking into account references.

I can propose a patch for that but I would like to know if the situation we encountered is not caused by some other things as I am surprised no one else had the issue.

**Comment by yannrouillard** [comment]
In case someone needs a quick around, here is a one-line shell to delete weave ipset contains other weave ipsets:
```
sudo ipset list -o save | egrep “^add weave-.* weave-.*” | while read _ IPSET _; do sudo ipset destroy “$IPSET”; done
```

After a successful run, you can relaunch weave and it will successfully destroy the remaining ipsets and start properly.

Note: the one-line works if there is only level of membership.

**Comment by brb** [comment]
@yannrouillard Thanks for the report.

> I can propose a patch for that but I would like to know if the situation we encountered is not caused by some other things as I am surprised no one else had the issue.

Patches are more than welcome!

I doubt that you are missing something. I think it is save to remove ipsets of the `hash:ip` type first, and afterwards those of the `list:set` type.

**Comment by yannrouillard** [comment]
Ok will work on a patch. You are right for the hash:ip/list:set thing, didn't notice two different types were used in ipset.

Questions: do you only have integration tests ? I didn't find unit tests after a quick look.

**Comment by bboreham** [comment]
@yannrouillard some modules have unit tests, e.g. https://github.com/weaveworks/weave/blob/master/net/address/address_test.go, but nothing under npc.  And we don't have an automated test for that either - that's open as #2620 😞

**Comment by bboreham** [comment]
@yannrouillard did you get anywhere with this?

**Comment by mikebryant** [comment]
Sorry if @yannrouillard wanted to work on this, we lost all of our npcs on a whole cluster because of this, so we needed to fix it.

**Comment by Iakim** [comment]
I found my fix, restart your node problem. Only this...
