### ISSUE TITLE
k8s 1.6.2 delete service error 

### ISSUE THREAD

**Issue by insoz** [weaveworks/weave#2921]
k8s:1.6.2
weave: 1.9.4

```bash
root@kb-node1:~# lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
root@kb-node1:~# uname -a
Linux kb-node1 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Created it by `kubectl apply -f https://git.io/weave-kube-1.6`

When i delete a service with `kubectl delete -f abc.yaml`,  the pod status become `Terminating`, and the master docker container was Exited, but the minon docker container is still UP, look like it is hold by something

The weave container log on minon:
```bash
network: error removing interface "eth0": nsenter: cannot open /proc/14582/ns/net: No such file or directory
```

**Comment by bboreham** [comment]
I'm not sure I understand your terminology.  What is "the master docker container" and "the minon docker container"?  "Master" usually refers to the node that is running Kubernetes api-server.

I presume `abc.yaml` is some service you are trying to run under Kubernetes, like a web service?

> The weave container log on minon:
>     `network: error removing interface "eth0": nsenter: cannot open /proc/14582/ns/net: No such file or directory`

This is very strange.  I could imagine seeing that message in `kubelet`'s log, but no idea why it would appear in a weave container log.  Is that what you meant - the container that runs the Weave Net router daemon?

**Comment by bboreham** [comment]
I put this back to a bug because the CNI spec says "Plugins should generally complete a DEL action without error even if some resources are missing.", and that error would be the Weave Net CNI plugin complaining there is no `eth0`

**Comment by insoz** [comment]
1. "the k8s master docker container" and "the k8s minon docker container"
2. Is that what you meant - the container that runs the Weave Net router daemon?   Yes

**Comment by bboreham** [comment]
Ok, and can you give a hint what the service you deleted was?

Can you supply the whole log that contained the error message you quoted, please?

**Comment by insoz** [comment]
Just a mysql service 
```bash
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - resources:
        limits :
          cpu: 0.5
      image: mysql
      name: mysql
      args:
        - "--ignore-db-dir"
        - "lost+found"
      env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value:
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
          # name must match the volume name below
        - name: mysql-persistent-storage
          # mount path within the container
          mountPath: /var/lib/mysql
      volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: ceph-claim
  volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
```


Sorry, I cant repetition that . I didn't save the whole log.

**Comment by bboreham** [comment]
OK, still a bit confused because MySQL isn't something you would run more than one of, so I don't get why you had two containers, which you called master and minion.

Is the issue repeatable?

**Comment by insoz** [comment]
```bash
root@kb-node1:~# kubectl get nodes
NAME       STATUS    AGE       VERSION
kb-node1   Ready     2h        v1.6.2
kb-node2   Ready     2h        v1.6.2
```
I was test the pv, and run `kubectl create/delete -f mysql.yaml` three times maybe, and  the pod on kb-node1 can delete , on kb-node2 can't

**Comment by bboreham** [comment]
Closed because `network: error removing interface "eth0":` will no longer be returned to kubelet, hence cannot kubelet to stall.

(this change is not yet in a released version, but the issue gets closed when the code is merged to master)
