### ISSUE TITLE
Remove docker binary from weaveexec container

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#2957]
I looked at what it would take to do this.  The benefits would be:
 - avoid triggering virus scans (the docker binary includes some vulnerable code, although we don't execute that code)
 - smaller weaveexec image
 - avoid unnecessary version coupling caused by bundling docker 1.10.3
 - avoid icky feeling from downloading a tarfile and extracting a binary in the Makefile
 - weave net would be available on arm64 (where we cannot find a usable docker binary)

The subcommands used now are kill, stop, inspect, run, rm, exec, create, pull, ps.
I give arguments below why exec and pull would not be needed; the rest could be re-implemented in weaveutil.

Only a subset of `docker run` arguments are needed: `-d`, `-v`, `-e`, `--name`, `--privileged`, `--net=host`, `--pid=host`, `--volumes-from`; although we have suggested that users set `WEAVE_DOCKER_ARGS` to add arbitrary more.

Things that would need converting:
- kill_container, called from wait_for_status (stop a restarting weave) - docker kill
- stop, called from weave stop - docker stop
- ask_version - printing the version of the weave container - inspect and run
- is_plugin_v1_enabled - inspect, looking for --plugin; this is bugged anyway
- check_running - inspect
- check_not_running - inspect and rm
- container_id - inspect
- http_call_unix - exec - could move this feature to TCP socket on 6784
- rewrite_etc_hosts - can move the docker inspect to weaveutil rewrite-etc
- with_container_fqdn - inspect
- launch - creating weavedb and weavewait containers - inspect, create
- weave reset - docker stop, rm, ps
- setup - docker pull - this could move to the non-remoted part of the script

Things that don't need converting:
- try_create_bridge - inspect - this is pointless because `/` isn't mounted
- util_op - this code only used when not running inside weaveexec

**Comment by vCloudernBeer** [comment]
Is this still something that needs to be fix/changed?  I see WIP.  thanks for the information.

**Comment by bboreham** [comment]
Yes, it's still open. I think by "WIP" you are referring to a linked issue which would not be required if this were done. 

Some of the itemised points are out of date.

**Comment by bboreham** [comment]
Updated list of things that would need converting, in the `weave` script:
- kill_container, called from wait_for_status (stop a restarting weave) - docker kill
- stop, called from weave stop - docker stop
- ask_version - printing the version of the weave container - inspect and run
- check_running - inspect
- check_not_running - inspect and rm
- container_id - inspect
- rewrite_etc_hosts - can move the docker inspect to weaveutil rewrite-etc
- with_container_fqdn - inspect
- launch - creating weavedb and weavewait containers - inspect, create, run
- stop - docker stop
- weave reset - docker stop, rm, ps
- weave setup - docker pull - this could move to the non-remoted part of the script

Things that don't need converting:
- check_docker_version - only called outside of the container
- try_create_bridge - inspect - this is pointless because `/` isn't mounted when this code is run
- util_op - this code only used when not running inside weaveexec

**Comment by vCloudernBeer** [comment]
I am new to Weave and would like to get my feet wet.  I would like to work on this but will need some pointer to get start.  I believe the "script" that needs to be worked on/convert is this https://github.com/weaveworks/weave/blob/master/weave

**Comment by bboreham** [comment]
Hi, that's great!  Please ask as many questions as you need.  We also have a [community Slack](https://weaveworks.github.io/community-slack/)

The proposal here is to write mini-replacements for the required `docker` commands inside [weaveutil](https://github.com/weaveworks/weave/blob/master/prog/weaveutil/main.go), which is a Go program we use for various other uses.  Then that program can be called by the `weave` script and we can stop bundling the `docker` binary.

So there would be `weaveutil stop`, `weaveutil kill`, etc., and each of them would call the Docker API.

**Comment by vCloudernBeer** [comment]
Thanks for the pointers. Let me look into this and get started.

**Comment by vCloudernBeer** [comment]
Thanks for the pointers. Let me look into this and get started.

**Comment by vCloudernBeer** [comment]
So take container_id as an example.  In the weave script there is a function container_id() which is doing docker inspect --format='{{.Id}}' $1 The idea is to create a function in weaveutil (a golang program) to perform the same. 

In some case the function in weaveutil can use Docker API instead of executing a Docker CLI command.

**Comment by bboreham** [comment]
Yep, I think you've got a handle on it

**Comment by rade** [comment]
In some cases we should create higher-level operations in `weaveutil` rather than just straight replacements of `docker` commands. For example, we have
```
    ps)
        [ $# -eq 0 ] && CONTAINERS="weave:expose $(docker ps -q)" || CONTAINERS="$@"
        with_container_addresses echo_addresses $CONTAINERS
```
which ideally should be implemented via a single `weaveutil` command (`with_container_addresses` already calls `weaveutil container-addrs`).

Also, all of `populate_router`, which calls `docker ps`, should just live inside the router.


I suppose we could do straight docker command replacements first and then tackle above in a second pass.

**Comment by vCloudernBeer** [comment]
Got it.

**Comment by vCloudernBeer** [comment]
In the weave script there is util_op(). If command is in **weaveutil** execute, else start a container with entry  point **/usr/bin/weaveuti**l.  Why do we need to specify the entry point when we know weaveutil does not have this command? . 

I thought the idea is when not in weaveutil then start a container to execute the command via Docker CLI.

 Thanks for the information

**Comment by rade** [comment]
That conditional checks whether `weaveutil` *itself* exists, and if so executes it directly, otherwise launching a container to execute it. The latter happens when the weave script is executing outside the weaveexec container.

**Comment by vCloudernBeer** [comment]
Got it.  Thanks.

**Comment by vCloudernBeer** [comment]
Not getting too far on this one.  Still want to get this going.

**Comment by dtshepherd** [comment]
I stumbled across this when trying to improve the `weave` script for net-plugin v2 status.

I initially made changes to the script to use direct docker commands, then realized a really old version of docker lives inside the `weaveexec` container.  I started searching around open issues and found that I was on the wrong path (need less `docker ...` commands, not more :-)

After I finish tackling the plugin support methods (if the weaveworks guys think thats a worth while effort), I may be able to help port some of these other methods over.

**Comment by bboreham** [comment]
@dtshepherd it would be great if you could contribute here!  Maybe if you did just one of the `docker` command replacements it would help @vCloudernBeer see the pattern and you could collaborate on doing more?

> After I finish tackling the plugin support methods (if the weaveworks guys think thats a worth while effort)

Is there an issue or PR specifically for that?

Generally when you have a problem, any troubleshooting tools are helpful.  We don't want to _require_ the `weave` script for plugin-v2 users, but as an optional extra it seems like a fine idea.

**Comment by bboreham** [comment]
BTW the `docker` binary is old because a new docker will refuse to talk to an older daemon, and we want Weave Net to work on as wide a range of targets as possible.  See also #2545 which was an attempt at solving this a different way.

**Comment by dtshepherd** [comment]
Completely agree the `weave` script shouldn't be required for plugin-v2. It would just be helpful for status and cleanup.

There isn't a PR yet, but the effort is related to #3102 and #3103. I actually codes up changes to the script and then realized the docker client in `weaveexec` was really old (no plugin support).

I figured I could implement some plugin commands in `weaveutil` so I could submit a PR for those two issues. 

What do you think? We can talk more on Slack if you want.

**Comment by vCloudernBeer** [comment]
Yes, this will help me a lot and get me going. Thanks so much.

**Comment by dtshepherd** [comment]
@bboreham I started down the path of implementing some of the docker commands in `weaveutil` tonight, but it seems to be just duplicating `docker/cli/command` functions (with way less features).  `weaveutil` commands should be used for higher level functionality (like a docker command sequences).

I really like the idea of just using the latest docker client (17.06.1-ce) and specifying DOCKER_API_VERSION environment variable (as noted in #2545).  It looks like your blocker (moby/moby#29040) was fixed in 17.03.  I tested docker-engine 1.11.2 with docker client 17.06.1-ce and it seems to work (see below).  We could dynamically set the DOCKER_API_VERSION based on the server API version.  Querying the server using the older 1.22 API version (docker 1.10.3) to determine the max supported API version.

If you don't want to download the docker tarfile, we could just use the `github.com/docker/docker/cli/command` functions directly and just create a helper wrapper in `weaveutil`.  We're already importing that vendor package for the `network_plugin.go` commands.

The code changes to get this working are straight forward, but I don't think I can take on the testing across all versions of docker.  Do you guys have a test harness to run against all versions?

Thoughts on implementing it this way?

```
$ docker-17.06 version
Client:
 Version:      17.06.1-ce
 API version:  1.24 (downgraded from 1.30)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)

$ DOCKER_API_VERSION=1.22 docker-17.06 version
Client:
 Version:      17.06.1-ce
 API version:  1.22
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23 (minimum version )
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
 Experimental: false

$ DOCKER_API_VERSION=1.23 docker-17.06 version
Client:
 Version:      17.06.1-ce
 API version:  1.23
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:51:12 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23 (minimum version )
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
 Experimental: false
dtshepherd@NUC:~/git/weave$ 
```

**Comment by bboreham** [comment]
> It looks like your blocker (moby/moby#29040) was fixed in 17.03.

It's always questionable whether to exclude a Docker version, but our stats say usage 1.13 with Weave Net has dwindled to about 0.5%, so maybe that would be ok.

I do think it would be plausible to re-use the Docker CLI implementations of `kill`, `stop`, etc.  

That might involve converting `weaveutil` to use the Cobra CLI library, which is already proposed in #2490.  And `docker/docker/cli/command/cli.go` may have some behaviour we don't want.

Not sure if I would want a pass-through implementation of `docker inspect` since we only use it in very specific scenarios and in places (e.g. `check_running`, `check_not_running`) the `weave` script code gets a bit twisted to work round its limitations.

> Do you guys have a test harness to run against all versions?

Our [test infrastructure](https://github.com/weaveworks/build-tools/tree/master/provisioning) in theory allows us to pick a Docker version; we don't have any automation to try a series of versions.  And I'm not sure how well the older installs work right now - Docker made changes a few months back which forced us to upgrade to 17.x.

**Comment by dtshepherd** [comment]
@vCloudernBeer I started work in PR #3110, I only implemented the simple command so far...

**Comment by bboreham** [comment]
Bit more detail on why re-implementing the `docker inspect` in `try_create_bridge` is pointless:

`try_create_bridge` is called from `create_bridge` which is called from `weave attach`, `weave expose` and `weave hide`.
elsewhere there is a routine `exec_options()` which mounts `/etc` and `/var/lib/dbus` for those commands.
The `docker inspect` in `try_create_bridge` will come up with a path like `/var/lib/docker/volumes/1337b0ba0598533f797546d70d489e10770bf85392a6fd2d6f0df6aef2f0125b/_data`, which it will try to access under `/host`, and it isn't there because it wasn't mounted.

**Comment by vCloudernBeer** [comment]
My understand of this issue from a very high level is to migrate to using go function as a Docker Client and to issue API calls to the Docker Engine to perform the above listed actions instead of spinning up a container and pass in the Docker CLI command.

**Comment by vCloudernBeer** [comment]
One example of using Docker client API can be found in  .../weave/prog/weaveutil/addr.go where it import in "github.com/fsouze/go-dockerclient"? Sorry I am still a bit slow but I am determine to get myself started.

**Comment by dtshepherd** [comment]
@vCloudernBeer Check out PR #3110.  I've ported a large portion of the `docker ...` dependencies to `weaveutil`.  I'm still working on the `docker create` replacement for the `weavevolumes`, generalization/reusable code for `docker run`, `docker ps`, and `docker pull`.  Some of those should be direct ports (e.g. `docker pull`), but others should be implemented as higher level functionality (see https://github.com/dtshepherd/weave/blob/6bb8afd46001f2704a874e1aae7059c92c97187b/prog/weaveutil/version.go#L10).

Maybe you can try to implement something simple like the `docker pull` command.  It probably belongs in a new file `image.go`.  Feel free to start from my current branch (https://github.com/dtshepherd/weave/tree/issues/2957-rm-docker-binary-from-weaveexec).   @bboreham is also pushing that into https://github.com/weaveworks/weave/tree/issues/2957-rm-docker-binary-from-weaveexec on occasion.

**Comment by vCloudernBeer** [comment]
Cool.  thanks.

**Comment by dtshepherd** [comment]
> instead of spinning up a container and pass in the Docker CLI command.
@vCloudernBeer It's worth mentioning that the `weaveexec` container will still be spun up to run the `weaveutil` CLI commands.  This issue is trying to eliminate the use of `docker ...` CLI commands in the `weaveexec` container.

**Comment by vCloudernBeer** [comment]
I found one reference of "docker pull ..." in the weave script. So the idea is to change from 

**docker pull $img** to **util_op docker-pull $img** where docker-pull is a new function in weaveutil?

**Comment by bboreham** [comment]
@vCloudernBeer yes, that's one way to do it.

I did note a different idea for `docker pull`, since it is only used in `weave setup`: it could move to the non-containerised part of the script.

Each time you execute the `weave` script, it does some initial stuff then calls `docker run` on the same script inside the `weaveexec` image.  This way we know we have certain tools available - `ip`, `curl`, `weaveutil`, etc.  But some commands like `weave help` are executed without doing a `docker run`.

So, my idea was that the `docker pull` part of `weave setup` could move to roughly where `weave help` is done.  It's just an idea.

**Comment by dtshepherd** [comment]
Not a bad idea, I thought about that and it probably a cleaner solution.  I ended up implementing it inside `weaveutil` in PR #3110 (https://github.com/weaveworks/weave/commit/01949309e9140b9063ee00ad77e8c5692df56ecd).  It's a decent amount of code to trigger a `docker pull` through the API.

**Comment by vCloudernBeer** [comment]
So this is already done.  Seems like I should work on another issue.
