### ISSUE TITLE
npc: shortName() includes chars that are invalid in xml

### ISSUE THREAD

**Issue by stuart-warren** [weaveworks/weave#2958]
As part of #2939 I was trying to parse the `ipset list` output to find references from one set to another and unlink them before destroying. I thought that parsing the raw stdout was likely a bit unmaintainable but there is an xml output option. Unfortunately the output is not valid xml due to the occasional bad char in the fields.

The ShortNameSymbols in `npc/shortname.go` include chars that are invalid in xml [<>&].

Can we replace them with other chars? Maybe  [¬`+]

**Comment by bboreham** [comment]
Good spot!  I guess it would be reasonable to change those chars; since we flush all ipsets on restart there should be no problem with backwards-compatibility.

**Comment by bboreham** [comment]
I would prefer to avoid backquote too, but haven't researched how many characters are available.
