### ISSUE TITLE
Weave not auto add the container dns entry

### ISSUE THREAD

**Issue by richardweib** [weaveworks/weave#2961]
When use add container to weave first time,the container hostname will add to dns entry auto,like use this command:

```
docker run --net weave image:tag
```

but docker can't add container to two bridge at the same time,like this command:

```
docker run --net weave --net isolated image:tag

docker network connect weave container_id
```

this container host name will not add the dns auto

**Comment by bboreham** [comment]
Welcome, @richardweib.

Could you describe your situation a bit more - what versions of Weave Net and Docker you are using; which commands you ran to lead up to the symptom you experienced.

**Comment by richardweib** [comment]
### weave version is:

```
$ weave version
weave script 1.9.4
weave router 1.9.4
weave proxy  1.9.4
weave plugin 1.9.4
```

### docker version is:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### STEPS TO REPRODUCE

1.run a container

```
docker run --net isolated -h test.weave.local image:tag
```

2.add to weave network:

```
docker network connect weave container_id
```

### EXPECTED RESULTS

I hope use `docker logs weave` and `weave status dns` can find the `test.weave.local` record,and others containers can know this dns record.but there is not.

### SUMMARY

when I run `docker run --name test --net weave --host test.weave.local image:tag`,I can find the dns record,but I run `docker run --name test --net isolated --host test.weave.local image:tag` and `docker network connect weave container_id`,the dns not entry this record.

**Comment by marccarre** [comment]
@richardweib, you may want to try: `weave attach container_id` to attach it to Weave Net's network.
See also: https://www.weave.works/docs/net/latest/using-weave/dynamically-attach-containers/

Full example:
```
$ weave launch

$ docker network create isolated
29c7d3184a1d

$ docker run -d --net isolated -h test.weave.local alpine top
91cf291ab88a
### Note that this container is currently not in Weave Net's network, which is why it does not appear in Weave DNS.

$ weave status dns
### No results, as expected.

$ weave attach 91cf291ab88a
10.32.0.1
### Container should now be in both networks, and indeed, it now appears in Weave Net:

$ weave status dns
test         10.32.0.1       91cf291ab88a 3a:69:c9:53:af:9e

$ eval "$(weave env)"
### Activate Weave's Docker proxy, the below container will therefore be automatically attached to Weave Net's network, and we therefore should be able to ping the above "test" container using its name.

$ docker run -ti alpine /bin/sh
/ # ping test
PING test (10.32.0.1): 56 data bytes
64 bytes from 10.32.0.1: seq=0 ttl=64 time=0.327 ms
64 bytes from 10.32.0.1: seq=1 ttl=64 time=0.221 ms
64 bytes from 10.32.0.1: seq=2 ttl=64 time=0.212 ms
^C
--- test ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.212/0.253/0.327 ms
```

Also, it may be more convenient for you to ask this kind of questions on our Slack channel: http://weave-community.slack.com/

**Comment by richardweib** [comment]
if I want to get this dns,I also can use `weave dns-add container_id`,but I want get this dns when I connect to weave,beacuse weave doesn't have api.

so when I use api to creat a container and start it,then connect to weave,I can't get this dns,and I also get add dns by python,so I hope get the dns when I connect to weave

**Comment by richardweib** [comment]
@marccarre

**Comment by marccarre** [comment]
@richardweib, 
1. Did you try `weave attach container_id` as suggested in my previous message?
  Notice it is not the same as `weave dns-add container_id` which you mentioned:
    - `dns-add` does NOT connect the container to Weave Net's network, it is only useful if your container is already connected; 
    - `attach` connects it AND adds a DNS entry for it, which is what you need in the scenario you gave earlier.
2. if `weave attach` did not work for you, could you please provide an example reproducing your latest issue?
3. regarding the API, you could definitely script this up. Why do  you mention Python? Are you starting containers using [`docker-py`](https://github.com/docker/docker-py)? If so, would something like the below work for you?
```
from subprocess import Popen, PIPE
from shlex import split

def run(command):
    process = Popen(split(command), stdout=PIPE, stderr=PIPE)
    process.wait()
    stdout, stderr = process.communicate()
    return process.returncode, stdout.decode(), stderr.decode()

status, stdout, stderr = run('weave attach %s' % container_id)
```

**Comment by richardweib** [comment]
thx for your patience，the thrid point is what I want to do,I use docker-py to operate docker container,I think about  container attach to weave when it is used docker network connect weave.I know what a stupid question right now

**Comment by marccarre** [comment]
@richardweib, no problem at all! I'm happy the above helped 👍
