### ISSUE TITLE
Is it safe to use IP 172.17.0.1 as a resolver?

### ISSUE THREAD

**Issue by olegabr** [weaveworks/weave#2983]
I' m using weave with nginx/openresty/lua. In order to make lua code connect to the database from another container, I've added this line to `nginx.conf` file:

```
resolver 172.17.0.1;
```

then I can specify database in Lua code like this:

```Lua
host = "db.weave.local"
```

the question is is it safe to use the `172.17.0.1` for resolver? is this IP stable, or I should obtain it with some command and inject to my nginx config?

Moved from #2157

**Comment by bboreham** [comment]
Thanks for opening as a new issue.

With the current implementation, WeaveDNS listens on the address of the bridge `docker0`, which is created by Docker.  So Docker picks that address; it should be stable if the machine itself doesn't change, but we cannot govern what they do.

You can obtain the address via `weave dns-args`

Some thoughts on making this address configurable at #1770.

**Comment by bboreham** [comment]
Closing; if there is more to discuss please re-open.
