### ISSUE TITLE
WEAVE_NO_FASTDP=true doesn't work

### ISSUE THREAD

**Issue by iwasnobody** [weaveworks/weave#2984]
WEAVE_NO_FASTDP=true
weave launch another_host
in version 1.9.5

But the command 'weave status connections' still show fastdp.
How to let weave run in sleeve mode?

**Comment by marccarre** [comment]
Hi @iwasnobody, could you please provide the set of steps which led to this outcome?

Quickly double-checking Weave Net 1.9.5 on my end leads to the expected behaviour:

- With FastDP (see: `fastdp` mode below):
```
host1$ weave launch
host2$ weave launch 10.128.0.4
host1$ weave status connections
<- 10.128.0.5:39587      established fastdp fa:e4:95:79:91:ac(host2) mtu=1376
host2$ weave status connections
-> 10.128.0.4:6783       established fastdp f6:42:b8:5c:0b:04(host1) mtu=1376
```

- Without FastDP (see: `sleeve` mode below):
```
host1$ WEAVE_NO_FASTDP=true weave launch
host2$ WEAVE_NO_FASTDP=true weave launch 10.128.0.4
host1$ weave status connections
<- 10.128.0.5:33249      established sleeve f6:42:b8:5c:0b:04(host2) mtu=1398
host2$ weave status connections
-> 10.128.0.4:6783       established sleeve fa:e4:95:79:91:ac(host1) mtu=1398
```

**Comment by bboreham** [comment]
bump @iwasnobody

**Comment by iwasnobody** [comment]
@marccarre It's my fault.
It just split the command to two line
WEAVE_NO_FASTDP=true 
weave launch

That's the problem, thanks

**Comment by marccarre** [comment]
@iwasnobody, thanks for your confirmation, I'm closing this issue then.
Feel free to reach out on [Slack](http://weave-community.slack.com/) if you face any other difficulty!
