### ISSUE TITLE
[Question]IPAM management in weave net

### ISSUE THREAD

**Issue by selvakumarnms** [weaveworks/weave#2999]
Hi All,
I just wanted to know how to make REST API for calling the weave net IPAM . I wanted to use the IPAM service for external IP management in kubernetes

_Edited: removed unused parts of the template_

**Comment by bboreham** [comment]
The REST API is internal to Weave Net and intentionally undocumented; we may decide to change how it works and don't want to feel bad that people built dependencies.

That said, the source code is here; you can probably figure it out from https://github.com/weaveworks/weave/blob/master/api/ipam.go#L35-L45

If you're using Kubernetes could you call the CNI plugin?

**Comment by selvakumarnms** [comment]
Hi thanks for the  responses.
Iam using kubernet cluster I wanted to implement a IPAM service for kubernet external IP management for the service. So I thought I can use weave net for ipam management.
How  to achieve through the cni plugin ?
Your help would be appreciated

**Comment by bboreham** [comment]
It's probably not useful for your service idea, but CNI plugins are programs you run with certain environment variables and config in JSON.

For example:

```
$ CNI_COMMAND=ADD CNI_NETNS='x' CNI_IFNAME='y' CNI_PATH='z' CNI_CONTAINERID='containerID' /opt/cni/bin/weave-ipam < /etc/cni/net.d/10-weave.conf 
{
    "ip4": {
        "ip": "10.32.0.4/12"
    },
    "dns": {}
}
```

For IPAM, the values of `CNI_NETNS`, `CNI_IFNAME` and `CNI_PATH` are not important.

**Comment by selvakumarnms** [comment]
Thanks @bboreham  for the clarifications I will try this option

**Comment by selvakumarnms** [comment]
@bboreham  Sorry .. I missed to ask another question based on your reply.
After running the /opt/cni/bin/weave-ipam command I got the below output 
{
    "ip4": {
        "ip": "10.32.0.4/12"
    },
    "dns": {}
}
But i dont see any process running , and another question is can I make any REST call to this container/pod once the weavnet-ipam is deployed for allocating and dell locating the ip address?

**Comment by marccarre** [comment]
@selvakumarnms, sorry, I am not sure I understand what you meant:
1. what did you expect to be running?
> But i dont see any process running

2. which container/pod are you talking about here? if your container is, for example, `nginx`, yes you would.
> can I make any REST call to this container/pod

**Comment by selvakumarnms** [comment]
I expect some process will be running after executing the command weave-ipam .
 Regarding 2 I wanted to know how the weave pod serves the ipam request from ?
How to make rest calls for allocate Ip other out of band than during pod creation?

**Comment by marccarre** [comment]
@selvakumarnms, I am still not sure I fully understand what you want to achieve, so clarifying this first may help us better advise you.

In any case, to answer question 1, no new process will be permanently created as a result of calling `weave-ipam`, it simply: 

- a. calls [`weaveutil`](github.com/weaveworks/weave/blob/master/prog/weaveutil/main.go#L59), which
- b. calls [libCNI](github.com/weaveworks/weave/blob/master/prog/weaveutil/cni.go#L25) (see also [here](https://github.com/containernetworking/cni/blob/master/pkg/skel/skel.go#L221)), which
- c. calls [Weave Net's CNI plugin](https://github.com/weaveworks/weave/blob/master/plugin/ipam/cni.go#L13), which creates the specified network interface inside the specified container, [allocates an IP](https://github.com/weaveworks/weave/blob/master/plugin/ipam/cni.go#L25) for the specified container (via [the code **bboreham** mentioned](https://github.com/weaveworks/weave/blob/master/api/ipam.go#L35-L45)), etc. -- I believe this answers question 2.
- d. Kubernetes, which keeps polling for changes, eventually detects this.

This is essentially the CNI equivalent of a [`weave attach`](https://www.weave.works/docs/net/latest/using-weave/dynamically-attach-containers/). See also: CNI's [`SPEC.md](https://github.com/containernetworking/cni/blob/master/SPEC.md) and [Weave Net's implementation](https://github.com/weaveworks/weave/tree/master/plugin).

**Comment by marccarre** [comment]
I am closing this issue for now. Feel free to reopen if you have any other question.
