### ISSUE TITLE
[Question]Deleting the weave-net pod 

### ISSUE THREAD

**Issue by selvakumarnms** [weaveworks/weave#3002]
Hi All,
I have installed the weave plugin through kubectl apply, Now I want to remove the pods that is running on kube-system namespace , is there any way to uninstall the weave plugin?
I tried deleting the pods and it is coming back as it is deployed as daemonset.

_Edited: removed unused parts of the template_

**Comment by marccarre** [comment]
Hi @selvakumarnms, 
The way to remove the pods is via [`kubectl delete`](https://kubernetes.io/docs/user-guide/kubectl-overview/). For example, if you created the Weave Net pods using:
```
$ kubectl -n kube-system apply -f https://git.io/weave-kube-1.6
```
you would remove them using:
```
$ kubectl -n kube-system delete -f https://git.io/weave-kube-1.6
```

**Comment by kasheemlew** [comment]
I tried to use `$ kubectl -n kube-system delete -f https://git.io/weave-kube-1.6` to remove, but it hung. I wonder why it did not proceed

```
$ kubectl -n kube-system delete -f https://git.io/weave-kube-1.6
clusterrole "flannel" deleted
clusterrolebinding "flannel" deleted
serviceaccount "flannel" deleted
configmap "kube-flannel-cfg" deleted

```

**Comment by bboreham** [comment]
@kasheemlew it's better to create your own issue than to piggy-back on an old one.

That said, it's extremely surprising that the Weave Net config would delete a _flannel_ role or account.  Could you double-check?

To find out more about what `kubectl` is doing, increase the logging level, e.g. `kubectl -v=8 -n kube-system delete -f https://git.io/weave-kube-1.6`

**Comment by wen73** [comment]
> Hi @selvakumarnms,
> The way to remove the pods is via [`kubectl delete`](https://kubernetes.io/docs/user-guide/kubectl-overview/). For example, if you created the Weave Net pods using:
> 
> ```
> $ kubectl -n kube-system apply -f https://git.io/weave-kube-1.6
> ```
> you would remove them using:
> 
> ```
> $ kubectl -n kube-system delete -f https://git.io/weave-kube-1.6
> ```

> Hi @selvakumarnms,
> The way to remove the pods is via [`kubectl delete`](https://kubernetes.io/docs/user-guide/kubectl-overview/). For example, if you created the Weave Net pods using:
> 
> ```
> $ kubectl -n kube-system apply -f https://git.io/weave-kube-1.6
> ```
> you would remove them using:
> 
> ```
> $ kubectl -n kube-system delete -f https://git.io/weave-kube-1.6
> ```

thanks, it work for me.

**Comment by Winterhart** [comment]
Assuming you've installed the weave package using:

```sh
export VAL=$(kubectl version | base64 | tr -d '\n')
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$VAL"
```

You can remove it using the same config file.

```sh
kubectl delete -f "https://cloud.weave.works/k8s/net?k8s-version=$VAL"
```
