### ISSUE TITLE
weave AMI of aws has a bug---fixed by myself

### ISSUE THREAD

**Issue by iwasnobody** [weaveworks/weave#3004]
AMI used: ami-f560d8e3
region: us-east-1

/etc/weave/peers.sh has the following command:
peer_instances=$($aws ec2 describe-tags --filters "Name=resource-type,Values=instance,Name=tag:weave:peerGroupName,Values=$PEER_GROUP_NAME" --query "Tags[?ResourceId!=\`$current_instance_id\`].ResourceId" --output text)

Should be modified to:
peer_instances=$($aws ec2 describe-tags --filters "Name=resource-type,Values=instance" "Name=tag:weave:peerGroupName,Values=$PEER_GROUP_NAME" --query "Tags[?ResourceId!=\`$current_instance_id\`].ResourceId" --output text)

Otherwise, EBS volume with the same tags will also returned

**Comment by pidster** [comment]
Thanks for the report!

This has been fixed and we'll push a release out shortly to update the AMIs.
