### ISSUE TITLE
How to export DOCKER_HOST env var running from SYSTEMD service

### ISSUE THREAD

**Issue by guillelb** [weaveworks/weave#3008]
- OS: `Ubuntu 16.04.2 LTS`
- Weave:
`weave script 1.9.7`
`weave router 1.9.7`
`weave proxy  1.9.7`
`weave plugin 1.9.7`
- Docker:
` Version:      1.12.6`
` API version:  1.24`

Everything works OK when I manually run weave:

`weave launch $PEERS`
`eval $(weave env)`
`docker run -ti busybox sh`
 
But, when I configure weave as a systemd service, It doesn't create the veth interface.
Following the documentation:
https://www.weave.works/docs/net/latest/installing-weave/systemd/

When I reboot the machine, weave.service is up, but the  env var  `DOCKER_HOST` is not setted:

How can I set the env var  `DOCKER_HOST` from the systemd service start?

**Comment by marccarre** [comment]
Hi @guillelb, just to be sure I understand correctly:
1. `weave` gets `launch`-ed by `systemd` on your machine, then
2. from some shell on your machine, you run `docker run -ti busybox sh`
    (without `eval $(weave env)` beforehand),
3. `ethwe`, Weave Net's veth, does not get created inside the `busybox` container,

is that right?

----

If so, that's expected, and you either:
- need `eval $(weave env)` before starting your container, or
- need to set `DOCKER_HOST` in:
  - your `~/.bashrc` (or equivalent for your shell), or
  - `/etc/environment`, 

as when you run `eval $(weave env)`, it basically sets `DOCKER_HOST` in the current shell:
```
$ weave env
export DOCKER_HOST=unix:///var/run/weave/weave.sock
```
and I don't think anything does that in your current setup.

----

Weave Net doesn't override `DOCKER_HOST` by default as there are multiple ways to work with Weave Net:
- as a Docker plugin
- as a Docker proxy
- as a CNI plugin
- etc.

and setting `DOCKER_HOST`, which means using it as a Docker proxy, is just one way among many.

**Comment by marccarre** [comment]
I am closing this issue for now. Feel free to reopen if you have any other question.

**Comment by guillelb** [comment]
Thank you, It is working perfect as a CNI plugin after reboot. I thought that I needed to create the env vars manually.
