### ISSUE TITLE
Unable to uninstall weave fully

### ISSUE THREAD

**Issue by reachrkr** [weaveworks/weave#3020]
I am unable to find any relevant  docs on how can i remove weave completely from my docker host . I have been trying to remove it clean on my archlinux host  , but failed though . I still see the dangling interfaces and veth pairs. Can somebody please point me on how to uninstall clean weave from my system .

**Comment by bboreham** [comment]
`weave reset` should work. 

If it doesn't, please provide more detail.

**Comment by reachrkr** [comment]
there was some issue, weave reset didn't work for me  first time .
 weave launch-router  followed by weave reset failed . i re-installed and wiped it clean , it worked now with launch and reset options .  closing it as isssue is resolved,

Thanks . 
Rajesh
