### ISSUE TITLE
Question: why weave modifies entrypoint to /w/w?

### ISSUE THREAD

**Issue by avkonst** [weaveworks/weave#3026]
Hi,

I have got few questions around /w/w process:
- why weave modifies entrypoint to /w/w?
- does it provide process "subreaper" functionaly?
- if no, is it safe to modify entrypoint for the container I attach to (start via weave proxy) weave net? I would like to modify entry-point to be "docker-init -s --", if /w/w does not provide process subreaper function.

Thank you for your answers.

**Comment by bboreham** [comment]
The `/w/w` program waits for the Weave network to become ready for use.  If you don't wait, then an attempt to connect to an address will route through the other network interface inside the container, the Docker interface, which is not attached to the Weave network.

Then `/w/w` calls the entrypoint defined for the container.

It does nothing else, no subreaper.  The source code is [here](https://github.com/weaveworks/weave/tree/master/prog/weavewait)

If you want to use a different entry-point then you can add the waiting function into your code, or decide it isn't necessary.  For instance if you listen on all interfaces (0.0.0.0) then Linux will do the right thing when the Weave interface is added.

Another alternative is to use the Docker plugin, then Docker doesn't start the entrypoint until after network setup is complete.

**Comment by avkonst** [comment]
Thanks. If a container has got defined entrypoint, will weave proxy discard it? or push to the command line instead?

**Comment by bboreham** [comment]
Suppose the defined entrypoint is `/bin/foo`, then this will be rewritten as `/w/w /bin/foo`

**Comment by avkonst** [comment]
Thanks!

**Comment by marccarre** [comment]
Closing this issue for now; feel free to reopen if you have questions **@avkonst**

**Comment by avkonst** [comment]
oh. Thanks. I do not have more questions about this area.
