### ISSUE TITLE
yaml generator asks for weave-kube 2.0.0 but tag doesn't exist

### ISSUE THREAD

**Issue by deitch** [weaveworks/weave#3029]
## What you expected to happen?

yaml generator would generate usable yaml

## What happened?

generated yaml asks for `weaveworks/weave-kube:2.0.0` but that doesn't exist

## How to reproduce it?

```
$ curl "https://cloud.weave.works/k8s/v1.6/net.yaml" > /tmp/w
$ grep image /tmp/w
              image: 'weaveworks/weave-kube:2.0.0'
              imagePullPolicy: Always
              image: 'weaveworks/weave-npc:2.0.0'
              imagePullPolicy: Always

# see that it doesn't exist
$ docker pull weaveworks/weave-kube:2.0.0
Error response from daemon: manifest for weaveworks/weave-kube:2.0.0 not found
$ docker pull weaveworks/weave-npc:2.0.0
Error response from daemon: manifest for weaveworks/weave-npc:2.0.0 not found
```

Looks like generator got ahead of the image. :-)

**Comment by bboreham** [comment]
Thanks for this @deitch - release 2.0.0 was in a 'draft' state which is why the launch generator tool could see it and you couldn't.

I'll leave this open for tracking since the LG repo is private.
