### ISSUE TITLE
Fastdp heart beat time out

### ISSUE THREAD

**Issue by SebastienDorgan** [weaveworks/weave#3037]
Hello,

I deploy VMs using automation scripts on a public cloud using open stack and I connect containers running on this VMs using Docker with an Etcd KV store and Weave net plugin as network driver.
 - Docker 17.03 ce 
 - Weave 2.0

I expected that weave cloud run using fastdp but when I checked _weave status connections_ it was sleeve.
Analysing the result of _docker logs weave_ I found that weave fallback to sleeve because of a Fastdp heart beat timeout.
So I have checked that port 6784 was open using nc and it was. I run tcp dump to analyse trafic on vxlan-6784 interface and I could see some trafic.
After that I checked kernel logs to see what's happens arround the timeout error and I see that my VM was very busy by etcd trafic.
I have reconfigured weave by hand once etcd trafic was less intensive and this time its works correctly, so I conclude that I was experiencing this timeout error because my VM was to busy.
Don't you think it could be interesting to add the possibility to users to increase the heart beat timeout or to implement a retry mechanism?

**Comment by rade** [comment]
> implement a retry mechanism?

See #1737.

**Comment by SebastienDorgan** [comment]
Not during the whole life cycle of the router but before establishing the connection.
Looking at fastDatapathForwarder.Confirm method I can see that you try to acquire the heart beat only once, maybe you can let to the kernel an another chance to answer a few seconds later?

**Comment by bboreham** [comment]
Although it is correct to say we could implement two different retry mechanisms, I don't see any point since #1737 will cover both kinds of failure.  I'm going to close this.
