### ISSUE TITLE
Service account in Weave pod doesn't have necessary permissions

### ISSUE THREAD

**Issue by bronger** [weaveworks/weave#3038]
With Kubernetes 1.6.6 and the YAML file generated with <https://cloud.weave.works/k8s/v1.6/net.yaml?k8s-version=1.6.6>, the Weave pods would not come up, and the logs say

    2017/06/26 06:48:12 error contacting APIServer: the server does not allow access to the requested resource (get nodes); trying with fallback: http://localhost:8080
    2017/06/26 06:48:12 Could not get peers: Get http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused
    Failed to get peers

I suspect a relation to #2847 but the workaround described there (deleting the secret and the pods, forcing re-creation) does not work for me.  Moreover, I can reproduce this issue reliably.

**Comment by bboreham** [comment]
Did you have `-n kube-system` in the command-line?

I'm trying to get this changed, but for now you have to do that when using the launch config generator.

**Comment by bronger** [comment]
Alright, with `-n kube-system`, it works.  Thank you!  Is there a ticket to follow so that I can remove the `-n` when it becomes unnecessary?

**Comment by bboreham** [comment]
@bronger I think #3006 will serve
