### ISSUE TITLE
Unable to start weave 2.0 on kubernetes 1.6.1

### ISSUE THREAD

**Issue by meatlewis** [weaveworks/weave#3040]
So the cluster might just be in a bad state but when I try to "install" weave via a daemonset all the pods crash with this error:

```
INFO: 2017/06/26 14:04:04.465734 Starting Weaveworks NPC 2.0.0; node name "ip-172-20-114-111"
INFO: 2017/06/26 14:04:04.466390 Serving /metrics on :6781
FATA: 2017/06/26 14:04:04.466528 Failed to bind metrics server: listen tcp :6781: bind: address already in use
```

As some background I was previously running weave on kubernetes, but I destroyed it while troubleshooting issues with using kubectl proxy to get to the dashboard.

**Comment by meatlewis** [comment]
This turned out to be a weird config issue, somehow I had a daemonset running in the default namespace.

**Comment by marccarre** [comment]
@meatlewis you must have previously run `kubectl apply -f` instead of [`kubectl -n kube-system apply -f`](https://www.weave.works/docs/net/latest/kube-addon/). FYI, we are making `-n kube-system` the default to avoid similar confusions -- see: #3006, #3033, #3038.
