### ISSUE TITLE
Should hostname be on weave-npc?

### ISSUE THREAD

**Issue by justinsb** [weaveworks/weave#3049]
We're trying to update the weave manifest in kops, but it looks like HOSTNAME is now defined on weave rather than on weave-npc: https://github.com/weaveworks/weave/blob/master/prog/weave-kube/weave-daemonset-k8s-1.6.yaml

In https://github.com/weaveworks/weave/pull/2996 it was added to weave-npc, which makes more sense to me.

Is this an error in the manifest, or was this changed in weave 2.0.1?

**Comment by bboreham** [comment]
Looks like it got screwed up in the merge commit https://github.com/weaveworks/weave/commit/7871a0b7a47dd651b740f3095081dc5a3a3a099f

My intention was to set it on both containers.

**Comment by marccarre** [comment]
N.B.: this change is now also present in our YAML generator.
