### ISSUE TITLE
question: what is the correct procedure to upgrade weave?

### ISSUE THREAD

**Issue by avkonst** [weaveworks/weave#3050]
I have got weave net running in proxy mode. My question is in general (but if it matters I have got current version 1.9.7).

- What actions should I do in order to upgrade life node without losing data and network settings (like IP assignments, peers, etc.)?
- Is there any difference depending on number of nodes connected? I am interested in use cases when there are 1, 2, 3, and 5 nodes.

Thanks!

**Comment by bboreham** [comment]
We have some [documentation on upgrades](https://www.weave.works/docs/net/latest/operational-guide/tasks/#cluster-upgrade) 
* Attached containers will continue to run with their existing IP address, etc., by default.  
* Persisted data is in a volume container `weavedb`; the new version will pick that up.

By default, each time you run `weave launch` it will take the list of peers from that command; you can ask it to use the previous list of peers with `--resume`

There should be no difference for different numbers of nodes.

**Comment by avkonst** [comment]
Thank you. Could you please clarify about the peers. Let's consider the following example:
I build Uniform Dynamic Cluster and increase it's size when needs come:
```
host1$ weave launch --name ::1 --ipalloc-init seed=::1,::2,::3
# very much later
host2$ weave launch --name ::2 --ipalloc-init seed=::1,::2,::3 host1
# very much later
host3$ weave launch --name ::3 --ipalloc-init seed=::1,::2,::3 host1 host2
# very much later
host4$ weave launch --ipalloc-init seed=::1,::2,::3 host1 host2 host3
# very much later
host5$ weave launch --ipalloc-init seed=::1,::2,::3 host1 host2 host3
```
I assume that at the end all hosts become aware about each other. So, executing the following:
```
host1$ weave stop
host2$ weave launch --resume
```
should be equal to the following (note all peers are known at this stage)?
```
host1$ weave stop
host1$ weave launch --name ::1 --ipalloc-init seed=::1,::2,::3 host2 host3 host4 host5
```
Is that right?

I see the note in the docs: "For maximum robustness, you should distribute an updated /etc/sysconfig/weave file including the new peer to all existing peers." But what happens if I do not do this for host1 when I add host2? What happens if I do not do this for hosts 1 and 2 when I add host3?What is the downside?

**Comment by avkonst** [comment]
Could you please provide with the quick answer for the above question?

**Comment by bboreham** [comment]
Sorry this question got lost.

`--resume` means to use the list of peers that this peer has been told to connect to, so it would be blank.  It is the sum of any list on the `launch` line and any subsequent `weave connect` or `weave forget` operations.  It does not include any peers discovered through gossip.

Regarding "maximum robustness", the downside is that you are relying on host2 making a connection to host1 if host1 goes down for a while then restarts.  It will re-try this periodically, up to every six minutes, but it would be better for host1 to know about host2 then it will try to connect immediately on restart.

**Comment by avkonst** [comment]
Thanks. Does it mean that the maximum robustness is when every host is
aware (launch or connect) about every other? It is a bit sad that gossip
does not allow to achieve this automatically... Would it be possible to
enable nodes, which auto-discovered with gossip, to auto-`weave connect`
with each other?

Is there any way to execute `host1> weave connect host2` operation via a
command similar to `host1> docker exec weave-proxy
<run-some-command-to-connect> host2`? I mean I can execute docker remotely,
so it would help me to execute `weave connect` remotely too (from host2 for
host1)?

**Comment by bboreham** [comment]
Peers will all find each other via gossip sooner or later; however in your specific example it will come up and connect to nobody so will have to wait for somebody else to connect to it.  @awh I think "maximum robustness" was your phrase - are there any other things to watch out for in the pre-seeded case ?

You can run `weave` commands remotely, since they all execute via docker:

    DOCKER_HOST=tcp://host1:2375 weave connect

(assuming you have opened that port and asked the docker daemon to listen on it)

**Comment by avkonst** [comment]
Great! Thanks. If "maximum robustness" needs explicit connect (?), I will
add it to my automation by invoking remote docker connecting via weave net
itself (I have got docker APIs exposed via http proxy inside of the weave
net cluster for every node).

**Comment by christian-2** [comment]
@bboreham Could you please also clarify about upgrading in the context of Kubernetes. Is it just a matter of replacing `daemonset/weave-net` with a version that refers to the newer images (e.g. 2.6.0 instead of 2.5.2), so perhaps just another:

    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

**Comment by bboreham** [comment]
Yes, for Kubernetes that endpoint should serve up the latest released version and the DaemonSet should then do a rolling upgrade.
