### ISSUE TITLE
Lost docker sock autobinding with new version

### ISSUE THREAD

**Issue by farfeduc** [weaveworks/weave#3063]
Hi ! 

Before the 2.0 version I could start Weave, stop the proxy and restart the proxy with `weave launch-proxy -H unix:///var/run/docker.sock --rewrite-inspect` without issues.

This way, all the containers I started where automatically available :)
(It is very convenient for me because I manage my containers with rancher).

But with the 2.0 version, a similar command might be `weave launch -H unix:///var/run/docker.sock --rewrite-inspect` but it fails to launch properly. I think it is because the other components beside the proxy need to properly start using the docker.sock without it being tampered with.

## Temporary solution

So I found the following solution : 
- Start docker on a `/var/run/docker-real.sock`
- Create a symbolic link to `/var/run/docker.sock`
- Start Weave with `weave launch --rewrite-inspect`
- Remove `/var/run/docker.sock` and create symbolic link from `weave.sock` to `/var/run/docker.sock`
- Start containers normally.

But this solution is not particularly elegant and does not persist on restart of the host.

## Ideal solution

It would be nice if there could be an option to use the `/var/run/docker.sock` directly (working even after a docker daemon restart if possible).

Or maybe fix the error in the case of a binding on `/var/run/docker.sock`.

This would be great for tools like Rancher that do not provide weave integration or a list of the available networks (to bind with net=weave) other than the default ones.

-----------------------------------------

If you have other solutions to propose I will gladly try them !

If yo want more details on the error I am encountering when start weave with `weave launch -H unix:///var/run/docker.sock --rewrite-inspect` please do not hesitate to ask, I will add them to this issue.

## Versions:
```
$ weave version
weave script 2.0.1
weave 2.0.1

$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ uname -a
Linux myhost 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
```

**Comment by brb** [comment]
@farfeduc Thanks for opening the issue.

I guess you misunderstood the usage of the weave proxy `-H` param. It supposed to specify a different endpoint than Docker is listening to. All requests sent to that endpoint are proxied to dockerd, so weave is not supposed to try to bind to the one dockerd is listening to. Please see https://www.weave.works/docs/net/latest/tasks/weave-docker-api/weave-docker-api/#weave-api-proxy for more details.

Out of curiosity, what error message did you get?
