### ISSUE TITLE
weave on arm crashing

### ISSUE THREAD

**Issue by stevesloka** [weaveworks/weave#3081]
## What you expected to happen?

Weave runs on my arm cluster.

## What happened?

Pod is crashing with following error:
```
modprobe: module br_netfilter not found in modules.dep
Ignore the error if "br_netfilter" is built-in in the kernel
modprobe: module xt_set not found in modules.dep
Ignore the error if "xt_set" is built-in in the kernel
iptables: No chain/target/match by that name.
"xt_set" does not exist
```

## How to reproduce it?

`kubectl apply -f https://git.io/weave-kube-1.6`

## Anything else we need to know?

Running on RPI 3 Cluster with ODROID XU4 as the master. 

## Versions:

```
$ weave version: 2.0.1
$ docker version
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:09 2017
 OS/Arch:      linux/arm

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:09 2017
 OS/Arch:      linux/arm
```
$ uname -a: Linux odroid 3.10.105-142 #1 SMP PREEMPT Fri Aug 4 03:58:46 UTC 2017 armv7l armv7l armv7l GNU/Linux
$ kubectl version: 1.7.3
```

**Comment by rade** [comment]
Looks like you are missing some kernel modules.

**Comment by stevesloka** [comment]
Do you have any hints as to which one's and how to enable? I'm running ubuntu 16.04 on arm.

**Comment by stevesloka** [comment]
Looks like my kernel is 3.10, upgrading now.

**Comment by stevesloka** [comment]
that was my problem, updating to kernel 4.9 and all works, thanks!
