### ISSUE TITLE
Encryption strength for inter-node traffic

### ISSUE THREAD

**Issue by avkonst** [weaveworks/weave#3086]
It is a question. I use weave net to connect containers across multiple nodes with inter-node traffic encryption enabled. I wonder how I can rate the strength of encryption for traffic between nodes? Let me explain. Some of stakeholders used to do rating of encryption by the websites like https://www.ssllabs.com/ssltest/
It basically rates based on cipher suite used. Now, when I can not configure cipher suites for weave encryption (which is a good thing, I do not want to worry about this configuration), I can not really answer the question about the strength of encryption for inter-node traffic. This is anticipated to come up as a question during security audit by external party. And it worries me that having no answer may not certify some security criteria and "fail" the audit.
What is the best way to answer this question, so that an auditor is convinced about the highest strength of encryption applied by weave net? And make an auditor to believe that weave encryption strength is as good as this rating (for example): https://www.ssllabs.com/ssltest/analyze.html?d=www.ssllabs.com&hideResults=on

Thank you for your help!

**Comment by bboreham** [comment]
Hi @avkonst and thank you for your question.

We give details on the encryption methods used, key sizes, etc., [here](https://www.weave.works/docs/net/latest/concepts/encryption-implementation/) and [here](https://github.com/weaveworks/weave/blob/master/docs/fastdp-crypto.md) (In short: either [AES in GCM mode](https://tools.ietf.org/html/rfc4106), or [Curve25519+Salsa20+Poly1305](https://cr.yp.to/highspeed/naclcrypto-20090310.pdf) with 256-bit keys).

Note that, in "fast datapath" mode (the default), the encryption is all done inside the Linux kernel; Weave Net just configures what gets done.

**Comment by avkonst** [comment]
Thank you guys.
