### ISSUE TITLE
dns stopped working inside containers

### ISSUE THREAD

**Issue by caarlos0** [weaveworks/weave#3118]
## What you expected to happen?

DNS inside containers running on a kubernetes cluster should resolve external addresses.

## What happened?

Containers couldn't resolve any address, for, example, google.com or amazon.com .

## How to reproduce it?

The cluster entered didn't have any more IPs to use, due to #2797. I used the script provided to remove the peers that don't exist anymore from the cluster.

That apparently worked for a while (can't confirm 100% sure), but later we found out that DNS inside new containers was not working.

`weave status ipam` was showing that all nodes were unreacheable:

```
/home/weave # ./weave --local status ipam
1a:a5:74:30:7c:3d(ip-10-10-201-41)           1 IPs (00.0% of total) (1 active)
ee:bb:0c:34:ab:31(ip-10-10-201-254)       2048 IPs (00.2% of total) - unreachable!
52:60:b2:bd:1a:a3(ip-10-10-200-19)       49152 IPs (04.7% of total) - unreachable!
66:42:12:77:e0:d2(ip-10-10-200-33)       65536 IPs (06.2% of total) - unreachable!
f6:34:d7:e3:af:c9(ip-10-10-201-185)      32768 IPs (03.1% of total) - unreachable!
5a:9f:68:70:ca:de(ip-10-10-201-122)     736103 IPs (70.2% of total) - unreachable!
8e:63:bc:56:4c:ca(ip-10-10-200-46)         512 IPs (00.0% of total) - unreachable!
72:a9:cc:8a:c5:3b(ip-10-10-200-125)       4096 IPs (00.4% of total) - unreachable!
a2:b6:29:8b:be:b7(ip-10-10-200-97)      131072 IPs (12.5% of total) - unreachable!
c2:1a:8b:80:ab:4c(ip-10-10-200-14)         512 IPs (00.0% of total) - unreachable!
ea:43:20:d6:aa:c8(ip-10-10-200-200)       8192 IPs (00.8% of total) - unreachable!
d2:45:4c:6c:e9:d6(ip-10-10-201-125)          8 IPs (00.0% of total) - unreachable!
6a:9b:f8:c5:11:1e(ip-10-10-201-116)         16 IPs (00.0% of total) - unreachable!
2a:5c:6c:40:2b:fb(ip-10-10-201-122)        128 IPs (00.0% of total) - unreachable!
2e:5e:65:75:fc:71(ip-10-10-200-83)       16384 IPs (01.6% of total) - unreachable!
7e:f5:cb:0b:3e:a3(ip-10-10-201-109)       1024 IPs (00.1% of total) - unreachable!
9e:68:a6:65:ee:1d(ip-10-10-200-22)        1024 IPs (00.1% of total) - unreachable!
```

It was late friday night and we tried several thing (like killing every weave pod, one by one, and also killing all nodes), but nothing was able to fix the issue.

We end up removing the weave daemonset and re-creating it.

I'm not sure if this is a problem in weave itself or if weave causes it, nor if it is strictly related to the rmpeers bug, all I can say is that I see this happening, in this same order, in 2 different occasions and 2 different kubernetes clusters.

## Anything else we need to know?

K8s 1.5.7 cluster created on AWS sa-east-1 with kops.

## Versions:

```
$ weave version
/home/weave # ./weave version
weave script 2.0.4
./weave: line 252: docker: not found
ERROR: Unable to parse docker version
/home/weave # ./weave --local version
Unable to find weaveworks/weave:2.0.4 image.
/home/weave #

(was 1.9.4 at the time of the bug)

$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
admin@ip-10-10-200-130:~$ sudo docker version
sudo: unable to resolve host ip-10-10-200-130
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
admin@ip-10-10-200-130:~$
$ uname -a
$ kubectl version
```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
```

don't have the logs anymore, unfortunately.

## Network:

```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by caarlos0** [comment]
same thing happen on another cluster today...

**Comment by bboreham** [comment]
@caarlos0 can you clarify the symptoms please?

If possible, use a dedicated DNS client like `dig` or `nslookup`.
Does it fail to resolve both Kubernetes and external addresses, or just external?  (i.e. can it resolve something like `kubernetes.default.svc.cluster.local`?).

If it's just external addresses, can the `kube-dns` pod contact external machines?  (i.e. can you `kubectl exec /bin/sh` inside that pod and ping the IP address of a machine elsewhere on the network?)

**Comment by caarlos0** [comment]
@bboreham 

> If possible, use a dedicated DNS client like dig or nslookup.

I did that.

> Does it fail to resolve both Kubernetes and external addresses, or just external? (i.e. can it resolve something like kubernetes.default.svc.cluster.local?).

not sure, but probably all. My pods don't use any internal kubernetes endpoints, so I didn't checked for that... What I can confirm is that things like aws, google, etc were not being resolved. Ping to previously resolved IPs wasn't working as well.

> If it's just external addresses, can the kube-dns pod contact external machines? (i.e. can you kubectl exec /bin/sh inside that pod and ping the IP address of a machine elsewhere on the network?)

didn't test for that. Can do when this happens again.

---

another info I have is that the `weavenpc_blocked_connections` was high in one of the pods when the problem was happening (and also long before, it seems):

![screen shot 2017-09-25 at 11 27 08](https://user-images.githubusercontent.com/245435/30813704-87d6c6fc-a1e4-11e7-8893-f5edb04def9e.png)

**Comment by bboreham** [comment]
> I did that.

Ok, if you could say what the output was, that'd be useful.

> `weavenpc_blocked_connections` was high 

that's a counter (not a gauge), so you would be more interested in `rate(weavenpc_blocked_connections)`

the details of which exact connections were blocked would be in the `weave-npc` logfile.

Sometimes individual packets can be blocked because the connection started before the information arrived to open the rule up; tcp will retry very soon and nobody notices, but the counter will increment.
We have `weave-npc` set to log at debug level which makes it possible to diagnose things like that (and makes the logfiles quite large).

**Comment by caarlos0** [comment]
> Ok, if you could say what the output was, that'd be useful.

sorry, I forgot to save them :/



> that's a counter (not a gauge), so you would be more interested in rate(weavenpc_blocked_connections)

`rate(weavenpc_blocked_connections_total[5m])` is `0`.

**Comment by caarlos0** [comment]
I really don't have enough info right now... A good way to test this is to fire up a cluster, start and stop lots of pods (could be in a single node), until that node has almost all IP allocations in the range, than, kill the node, start new nodes, and create more pods... this should cause that bug in which IP allocations are not released, and manually removing the nodes from weave is causing this issue (or at least was causing it in weave 1.9.4).

**Comment by bboreham** [comment]
Is that the same as #2797 ?

**Comment by caarlos0** [comment]
@bboreham not quite, the script solution provided for that bug causes this one (at least in some cases, since no one else reported)...

**Comment by rade** [comment]
Seems like we've reached a dead end here in the investigation. -> closing.
