### ISSUE TITLE
Connecting through a service with network policies is blocked

### ISSUE THREAD

**Issue by mmerrill3** [weaveworks/weave#3139]
## What you expected to happen?

I created a default namespace called mike, and set that to my default namespace in my kube context.

I annotated the namespace for this example https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/#limit-access-to-the-nginx-service with 

kubectl annotate ns mike net.beta.kubernetes.io/network-policy='{"ingress":{"isolation":"DefaultDeny"}}'

I needed to do this to simulate 1.7 k8s network policy behavior.  My cluster is version 1.7.6.  My weave npc version is 2.0.4

## What happened?
Per the example, the last step traffic should be allowed through when the container is started with the correct label to allow traffic.  This is not allowed through.  I see the same results with any service that is trying to access to target pods in a namespace.  Only pods are allowed to talk to the target pods.  If traffic is through the service, the traffic is disallowed.

## How to reproduce it?
I created a namespace called mike

kubectl create ns mike

Next, I annotate it

kubectl annotate ns mike net.beta.kubernetes.io/network-policy='{"ingress":{"isolation":"DefaultDeny"}}'

Then, I run through the nginx example here https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/#limit-access-to-the-nginx-service

This fails at the final step, when a properly labelled pod tries to access the nginx service.

## Anything else we need to know?
Running on a 1.7.6 cluster created through kops in AWS.

## Versions:

```
$ weave version
2.0.4
$ docker version
$ uname -a
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
```

## Network:

```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by bboreham** [comment]
Hi, could you say exactly what policies you have applied?  The syntax understood by Weave Net is a little different from that in the current Kubernetes docs - see #3105

**Comment by mmerrill3** [comment]
Hi @bboreham, below is the policy that I applied.  Before I applied to policy, for the mike namespace, I annotated it with the default deny annotation.  This was the command:

kubectl annotate ns mike net.beta.kubernetes.io/network-policy='{"ingress":{"isolation":"DefaultDeny"}}'

After that, all ingress traffic would be blocked from all pods, unless a network policy was defined to allow access from pods with specific labels. So, the next step I did was to follow the k8s example for nginx, and create a policy to allow traffic from pods labelled with access: "true".  I would have expected traffic to flow between pods after that, but it was still blocked.  I'll paste the entire flow below.

This is the policy I applied after I annotated the namespace to default deny all traffic.

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
spec:
  podSelector:
    matchLabels:
      run: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"


Here is the flow where I show the network policy, the service, and the pods behind the service.  I then show a busybox instance with the correct labels trying to connect through the service to the target pods.  It is blocked.

`mmerrillmbp:test mmerrill$ kubectl get pods -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP           NODE
nginx-4217019353-jmh6m   1/1       Running   0          17h       10.41.96.9   ip-10-203-21-177.ec2.internal
nginx-4217019353-kbck1   1/1       Running   0          17h       10.36.96.6   ip-10-203-20-215.ec2.internal
mmerrillmbp:test mmerrill$ kubectl get networkpolicy
NAME           POD-SELECTOR   AGE
access-nginx   run=nginx      17h
mmerrillmbp:test mmerrill$ kubectl get networkpolicy access-nginx -o json
{
    "apiVersion": "extensions/v1beta1",
    "kind": "NetworkPolicy",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"NetworkPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"access-nginx\",\"namespace\":\"mike\"},\"spec\":{\"ingress\":[{\"from\":[{\"podSelector\":{\"matchLabels\":{\"access\":\"true\"}}}]}],\"podSelector\":{\"matchLabels\":{\"run\":\"nginx\"}}}}\n"
        },
        "creationTimestamp": "2017-10-05T20:26:30Z",
        "generation": 1,
        "name": "access-nginx",
        "namespace": "mike",
        "resourceVersion": "42787075",
        "selfLink": "/apis/extensions/v1beta1/namespaces/mike/networkpolicies/access-nginx",
        "uid": "7872ddec-aa0b-11e7-ba3b-12a04e6fcc4a"
    },
    "spec": {
        "ingress": [
            {
                "from": [
                    {
                        "podSelector": {
                            "matchLabels": {
                                "access": "true"
                            }
                        }
                    }
                ]
            }
        ],
        "podSelector": {
            "matchLabels": {
                "run": "nginx"
            }
        }
    }
}
mmerrillmbp:test mmerrill$ kubectl get service -o wide
NAME      CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE       SELECTOR
nginx     100.70.25.58   <none>        80/TCP    17h       run=nginx
mmerrillmbp:test mmerrill$ kubectl get service nginx -o json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "creationTimestamp": "2017-10-05T20:24:29Z",
        "labels": {
            "run": "nginx"
        },
        "name": "nginx",
        "namespace": "mike",
        "resourceVersion": "42786506",
        "selfLink": "/api/v1/namespaces/mike/services/nginx",
        "uid": "309d5956-aa0b-11e7-ad1e-062cd9eb02fa"
    },
    "spec": {
        "clusterIP": "100.70.25.58",
        "ports": [
            {
                "port": 80,
                "protocol": "TCP",
                "targetPort": 80
            }
        ],
        "selector": {
            "run": "nginx"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}
mmerrillmbp:test mmerrill$ kubectl run busybox --rm -ti --labels="access=true" --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # wget --spider --timeout=1 nginx
Connecting to nginx (100.70.25.58:80)
wget: download timed out
/ # 
`

**Comment by mmerrill3** [comment]
This is not a weave issue.  The problem was that the cluster cidr range for the kube proxy was set to a separate cidr clock than what weave-net was configured for.  This was causing kube-proxy to masqerade requests through the cluster service to the nginx pod.  We have fixed our cluster to make the cluster cidr range match the weave cidr range, and I cannot reproduce the issue now.  Thank you @bboreham for your time on this.  I was hoping that there was something I could contribute here, but it turns out to just be a misconfigured cluster.

**Comment by bboreham** [comment]
Thanks for the update @mmerrill3.

I filed http://github.com/kubernetes/kubernetes/issues/46508 some time ago, which would let us report the misconfiguration
(I guess we could dig around in the `/proc` info, but an API would be nicer)
