### ISSUE TITLE
`weaveworks/weave-kube:2.0.5` image missing in DockerHub.

### ISSUE THREAD

**Issue by mindw** [weaveworks/weave#3140]
## What you expected to happen?
`docker pull weaveworks/weave-kube:2.0.5` completes successfully.

## What happened?
```
$ docker pull weaveworks/weave-kube:2.0.5
Error response from daemon: manifest for weaveworks/weave-kube:2.0.5 not found
```

## How to reproduce it?
```
docker pull weaveworks/weave-kube:2.0.5
```

**Comment by bboreham** [comment]
Version 2.0.5 in the process of being released. 

Would be interested to know what led to you attempting to pull the image.

**Comment by mindw** [comment]
Got notified of a new tag via https://about.sibbell.com .

**Comment by mindw** [comment]
It's there now, closing,

**Comment by bboreham** [comment]
I don't know anything about sibbell, but we create a tag first, then build all the software and test it, then make the release visible on GitHub.  So it would be better if they reacted to the latter event.

**Comment by mindw** [comment]
Thanks for the info. Understood - wont bother you again :)

Sibell is just a s small web service which scans starred repo for new tags/releases and sends emails when a new one is detected. It detected the tag (and eventually the release).
