### ISSUE TITLE
CNI DEL logs nil errors

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#3143]
seen in user's kubelet log:

    Oct 17 13:02:24 ip-172-20-73-204 kubelet[1657]: weave-cni: unable to release IP address: %!s(<nil>)

**Comment by bboreham** [comment]
Fixed in 62dbe03193aca4b025438cdacf05e52f05368d6b

**Comment by bamb00** [comment]
Hi,

Ran into the same issue.  I'm running 2.0.1 with Kubernetes v1.7.4.  Is there a workaround?

Nov 29 20:21:31 ... kubelet[27470]: weave-cni: unable to release IP address: Delete http://127.0.0.1:6784/ip/c757a1260a2c35074af8a43536e88b57aa4dc9f285d6600f0e19dc44260e4926: dial tcp 127.0.0.1:6784: getsockopt: connection refused

Thanks in Advance.

**Comment by rade** [comment]
>  Is there a workaround?

Upgrade to a version that includes the fix. See the milestone assigned to this issue - 2.0.6 or higher.

**Comment by bboreham** [comment]
@bamb00 simplest thing to do would be to ignore it.

@rade 2.0.6 was skipped so 2.1.0 is the first that has it

**Comment by bamb00** [comment]
@bboreham I assume the error was the cause of the weave-net pod CrashLoopBackOff.

kubelet log:
Nov 29 20:21:31 ... kubelet[27470]: weave-cni: unable to release IP address: Delete http://127.0.0.1:6784/ip/36d24d17934dd53b9050e34d681cca7911df1d2763ce337ffb16d28610d8b153: dial tcp 127.0.0.1:6784: getsockopt: connection refused
Nov 29 20:21:31 ... kubelet[27470]: weave-cni: unable to release IP address: Delete http://127.0.0.1:6784/ip/57b2cf26a5cb5a526eff1c1e0f34b120064e904d79c85a50ca92138838148464: dial tcp 127.0.0.1:6784: getsockopt: connection refused
Nov 29 20:21:31 ... kubelet[27470]: I1129 20:21:31.257060   27470 kuberuntime_manager.go:457] Container {Name:weave Image:weaveworks/weave-kube:2.0.1 Command:[/home/weave/launch.sh] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:HOSTNAME Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:spec.nodeName,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:10 scale:-3} d:{Dec:<nil>} s:10m Format:DecimalSI}]} VolumeMounts:[{Name:weavedb ReadOnly:false MountPath:/weavedb SubPath:} {Name:cni-bin ReadOnly:false MountPath:/host/opt SubPath:} {Name:cni-bin2 ReadOnly:false MountPath:/host/home SubPath:} {Name:cni-conf ReadOnly:false MountPath:/host/etc SubPath:} {Name:dbus ReadOnly:false MountPath:/host/var/lib/dbus SubPath:} {Name:lib-modules ReadOnly:false MountPath:/lib/modules SubPath:} {Name:weave-net-token-rc0l2 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/status,Port:6784,Host:127.0.0.1,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:30,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Nov 29 20:21:31 ... kubelet[27470]: I1129 20:21:31.257450   27470 kuberuntime_manager.go:741] checking backoff for container "weave" in pod "weave-net-sb737_kube-system(c60f68ad-d53d-11e7-8c9f-005056917dec)"
Nov 29 20:21:31 ... kubelet[27470]: I1129 20:21:31.257640   27470 kuberuntime_manager.go:751] Back-off 5m0s restarting failed container=weave pod=weave-net-sb737_kube-system(c60f68ad-d53d-11e7-8c9f-005056917dec)
Nov 29 20:21:31 ... kubelet[27470]: E1129 20:21:31.257712   27470 pod_workers.go:182] Error syncing pod c60f68ad-d53d-11e7-8c9f-005056917dec ("weave-net-sb737_kube-system(c60f68ad-d53d-11e7-8c9f-005056917dec)"), skipping: failed to "StartContainer" for "weave" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=weave pod=weave-net-sb737_kube-system(c60f68ad-d53d-11e7-8c9f-005056917dec)"
Nov 29 20:21:31 ... kubelet[27470]: weave-cni: unable to release IP address: Delete http://127.0.0.1:6784/ip/229cafe28657f82a76196ec1409d9867d739508fb25b1f1fa5da4dd6f2cdd35a: dial tcp 127.0.0.1:6784: getsockopt: connection refused

NAME                                                   READY     STATUS               RESTARTS   AGE
etcd-tricorderappliance-master-01                      1/1       Running              5          56d
kube-apiserver-tricorderappliance-master-01            1/1       Running              7          56d
kube-controller-manager-tricorderappliance-master-01   1/1       Running              9          56d
kube-dns-2425271678-2rzwq                              0/3       ContainerCannotRun   0          2h
kube-proxy-ccdb1                                       0/1       ContainerCreating    1          56d
kube-scheduler-tricorderappliance-master-01            1/1       Running              9          56d
kubernetes-dashboard-2220841768-mzw6p                  0/1       ContainerCreating    0          9s
weave-net-sb737                                        1/2       CrashLoopBackOff     20         55m

**Comment by bboreham** [comment]
@bamb00 no, the CNI plugin runs outside of all pods.  Please supply the log of the pod that is crashing.

**Comment by bboreham** [comment]
@bamb00 and please open a new issue rather than commenting on an old closed one.

**Comment by bamb00** [comment]
Got it.  Open a new issue #3191
