### ISSUE TITLE
Unable to  install specific version of the V2 network plugin

### ISSUE THREAD

**Issue by currychomper** [weaveworks/weave#3148]
Attempting to install specific version of V2 network plugin.

## What you expected to happen?
Install a specific version rather that the latest_release

## What happened?
Error response from daemon: manifest for store/weaveworks/net-plugin:2.0.4 not found

## How to reproduce it?
$ docker plugin install store/weaveworks/net-plugin:2.0.4

note I have also tried 2.0.5 and other older versions.

$ docker plugin install store/weaveworks/net-plugin:latest_release does find and download the plugin.

docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

uname -a
Linux swarm-master-1 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rade** [comment]
2.0.1 is available in the docker store, and 2.0.5 in the docker hub. See #3150.
