### ISSUE TITLE
v2 docker plugin in docker store is ancient

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#3150]
Following the [weave net v2 docker plugin instructions](https://www.weave.works/docs/net/latest/install/plugin/plugin-v2/), installs a version that is from May 2017 - running `weave version` on it reports [`git-1da1943df9d8`](https://github.com/weaveworks/weave/commit/1da194).

**Comment by currychomper** [comment]
What's the eta on this fix? Is there another way of installing the 2.0.5 V2 plugin in the mean time - am trying to work out if using it is a good fit for us but can't get hold of it?

**Comment by rade** [comment]
> What's the eta on this fix?

It might take a couple of weeks.

> Is there another way of installing the 2.0.5 V2 plugin in the mean time.

Not that I can think of.

**Comment by rade** [comment]
Actually, you can grab the v2.0.5 plugin with
```
docker plugin install weaveworks/net-plugin:latest_release
```

**Comment by rade** [comment]
There is also a v2.0.1 plugin in the main store, so
```
docker plugin install store/weaveworks/net-plugin:2.0.1
```
works. This does support the `IPALLOC_RANGE` setting (in reference to #3147).

**Comment by bboreham** [comment]
I just ran `docker plugin install weaveworks/net-plugin:latest_release` and I got version 2.1.0

So not as bad as it was, but still somehow one version behind the latest.

**Comment by rade** [comment]
so what went wrong during the v2.1.1 release?
