### ISSUE TITLE
cni config uninitialized on worker node added some time after Weave

### ISSUE THREAD

**Issue by definitelyuncertain** [weaveworks/weave#3167]
Note: I posted this issue [here](https://github.com/kubernetes/kubernetes/issues/55073), and I've moved the issue on their recommendation. Since I'm not sure where the issue lies , I'm posting here as well as in the Kubeadm repo.

## What happened?
I followed this [guide](https://github.com/Langhalsdino/Kubernetes-GPU-Guide) for setting up a Kubernetes cluster with `kubeadm` for both master and worker nodes.

Just like in https://github.com/kubernetes/kubernetes/issues/48798 , the CNI network plugin remains uninitialized, but on a worker node rather than the master. I get the following from `systemctl status kubelet` : 

```
4282 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
4282 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
```
I get the exact same messages from `journalctl -u kubelet` as well. `kubectl get nodes` shows the node status is "Not Ready".

Thing is, I've already connected several other nodes to the cluster and they are all able to run pods quite fine, and I added them using the exact same steps.

Additionally, it seems this happens only to nodes that I add a couple of hours after adding the Weave add-on. The very same nodes are ready if I first join all of them to the master and then add Weave, so the problem isn't with the number of nodes or any particular node.

When I do `kubeadm reset` and try again, the same thing happens. I've also tried restarting the master node.

## What you expected to happen?
The node should have been added and ready for scheduling.

## How to reproduce it?
The usual procedure for adding a worker node. I followed this [guide](https://github.com/Langhalsdino/Kubernetes-GPU-Guide) except that I used `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"` instead of `kubectl apply -f https://git.io/weave-kube-1.6` for Weave. As mentioned, this happens only a couple of hours after I apply Weave.

## Anything else we need to know?

- Kubernetes version (use `kubectl version`): `1.8.2` on all nodes, with `kubernetes-cni 0.5.1` 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 on all nodes
- Kernel (e.g. `uname -a`): 4.4.0-97-generic
- Install tools: `kubeadm`
- Others: I am using the weave works add-on, installed by running `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"`

I checked one of the working nodes and found a file `/etc/cni/net.d/10-weave.conf` and copied it over to the problematic node in the same place. Now, the node becomes ready, but when I schedule a pod on it, the pod remains pending indefinitely (the pod runs fine on other nodes).

## Versions:

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

## Logs:

Note: There is no pod running Weave on the worker node!

```
$ kubectl get events
LAST SEEN   FIRST SEEN   COUNT     NAME                       KIND      SUBOBJECT   TYPE      REASON                    SOURCE              MESSAGE
3m          5d           1720      master.14f4725a44b0b74a    Node                  Warning   ImageGCFailed             kubelet, master     (combined from similar events): wanted to free 89849875660 bytes, but freed 107731744 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container c2a323745ce3
```
The master node has 80G of space left, so I don't think that would be a problem.

```
$ journalctl -u kubelet --no-pager
Nov 12 13:28:55 master kubelet[12846]: E1112 13:28:55.137751   12846 kuberuntime_image.go:126] Remove image "sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2" failed: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container b4b67c87983b
Nov 12 13:28:55 master kubelet[12846]: E1112 13:28:55.137772   12846 kubelet.go:1230] Image garbage collection failed multiple times in a row: wanted to free 89800187084 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container b4b67c87983b
Nov 12 13:29:19 master kubelet[12846]: E1112 13:29:19.755900   12846 kubelet.go:1612] Failed creating a mirror pod for "kube-apiserver-master_kube-system(afdc27eca77cd60b050eeedbfd69ba77)": pods "kube-apiserver-master" is forbidden: no providers available to validate pod request
```
I added a Pod Security Policy to permit everything, but I still keep getting those messages

```
$ journalctl -u docker.service --no-pager
Nov 12 13:18:55 master docker[1432]: time="2017-11-12T13:18:55.084379129+05:30" level=error msg="Handler for DELETE /v1.23/images/sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2 returned error: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container b4b67c87983b"
Nov 12 13:23:55 master docker[1432]: time="2017-11-12T13:23:55.102424670+05:30" level=error msg="Handler for DELETE /v1.23/images/sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2 returned error: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container c2a323745ce3"
Nov 12 13:28:55 master docker[1432]: time="2017-11-12T13:28:55.137400373+05:30" level=error msg="Handler for DELETE /v1.23/images/sha256:99e59f495ffaa222bfeb67580213e8c28c1e885f1d245ab2bbe3b1b1ec3bd0b2 returned error: conflict: unable to delete 99e59f495ffa (cannot be forced) - image is being used by running container b4b67c87983b"
```

**Comment by discostur** [comment]
Seeing exactly the same problem on Fedora Atomic Host 27

**Comment by bboreham** [comment]
> Note: There is no pod running Weave on the worker node!

This explains "No networks found in /etc/cni/net.d" - it's the weave-net pod which installs the software.

So you need to find out why it's not running - either it ran and errored, in which case there will be a log, it was scheduled and never ran, in which case kubelet will say why, or it was never scheduled, which can be a bit harder to figure out.

**Comment by messmerxx** [comment]
https://github.com/kubernetes/kubernetes/issues/56696

i am facing similar problem. weave-net pod can not be started on windows server 2016.

**Comment by bboreham** [comment]
Thanks for the update @definitelyuncertain.
