### ISSUE TITLE
Support ipBlock for ingress rules of NetworkPolicy in weave-npc

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#3168]
k8s 1.8 extended `NetworkPolicyPeer` object by introducing `ipBlock`: https://kubernetes.io/docs/api-reference/v1.8/#networkpolicypeer-v1-networking

As it is stated in the linked doc, _"IPBlock describes a particular CIDR (Ex. "192.168.1.1/24") that is allowed to the pods matched by a NetworkPolicySpec's podSelector."_

**Comment by kitt1987** [comment]
Any progress on this feature?

**Comment by brb** [comment]
Sorry, no progress yet. PRs are very welcome!

**Comment by kitt1987** [comment]
Could you please help me review this PR?
