### ISSUE TITLE
Forbidden by K8s rbac creating clusterrole and role

### ISSUE THREAD

**Issue by sjtindell** [weaveworks/weave#3180]
## What you expected to happen?
All k8s objects would be created.

## What happened?

serviceaccount "weave-net" configured
clusterrolebinding "weave-net" configured
rolebinding "weave-net-kube-peer" configured
daemonset "weave-net" configured
Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-net" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["networkpolicies"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["networkpolicies"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["networkpolicies"], APIGroups:["extensions"], Verbs:["watch"]}] user=&{192.168.65.15  [NIO system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
Error from server (Forbidden): roles.rbac.authorization.k8s.io "weave-net-kube-peer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["configmaps"], ResourceNames:["weave-net"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], ResourceNames:["weave-net"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["create"]}] user=&{192.168.65.15  [NIO system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
## How to reproduce it?

Setup a kubernetes cluster manually with a self signed CA.
Using the latest release 1.8.3 of all binaries.

**Comment by Bregor** [comment]
> Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-net" is forbidden: attempt to grant extra privileges
Are you sure it's weave's problem?.. 🤔

**Comment by sjtindell** [comment]
This was an issue with RBAC authorization setup.
