### ISSUE TITLE
weave-net pod can not be created on windows server 2016 node

### ISSUE THREAD

**Issue by messmerxx** [weaveworks/weave#3193]
** Is this a BUG REPORT? **

while creating a weave-net pod on windows server 2016 node in a kubernetes cluster, i got the following error message.

I1202 10:58:09.329692    7076 eviction_manager.go:325] eviction manager: no resources are starved
I1202 10:58:09.514693    7076 volume_manager.go:366] All volumes are attached and mounted for pod "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)"
I1202 10:58:09.514693    7076 kuberuntime_manager.go:403] No ready sandbox for pod "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)" can be found. Need to start a new one
I1202 10:58:09.515691    7076 kuberuntime_manager.go:571] computePodActions got {KillPod:true CreateSandbox:true SandboxID:ac1f28b8dc1bb8f287d420abc40496753838cb9373d8142b8046ca31b08b3800 Attempt:32 NextInitContainerToStart:nil ContainersToStart:[0 1] ContainersToKill:ma
p[]} for pod "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)"
I1202 10:58:09.515691    7076 server.go:231] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"weave-net-drbkl", UID:"9700a989-d74f-11e7-a4cd-0289db2a7c18", APIVersion:"v1", ResourceVersion:"559651", FieldPath:""}): type: 'Normal' reason: 'SandboxChange
d' Pod sandbox changed, it will be killed and re-created.
I1202 10:58:09.584692    7076 docker_service.go:437] Setting cgroup parent to: ""
I1202 10:58:09.585693    7076 docker_service.go:437] Setting cgroup parent to: ""
E1202 10:58:09.775691    7076 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-drbkl": Error response from daemon: No such network: host
E1202 10:58:09.775691    7076 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-drbkl": Error response from
 daemon: No such network: host
E1202 10:58:09.776690    7076 kuberuntime_manager.go:647] createPodSandbox for pod "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "weave-net-drbkl": Error response fro
m daemon: No such network: host
E1202 10:58:09.777690    7076 pod_workers.go:186] Error syncing pod 9700a989-d74f-11e7-a4cd-0289db2a7c18 ("weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)"), skipping: failed to "CreatePodSandbox" for "weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd
-0289db2a7c18)" with CreatePodSandboxError: "CreatePodSandbox for pod \"weave-net-drbkl_kube-system(9700a989-d74f-11e7-a4cd-0289db2a7c18)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"weave-net-drbkl\": Error response from daemon:
 No such network: host"

if i create a weave network with docker:
docker create network --weave weavenet
the error message is "weave net plugin can not be located"

## Versions:

```
$ weave version
$ docker version 17.09
$ uname -a
$ kubectl version 1.9.3.alpha
```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
```

## Network:

```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by bboreham** [comment]
Weave Net is currently Linux-only. 

Looks like the main error you got was that Kubernetes on Windows does not understand the "host network" concept. Given that, if didn't even run the Weave Net software. 

I guess you could ask for a better error from Kubernetes.
