### ISSUE TITLE
Make "ipalloc-range" configurable for container weaveworks/weave-kube

### ISSUE THREAD

**Issue by xiangpengzhao** [weaveworks/weave#3211]
## What you expected to happen?
`weave-net` pod running

## What happened?

1. kubeadm init
2. deploy weave
```
kubectl apply -n kube-system -f \
    "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 |tr -d '\n')"
```

3. `weave-net` pod CrashLoopBackOff, the logs show:
`Network 10.32.0.0/12 overlaps with existing route 10.0.0.0/8 on host`

Doc https://github.com/weaveworks/weave/blob/master/site/tasks/ipam/configuring-weave.md says we can pass `ipalloc-range` to specify the range. But users can't configure this when weave is deployed as a pod.

So it'd be good to make `ipalloc-range` configurable in the manifest.

## How to reproduce it?

As described above.

/cc @bboreham 

 Thanks! Maybe I miss something.

## Versions:

```
$ weave version
$ docker version
$ uname -a
$ kubectl version: v1.9.0
```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
```

## Network:

```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by bboreham** [comment]
Hi @xiangpengzhao , and thanks for your interest!

You should be able to change it as described at https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#configuration-options

Let us know if you need more help.

**Comment by xiangpengzhao** [comment]
@bboreham thank you so much for the doc link. Everything works well now. I should have tried to find the doc :)

**Comment by manoel1845** [comment]
thank you so much, help me a lot
