### ISSUE TITLE
Some nodes having significant delays when connecting to other nodes

### ISSUE THREAD

**Issue by inetfuture** [weaveworks/weave#3220]
## What you expected to happen?

No significant delays when connecting to other nodes.

## What happened?

We have a bare-metal k8s cluster with 14 nodes, half of the nodes run business pods, the other half of them are for databases, and they only run daemonsets for monitoring purpose.

This cluster has been running fine for several months, but recently, we encountered some weird network issues, like:

- PHP code reporting `Failed to open redis DB connection (xxx:6379, database=1): 110 - Connection timed out`, 
- consul client reporting `failed to query xxx: Unexpected response code: 500 (rpc error: failed to get conn: dial tcp <nil>->192.168.161.102:8300: i/o timeout) [<nil>]`

The weird part is, currently only two nodes have this kind of issues, and the delays causing the timeout errors are not constant, sometimes they are not noticeable, sometimes they are significant(seconds).

Here are the tcpdump captures from the src and dest host, I got these captures by:

- start up a tcp listener on a normal node with `nc -lk 8888`, the node's ip is `192.168.161.55`.
- `kubectl exec` into any pod on one of the abnormal node, run `nc -vz 192.168.161.55 8888` , the node's ip is `192.168.161.104`, the pod's ip is `10.42.0.9`.
- run `tcpdump -i any port 8888` on both nodes(not inside pods).

To simplify things, I didn't use connecting to redis or consul as example, but the result is the same, in the captures you can see that sometimes src node has to retransmit many times before dest node can receive it.

capture on src node:

![screen shot 2018-01-15 at 23 23 35](https://user-images.githubusercontent.com/1363189/34949567-6b575a90-fa4b-11e7-8199-4e1d0c3ba7f9.png)

http://op1zz35qd.bkt.clouddn.com/src-host.pcapng

capture on dest node:

![screen shot 2018-01-15 at 23 23 20](https://user-images.githubusercontent.com/1363189/34949572-6da05130-fa4b-11e7-950b-b4c574ce5177.png)

http://op1zz35qd.bkt.clouddn.com/dest-host.pcapng

## How to reproduce it?

I really don't know.

## Anything else we need to know?

This problem came out no where, we haven't do any changes lately.

We have tried to delete and recreate weave-net daemonset, and all pods, no luck.

We have also tried to reboot the system, no luck.

## Versions:

```
$ weave status
Version: 1.9.4 (failed to check latest version - see logs; next check at 2018/01/15 16:51:55)

        Service: router
       Protocol: weave 1..2
           Name: 6a:f4:5c:54:33:ad(192-168-161-100)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 14
    Connections: 14 (13 established, 1 failed)
          Peers: 14 (with 182 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 10.32.0.0/12
  DefaultSubnet: 10.32.0.0/12
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64
$ uname -a
Linux 192-168-161-100 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-101 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-102 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-103 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-104 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-105 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-106 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-107 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-108-2 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-108-2 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-108-2 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-112 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-54 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-55 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-56 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux 192-168-161-57 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:07Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

## Logs:

```
$ kubectl logs -n kube-system <weave-net-pod> weave
```
seeing a lot of these on abnormal nodes(nothing else special):

```
WARN: 2018/01/15 14:26:31.232676 TCP connection from 10.42.0.11:10108 to 192.168.161.55:6379 blocked by Weave NPC.
WARN: 2018/01/15 14:29:59.721080 TCP connection from 10.42.0.9:7386 to 192.168.161.102:8300 blocked by Weave NPC.
```

I suspected this is the reason, but we haven't use any Network Policy, what else might cause NPC blocking connections?

**Comment by inetfuture** [comment]
After I run `weave reset` on only one of the abnormal nodes, the delays disappeared, on both abnormal nodes!

`blocked by Weave NPC` logs also disappeared, almost, still seeing dozens of them pop up every few quarters, but a lot less, here is the comparison:

![screen shot 2018-01-16 at 14 14 16](https://user-images.githubusercontent.com/1363189/34974393-a7ff15ba-fac7-11e7-836b-37a9857119e2.png)

So, I guess something wrong with weave bridge or db？I see these will be removed in the reset process:

```
reset)
        [ $# -eq 0 ] || [ $# -eq 1 -a "$1" = "--force" ] || usage
        res=0
        [ "$1" = "--force" ] || check_running $CONTAINER_NAME 2>/dev/null || res=$?
        case $res in
            0)
                call_weave DELETE /peer >/dev/null 2>&1 || true
                fractional_sleep 0.5 # Allow some time for broadcast updates to go out
                ;;
            1)
                # No such container; assume user already did reset
                ;;
            2)
                echo "ERROR: weave is not running; unable to remove from cluster." >&2
                echo "Re-launch weave before reset or use --force to override." >&2
                exit 1
                ;;
        esac
        stop
        for NAME in $CONTAINER_NAME $OLD_PROXY_CONTAINER_NAME $OLD_PLUGIN_CONTAINER_NAME ; do
            docker rm -f $NAME >/dev/null 2>&1 || true
        done
        protect_against_docker_hang
        VOLUME_CONTAINERS=$(docker ps -qa --filter label=weavevolumes)
        [ -n "$VOLUME_CONTAINERS" ] && docker rm -v $VOLUME_CONTAINERS  >/dev/null 2>&1 || true
        rm -f $HOST_ROOT/var/lib/weave/weave-netdata.db >/dev/null 2>&1 || true
        destroy_bridge
        for LOCAL_IFNAME in $(ip link show | grep v${CONTAINER_IFNAME}pl | cut -d ' ' -f 2 | tr -d ':') ; do
            ip link del ${LOCAL_IFNAME%@*} >/dev/null 2>&1 || true
        done
        ;;
```

Seems I find the way to fix it, but I still have no clue how did it get broken and how to prevent it from happening again, please help.

**Comment by inetfuture** [comment]
I can see that the `blocked by Weave NPC` log is printed when `gatherMetrics()` seeing an initial SYN packet being captured by ulogd, but I don't get how the uglod is filtering packets.

https://github.com/weaveworks/weave/blob/1.9/npc/metrics/metrics.go#L48

**Comment by bboreham** [comment]
I'll try to give a brief overview to help out:

At the highest level, the filtering is done in pursuit of Kubernetes NetworkPolicy.
When the bridge is created, the code injects iptables rules into the FORWARD chain which will redirect to another WEAVE-NPC, then drop the packet and generate a message for `ulogd` if it is not accepted.

If you have no network policies, there should be rules in the WEAVE-NPC chain which accept your packets.

**Comment by inetfuture** [comment]
@bboreham Thanks for the help, your explanation does make things a lot easier to understand. 

As I described above, I have run `weave reset`, so the bad rules most likely have been wiped out, I really should have protect the scene..., here are the latest rules anyway:

![screen shot 2018-01-17 at 00 18 32](https://user-images.githubusercontent.com/1363189/34999180-0b481dca-fb1c-11e7-82bf-d72c98cf461a.png)

Seems fine, right?

And, just curious, why `weave reset` fixed the problem while recreating pod didn't? Any thoughts?

Thanks again.

**Comment by inetfuture** [comment]
Maybe some ip-ipset belonging relationships were wrong, and they got cleared after `weave reset`?

**Comment by inetfuture** [comment]
One important fact to consider is that, the tcp connection handshaking delays are not constant, sometimes they're low, sometimes they're high, it's like the SYN packets were being blocked randomly? 

And once the connection was established, no delays anymore(if I remember correctly, I'm having fuzzy memory about this part...)

**Comment by brb** [comment]
This is very weird: `TCP connection from 10.42.0.11:10108 to 192.168.161.55:6379 blocked by Weave NPC.`. Weave NPC should filter only pod-to-pod communication, and `192.168.161.55` is the node IP.

OTOH, you're running quite an old version of Weave, and there were many changes to Weave NPC since then. Technically, https://github.com/weaveworks/weave/pull/2979 could have fixed your problem, but you said that connections get eventually established creates some doubts.

Do you plan to update your cluster?

**Comment by inetfuture** [comment]
@brb We will, just not in a short time, like 2 or 3 months later. 

So I'm hopping we can understand the root cause and do some precautions, we currently run 7 independent clusters, this problem makes me worry(although we only run into this once in serval months).

Anyway, if even you guys have on clue on this behavior, maybe we'll just move on.

**Comment by rade** [comment]
It seems like we've reached a dead end in the investigation here. -> closing
