### ISSUE TITLE
Weavenet vxlan packet with Wireshark

### ISSUE THREAD

**Issue by Sk3pper** [weaveworks/weave#3225]
Good morning, I’m using containers technology, since for my project I need a multicast feature and docker overlay does’t give me this possibility I installed weave network following these instruction (https://github.com/weaveworks/weave/blob/master/site/install/plugin/plugin-v2.md). 

In my lab-test network I have three nodes:
	- swarm-manager= boot2Docker image (192.168.99.104)
	- swarm-worker-0= boot2Docker image (192.168.99.105)
	- sniff-VirtualBox = ubuntu-16.04.3-desktop-amd64 (192.168.99.106)
And in each nodes runs some containers.

These three machines are connected thought Host-only Networking (vboxnet0).

After the weave net plugin installation everything works, I can perform unicast and multicast operations.
This is an example that multicast works between containers that run in different nodes:

![multicast_works](https://user-images.githubusercontent.com/13051136/35436682-af76ad88-028f-11e8-8b4a-8094fff8fb7d.png)

My problem arises when I try to understand better how the weave network works. I installed sniff-VirtualBox in order to sniff packets. I enables promiscuous mode and if I ping swarm-worker-0 from swarm-worker-1 through Wireshark in sniff-VirtualBox I see the ICMP packets.
![sniff_vboxnet_managertoworker](https://user-images.githubusercontent.com/13051136/35436694-bc50cb60-028f-11e8-8ab3-3871f6a991f7.png)

I tried to sniff packets between containers, so I pinged container from swarm-manager to container in swarm-worker-0. These containers are linked with overlay weavenet. This is the screenshot about sniff (I enable Vxlan encode in wirehsark in sniff-VirtualBox):
![siniff_containers_weavenet](https://user-images.githubusercontent.com/13051136/35436708-d1649482-028f-11e8-90f0-14395311184e.png)

How you can see the data fild is not in clear and I cannot see the payload.  Since I did not enable the encptyption mode, in fact:
![weavenet_setting](https://user-images.githubusercontent.com/13051136/35436729-dfc93c4e-028f-11e8-90dd-9b339d325fc6.png)

I don’t understand which is the problem. 

In order to have another proof I removed the weave network and I setup a default overlay network between containers. So I pinged again container from swarm-manager to container in swarm-worker-0 and I saw the data field in clear in Wireshark in sniff-VirtualBox . Here you are the proof:
![siniff_containers_default_overlay](https://user-images.githubusercontent.com/13051136/35436738-e5f33930-028f-11e8-9916-432e77a17200.png)

The question is how can I see the contentent of the data field with weave net? Which is the problem?

**Comment by errordeveloper** [comment]
Following up the discussion on the [mailing list](https://groups.google.com/a/weave.works/d/msg/weave-users/dmKu0BMHBWw/RQyHLq_KBAAJ), I think we can close this.
