### ISSUE TITLE
Bad Performance on ARM

### ISSUE THREAD

**Issue by dhet** [weaveworks/weave#3244]
I'm currently messing around with weave net and Raspberry Pis (v2). I noticed that as soon as I install weave and set up the Docker API proxy, Docker starts responding noticably more sluggishly. So I ran a few throughput benchmarks using _iperf3_ to see if the slow response times also translate to networking performance. I ran tests in the following scenarios: (a) plain host-to-host communication, (b) weave overlay and (c) weave encrypted overlay. The hosts are connected over the Internet using sleeve mode. In the tests weave version 2.2.0 and Docker version 17.12.0-ce was used. 

The results look rather dismal: On x86, weave performs pretty well with reasonable overhead of ~5% to ~7%. On ARM the overhead is at ~50%.

What could be the reason for this?

![throughput](https://user-images.githubusercontent.com/2668621/36478878-cd723d76-1706-11e8-8336-4f74052f660a.png)

**Comment by brb** [comment]
Thanks for the report.

First of all, I would note that probably you are performing benchmarks on two very different machines: Raspberry Pi (ARMv7) vs ??? (X86_64). I guess the latter is more powerful than the former. It matters when using the sleeve mode which can be CPU intensive, and thus on a slower machine it can take a significant part of CPU slices from the system making it sluggish. You could use e.g. `mpstat` to trace CPU utilization. 

Next, you mentioned that hosts are connected over the internet which is not a very stable medium for performing benchmarks. I see that in the X86_64 case, sleeve was performing quite well compared to the native, so I expect that the network is not fully saturated. I bet that with a faster network you would see comparable performance patterns.

Having said that, I would suggest to connect hosts directly (or via switch) and to measure CPU utilization to see whether the CPU is a bottleneck in the ARMv7 case. Also, don't forget to run benchmarks multiple times.

**Comment by dhet** [comment]
Ah, I see. I wasn't aware that the overlay puts so much load on the CPU. I measured CPU utilization as you suggested and and as it turns out the Raspberry Pi hits a CPU-bound wall at around 21 Mbit/s when using encrypted sleeve mode, and at around 50 Mbit/s when using encrypted fast dp.

Thanks!

**Comment by brb** [comment]
Thanks for the follow-up.
