### ISSUE TITLE
Fail to build weave on OSX and using vagrant

### ISSUE THREAD

**Issue by NathanHaim** [weaveworks/weave#3245]
Weave can't be built on OSX or with vagrant. There is some cross-compilation dependences broken. One of your engineer said it could come from the Dockerfile.

You can reproduce it by building on OSX with the following step:
- git clone project
- git submodule update --init --recursive
- make

OR using vagrant:
- git clone project
- git submodule update --init -- recursive
- vagrant up
- vagrant ssh
- cd src/github.com/weaveworks/weave
- make

![img_4667](https://user-images.githubusercontent.com/16245614/36526106-278597da-17ad-11e8-8bbd-b324e1697a55.JPG)

It seems that you rarely use OSX and vagrant. But it could be nice to build with in a dev environment without cross-compilation dependencies.
I propose to manage that by allowing developer to build without cross-compilation.
I can do it.

**Comment by bboreham** [comment]
I use vagrant on OSX every day, created by `vagrant up` in this repo. 

Looks like some dependencies have changed since we last created a build container. 

I’m not sure what you are proposing - have two different build containers for with and without cross-CPU builds?

**Comment by NathanHaim** [comment]
Sorry, I was not clear. I was thinking about giving the possibility to build without cross CPU builds by creating a second Dockerfile. But I should search to resolve these dependencies.

You don't have the error because a ``docker build`` is not occurring on your machine since you already have the image ready?
If the dependencies have changed, I have no idea how to properly get them. Do you have some tips?

**Comment by bboreham** [comment]
There are already four or five Dockerfiles in this repo. The one failing in your screenshot is the “build container” which collects lots of dependencies and tools so you don’t need them on your host, then we run builds inside it and generate the output containers such as `weaveworks/weave`. 

It’s common in the Linux world to find that upstream dependencies have changed, and to spend several hours a month dealing with this. Generally by googling some of the error messages you can find someone else who tripped over the same problem and blogged about how to work round it. 


Let me stress I don’t know for sure what you hit. I’m just reacting to what it says in your screenshot and trying to clarify some assumptions.

**Comment by bboreham** [comment]
Thanks to @luxas who pointed me at https://github.com/kubernetes/kubernetes/commit/f482b17e99e9f9ac49cf3578f40b157ce9821986#diff-cecd92099afe8834b084bfc9bbc0e980R56

**Comment by bboreham** [comment]
Fixed by #3253, thanks!
