### ISSUE TITLE
weave doesn't stay on fastdp, switches to sleeve and never comes back

### ISSUE THREAD

**Issue by notmaxx** [weaveworks/weave#3252]
## What you expected to happen?
Weave stays in `fastdp` mode

## What happened?
Weave switches to `sleeve` mode

## How to reproduce it?
After running some production load for 1-2 weeks most of weave's connection switched to `sleeve`

## Anything else we need to know?
- AWS, us-east-1, 3 subnets in 3 AZs, machines: r4.2xlarge & m4.2xlarge, around 20 nodes total
- some sysctl tuning done (i can provide sysctl current state)
- kops 1.8
- weave with encryption

## Versions:

```
$ weave version
weave 2.1.3

$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ uname -a
Linux ip-10-177-160-136 4.4.115-k8s #1 SMP Thu Feb 8 15:37:40 UTC 2018 x86_64 GNU/Linux
It is kops image: k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08 (ami-b0c6ccca)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:10:44Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

$ weave status (on one of the nodes)

        Version: 2.1.3 (version 2.2.0 available - please upgrade!)

        Service: router
       Protocol: weave 1..2
           Name: aa:fd:20:db:6f:e3(ip-10-177-160-136.ec2.internal)
     Encryption: enabled
  PeerDiscovery: enabled
        Targets: 19
    Connections: 21 (20 established, 1 failed)
          Peers: 21 (with 420 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 100.96.0.0/11
  DefaultSubnet: 100.96.0.0/11
```

## Logs:
https://gist.github.com/notmaxx/9a185337a8083ea945229610bd9a8eda
1. logs with switch from `fastdp` to `sleeve`
2. state of some weave instances + `netstat -i` showing VXLAN packets drops for Feb, 28 & March, 1

**Comment by brb** [comment]
@notmaxx Thanks for the detailed issue.

However, as you have already pointed out, it's a known issue. One possible workaround is to restart the `weaver` process which would reconnect to its peers, so that `fastdp` could be chosen again.

**Comment by notmaxx** [comment]
@brb is it ok I see VXLAN packets drop? any idea how to avoid them or make less disruptive?

**Comment by brb** [comment]
@notmaxx VXLAN runs over UDP which does not provide any guarantee on delivering, so delivery of VXLAN packets depend on your network reliability.

Out of curiosity, did you check whether the fallback happens between nodes running in different AZs?

**Comment by notmaxx** [comment]
@brb:

it was my first idea but surprisingly i found that switch to `sleeve` didn't really depend on cross-AZ traffic. Correlation is a bit different - nodes containing pods handling more traffic than others tend to have higher number of dropped packets and have more connections switched to `sleeve` in general. 
Interesting fact to me is VXLAN TX DROP packets is not zero. @bboreham had idea kernel may not have enough CPU to handle encryption, what do you think about it?

**Comment by brb** [comment]
>  kernel may not have enough CPU to handle encryption

It could be the reason.

A few ideas:

1. Do you have the kernel module `aesni_intel` enabled (fastp crypto uses AES-GCM)?
2. Have you checked with `ethtool -k $IFACE` whether your network driver and card have special capabilities for offloading ipsec (e.g. `esp-hw-offload`)?
2. Have you tried monitoring udp tx queue (e.g. via `/proc/net/udp`) to see whether it becomes full during a peak time? You can tune queue sizes with sysctl (grep for `udp` and `wmem_max` at https://github.com/torvalds/linux/blob/master/Documentation/networking/ip-sysctl.txt).

**Comment by brb** [comment]
One more thing - maybe you have an output of `dmesg` from any machine which switched to `sleeve` and which vxlan tx drop > 0?

**Comment by brb** [comment]
@Cryptophobia Could be. I guess it's easier to fix the original issue (https://github.com/weaveworks/weave/issues/1737) instead of debugging why it could have happened. I'm going to prioritize fixing it.

**Comment by Cryptophobia** [comment]
Thank you Martynas @brb
