### ISSUE TITLE
Weave net fails to run when a valid address range is specified

### ISSUE THREAD

**Issue by bricef** [weaveworks/weave#3254]
## What you expected to happen?
The `--ip-alloc` option should accept all valid IP address ranges.

## What happened?
When using the ip address `10.118.0.0/12`, which is a valid CIDR range, weave fails with 

```
FATA: 2018/03/07 18:55:06.533897 invalid subnet - bits after network prefix are not all zero: 10.118.0.0/12
```

**Comment by rade** [comment]
No, that's not a valid CIDR range. The error message is correct. "10.118.0.0" has the 15th MSB set, hence "bits after the network prefix (of 12 bits) are not all zero".

**Comment by bricef** [comment]
Huh, I always thought it was ok to specify ranges with host bits set. My bad.
