### ISSUE TITLE
Generated yaml from kubectl apply in release has minReadySeconds in the wrong place

### ISSUE THREAD

**Issue by davejrt** [weaveworks/weave#3257]
## What you expected to happen?

Weave 2.2.1 to install without error.

## What happened?

When running `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"` the following error is produced.

error validating data: ValidationError(DaemonSet.spec.template.spec): unknown field "minReadySeconds" in io.k8s.api.core.v1.PodSpec

## How to reproduce it?
Run `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"` against the latest release of weave

## Anything else we need to know?
I am testing this using [KREAM](https://github.com/puppetlabs/kream)
## Versions:

```
$ weave version
n/a 

$ crictl version
Version:  0.1.0
RuntimeName:  cri-containerd
RuntimeVersion:  1.0.0-beta.1
RuntimeApiVersion:  0.0.0

$ uname -a
Linux kube-master 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bboreham** [comment]
Oops, sorry about that. Have rolled back that change.

**Comment by davejrt** [comment]
Just tested successfully, thanks for the quick turnaround @bboreham

**Comment by bboreham** [comment]
We rolled back the change; let's keep this open until we push a new version that works.

**Comment by bboreham** [comment]
The fix is rolled out to cloud.weave.works now.
