### ISSUE TITLE
Failed to list *v1.NetworkPolicy error message in weave-npc (missing RBAC verb?)

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/weave#3279]
A user reported this error message, I don't have much information at this point, but opening a bug to track the issue:

![logs-networkpolicy](https://user-images.githubusercontent.com/7986/38945393-5186d182-432e-11e8-89f6-9cfc702cd321.png)

What would be interesting to know:
- how was weave-net installed?
- k8s version

**Comment by marccarre** [comment]
OP:
> I use kubeadm to configure my cluster then i follow your official documentation https://www.weave.works/blog/weave-net-kubernetes-integration/
> after `$ kubeadm init`
> `$ kubectl apply -f https://git.io/weave-kube-1.6`

**Comment by brb** [comment]
Thanks for the info.

Indeed, https://git.io/weave-kube-1.6 (https://github.com/weaveworks/weave/releases/download/latest_release/weave-daemonset-k8s-1.6.yaml) misses RBAC for the `'networking.k8s.io'` apiGroup, thus the error.

Could you meanwhile suggest the user to follow the official installation method: https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#install ?

We need to update https://git.io/weave-kube-1.6 to point to https://github.com/weaveworks/weave/releases/download/latest_release/weave-daemonset-k8s-1.7.yaml and update the blog post to add the link to the docs.

**Comment by brb** [comment]
Closing this as the git.io link got updated and thus, the installation method listed in the blogpost https://www.weave.works/blog/weave-net-kubernetes-integration/ becomes valid again.
