### ISSUE TITLE
Older blog post has a broken weave-kube-1.6 link

### ISSUE THREAD

**Issue by fbarl** [weaveworks/weave#3286]
An Intercom user recently ended up reading https://www.weave.works/blog/weave-net-kubernetes-integration/ for setting up Weave Net on their K8s cluster (instead of our newer docs).

When trying to run the first command...

```
$ kubectl apply -f https://git.io/weave-kube-1.6
```

... he found that the link https://git.io/weave-kube-1.6 gives:

```
No url found for weave-kube-1.6
```

cc @bboreham

**Comment by bboreham** [comment]
This is a GitHub short URL; there is no API to remove them so I don't know what happened.

I think I'll recreate it pointing at the 1.7 (and above) file as Kubernetes 1.6 is ancient now.

**Comment by bboreham** [comment]
We should probably update the blog post to point at the cloud.weave.works endpoint which allows more flexibility

**Comment by bboreham** [comment]
Oddly, it wouldn't let me make it point at the 1.7 file.  
It's now back pointing at the 1.6 file.

**Comment by brb** [comment]
I've asked the GH support to update the redirect to 1.7. Instead, they deleted it, so that we could re-create it.

Anyway, the redirect is still pointing to 1.6. I've just pinged the support again.
