### ISSUE TITLE
offer choice of all log levels

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#329]
We use four log levels in our code - debug, info, warn, error - yet only allow selection of "all except debug" (the default) and "all" (when `-debug` is supplied).

**Comment by inercia** [comment]
I think _warn_ and _error_ should never be silenced, right?. I cannot imagine a situation where you don't want to see errors. If this is the case, that would leave _info_ and _debug_ as optional. Maybe we could `-verbose`/`-v` for enabling _info_, and a second `-v` or `-debug` could enable _debug_...
