### ISSUE TITLE
weave-net                     1/2       CrashLoopBackOff 

### ISSUE THREAD

**Issue by rbehravesh** [weaveworks/weave#3303]
** Is this a BUG REPORT? **
Yes (I think)

Thank you!
-->

## What you expected to happen?
To have a healthy and running cluster
## What happened?
I have a cluster of 3 raspberry pi3 nodes. I can initialize the cluster; but as soon as I add a node to the cluster weave-net pod goes down.

## Anything else we need to know?

[node.txt](https://github.com/weaveworks/weave/files/2014024/node.txt)
[error.txt](https://github.com/weaveworks/weave/files/2014026/error.txt)

## Versions:
HypriotOS/armv7: pirate@kubemaster in ~

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm"}
The connection to the server 192.168.1.2:6443 was refused - did you specify the right host or port?

$ weave version
v1.6
$ docker version
Version:	18.04.0-ce
$ uname -a
Linux kubemaster 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux
$ kubectl version
```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave

"kubectl -n kube-system get pods"

NAME                                 READY     STATUS             RESTARTS   AGE
etcd-kubemaster                      1/1       Running            1          6h
kube-apiserver-kubemaster            1/1       Running            1          6h
kube-controller-manager-kubemaster   1/1       Running            1          6h
kube-dns-686d6fb9c-lhnln             3/3       Running            3          7h
kube-proxy-9khvb                     1/1       Running            1          7h
kube-proxy-lbfps                     1/1       Running            3          6h
kube-scheduler-kubemaster            1/1       Running            1          6h
weave-net-bfv86                      2/2       Running            3          6h
weave-net-w9rsw                      1/2       CrashLoopBackOff   88         6h
[error.txt](https://github.com/weaveworks/weave/files/2014031/error.txt)

"kubectl -n kube-system logs weave-net-w9rsw weave"
output---> standard_init_linux.go:190: exec user process caused "exec format error"

Also, After joining the 3rd node to the cluster it closes the connection following by this error:

Message from syslogd@behrouz at May 17 15:43:49 ...
 kernel:[  225.031619] Internal error: Oops: 80000007 [#1] SMP ARM

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.111898] Process weaver (pid: 2794, stack limit = 0xa96e6210)

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.124577] Stack: (0xa96e79f0 to 0xa96e8000)

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.137032] 79e0:                                     00000000 00000000 0201a8c0 a96e7a90

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.162494] 7a00: 0000801a 00001687 ae661d50 ae661d18 80c85e00 a96e7a20 80c7b140 b96eb480

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.187723] 7a20: 80c7b140 00000000 a96e7a64 00000000 00000000 a9652850 00000000 00001687

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.213473] 7a40: ae474000 aa98c500 00002100 a9652800 00000050 0000801a 68bcc000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.239420] 7a60: 00000000 00000000 00008000 0000ee47 00000002 0201a8c0 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.265180] 7a80: 00000000 00000000 00000000 00000000 1401a8c0 00000000 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.290944] 7aa0: 00000000 00000000 00000000 ae6616c0 aa98c000 00002000 aa98c000 0000056e

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.316808] 7ac0: a9652800 ae763900 a96e7b54 a96e7ad8 7f65532c 7f653cf4 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.342913] 7ae0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.369939] 7b00: 00000000 00000000 00000000 8067af3c 00000040 401d5809 00000040 ae6616c0

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.398005] 7b20: 00000000 aa98c000 a96e7b64 ae6616c0 00000003 aa98c000 aa98c000 0000056e

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.427270] 7b40: 00000000 ae763900 a96e7b9c a96e7b58 8067b4a4 7f654f34 a96e7b9c a96e7b68

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.457995] 7b60: 8067b0ec a96e7bb0 80c04e84 00000000 00000000 80b8c578 00000003 ae6616c0

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.489886] 7b80: aa98c000 ae763900 00000008 ae6616c0 a96e7bf4 a96e7ba0 8067be44 8067b410

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.522952] 7ba0: 00000000 00000000 00000000 00000000 fffffff4 00000000 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.556219] 7bc0: 00000000 00000000 00000000 ae6616c0 aa9c1800 0000ffff aa9c1800 aab66c40

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.588645] 7be0: 00000008 ae6616c0 a96e7c04 a96e7bf8 8067bfcc 8067b744 a96e7c24 a96e7c08

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.621127] 7c00: 7f628bd8 8067bfbc 00000000 ae6616c0 98c80038 00000000 a96e7c54 a96e7c28

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.655357] 7c20: 7f61b32c 7f628afc a96e7c54 a96e7c38 7f622b18 00000002 b96eb19c ae6616c0

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.689307] 7c40: 00000001 98c80038 a96e7cdc a96e7c58 7f61c74c 7f61b2d8 00000001 00000400

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.721448] 7c60: 00000000 00000001 00000000 80273138 80c7b140 00000001 00000000 98c80038

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.753563] 7c80: 00000001 b96eb190 006275e0 aab66c40 a96e7cc4 00000040 98c80038 a96e7d24

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.786067] 7ca0: 80c7b140 00000001 a9653014 a9653590 98c80038 80b8d820 aab66c40 ae6616c0

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.818847] 7cc0: 00000001 98c80038 a9653014 00000000 a96e7d0c a96e7ce0 7f61cac4 7f61b3e8

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.850439] 7ce0: 00000014 a96e7cf0 aab66c40 ae6616c0 98c80000 b96eb180 98c80038 a9653014

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.881919] 7d00: a96e7d54 a96e7d10 7f61e29c 7f61ca70 00000001 00000044 7f62d294 00000001

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.913387] 7d20: a96e7d54 b96eb180 804b5018 7f62d27c 7f631050 a9653000 ae661300 80c7b140

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.944844] 7d40: ae4cc3c0 a96e7dc0 a96e7dbc a96e7d58 806b85f8 7f61e0cc 7f62d294 a96e7dc0

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  225.976353] 7d60: a9653010 00000018 0000001f 00000a8c a9653000 a9653010 a9653014 ae4cc3c0

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.007862] 7d80: 80c7b140 00000000 00000000 a96e7dc0 807878e8 ae661300 a9653000 806b83d0

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.039604] 7da0: 000005d4 00000000 00000000 ae661300 a96e7dfc a96e7dc0 806b7500 806b83dc

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.071167] 7dc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.102670] 7de0: 807878e8 80c7e9b8 ae661300 ae661300 a96e7e14 a96e7e00 806b83bc 806b7430

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.134204] 7e00: bce3e000 ae5fe800 a96e7e44 a96e7e18 806b6c70 806b8398 a96e7ea4 7fffffff

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.166009] 7e20: ae5fe800 a96e7ed0 ae5fe800 000005d4 00000000 00000000 a96e7ea4 a96e7e48

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.197729] 7e40: 806b70c4 806b6b00 014200ca 0000035b 0036b000 802a6bd8 aa8a0c00 00000008

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.229281] 7e60: a96e7ec4 bc213800 00000000 00000a8c 00000000 00000000 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.260879] 7e80: 9cc92000 1265a0ec 0000000c 00000000 a96e6000 00000000 a96e7eb4 a96e7ea8

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.292390] 7ea0: 8065a438 806b6e18 a96e7fa4 a96e7eb8 8065b570 8065a420 a96e7ed8 be5dad40

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.323911] 7ec0: 00000000 00000001 123c0000 000005d4 a96e7f00 0000000c 00000001 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.355377] 7ee0: 00000000 a96e7ed0 00000000 123dc700 00000000 00000000 00000000 8078ae20

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.386798] 7f00: 00000010 00000000 00000000 801eb8bc 00000bb8 6f6febc4 00000000 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.418594] 7f20: a96e7f3c a96e7f30 80628c14 80628bd0 a96e7f6c 6f6fea74 00000000 00000107

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.451102] 7f40: 80107f64 6f6fea74 00000008 00000000 00000001 80495d30 a96e7f7c a96e7f68

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.482591] 7f60: 80187168 80495d14 000000e1 01c55ba3 a96e7fa4 a96e7f80 80195148 8018710c

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.514291] 7f80: 000000e1 1265a0ec 0000000c 007e6e40 00000122 80107f64 00000000 a96e7fa8

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.546063] 7fa0: 80107dc0 8065b4b8 1265a0ec 0000000c 00000005 123c0000 000005d4 00000000

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.577549] 7fc0: 1265a0ec 0000000c 007e6e40 00000122 1265a100 00000007 123dc700 00d77d28

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  226.609009] 7fe0: 1265a0fd 125c4da8 00011408 0007b2a8 600f0010 00000005 ebfffffe ea000058

Message from syslogd@behrouz at May 17 15:43:51 ...
 kernel:[  227.183252] Code: bad PC value
packet_write_wait: Connection to 192.168.1.20 port 22: Broken pipe
```
<!-- (If output is long, please consider a Gist.) -->
<!-- Anything interesting or unusual output by the below, potentially relevant, commands?
$ journalctl -u docker.service --no-pager
$ journalctl -u kubelet --no-pager
$ kubectl get events
-->

## Network:
<!-- If your problem has anything to do with one network endpoint not being able to contact another, please run the following commands -->
```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by Rasoul2669** [comment]
@brb I also tried the latest version, but it's the same!

**Comment by pataha** [comment]
I have same issue with `raspbian stretch lite`

**Comment by brb** [comment]
Probably a duplicate of https://github.com/weaveworks/weave/issues/3276
