### ISSUE TITLE
'weave expose' address does not persist after host rebooted

### ISSUE THREAD

**Issue by kcao3** [weaveworks/weave#3306]
I notice currently on a host, the IP address assigned to the weave interface after running 'weave expose' command does not persist after the host rebooted. Is there a simple way to persist this IP address without running the 'weave expose' command every time the host reboots?

**Comment by bboreham** [comment]
I think your question is mostly a duplicate of #2144

It’s not a complex change, but no-one has submitted a PR yet.  Probably creating a test is the hard part. 

You can force the address, eg `weave expose 9.8.7.6`

**Comment by kcao3** [comment]
Thank you for your prompt response. No big deal. I'll just use a systemd service unit for now then.
