### ISSUE TITLE
Extend checkpoint to include information about Kubernetes clusters

### ISSUE THREAD

**Issue by brb** [weaveworks/weave#3324]
Currently, we do not have any coarse grained information about Kubernetes clusters which are powered by Weave Net. The information would be used for prioritizing issues.

1. Kubernetes version.
2. Nodes count.
3. Whether NetworkPolicies are used (and what type - Ingress / Egress).

**Comment by murali-reddy** [comment]
I made a small patch, but before going further just want to check if its correct way?

https://gist.github.com/murali-reddy/07ef27d90b3b160bfe892ff2c2d1977b#file-checkpoint-go

From [schema](https://github.com/weaveworks/marketingops/blob/master/checkpoint/schema.json) extending flags is the right way?

**Comment by murali-reddy** [comment]
> You won't get the version that way, will you?

Yes, we get the version info. Its same api call `kubectl version` makes
