### ISSUE TITLE
Pod creation based on Weave CNI

### ISSUE THREAD

**Issue by psaini79** [weaveworks/weave#3329]
I have multiple CNI plugin installed on my k8s master and worker nodes. By default flannel is come as a network for a pod. I am trying to create a pod based on weave, is there a way to force the weave for CNI?

I am using following pod yaml file but it didn't work:
apiVersion: v1
kind: Pod
metadata:
  name: ol76
  labels:
    name: ol76
  annotations:
    cni: "weave"
spec:
  hostname: ol76
  containers:
    - name: ol76
      image: oraclelinux:latest
      resources:
       limits:
         memory: "200Mi"
         cpu: "1.5"
       requests:
         memory: "200Mi"
         cpu: "1.5"

**Comment by brb** [comment]
@psaini79 You need either to uninstall flannel or to make sure that `/etc/cni/net.d/10-weave.conf` comes first in lexicographical order before flannel's config in the same dir. Please see the "CNI" section in https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements for more details.

Where did you find about the "cni" annotation used in your example?

**Comment by psaini79** [comment]
I have not looked at it completely but https://github.com/Huawei-PaaS/CNI-Genie claims that assign an IP address to a pod from a particular network solution.

I looked at some of their pod spec files and found annotation:cni but it seems it is the way they have written the CNI.
