### ISSUE TITLE
IP range for PODs

### ISSUE THREAD

**Issue by psaini79** [weaveworks/weave#3330]
Hi,

Is there a way to specify the range of IPs for a pod? for example, I have weave network configured on following cidr 192.168.16.0./24 but I want pods choose IPs for pod from this range only 192.168.168.100-192.168.168.200 during POD creation. However, rest of the IPs can be up as an IP alias inside the POD.
Eg:

eth1 will have 192.168.16.100 but our application will create an alias of 192.168.16.10 on eth0:1. I just want to make sure that some reserved IPs should not be given to pod during pod creation.

**Comment by brb** [comment]
@psaini79 You could modify the weave CNI config (`/etc/cni/net.d/10-weave.conf`) on each of your nodes to:

```
{
    "name": "weave",
    "type": "weave-net",
    "hairpinMode": true,
    "ipam": {
       "type": "weave-ipam",
       "subnet":  $PODS_CIDR
    }
}
```
where `$PODS_CIDR` is a CIDR range for Pod IP addrs (in your example, 192.168.16.100-192.168.16.200 cannot be represented as a single CIDR range).

Unfortunately, at the moment this does not work due to the bug: https://github.com/weaveworks/weave/issues/3331. Please follow #3331 for updates.

**Comment by psaini79** [comment]
I tried following conf and it worked. I am getting correct route settings.

{
    "name": "weave",
    "type": "weave-net",
    "hairpinMode": true,
    "ipam": {
        "type": "host-local",
        "subnet": "192.168.16.0/24",
        "rangeStart": "192.168.16.201",
        "rangeEnd": "192.168.16.225",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}

**Comment by brb** [comment]
@psaini79 Currently, we do not support the "host-local" IPAM plugin (see #3311), and it's not safe to use it. One problem is that the weave bridge might end up getting an IP addr from Weave IPAM instead of asking the host-local plugin which leads to various problems, e.g. a host can't reach a pod.

**Comment by bboreham** [comment]
I suspect the case you outline will still work.  The Weave Net CNI plugin sets a route to the gateway address if it's not on the same subnet.

**Comment by brb** [comment]
I doubt that it can work if https://github.com/weaveworks/weave/blob/2.3/prog/weave-kube/launch.sh#L145 wins the race against https://github.com/weaveworks/weave/blob/2.3/plugin/net/cni.go#L97:

- No route to a pod network on a host (the weave bridge in different subnet than the pod network).
- The default gw is `192.168.16.1` (haven't checked why though) which is unassigned, so a pod can't reach outside.
