### ISSUE TITLE
Connection reset after transmission for several successful packets

### ISSUE THREAD

**Issue by hongxima** [weaveworks/weave#3336]
Dear gurus,

We just hit a terrible network issue in a new setup for a key customer.
Two days sent on troubleshooting and not resolved.

Symptom
Pod communication to outside host was reset after transmission for several successful packets, and BLOCKing messages were logged in weave-npc.

The outside host is an SVN server. Inside the pod, curl server:port was able to get a short HTML response, but if do "svn co SERVER", the connection get reset.

Tcpdump says, several packages were sucessfully transimitted in the peers before a RST sent to SVN Server.

Also tried docker run with generic docker bridge, works great. 

Issue remains and always happens to K8S + Weavenet.

Weave version: 2.3
Kernel 3.10.0-327 
Linux RHEL7.2
K8S: 1.9.3
Docker 18.03.1

The similar design and configurations work good on Ubuntu 16.04 clusters.

Any ideas? Thanks!

**Comment by bboreham** [comment]
I can't think of any mechanism in Weave Net that sends a RST.  Maybe duplicate IP address would lead to it, if the other side was getting confusing messages.

When using the default CNI config, communication to the outside world goes container -> veth -> bridge -> host -> world: those packets don't traverse the Weave Network.

About the blocking messages: did the IP addresses correspond to the connections that were being reset?  Did the times match?  If so, it should be possible to trace back to the policy that was causing blocking.  Currently we only support ingress policies so those shouldn't affect traffic leaving the cluster.

These instructions, from the issue template, may provide some information which helps to understand the problem:

> If your problem has anything to do with one network endpoint not being able to contact another, please run the following commands 
```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by hongxima** [comment]
Bryan,
Thanks for the reply!
Just update to you ,we were able to reproduce the issue (need promisc to be on, and connection always reset)  in another setup, the issue gone after upgrade to RHEL 7.5

So we'll take this as our resolution.

Thanks!

**Comment by brb** [comment]
@hongxima May I ask on which interface you have set promiscuous mode on?

**Comment by hongxima** [comment]
@brb  the weave bridge itself. 
But this only happens to RHEL 7.2 ,  you don't need it for RHEL7.4+

**Comment by brb** [comment]
@hongxima Thanks. Any idea which change (probably in the kernel) between RHEL7.2 and RHEL7.4 has fixed the issue?

**Comment by hongxima** [comment]
@brb We didn't have time to find the root cause, so far RHEL7.5 has been working pretty well.
