### ISSUE TITLE
Update ECS references

### ISSUE THREAD

**Issue by dholbach** [weaveworks/weave#3338]
[site/install/installing-weave.md](https://github.com/weaveworks/weave/blame/master/site/install/installing-weave.md#L53) contains these bits currently:

```markdown
Amazon ECS users see [here](https://github.com/weaveworks/integrations/blob/master/aws/ecs/README.md)
for the latest Weave AMIs and [here](https://www.weave.works/docs/tutorials/old-guides/ecs/) to get started with Weave Net on ECS.
```

The former link should be https://www.weave.works/docs/scope/latest/ami/ (or https://github.com/weaveworks/scope/blob/master/site/ami.md) instead.

The latter is part of `old-guides` which are unfortunately very much out of date. Is the tutorial generally useful and something we should keep? If yes, it would need quite a bit of updating.

**Comment by dholbach** [comment]
I'm going to move the `old-guides` to https://github.com/weaveworks-guides/old-guides for archiving purposes soon.

It'd be good to resolve this issue before then. Does anyone have any opinions?

**Comment by bboreham** [comment]
I think https://www.weave.works/docs/scope/latest/ami/ is the best we have.
If the other one is out of date and there's nothing to replace it, we just have to delete the link.
