### ISSUE TITLE
Cant Set logLevel for kubernetes Deployment

### ISSUE THREAD

**Issue by tmedford** [weaveworks/weave#3342]
I may be missing something but I cant see anyway to set the log level of weave-npc or weave via ENV vars for kuberentes deployment.

**Comment by bboreham** [comment]
It’s a command-line argument `—log-level`

Please can you provide more context why you specifically need an environment variable.

**Comment by brb** [comment]
We do not document how to change the log levels at https://www.weave.works/docs/net/latest/kubernetes/kube-addon/.

For `weave`, you can pass `--log-level=...` via the `EXTRA_ARGS` env arg.

**Comment by jrryjcksn** [comment]
I'd like to address this, but I want to be completely clear on what's being asked. I followed the link in the comment above but found the following: 

`By default log level of weave container is set to info level. If you wish to see more detailed logs you can set the desired log level for the -log-level flag through the EXTRA_ARGS environment variable for the weave container in the weave-net daemon set. Add environment variable as below.` and an example:

>   containers:
      - command:
        - /home/weave/launch.sh
        name: weave
        env:
        - name: EXTRA_ARGS
          value: --log-level=debug

The comment says we do not document how to change it.  I'm a bit confused. Can someone clarify exactly what needs to be fixed?

**Comment by murali-reddy** [comment]
https://github.com/weaveworks/weave/pull/3391 added the documentation which should have closed this issue. But as you already linked this issue to #3594 with extra details its fine.
