### ISSUE TITLE
How to bootstrap Weave Net on k8s Master nodes?

### ISSUE THREAD

**Issue by krzysztof-bronk** [weaveworks/weave#3365]
Hello,

I've successfully deployed Weave 2.4.0 for k8s 1.10.4 via CNI using the **V2 Docker Network plugin**

However, I currently need to be able to connect from my master **nodes** to worker **pods**. 
The problem is, as there is no kubelet running on Master nodes, weave is essentially idle - it does not create the weave interface and so pod routing is missing.

Is there a way to force weave to do it without having to use kubelet on the master node and running pods you don't want anyway?

Note: I tried to **docker run** a random container and then attach weave to it, and it did receive an IP address, but somehow the interface was still missing...

**Comment by krzysztof-bronk** [comment]
Correction: the interface is there, but the route is not. I'll see if I can create it manually and if that is enough for the setup to work.

**Comment by krzysztof-bronk** [comment]
I found that after running **weave expose** I'm getting the desired outcome - iptables are updated, and so is the route table. 

However this does not survive a reboot

**Comment by bboreham** [comment]
> via CNI using the V2 Docker Network plugin

Is that something you specifically needed to do?  CNI and Docker Plug-in are two different ways to achieve the same end. 

If you have no preference, just use the Weave Net Kubernetes add-on which will configure everything for you. 

https://www.weave.works/docs/net/latest/kubernetes/kube-addon

**Comment by krzysztof-bronk** [comment]
In general I prefer the systemd or plugin way, to limit the number of k8s parts that are run... within k8s. I know it's common practice, but I feel a little uneasy when running cluster-critical components as part of the very same cluster, so if possible, I avoid it.

But all in all, using the addon instead of the plugin still requires CNI right?
It is just much more clear what is actually running (as opposed to the invisible docker containers in case of the plugin, where also half of the weave commands are suddenly not to be used).
 
I'm also running pure Master nodes, that nevertheless need access to pods, don't remember if the addon provides that.

**Comment by bboreham** [comment]
> It is just much more clear what is actually running (as opposed to the invisible docker containers in case of the plugin, where also half of the weave commands are suddenly not to be used).

OK, so you don't want to use the Docker plugin interface.

Kubernetes (broadly) requires CNI, yes.

The non-addon CNI instructions are at https://www.weave.works/docs/net/latest/kubernetes/

"`weave expose` does not survive a reboot" is #2144

**Comment by krzysztof-bronk** [comment]
Thank you for the tips, I'll test the alternatives :) Hopefully I will find a non-intrusive way of rolling it out though, as we have a lot of services already running in production.

**Comment by gbolo** [comment]
hey @krzysztof-bronk , I also have a similar deployment (master components are not in the k8s infrastructure). Was wondering if you ever figured out an elegant solution to this? Or did you just end up bootstrapping the apiserver with kublet so that it's now part of the k8s infrastructure?
