### ISSUE TITLE
WEAVE_DOCKER_ARGS cause "invalid reference format" error

### ISSUE THREAD

**Issue by bklau** [weaveworks/weave#3370]
Symptom:
------------
When attempting to pass additional Docker run arguments to `weave launch`, got an error "invalid reference format".
Found in version : Weave version2.4.0

Steps to repro:
-----------------
Just execute the code below to add a  custom Docker label "com.abc.com.container.ignore"
`WEAVE_DEBUG= WEAVE_DOCKER_ARGS="-l com.abc.com.container.ignore"  weave launch`
unable to create container: API error (500): invalid reference format

Note: When WEAVE_DOCKER_ARGS="", it works.

**Comment by bboreham** [comment]
Hi, could you run `WEAVE_DEBUG=true WEAVE_DOCKER_ARGS="-l com.abc.com.container.ignore" weave launch` and post the full output please

**Comment by bklau** [comment]
WEAVE_DEBUG=true  WEAVE_DOCKER_ARGS="-l com.abc.com.container.ignore"  weave launch
/usr/local/bin/weave: 6: /usr/local/bin/weave: Bad substitution

**Comment by bklau** [comment]
WEAVE_DOCKER_ARGS="-l com.abc.com.container.ignore"  weave launch
unable to create container: API error (500): invalid reference format

**Comment by brb** [comment]
Fixed by #3371.
