### ISSUE TITLE
Weave not updating tables from network policy

### ISSUE THREAD

**Issue by michaelplemmons** [weaveworks/weave#3377]
## What you expected to happen?
I expect egress traffic to be blocked

## What happened?

All egress traffic is allowed

## How to reproduce it?
The custom container is just a script accessing a public website every 30 seconds.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: plem-network-policy
  policyTypes:
  - Egress
  egress: []

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plem-network-policy
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plem-network-policy
      annotations:
        realm: bonn
        app: plem-network-policy
    spec:
      containers:
      - name: plem-network-policy
        image: CUSTOM_CONTAINER
        imagePullPolicy: Always
      nodeSelector:
        environment: dev

## Anything else we need to know?
The K8s cluster was configured by hand.

AWS
Weave
Kubernetes
CoreOS

## Versions:

$ kubectl exec -ti weave-net-cx7jp -n kube-system sh   
Defaulting container name to weave.
Use 'kubectl describe pod/weave-net-cx7jp' to see all of the containers in this pod.
/home/weave # ./weave version
weave script 2.3.0
./weave: line 249: docker: not found
ERROR: Unable to parse docker version

 # docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.6
 Git commit:   9ee9f40
 Built:        Thu Apr 26 04:27:49 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.6
  Git commit:   9ee9f40
  Built:        Thu Apr 26 04:27:49 2018
  OS/Arch:      linux/amd64
  Experimental: false

$ uname -a
Linux ip-10-49-10-167.XXXXXXX.com 4.14.59-coreos-r2 #1 SMP Sat Aug 4 02:49:25 UTC 2018 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", GitCommit:"c2aac694c2c7373dfe3ad81f47fc3cbc70a5a8fa", GitTreeState:"clean", BuildDate:"2018-03-21T21:54:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

## Logs:
The gist is the output of ipset and iptables rules as well as our weave manifest.

https://gist.github.com/michaelplemmons/95a1cff3412eff81022de640c5407244

**Comment by murali-reddy** [comment]
@michaelplemmons Please note that egress network policies are supported only from 2.4.0.

https://github.com/weaveworks/weave/releases/tag/v2.4.0
