### ISSUE TITLE
Feature request: Please make NO_MASQ_LOCAL=1 the default setting

### ISSUE THREAD

**Issue by jeroenjacobs79** [weaveworks/weave#3389]
Please make NO_MASQ_LOCAL=1 the default setting.

People expect that "ExternalTrafficPolicy: Local" behaves as described by the Kubernetes documentation. This currently not the case with Weave, which causes confusion. I lost hours troubleshooting why ExternalTrafficPolicy was not working as expected, and it was only due to pure luck and some creative googling that I discovered the problem was caused by Weave.

While some might argue that NO_MASQ_LOCAL is mentioned in the release notes of 2.4.0, It feels wrong that you need extra config parameters to make Weave work in a way that is compliant with the standard.

**Comment by brb** [comment]
@jeroenjacobs1205 Thanks for the issue. We will discuss, and maybe make it the default.

Noting that the setting is documented at https://www.weave.works/docs/net/latest/kubernetes/kube-addon/ which I always recommend to read before installing Weave Net on Kubernetes.

**Comment by RRAlex** [comment]
@jeroenjacobs1205 had anything else to do to make it work?
I can't get this to work with both `NO_MASQ_LOCAL` and `ExternalTrafficPolicy: Local`...

**Comment by brb** [comment]
@RRAlex please open a separate issue.

**Comment by dnavre** [comment]
Lost 2 days on this stuff. Indeed, please make this the default.

**Comment by cbabs** [comment]
I agree.  Needs to be default.  It follows the service intended state.  Without it's like ordering fries(DNAT only)  with your burger, but the chef gives you a salad(SNAT).  Oh, you actually wanted the fries you ordered?  Why didnt you say so?! :)

**Comment by virtualdxs** [comment]
I'm wondering, is there any specific reason this isn't the default? Does this being on break something else, or cause something to behave unexpectedly?

**Comment by bboreham** [comment]
> is there any specific reason this isn't the default? Does this being on break something else

It's hard to know what will break when you change something that has been installed 200 million times, so the general tendancy is to make changes optional.
For instance `NO_MASQ_LOCAL` relies on ipset support so will break on a kernel without that, and it's more expensive at runtime.

However #3756 will change the default in our published Kubernetes configs.
