### ISSUE TITLE
weave logs returns many WARN: Vetoed installation of hairpin flow FlowSpec

### ISSUE THREAD

**Issue by bamb00** [weaveworks/weave#3390]
## What you expected to happen?
kube-dns pod does not go into CrashLoopBackOff and the weave pod does not have the vetoed problem with minion-01 node.

## What happened?
kube-dns consistently goes into CrashLoopBackOff and weave log returns "Vetoed installation of hairpin flow FlowSpec" repeatedly of node minion-01 in a 5 node cluster.  The WARN message occurs only on k8s master node.

     
## How to reproduce it?
Install k8s with 5 node (1 master, 4 minion) using kubeadm

## Anything else we need to know?
Provide: Vsphere
OS: CentOS 7.5

## Versions:

       Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
       Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ weave version 2.2.0
$ docker version 1.13.1-cs9 overlay2
$ uname -a  3.10.0-862.9.1.el7.x86_64
$ kubectl version v1.9.5

## Logs:

Weave Logs from master-01:

		INFO: 2018/09/02 09:07:51.881375 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 09:07:53.954330 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: d2:f5:03:28:ac:42} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		WARN: 2018/09/02 09:18:00.958391 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 0e:7a:57:7f:40:c6} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 09:49:26.841209 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 09:49:28.914372 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 12:c3:a9:73:3b:36} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 09:50:03.888489 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=3.10.0-862.9.1.el7.x86_64&flag_network=fastdp&flag_network=fastdp&flag_network=fastdp&flag_network=fastdp&os=linux&signature=630Ii0gqKoS6Ju6LuDUmPcvUifShTj4odf02d%2BHjw%2Fg%3D&version=2.2.0: dial tcp 173.194.203.121:443: i/o timeout
		INFO: 2018/09/02 10:00:03.344156 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 10:00:05.426252 Vetoed installation of hairpin flow FlowSpec{keys: [InPortFlowKey{vport: 1} EthernetFlowKey{src: de:30:04:12:c0:24, dst: f6:a4:29:6c:ce:fe}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 10:19:42.411650 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 10:19:44.442401 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: ae:45:55:c5:5b:29} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 10:30:13.532442 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 10:30:15.562336 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 46:46:b0:a5:f6:49} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 11:01:02.885944 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 11:01:04.958381 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: ba:39:b8:48:45:fb} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 11:22:48.929458 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 11:22:50.962354 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: ee:02:7d:2a:0c:73} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		WARN: 2018/09/02 11:31:58.450376 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 16:0f:cc:81:8e:d6} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 11:52:47.419842 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 11:52:49.494330 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 6a:74:94:c2:1f:01} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		WARN: 2018/09/02 12:04:42.022332 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: f6:3c:4b:f8:5a:d1} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 12:15:05.255231 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 12:15:07.342341 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: c6:f7:3c:a8:aa:d6} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 12:34:43.888736 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 12:34:45.970333 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 36:42:59:eb:ab:97} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 12:45:07.813614 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 12:45:09.890363 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: ca:a5:3a:d6:ce:41} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 13:16:03.904527 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		INFO: 2018/09/02 13:37:49.894849 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 13:37:51.974298 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 7e:9b:24:08:8d:99} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		WARN: 2018/09/02 13:46:56.018307 Vetoed installation of hairpin flow FlowSpec{keys: [InPortFlowKey{vport: 1} EthernetFlowKey{src: de:30:04:12:c0:24, dst: fa:f3:31:75:01:e3}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 14:07:45.919948 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 14:07:48.006344 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 4a:d2:26:d1:e3:97} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		WARN: 2018/09/02 14:17:58.962342 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 36:d0:a7:e8:eb:87} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 14:49:49.937084 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 14:49:52.026320 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 4e:4e:83:f3:fb:eb} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 15:00:09.908146 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 15:00:11.938269 Vetoed installation of hairpin flow FlowSpec{keys: [InPortFlowKey{vport: 1} EthernetFlowKey{src: de:30:04:12:c0:24, dst: 42:d6:b1:c3:bf:dc}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 15:30:24.314662 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 15:30:26.394364 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: ca:5d:b0:89:6a:c3} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 16:01:13.404314 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 16:01:15.490308 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: aa:18:b5:17:db:1f} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
		INFO: 2018/09/02 16:04:11.524551 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=3.10.0-862.9.1.el7.x86_64&flag_network=fastdp&flag_network=fastdp&flag_network=fastdp&flag_network=fastdp&os=linux&signature=630Ii0gqKoS6Ju6LuDUmPcvUifShTj4odf02d%2BHjw%2Fg%3D&version=2.2.0: dial tcp 173.194.203.121:443: i/o timeout
		INFO: 2018/09/02 16:22:46.915145 Discovered remote MAC 0e:b4:87:15:0b:b0 at 2e:6b:69:19:f4:86(minion-01)
		WARN: 2018/09/02 16:22:48.970324 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: de:30:04:12:c0:24, dst: 42:63:9c:40:76:c3} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}

Weave Log from minion-01:

		INFO: 2018/09/02 13:00:05.610018 Discovered remote MAC e2:2a:25:e9:94:5e at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 13:15:06.968331 Discovered remote MAC ae:c7:50:f1:f2:3a at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 13:29:58.229110 Discovered remote MAC 7e:9b:24:08:8d:99 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 13:31:07.335485 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=3.10.0-862.9.1.el7.x86_64&flag_network=fastdp&flag_network=fastdp&flag_network=fastdp&flag_network=fastdp&os=linux&signature=XR18h7obksQP09uLJscyFAtIh%2BIF2s3bhd1RyrzAX5o%3D&version=2.2.0: dial tcp 173.194.203.121:443: i/o timeout
		INFO: 2018/09/02 13:44:59.494274 Discovered remote MAC fa:f3:31:75:01:e3 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 14:00:00.807773 Discovered remote MAC 4a:d2:26:d1:e3:97 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 14:15:02.242256 Discovered remote MAC 36:d0:a7:e8:eb:87 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 14:30:03.480289 Discovered remote MAC 9a:51:b9:03:bd:15 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 14:45:04.786768 Discovered remote MAC 4e:4e:83:f3:fb:eb at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 15:00:06.357446 Discovered remote MAC 42:d6:b1:c3:bf:dc at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 15:00:08.878063 Discovered remote MAC f2:9b:b7:43:65:a9 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 15:14:57.631007 Discovered remote MAC e2:cd:5e:c8:4b:fb at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 15:29:59.183942 Discovered remote MAC ca:5d:b0:89:6a:c3 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 15:45:00.207620 Discovered remote MAC f6:76:0b:4d:3b:ba at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 16:00:01.616831 Discovered remote MAC aa:18:b5:17:db:1f at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 16:15:03.197339 Discovered remote MAC 42:63:9c:40:76:c3 at 0a:1a:1c:b5:b1:e7(master-01)
		INFO: 2018/09/02 16:30:04.196342 Discovered remote MAC e2:c0:44:00:d6:b1 at 0a:1a:1c:b5:b1:e7(master-01)

## Network:

```
$ ip route

		default via 172.22.64.129 dev ens192 proto static metric 100
		10.0.0.0/16 dev weave proto kernel scope link src 10.0.0.1
		10.1.1.0/25 dev ens224 proto kernel scope link src 10.1.1.8 metric 101
		172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
		172.22.64.128/25 dev ens192 proto kernel scope link src 172.x.x.x metric 100
		192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1

$ ip -4 -o addr

		1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
		2: ens192    inet 172.x.x.x/25 brd 172.22.64.255 scope global noprefixroute ens192\       valid_lft forever preferred_lft forever
		3: ens224    inet 10.1.1.8/25 brd 10.1.1.127 scope global noprefixroute ens224\       valid_lft forever preferred_lft forever
		4: virbr0    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.1/16 brd 10.0.255.255 scope global weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.2/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.3/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.4/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.5/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.6/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.7/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.8/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.9/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.10/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.11/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		9: weave    inet 10.0.0.12/16 brd 10.0.255.255 scope global secondary weave\       valid_lft forever preferred_lft forever
		4594: docker0    inet 172.17.0.1/16 scope global docker0\       valid_lft forever preferred_lft forever


kube-dns logs:

		# kubectl logs kube-dns-6f4fd4bdf-szpbf -n kube-system kubedns
		I0901 16:13:08.997496       1 dns.go:48] version: 1.14.6-3-gc36cb11
		I0901 16:13:08.998592       1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
		I0901 16:13:08.998658       1 server.go:112] FLAG: --alsologtostderr="false"
		I0901 16:13:08.998673       1 server.go:112] FLAG: --config-dir="/kube-dns-config"
		I0901 16:13:08.998680       1 server.go:112] FLAG: --config-map=""
		I0901 16:13:08.998684       1 server.go:112] FLAG: --config-map-namespace="kube-system"
		I0901 16:13:08.998689       1 server.go:112] FLAG: --config-period="10s"
		I0901 16:13:08.998694       1 server.go:112] FLAG: --dns-bind-address="0.0.0.0"
		I0901 16:13:08.998699       1 server.go:112] FLAG: --dns-port="10053"
		I0901 16:13:08.998709       1 server.go:112] FLAG: --domain="cluster.local."
		I0901 16:13:08.998715       1 server.go:112] FLAG: --federations=""
		I0901 16:13:08.998721       1 server.go:112] FLAG: --healthz-port="8081"
		I0901 16:13:08.998726       1 server.go:112] FLAG: --initial-sync-timeout="1m0s"
		I0901 16:13:08.998733       1 server.go:112] FLAG: --kube-master-url=""
		I0901 16:13:08.998738       1 server.go:112] FLAG: --kubecfg-file=""
		I0901 16:13:08.998742       1 server.go:112] FLAG: --log-backtrace-at=":0"
		I0901 16:13:08.998751       1 server.go:112] FLAG: --log-dir=""
		I0901 16:13:08.998756       1 server.go:112] FLAG: --log-flush-frequency="5s"
		I0901 16:13:08.998761       1 server.go:112] FLAG: --logtostderr="true"
		I0901 16:13:08.998766       1 server.go:112] FLAG: --nameservers=""
		I0901 16:13:08.998770       1 server.go:112] FLAG: --stderrthreshold="2"
		I0901 16:13:08.998775       1 server.go:112] FLAG: --v="2"
		I0901 16:13:08.998779       1 server.go:112] FLAG: --version="false"
		I0901 16:13:08.998787       1 server.go:112] FLAG: --vmodule=""
		I0901 16:13:08.998935       1 server.go:194] Starting SkyDNS server (0.0.0.0:10053)
		I0901 16:13:08.999419       1 server.go:213] Skydns metrics enabled (/metrics:10055)
		I0901 16:13:08.999440       1 dns.go:146] Starting endpointsController
		I0901 16:13:08.999448       1 dns.go:149] Starting serviceController
		I0901 16:13:08.999603       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
		I0901 16:13:08.999629       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
		I0901 16:13:09.020861       1 dns.go:555] Could not find endpoints for service "kafka" in namespace "default". DNS records will be created once endpoints show up.
		I0901 16:13:09.499764       1 dns.go:170] Initialized services and endpoints from apiserver
		I0901 16:13:09.499808       1 server.go:128] Setting up Healthz Handler (/readiness)
		I0901 16:13:09.499829       1 server.go:133] Setting up cache handler (/cache)
		I0901 16:13:09.499839       1 server.go:119] Status HTTP port 8081
		I0901 16:14:48.663106       1 server.go:153] Ignoring signal terminated (can only be terminated by SIGKILL)

**Comment by bboreham** [comment]
Are those the whole logs?

**Comment by bboreham** [comment]
It may also be useful to have the kube-dns log, if it's crashing.

**Comment by bamb00** [comment]
Added the kube-dns log.

**Comment by bamb00** [comment]
An application was causing conflict with the network. It would be nice if the log message was a little more translatable.

Closing issue.

**Comment by brb** [comment]
@bamb00 Any idea why the `weave` bridge interface has so many IP addrs assigned to it? Left by previous installations?

It could be that the same IP addrs are used by containers, so that could lead to the logged hairpin flows.

**Comment by bboreham** [comment]
@brb that's a great spot.  I can imagine multiple Weave Net installations adding more varied IP addresses, but can't think of a way it would assign 12 consecutive addresses in a `/16`.

Multiple IPs in the same subnet doesn't seem like something we could ever want on the `weave` bridge.

**Comment by bamb00** [comment]
@brb Thanks for pointing out the multiple IP addr.  Let me look into that further and report back.

**Comment by brb** [comment]
@bamb00 

> From the Veteod message, How do I track the source 6a:81:04:3d:c5:e7?

This can be a MAC addr either of the `weave` bridge or any container.

Without full logs from your nodes it's difficult to say what's happening.
