### ISSUE TITLE
--conn-limit is not documented

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#3395]
It's not in the `site` directory or in the Usage text in the `weave` script.

I'm rather puzzled since the topic comes up fairly often in questions.

The kube-addon page does mention `CONN_LIMIT`.

**Comment by murali-reddy** [comment]
there is one-liner in configuration options in `kube-addon.md` but needs to be updated with current default of 100

`CONN_LIMIT - soft limit on the number of connections between
  peers. Defaults to 30.`

Will update the docs
