### ISSUE TITLE
Reboot race condition between weave and iptables

### ISSUE THREAD

**Issue by jimethn** [weaveworks/weave#3402]
## What you expected to happen?

When I reboot the machine, my iptables rules are restored from `/etc/sysconfig/iptables`.

## What happened?

The iptables rules were not restored. The systemd iptables.service unit reported:

```
iptables: Applying firewall rules: iptables-restore v1.4.21: Set weave-local-pods doesn't exist.
```

## How to reproduce it?

1. Use kubeadm to set up kubernetes.
2. Install weave
3. Set some custom iptables rules
4. Run `iptables-save > /etc/sysconfig/iptables`
5. Reboot
6. Custom iptables rules are missing

## Anything else we need to know?

When the machine comes up from a reboot, weave hasn't started yet (because it's running inside kubernetes). Because weave is not up yet, it has not yet registered its ip sets with the kernel. Because the ip sets don't exist yet, trying to restore the iptables rules (which contains references to the ip sets) fails.

I'm running kubernetes 1.9.1 on centos 7, set up via kubeadm. Weave was installed by using kubectl to install the weave-net spec (Role, DaemonSet, etc) into the running kubernetes cluster.

## Versions:
```
$ weave version
-bash: weave: command not found
$ kubectl describe pod -n kube-system weave-net-f2ddv |grep Image:
    Image:         weaveworks/weave-kube:2.2.0
    Image:          weaveworks/weave-npc:2.2.0
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
$ uname -a
Linux bal-lab-top-015 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by murali-reddy** [comment]
@jimethn I feel this is not an issue with Weave, but rather how you are restoring the ipset. I think if you do same with ipset i.e.) ipset save an restore before iptables restore. you should be able to overcome the issue you are facing.

However I think if you have custom iptable that need to be created after reboot, it would be better them created separate.

If you restore ipset and ipables that weave created prior to reboot, you would be likely restoring stale configuration which is not desired.

**Comment by jimethn** [comment]
We're restoring iptables the way centos does it out-of-the-box.

**Comment by murali-reddy** [comment]
This is a generic problem you will hit once you have ipset referred by iptables. There does not exist ipset restore (like iptables) on some distros. Please see

https://bugzilla.redhat.com/show_bug.cgi?id=1136257 if it helps

**Comment by murali-reddy** [comment]
Like mentioned in above comment its generic problem. Please re-open if you feel Weave should be doing something to mitigate this.
