### ISSUE TITLE
weave on kubernetes create wrong cni configuration

### ISSUE THREAD

**Issue by fvigotti** [weaveworks/weave#3403]
Hi, with weave version 2.4.1
after an updated I saw errors in kubelet.log reporting invalid "T" charcted in configuration for cni 

the weave created configuration file is : 
```
{
    "name": "weave",
    "type": "weave-net",
    "hairpinMode": True
}
```
now the problem is that  this: `    "hairpinMode": True `  should be `    "hairpinMode": true ` 

now I've already have a conflist file (00-weave.conflist) .. I'm trying to disable the 10-weave.conf creation but that's another story probably.. ( anyway because the first file is taken when the default conflist file is present I don't  get the error described above ) 

I'm wrong or the configuration file created by weave is wrong ? 
have a nice day :)
Francesco

**Comment by murali-reddy** [comment]
> I'm wrong or the configuration file created by weave is wrong ?

I see conf file getting created with `true`.  Are you sure  you this after upgrade to 2.4.1 and also do you see conf files with `True` across all the nodes in the cluster?

**Comment by fvigotti** [comment]
Hi, I'm superbusy fixing other parts of the cluster, if I have a bit of time to create a clean env to test I'll do more specific test and I'll update this issue :) if no one else have seen this behavior you can close the issue  

thank you for your prompt reply,
Francesco

**Comment by murali-reddy** [comment]
No one reported this issue. Please reopen if you are able to reproduce.
