### ISSUE TITLE
weave Net 2.4.1 on macosx 10.13.6

### ISSUE THREAD

**Issue by guijun** [weaveworks/weave#3405]
No DNS entry added after container started.
steps to repoduce:
1. Docker Version 18.06.1-ce-mac73 (26764)
2. install weave 2.4.1 by curl
3. eval $(weave env)
4. docker run --name AAA bash /usr/bash
5. weave ps
   No entry listed.

**Comment by guijun** [comment]
in macosx:
I can't find log lines like below:

INFO: 2018/09/18 14:49:03.386818 GET /_ping
INFO: 2018/09/18 14:49:03.407516 POST /v1.38/containers/create?name=bash01
INFO: 2018/09/18 14:49:03.413996 Creating container with WEAVE_CIDR ""
INFO: 2018/09/18 14:49:09.028982 GET /_ping
INFO: 2018/09/18 14:49:09.030883 GET /v1.38/containers/json?all=1
INFO: 2018/09/18 14:49:13.727706 GET /_ping
INFO: 2018/09/18 14:49:13.734527 DELETE /v1.38/containers/ecb
INFO: 2018/09/18 14:49:18.941662 GET /_ping
INFO: 2018/09/18 14:49:18.944324 GET /v1.38/containers/json
INFO: 2018/09/18 14:49:25.060308 GET /_ping
INFO: 2018/09/18 14:49:25.062860 POST /v1.38/containers/ecb/stop
INFO: 2018/09/18 14:49:25.990321 [nameserver 36:bb:50:ce:71:0c] container ecb837686cbf1d7b7d463bbf10d77187db59a5f2a9d7ce6922617ff7003f43f6 died; tombstoning entry bash01.weave.local. -> 10.32.0.1
INFO: 2018/09/18 14:49:30.125288 GET /_ping
INFO: 2018/09/18 14:49:30.126700 DELETE /v1.38/containers/ecb
INFO: 2018/09/18 14:49:37.040208 GET /_ping
INFO: 2018/09/18 14:49:37.041915 POST /v1.38/containers/create?name=bash01
INFO: 2018/09/18 14:49:37.042120 Creating container with WEAVE_CIDR ""
INFO: 2018/09/18 14:49:37.143940 POST /v1.38/containers/f3b0aba6d71ce7d3610359b5194b15b361fd8a6707c833f5b8f07a4f6ab5ef75/wait?condition=next-exit
INFO: 2018/09/18 14:49:37.147628 POST /v1.38/containers/f3b0aba6d71ce7d3610359b5194b15b361fd8a6707c833f5b8f07a4f6ab5ef75/start
INFO: 2018/09/18 14:49:38.821974 Attaching container f3b0aba6d71ce7d3610359b5194b15b361fd8a6707c833f5b8f07a4f6ab5ef75 with WEAVE_CIDR "" to weave network
INFO: 2018/09/18 14:49:39.947841 [nameserver 36:bb:50:ce:71:0c] adding entry for f3b0aba6d71ce7d3610359b5194b15b361fd8a6707c833f5b8f07a4f6ab5ef75: bash01.weave.local. -> 10.32.0.1

**Comment by murali-reddy** [comment]
@guijun How are you running/installing weave on Mac as per the [instructions](https://www.weave.works/docs/net/latest/install/installing-weave/)? 

> 2018/09/17 10:40:51 http: panic serving 127.0.0.1:45342: runtime error: invalid memory address or nil pointer dereference
goroutine 541 [running]:

Is this the error across the  2.4.1 2.4.0 2.3.0 versions you tried?

**Comment by brb** [comment]
Fixed in #3408

**Comment by guijun** [comment]
thanks for feedback.
"weave ps" will list new running container with name+ip if I upgrade to 2.4.2, right?

**Comment by guijun** [comment]
Could you please let me know that when will 2.4.2 will be released and had follow issue fixed?

No DNS entry added after container started.
steps to repoduce:

Docker Version 18.06.1-ce-mac73 (26764)
install weave 2.4.1 by curl
eval $(weave env)
docker run --name AAA bash /usr/bash
weave ps
No entry listed.

**Comment by murali-reddy** [comment]
there is nothing targeted/planned for 2.4.2, but likely 2.5 will be released in next couple of weeks
