### ISSUE TITLE
picks up internal AWS IP and fails to connect to itself

### ISSUE THREAD

**Issue by Dmitry1987** [weaveworks/weave#3419]
## What you expected to happen?
weave to use the kube-api IP on master node, the external IP of AWS instance

## What happened?
picked up internal IP automatically 

## How to reproduce it?
kubeadm init, with external AWS instance IP, then install weave, all default as in official k8s docs.

## Anything else we need to know?
AWS,  k8s 1.11.3

## Versions:
weave 2.4.1
docker 17.12.1-ce

## Logs:
```
INFO: 2018/09/28 07:37:46.129944 [kube-peers] Added myself to peer list xxxxxxxxxxxxx
DEBU: 2018/09/28 07:37:46.239549 [kube-peers] Nodes that have disappeared: map[]
10.44.0.0
INFO: 2018/09/28 07:37:49.257600 Discovered remote MAC xxxxxxx  at xxxxxxxxx
INFO: 2018/09/28 07:39:52.301078 ->[172.31.12.194:6783] error during connection attempt: dial tcp4 :0->172.31.12.194:6783: connect: connection timed out
INFO: 2018/09/28 07:39:54.878098 ->[172.31.12.194:6783] attempting connection
INFO: 2018/09/28 07:42:02.093191 ->[172.31.12.194:6783] error during connection attempt: dial tcp4 :0->172.31.12.194:6783: connect: connection timed out
INFO: 2018/09/28 07:42:06.123281 ->[172.31.12.194:6783] attempting connection
INFO: 2018/09/28 07:44:13.421038 ->[172.31.12.194:6783] error during connection attempt: dial tcp4 :0->172.31.12.194:6783: connect: connection timed out
```

routes, just in case (aws instance, k8s 1.11.3 fresh install with kubeadm init):

```
default via 172.31.48.1 dev ens3 proto dhcp src 172.31.54.142 metric 100
10.32.0.0/12 dev weave proto kernel scope link src 10.32.0.1
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.31.48.0/20 dev ens3 proto kernel scope link src 172.31.54.142
172.31.48.1 dev ens3 proto dhcp scope link src 172.31.54.142 metric 100
```

I joined few machines, they were even able to connect, I have no idea how but stuff works on remote machines - but there are some problems with connections and I am guessing it's related to weave.

funny thing is, what we see there it's the internal VPC IP address, so it picks it up automatically, and then complains that it can't connect to itself 🤣 I don't get it.

But I need it all to communicate with external IPs only (because I'm doing a multi cloud setup of worker nodes distributed across many bare metal hosting providers , and only master nodes on AWS) how can I fix it?  I don't want weave to use those internal IPs.

**Comment by murali-reddy** [comment]
> But I need it all to communicate with external IPs only (because I'm doing a multi cloud setup of worker nodes distributed across many bare metal hosting providers , and only master nodes on AWS) how can I fix it? I don't want weave to use those internal IPs.

You have a valid case, its good to have the flexibility to choose the external IP address, but unfortunately its hard-coded to give internal IP precedence over external IP.

https://github.com/weaveworks/weave/blob/v2.4.1/prog/kube-utils/main.go#L50-L53

You can swap the order and built an image yourself if you want to try now.

**Comment by Dmitry1987** [comment]
@murali-reddy thank you for the suggestion :)

**Comment by murali-reddy** [comment]
you may also try passing list of peers (with external IP address) with KUBE_PEERS [environment variable](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/)

**Comment by murali-reddy** [comment]
Since you need to specify environment variable in the daemonset, you need to pass list of _all_ the nodes. I have not tested, but i see no reason why it should not work if you pass external IP's as peer's.

**Comment by Dmitry1987** [comment]
I see,
thanks a lot @murali-reddy !

**Comment by gabrielcalderon** [comment]
I'm having the same issue as @Dmitry1987 . Where you able to get it working?

Somo of my nodes are only reachable via External Address. Weave keeps trying to connect via Internal Address.

**Comment by Dmitry1987** [comment]
I don't remember, I think we didn't solve this, but AWS EKS is the way to go on amazon now, so it's better to use EKS service.

**Comment by Dmitry1987** [comment]
Passing all IPs of peers is an option as well but I didn't tried it (it's dynamic usually so it's a hack, not really good idea). We use EKS now and it works great all the time.

**Comment by gabrielcalderon** [comment]
@Dmitry1987 Thanks for the information. We are running on-prem with OpenStack/KVM. Several nodes are running in a different NAT only accesible via External-IP, but they also have an internal-ip. I'm guessing that kube-api is passing these internal IP's to Weave thus why i get a bunch of "error during connection attempt". I will try the Peer List since the IP's are static right now.
