### ISSUE TITLE
weave - net pod crashing CrashLoopBackOff

### ISSUE THREAD

**Issue by irfanjs** [weaveworks/weave#3429]
**what is expected :** 
weave net pod run into CrashLoopBackOff status on worker node, but should be recovered from that 

**what happened**
```
[root@kube-worker kubernetes]# kubectl logs weave-net-vfmbf -p -c weave -n kube-system
Failed to get peers
[root@kube-worker kubernetes]#

```
**how to reproduce**

NA

**environment details need to know :**

kubernetes cluster
one master , one worker 

```
[root@kube-worker kubernetes]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
[root@kube-worker kubernetes]#

Kubernetes v1.12.1

[root@kube-worker kubernetes]# kubectl get nodes
NAME          STATUS   ROLES    AGE     VERSION
kube-master   Ready    master   5d10h   v1.12.1
kube-worker   Ready    <none>   41h     v1.12.1
[root@kube-worker kubernetes]#

[root@kube-worker kubernetes]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                  READY   STATUS             RESTARTS   AGE     IP             NODE          NOMINATED NODE
kube-system   coredns-576cbf47c7-4n4tj              1/1     Running            5          5d10h   10.32.0.12     kube-master   <none>
kube-system   coredns-576cbf47c7-7gqjg              1/1     Running            6          5d10h   10.32.0.13     kube-master   <none>
kube-system   etcd-kube-master                      1/1     Running            6          5d10h   172.28.128.3   kube-master   <none>
kube-system   kube-apiserver-kube-master            1/1     Running            5          5d10h   172.28.128.3   kube-master   <none>
kube-system   kube-controller-manager-kube-master   1/1     Running            5          5d10h   172.28.128.3   kube-master   <none>
kube-system   kube-proxy-ndbv8                      1/1     Running            5          5d10h   172.28.128.3   kube-master   <none>
kube-system   kube-proxy-rnr8x                      1/1     Running            3          41h     172.28.128.4   kube-worker   <none>
kube-system   kube-scheduler-kube-master            1/1     Running            6          5d10h   172.28.128.3   kube-master   <none>
kube-system   weave-net-5thls                       2/2     Running            15         5d10h   172.28.128.3   kube-master   <none>
kube-system   weave-net-vfmbf                       1/2     CrashLoopBackOff   102        41h     172.28.128.4   kube-worker   <none>
[root@kube-worker kubernetes]#

[root@kube-worker kubernetes]# uname -a
Linux kube-worker 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@kube-worker kubernetes]#

[root@kube-worker kubernetes]# docker --version
Docker version 1.13.1, build 8633870/1.13.1
[root@kube-worker kubernetes]#


```

**Logs**

```
[root@kube-worker kubernetes]# kubectl logs weave-net-vfmbf -p -c weave -n kube-system
Failed to get peers
[root@kube-worker kubernetes]#

[root@kube-worker kubernetes]# ip route
default via 10.0.2.2 dev enp0s3 proto dhcp metric 100
10.0.2.0/24 dev enp0s3 proto kernel scope link src 10.0.2.15 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
172.28.128.0/24 dev enp0s8 proto kernel scope link src 172.28.128.4 metric 101
[root@kube-worker kubernetes]#

[root@kube-worker kubernetes]# ip -4 -o addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: enp0s3    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic enp0s3\       valid_lft 79282sec preferred_lft 79282sec
3: enp0s8    inet 172.28.128.4/24 brd 172.28.128.255 scope global noprefixroute enp0s8\       valid_lft forever preferred_lft forever
4: docker0    inet 172.17.0.1/16 scope global docker0\       valid_lft forever preferred_lft forever
[root@kube-worker kubernetes]#


``` 
**NOTE :**
both these nodes are Vagrant nodes using virtualbox as a hypervisor. 
master node has IP : 172.28.128.3
worker node has IP : 172.28.128.4

**Comment by bboreham** [comment]
It is failing to talk to the Kubernetes api-server.  Very similar to https://github.com/weaveworks/weave/issues/3420#issuecomment-427354236

Vagrant is known for creating multiple interfaces, which is the broad context of that problem with Kubernetes.

**Comment by irfanjs** [comment]
thanks. let me follow/read and come back here again ...

**Comment by irfanjs** [comment]
please do not close by that time .... :)

**Comment by bboreham** [comment]
Did you see the bit about adding a route?

**Comment by irfanjs** [comment]
can you please help adding route ?
on master , getting below : 
```
[root@kube-master vagrant]# curl -Ik https://172.28.128.3:6443/api/v1/namespaces/default/events
HTTP/1.1 403 Forbidden
Content-Type: application/json
X-Content-Type-Options: nosniff
Date: Thu, 18 Oct 2018 10:00:48 GMT
Content-Length: 316

```

on worker getting below : 

`Unable to write event: 'Post https://172.28.128.3:6443/api/v1/namespaces/default/events: dial tcp 172.28.128.3:6443: connect: connection refused' (may retry after sleep)`

**Comment by bboreham** [comment]
"connection refused" is unlikely to be the route problem I am thinking of.  "refused" means it contacted some host which actively rejected the connection.

Is Weave Net really trying to talk to 172.28.128.3 ?   Normally the api-server address is a cluster IP like 10.96.0.1.

Is it possible there is another 172.28.128.3 on your network?

**Comment by irfanjs** [comment]
no. there is no another 172.28.128.3 on the network. 
172.28.128.3 is for master and 172.28.128.4 is for worker 
here is the few commands i ran : 

```
[root@kube-master vagrant]# kubectl describe svc kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.96.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         172.28.128.3:6443
Session Affinity:  None
Events:            <none>
[root@kube-master vagrant]#

```
```
[root@kube-master vagrant]# kubectl describe endpoints kubernetes
Name:         kubernetes
Namespace:    default
Labels:       <none>
Annotations:  <none>
Subsets:
  Addresses:          172.28.128.3
  NotReadyAddresses:  <none>
  Ports:
    Name   Port  Protocol
    ----   ----  --------
    https  6443  TCP

Events:  <none>
[root@kube-master vagrant]#

```
are these commands showing valid settings :? 
further, is there any file/config which should be verified to point to 172.x.x.x IP  address range rather than 10.x.x.x.?  
as i said earlier, this is vagrant/virtualbox based infrastructure and i am using multi-machine vagrant configuration described [here ](https://www.vagrantup.com/docs/multi-machine/)
please suggest

**Comment by bboreham** [comment]
Weave Net (and any other program following standard Kubernetes conventions) picks up the address via environment variables `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`.  These are set by kubelet.

The output you show is valid, but not relevant to this particular point.

Adding a route would go something like:

    ip route add 10.96.0.0/16 dev enp0s8 src 172.28.128.4

on the worker node.

**Comment by irfanjs** [comment]
thanks. i added this command and weave net pod is now into running state. 

have couple of queries. 
- i am just wondering, the above command is just workaround OR proper fix .?
OR is this just applicable to such network, where 172 IP address range is being used rather than 10.x 

-  further, while initializing the kubernetes cluster , have used the option: `--apiserver-advertise-address`
option in the `kubeadm init` command so my understanding is that kubernetes should take the 172 IP address range for all the cluster service communication , then why it is still pointing to 10.x range ? and for that purpose , we have to use this ip route command.

**Comment by irfanjs** [comment]
thanks. we can close the issue

**Comment by mwtzzz** [comment]
I would just like to add that I had to do the `ip route add` command as well in order to get Kubernetes working with a multi node set up in Vagrant. Other things I had tried which did not work were to use the `modifyvm` option in Vagrant to try to swap the NICs (didnt' seem to actually swap them).
