### ISSUE TITLE
Metric server with weave net can't collect monitoring data from the node where his pod is placed

### ISSUE THREAD

**Issue by hshtel** [weaveworks/weave#3434]
Metric server can't collect monitoring data from the node where his pod is placed, I think it is policy or networking problem as I cant ping from the pod to its host (r2s13) while I am able to ping the other two nodes. (same result when I tested on another pod)

I am trying to figure out why Metric server isn't collecting stats from the node where his pod is placed. There are 3 nodes in my cluster (master and 2 workers)

metric server version is 0.3.1
kubernetes version is 1.12 installed with kubeadm
CNI plugin is weave net

"kubectl top node" output:
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
r2s12   344m         4%     3079Mi          12%
r2s14   67m          0%     1695Mi          21%
r2s13   <unknown>                           <unknown>               <unknown>               <unknown>

in metric server log I have the below line repeated:
E1023 15:28:14.643011       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:r2s13: unable to fetch metrics from Kubelet r2s13 (10.199.183.218): Get https://10.199.183.218:10250/stats/summary/: dial tcp 10.199.183.218:10250: i/o timeout

"netstat -a | grep 10250" output from r2s13:
tcp6       0      0 [::]:10250              [::]:*                  LISTEN
tcp6       0      0 r2s13.r2s13:10250       r2s12.r2s12:33950       ESTABLISHED

"netstat -a | grep 10250" output from inside the pod:
tcp        0      1 metrics-server-7fbd9b8589-r9nnv:60384 10.199.183.218:10250    SYN_SENT
tcp        0      0 metrics-server-7fbd9b8589-r9nnv:43876 10-199-183-217.kubernetes.default.svc.cluster.local:10250 ESTABLISHED
tcp        0      0 metrics-server-7fbd9b8589-r9nnv:45926 10.199.183.219:10250    ESTABLISHED

I do not know if the default setting of weave net npc is blocking the traffic from the pod to its hosts, or it is something else.

**Comment by brb** [comment]
@hshtel Please provide `weave` and `weave-npc` logs as requested in the issue template.

**Comment by hshtel** [comment]
here is more detailed log as you request:

** Is this a REQUEST FOR HELP? **

** Is this a BUG REPORT? **
yes

## What you expected to happen?
allow connection from inside the pod to the host where it's placed (so Metric server can collect monitoring data from the node where his pod is placed)

## What happened?

I cant get metrics from the r2s14 which is the node where Metric server pod is placed.
"kubectl top node" output:
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
r2s12   320m         4%     1869Mi          7%
r2s13   65m          0%     705Mi           5%
r2s14   <unknown>                           <unknown>               <unknown>               <unknown>

in metric server log I have the below line repeated:
unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:r2s14: unable to fetch metrics from Kubelet r2s14 (10.199.183.219): Get https://10.199.183.219:10250/stats/summary/: dial tcp 10.199.183.219:10250: i/o timeout


## Anything else we need to know?
kubeadm is used to create the cluster.
below are my nodes:
NAME         STATUS   ROLES    AGE     VERSION   INTERNAL-IP
node/r2s12   Ready    master   7d19h   v1.12.1   10.199.183.217
node/r2s13   Ready    <none>   7d19h   v1.12.1   10.199.183.218
node/r2s14   Ready    <none>   7d19h   v1.12.1   10.199.183.219

## Versions:

$ weave version
root@r2s12:~# weave version
This is WEAVE, Version 4.4 (TeX Live 2015/Debian)
weave: fatal: web file `version.web' not found.

$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false

$ kubectl version
v1.12.1

## Logs:

$ kubectl logs -n kube-system <weave-net-pod> weave

nothing special in this log it is all like below:

WARN: 2018/10/24 09:49:14.479057 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: f6:b0:8c:c6:13:40, dst: 56:41:54:56:ea:d8} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}
INFO: 2018/10/24 09:49:41.618990 Discovered remote MAC 8a:6d:19:0e:95:26 at ae:9a:41:9a:13:07(r2s13)
INFO: 2018/10/24 09:49:41.637759 Discovered remote MAC 66:eb:77:3e:83:18 at 0a:3a:30:bc:0c:e2(r2s12)
WARN: 2018/10/24 09:52:06.717484 [allocator]: Delete: no addresses for 571ccb5552b16cc8b36780d277323bf979c9604c9a82db508b1df9c2b91e9111

$ kubectl logs -n kube-system <weave-net-pod> weave-npc

nothing special in this log it is all like below:

DEBU: 2018/10/24 11:57:17.698101 EVENT DeletePod {"metadata":{"creationTimestamp":"2018-10-24T11:03:18Z","deletionGracePeriodSeconds":0,"deletionTimestamp":"2018-10-24T11:56:59Z","generateName":"coredns-745bf547c4-","labels":{"k8s-app":"kube-dns","pod-template-hash":"745bf547c4"},"name":"coredns-745bf547c4-g5v7r","namespace":"kube-system","resourceVersion":"866220","selfLink":"/api/v1/namespaces/kube-system/pods/coredns-745bf547c4-g5v7r","uid":"69b12a72-d77c-11e8-a2ac-00259e1e2b8c"},"spec":{"containers":[{"image":"k8s.gcr.io/coredns:1.2.2","imagePullPolicy":"IfNotPresent","name":"coredns","ports":[{"containerPort":53,"name":"dns","protocol":"UDP"},{"containerPort":53,"name":"dns-tcp","protocol":"TCP"},{"containerPort":9153,"name":"metrics","protocol":"TCP"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"Default","nodeName":"r2s12","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"coredns","serviceAccountName":"coredns","terminationGracePeriodSeconds":30},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2018-10-24T11:03:18Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2018-10-24T11:56:00Z","message":"containers with unready status: [coredns]","reason":"ContainersNotReady","status":"False","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2018-10-24T11:56:00Z","message":"containers with unready status: [coredns]","reason":"ContainersNotReady","status":"False","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2018-10-24T11:03:18Z","status":"True","type":"PodScheduled"}],"hostIP":"10.199.183.217","phase":"Running","podIP":"10.38.128.4","qosClass":"Burstable","startTime":"2018-10-24T11:03:18Z"}}
INFO: 2018/10/24 11:57:17.698152 deleting entry 10.38.128.4 from weave-P.B|!ZhkAr5q=XZ?3}tMBA+0 of 69b12a72-d77c-11e8-a2ac-00259e1e2b8c


## Network:

ip route from inside the pod:
/ # ip route
default via 10.40.0.2 dev eth0
10.32.0.0/12 dev eth0 scope link  src 10.40.0.26

netstat from inside the pod:
/ # netstat -a | grep 10250
tcp        0      1 metrics-server-7fbd9b8589-whstv:48430 10.199.183.219:10250    SYN_SENT
tcp        0      0 metrics-server-7fbd9b8589-whstv:56664 10.199.183.218:10250    ESTABLISHED
tcp        0      0 metrics-server-7fbd9b8589-whstv:41814 10-199-183-217.kubernetes.default.svc.cluster.local:10250 ESTABLISHED

ip route from the node where the pod deployed:
root@r2s14:~# ip route
default via 172.1.1.1 dev enp5s4f1 onlink
10.32.0.0/12 dev weave  proto kernel  scope link  src 10.40.0.2
10.199.183.192/26 dev enp5s4f0  proto kernel  scope link  src 10.199.183.219
172.1.1.0/24 dev enp5s4f1  proto kernel  scope link  src 172.1.1.3
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown

netstat from the node where the pod is deployed:
root@r2s14:~# netstat -a | grep 10250
tcp6       0      0 [::]:10250              [::]:*                  LISTEN
tcp6       0      0 r2s14.r2s14:10250       r2s12.r2s12:42440       ESTABLISHED


$ ip -4 -o addr
root@r2s14:~# ip -4 -o addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
4: enp5s4f0    inet 10.199.183.219/26 brd 10.199.183.255 scope global enp5s4f0\       valid_lft forever preferred_lft forever
5: enp5s4f1    inet 172.1.1.3/24 brd 172.1.1.255 scope global enp5s4f1\       valid_lft forever preferred_lft forever
7: docker0    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0\       valid_lft forever preferred_lft forever
10: weave    inet 10.40.0.2/12 brd 10.47.255.255 scope global weave\       valid_lft forever preferred_lft forever

**Comment by hshtel** [comment]
@brb please the issue has been updated as your request

**Comment by brb** [comment]
@hshtel which kernel version?

**Comment by hshtel** [comment]
@brb it is ubuntu 16.04

**Comment by hshtel** [comment]
@brb please your support :)
