### ISSUE TITLE
[docs] improve the k8s docs on encryption

### ISSUE THREAD

**Issue by farcaller** [weaveworks/weave#3446]
## What you expected to happen?

The [k8s docs](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/) briefly mention the `password-secret` but provide no explanation on what role it plays. If installed in a default manner, weavenet runs unencrypted and again, the consequences of that aren't immediately clear.

I would suggest to improve the documentation to
- clearly state that the default setup is not encrypted and explaining what that means, which attack scenarios weave is exposed to
- clearly state how to secure weave net

Most people tend to use the most simple configuration without bothering with options unless absolutely necessary. Being one of the major CNI plugins weavenet could do better in terms of explaining the security landscape of the default installation.

**Comment by farcaller** [comment]
I'll also note that `password-secret` sets WEAVE_PASSWORD, which is only mentioned in [this doc](https://www.weave.works/docs/net/latest/tasks/manage/security-untrusted-networks/) and it's not immediately clear if and how this applies to k8s clusters.

**Comment by bboreham** [comment]
Good observation, thanks!

Would you like to make a PR with your suggested changes?

**Comment by farcaller** [comment]
I'm not sure where's that doc in relation to your GH repo.

**Comment by bboreham** [comment]
Under https://github.com/weaveworks/weave/tree/master/site

https://github.com/weaveworks/weave/blob/master/site/kubernetes/kube-addon.md
https://github.com/weaveworks/weave/blob/master/site/tasks/manage/security-untrusted-networks.md
