### ISSUE TITLE
[Question] xtables-lock volume removed?

### ISSUE THREAD

**Issue by hiscal2015** [weaveworks/weave#3462]
Hi,

I see there's a difference below weave-daemonset-1.6/1.7/1.8.yaml and  weave-daemonset.yaml in the release page, that is, volume xtables-lock is removed in weave-daemonset.yaml. Is this necessary in Kubernetes 1.11+? Thanks.
```
                - name: xtables-lock
                  mountPath: /run/xtables.lock
```

**Comment by murali-reddy** [comment]
No its still used. There was recent change to remove just `FileOrCreate` which was causing #3351 otherwise is still in use.

Could you point me to weave-daemonset.yaml which has missing xtables-lock path mount?

**Comment by hiscal2015** [comment]
@murali-reddy 
Please check:
https://github.com/weaveworks/weave/releases/download/v2.5.0/weave-daemonset.yaml

**Comment by bboreham** [comment]
I think you’re looking at the timeline the wrong way round. The version-less file was the first one, then we added 1.7 and 1.8 versions.

**Comment by murali-reddy** [comment]
Looks like `weave-daemonset.yaml` never mounted xtables.lock path. If you use suggested [installation]( https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#install) you get manifest which loads xtables.lock path.

Not sure of historical context of  `weave-daemonset.yaml`, @bboreham why is it maintained and where it is supposed to be used?

**Comment by murali-reddy** [comment]
@hiscal2015 hope its clear now. Please reopen if you still have a doubt.
