### ISSUE TITLE
[dns] request for non-weave name can easily time out (in tests)

### ISSUE THREAD

**Issue by squaremo** [weaveworks/weave#347]
When I do

    make tests

the last test in server_test.go frequently fails. It asks for an MX record for `weave.works.`, which prompts the DNS server to use the nameserver given in /etc/resolv.conf which on my VM is `10.0.2.3`. Using `dig` I can see that this takes about 2.5 seconds; using `8.8.8.8` takes a handful of milliseconds.

**Comment by squaremo** [comment]
.. and now it is back to being about 40 ms. It would be nice to have this test work independently of crappy network conditions, but it's not the end of the world.

**Comment by rade** [comment]
I see this quite a lot.

**Comment by rade** [comment]
I haven't run into this for a while. Has something changed?

**Comment by inercia** [comment]
This has probably been fixed in #761, as the timeout for connections to upstream servers has been raised...

**Comment by rade** [comment]
> the timeout for connections to upstream servers has been raised...

from what to what?

**Comment by inercia** [comment]
The "from" depends on the moment in time: can be from 4ms (a bug) to 2 seconds. The "to" is 5 seconds, as the standard resolver in Linux....
