### ISSUE TITLE
Multicast packets circumvent app isolation

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#354]
With CoreOS out-of-the box:

```
core@core-01 ~ $ docker attach `sudo weave run 10.9.1.1/24 -ti bboreham/mcast:latest`
...
Status: Downloaded newer image for bboreham/mcast:latest
root@f7f69b63a0b7:/# 
root@f7f69b63a0b7:/# /home/mcreceive 224.2.2.4 5050
Received 3 bytes from 10.9.1.2: HI
Received 3 bytes from 10.9.2.2: HI
Received 3 bytes from 10.10.2.2: HI
Received 3 bytes from 192.168.2.2: HI
```

Now on the second machine:
```
core@core-02 ~ $ docker attach `sudo weave run 10.3.1.1/24 -ti bboreham/mcast:latest`
...
Status: Downloaded newer image for bboreham/mcast:latest
root@3fb6b80d2820:/# 
root@3fb6b80d2820:/# /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
HI
^C
root@3fb6b80d2820:/# exit
```
For some reason it didn't arrive on the first attemp, let's try again...
```
core@core-02 ~ $ docker attach `sudo weave run 10.9.1.2/24 -ti bboreham/mcast:latest`
root@711ca39b82d3:/# 
root@711ca39b82d3:/# echo HI | /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
root@711ca39b82d3:/# exit
core@core-02 ~ $ docker attach `sudo weave run 10.9.2.2/24 -ti bboreham/mcast:latest`
root@a44b9ab53823:/# echo HI | /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
root@a44b9ab53823:/# exit
core@core-02 ~ $ docker attach `sudo weave run 10.10.2.2/24 -ti bboreham/mcast:latest`
root@5e14e4888104:/# 
root@5e14e4888104:/# echo HI | /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
root@5e14e4888104:/# exit
core@core-02 ~ $ docker attach `sudo weave run 192.168.2.2/24 -ti bboreham/mcast:latest`
root@7f844a353553:/# 
root@7f844a353553:/# echo HI | /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
root@7f844a353553:/# 
```

To reproduce this, you can do:
```
git clone https://github.com/errordeveloper/weave-demos
cd weave-demos/felix; vagrant up
```
Then `vagrant ssh core-01` and `vagrant ssh core-02`.

----
Just to be sure, check `rp_fileter`:
```
$ for i in /proc/sys/net/ipv4/conf/*/rp_filter; do echo $i: `cat $i`; done
/proc/sys/net/ipv4/conf/all/rp_filter: 1
/proc/sys/net/ipv4/conf/default/rp_filter: 1
/proc/sys/net/ipv4/conf/docker0/rp_filter: 1
/proc/sys/net/ipv4/conf/dummy0/rp_filter: 1
/proc/sys/net/ipv4/conf/eth0/rp_filter: 1
/proc/sys/net/ipv4/conf/eth1/rp_filter: 1
/proc/sys/net/ipv4/conf/lo/rp_filter: 0
/proc/sys/net/ipv4/conf/veth0114561/rp_filter: 1
/proc/sys/net/ipv4/conf/veth2310286/rp_filter: 1
/proc/sys/net/ipv4/conf/veth3188b88/rp_filter: 1
/proc/sys/net/ipv4/conf/vethwepl1293/rp_filter: 1
/proc/sys/net/ipv4/conf/vethwepl1485/rp_filter: 1
/proc/sys/net/ipv4/conf/vethwepl1875/rp_filter: 1
/proc/sys/net/ipv4/conf/weave/rp_filter: 1
```
----
Let's try to run docker daemon with `--icc=false`...

If you use _weave-demos/felix_, do this
```
$ git checkout docker-icc-false
$ vagrant destroy -f ; vagrant up
```

and then back in.
```
core@core-01 ~ $ ps -ef | grep docker | grep icc
root       987     1  4 12:16 ?        00:00:12 docker --daemon --host=fd:// --insecure-registry=0.0.0.0/0 --icc=false
core@core-01 ~ $ docker attach `sudo weave run 10.9.1.1/24 -ti bboreham/mcast:latest`
...
Status: Downloaded newer image for bboreham/mcast:latest
root@3a11d59950e7:/# 
root@3a11d59950e7:/# /home/mcreceive 224.2.2.4 5050
Received 3 bytes from 10.9.1.2: HI
Received 3 bytes from 10.9.5.2: HI
Received 3 bytes from 192.168.5.2: HI

^C
root@3a11d59950e7:/# exit
```

I have repeated most of the same commands on `core-02`:
```
core@core-02 ~ $ docker attach `sudo weave run 10.9.1.2/24 -ti bboreham/mcast:latest`
root@2a43aaed4e03:/# 
root@2a43aaed4e03:/# echo HI | /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
root@2a43aaed4e03:/# exit
core@core-02 ~ $ docker attach `sudo weave run 10.9.5.2/24 -ti bboreham/mcast:latest`
root@ce66b715f7de:/# 
root@ce66b715f7de:/# echo HI | /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
root@ce66b715f7de:/# exit
core@core-02 ~ $ docker attach `sudo weave run 192.168.5.2/24 -ti bboreham/mcast:latest`
root@bca0694a2f9b:/# 
root@bca0694a2f9b:/# echo HI | /home/mcsend 224.2.2.4 5050
Begin typing (return to send, ctrl-C to quit):
root@bca0694a2f9b:/# exit
```

**Comment by dpw** [comment]
Can you check whether rp filtering is set on the ethwe interfaces in the containers? (Those are the ones with the ipv4 addresses attached, and so that where the rp filtering will occur, if anywhere.).  I.e., do:

    weave/bin/docker-ns <container id> sh -c 'for i in /proc/sys/net/ipv4/conf/*/rp_filter; do echo $i: `cat $i`; done'

with the `docker-ns` script from the weave repo.

I get (not using coreos):

    /proc/sys/net/ipv4/conf/all/rp_filter: 1
    /proc/sys/net/ipv4/conf/default/rp_filter: 1
    /proc/sys/net/ipv4/conf/eth0/rp_filter: 1
    /proc/sys/net/ipv4/conf/ethwe/rp_filter: 1
    /proc/sys/net/ipv4/conf/lo/rp_filter: 1

**Comment by rade** [comment]
FTR, @dpw was unable to reproduce this.

**Comment by dpw** [comment]
With two containers on the same machine, I can't reproduce this:  mc packets don't reach the receiver program.

The rp_filter settings on my receiving container, by default, are:

    /proc/sys/net/ipv4/conf/all/rp_filter: 1
    /proc/sys/net/ipv4/conf/default/rp_filter: 1
    /proc/sys/net/ipv4/conf/eth0/rp_filter: 1
    /proc/sys/net/ipv4/conf/ethwe/rp_filter: 1
    /proc/sys/net/ipv4/conf/lo/rp_filter: 1

Note that 1 is the strictest setting (0 is no filtering, 1 is strict filtering, 2 is loose filtering).  Also, the `all/rp_filter` setting interacts with the per-if settings in a surprising way. See the kernel docs on this at https://github.com/torvalds/linux/blob/master/Documentation/networking/ip-sysctl.txt#L989

So, as expected, if RP filtering is at its strictest setting, the receiver does not get the packets.

To confirm that RP filtering is responsible and that I haven't messed something else up, I turned it off, by setting `ethwe/rp_filter` and `all/rp_filter` to 0 for the receiving container.  And then the receiver program does see the packets.

Note that there is some odd statefulness on the receiving socket which can lead to confusion.  If I have RP filtering enabled, start the receiver program, and disabled RP filtering, it will see packets without a restart of the program.  But if RP filtering is enabled again, the program will continue to see packets! The program has to be restarted for the change to affect it.

**Comment by dpw** [comment]
I just reproduced a problem using a scenario suggested by Ilya, even with RP filtering enabled:

* Start 3 containers, let's call them A, B and C, with A and B on one subnet and C on another.

* Run the MC receiver on A and the sender on C.  As expected, A does not see packets from C.

* Run the MC sender on B.  As expected, A sees packets from B.

* But after A has received packets from B, it can now magically receive packets from C!

**Comment by errordeveloper** [comment]
FTR, here is what I was doing, it's got output of tcpdump as well: https://gist.github.com/errordeveloper/c28ebae41b6d1b7e7ced

**Comment by rade** [comment]
@errordeveloper ping

**Comment by dpw** [comment]
Out of interest, what's the plan on this?  Me and Ilya talked about reporting this to kernel developers, but even if anything comes of that, it is unlikely to have much singnificance on timescales that matter to weave.  So I'm wondering if there is something more?

**Comment by rade** [comment]
IMO we should certainly report this to the kernel devs. Let's see what that reveals about the nature of the problem and when/where any fix might appear.

**Comment by dpw** [comment]
I already have some knowledge about the nature of the problem, although no idea how to fix it.

But if we report it and some kindly kernel developer takes it seriously and develops a fix (and I wouldn't get too hopeful about that), it's usually at least 3 months until such a change will appear in a released kernel.  And then a few weeks until the bleeding edge distros pick that up.  Even in the very best case, it's a few months.

And then there are RHEL and Ubuntu LTS, where we have to treat the kernels as more or less unchanging.

So it seems to me we ought to take our own position on this issue.  Maybe we don't actually think it is very serious.  Or maybe we do consider it serious, in which case we can think about workarounds (maybe a per-subnet iptables rule to prevent reception of multicast packets from other subnets?).

I do think we should report it in any case, but that's just because I think reporting bugs in open source software is The Right Thing To Do (whatever reception they encounter).

**Comment by rade** [comment]
Where weave is right now, I reckon this issue warrants a couple of days work max. So if there is a reasonable chance of developing a workaround in that time then let's go for it.

**Comment by errordeveloper** [comment]
Just an update for those who reading this, it's [not a Weave bug][1].

[1]: https://github.com/errordeveloper/subleak

**Comment by errordeveloper** [comment]
@rade should it be retagged with `kernel-bug` or something similar? May be just removing `bug` tag would make sense..?

**Comment by rade** [comment]
I'd leave the `bug` tag. The behaviour is buggy, regardless of the cause.

**Comment by rade** [comment]
Didn't @dpw reproduce the problem [on a single machine](https://github.com/zettio/weave/issues/354#issuecomment-70691548), or am I misreading that comment?

**Comment by dpw** [comment]
> Didn't @dpw reproduce the problem on a single machine, or am I misreading that comment?

Yes, but I was still using weave and docker.  Though we might have confidence that those are not implicated when on a single machine, Ilya is trying to strip it down to the point where it can be reported to the Linux network developers with some chance of them paying attention.

**Comment by errordeveloper** [comment]
@dpw it'd be great if you could have a look at the [setup script](https://github.com/errordeveloper/subleak/blob/master/test.sh). I have based on a [ServerFault post](http://superuser.com/questions/764986/howto-setup-a-veth-virtual-network/765078#765078). It does what's needed, but I am not quite sure what exactly is the role of the tap device there...

**Comment by dpw** [comment]
> @dpw it'd be great if you could have a look at the setup script. I have based on a ServerFault post. It does what's needed, but I am not quite sure what exactly is the role of the tap device there...

Yeah, it looks a bit more complicated than I'd expect.  I'd expect you just need two netnamespaces connected to a bridge via veth pairs.   Like the instructions in https://github.com/zettio/weave/blob/master/docs/dockerless.txt , but without the third veth pair for the weave router.

**Comment by rade** [comment]
> @errordeveloper is trying to strip it down to the point where it can be reported to the Linux network developers with some chance of them paying attention.

Understood, but surely if the problem can be reproduced on a single machine, we should produce instructions - not involving docker or weave - for doing that. Currently @errordeveloper's setup appears to be using multiple vagrant VMs. I doubt that would go down well with the kernel devs.

**Comment by rade** [comment]
Oh, just looking at the instructions again, they are using just a single vagrant VM? If so that's fine. Though I suspect even that is asking a bit much, especially since the VM is based on coreos and the Vagrantfile is far from simple.

**Comment by errordeveloper** [comment]
Exactly, there is only one Vagrant VM, which is only a tool of avoiding human errors by repeated automation. My intention is to post generic instructions to the netdev list. A good reason to use CoreOS here is that it actually runs latest (or at least very recent) vanilla kernel release.

**Comment by rade** [comment]
I see. So all the vagrant stuff is really just there for convenience; the setup script + multicast send/receive invocations should reproduce the problem on most Linuxes.

I guess we'd want to find something more standard than mcsend/receive. Would iperf work? or [omping](http://linux.die.net/man/8/omping)?

**Comment by rade** [comment]
[mint](http://mc-mint.sourceforge.net/) is another one.

**Comment by errordeveloper** [comment]
@rade good point, I somehow overlooked that idea... I'll make sure to use something that few distros have packages for.

**Comment by dpw** [comment]
> I guess we'd want to find something more standard than mcsend/receive. Would iperf work? or omping?

I doubt that the Linux kernel network developers consider any of those to be standard.

If mcsend/receive are what I think they are, then they are trivial C programs, and so probably acceptable.

**Comment by rade** [comment]
@errordeveloper did you submit this to the linux kernel devs?

**Comment by errordeveloper** [comment]
[Submitted just now](http://marc.info/?l=linux-netdev&m=142771711225747&w=2).

**Comment by rade** [comment]
worth prodding?

**Comment by errordeveloper** [comment]
Probably, but for best result we should CC some folks who might have otherwise not noticed the post. Any ideas who we could CC?

**Comment by rade** [comment]
I have just tried this on a 4.2.0-35 kernel, and the behaviour is unchanged :(

**Comment by rade** [comment]
One way to prevent this is to insert a couple of rules inside the receiving containers that drop packets to the multicast destination when they are not sent from an IP in the same subnet. E.g.,

```
# ./bin/docker-ns rcv iptables -I INPUT -d 224.0.0.0/4 -j DROP
# ./bin/docker-ns rcv iptables -I INPUT -s 10.0.1.0/24 -d 224.0.0.0/4 -j ACCEPT
```

We can insert these rules in `weave attach`.

That doesn't help when using the Docker Network Plugin though :(
