### ISSUE TITLE
Can I access  weave network from external machine?

### ISSUE THREAD

**Issue by SrinivReddy** [weaveworks/weave#3571]
Hi,  I have k8s cluster with weave network,    my requirement is i want to access pod from external Vm(outside cluster). how can I achieve this???

**Comment by murali-reddy** [comment]
As you many know, what Weave network provides for pods/containers is a L2 network. If you want pod's the be accessed from outside of k8s cluster, then easy way would be run weave agent on that node and peer it with one or more nodes in the cluster. This essentially extends the overlay to the node from which  you want to access to the pods.

If you want more generic solution that works for any node out side the cluster, then you need to rely on the routing infrastructure to route the traffic to pods in-and-out of the cluster. Typically you would need some sort of routing protocols (like OSPF, BGP) to advertise routes the pods.

You may find this conversation useful. https://weave-community.slack.com/archives/C2ND76PAA/p1543526813465600
