### ISSUE TITLE
weave build is failing for ppc64le with upstream go

### ISSUE THREAD

**Issue by sudeeshjohn** [weaveworks/weave#3577]
## What you expected to happen?
Build should be successful 

## What happened?
Building weave on pp64le platform with upstream go version is failing with below error

```
<snip>
go build -i -ldflags "-linkmode external -extldflags -static -X main.version=git-294e3096c80e" -tags netgo -o prog/weaver/weaver ./prog/weaver
# github.com/weaveworks/weave/vendor/github.com/google/gopacket/pcap
vendor/github.com/google/gopacket/pcap/pcap.go:189:7: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:445:13: identifier "_Ctype_struct_pcap_stat" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:490:49: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:513:10: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:546:41: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:618:66: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:631:19: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:741:34: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:744:56: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo
Makefile:216: recipe for target 'prog/weaver/weaver' failed
make: *** [prog/weaver/weaver] Error 2
<snip>

```
## How to reproduce it?

```
on ppc64le platform build the upstream go version and set in $PATH
git clone https://github.com/weaveworks/weave.git
export BUILD_IN_CONTAINER=false
export ARCH_EXT?=
export  CC=gcc
ARCH=ppc64le make
```

## Versions:

```
root@ip:/go/src/github.com/weaveworks/weave# go version
go version devel +a1d5e8a Tue Jan 8 02:10:40 2019 +0000 linux/ppc64le
root@ip:/go/src/github.com/weaveworks/weave#

$ weave version
$ docker version
```
root@ip:/go/src/github.com/weaveworks/weave# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:26:38 2018
 OS/Arch:           linux/ppc64le
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:24:46 2018
  OS/Arch:          linux/ppc64le
  Experimental:     false
root@ip:/go/src/github.com/weaveworks/weave#
```
$ uname -a
```
root@ip:/go/src/github.com/weaveworks/weave# uname -a
Linux ip-custom #1 SMP Thu Sep 13 03:13:53 EDT 2018 ppc64le ppc64le ppc64le GNU/Linux
root@ip:/go/src/github.com/weaveworks/weave#
```
```

## Logs:
```
root@ip:/go/src/github.com/weaveworks/weave# ARCH=ppc64le make
echo "DOCKERHUB_USER|weaveworks|g;s|ARCH_EXT||g;s|ALPINE_BASEIMAGE|ppc64le/alpine:3.6|g;s|QEMUARCH|ppc64le"
DOCKERHUB_USER|weaveworks|g;s|ARCH_EXT||g;s|ALPINE_BASEIMAGE|ppc64le/alpine:3.6|g;s|QEMUARCH|ppc64le
sed -e "s|DOCKERHUB_USER|weaveworks|g;s|ARCH_EXT||g;s|ALPINE_BASEIMAGE|ppc64le/alpine:3.6|g;s|QEMUARCH|ppc64le|g" prog/weaver/Dockerfile.template > prog/weaver/Dockerfile.weaveworks
curl -sSL https://github.com/multiarch/qemu-user-static/releases/download/v2.7.0/x86_64_qemu-ppc64le-static.tar.gz | tar -xz -C prog/weaver
cd prog/weaver && sha256sum -c /go/src/github.com/weaveworks/weave/build/shasums/qemu-ppc64le-static.sha256sum
qemu-ppc64le-static: OK
sed -i.bak "s/CROSS_BUILD_//g" prog/weaver/Dockerfile.weaveworks
go build -i -ldflags "-linkmode external -extldflags -static -X main.version=git-294e3096c80e" -tags netgo -o prog/weaver/weaver ./prog/weaver
# github.com/weaveworks/weave/vendor/github.com/google/gopacket/pcap
vendor/github.com/google/gopacket/pcap/pcap.go:189:7: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:445:13: identifier "_Ctype_struct_pcap_stat" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:490:49: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:513:10: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:546:41: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:618:66: identifier "_Ctype_struct_bpf_program" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:631:19: identifier "_Ctype_struct_bpf_insn" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:741:34: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo
vendor/github.com/google/gopacket/pcap/pcap.go:744:56: identifier "_Ctype_struct_pcap_addr" may conflict with identifiers generated by cgo
Makefile:216: recipe for target 'prog/weaver/weaver' failed
make: *** [prog/weaver/weaver] Error 2
root@ip:/go/src/github.com/weaveworks/weave#
```

**Comment by mkumatag** [comment]
The errors are coming from https://github.com/golang/go/commit/5e1727892bf36076ee45c417b56bba32801ffbd7#diff-d390090e3c58a2b4a9dbe8531e63b0e7R188 merged part of https://github.com/golang/go/issues/28721

**Comment by murali-reddy** [comment]
thanks @mkumatag for pointing out. Closing the issue. Issue seems to be from `go` version used.

**Comment by sudeeshjohn** [comment]
weave will hit the issue with the future go versions. I think this should be fixed.

**Comment by mkumatag** [comment]
> weave will hit the issue with the future go versions. I think this should be fixed. the go version I used is the upstream one.

that's right, we need to find how to fix them to work fine with the latest version of golang. @murali-reddy can you please reopen this issue.?

**Comment by murali-reddy** [comment]
sorry i misread comment. From which version of go this is going to be issue @sudeeshjohn @mkumatag ?

**Comment by sudeeshjohn** [comment]
@murali-reddy from golang version 1.12 onwards . 

just putting down the steps I used 

1. cd /tmp ; mkdir go ; wget https://dl.google.com/go/go1.12beta1.linux-ppc64le.tar.gz; tar -zxvf go1.12beta1.linux-ppc64le.tar.gz; export export PATH=/tmp/go/go/bin:$PATH ; export GOPATH=/go
2. mkdir -p /go/src/github.com/weaveworks/
3. cd /go/src/github.com/weaveworks/ ; git clone https://github.com/sudeeshjohn/weave.git
4. to enable native building, change the following lines in Makefile

```
         BUILD_IN_CONTAINER=false

        CC=gcc
```

5. ARCH=ppc64le make

**Comment by mkumatag** [comment]
> 1. cd /tmp ; mkdir go ; wget https://dl.google.com/go/go1.12beta1.linux-ppc64le.tar.gz; tar -zxvf go1.12beta1.linux-ppc64le.tar.gz; export export PATH=/tmp/go/go/bin:$PATH ; export GOPATH=/go

@sudeeshjohn I hope this happens on x86 platform as well, correct me if I'm wrong..

**Comment by bboreham** [comment]
For the errors in that specific library, it looks like this is fixed in https://github.com/google/gopacket/pull/589 so we just have to update the vendor'd libs.
