### ISSUE TITLE
Random network failure on nodes

### ISSUE THREAD

**Issue by Mymetique** [weaveworks/weave#3578]
Hello, 

We are using kubernetes installed with kubeadm and weave as network overlay. Il will try to give as much details as I can and answer all your questions. I thank you very much for your help and apologize if weave is not the root of our issue but our digging implied it is related in some way.

The issue in few words : Our two clusters have randomly a complete network shortage on a random node. It is then impossible to reach pods from an other machine, talk with the kube api and so on. The node status makes a flip flop between ready and not ready sometimes, sometimes not. The result is that critical services go down sometimes in middle of the day (load) sometimes of the night (few to no load at all)

We are using kubernetes 1.12.4 and weave : docker.io/weaveworks/weave-kube:2.5.0 on arch kernel 4.20.0

We have two very simple clusters (production and staging) with the same conf and the same number of nodes. 3 nodes, 2 with normal pods and one is a kind of gateway. The gateway uses hostport (pod listening on 80 443 for instance). We also use network policies.

We read that promiscious bridge can solve some troubles so we enabled that also.

I will give you some logs we retrieved on broken nodes : 
Systemctl : 
`Jan 08 17:29:31 oc002 kernel: weave: port 29(vethwepl820462c) entered disabled state
Jan 08 17:29:31 oc002 kernel: device vethwepl820462c left promiscuous mode
Jan 08 17:29:31 oc002 kernel: weave: port 29(vethwepl820462c) entered disabled state`

Weave pod : 
`WARN: 2019/01/08 16:40:03.105041 Vetoed installation of hairpin flow FlowSpec{keys: [EthernetFlowKey{src: 66:ec:25:95:73:b3, dst: 36:16:01:fa:e8:5f} InPortFlowKey{vport: 1}], actions: [OutputAction{vport: 1}]}`

Restart of kubelet on the broken node : 
`kubelet.service: State 'stop-final-sigterm' timed out. Killing.
Jan 08 18:56:04 oc002 systemd[1]: kubelet.service: Killing process 19901 (weave-net) with signal SIGKILL.`

First few lines after kubelet restart : 
`Jan 08 22:52:42 of01 kernel: device vethweplc25cb64 entered promiscuous mode
Jan 08 22:52:42 of01 systemd-udevd[6983]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jan 08 22:52:42 of01 systemd-udevd[7071]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jan 08 22:52:42 of01 systemd-udevd[7071]: Could not generate persistent MAC address for vethweplc25cb64: No such file or directory
Jan 08 22:52:42 of01 NetworkManager[367]: <info>  [1546984362.8403] manager: (vethweplc25cb64): new Veth device (/org/freedesktop/NetworkManager/Devices/13)
Jan 08 22:52:42 of01 systemd-udevd[6983]: link_config: could not get ethtool features for vethwepgc25cb64
Jan 08 22:52:42 of01 systemd-udevd[6983]: Could not set offload features of vethwepgc25cb64: No such device
Jan 08 22:52:42 of01 kernel: eth0: renamed from vethwepgc25cb64`

/etc/cni/net.d/01-weave.conflist:
`{
    "cniVersion": "0.3.0",
    "name": "weave",
      "plugins": [
        {
            "name": "weave",
            "type": "weave-net",
            "hairpinMode": true
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }  
      ]
}
`

Sorry for the long post and thank you for your help !

**Comment by murali-reddy** [comment]
>Jan 08 22:52:42 of01 systemd-udevd[7071]: Could not generate persistent MAC address for vethweplc25cb64: No such file or directory Jan 08 22:52:42 of01 NetworkManager[367]: <info> [1546984362.8403] manager: (vethweplc25cb64): new Veth device (/org/freedesktop/NetworkManager/Devices/13)
> Jan 08 22:52:42 of01 systemd-udevd[6983]: link_config: could not get ethtool features for vethwepgc25cb64 Jan 08 22:52:42 of01 systemd-udevd[6983]: Could not set offload features of vethwepgc25cb64: No such device Jan 08 22:52:42 of01 kernel: eth0: renamed from vethwepgc25cb64

Could be related to above errors. Please try suggested workaround and see if that helps

https://github.com/systemd/systemd/issues/3374#issuecomment-339258483
https://github.com/systemd/systemd/issues/3374#issuecomment-288882355

**Comment by Mymetique** [comment]
Thank you ! We applied the workaround and will monitor if the situation is better for the next few days. We no longer have the log message you quoted. 

Do you think that is can be the cause ? I mean, even with this log at startup we managed to have a functional cluster for some time before a node breakage occurs (almost once every week). 
My understanding before the workaround is that systemd would change the mac address of a virtual interface on his own making weave inconsistent on the node. Is that right ?

**Comment by kovetskiy** [comment]
@Mymetique did it help you? I run into the same case.

**Comment by Mymetique** [comment]
Well we no longer had complete network outage since. We have very quick network unavailability (less than a minute) from time to time though . We followed the workaround only for the docker virtual interfaces if that can help .

**Comment by opslinux** [comment]
reopen it?
we have an application cause: TCP Retransmission. With tcpdump tool, have found it happend some times.
as below:

**Comment by bboreham** [comment]
@opslinux your message appears to be truncated.
This was issue was resolved on the basis that systemd network-manager was trying to manage devices that were owned by Weave Net.

If you have different symptoms please click the "new issue" button and supply the requested information.
