### ISSUE TITLE
replace homegrown testing library with something off-the-shelf

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#358]
Our [testing util](https://github.com/zettio/weave/blob/master/testing/util.go) library is growing. It's still quite small, but at some point we should probably bite the bullet and pull in something like [gocheck](http://labix.org/gocheck) or [testify](https://github.com/stretchr/testify).

**Comment by paulbellamy** [comment]
Advantage of testify is that it is a drop-in replacement for our custom testing package.

Have asked @peterbourgon if he has any opinion...

**Comment by paulbellamy** [comment]
Per f2f discussion with @rade, need to see if gocheck provides better failure stacktraces. testify just gives line-number of assertion, which makes refactoring assertions harder.

**Comment by peterbourgon** [comment]
[I fully endorse](https://www.youtube.com/watch?v=Y1-RLAl7iOI&t=14m20s) the Go philosophy of testing as summarized [in the FAQ, quote](http://golang.org/doc/faq#testing_framework),

>  [T]esting frameworks tend to develop into mini-languages of their own, with conditionals and controls and printing mechanisms, but Go already has all those capabilities; why recreate them? We'd rather write tests in Go; it's one fewer language to learn and the approach keeps the tests straightforward and easy to understand.

I suppose testify is preferable to gocheck, and either is preferable to goconvey. But (brutal honesty ahead) I don't see much value in [any of these functions](https://github.com/weaveworks/weave/blob/master/testing/util.go) and would prefer to just inline them in the relevant tests, eliminating the package altogether.

**Comment by rade** [comment]
> prefer to just inline them

Thereby turning every assertion in a three-line `if`?!?

**Comment by peterbourgon** [comment]
> Thereby turning every assertion in a three-line `if`?!?

Sure. [For example](https://github.com/go-kit/kit/blob/319c1c7129a146b541bbbaf18e2502bf32c603c5/tracing/zipkin/zipkin_test.go#L40). Neither newlines nor vertical screen space are limited resources :)

**Comment by rade** [comment]
That is gross, but I guess we'll just have to agree to disagree.

**Comment by paulbellamy** [comment]
After trying them: unlike testify, gocheck *does* give stacktraces of failures

**Comment by paulbellamy** [comment]
But, does come with a lot of other baggage. :(

**Comment by peterbourgon** [comment]
Curious: you can generate a stacktrace on demand with [debug.PrintStack](https://golang.org/pkg/runtime/debug/#PrintStack); what does integration with a testing package get you?

**Comment by paulbellamy** [comment]
It tells us which test failed, in the case where the assertion is not at the top level. e.g.

```Go
func TestSomething(t *testing.T) {
  helper(t)
}

func TestSomethingElse(t *testing.T) {
  helper(t)
}

func helper(t *testing.T) {
  t.Fatal("failure!")
}
```

**Comment by paulbellamy** [comment]
So, the options so far seem to be:
1) Use gocheck, and deal with it's baggage.
2) Just do all checks inline, with no helper functions
3) Fork testify/assert, and add stacktraces to it

Of those, I prefer 3. By inlining everything, I worry we'll end up re-inventing stuff all over the place, and end up back where we started.

**Comment by peterbourgon** [comment]
@paulbellamy what about wrapping Fatals with something that invokes [stack.Caller](https://godoc.org/gopkg.in/stack.v1#Caller)?

**Comment by paulbellamy** [comment]
@peterbourgon Do you mean like this? Or something else in mind? https://github.com/weaveworks/weave/blob/master/testing/util.go#L133

**Comment by peterbourgon** [comment]
@paulbellamy Ah, I see. Yes. I'd rename that to e.g. `FatalWithStack` but that's what I was driving at. Single-purpose wrappers like that are, I think, the best available pattern.

**Comment by paulbellamy** [comment]
@peterbourgon Right. Given that, I'd also be ok with inlining checks, and using the "XxxWithStack" variants in any helpers.
