### ISSUE TITLE
how to export sflow, netflow or ipfix from weave on kubernetes 

### ISSUE THREAD

**Issue by vistalba** [weaveworks/weave#3596]
Hi

I foud this here but nothing else:
https://github.com/weaveworks/weave/blob/master/vendor/github.com/google/gopacket/layers/sflow.go

Is there a way to export netfow, sflow or IPFIX to a collector? I can't find any documentation about this.

**Comment by murali-reddy** [comment]
@vistalba No there is no functionality to export netflow, sflow etc. What use-case you are looking at? [Weave scope](https://github.com/weaveworks/scope) can provide some of the information that you may be interested in.

**Comment by vistalba** [comment]
@murali-reddy Okay... very bad news :( I've already a collector running for other devices like esx dswitches, firewalls and so on. So it would be nice to integrate my kubernetes cluster with weave into the existing collector. 

As I see weave scope is just another collector and GUI.

**Comment by murali-reddy** [comment]
Sorry that both scope and weave-net did not fit to your needs. Closing the issue as there is no plan to support such monitoring.
