### ISSUE TITLE
use ovs as an alternative to pcap

### ISSUE THREAD

**Issue by kapilt** [weaveworks/weave#36]
ie. you just want to route the flows not process every packet in userspace.

**Comment by mffrench** [comment]
Hello weave team ! Just to say I'm interested on that topic too and I would like to know the status of this request...

Kind regards ;)

**Comment by dpw** [comment]
Using openvswitch would involve rewriting a large portion of weave, and preserving all of the functionality that weave currently provides would not be trivial.  It would also add a significant dependency to weave.

With that said, we are looking at ways to improve weave for applications that require high network throughput or low latency.  When we have something to announce, we will link to it in this issue.

**Comment by mffrench** [comment]
@dpw : thank you for this clear answer :) 

This raise my curiosity anyway. When you have some time could you give us more inputs on the difficulties you see on the openvswitch integration with weave/docker ? 

Thank you again.

Cheers

**Comment by dpw** [comment]
> This raise my curiosity anyway. When you have some time could you give us more inputs on the difficulties you see on the openvswitch integration with weave/docker ?

Openvswitch integration with docker is quite a different matter from openvswitch integration with weave.  There are no particular difficulties in integrating openvswitch with docker.  Indeed, the openvswitch repository contains a shell script to provide a simple form of integration with docker.

But when we consider how to evolve weave, we'd like to retain the existing functionality and ease of use.  Of particular note are features like:

* Firewall traversal

* Encryption

* Good support for Path MTU discovery on the overlay network, without requiring careful setting of MTUs on the overlay and/or underlay networks.

So in general, weave aims to work well even when the underlying network presents difficulties.  This is not the traditional domain of openvswitch, which tends to assume that the users are network administrators who have a high degree of control of the underlying network environment.  So there's a gap there that we would have to bridge.

And there is the less fundamental but significant issue that integrating weave hand openstack would involve a lot of development effort.

**Comment by rade** [comment]
> we are looking at ways to improve weave for applications that require high network throughput or low latency. When we have something to announce, we will link to it in this issue.

http://blog.weave.works/2015/06/12/weave-fast-datapath/

**Comment by rade** [comment]
Fixed by #1438.
