### ISSUE TITLE
allocator should broadcast updated ring after donating space

### ISSUE THREAD

**Issue by murali-reddy** [weaveworks/weave#3628]
## What you expected to happen?

When a node donates tokens to peers, it is expected to reflect the updated ring across the nodes in the cluster.

## What happened?

It is noticed that other peers occasionally does not see updated tokens in the ring and continue to see the token as owned by previous donor owner. It is observed delay could be in the order of minutes.

During this window of time its possible a conflicting operation can be performed leaving the ring in inconsistent state.

When debugging #3444 I found the root cause to be this issue. 

## How to reproduce it?

Just keep repeating `kubectl delete` a node then rejoin the node to the cluster, you will see updated ring on the node which donated the range, but occasionally rest of the nodes would see updated ring after long delay.

**Comment by rade** [comment]
> During this window of time its possible a conflicting operation can be performed leaving the ring in inconsistent state.

Please list a sequence of steps that results in an inconsistency.

**Comment by murali-reddy** [comment]
> Please list a sequence of steps that results in an inconsistency.

Not a best example but the scenario seen in https://github.com/weaveworks/weave/issues/3444 is like below:
- node C joins a cluster with node A and node B
- node B donates a range to node C and updates ring locally
- node A does not get updated view of ring (this only occasionally happens)
- node C is deleted from the cluster
- `weave rmpeer` is performed on the node A
- node A performs transfer, but in its view it does not have any entries owned by node C resulting in 0 ip's getting reclaimed

**Comment by murali-reddy** [comment]
Brayn shared below examples offline

- A owns 10, B owns 20, C owns 30
- B donates 20 to C
- A owns 10, C owns 20,30
- A still thinks B owns 20
- B is deleted
- A does rmpeer B
- A owns 10,20, C owns 20,30

another example

- A owns 10, B owns 20,25, C owns 30
- B donates 25 to C
- A owns 10, B owns 20, C owns 25,30
- A still thinks B owns 20,25
- B is deleted
- A does rmpeer B
- A owns 10,20,25, C owns 25,30

**Comment by murali-reddy** [comment]
Brayn shared below examples offline

- A owns 10, B owns 20, C owns 30
- B donates 20 to C
- A owns 10, C owns 20,30
- A still thinks B owns 20
- B is deleted
- A does rmpeer B
- A owns 10,20, C owns 20,30

another example

- A owns 10, B owns 20,25, C owns 30
- B donates 25 to C
- A owns 10, B owns 20, C owns 25,30
- A still thinks B owns 20,25
- B is deleted
- A does rmpeer B
- A owns 10,20,25, C owns 25,30
