### ISSUE TITLE
kubectl version returns json string

### ISSUE THREAD

**Issue by utdrmac** [weaveworks/weave#3631]
## What you expected to happen?
Following the documentation here:
 https://www.weave.works/docs/net/latest/kubernetes/kube-addon/

it says to run this command:
`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"`

But that doesn't work. If you run `kubectl version | base64 | tr -d '\n'` by itself, you get this:
Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxNCIsIEdpdFZlcnNpb246InYxLjE0LjEiLCBHaXRDb21taXQ6ImI3Mzk0MTAyZDZlZjc3ODAxN2YyY2E0MDQ2YWJiYWEyM2I4OGMyOTAiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE5LTA0LTA4VDE3OjExOjMxWiIsIEdvVmVyc2lvbjoiZ28xLjEyLjEiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjE0IiwgR2l0VmVyc2lvbjoidjEuMTQuMSIsIEdpdENvbW1pdDoiYjczOTQxMDJkNmVmNzc4MDE3ZjJjYTQwNDZhYmJhYTIzYjg4YzI5MCIsIEdpdFRyZWVTdGF0ZToiY2xlYW4iLCBCdWlsZERhdGU6IjIwMTktMDQtMDhUMTc6MDI6NThaIiwgR29WZXJzaW9uOiJnbzEuMTIuMSIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==

If you run just `kubectl version` you get this:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?
see above

## How to reproduce it?
see above

## Versions:

```
$ docker version
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:34:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:04:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false

Linux k8s-master 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by utdrmac** [comment]
Attempting manual install by specifying version in URL seems to "fail" as well, as the URL backports me to 1.10 even though I'm on 1.14

```
$ curl https://cloud.weave.works/k8s/v1.14/net.yaml
code: Redirect
message: >-
  Moved permanently to `/k8s/v1.10/net.yaml`, assuming Kubernetes version is
  "v1.10", old location (`/k8s/v1.14/net.yaml`) will be deprecated soon. If you
  are using `curl`, you can pass `--location`, but it is best to just use the
  new URL.
```

**Comment by murali-reddy** [comment]
>it says to run this command:
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

>But that doesn't work

Can you please elaborate what issue you ran into?

**Comment by utdrmac** [comment]
I'm confused by your question. In the first box on this issue, I stated that I was trying to follow the instructions on your website for adding Weave to K8S. I copied the command from the documentation, pasted it into my terminal, and I did not receive the correct output.

**Comment by utdrmac** [comment]
Do you also see in my 2nd comment box where weave.works is not detecting the correct version of K8S that I have installed?

**Comment by bboreham** [comment]
That message is misleading and  confusing; it should be rewritten.  However what it is telling you, that a redirect is required, is valid.

If you run `curl --location` instead it will do the redirect and not bother you with the message.

**Comment by bboreham** [comment]
BTW we still don't know what "doesn't work" means from your original report.  
You have pointed out that running some different commands have different results; if you could supply the error message or other symptoms relating to "doesn't work" that may be helpful.

**Comment by utdrmac** [comment]
Ok. Take a look at the documentation. It says run the command with this URL:
`https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')`
Break that apart. Run just this `kubectl version | base64 | tr -d '\n'` This is a string which is 656 characters long. Is that string is the proper parameter to the `net?k8s-version=` aspect of the URL? If so, well OK, that's just odd to me as a web developer. Additionally, that URL returns/assumes I'm on k8s 1.10, which I'm not. That was the other reasoning for "doesn't work" since my version is 1.14 and I'm receiving the yaml for 1.10.

**Comment by bboreham** [comment]
Yes, that's the way it is designed.

We want to serve different config for different versions of Kubernetes.
A way to get the version of Kubernetes, that anyone running this install can do without any further downloads, is to run `kubectl version`
The output of this command may include special characters, so we base64-encode the whole lot.
`kubectl version` includes a lot of information we don't need, hence the result is quite long as you have observed.

I notice `kubectl version` has an option `--short` which would ease this pain. I don't know when that was added.

**Comment by utdrmac** [comment]
Alrighty. I stand educated. Other than getting wrong version, I guess this is OK. I've absolutely never ever used K8S before, and this is all brand-spanking new to me. Thanks!
