### ISSUE TITLE
[dns] idiomatic support for containers with more than one name

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#364]
With weavedns one can create multiple DNS records for containers - with PUTs on the weavedns HTTP API. There are a few problems with that...

1. Adding the records requires peeking under the hood of weavedns, i.e. there is no corresponding weave or docker command.

2. The extra records do not survive a weavedns restart, since, unlike the hostname, the information is not part of the container's metadata and weavedns does not itself persist any data.

3. weavdns only deals in A records; whereas for some use cases CNAMEs would be more appropriate.

Related to #226.

**Comment by inercia** [comment]
Any suggestion on how to solve the second issue? Do you suggest to add some persistence mechanism to WeaveDNS?

**Comment by rade** [comment]
>  Do you suggest to add some persistence mechanism to WeaveDNS?

No! https://github.com/docker/docker/pull/9013 would offer a solution.

**Comment by inercia** [comment]
I presumed you were not suggesting that... :) 

So I guess this issue is blocked until docker/docker#9013 is solved...

**Comment by rade** [comment]
I've captured points 2 and 3 in #635 and #636, respectively.
