### ISSUE TITLE
steps for how to use weave-wiper script in kubernetes cluster.

### ISSUE THREAD

**Issue by kasim457** [weaveworks/weave#3640]
Hi Team, 

As I have been experiencing IP leakage issue in k8s 1.12.2 & 1.13.2 clusters very frequently.  I found someone created a script called wiper.bash to release unused IP's in k8s.  I did not find steps how to use it in order to release unused IPs. 

I cloned the git clone https://github.com/ocadotechnology/weave-wiper.git and executed "sh wiper.bash".  However, I ended up with below error message.

[root@ip-172-31-0-133 weave-wiper]# sh wiper.bash
wiper.bash: line 97: `T_ids_wrong_files_validation_containers-json': not a valid identifier
[root@ip-172-31-0-133 weave-wiper]#

Could you help me how to use it in kubernetes clsuter.

**Comment by murali-reddy** [comment]
@kasim457 Closing the bug as per slack discussion to open a issue in weave-wiper repo.
