### ISSUE TITLE
Multiple issues in weave-net (kubernetes cni)

### ISSUE THREAD

**Issue by monicagangwar** [weaveworks/weave#3656]
I'm using weave version 2.5.2 on kubernetes version 1.11.10. I've been seeing these errors in weave frequently in every hour. There are a lot of connection issues while external calls from pods. I'm unable to troubleshoot these issues. Can anyone help me understand what these errors mean and how can i remove them. 
Also I'd like to understand how can I tune my MTU settings. There are multiple network interfaces in my host. How do I decide whose MTU value should be equivalent to that of weave. Would really appreciate any documentation or pointers on this.  Our prod performance is really taking a hit. Would want to eliminate weave as an issue if the logs are misleading and get to the real root of the problem
```
INFO: 2019/07/04 07:23:33.520512 EMSGSIZE on send, expecting PMTU update (IP packet was 60028 bytes, payload was 60020 bytes)
INFO: 2019/07/04 06:52:56.549384 sleeve ->[10.11.3.170:6783|ee:10:f8:5f:7a:b0(ip-10-11-3-170.ap-southeast-1.compute.internal)]: Effective MTU verified at 8939
INFO: 2019/07/04 07:30:13.986939 ->[10.11.3.24:6783|8e:4a:6b:b5:b5:e0(ip-10-11-3-24.ap-southeast-1.compute.internal)]: connection shutting down due to error: cannot connect to ourself
INFO: 2019/07/04 07:20:25.694554 ->[10.11.4.147:6783] error during connection attempt: dial tcp4 :0->10.11.4.147:6783: connect: connection refused
INFO: 2019/07/04 07:22:47.667506 ->[10.11.4.147:6783] error during connection attempt: dial tcp4 :0->10.11.4.147:6783: connect: connection timed out
INFO: 2019/07/04 07:23:32.962780 ->[10.11.4.124:6783|be:25:ec:67:b2:53(ip-10-11-4-124.ap-southeast-1.compute.internal)]: connection shutting down due to error: Multiple connections to be:25:ec:67:b2:53(ip-10-11-4-124.ap-southeast-1.compute.internal) added to 8e:4a:6b:b5:b5:e0(ip-10-11-3-24.ap-southeast-1.compute.internal)
```

weave status
```
Use 'kubectl describe pod/weave-net-s7fhk -n kube-system' to see all of the containers in this pod.
/home/weave # ./weave --local status

        Version: 2.5.2 (up to date; next check at 2019/07/04 13:56:41)

        Service: router
       Protocol: weave 1..2
           Name: 8e:4a:6b:b5:b5:e0(ip-10-11-3-24.ap-southeast-1.compute.internal)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 54
    Connections: 54 (53 established, 1 failed)
          Peers: 54 (with 2862 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 100.96.0.0/11
  DefaultSubnet: 100.96.0.0/11
```
weave connections status 
```
/home/weave # ./weave --local status connections
<- 10.11.3.186:42093     established fastdp de:4e:e2:52:09:5e(ip-10-11-3-186.ap-southeast-1.compute.internal) mtu=8912
-> 10.11.3.199:6783      established fastdp 2e:07:5a:86:47:db(ip-10-11-3-199.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.4.242:16539     established fastdp 4e:57:b6:df:bf:2e(ip-10-11-4-242.ap-southeast-1.compute.internal) mtu=8912
-> 10.11.3.193:6783      established fastdp 7a:00:13:3d:7f:37(ip-10-11-3-193.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.4.76:55588      established fastdp f6:45:18:0f:2f:9b(ip-10-11-4-76.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.3.177:37937     established fastdp be:78:1e:60:68:c6(ip-10-11-3-177.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.4.116:20028     established fastdp 7e:d4:ca:29:3d:b6(ip-10-11-4-116.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.4.96:47457      established fastdp 6e:40:11:fd:69:b7(ip-10-11-4-96.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.3.137:63090     established fastdp 7a:34:9d:f6:4a:92(ip-10-11-3-137.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.3.139:17730     established fastdp 06:3c:c0:54:34:bc(ip-10-11-3-139.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.4.225:18892     established fastdp ca:00:4e:48:ed:7c(ip-10-11-4-225.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.3.197:58850     established fastdp c6:45:7e:43:1e:06(ip-10-11-3-197.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.4.103:43112     established fastdp ca:ff:3f:f2:d5:c2(ip-10-11-4-103.ap-southeast-1.compute.internal) mtu=8912
<- 10.11.3.142:18248     established fastdp 62:27:64:05:d2:8a(ip-10-11-3-142.ap-southeast-1.compute.internal) mtu=8912
```

**Comment by mars64** [comment]
Re: connectivity issues, please see my comment #3619: https://github.com/weaveworks/weave/issues/3619#issuecomment-510569366

**Comment by murali-reddy** [comment]
> There are a lot of connection issues while external calls from pods.  I'm unable to troubleshoot these issues.

@monicagangwar please provide the details on the symptoms or nature of issues you are seeing. Its hard to help with a generalized description.

> connection shutting down due to error: cannot connect to ourself

You can ignore this error. Weave running on each Kubernetes node connectes to rest of the nodes in the cluster. As error indicates its rejecting the connection to self.

> connection shutting down due to error: Multiple connections

This could just be a trasient error. eventually all nodes can end up fully connected. Your `weave --local status connections` indicates all peers are connected.

> Also I'd like to understand how can I tune my MTU settings. 

MTU tuning is only needed for better performance. Should not result in any connection loss etc. Is this cluster a `kops` provisioned cluster? In which case it should have set to 8192.

You can find documentation https://www.weave.works/docs/net/latest/tasks/manage/fastdp/#packet-size-mtu

**Comment by monicagangwar** [comment]
@murali-reddy thanks for clearing my doubts. Will update the comment  after debugging more for connection issues

**Comment by KrishnaKoppineni** [comment]
@monicagangwar Hii Monica
Is this resolved or not?
1). I am facing the same issue. Suddenly my pods are not able to communicate mongoDB running on another host......But i am telnet from the server.
2) After restarting the weavenet pod......application pods are able to connect the mongodb

K8s version: 1.15
Weavnet Version: 2.5.2
A simple kubernetes cluster with single node(Master) acts as a worker as well.......


Can anyone please help me to resolve the issue. Thank you

**Comment by bboreham** [comment]
@KrishnaKoppineni please open a new issue and supply the details requested.

I'll close this because everything that was specifically described was answered.
