### ISSUE TITLE
Update the API for DaemonSet

### ISSUE THREAD

**Issue by Pensu** [weaveworks/weave#3658]
The extensions/v1beta1 API has been deprecated for DaemonSet. Hence, the command:

```
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

throws the error:

```
error: unable to recognise no matches for kind "DaemonSet" in version "extensions/v1beta1"
```

Please update the DaemonSet API to apps/v1.

**Comment by getvivekv** [comment]
I see that this is resolved and a new ci/cd build has been created. But I've just tried to deploy a fresh k8s server and attempted to install weave and I get this error. Is there anything else that I should in order to get the update?

**Comment by bboreham** [comment]
The file in this repo has been updated; the service at cloud.weave.works has not.

**Comment by bboreham** [comment]
For test purposes you can use our staging server, which has the updated code:

    kubectl apply -f "https://frontend.dev.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

**Comment by bboreham** [comment]
cloud.weave.works should be fixed now.
