### ISSUE TITLE
coredns pending issue while installing K8 single node.

### ISSUE THREAD

**Issue by wnagesh** [weaveworks/weave#3661]
Hi all, 
 I am trying to install kubernetes on ubuntu 18.04 on my laptop,
after hitting 

`kubectl get pods --all-namespaces` 
 
I'm getting ,

`NAMESPACE     NAME                               READY   STATUS             RESTARTS   AGE
default       new                                0/1     Pending            0          12m
kube-system   coredns-54ff9cd656-228wd           0/1     Pending            0          16m
kube-system   coredns-54ff9cd656-tb6hv           0/1     Pending            0          16m
kube-system   etcd-roothost                      1/1     Running            0          15m
kube-system   kube-apiserver-roothost            1/1     Running            1          15m
kube-system   kube-controller-manager-roothost   1/1     Running            1          15m
kube-system   kube-proxy-kmgg4                   1/1     Running            0          16m
kube-system   kube-scheduler-roothost            1/1     Running            1          15m
kube-system   weave-net-xwgg5                    1/2     ImagePullBackOff   0          8m6s
`

the core DNS is always stays in pending mode while weave gives  **"ImagePullBackOff"** and then gives **ErrImagePull**.

I have used 

`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"`
  to setup the weave.

Thank you!
Versions:

```
$ docker version
    Client: Docker Engine - Community
 Version:           19.03.0-rc3
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        27fcb77
 Built:             Thu Jun 20 02:02:20 2019
 OS/Arch:           linux/amd64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8", GitCommit:"0c6d31a99f81476dfc9871ba3cf3f597bec29b58", GitTreeState:"clean", BuildDate:"2019-07-08T08:38:54Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

Logs:

kubectl describe pod weave-net-xwgg5 -n kube-system
Name:           weave-net-xwgg5
Namespace:      kube-system
Priority:       0
Node:           roothost/192.168.100.101
Start Time:     Tue, 16 Jul 2019 16:17:55 +0530
Labels:         controller-revision-hash=596687fd4
                name=weave-net
                pod-template-generation=1
Annotations:    <none>
Status:         Pending
IP:             192.168.100.101
Controlled By:  DaemonSet/weave-net
Containers:
  weave:
    Container ID:  
    Image:         docker.io/weaveworks/weave-kube:2.5.2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /home/weave/launch.sh
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
    Readiness:  http-get http://127.0.0.1:6784/status delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      HOSTNAME:   (v1:spec.nodeName)
    Mounts:
      /host/etc from cni-conf (rw)
      /host/home from cni-bin2 (rw)
      /host/opt from cni-bin (rw)
      /host/var/lib/dbus from dbus (rw)
      /lib/modules from lib-modules (rw)
      /run/xtables.lock from xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from weave-net-token-xdnmb (ro)
      /weavedb from weavedb (rw)
  weave-npc:
    Container ID:   docker://d5387c2bf3006dfc1b57303dcdb8a5ad546346fa52b3bfe2690e825d8aeb700d
    Image:          docker.io/weaveworks/weave-npc:2.5.2
    Image ID:       docker-pullable://weaveworks/weave-npc@sha256:56c93a359d54107558720a2859b83cb28a31c70c82a1aaa3dc4704e6c62e3b15
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 16 Jul 2019 16:18:25 +0530
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:  10m
    Environment:
      HOSTNAME:   (v1:spec.nodeName)
    Mounts:
      /run/xtables.lock from xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from weave-net-token-xdnmb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  weavedb:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/weave
    HostPathType:  
  cni-bin:
    Type:          HostPath (bare host directory volume)
    Path:          /opt
    HostPathType:  
  cni-bin2:
    Type:          HostPath (bare host directory volume)
    Path:          /home
    HostPathType:  
  cni-conf:
    Type:          HostPath (bare host directory volume)
    Path:          /etc
    HostPathType:  
  dbus:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/dbus
    HostPathType:  
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  weave-net-token-xdnmb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  weave-net-token-xdnmb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  77s                default-scheduler  Successfully assigned kube-system/weave-net-xwgg5 to roothost
  Warning  Failed     50s                kubelet, roothost  Failed to pull image "docker.io/weaveworks/weave-kube:2.5.2": rpc error: code = Unknown desc = error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/f0/f04a043bb67a04b734d620e886b183b85a89271bede603004787f945537e5f4b/data?verify=1563277091-74kbRpgQeaZPnw3XfnWKa3IWuQA%3D: dial tcp: lookup production.cloudflare.docker.com: no such host
  Warning  Failed     50s                kubelet, roothost  Error: ErrImagePull
  Normal   Pulled     50s                kubelet, roothost  Container image "docker.io/weaveworks/weave-npc:2.5.2" already present on machine
  Normal   Created    48s                kubelet, roothost  Created container
  Normal   Started    46s                kubelet, roothost  Started container
  Normal   BackOff    45s (x2 over 46s)  kubelet, roothost  Back-off pulling image "docker.io/weaveworks/weave-kube:2.5.2"
  Warning  Failed     45s (x2 over 46s)  kubelet, roothost  Error: ImagePullBackOff
  Normal   Pulling    33s (x2 over 74s)  kubelet, roothost  pulling image "docker.io/weaveworks/weave-kube:2.5.2"

**Comment by nageshwaghmare** [comment]
nagesh@roothost:~/Data/v3/post-user-creation$ kubectl get pods --all-namespaces
NAMESPACE     NAME                               READY   STATUS             RESTARTS   AGE
default       new                                0/1     Pending            0          12m
kube-system   coredns-54ff9cd656-228wd           0/1     Pending            0          16m
kube-system   coredns-54ff9cd656-tb6hv           0/1     Pending            0          16m
kube-system   etcd-roothost                      1/1     Running            0          15m
kube-system   kube-apiserver-roothost            1/1     Running            1          15m
kube-system   kube-controller-manager-roothost   1/1     Running            1          15m
kube-system   kube-proxy-kmgg4                   1/1     Running            0          16m
kube-system   kube-scheduler-roothost            1/1     Running            1          15m
