### ISSUE TITLE
Sock-shop front end IP time out

### ISSUE THREAD

**Issue by alex-rebo** [weaveworks/weave#3678]
Hello all, this is my first post and I'm afraid maybe this is not the right way to post my problem so apologies if I did it on the wrong way.

I am playing a bit with kubernetes to learn about it, my cluster is made of 1 master and 4 slaves,  I have installed weave-net as pod networking and configured the sock-shop which apparently all went good, however, when I try to load the front end webpage by using the 10.107.131.153:30001 I am not able to get it, the browser just try but after a while times out.

>here are the fw status:
kubernets@master2-node:~$ sudo ufw status verbose
Status: inactive

> here are my pods :
kubernets@master2-node:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
default       avise-defaultgroup-87pws                   0/1     Pending   0          6d22h
default       avise-defaultgroup-9t6sk                   1/1     Running   1          29d
default       avise-defaultgroup-frwpk                   0/1     Pending   0          6d22h
default       avise-defaultgroup-h77t6                   1/1     Running   1          29d
default       avise-defaultgroup-kk4rl                   1/1     Running   1          29d
default       curl-66bdcf564-9fxsj                       1/1     Running   2          42d
default       my-nginx-bd8b44fcd-6r9qp                   1/1     Running   1          42d
kube-system   calico-kube-controllers-8646dd497f-q2xsc   1/1     Running   1          49d
kube-system   calico-node-4t8m7                          1/1     Running   5816       49d
kube-system   calico-node-jz747                          1/1     Running   0          6d22h
kube-system   calico-node-lxqwz                          1/1     Running   0          6d22h
kube-system   calico-node-qt6zd                          0/1     Running   1          46d
kube-system   calico-node-sfzd2                          1/1     Running   5810       49d
kube-system   coredns-fb8b8dccf-4sltp                    1/1     Running   1          49d
kube-system   coredns-fb8b8dccf-xkp6r                    1/1     Running   1          49d
kube-system   etcd-master2-node                          1/1     Running   2          49d
kube-system   kube-apiserver-master2-node                1/1     Running   2          49d
kube-system   kube-controller-manager-master2-node       1/1     Running   1          49d
kube-system   kube-proxy-44mkp                           1/1     Running   0          6d22h
kube-system   kube-proxy-978sb                           1/1     Running   1          49d
kube-system   kube-proxy-tl6jx                           1/1     Running   2          46d
kube-system   kube-proxy-wczrp                           1/1     Running   0          6d22h
kube-system   kube-proxy-xfk2q                           1/1     Running   2          49d
kube-system   kube-scheduler-master2-node                1/1     Running   2          49d
kube-system   weave-net-hdc82                            2/2     Running   0          18h
kube-system   weave-net-jqlr4                            2/2     Running   0          18h
kube-system   weave-net-pgdrl                            2/2     Running   0          18h
kube-system   weave-net-r67q9                            2/2     Running   0          18h
kube-system   weave-net-rft28                            2/2     Running   0          18h
sock-shop     carts-d646975bf-jdf8g                      1/1     Running   0          17h
sock-shop     carts-db-f5677f464-qx584                   1/1     Running   0          17h
sock-shop     catalogue-7db746bc5b-c7b4p                 1/1     Running   0          17h
sock-shop     catalogue-db-55965799b9-g8xkg              1/1     Running   0          17h
sock-shop     front-end-55b99f8c59-9942x                 1/1     Running   0          17h
sock-shop     orders-986494c98-f5bd9                     1/1     Running   0          17h
sock-shop     orders-db-78568b65bb-dj9px                 1/1     Running   0          17h
sock-shop     payment-7d4d4bf9b4-97h6m                   1/1     Running   0          17h
sock-shop     queue-master-6b5b5c7658-9gjhh              1/1     Running   0          17h
sock-shop     rabbitmq-f984b75c4-5l4cp                   1/1     Running   0          17h
sock-shop     shipping-7b8865d964-cfrcm                  1/1     Running   0          17h
sock-shop     user-54555fbb7-nnzjn                       1/1     Running   0          17h
sock-shop     user-db-7b9846c559-gjvqz                   1/1     Running   0          17h

>here is the service I am trying
kubernets@master2-node:~$ kubectl -n sock-shop get svc front-end
NAME        TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
front-end   NodePort   10.107.131.153   <none>        80:30001/TCP   5m50s

I am not able to ping the IP neither wget it, but I tried the cluster IP I have for nginx svc and worked and that subnet is not either in my routing table so, I think the lack of connectivity is not an issue...

kubernets@master2-node:~$ wget 10.107.131.153:30001
--2019-07-31 22:13:54--  http://10.107.131.153:30001/
Connecting to 10.107.131.153:30001... ^C

kubernets@master2-node:~$ kubectl -n default get svc my-nginx
NAME       TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
my-nginx   NodePort   10.103.74.203   <none>        8080:31134/TCP   43d

kubernets@master2-node:~$ wget 10.103.74.203:8080
--2019-07-31 22:10:37--  http://10.103.74.203:8080/
Connecting to 10.103.74.203:8080... connected.
HTTP request sent, awaiting response... 200 OK

>This is my routing table
kubernets@master2-node:~$ ip route
default via 10.102.10.1 dev enp4s0f1 proto static
10.32.0.0/12 dev weave proto kernel scope link src 10.34.0.0
10.102.10.0/24 dev enp4s0f1 proto kernel scope link src 10.102.10.61
blackhole 10.255.112.192/26 proto bird
10.255.112.206 dev cali86a06ee0356 scope link
10.255.112.207 dev cali3429827543d scope link
10.255.112.208 dev calia521bde45f0 scope link
10.255.112.209 dev cali6351b48434d scope link
10.255.112.219 dev cali93cb4ed0a73 scope link
10.255.112.220 dev cali275f2ab9de7 scope link
10.255.112.221 dev cali0303e6f856c scope link
10.255.112.222 dev cali4644d65ce61 scope link
10.255.112.223 dev cali9151d80c571 scope link
10.255.243.64/26 via 10.44.0.0 dev tunl0 proto bird onlink
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev bravi proto kernel scope link src 172.18.0.1

I found a post that looks pretty similar to my issue, this is https://github.com/kubernetes/kubernetes/issues/49458  which is closed now, but does not mention how was fixed except "Current version of docs works as expected, thanks", I looked in docs but didnt find any document that could help ... so, here I am asking for your help... I'll appreciate any clue or idea on how to fix my problem. 
thanks in advance. Alex.

**Comment by alex-rebo** [comment]
hello all,
I have an update ... I am able now to access the frontpage by http://localhost:30001 or by http://clusterIP:30001 (I didn't do any new change), however some interaction between the pods seems is failing since first I am not able to load correctly the main image in the front end page (however if I right click in the blank space I can download that picture that I can't see in the webpage) and second, I can't logging by using user/password or user1/password which according to https://microservices- demo.github.io/docs/user-accounts.html are valid credentials.  it takes a long long long time to process the user validation to finally give me an invalid credentials message ... personally I think that is more a time out than an a username error ... any help is highly appreciated. 
thanks all. alex.

**Comment by murali-reddy** [comment]
@alex-rebo its hard to figure what could be the problem you are running into with broader description of the problem. Just so you know there are many components at play here, Kubernetes ingress, service proxy and Waeve-net acting as CNI.

> some interaction between the pods seems is failing since first I am not able to load correctly the main image in the front end page (however if I right click in the blank space I can download that picture that I can't see in the webpage) 

Please narrow down the issue further. First check if you have proper pod-to-pod connectivity across the pods.  If you have problem with basic pod-to-pod connectivity then go through this guide https://www.weave.works/docs/net/latest/troubleshooting/ and share the necessary details that can help trouble shoot.

If you suspect the problem is with service proxy then follow this guide https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by oumkale** [comment]
Hello @bboreham @murali-reddy ,
The front-end pod is crashing again and again during catalogue pod delete?
Liveness: http-get http://:8079/ delay=300s timeout=1s period=3s #success=1 #failure=3
Readiness: http-get http://:8079/ delay=30s timeout=1s period=3s #success=1 #failure=3

Connection refused

**Comment by bboreham** [comment]
@oumkale your description does not seem to relate to anything in this repo.
Sock Shop lives under https://github.com/microservices-demo

**Comment by oumkale** [comment]
@bboreham, I am having same issue like @alex-rebo, Sock-shop front end IP time out
