### ISSUE TITLE
Is there any firewall for Weave Network ?

### ISSUE THREAD

**Issue by dapapko** [weaveworks/weave#3681]
Hello. I know that it is possible to isolate containers from each other by creating multiple Weave networks. But I want to isolate some containers which share the same network. I have a large amount of containers situated in different hosts. What should I do to do it? I need something like Kubernetes Network Policy, but I don't use Kubernetes and I'm not going to use it.

**Comment by bboreham** [comment]
There is nothing firewall-like in Weave Net apart from Kubernetes Network Policy, but you could consider using multiple subnets as described [here](https://www.weave.works/docs/net/latest/tasks/manage/application-isolation/)

**Comment by murali-reddy** [comment]
Please reopen or reach us on slack if you need further information.
