### ISSUE TITLE
weave multicast 

### ISSUE THREAD

**Issue by nyrank** [weaveworks/weave#3699]
is there any weave multicast setup guide or instructions for newbie

**Comment by bboreham** [comment]
There is nothing extra to set up - multicast always works from interfaces connected to the Weave network. 

You do need some software that is expecting to send and receive multicast packets. Do you have that already?

**Comment by murali-reddy** [comment]
Please ask on the slack or reopen if you still need any info.

**Comment by yogeshVU** [comment]
How to test that the multi-casting is working? Any ideas?

**Comment by murali-reddy** [comment]
@yogeshVU multicast is enabled by default, so testing your multicast app will be no different in when run as container. 

If you want to quickly try `kubectl run weave-multicast-test --image=muralireddy/multicasttest --replicas=3` container runs simple test app https://gist.github.com/murali-reddy/e708f98833e89d637b3e616fa279561a

**Comment by yogeshVU** [comment]
Hi @murali-reddy  Thanks for the app. Will test it out. Though I am having an application in which
I can run  the multicast when working on a  single host, but when they are working on different
host multicasting is not working. I  am  using the V2 plugin for docker swarm. Does one need to 
also update the iptable on the host machine?

``` 
sudo iptables -P FORWARD ACCEPT
```
