### ISSUE TITLE
post some benchmarks

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#37]
We should post some performance benchmarks, comparing communication over the weave network with alternative ways containers on multiple hosts can be made to talk to each other, e.g. over exposed ports that have been made accessible by the respective firewalls.

**Comment by neurogenesis** [comment]
http://www.generictestdomain.net/docker/weave/networking/stupidity/2015/04/05/weave-is-kinda-slow/

**Comment by bboreham** [comment]
http://blog.weave.works/2015/06/12/weave-fast-datapath/

**Comment by neurogenesis** [comment]
@bboreham, wow. great to see the performance improvements!

**Comment by bboreham** [comment]
Closing with http://blog.weave.works/2015/11/13/weave-docker-networking-performance-fast-data-path/
