### ISSUE TITLE
Cannot create Weavenet daemonset on 1.16

### ISSUE THREAD

**Issue by lucj** [weaveworks/weave#3700]
## What you expected to happen?

Creation of the Weavenet daemonset on a 1.16 Kubernetes cluster

## What happened?

The weavenet daemonset cannot be deployed. The following error is returned:

```
unable to recognize no matches for kind "DaemonSet" in version "extensions/v1beta1
```
 
## How to reproduce it?

The problem can be reproduced with the following command:

```
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

## Anything else we need to know?

Those tests are done on DIgitalOcean Ubuntu 18.04 droplets. Kubernetes 1.16 was setup with kubeadm

## Versions:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by murali-reddy** [comment]
For `DaemonSet` api group`extensions/v1beta1 ` is depreated in 1.16. This isssue addressed in https://github.com/weaveworks/weave/pull/3660 but fix is yet to released. 

Could you please apply https://raw.githubusercontent.com/weaveworks/weave/master/prog/weave-kube/weave-daemonset-k8s-1.9.yaml to work arund it?

**Comment by bboreham** [comment]
cloud.weave.works should be fixed now.
