### ISSUE TITLE
Weave causes restart of cluster to stall

### ISSUE THREAD

**Issue by s3than** [weaveworks/weave#3702]
## What you expected to happen?

weave net to start and connect to all nodes

## What happened?

After a complete shutdown of the entire cluster and then restart the weave-net stops deploying two pods will show a running status and the logs show as follows, removing the running pods will allow weave net to connect to all the nodes.

Status output both show identical status

```

        Version: 2.5.2 (up to date; next check at 2019/09/25 04:37:41)

        Service: router
       Protocol: weave 1..2
           Name: d2:26:10:81:13:a1(ip-10-31-21-8.ap-southeast-2.compute.internal)
     Encryption: enabled
  PeerDiscovery: enabled
        Targets: 3
    Connections: 3 (1 established, 2 failed)
          Peers: 2 (with 2 established connections)
 TrustedSubnets: none

        Service: ipam
         Status: ready
          Range: 100.96.0.0/11
  DefaultSubnet: 100.96.0.0/11

```

## How to reproduce it?

AWS KOPS, HA configuration

Set all autoscaling groups to 0

Set master a to 1
Set master b to 1
Set master c to 1

Set nodes to 3

## Versions:

```
$ weave script 
```
2.5.2
```
$ docker version
```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

$ uname -a
```
Linux ip-10-31-1-207 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
```

$ kubectl version
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

## Logs:

$ kubectl logs -n kube-system <weave-net-pod> weave
```

DEBU: 2019/09/24 23:38:01.898077 [kube-peers] Nodes that have disappeared: map[]
100.96.0.2
10.31.1.207
10.31.1.57
10.31.21.118
10.31.21.8
10.31.41.146
10.31.41.195
DEBU: 2019/09/24 23:38:03.195574 registering for updates for node delete events
INFO: 2019/09/24 23:38:16.608506 ->[10.31.41.195:6783] attempting connection
INFO: 2019/09/24 23:38:16.613106 ->[10.31.41.195:6783] error during connection attempt: dial tcp4 :0->10.31.41.195:6783: connect: connection refused
INFO: 2019/09/24 23:38:35.271216 ->[10.31.41.195:6783] attempting connection
INFO: 2019/09/24 23:38:35.272389 ->[10.31.41.195:6783] error during connection attempt: dial tcp4 :0->10.31.41.195:6783: connect: connection refused
INFO: 2019/09/24 23:39:07.873139 ->[10.31.41.195:6783] attempting connection
INFO: 2019/09/24 23:39:07.877097 ->[10.31.41.195:6783] error during connection attempt: dial tcp4 :0->10.31.41.195:6783: connect: connection refused
INFO: 2019/09/24 23:40:02.085130 ->[10.31.41.195:6783] attempting connection
INFO: 2019/09/24 23:40:02.086257 ->[10.31.41.195:6783] error during connection attempt: dial tcp4 :0->10.31.41.195:6783: connect: connection refused
INFO: 2019/09/24 23:42:45.495875 ->[10.31.41.195:6783] attempting connection
INFO: 2019/09/24 23:42:45.496984 ->[10.31.41.195:6783] error during connection attempt: dial tcp4 :0->10.31.41.195:6783: connect: connection refused
INFO: 2019/09/24 23:45:28.096339 ->[10.31.41.195:6783] attempting connection
INFO: 2019/09/24 23:45:28.185104 ->[10.31.41.195:6783] error during connection attempt: dial tcp4 :0->10.31.41.195:6783: connect: connection refused
```

## Network:
```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by murali-reddy** [comment]
After a restart was there a weave-net pod running on `10.31.41.195`?

`[10.31.41.195:6783] error during connection attempt: dial tcp4 :0->10.31.41.195:6783: connect: connection refused`

indicates weave-net was running on `10.31.41.195`.

**Comment by s3than** [comment]
No just two of the nodes have daemonsets running

**Comment by s3than** [comment]
Some additional debugging, the network gets stuck waiting on the third master, if I terminate the master that is not connecting and allow it to create a new instance the network will get unstuck and continue.

The resolution options at the moment are

* Delete the weave pods and allow it to recreate
or
* Terminate the instance that has not attached

Either of those two options allow the restart of the cluster.

**Comment by murali-reddy** [comment]
> No just two of the nodes have daemonsets running

Please check why weave-net pod was not running? What was status of the pod?

> Terminate the instance that has not attached

Check why after restart node went into this state. Please check for any errors in kubelet logs.

**Comment by s3than** [comment]
Updating the cluster to 1.13.11 seemed to resolve and I'm unable to replicate it now, thank you.
