### ISSUE TITLE
Possible issue with kube-proxy on AWS EKS

### ISSUE THREAD

**Issue by getvivekv** [weaveworks/weave#3719]
New aws eks cluster was setup with k8s 1.14. After the cluster is ready, the aws cni was removed.

```
kubectl delete ds --namespace=kube-system aws-node 
```
Then the Weave net was installed as kubernetes service

```
curl --silent --location "https://cloud.weave.works/k8s/v1.10/net"  --output weave-net.yaml && kubectl apply -f weave-net.yaml
```

Then the kubernetes dashboard was installed as per official aws documentation 
https://docs.aws.amazon.com/eks/latest/userguide/dashboard-tutorial.html

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml
```

Started proxy

```
kubectl proxy
```
Opened the dashboard url 
```
http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#!/login
```

And the error message is 

```
Error: 'dial tcp 10.32.0.6:8443: i/o timeout'
Trying to reach: 'https://10.32.0.6:8443/'
```

Output of 
```
kubectl get pods --all-namespaces -o wide  
```

![image](https://user-images.githubusercontent.com/914305/66722355-61bde880-edda-11e9-94e2-d2dfa0f9ae1b.png)

It would appear that the kube-proxy container is unable to connect to the kubernetes-dashboard container. The kube-proxy has a the aws vpc private IP, whereas all other containers have the weave IP

Also tested this 
https://github.com/weaveworks/eksctl/issues/109

by removing all pods.

AWS Security group has ALL TRAFFIC between nodes and between master and nodes are enabled. Any idea why the proxy cannot send traffic to kubernetes-dashboard?

**Comment by murali-reddy** [comment]
@getvivekv Did you just delete the AWS CNI deamon set and installed Weave net?

That is not sufficient enough. Please see the additional steps needed https://github.com/weaveworks/weave/issues/3335#issuecomment-441522517

**Comment by getvivekv** [comment]
I've attempted all those steps. I created cluster using Aws console. Not using eksctl. The worker nodes weren't even setup so it wasn't necessary to remove Aws cni the files in /etc though I confirmed by logging into the worker node that those files aren't there. Iptables flushed. All containers restarted. Still kube-proxy has the Aws ip and it's not able to connect to k8s dashboard.

Let me know if you need anything specific to understand this issue more

**Comment by getvivekv** [comment]
I just want to clarify that I'm about to run weavenet and new pods are being assigned an IP by weave. The only problem is to run k8s dashboard

**Comment by murali-reddy** [comment]
thanks for confirming you ran the necessary steps.

Please try to narrow down the problem. First check if you have basic pod-to-pod connectivity is working as expected. Also check if node can access the pods and services running on the pods.

Use this guide https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ to narrow down the problem.

**Comment by murali-reddy** [comment]
Closing the issue as its related to service proxy. Please reopen with repro steps if you suspect weave-net is causing this problem.

**Comment by MMichael-S** [comment]
> I just want to clarify that I'm able to run weavenet and new pods are being assigned an IP by weave. The only problem is to run k8s dashboard

Hi Vivek
Do you have found a way to access the dashboard in the weave net CNI installed?
Thank you.

**Comment by getvivekv** [comment]
No. I dropped it. I no longer use the dashboard after started using Lens https://k8slens.dev/

**Comment by MMichael-S** [comment]
Hi Vivek
Thank you for your reply.
I am trying the Lens, but I found Lens still can't connect to the metrics-server pod. :(
So I can't get performance information about Cluster & Node.
I think it's same issue about Weave Net on EKS.

Err Msg:
Liveness probe failed: Get https://10.32.0.11:4443/livez: dial tcp 10.32.0.11:4443: connect: connection refused
