### ISSUE TITLE
when multiple hosts are removed, chances for duplicate reclaiming of IP space increases when the cluster size increases, causing IPAM inconsistencies

### ISSUE THREAD

**Issue by mmerrill3** [weaveworks/weave#3722]
## What you expected to happen?
Only one weave pod will reclaim IP space from a removed peer
## What happened?

Two pods try to reclaim IP space, and sometimes, they both succeed in getting the IP space from the node that was removed

## How to reproduce it?

Allow the autoscaler to remove half your cluster at once by cordoning and draining nodes.
## Anything else we need to know?

weave version 2.5.2, running on k8s 1.15.5

## Versions:

```
$ weave version
2.5.2
$ docker version
$ uname -a
$ kubectl version
```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
```

## Network:

```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

The issue can be seen here, where 3 weave pods try to reclaim space from the same peer that has been removed by the autoscaler:

October 17th 2019, 15:19:23.562 | DEBU: 2019/10/17 19:19:23.562338 [kube-peers] Noting I plan to remove  02:96:0b:ff:6e:d6 | weave-net-mgt6x
October 17th 2019, 15:19:23.486 | DEBU: 2019/10/17 19:19:23.486620 [kube-peers] Noting I plan to remove  02:96:0b:ff:6e:d6 | weave-net-mtvht
October 17th 2019, 15:19:23.482 | DEBU: 2019/10/17 19:19:23.482804 [kube-peers] Noting I plan to remove  02:96:0b:ff:6e:d6 | weave-net-tw5dr

But... two of them got the IP space, which caused our cluster to go haywire and we had to reinstall weave.  The last column (pipe separated from kibana) is the weave pod name.

October 17th 2019, 15:19:23.573 | INFO: 2019/10/17 19:19:23.573462 [kube-peers] rmpeer of 02:96:0b:ff:6e:d6: 16384 IPs taken over from 02:96:0b:ff:6e:d6 | weave-net-mgt6x
October 17th 2019, 15:19:23.502 | INFO: 2019/10/17 19:19:23.502368 [kube-peers] rmpeer of 02:96:0b:ff:6e:d6: 16384 IPs taken over from 02:96:0b:ff:6e:d6 | weave-net-mtvht

This happened a couple times to other removed peers too.  

I think it's the lack of a lock on this line: 	https://github.com/weaveworks/weave/blob/90e0c43bf2737ae5b6839b7f31c5c40b1300f69b/prog/kube-utils/main.go#L168

Multiple peers get to this line, and try to acquire the rights to remove the peer.  As your cluster gets bigger, there's a better chance for this b/c you have more weave pods looking for changes.

There needs to be some kind of lock here, to prevent the race condition.  Maybe only let one rmpeer operation happen at a given time by using some kind of mutex in k8s?  If only one weave pod is ever running this function https://github.com/weaveworks/weave/blob/90e0c43bf2737ae5b6839b7f31c5c40b1300f69b/prog/kube-utils/main.go#L74, then there will be no future contention.

**Comment by mmerrill3** [comment]
I see the sleep attempt, ,up to 5 seconds, per node here https://github.com/weaveworks/weave/blob/90e0c43bf2737ae5b6839b7f31c5c40b1300f69b/prog/kube-utils/main.go#L244,
but that doesn't scale.  I have around 25 cluster members, and chances further increase of collisions when I remove 15 nodes at a time due to upgrades.  That increases the chances of a couple weave pods accessing the config map at the same time, since each node getting removed is a new "roll of the dice" on the sleep time.

**Comment by mmerrill3** [comment]
I've seen examples, like the nginx-ingress-controller, that use leader elections with a config map to only have one "leader" make cluster wide changes.

**Comment by mmerrill3** [comment]
I think the annotation has to remain in the config map, to mark ownership, for at least 5 seconds, to account for any other weave pods that are sleeping and may wake up and think they can "own" the removed peer.  

That would be the easiest fix.  Before the annotations are removed from the config map by the original weave pod that removed the peer, wait at least 5 seconds.  There are other weave pods that may wake up and operate on the same peer that was removed.

**Comment by murali-reddy** [comment]
@mmerrill3 thanks for reporting the issue

```
October 17th 2019, 15:19:23.573 | INFO: 2019/10/17 19:19:23.573462 [kube-peers] rmpeer of 02:96:0b:ff:6e:d6: 16384 IPs taken over from 02:96:0b:ff:6e:d6 | weave-net-mgt6x
October 17th 2019, 15:19:23.502 | INFO: 2019/10/17 19:19:23.502368 [kube-peers] rmpeer of 02:96:0b:ff:6e:d6: 16384 IPs taken over from 02:96:0b:ff:6e:d6 | weave-net-mtvht
```
certainly indicates a race condition. 

Do you see `[kube-peers] error from UpdateAnnotation` in your logs?

there is no explicit leader election/distributed locking but implicitly relies on kube api server for achieving same.

**Comment by raoofm** [comment]
@murali-reddy same team as @mmerrill3 

yes we saw those errors, sample below

`ERRO: 2019/10/17 19:19:14.328344 [kube-peers] error from UpdateAnnotation:  Operation cannot be fulfilled on configmaps "weave-net": the object has been modified; please apply your changes to the latest version and try again`

**Comment by mmerrill3** [comment]
@murali-reddy I believe the random sleeps, and hence the random order of processing, allows for this to happen.  

I see many instances of two weave pods attempting to remove the same peer.  Most of the time, only one weave pod gets the IPs from the removed peer, like below:


October 17th 2019, 15:19:58.247 | INFO: 2019/10/17 19:19:58.247003 [kube-peers] rmpeer of d2:57:b2:f2:5d:60: 0 IPs taken over from d2:57:b2:f2:5d:60 | weave-net-b6xdr
October 17th 2019, 15:19:57.583 | INFO: 2019/10/17 19:19:57.582999 [kube-peers] rmpeer of d2:57:b2:f2:5d:60: 32768 IPs taken over from d2:57:b2:f2:5d:60 | weave-net-b24xt


But sometimes, depending on timing, they both get the IPs.

I think a sleep on the removal of the annotation for the configmap will fix this, which would be at least 5 seconds.

**Comment by bboreham** [comment]
> random sleeps

Do note they aren't very random - fixed in #3716

**Comment by mmerrill3** [comment]
thanks @bboreham , I still think keeping the annotation in the config map until we are reasonably sure all the current peers that have received the event for the deletion of the node have processed the event.

Maybe spin off the removal of the annotation into a separate go routine with the stop channel, that has a reasonable delay?

**Comment by bboreham** [comment]
Sounds plausible.  Do you want to make a PR?

**Comment by mmerrill3** [comment]
will look into it.

**Comment by mmerrill3** [comment]
@bboreham is there a way to check if a peer has already been removed before actually removing it, like doing a GET before the DELETE here:

https://github.com/weaveworks/weave/blob/cb4a8769a8fd8d6cee4b5f872d849a15c7dbb165/api/ipam.go#L66


I tried to do a GET through a browser, and I get a 405 method not allowed.

I'm thinking you can do a last check before actually removing the peer to see if its still in the IPAM ring.

**Comment by bboreham** [comment]
If it’s not in the ring then removing it should be a no-op.

**Comment by mmerrill3** [comment]
@bboreham I think the smoke tests need a secret key?  I gave it a try to handle the case.  I didn't have to use go routines (which would have shared cml and other objects).  I switched around when the "unlock" happens until the end of the outer loop, that will achieve the same thing.
