### ISSUE TITLE
CI smoke-tests cloud VM setup is broken

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#3741]
e.g. https://circleci.com/gh/weaveworks/weave/12910
The last succcessful build was Nov 11.

Error message:
```
* google_compute_firewall.fw-allow-docker-and-weave: Error reading network: googleapi: got HTTP response code 400 with body: 
* google_compute_instance.tf_test_vm.3: Error loading zone 'us-central1-a': Get https://www.googleapis.com/compute/v1/projects/weave-net-tests/zones/us-central1-a?alt=json: stream error: stream ID 3; PROTOCOL_ERROR
```

Poking around I suspect Google Cloud has changed the protocol and we need to update terraform.  And in turn terraform has changed its syntax so we need to update our config files.

**Comment by murali-reddy** [comment]
bumping up terraform version and updating build-tools's terraform provisioning scripts as per the latest google provider documentation fixed the issue.

https://circleci.com/gh/weaveworks/weave/13004

PR for [build-tools](https://github.com/weaveworks/build-tools) https://github.com/weaveworks/build-tools/pull/161

will open weave PR once build-tool pr is merged
