### ISSUE TITLE
[dns] naming 'expose'd hosts

### ISSUE THREAD

**Issue by yaronr** [weaveworks/weave#375]
moonfish: Back to my question, then: host2# weave expose 10.0.1.102/24.  Now from a weave + dns container, I ping 10.1.0.102 - works. ping host2 - nada
yaronr
because doing expose doesn't register 'host2' as 10.1.0.102 in weavedns
yaronr
(or does it?0
moonfish
no. and neither should it. You could have a weave network of a dozen hosts which are all called 'host2'.
yaronr
tell you why I'm asking:
moonfish
we could perhaps add an option to 'expose' to specify a name that goes into weavedns.
yaronr
back to mesos - I'm running mesos slaves with -host. I had to manually re-write the resolv.conf, putting the bridge ip as nameserver. but the hostname is set by mesos. I also had to change dns resolution to be based on DNS (and not /etc/hosts). so mesos starts, and tries to gethostbyname. but since host2 is not a weave dns name, it returns nothing, and that's a problem.
yaronr
moonfish: so back to 'perhaps add an option to 'expose' to a specific name' - that would be very useful
moonfish
right. At first glance at least, does seem like a reasonable thing one may want to do.
moonfish
So please file an issue :)
yaronr
Also I believe that many admins will like it, especially those that set their names using puppet / chef / whatever  - they usually won't have a dozen 'host2'
yaronr
will do :)

**Comment by rade** [comment]
something like `weave expose 10.0.1.102/24 -h $(hostname)`

**Comment by yaronr** [comment]
xactly

**Comment by rade** [comment]
There's a similar issue here as in #364, namely that the record would be lost on restart of weavedns.

**Comment by awh** [comment]
Any thoughts on how this will work now that `weave expose` admits multiple CIDR arguments?

**Comment by rade** [comment]
> Any thoughts on how this will work now that `weave expose` admits multiple CIDR arguments?

In the same way that `weave run <cidr> <cidr> ... -h <hostname> ...` works.
