### ISSUE TITLE
Allocate manually pod IP address Kubernetes

### ISSUE THREAD

**Issue by g-dury** [weaveworks/weave#3759]
Hello all, just wanted to know if it was possible to specify the pod IP to be in a specific subnet.
Example by applying this conf in the weave daemon set:
```
Environment:
      HOSTNAME:        (v1:spec.nodeName)
      IPALLOC_RANGE:  10.0.3.0/24
      EXTRA_ARGS:     --ipalloc-default-subnet 10.0.0.0/16
```
And later applying the environment variable WEAVE_CIDR=net:10.0.1.0/24 on the pod that I would want to manually allocate. Is this supposed to work?

## Anything else we need to know?
Cloud provider: EKS

## Versions:

weave version: ```Image:      docker.io/weaveworks/weave-kube:2.5.2```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-17T10:01:51Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Thank you very much!

**Comment by murali-reddy** [comment]
Functionality to manually specifying the IP Address for the container is not available in kubernetes integration.

**Comment by g-dury** [comment]
Thank you @murali-reddy for your answer, I'll close this. If anybody is looking for the same feature I was looking around, contiv from cisco seems to address this but there is very little documentation about it. Anyway thank you for the hard work Weave team! Cheers!
