### ISSUE TITLE
Weave Net: Merge of incoming data issues / Auto fix inconsistency if any

### ISSUE THREAD

**Issue by alok87** [weaveworks/weave#3767]
## What you expected to happen?
The main expectation is weave should recover automatically from an inconsitent state. If not please suggest how to recover from it.

We expect any of the node in the network does not become un-routable. We use Kubernetes and we route to kubernetes services using Node Ports. So the route to the pods across a cluster of nodes can happen from any node in the network. Route is being done using ELB which keeps all the routable nodes in its pool of instances.

In one of the cluster some nodes keep becoming un-routable.

For example: Say if we have a service at port 32238. Then every node will resolve `node-ip:32238/status` , except the node which has become un-routable.

## What happened?
We see a lot of Merge connection issue in the weave logs of the the node that has become unroutable.
```
ubuntu @ kuber-mumbai :~ $ kubectln get pods -n kube-system -o wide | grep weave | awk '{print $1}' | xargs -I {} kubectln  exec {} -c weave -n kube-system -- /home/weave/weave --local status connections | grep Merge
-> 10.2.20.42:6783       failed      Merge of incoming data causes: Entry 100.96.128.0-100.96.128.3 reporting too much free space: 4 > 3, retry: 2020-02-09 20:01:06.669854666 +0000 UTC m=+16666.766922212
```

## How to reproduce it?
We saw this happening after many scale ups and down when we were in 2.5.2 https://github.com/weaveworks/weave/issues/3677
(but cannot be certain to say that only caused it)

We have moved to 2.6.0, and want to recover from the inconsistent network **completely**.

When the network becomes inconsistent and keeps getting merge issues, we are unable to recover from it. 

Short term fix that works is by finding the nodes which are having most merge issues and then deleting its weave db and rebooting it. This makes them routable. If we do this for sometime the merge issues become very intermittent but in  a few days it again becomes a mess.

Any new node that joins after the mess, is mostly unroutable and requires removal of weave db and reboot(sometimes multiple times)

The concern is the short term fix help does not completely remove the merge issues we see. Even after short term fix, we keep seeing merge issues intermittently.
We use the below command to find Merge issues.
```kubectl get pods -n kube-system -o wide | grep weave | awk '{print $1}' | xargs -I {} kubectl exec {} -c weave -n kube-system -- /home/weave/weave --local status connections  | grep Merge```

We are not able to totally get rid of some issue in the network, that is why it keeps coming back.

## Anything else we need to know?
Configured using kops, cloud provider is aws.

## Versions:
```
$ weave version (We migrated from 2.5.2 to 2.6.0 - we were facing this in 2.5.2 also)
2.6.0

admin@ip-10-2-21-245:~$ sudo docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false

admin@ip-10-2-21-245:~$ uname -a
Linux ip-10-2-21-245 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

$ kubectl version
1.15.5
```

## Logs:
Weave log of the new unroutable node
https://gist.github.com/alok87/c259683496c10ed007c61516839579b6

## Network:
New node that was unroutable.

```
admin@ip-10-2-21-245:~$ ip route
default via 10.2.21.1 dev eth0
10.2.21.0/24 dev eth0 proto kernel scope link src 10.2.21.245
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
```
```
admin@ip-10-2-21-245:~$  ip -4 -o addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 10.2.21.245/24 brd 10.2.21.255 scope global eth0\       valid_lft forever preferred_lft forever
3: docker0    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0\       valid_lft forever preferred_lft forever
5: nodelocaldns    inet 169.254.20.10/32 brd 169.254.20.10 scope global nodelocaldns\       valid_lft forever preferred_lft forever
5: nodelocaldns    inet 100.64.0.10/32 brd 100.64.0.10 scope global nodelocaldns\       valid_lft forever preferred_lft forever
```
```
INFO: 2020/02/09 20:07:34.431743 ->[10.2.20.42:6783|e6:45:d0:e3:de:16(ip-10-2-20-42.ap-south-1.compute.internal)]: connection shutting down due to error: Merge of incoming data causes: Entry 100.96.128.0-100.96.128.3 reporting too much free space: 4 > 3
```
Ip tables save output https://gist.github.com/alok87/444cf1c64c11cd91b8ed70ac141527b5

The weave status in this bad node. Says `waiting for IP(s) to become available`

```
/home/weave # ./weave --local status

        Version: 2.6.0 (up to date; next check at 2020/02/10 01:01:03)

        Service: router
       Protocol: weave 1..2
           Name: 7a:79:ee:42:45:e4(ip-10-2-21-245.ap-south-1.compute.internal)
     Encryption: disabled
  PeerDiscovery: enabled
        Targets: 33
    Connections: 37 (36 established, 1 failed)
          Peers: 37 (with 1331 established, 1 pending connections)
 TrustedSubnets: none

        Service: ipam
         Status: waiting for IP(s) to become available
          Range: 100.96.0.0/11
  DefaultSubnet: 100.96.0.0/11
```

### Weave status ipam output (nothing seemed reachable)
https://gist.github.com/alok87/d374cfb18de38aefe38bdabe35acc5f4

**Comment by alok87** [comment]
Got one more alert: Weave IPAM was not ready and was waiting for IPs to be become ready. This time instead of delete db and restart, `rmpeer` ed some of the dead nodes and it became ready.
Not concluding anything.

**Comment by alok87** [comment]
cc @murali-reddy please help out here.

**Comment by bboreham** [comment]
The error message which you identified "reporting too much free space" is very likely the key problem here.
Can you do a `weave report` on two nodes `7a:79:ee:42:45:e4(ip-10-2-21-245.ap-south-1.compute.internal)` and `b2:d0:cc:b4:76:01(ip-10-2-20-172.ap-south-1.compute.internal)` please - I think that will let us see the mismatch.

(If you've restarted things since then any two nodes which are doing the "connection shutting down ... free space" thing)

Ahead of any code fix, draining any nodes which have mismatched data, removing the persistence file and restarting should help.

**Comment by alok87** [comment]
@bboreham These nodes are terminated(/replaced by autoscaler). Can't give details about them now. 

The issue of `Merge` looks related to dead nodes IP addresses not getting reclaimed. 
[As soon as](https://github.com/weaveworks/weave/issues/3767#issuecomment-583904556) I rm-peered the dead node. The IPAM of the unroutable node became ready, it was stuck in waiting before that.

We have deployed [the weave rm peerer script](https://gist.github.com/mikebryant/f5b25f9b14e5d6275ff0d3e934f73f12) to reclaim the dead node ips every 2 hours. I think weave also reclaims the IPs when the new node needs it. But the issue has still happened, so we are running this for now. But reporting it here, as there still seems to be the issue with reclaiming which causes problem.

After running that script every 2 hours, we have not seen any Merge issues and none of the nodes have turned unhealthy.

Attaching some of the prometheus graphs for weave monitoring. 
Issue for us has mostly happening on these two dates
- 25th Jan 2020
- 9th/10th Feb 2020

## Weave monitoring graphs
<img width="1277" alt="Screenshot 2020-02-13 at 8 07 02 PM" src="https://user-images.githubusercontent.com/9006763/74445765-ef9b0480-4e9c-11ea-9c3a-2f0046a8a218.png">
<img width="1280" alt="Screenshot 2020-02-13 at 8 06 49 PM" src="https://user-images.githubusercontent.com/9006763/74445774-f32e8b80-4e9c-11ea-8c63-11c9e06a1a89.png">
<img width="1280" alt="Screenshot 2020-02-13 at 8 06 25 PM" src="https://user-images.githubusercontent.com/9006763/74445777-f45fb880-4e9c-11ea-8e95-9afe013c6796.png">

Let me know if i can help in any other way to fix this.

**Comment by alok87** [comment]
We had a split brain problem. Fixing that has solved the inconsistency.  Nodes were seeing two sets of unreachable ip addresses. We fixed this by deleting the weave and restarting the nodes for one set and this fixed the problem when all became healthy.

We have used this grafana graph to find the issue https://grafana.com/grafana/dashboards/11789

Please read this for complete discussion on this: https://weave-community.slack.com/archives/C2ND76PAA/p1582613239010900
