### ISSUE TITLE
Question: Aliasing weave IP on host

### ISSUE THREAD

**Issue by dlmarion** [weaveworks/weave#3768]
First, sorry to ask a question in your issues, I looked on the web site and did not find a link to a mailing list. I'm using `weave` and have a case where I have a non-Docker process and I want to allocate an IP for it on the network and assign it a DNS entry. The following worked:

`ifconfig weave:0 inet <weave_ip_plus_one> netmask <netmask_of_weave_if> broadcast <broadcast_of_weave_ip> mtu 1376`

`weave dns-add <ip> -h <fqdn>`

With that I am able to `ssh` to this host from another host on the weave network. I tried several things using the `weave` cli but was unable to just allocate an IP without a process. Will this work in the long term? Is this the "correct" way to do this?

**Comment by bboreham** [comment]
Sounds quite like what we call ["service import"](https://www.weave.works/docs/net/latest/tasks/manage/service-management/#importing-services)

**Comment by dlmarion** [comment]
@bboreham - Thanks for the response. Re-reading that section makes a little more sense now. I have a good number of http-based services that are not in Docker that our docker applications call out to. The example in the 'import services' section seems like I would still have all of my services bound to the host weave IP, but on a different port. I'm attempting to get out of having to maintain a bunch of port mappings (serviceA -> port1, serviceB -> port2, etc) and instead just use DNS addresses (and the default port - 80) for the different services. I think if WeaveDNS supported SRV addresses that might solve my issue. Absent that, I came up with the solution above to:
  *  create a virtual IP on the weave network
  *  have my service bind to that virtual IP
  *  register that IP in WeaveDNS with a service name
This seems to work, but I'm looking for some confirmation that the virtual IPs defined on the host won't break weave.

**Comment by bboreham** [comment]
Generally Weave Net works at Layer 2, i.e. it doesn't even know what you are doing with IP addresses.
So I can't think of anything immediately that would break, but it's impossible to be sure without trying it.
Do let us know how you get on.
