### ISSUE TITLE
A lot of weavetools containers are left behind

### ISSUE THREAD

**Issue by yaronr** [weaveworks/weave#378]
I don't have a specific scenario, I just did a docker ps and found:
42019eb389db        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X PUT   15 hours ago                                                                                     evil_tesla                 
2ed09c6f2597        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   15 hours ago        Exited (7) 15 hours ago                                                      happy_bartik               
2d9660621e4e        zettio/weavetools:git-719efd0ac4b8             "/bin/ethtool -K vet   17 hours ago                                                                                     trusting_turing            
1ea9e8d2a47f        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   18 hours ago        Exited (7) 17 hours ago                                                      berserk_shockley           
0515b237303f        zettio/weavetools:git-719efd0ac4b8             "/bin/ethtool -K wea   18 hours ago                                                                                     hungry_einstein            
1591be68b5ce        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   19 hours ago        Exited (7) 19 hours ago                                                      insane_yonath              
674c0c786335        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   21 hours ago        Exited (7) 21 hours ago                                                      trusting_mayer             
34b8a0504568        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   21 hours ago        Exited (7) 21 hours ago                                                      ecstatic_wozniak           
f373c3787825        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   21 hours ago        Exited (7) 21 hours ago                                                      silly_carson               
17b04550c6bd        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   21 hours ago        Exited (7) 21 hours ago                                                      grave_lalande              
8ab5a3e03881        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   2 days ago          Exited (0) 2 days ago                                                        cocky_curie                
2940f4cc9619        zettio/weavetools:git-719efd0ac4b8             "/bin/curl -s -X DEL   2 days ago

**Comment by rade** [comment]
That's all a bit odd. Looks like a docker bug to me; we start these containers with `--rm`, so they should not stick around after exiting. The other odd thing is that some containers - all the ones that don't say "Exited" - purport to still be running. Can you double check on that? Run 'docker inspect' on them, grab the pid, check that pid is still alive.

**Comment by yaronr** [comment]
pid is 0 for a couple that I looked at

**Comment by rade** [comment]
> pid is 0 for a couple that I looked at

including some that *don't* say "Exited"?

**Comment by yaronr** [comment]
both :)

"State": {
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "0001-01-01T00:00:00Z"
    },

**Comment by rade** [comment]
I see. Do any show as `"Running": true` in the state?

**Comment by yaronr** [comment]
No. 
But BTW, for these instances, it doesn't show as Exited OR running, it just shows an empty value.
I have seen this in the past, and there I had tens of instances I had to manually rm.

My guess would be a Docker bug, but you may need to do some fallback cleanup there.

**Comment by rade** [comment]
`--rm` is so far from being reliable, it's not funny. See https://github.com/docker/docker/issues/7245. Or just look at the code. It's all done client side, involving multiple http calls to the docker daemon. So anything going wrong in or during those results in a leftover container. Nice.

**Comment by threadflow** [comment]
Occurred the same problem.

**Comment by rade** [comment]
I do wonder whether #395 ameliorates this somewhat.

**Comment by yaronr** [comment]
I just checked 'ameliorates' in a dictionary ;)

**Comment by rade** [comment]
weavetools is gone. welcome weavexec. see #607.
