### ISSUE TITLE
net-plugin 2.6.1 not built for x86

### ISSUE THREAD

**Issue by mcvetra** [weaveworks/weave#3786]
weaveworks/net-plugin 2.6.1 is not built for x86 architectures. Running "file" on the busybox binary in the plugin /bin directory shows it has the wrong ELF format (e.g. MSB instead of LSB) to run on x86.

To reproduce:
docker plugin install weaveworks/net-plugin:latest_release

It gives an error indicating the weave unix socket doesn't exist. Version 2.6.0 works just fine.

**Comment by bboreham** [comment]
Thanks for the report; looks like something went wrong in the release build.
Note that 2.6.1 is [suspect](https://github.com/weaveworks/weave/releases/tag/v2.6.1) anyway; 2.6.2 will be out shortly.

**Comment by murali-reddy** [comment]
@mcvetra Can you please try `weaveworks/net-plugin:latest_release`, 2.6.2 is released now

**Comment by murali-reddy** [comment]
I am able to install the plugin ver 2.6.2. Please reopen if you still are facing the issue.
