### ISSUE TITLE
weave_flows metric is fastdp-only, no way to see how many sleeve flows there are

### ISSUE THREAD

**Issue by hairyhenderson** [weaveworks/weave#3788]
_(note: I'm not very familiar with Weave internals, so apologies if I make terminology mistakes below - please correct me!)_

We recently ran into the issues fixed in [2.6.2](https://github.com/weaveworks/weave/releases/tag/v2.6.2) (#3781, #3783, #3782), and while working through upgrading our clusters were wondering how we could detect this sort of thing in the future.

We use Prometheus for our monitoring, and have the `weave_flows` metric graphed on a Grafana dashboard. It's obvious when looking over a period of time that the number of flows plummets (in our case, from an average of a few thousand per node to below ~100 per node).

However, we found no way to measure the number of sleeve flows.

Note that this may be related to #2557, but that may be a big general, and it's been stale for a long time.

## What you expected to happen?

A metric to measure the number of sleeve flows should be present, or perhaps a label to indicate which kind of flows are being measured.

## What happened?

No indication of what `weave_flows` is actually indicating.

## How to reproduce it?

Grab the output of the `/metrics` endpoint from a weave process.

## Anything else we need to know?

Probably not relevant, but we're running on AWS with KOPS.

## Versions:

Note: we _were_ running Weave 2.6.1, but have now upgraded to 2.6.2. (can't exec into the weave-net pod, but we're running `weaveworks/weave-npc:2.6.2`).

```
$ docker version
Client:
 Version:           18.09.9
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:48 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
$ uname -a
Linux ip-10-40-108-161 5.3.0-0.bpo.2-cloud-amd64 #1 SMP Debian 5.3.9-2~bpo10+1 (2019-11-13) x86_64 GNU/Linux
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

## Logs:

(not relevant IMO)

## Network:

(not relevant IMO)

**Comment by bboreham** [comment]
"flow" is an object in the OVS kernel module used by fastdp; there is no analogous structure for sleeve.

But I think you are looking for some indication that peer-to-peer connections have stuck at `sleeve` when they should be `fastdp`.  We could add the connection type as a label on `weave_connections`.

Does `weave_connections{state="established"} - weave_flows` give you the number of sleeve connections?

**Comment by hairyhenderson** [comment]
> "flow" is an object in the OVS kernel module used by fastdp; there is no analogous structure for sleeve.
> 
> But I think you are looking for some indication that peer-to-peer connections have stuck at `sleeve` when they should be `fastdp`. We could add the connection type as a label on `weave_connections`.

Ah, thanks for clarifying. Yes, that's definitely what I'm looking for, and connection type on `weave_connections` sounds about right!

> Does `weave_connections{state="established"} - weave_flows` give you the number of sleeve connections?

That's kind of what I was wondering, but the scale seems off. From what you're implying `weave_connections{state="established"}` should include both `fastdp` and `sleeve` connections?

For example, during one of the instants when we were running Weave 2.6.1, for one of the pods, `weave_connections{state="established"}` is `15`, where `weave_flows` is `42`, though the `weave_flows` count seems to vary quite a bit more than connections:

<img width="2533" alt="Screen Shot 2020-03-18 at 13 35 45" src="https://user-images.githubusercontent.com/2037086/76989838-66547300-691d-11ea-9460-f3c970b447df.png">

And then, after the upgrade to 2.6.2, `weave_flows` is quite a bit larger than `weave_connections{state="established"}`:

<img width="2530" alt="Screen Shot 2020-03-18 at 13 42 41" src="https://user-images.githubusercontent.com/2037086/76990476-62752080-691e-11ea-9e3e-26abc48bcd1a.png">

So I suppose that means that no, `weave_connections{state="established"} - weave_flows` won't really mean anything 😉

**Comment by bboreham** [comment]
Ah, right: flows are per-MAC whereas connections are per-machine (or peer if you prefer).

Would you be interested to try a PR to add the connection-type label?

**Comment by hairyhenderson** [comment]
perhaps, though I'm not at all familiar with the weave code so it may take some time... I'll poke at it and see 😉

**Comment by bboreham** [comment]
Great!  Start here: https://github.com/weaveworks/weave/blob/0c4659c3b545f2fa719474ef941629d28b699820/prog/weaver/metrics.go#L50

The status struct has a dictionary `Attrs` where key `name` should give a string like `sleeve` or `fastdp`.  (There may also be keys like `encrypted` and `mtu`)

**Comment by hairyhenderson** [comment]
@bboreham thanks - I was wondering what `Attrs` would be! `map[string]interface{}`s are the bane of my existence 😂

**Comment by hairyhenderson** [comment]
@bboreham I've issued #3789 - PTAL when you have a chance, it's perhaps a bit rough, let me know how I can improve it!
