### ISSUE TITLE
proxy settings can break 'weave status' and friends

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#379]
A user was seeing

	# weave status
	<HTML><HEAD><TITLE>Network Error</TITLE></HEAD>
	<BODY>
	<FONT face="Helvetica"><big><strong></strong></big><BR></FONT>
	<blockquote>
	<TABLE border=0 cellPadding=1 width="80%">
	<TR><TD>
	<FONT face="Helvetica"><big>Network Error (tcp_error)</big><BR><BR></FONT>
	</TD></TR><TR><TD><FONT face="Helvetica">A communication error
	occurred: "No route to host"</FONT></TD></TR><TR><TD>
	<FONT face="Helvetica">The Web Server may be down, too busy, or
	experiencing other problems preventing it from responding to
	requests. You may wish to try again at a later
	time.</FONT></TD></TR><TR><TD><FONT face="Helvetica" SIZE=2><BR>For
	assistance, contact your network support team.</FONT></TD></TR>
	</TABLE>
	</blockquote>
	</FONT>
	</BODY></HTML>

which turned out to be due to proxy settings.

Presumably the same problem arises with all other http interactions between the script and containers, such as `connect` and all the communication with weavedns.

**Comment by bboreham** [comment]
According to the [curl man page](http://curl.haxx.se/docs/manpage.html), `--proxy ''` is the way to ask for no proxy.

**Comment by rade** [comment]
Yes, I looked that up last night. This would work currently and I guess is what we should do for now. But it would be wrong for #312. @squaremo?

**Comment by errordeveloper** [comment]
There is a well-known set of environment variables which would have to check and unset otherwise...

**Comment by errordeveloper** [comment]
With #388 proxy settings (i.e. environment variables) would be completely isolated, as the container the driver runs in will not inherit those, I believe.

**Comment by awh** [comment]
Is this fixed now that #388 is merged?

**Comment by rade** [comment]
*should* be fixed. but somebody should have a play.

**Comment by rade** [comment]
One concern I have is whether proxy settings could somehow leak into the weavexec container. After all, it's executing in the host netns and in privileged mode.

**Comment by awh** [comment]
The form of the 'proxy settings' alluded to in the original report is quite vague - are we talking solely about the `http_proxy` environment variable (and friends) observed by `curl` and `docker`? In that case, my testing shows this to be fixed (although obviously if you have docker-affecting proxy env vars set they need to be workable in terms of us being able to docker run the weaveexec container) - as @errordeveloper says the environment variables are isolated from the weaveexec container...

**Comment by rade** [comment]
The original user had `http_proxy` set.

So let's just leave it at that. Fixed by #388.
