### ISSUE TITLE
Simple helm chart deployment can cause entire CNI crash

### ISSUE THREAD

**Issue by tranx** [weaveworks/weave#3798]
***Summary***
All weave-net pods crash on all nodes.
I had the issues with two clusters in last 48 hours. 
I think it is due to change of error handling in latest merge.

***More context***
Looking at the logs I have the following fatal error:
kubectl logs -f -n kube-system  weave-net-w229k weave-npc
(...)
FATA: 2020/05/11 14:10:04.591709 add network policy: named ports in network policies is not supported yet. Rejecting network policy: devops-pgadm-pgadmin4 from further processing. named port http in network policy

pgadm is deployed using standard helm chart. 

**Expected behaviour:**
Even if named port is not supported, I would expect that it could be deployed on the cluster without causing a fatal error on weave.

**Comment by bboreham** [comment]
There is no helm chart in this repo.

However I suspect your issue is the same as #3785.

**Comment by bboreham** [comment]
A change was made in #3790 to turn the fatal error into a warning error; you should be able to try that out by using image tag `:latest`.
