### ISSUE TITLE
Weave firewall rule interferes with local traffic

### ISSUE THREAD

**Issue by drigz** [weaveworks/weave#3810]
## What you expected to happen?

We use a DNAT rule to capture traffic to 169.254.169.254:80 and send it to 127.0.0.1:8965. I expect Weave not to interfere with this.

## What happened?

Weave creates a firewall rule that drops this traffic:

```
$ sudo iptables -t filter -L | grep 'DROP.*localhost'
DROP       tcp  --  anywhere             localhost            ADDRTYPE match src-type !LOCAL ! ctstate RELATED,ESTABLISHED
```

If I delete that rule, our setup works as normal.

## How to reproduce it?

```
sudo iptables -t nat -I PREROUTING -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination 127.0.0.1:8965
nc -v -l 127.0.0.1 8965
# in another terminal
docker run --rm -it debian:stretch bash
apt update && apt install -y netcat
nc -v 169.254.169.254 8965
```

## Anything else we need to know?

This appears to have been introduced by https://github.com/weaveworks/weave/pull/3805. Is there a reason that rule affects traffic on all ports?

## Versions:

```
$ weave version
weave script 2.6.0
weave 2.6.3
$ docker version
19.03.5
$ uname -a
Similar to Debian buster
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

## Logs:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
DEBU: 2020/05/29 14:53:58.663236 [kube-peers] Checking peer "9e:49:f7:aa:15:13" against list &{[{9e:49:f7:aa:15:13 hostname}]}
INFO: 2020/05/29 14:53:58.703351 Command line options: map[conn-limit:200 datapath:datapath db-prefix:/weavedb/weave-net docker-api: expect-npc:true host:127.0.0.1 host-root:/host http-addr:127.0.0.1:6784 ipalloc-init:consensus=0 ipalloc-range:192.168.9.0/24 metrics-addr:0.0.0.0:6782 name:9e:49:f7:aa:15:13 nickname:hostname no-dns:true port:6783]
INFO: 2020/05/29 14:53:58.703384 weave  2.6.3
INFO: 2020/05/29 14:53:59.014044 Re-exposing 192.168.9.1/24 on bridge "weave"
INFO: 2020/05/29 14:53:59.044042 Bridge type is bridged_fastdp
INFO: 2020/05/29 14:53:59.044073 Communication between peers via untrusted networks is encrypted.
INFO: 2020/05/29 14:53:59.122937 Our name is 9e:49:f7:aa:15:13(hostname)
INFO: 2020/05/29 14:53:59.122976 Launch detected - using supplied peer list: []
INFO: 2020/05/29 14:53:59.130554 Checking for pre-existing addresses on weave bridge
INFO: 2020/05/29 14:53:59.131803 weave bridge has address 192.168.9.1/24
INFO: 2020/05/29 14:53:59.149237 Found address 192.168.9.4/24 for ID _
INFO: 2020/05/29 14:53:59.155631 [allocator 9e:49:f7:aa:15:13] Initialising with persisted data
INFO: 2020/05/29 14:53:59.155700 Sniffing traffic on datapath (via ODP)
INFO: 2020/05/29 14:53:59.159853 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2020/05/29 14:53:59.160471 Listening for metrics requests on 0.0.0.0:6782
INFO: 2020/05/29 14:53:59.738394 [kube-peers] Added myself to peer list &{[{9e:49:f7:aa:15:13 hostname}]}
DEBU: 2020/05/29 14:53:59.744461 [kube-peers] Nodes that have disappeared: map[]
192.168.9.1
DEBU: 2020/05/29 14:53:59.836098 registering for updates for node delete events
```

## Network:

```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by bboreham** [comment]
Thanks for pointing this out.  
The reason I did it for all ports is to protect other programs which have the same assumption that 127.0.0.1 is a security boundary, e.g. as pointed out in the linked Kubernetes issue.

**Comment by bboreham** [comment]
Wait, why does traffic from your host match the `src-type !LOCAL` part of the rule?

**Comment by drigz** [comment]
I'm not an expert on this, but I guess it's because the traffic is running inside a docker container, so the source IP is on the docker subnet. A log statement before the packet is dropped looks like:

```
May 29 16:38:01 hostname kernel: [_REQUEST_AT_FILTER_INPUT_12_IN=docker0 OUT= PHYSIN=veth7033ebd MAC=02:42:80:13:41:cb:02:42:c0:a8:0a:02:08:00 SRC=192.168.10.2 DST=127
.0.0.1 LEN=52 TOS=0x00 PREC=0x00 TTL=64 ID=51806 DF PROTO=TCP SPT=56058 DPT=8965 WINDOW=501 RES=0x00 ACK URGP=
```

**Comment by bboreham** [comment]
Ah, thanks. 
I have a suggested change at #3811 - are you able to try an unreleased image?

**Comment by drigz** [comment]
Possibly, would I just need to edit the label/digest into the DaemonSet?

Will the change clean up the old rule or does that need to be done manually / with a reboot?

Also, is there a way to add a comment to the rule to indicate it's created by Weave, in case others run into issues with it? I had to figure it out by deleting the rule and restarting Weave.

**Comment by bboreham** [comment]
Yes, change the tag in the daemonset.
Good point - it will not take out the previous rule.

**Comment by bboreham** [comment]
Sorry, I'm on a phone call at the same time.
I just pushed `weaveworks/weave:allow-dnat-127-46e7c766`

**Comment by drigz** [comment]
I get `Failed to pull image "weaveworks/weave-kube:allow-dnat-127-46e7c766": rpc error: code = Unknown desc = Error response from daemon: manifest for weaveworks/weave-kube:allow-dnat-127-46e7c766 not found: manifest unknown: manifest unknown
` with or without docker.io/ in the image ref. Is `weave` the same as `weave-kube`?

**Comment by bboreham** [comment]
Sorry, I shouldn't try to do two things at once.
I have now pushed `weaveworks/weave-kube:allow-dnat-127-46e7c766`

**Comment by drigz** [comment]
Thanks, can confirm that it works once after I update and run:

```
DROP       tcp  --  anywhere             localhost            ADDRTYPE match src-type !LOCAL ! ctstate RELATED,ESTABLISHED,DNAT
```

**Comment by drigz** [comment]
weaveworks/weave-kube:allow-dnat-127-e2932351 works great, thanks!

Out of curiosity, is there an issue with the `!cstate RELATED,ESTABLISHED,DNAT` approach, or are you just hoping to avoid related breakage? We have some other services that make the same assumption about the safety of the loopback interface, so I'm wondering how to protect them.

**Comment by bboreham** [comment]
I reflected on what I needed to achieve, and decided it was safer to write the rule with the port number in.  That done, there seemed to be no reason to include the DNAT addition.

Suggest you follow along at https://github.com/kubernetes/kubernetes/pull/91569 where roughly the same broader rule is proposed, and see if anyone spots an issue.

**Comment by bboreham** [comment]
[Weave Net 2.6.4](https://github.com/weaveworks/weave/releases/tag/v2.6.4) released with the change.
