### ISSUE TITLE
Readiness probe failing on upgrade to 2.6.4 on EKS

### ISSUE THREAD

**Issue by ac-hibbert** [weaveworks/weave#3814]
## What you expected to happen?

weave starts okay when container is upgraded from 2.6.2 to 2.6.4

## What happened?

Get the message:

```
Readiness probe failed: Get http://127.0.0.1:6784/status: dial tcp 127.0.0.1:6784: connect: connection refused
```

## How to reproduce it?

Running on EKS, originally I have ports 6783-6784 UDP and 6783 TCP allowed from EKS workers to cluster and runs okay on 2.6.2. After upgrading I get the readiness probe failure. If I open up 6784 I seem to be getting a different error:

```
DEBU: 2020/06/03 18:42:50.412103 [kube-peers] Checking peer "86:8d:08:e5:0d:a6" against list &{[{96:bb:40:05:dd:db ip-10-207-56-229.ec2.internal} {ca:b7:8d:a2:b9:49 ip-10-207-56-143.ec2.internal} {86:8d:08:e5:0d:a6 ip-10-207-56-225.ec2.internal} {62:67:8f:44:45:ec ip-10-207-56-183.ec2.internal}]}
FATA: 2020/06/03 18:42:50.654286 creating bridged fastdp veth pair: setting accept_ra to 0: open /proc/sys/net/ipv6/conf/vethwe-bridge/accept_ra: no such file or directory
```

## Anything else we need to know?

EKS

## Versions:

```
$ weave version
$ docker version
$ uname -a
$ kubectl version
```

## Logs:
```
$ docker logs weave
```
or, if using Kubernetes:
```
$ kubectl logs -n kube-system <weave-net-pod> weave
```

## Network:

```
$ ip route
$ ip -4 -o addr
$ sudo iptables-save
```

**Comment by bboreham** [comment]
Presuming you mean 2.6.4, this is indeed a new fix that was put in for a [CVE reported via Kubernetes](https://github.com/weaveworks/weave/security/advisories/GHSA-59qg-grp7-5r73).

Do your nodes have ipv6 disabled or something like that?  I can put in some protection against failure in this case.

**Comment by bboreham** [comment]
Sorry about that.  Ironically the CVE is for nodes not _using_ IPv6 but I didn't look at what happens when you have disabled it entirely.

**Comment by bboreham** [comment]
If you're in a position to test an unreleased version, please try `weaveworks/weave_kube:latest` which should fix this problem.

**Comment by hibbert** [comment]
I've tested that version, it fixed the problem
