### ISSUE TITLE
weave net in k8s bandwidth measure

### ISSUE THREAD

**Issue by CCrainys** [weaveworks/weave#3819]
Hi,
     I'm doing some network measurement in my kubernetes cluster. After installing weave net CNI plugin, there are six nic interfaces shown in "ifconfig" output,  (datapath ,weave ,vethwe-datapath      vethwe-bridge, vxlan-6784, vethwepl35b0219) 

  I plan to use "ifstat" to monitor weave network. However, I am confused which interface I should monitor. It seems that the  inbound bandwidth of vethwe-datapath is equal to outbound bandwidth of vethwe-bridge.

  I am so confused about the relationship between these interfaces, 
   1. Can you explain the function and relationship of these interface? 
   2. Which interface should I monitor? 
   3. If ifstat is not a good tool to monitor weave net, can you give me some guidance about how to test weave net bandwidth

Best regareds

## Versions:

```
$ kubectl version
v1.18.3
$ uname -r
3.10.0-957.10.1.el7.x86_64
$ OS version
centos-7
```

## Install comand
```
 kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

**Comment by bboreham** [comment]
> Can you explain the function and relationship of [datapath ,weave ,vethwe-datapath vethwe-bridge, vxlan-6784, vethwepl35b0219]?

'vethwepl35b0219' belongs to one container.  As you run more containers you should see more veths. There's a picture here: https://github.com/weaveworks/weave/blob/1ff09fd4d1c52bfa49222b724742f7b4bb80543a/net/bridge.go#L35-L43

'vxlan-6784' is mentioned here: https://github.com/weaveworks/weave/blob/master/docs/fastdp.md#virtual-ports

> Which interface should I monitor?

I guess that depends what you mean to find out.  The per-container virtual interfaces will give you the best data about what is happening at an application level; if you want to know what Weave Net is doing on your underlying network then monitor ports 6783 and 6784 on the real device(s) of your hosts.

Personally I use data collected via Prometheus from cAdvisor (which will be running inside your Kubernetes kubelet component already) - metrics like `container_network_transmit_bytes_total`.  
We run a commercial service [Weave Cloud](https://cloud.weave.works) that sets up all the data collection automagically and will give you charts like this:
![image](https://user-images.githubusercontent.com/8125524/84995586-18315480-b144-11ea-9514-a3477efba7f7.png)


> how to test weave net bandwidth

That strikes me as a totally different question.  Here's how we did it:  https://www.weave.works/blog/weave-net-performance-fast-datapath/

**Comment by CCrainys** [comment]
Thanks for your quick reply! I learn a lot from it.
I will deploy Prometheus to measure application ASAP.
But I still has a question.

> Which interface should I monitor

For example, deploy a distributed service in k8s, like memcached. Assumed that, there are one pod in each node, one pod only consists of one container. Here, I want measure the network bandwidth of memcached pod in each pod or node

Prometheus is good choice, but according to picture below,  I think that measuring container-veth or vethwe-datapath via ifstat can also reflect application network performance, Do you think this method is reasonable? 
<img width="577" alt="Screen Shot 2020-06-18 at 5 22 31 PM" src="https://user-images.githubusercontent.com/18700694/85003120-610afc80-b188-11ea-8d1c-220ed47e168d.png">

**Comment by bboreham** [comment]
Yes, to understand what one pod is doing, look at the veth inside the container, which will be named `eth0` in that namespace.  This is what cAdvisor does.

`vethwe-datapath` will combine traffic from all containers that needs to traverse to another host; it will not tell you anything about your memcached.

**Comment by CCrainys** [comment]
Ok, thanks
