### ISSUE TITLE
[dns] launch weavedns by default

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#382]
Instead of a separate `weave launch-dns` step, we should launch weavedns by default, as part of `weave launch`. Unless the user specifies a `--without-dns` option.

This does depend on #22 somewhat, in that weavedns needs an IP (and subnet), and we don't really want to clutter `weave launch` with that information, at least not by default.

A few other points need consideration:

- if we pick the IP and subnet automatically, should it be possible to override that choice?
- should it still be possible to launch (and stop) weavedns separately?

We want to avoid option/command clutter, so unless we have *compelling* use cases for needing the above, we should refrain.

**Comment by rade** [comment]
#741, #762, #763 are all related.

**Comment by awh** [comment]
Fixed by #1009.
