### ISSUE TITLE
Weave Subnet is not being contained or encapsulated within my host.

### ISSUE THREAD

**Issue by ricsonchua** [weaveworks/weave#3821]
As discussed with @bboreham  in #2736. I have raised a new issue.
I have encountered a scenario where encapsulation is not working. 

Below is a link of what is happening.
https://drive.google.com/file/d/1oKyhC8woFEZGBhhG-EjjFm-fBTw9iN4I/view?usp=sharing

- On the upper right corner. You can see that my workstation's IP is within 10.32.0.1/12 (10.35.54.126 for that matter)
- On the lower right corner. I am unable to SSH to 10.26.58.162 because Weave, which is supposed to be encapsulated,  is conflicting with my organization's network.
- On the left side, I am using another server that I can access which has SSH access to 10.26.58.162. Upon entering 10.26.58.162, I execute show commands to show my server's interface and weave's interface.

The machine is a VM with Redhat 7.8 installed. I understand from @bboreham's response to me in #2736 that it is better to not have conflicts with my organization's IP. You may close this if the understanding is correct. I have written to my network team anyway that I want to reserve some IP addresses. I just can't personally agree that this is not contained/encapsulated within my host or the Kubernetes cluster.

Best regards,
Ricson

**Comment by ricsonchua** [comment]
@bboreham Sorry about that. I updated just now as I missed masking some sensitive info.

**Comment by bboreham** [comment]
I note you have chosen not to fill in any of the requested information in our issue template.
This makes it impossible to give a detailed answer.

> my workstation's IP is within 10.32.0.1/12 (10.35.54.126 for that matter)

You must pick a range for Weave Net disjoint from any addresses you will use for anything else.
