### ISSUE TITLE
make weavedns the name resolver for containers by default

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#383]
Right now, containers started with `weave run` only use weavedns for name resolution when the `--with-dns` option has been specified. We did that because weavedns used to lack some key features required to act as a nameserver in a fair few cases. That has changed now, and hence that choice should be inverted, i.e. we should have a `--without-dns` option, though, arguably, only after #382.

NB: we'd want to avoid an ordering dependency here; i.e. it should be possible to start containers with dns pointing at weavedns even when weave/weavedns isn't running.

**Comment by squaremo** [comment]
> NB: we'd want to avoid an ordering dependency here; i.e. it should be possible to start containers with dns pointing at weavedns even when weave/weavedns isn't running.

One way to do that is to check whether it's running, and run it if not. Are there other ways?

**Comment by rade** [comment]
> One way to do that is to check whether it's running, and run it if not.

We don't do that for weave.

> Are there other ways?

I want to preserve what is possible now; there is nothing stopping you from `weave run --with-dns`ing a container when neither weave or weavedns are running.

**Comment by peterbourgon** [comment]
+1

**Comment by rade** [comment]
>  it should be possible to start containers with dns pointing at weavedns even when weave/weavedns isn't running.

While that is possible currently, doing so by default strikes me as dangerous; seems way to easy to accidentally start containers pointing at a non-existing (and never-to-exist) weavedns server.

So, how about the default behaviour is to point at weavedns if it is running. And have `--with-dns` and `--without-dns` options to override that choice.

The proxy's behaviour should be changed to match.

**Comment by inercia** [comment]
Should this issue be solved after #382? If so, I guess #382 should have the same milestone...

**Comment by rade** [comment]
> Should this issue be solved after #382?

No.
