### ISSUE TITLE
Needed for PROD - check BUILD_IN_CONTAINER from ENV - Quick fix

### ISSUE THREAD

**Issue by MaximeAubanel** [weaveworks/weave#3830]
Hello, 

could you please in the main Makefile, change:

`BUILD_IN_CONTAINER=true` to `BUILD_IN_CONTAINER?=true`

In order for the variable to be taken from the ENV if it exists.

Thank you :)

**Comment by bboreham** [comment]
You know you can override it on the `make` command-line, right?

**Comment by MaximeAubanel** [comment]
I didn't know actually.

For those wondering too, this is how you do it: `make .net-plugin-arm64.uptodate BUILD_IN_CONTAINER=false`
