### ISSUE TITLE
Preserve old docker weaveworks images

### ISSUE THREAD

**Issue by marcindulak** [weaveworks/weave#3858]
## What you expected to happen?

Docker [announced](https://www.docker.com/pricing/resource-consumption-updates) that starting from November 1st 2020

```
If an image has not been pulled or pushed within 6 months, the image will be
marked “inactive.” Any images that are marked as “inactive” will be scheduled for
deletion. Only accounts that are on the Free individual or organization plans will be
subject to image retention limits. 
```

This may affect the images from https://hub.docker.com/u/weaveworks, and it would be great if the old images can be preserved.

The same docker announcement mentions:

```
If you have a Free account, you can easily upgrade to a Pro or Team account
starting at $5 per month with an annual plan.
```

**Comment by bboreham** [comment]
Can you give an example of an image that nobody has used in 6 months that needs to be preserved?

Weaveworks does have a paying account; I don't think you should worry, but I am interested in what specific name or tag you were thinking of.

**Comment by marcindulak** [comment]
I'm thinking about https://hub.docker.com/r/weaveworks/weave-kube and https://hub.docker.com/r/weaveworks/weave-npc which are pulled by default configurations of legacy kops versions.

**Comment by bboreham** [comment]
If they are pulled by kops then surely they do not meet the condition “not been pulled or pushed within 6 months”.

**Comment by marcindulak** [comment]
Docker says in the announcement that

```
a new dashboard will also be available in Docker Hub that offers the ability to view the status of all of
your container images in all repositories within your account
```

There may still be old kops clusters and someone may decide to add another worker to such a cluster to realize that the weave images are gone.

Kops automatic tests https://testgrid.k8s.io/kops-versions go back to k8s 1.11 still, but I don't see they test weave.

**Comment by bboreham** [comment]
OK, thanks for clarification.
