### ISSUE TITLE
Weave container falls into a bad state with readiness probe failures and unable to recover

### ISSUE THREAD

**Issue by mattmelgard** [weaveworks/weave#3866]
## What you expected to happen?

Weave not to get into a bad state on the node

## What happened?

Every so often a single weave pod on our development cluster will go into a wonky state and cause pods to get stuck in container creating and init phases when they try to schedule to the node. The first sign we usually see for this is that a weave pod will be in `Running` state but with `1/2` containers ready:

```
kubectl get pods -n kube-system -o wide
NAME                                                                  READY   STATUS    RESTARTS   AGE     IP               NODE                                           NOMINATED NODE   READINESS GATES
weave-net-w725d                                                       1/2     Running   5          55d     172.20.52.135    ip-172-20-52-135.us-west-2.compute.internal    <none>
```

What we see in the describe output for the weave pod in question is this:

```
Events:
  Type     Reason     Age                     From                                                  Message
  ----     ------     ----                    ----                                                  -------
  Warning  Unhealthy  3m17s (x3631 over 10h)  kubelet, ip-172-20-112-17.us-west-2.compute.internal  Readiness probe failed: Get http://127.0.0.1:6784/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Individual containers in the weave pod describe output look as follows:

```
  weave:
    Container ID:  docker://022a374421303d46afb9b35110172c2711ed0ebf6cca1721339f6dd2cecb4c5f
    Image:         weaveworks/weave-kube:2.6.5
    Image ID:      docker-pullable://weaveworks/weave-kube@sha256:703a045a58377cb04bc85d0f5a7c93356d5490282accd7e5b5d7a99fe2ef09e2
    Port:          6782/TCP
    Host Port:     6782/TCP
    Command:
      /home/weave/launch.sh
    State:          Running
      Started:      Tue, 01 Sep 2020 19:05:58 -0600
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  200Mi
    Requests:
      cpu:      50m
      memory:   200Mi
    Readiness:  http-get http://127.0.0.1:6784/status delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      HOSTNAME:        (v1:spec.nodeName)
      IPALLOC_RANGE:  100.96.0.0/11
      WEAVE_MTU:      8912
    Mounts:
      /host/etc from cni-conf (rw)
      /host/home from cni-bin2 (rw)
      /host/opt from cni-bin (rw)
      /host/var/lib/dbus from dbus (rw)
      /lib/modules from lib-modules (rw)
      /run/xtables.lock from xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from weave-net-token-tw7hm (ro)
      /weavedb from weavedb (rw)
  weave-npc:
    Container ID:   docker://a3a7f080c0a828d55f8208c8b72dd2aaaffba8fc1bded3d9efd0e82453136e3a
    Image:          weaveworks/weave-npc:2.6.5
    Image ID:       docker-pullable://weaveworks/weave-npc@sha256:0f6166e000faa500ccc0df53caae17edd3110590b7b159007a5ea727cdfb1cef
    Port:           6781/TCP
    Host Port:      6781/TCP
    State:          Running
      Started:      Tue, 13 Oct 2020 15:06:41 -0600
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    1
      Started:      Thu, 03 Sep 2020 14:46:38 -0600
      Finished:     Tue, 13 Oct 2020 15:06:39 -0600
    Ready:          True
    Restart Count:  3
    Limits:
      memory:  200Mi
    Requests:
      cpu:     50m
      memory:  200Mi
    Environment:
      HOSTNAME:   (v1:spec.nodeName)
    Mounts:
      /run/xtables.lock from xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from weave-net-token-tw7hm (ro)
```

When describing pods that are stuck on the node we see things like this:
```
 Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "3e90c1f89e752030f4544ffe1e4da489f575803e1d93e469d265e1a5c85c08cd" network for pod "frontend-7769d67758-k7hbs": networkPlugin cni failed to set up pod "frontend-7769d67758-k7hbs_gsirois" network: unable to allocate IP address: Post http://127.0.0.1:6784/ip/3e90c1f89e752030f4544ffe1e4da489f575803e1d93e469d265e1a5c85c08cd: dial tcp 127.0.0.1:6784: i/o timeout, failed to clean up sandbox container "3e90c1f89e752030f4544ffe1e4da489f575803e1d93e469d265e1a5c85c08cd" network for pod "frontend-7769d67758-k7hbs": networkPlugin cni failed to teardown pod "frontend-7769d67758-k7hbs_gsirois" network: Delete http://127.0.0.1:6784/ip/3e90c1f89e752030f4544ffe1e4da489f575803e1d93e469d265e1a5c85c08cd: dial tcp 127.0.0.1:6784: i/o timeout]
```

## How to reproduce it?
Unknown at this time

## Anything else we need to know?

Our clusters run in AWS using KOPS

## Versions:

* Kubernetes: `v1.16.10`
* Docker: `18.09.9`
* OS (`uname` output): `Linux ip-172-20-101-51 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux`
* Weave image tag: `weaveworks/weave-kube:2.6.5`

## Logs:

I've got a gist setup for the weave and weave npc container logs below:

1. [weave container](https://gist.github.com/mattmelgard/25acdcb6868c2f77dd66eb47977ffd6b)
2. [weave-npc container](https://gist.github.com/mattmelgard/530a114a47be862108532e47a5195a6f)

But as far as I can tell I don't see anything glaringly out of place there. Please also note that I've redacted the MAC addresses in the weave container logs, but I can provide a log file with those added back in if necessary

Also, I can provide the full logs for the kubelet, host dmesg output and host docker daemon if need be but I'd like to provide those only as they're requested. I can also provide the node describe output in a gist if needed but from looking at it myself I didn't see anything obvious there (ie no events, or bad statuses)

In my own investigation I was only really able to find kubelet logs that seemed to indicate that there was a problem occurring with CNI. Specifically this log message stood out as correlating perfectly with the outage of the weave pod:

```
"weave-cni: unable to release IP address: Delete http://127.0.0.1:6784/ip/78527467a9b15eb90d952146d0259c8319e630d56dc4324593636dea2b412195: dial tcp 127.0.0.1:6784: i/o timeout",
```

but that seems to just be a symptom of CNI being unavailable on the node and not a cause.

## Further Notes

1. I'm still doing an investigation on my part but it would be helpful to have some guidance on what to look for and where. In looking myself I just haven't been able to really find a smoking gun.

2. In the past I have gotten the weave pod to recover but only by restarting the docker daemon on the host and deleting the iptables lock. Unfortunately because this issue tends to severely impact our engineering org's velocity when this happens I'm unable to get much time with the node in question before having to cordon and drain the node leading to its eventual demise at the hands of the cluster autoscaler.

3. An interesting thing to note is that we use the same version of weave on our staging cluster, but we have not seen this issue occur there as of yet. The major difference between the two clusters is size with our dev cluster having around 100 nodes at any given time and the staging cluster having around 45 nodes. There's also significantly more churn on the dev cluster with development environments for all of our engineers being constantly deployed and re-deployed as well as ephemeral CI workers.

**Comment by mattmelgard** [comment]
Looking at this a bit further it almost seems like the Readiness/Liveness probe failures are the first indication of failure from the perspective of the Kubelet. By all other accounts it appears as if the weave pod is in working order but trying to reach the `/status` endpoint results in a timeout, even when running it from within the running weave container:

```
/home/weave # curl 127.0.0.1:6784/status
curl: (7) Failed to connect to 127.0.0.1 port 6784: Operation timed out
```

**Comment by bboreham** [comment]
This message suggests to me that the `weave` container has hung:

> Readiness probe failed: Get http://127.0.0.1:6784/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

In the logs you supply, one ends at `2020-11-04T05:25:48` while the other ends at `2020/11/04 17:26:27`, which is consistent with the first one hanging.

Can you send the process a SIGQUIT and see if it dumps a stack trace to the log?

Other things of interest:

>     Image:         weaveworks/weave-kube:2.6.5

Can you try the latest release?

>      Reason:       OOMKilled

Do you have metrics (e.g. Prometheus) saying how big it was at the time it was killed?  Can you check how big it is now?

**Comment by mattmelgard** [comment]
@bboreham I'm realizing I may have posted up the wrong logs for the weave container which is why the timestamp ends where it does. The logs I posted for that were from our cloudwatch log stream, which for some reason gets cut off prematurely.

I'll post up the logs that were obtained from the host as well so that you have a more complete picture, but from what I saw the pod was still logging normally when I tailed the docker logs on the host after the readiness probes had begun failing.

As for memory usage, here's a bit of a snapshot from the day of as well as leading up to the event in question (timestamps are in in Mountain Time (Denver, USA)):

<img width="1348" alt="Screen Shot 2020-11-20 at 3 21 33 PM" src="https://user-images.githubusercontent.com/14903000/99855730-b20e8a80-2b44-11eb-8ecb-c60d0b0ecd6c.png">
<img width="1346" alt="Screen Shot 2020-11-20 at 3 20 10 PM" src="https://user-images.githubusercontent.com/14903000/99855734-b5097b00-2b44-11eb-93ce-94201fe95af8.png">

Unfortunately this pod is no longer around since we eventually killed the node, but this does seem to happen at least once a week in our development cluster so I'll be sure to cordon and isolate it so I can try issuing a SIGQUIT as well as another actions you suggest.

I don't know how feasible it will be to update the version of weave since we would like to keep it in sync with our production and staging clusters, but I'll float the idea to my team. Would that just be `2.7.0`? Is there a particular bug/issue you're thinking that will address?

**Comment by dntosas** [comment]
We had the same problems with latest release `2.7.0` on Kops Clusters. 

Increasing the requested capacity for CPU/Memory (350m/400Mi) seems to solve the issue for us, until now ^^ cc @mattmelgard

**Comment by bboreham** [comment]
@dntosas could you say how big your cluster is?

We have a [recommendation](https://github.com/weaveworks/weave/blob/fb7fc7ddae2064ba3631f162f43eb2ae230f8c57/site/kubernetes/kube-addon.md#cpu-and-memory-requirements) to adjust the request, but even better if we can put some example sizes.

**Comment by dntosas** [comment]
for a 200 nodes cluster, we set the following on weave:
```yaml
  networking:
    weave:
      memoryRequest: 512Mi
      memoryLimit: 2048Mi
      cpuRequest: 300m

      npcMemoryRequest: 784Mi
      npcMemoryLimit: 2048Mi
      npcCPURequest: 300m
```

**Comment by mattmelgard** [comment]
@bboreham sorry for the late reply on this. I did up the memory requests and limits to `600Mi` (from `300Mi`) but I'm still seeing the same issue. We had two pods go into a bad state today, again on our development cluster with the same symptoms (continuous readiness probe failure). It doesn't seem to be related to the memory or CPU usage from what I can tell using the basic kubernetes mixin dashboards (pictured over `24h`, where the readiness probes began failing over the past `14h`):

<img width="1992" alt="Screen Shot 2020-12-17 at 12 53 14 PM" src="https://user-images.githubusercontent.com/14903000/102537788-a8efdb00-4068-11eb-93cb-f10d656eb669.png">
<img width="2048" alt="Screen Shot 2020-12-17 at 12 53 00 PM" src="https://user-images.githubusercontent.com/14903000/102537791-aab99e80-4068-11eb-9ca3-ca4a484efe22.png">

I did try to issue a SIGQUIT to the process, but I'm not sure if I'm hitting the correct one. PID 1 seems to be `/bin/systemd` and when I look for `weave-net` in the process list it appears to be one a bit further down in the process list. I tried to SIGQUIT both processes but didn't see anything interesting happen in the logs.

To respond to this point:

> In the logs you supply, one ends at 2020-11-04T05:25:48 while the other ends at 2020/11/04 17:26:27, which is consistent with the first one hanging.

I believe this may have just been due to me posting up the incorrect file, I believe the other one I have continues to the same timestamp as the other my apologies on that, I'll post up the full log.

**Comment by mattmelgard** [comment]
Here's the [gist](https://gist.github.com/mattmelgard/6f272328ebaf73b16308cbaabce74c30) for the more complete log of the weave container that I had mis-posted originally. You can see there that the timestamps continue to the same time as the weave-npc pod. Sorry for the mixup on that.

**Comment by mattmelgard** [comment]
Actually, one thing I did see just now while looking back through some of the logs for this most recent pod was that there was [a bit of stack trace output](https://gist.github.com/mattmelgard/a1c0aa39c34be66513008ec639d3ed99) from a `weave-npc` container that had exited.

**Comment by mattmelgard** [comment]
So, it looks like initially there was once more incident of this happening after increasing resource limits and requests, but things have actually been quite a bit more stable since then (going on about a month and a half). I'm going to call this resolved since I think the increase in resource limits and requests actually did seem to solve the problem.
