### ISSUE TITLE
Client IP Address not sent to ingress-nginx with weave 2.7.0

### ISSUE THREAD

**Issue by dbaylerg** [weaveworks/weave#3870]
## What you expected to happen?
I should receive the original Client IP Address from the Weave container

## What happened?
I am receiving the Weave container (kubernetes network) IP Address

## How to reproduce it?

I've been working for a week on this and need some help. No matter what I try I cannot seem to get the client IP address to my back-end service. The nginx ingress controller pod always log the client IP address ($remote_addr) as the cluster IP address of the weave container (verified with ip addr command on container). According to https://github.com/weaveworks/weave/releases/tag/v2.7.0 the NO_MASQ_LOCAL=1 is now on by default which is supposed to preserve client IP Address with externalTrafficPolicy = "Local"
But I still always get the cluster IP address from Weave.

Any help would be appreciated. Below is all the relevant information I could think of.

Bare Metal (VMs)

----- kubernetes version -----
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

---- kube-system namespace

kube-proxy:v1.18.1
weave-kube:2.7.0
weave-npc:2.7.0

--- Helm Chart -----

name: ingress-nginx
version: "3.11.0"
repository: "https://kubernetes.github.io/ingress-nginx"

----- override chart default values -----

defaultBackend:
  enabled: true
controller:
  replicaCount: 4
  service:
    externalTrafficPolicy: "Local"
    externalIPs:
      - 192.168.192.209 # VIP
      - 192.168.192.115
      - 192.168.192.215
      - 192.168.192.119
      - 192.168.192.219
  nodeSelector:
    dmz: "true"
  tolerations:
    - key: "dmz"
      operator: "Exists"
    effect: "NoSchedule"
  extraArgs:
    default-ssl-certificate: default/tls-ingress-controller
  config:
    proxy-read-timeout: "300"
    proxy-send-timeout: "300"
    enable-real-ip: "true"
    use-forwarded-headers: "true"

**Comment by maxisam** [comment]
I am using 2.8.0. It doesn't preserve the ip with externalTrafficPolicy = "Local"

**Comment by dbaylerg** [comment]
This is now working for me.  The only thing that I believe changed is the Kubernetes version from 1.18.1 to 1.19.4

----- kubernetes version -----

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

---- kube-system namespace

kube-proxy:v1.18.1
weave-kube:2.7.0
weave-npc:2.7.0

--- Helm Chart -----

name: ingress-nginx
version: "3.11.0"
repository: "https://kubernetes.github.io/ingress-nginx"

**Comment by maxisam** [comment]
well, I am on 1.19.4 with Weave 2.8.1
