### ISSUE TITLE
K3s cluster networking broken with weave

### ISSUE THREAD

**Issue by msimonelli331** [weaveworks/weave#3874]
## What you expected to happen?
Expected to be able to replace flannel with weave as a cni in a k3s cluster

## What happened?
Weave runs successfully but the networking in the cluster does not work. 

## How to reproduce it?
Install cni plugins manually

Start k3s with INSTALL_K3S_EXEC="--flannel-backend=none --no-flannel"

Deploy weave: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

Deploy a busybox container

Try to nslookp a pod outside the namespace (doesn't work), nslookup a pod inside the namespace (does work), nc a pod and port (doesn't work)

## Anything else we need to know?
CentOS 7.9.2009
k3s cluster installed as air gapped
Running containerd without docker

## Versions:
weave script 2.7.0

kubectl version:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s2", GitCommit:"f8a4547bec36b4d1597c19c86b5063756d4c150e", GitTreeState:"clean", BuildDate:"2020-10-30T19:30:45Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s2", GitCommit:"f8a4547bec36b4d1597c19c86b5063756d4c150e", GitTreeState:"clean", BuildDate:"2020-10-30T19:30:45Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

ctr --version:
ctr github.com/rancher/containerd v1.4.0-k3s1

## Logs:
weave:
INFO: 2020/12/07 21:46:37.198415 Command line options: map[conn-limit:200 datapath:datapath db-prefix:/weavedb/weave-net docker-api: expect-npc:true host-root:/host http-addr:127.0.0.1:6784 ipalloc-init:consensus=0 ipalloc-range:10.43.0.0/16 metrics-addr:0.0.0.0:6782 name:9a:ca:9e:1b:b4:41 nickname:localhost.localdomain no-dns:true no-masq-local:true port:6783]
INFO: 2020/12/07 21:46:37.198449 weave  2.7.0
INFO: 2020/12/07 21:46:37.609371 Bridge type is bridged_fastdp
INFO: 2020/12/07 21:46:37.609387 Communication between peers is unencrypted.
INFO: 2020/12/07 21:46:37.627977 Our name is 9a:ca:9e:1b:b4:41(localhost.localdomain)
INFO: 2020/12/07 21:46:37.628029 Launch detected - using supplied peer list: []
INFO: 2020/12/07 21:46:37.676966 Unable to fetch ConfigMap kube-system/weave-net to infer unique cluster ID
INFO: 2020/12/07 21:46:37.676994 Using "no-masq-local" LocalRangeTracker
INFO: 2020/12/07 21:46:37.676999 Checking for pre-existing addresses on weave bridge
INFO: 2020/12/07 21:46:38.061863 [allocator 9a:ca:9e:1b:b4:41] No valid persisted data
INFO: 2020/12/07 21:46:38.098964 [allocator 9a:ca:9e:1b:b4:41] Initialising via deferred consensus
INFO: 2020/12/07 21:46:38.099008 Sniffing traffic on datapath (via ODP)
INFO: 2020/12/07 21:46:38.118947 Listening for HTTP control messages on 127.0.0.1:6784
INFO: 2020/12/07 21:46:38.118961 Listening for metrics requests on 0.0.0.0:6782
INFO: 2020/12/07 21:46:38.267690 Error checking version: Get "https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=3.10.0-1160.6.1.el7.x86_64&flag_kubernetes-version=v1.19.3%2Bk3s2&os=linux&signature=8z%2Fr32b9VVwGa%2Fu7EvIrb%2B6oNttG8LMRFZ06flOcUxo%3D&version=2.7.0": dial tcp: lookup checkpoint-api.weave.works on 10.43.0.10:53: write udp 192.168.88.157:52189->10.43.0.10:53: write: operation not permitted
INFO: 2020/12/07 21:46:38.352033 [kube-peers] Added myself to peer list &{[{9a:ca:9e:1b:b4:41 localhost.localdomain}]}
DEBU: 2020/12/07 21:46:38.355981 [kube-peers] Nodes that have disappeared: map[]
INFO: 2020/12/07 21:46:38.385967 Assuming quorum size of 1
INFO: 2020/12/07 21:46:38.386041 adding entry 10.43.0.0/16 to weaver-no-masq-local of
INFO: 2020/12/07 21:46:38.386048 added entry 10.43.0.0/16 to weaver-no-masq-local of
10.43.0.1
DEBU: 2020/12/07 21:46:38.543569 registering for updates for node delete events

## Network:
default via x.x.x.x dev ens33 proto dhcp metric 100
10.43.0.0/16 dev weave proto kernel scope link src 10.43.0.1
x.x.x.x/24 dev ens33 proto kernel scope link src x.x.x.x metric 100

**Comment by aitorhh** [comment]
I am also experiencing the same issues. In that deployment (by default without flannel), kubernetes service is exposed by the service at IP 10.43.0.1:443 and mapped to the host IP as the external endpoint (<host>:6443).

In K3S, the API server is running with systemd as a host service k3s.  

**Working**: 
* access k8s API from the **host** using k8s service (curl -k https://10.43.0.1)
* access k8s API from the **host** using host endpoint (curl -k https://<host>:6443)
* access k8s API from a POD using host endpoint (wget https://<host>:6443)

**Not working**
* no access to the k8s API from a POD using kubernetes service (wget https://10.43.0.1)

So, my guess is that iptables is preventing the POD to access the API, but I haven't find the solution. Just doing some debuging with:
```
sudo iptables -A INPUT -s 10.32.0.1/12 -m limit --limit 5/min -j LOG --log-prefix "iptables dropped input" --log-level 7
sudo iptables -A INPUT -d 10.32.0.1/12 -m limit --limit 5/min -j LOG --log-prefix "iptables dropped input" --log-level 7
sudo iptables -A OUTPUT -s 10.32.0.1/12 -m limit --limit 5/min -j LOG --log-prefix "iptables dropped output" --log-level 7
sudo iptables -A OUTPUT -d 10.32.0.1/12 -m limit --limit 5/min -j LOG --log-prefix "iptables dropped output" --log-level 7
```
And by enabling all traffic from that subnet to INPUT and OUTPUT, it removed the dropped packages but it does not fix the problem.


I am sure that someone more experience with iptables/weave will find the solution straight away (assuming that the problem is what I mentioned)

**Comment by msimonelli331** [comment]
@aitorhh I think you can resolve it by changing the IPALLOC_RANGE in the weave yaml. By default weave uses 10.32.0.0/12 but I believe k3s uses 10.42.0.0/16. Update the yaml manually: https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#-changing-configuration-options

This should fix this issue. However, when I created an HA k3s cluster the cluster networking to agents broke. I had to move away from weave. I'm not sure if it's really compatible with k3s. To be fair it never promised to be.

**Comment by aitorhh** [comment]
Sorry for the late reply! Indeed that solve the issue. I've just had to configure the `IPALLOC_RANGE` to `10.42.0.0/16`.

Thanks a lot!
