### ISSUE TITLE
Weave IP range different than cluster and worker node IP range?

### ISSUE THREAD

**Issue by vinusorout** [weaveworks/weave#3895]
**REQUEST FOR HELP? **
I fund that the IP range used by weave is 10.32.0.0/12, I am new to kubernetes and got confused with following queries:

Q1: Can I change this IP range used by weave? If yes how, and does it need to be same as of my kubernetes cluster IP range(CLUSTER_CIDR = 10.200.0.0/16) OR service cluster ip range(SERVICE_CLUSTER_IP_RANGE = 10.32.0.0/24) OR worker node podCIDR(10.200.1.0/24) ?

Q2: Will there be any issue if I use weave IP range as 10.32.0.0/12 and different range for cluster ?

**Comment by mmerrill3** [comment]
For your daemon set in kubernetes, you can specify the environment variable IPALLOC_RANGE for the weave container, not the weave-npc container.

Like so:

- name: IPALLOC_RANGE
   value: 100.96.0.0/11

Yes, it can be different than your SERVICE_CLUSTER_IP_RANGE.  I'm not sure about your setup, but it can also be separate from your host network CIDR range from your cloud provider (the native CIDR range...).
