### ISSUE TITLE
Trying to add Jetson nano to Kubernetes cluster and weave network plugin is not ready. Is it Hardware issue?

### ISSUE THREAD

**Issue by igorkhazanov** [weaveworks/weave#3898]
Trying to create a k8 cluster with weave. Getting notReady for Jetson Nano node.

From my linux 20.4 laptop was able to connect to another linux box, Raspberry Pi. Trying to add Jetson Nano to the set.
used 
sudo swapoff -a
sudo kubead init
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

Run join command on all nodes. Every node except jetson nano is Ready, except Jetson Nano.

Run
kubectl get nodes
NAME              STATUS     ROLES                  AGE     VERSION
laptop3   Ready      control-plane,master   9h      v1.21.0
godeep-v2-2       Ready      godeep                 9h      v1.21.0
jetson01          NotReady   <none>                 108s    v1.21.0
pi01              Ready      pi01                   5h45m   v1.20.4

Run 
kubectl describe node jetson01
Name:               jetson01
Roles:              <none>
Labels:             beta.kubernetes.io/arch=arm64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=arm64
                    kubernetes.io/hostname=jetson01
                    kubernetes.io/os=linux
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 27 Apr 2021 17:12:51 -0500
Taints:             node.kubernetes.io/not-ready:NoExecute
                    node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  jetson01
  AcquireTime:     <unset>
  RenewTime:       Tue, 27 Apr 2021 17:15:01 -0500
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Tue, 27 Apr 2021 17:13:01 -0500   Tue, 27 Apr 2021 17:12:51 -0500   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Tue, 27 Apr 2021 17:13:01 -0500   Tue, 27 Apr 2021 17:12:51 -0500   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Tue, 27 Apr 2021 17:13:01 -0500   Tue, 27 Apr 2021 17:12:51 -0500   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Tue, 27 Apr 2021 17:13:01 -0500   Tue, 27 Apr 2021 17:12:51 -0500   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Addresses:
  InternalIP:  192.168.42.179
  Hostname:    jetson01
Capacity:
  cpu:                4
  ephemeral-storage:  61461244Ki
  hugepages-2Mi:      0
  memory:             4059272Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  56642682377
  hugepages-2Mi:      0
  memory:             3956872Ki
  pods:               110
System Info:
  Machine ID:                 a3d9197b765643568af09eb2bd3e5ce7
  System UUID:                a3d9197b765643568af09eb2bd3e5ce7
  Boot ID:                    d03c53a2-052a-4f66-bd7f-afbdff58d654
  Kernel Version:             4.9.201-tegra
  OS Image:                   Ubuntu 18.04.5 LTS
  Operating System:           linux
  Architecture:               arm64
  Container Runtime Version:  docker://20.10.2
  Kubelet Version:            v1.21.0
  Kube-Proxy Version:         v1.21.0
Non-terminated Pods:          (2 in total)
  Namespace                   Name                CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                ------------  ----------  ---------------  -------------  ---
  kube-system                 kube-proxy-fqm4d    0 (0%)        0 (0%)      0 (0%)           0 (0%)         2m13s
  kube-system                 weave-net-ddl5d     100m (2%)     0 (0%)      200Mi (5%)       0 (0%)         2m13s
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                100m (2%)   0 (0%)
  memory             200Mi (5%)  0 (0%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
  Type    Reason                   Age    From        Message
  ----    ------                   ----   ----        -------
  Normal  Starting                 2m13s  kubelet     Starting kubelet.
  Normal  NodeHasSufficientMemory  2m13s  kubelet     Node jetson01 status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    2m13s  kubelet     Node jetson01 status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID     2m13s  kubelet     Node jetson01 status is now: NodeHasSufficientPID
  Normal  NodeAllocatableEnforced  2m13s  kubelet     Updated Node Allocatable limit across pods
  Normal  Starting                 2m10s  kube-proxy  Starting kube-proxy.

**Comment by jonmahoney15** [comment]
@igorkhazanov I am having a similar issue did you resolve this?
