### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by c4milo** [weaveworks/weave#41]
I have a generic contributing guide for go projects if you want to use it: https://github.com/cloudescape/gowsdl/blob/master/CONTRIBUTING.md

**Comment by bboreham** [comment]
I made a draft at https://github.com/zettio/weave/wiki/Contributing; much of the development workflow is already at [WorkingOnWeave](https://github.com/zettio/weave/wiki/WorkingOnWeave), but we may want to specify differences for in-team and 3rd-party.

**Comment by inercia** [comment]
Maybe we could add something very simple about code style, ie, _you should run "go fmt" on your code_, _do not use dot-imports_ ;)

**Comment by squaremo** [comment]
How come you left out the code of conduct section?

**Comment by rade** [comment]
@errodeveloper came across a useful [meta contributing guide](https://github.com/nayafia/contributing-template).

**Comment by rade** [comment]
The guide @bboreham put together looks fine to me. If there are any specific issues we want to change about it, we can file fresh issues for those. -> closing.
