### ISSUE TITLE
Weave can re-try connections too quickly

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#412]
Example, from weave logs, where the next attempt occurs 80ms after the previous attempt:

````
20:59:34.196292 ->[104.236.19.13:59829] attempting connection
20:59:34.241031 ->[104.236.19.13:59829] error during connection attempt: dial tcp4 104.236.19.13:59829: connection refused
20:59:34.277109 ->[104.236.19.13:59829] attempting connection
````

This behaviour can generate a lot of uninteresting log lines, making troubleshooting difficult.

From inspection of connection_maker.go, the time intervals are randomized, so could be very tiny.  Suggest we add a minimum delay of a few seconds to the next interval in `tryImmediately()`.

**Comment by achanda** [comment]
How about exponentially backing off? Like https://github.com/cenkalti/backoff

**Comment by bboreham** [comment]
It already d

**Comment by bboreham** [comment]
It already does exponential backoff. I am suggesting to tweak the behaviour.

**Comment by rade** [comment]
The code referenced by @achanda actually is not the the [traditional exponential backoff](http://en.wikipedia.org/wiki/Exponential_backoff). In particular, the lower bound for the backoff interval gets increased exponentially too.

**Comment by fermayo** [comment]
+1

**Comment by rade** [comment]
So there is actually a bug here... There's a 1/(2^63) chance that we will randomly choose an initial retry interval of 0, and thus retry immediately, indefinitely.

**Comment by rade** [comment]
> 1/(2^63)

Actually the odds are 1/(5*10^9), since the initial interval is 5 seconds and durations are represented in nanoseconds.
