### ISSUE TITLE
shrink top-level dir by moving exe/image sub-dirs

### ISSUE THREAD

**Issue by dpw** [weaveworks/weave#420]
I have an idea to simplify the structure of the weave repo, and make things more uniform.

Currently, we have the 'router' directory, and a corresponding 'weaver' directory for the weave container Dockerfile (and main.go). Then we have the 'nameserver' directory, and a corresponding 'weavedns' directory containing the weavedns container Dockerfile (and main.go).  It's not hugely confusing, but it does lead to an impression of clutter in the top-level directory of the repo.

It would be nice to reduce that clutter.  It would be nice if the names of the directories containing Dockerfiles uniformly matched the container image names.  And one day it might be nice to have a go package name that is the same as a container name.

So I suggest moving:

* weaver -> containers/weave
* weavedns -> containers/weavedns
* tools -> containers/tools
* (And build -> containers/build if #387 gets merged)

And updating the makefile and any other references, of course.

**Comment by rade** [comment]
Seems reasonable. Not sure about 'containers'. 'images'? (might be too ambiguous) 'docker'?

**Comment by squaremo** [comment]
Sounds good to me. I'm in favour of `docker/weave` etc. Would we move the Makefile and (very docker-specific) `weave` script into docker/ as well?

**Comment by dpw** [comment]
> Would we move the Makefile and (very docker-specific) weave script into docker/ as well?

Yeah, makes sense.

The 'docker specifics are under docker/' picture will be slightly spoiled by the main.go files. I guess the only reason they are not in the router and nameserver dirs is because of go fussiness. But we can move them out later if the need arises.

**Comment by rade** [comment]
>> Would we move the Makefile and (very docker-specific) weave script into docker/ as well?
> Yeah, makes sense.

Does it? Call me old-fashioned, but I do quite like projects to have a Makefile at the top level.

As for the weave script, it's by far the most prominent piece of code in weave that people may actually a) download, and b) look at. So let's not hide it in a sub-dir.

Also, scope creep.

**Comment by squaremo** [comment]
> Also, scope creep.

The suggested renaming strongly suggests that the spirit of the re-org is to put container-related stuff in a subdirectory. The Makefile and weave script are container-related.

> Does it? Call me old-fashioned, but I do quite like projects to have a Makefile at the top level.

That would make sense if the top-level makefile was making the "ultimate" product of the repo -- but it's not, it drives the docker builds.

> As for the weave script, it's by far the most prominent piece of code in weave that people may actually a) download, and b) look at. So let's not hide it in a sub-dir.

This is a fair argument though -- until there's different, supported ways of deploying weave.

**Comment by rade** [comment]
> The makefile [...] drives the docker builds.

It does more than that. It builds everything that there is to build. And yes, some targets modify the local docker state. That is fine until we have non-docker weaves.

**Comment by rade** [comment]
Actually, thinking about the directory naming again, IMO it is actually wrong to move weaver et al into a sub-directory that implies containers. The dirs contain code for a) an exe, and b) packaging that exe in an image. The [established convention](http://dave.cheney.net/2014/12/01/five-suggestions-for-setting-up-a-go-project), based on [how go itself packages multiple exes](https://code.google.com/p/go/source/browse/?repo=tools) is to have a `cmd` dir. Now, that may be perhaps be misleading the other way. `cmd-and-associated-docker-image`. urgh.

**Comment by squaremo** [comment]
> Now, that may be perhaps be misleading the other way. cmd-and-associated-docker-image. urgh.

Or, `cmd/blah` in one place, and `docker/blah/Dockerfile` in another.

**Comment by rade** [comment]
> Or, `cmd/blah` in one place, and `docker/blah/Dockerfile` in another.

Right. I did consider that. But that way we end up with yet more directories containing just a single file.

**Comment by dpw** [comment]
> The suggested renaming strongly suggests that the spirit of the re-org is to put container-related stuff in a subdirectory. The Makefile and weave script are container-related.

It might be nice to keep a top-level Makefile that just knows how to build the go code and run local tests.  Then under `docker/` have another Makefile that knows how to package it up into docker containers.

**Comment by rade** [comment]
> It might be nice to keep a top-level Makefile that just knows how to build the go code and run local tests. Then under `docker/` have another Makefile that knows how to package it up into docker containers.

This does imply having a separate `cmd/blah` dir tree as discussed above, with the dir proliferation that entails, since it would be just wrong for the top-level Makefile to reach into a `docker` sub-dir in order to build exes that have nothing to do with docker.

It also requires the Makefile under `docker/` to "reach up and then down" in the directory tree, which I thoroughly dislike. And we end up with two Makefiles.

This all hardly seems to fit the original objective to "simplify the structure".

**Comment by dpw** [comment]
> This does imply having a separate cmd/blah dir tree as discussed above, with the dir proliferation that entails, since it would be just wrong for the top-level Makefile to reach into a docker sub-dir in order to build exes that have nothing to do with docker.

Yes.

> It also requires the Makefile under docker/ to "reach up and then down" in the directory tree, which I thoroughly dislike.

This is what any packaging tends to imply.  Spec files, `debian/` gubbins, etc.

We could move the go stuff into a `go/` sbudirectory, in which case the docker bits would be reaching across rather than up.  Do you dislike that any less thoroughly?

> And we end up with two Makefiles.

They would have different concerns.  I'm not sure how that is different from saying "we end up with two source files".

> This all hardly seems to fit the original objective to "simplify the structure".

It's not a whole lot more work, once one considers the overheads of getting something merged, and if it's worth doing, why not do it?

**Comment by rade** [comment]
So the proposal here then is:

1. create a `cmd` (or `exe`?) sub-directory and a `docker` sub-directory
2. move all the exisiting 'main.go' into per-exe sub-dirs of the former, and all the existing Dockerfiles into per-image sub-dirs of the latter
3. move the docker-related portions of the current Makefile into a Makefile in the `docker` sub-directory

Correct?

It is not clear from the above what the relationship between the two Makefiles is. Say I want to build & publish new images. Can I do that with a single `make` invocation, as now? If so, on what Makefile?

TBH, this all feels like an awful lot of work for little gain.

**Comment by rade** [comment]
Since we now have a few binaries that don't go in their own docker image, the "move every dir with a `main.go` under a `cmd` sub-dir" idea no longer seems that bad. So I suggest we do that, and nothing else.
