### ISSUE TITLE
attach weave during builds?

### ISSUE THREAD

**Issue by anandkumarpatel** [weaveworks/weave#424]
Hi quick question

is there a way to attach weave network to containers started with `docker build .` ?

**Comment by bboreham** [comment]
I'm not sure I quite understand - you want to be able to access the weave network whilst commands in a Dockerfile are running?

I don't think this is straightforward, and we've certainly never tried.  The `docker build` runtime is not set up like a regular Docker container, and there is quite a debate about extending it, e.g. at https://github.com/docker/docker/pull/9176.

**Comment by anandkumarpatel** [comment]
hacked up implementation can be found here https://github.com/anandkumarpatel/weave

**Comment by anandkumarpatel** [comment]
If this seems like a feature you would like I can clean it up. I have a use case for this. we have certain services which expose files which should only be accessible in a weave network. would also help with things like `rake db migrate` which require access to a db during build process.

**Comment by rade** [comment]
Have you tried running a build via the weave proxy? I wonder whether that would automatically attach build containers to the weave network.

**Comment by anandkumarpatel** [comment]
@rade  just tried it now, no dice. from the docs http://docs.weave.works/weave/latest_release/proxy.html#setup
```
Usage
When containers are created via the weave proxy, their entrypoint will be modified to wait for the weave network interface to become available. When they are started via the weave proxy, containers will be automatically assigned IP addresses and connected to the weave network. We can create and start a container via the weave proxy with
```
it looks like it only modifies `entrypoint` which is not available during a docker build.

**Comment by bboreham** [comment]
I note that the argument over at https://github.com/docker/docker/pull/9176 is still raging.

Your approach of watching the Docker build output is ingenious, if somewhat fragile.  Maybe we can extend the proxy in similar spirit, so it does work during build?

Why modify the Dockerfile?  If it only ever works under weave, why not put the wait-for-ethwe stuff in plain sight?

**Comment by anandkumarpatel** [comment]
@bboreham agreed, super fragile. just following linux philosophy to use output stream of one program into another :) so hopefully it wont change much. one edge case is when that line appears in the output of someones `RUN ` step.

> Maybe we can extend the proxy in similar spirit, so it does work during build?

I am not familiar with weave proxy but it should be possible if it has access to the build stream, if it does not then I am not sure how to get the context (ip/subnet to put each build step in)

> Why modify the Dockerfile? If it only ever works under weave, why not put the wait-for-ethwe stuff in plain sight?

It was just some suger incase users did not know how to wait for ethwe, it can be removed. and put in some documentation.

**Comment by bboreham** [comment]
This feature was added by Docker in https://github.com/docker/docker/pull/27702
