### ISSUE TITLE
support systems with older versions of `iptables` and `ip`

### ISSUE THREAD

**Issue by kenshin54** [weaveworks/weave#45]
I got error `RTNETLINK answers: Operation not supported` while running `weave launch 10.0.0.1/16`. Weave script use ip and iptables command to create bridge and nat rule. It seems ip command doesn't support bridge type on CentOS 6.5. And iptables doesn't support `-C` flag also.

Maybe we can use brctl as a backup method to create a bridge and check nat rule with delete then append to mitigate the issue.

**Comment by bboreham** [comment]
Docker now requires at least kernel 3.10; closing.
