### ISSUE TITLE
set up app container networking before containers start

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#47]
Currently 'weave run' sets up the app container's interface into the weave network *after* the container has been launched with 'docker run -d'. That means the network may not be available to the container process straight away. Depending on what the container is doing, that can be benign, annoying, or disastrous.

Containers can themselves ensure that the interface is available, by running s.t. like https://github.com/jpetazzo/pipework/blob/master/pipework#L30, i.e.

    while ! grep -q ^1$ /sys/class/net/ethwe/carrier 2>/dev/null
    do sleep 1
    done

before starting the actual container process, but this of course requires containers to have been constructed with weave in mind, which is limiting.

There is no way around this issue w/o some changes to docker.

**Comment by rade** [comment]
One challenge with the "rewrite entrypoint to a volume-mounted exe" approach is making it work when we don't have direct access to the docker host and instead run weave itself in a container (as per #312)? Where would the exe live s.t. we can volume-mount it into containers?

The answer is `--volumes-from`... As part of `weave launch` we start a named container that copies the required exe into a volume created with `-v`. For example,  we could add the exe, and the program to copy it, to the weavetools image, in which case we would start that container with something like `docker run --name weavetools -v /home/weave zettio/weavetools /bin/copy-entrypoint-exe /home/weave`. We can then start all other containers with `--volumes-from=weavetools`.

Note that weavetools doesn't need to remain running for this to work, though the container needs to continue to exist. We'd need to take care of removing it with `docker rm -v` on `weave stop`.

**Comment by rade** [comment]
Trying to extract the orginal entrypoint from the command line (in case it was specified there), and determining the image from the command line (so we can lookup the entry point specified in that), is fiendishly hard. Go's option parser library `flag`, which is what docker uses, allows options to be specified in a myriad of ways. Moreover, there is no generic parsing function; parsing requires a specification of all the options. This not not just a matter of missing APIs; the option grammar is ambiguous in the absence of an option specification - consider the difference between `docker run -i a b` (`a` is the image and `b` is the command) and `docker run -h a b` (`a` is the host and `b` is the image).

The best option I can think of here is to invoke docker's `runconfig.Parse` function. This performs nearly all of the `docker run` option parsing and appears to require little/no context. However, it is missing some options, because the function is also used to for parsing `docker create`, so any options not shared with `docker create` would have to be added by us before invoking the function.

Furthermore, the whole thing is highly version specific; there's probably not been a single docker release when the `docker run` options haven't changed.

Finally, there is no pretty-printer, so one cannot, say, parse a command line, then remove/add/modify some options, and then produce a modified command line. Which is what we need to do here.

**Comment by errordeveloper** [comment]
> Trying to extract the orginal entrypoint from the command line (in case it was specified there), and determining the image from the command line (so we can lookup the entry point specified in that), is fiendishly hard.

Am I understanding right that this implies `docker run --entrypoint=foo` will not reflect `.Config.Entrypoint`? This doesn't look like it's been reported yet, is it considered a feature?

Separately from "entrypoint" overwriting approach, have we considered `docker pause` (or `SIGSTOP`) with consequent `docker unpause` (or `SIGCONT`) approach? The question is whether set-up of network namespace continues while container process is paused?

**Comment by binocarlos** [comment]
Hey guys sorry for delay have been out of action for a coupla months...

@rade Great idea r.e. mounting the exe from a volume - makes this whole thing much more portable and allows the exe to be distributed as a container.

It's mad how fiendishly hard parsing the `docker run` args can be - I made start in go (which is new for me) and hit that same problem of 'where do the docker arguments end and container arguments begin'

Had not thought of using dockers `runconfig.Parse` however - that plus some extra wrapping in it's own go library called `parse-docker-args` would be a good start - I will pick this up again this week and see where my beginner golang skills get me :) 

@errordeveloper pausing the container would be great if it works!

The challenge I suppose would be how to check `/sys/class/net/ethwe/carrier` from the outside of the container and if the initiation of the network continues for a paused container.

**Comment by rade** [comment]
@errordeveloper 

> Am I understanding right that this implies docker run `--entrypoint=foo` will not reflect .Config.Entrypoint? This doesn't look like it's been reported yet, is it considered a feature?

Not sure what you mean. The whole point of `--entrypoint` is to be able to override the entrypoint configured in the image.

> have we considered `docker pause` (or `SIGSTOP`) with consequent `docker unpause` (or `SIGCONT`) approach?

That's just racy; there's no way to guarantee we'd be able to pause the container before it attempts to access the network.

**Comment by rade** [comment]
@squaremo suggested an alternative technique for modifying the entrypoint: run a docker proxy. i.e. a process (in a container, naturally) that the `weave` script would perform all docker actions on (using `DOCKERHOST=... docker ...` or `docker -H ...`), and that forwards requests/responses to/from the real docker daemon. In the process it could rewrite the entrypoints, which, since it is speaking the docker remoting protocol, are easy to pick out and modify.

That same proxy could also take care of #251.

**Comment by binocarlos** [comment]
@rade yes the proxy would be a great way to bypass the cli arguments issue - I've been messing with a [docker proxy in node](https://github.com/binocarlos/mdock) - mdock - and it works a treat because as you say, the arguments are now in nice, already processed JSON format.

When doing this, I had lots of fun and games realizing that `docker run` was (as #251 points out) in fact a sequence of commands rather than a single action.

So perhaps I can make a simple container based on `mdock` to quickly test this idea (which feels much better than command line processing the arguments).

**Comment by lukemarsden** [comment]
@binocarlos Do you have a fork of `mdock`? It looks like it's meant for single-host <=> many-hosts, rather than single-host docker API proxying.

I'm working on my own single-host Docker proxy in Twisted, but would be curious to see the node version.

**Comment by binocarlos** [comment]
@lukemarsden I've published `mdock` onto npm [here](https://www.npmjs.com/package/mdock) (so `npm install mdock` will grab the code locally).  You are right though - it's trying to be a single entry point to multiple docker servers - not the single destination proxy we need here.

Slight distraction: I had originally called this library `flocker` (as in flock of dockers) - then I realised clusterhq existed and so renamed it to `mdock` (multiple dockers) - you are welcome to take over the npm package `flocker` at any time :)

@rade  - here is a rough plan for the proxy I have in mind - I have no idea if a) it will work or b) how it might integrate into weave so feedback is welcome!

We need a container that can be named 'weave-proxy' and:

 * has the `weave` command
 * has `--net=host -v /proc:/hostproc` so weave can mess with the system (i.e. #230)
 * has access to the docker host (via HTTP 2375 or mounted `/var/run/docker.sock`)
 * publishes a tcp port and listens for HTTP (.e.g. port 2475)

We need another container that contains a `wait-for-weave` binary in a volume.  This binary will wait for the weave network to be ready and then execute its arguments as a command.  So `echo "weave rocks"` becomes `wait-for-weave echo "weave-rocks"`.  Any container that has '--volumes-from=wait-for-weave' can then access that binary.

The HTTP proxy port (2475) will forward all requests to the docker server (2375) by default.  Any requests to `POST /containers/create` will be intercepted and the JSON packet processed as follows:

 * add a `--volumes-from=wait-for-weave`
 * change the entry-point to `wait-for-weave $@`

Any requests to `POST /containers/:id/start` will:

 * ensure the entry-point is `wait-for-weave $@`
 * extract $CIDR from the env or auto-create it
 * forward the request to the docker server
 * the container is now running but blocked by `wait-for-weave`
 * capture the returned $CONTAINER_ID
 * run a `weave with_container_netns $CONTAINER_ID attach $CIDR` style command
 * run a `weave tell_dns PUT $CONTAINER_ID $CIDR` command
 * return the $CONTAINER_ID to the docker client

We point the docker client at our proxy:

```bash
$ export DOCKER_HOST=tcp://127.0.0.1:2475
```

Now we can run long-lived servers:

```bash
$ docker run -d --env WEAVE_CIDR=10.0.1.10/24 mystack/mysql
```

And interactive jobs:

```bash
$ docker run --env WEAVE_CIDR=10.0.1.11/24 ubuntu bash -c "ping 10.0.1.10"
```

The interactive job will be blocked by `wait-for-weave` before attempting to ping 10.0.1.10. 

There are a couple of problems I can see:

 * point number 3 from #230 - i.e. how do we know what CIDR address to instruct weave with
 * returning the $CONTAINER_ID to the docker client before `wait-for-weave` has run the container's original entry point (perhaps adding a delay might help)

I'll give this a try this week and discover all the things that I've missed out :)

**Comment by lukemarsden** [comment]
@binocarlos Thanks for this. By the way, do you live in Bristol? (So do I...)

**Comment by binocarlos** [comment]
@lukemarsden No problem - yes I live in Bristol - its a great city!

Perhaps I should come and say hello sometime - I met Richard Wall a few months ago @ a meetup in the engine shed and he was telling about what you guys were doing upstairs.

**Comment by binocarlos** [comment]
I'm making good progress with a container that:

 * runs weave from inside a container
 * presents a docker API proxy that will
    * rewrite the entry-point for /containers/create
    * add `--volumes-from=weavetools`
 * will run weave `attach` before returning the container id for /containers/:id/start

In the meantime - I've uploaded [wait-for-weave](https://github.com/binocarlos/wait-for-weave) which is the golang program that will wait for `/sys/class/net/ethwe/carrier` before running its args as a command.

This binary is what will be mounted in a volume in a container called `weavetools`

@rade if you could check this (golang being very new to me) I would be most grateful :)

**Comment by rade** [comment]
@binocarlos you may want to use [`EnsureInterface`](https://github.com/zettio/weave/blob/c7701a20b5f7e03a6a17b0876eb6ab30ca6f13fa/net/if.go#L9)

**Comment by binocarlos** [comment]
@rade thanks! - that is far more civilized :)

I've added an exit with a non-zero code if it decides there is no `ethwe` to be found - I'm assuming this is a good plan rather than try to run the entrypoint anyway.

**Comment by rade** [comment]
> I've added an exit with a non-zero code if it decides there is no `ethwe` to be found - I'm assuming this is a good plan rather than try to run the entrypoint anyway.

Agreed.

**Comment by tangzhankun** [comment]
Hi, @rade 
Is there any update in docker that can let docker wait for NIC ready in a Docker way? I searched but only found this thread is almost same with what I needs. I saw that you are using another container to replace entrypoint and then run the original one after weave device ready.

**Comment by rade** [comment]
@tangzhankun The answer is Docker Network Plugins. Which obviously does a whole lot more than just wait for an entrypoint.

**Comment by tangzhankun** [comment]
hi, @rade 
oh. Thanks for the quick reply. Writing a plugin is obviously overkill for my needs. I think using the wait in entrypoint is enough. BTW, if I want to wait custom NIC name, like eth0, or if0. Will wait-for-weave support this in the future? Or I should build a wait-for-NIC?

**Comment by rade** [comment]
>  if I want to wait custom NIC name, like eth0, or if0. Will wait-for-weave support this in the future? Or I should build a wait-for-NIC?

Submit a PR :) This should be a straightforward extension.

**Comment by tangzhankun** [comment]
hi, @rade 
:) I'll do it if I have time in the future. Haha. Thanks again.

**Comment by apassi** [comment]
Is there somekind summary, what is correct solution to fix this. There is situations like DNS server in docker & weave networks, which needs to be up and running before other containers in reboot.

**Comment by marccarre** [comment]
@apassi, what are you looking for exactly?

Weave Net's [Docker proxy](https://www.weave.works/docs/net/latest/weave-docker-api/) already waits for the NIC to be ready before your container gets started, and Weave Net's [Docker plugin](https://www.weave.works/docs/net/latest/plugin/) relies on Docker to do that, but leads to the same outcomes, so all dependencies should be ready by the time your container's `ENTRYPOINT` gets run.

**Comment by apassi** [comment]
Basically i like to understand how weave and containers handle host's reboot situation. I havent able to find any "internals" document about weave. After i run weave launch, there seems to run new weave related containers, weavedb etc. but i havent been able to find documents for those..

**Comment by marccarre** [comment]
@apassi, I understand what you meant now, thanks clarifying it.
Indeed, details on the internals of Weave Net, when present at all, are very much diluted in the online user docs. You can find lower-level details in our [developers docs](https://github.com/weaveworks/weave/tree/master/docs), but ultimately the code is the source of truth.

If you think a "Weave Net's internals" documentation could be useful, feel free to [open a new GitHub issue](https://github.com/weaveworks/weave/issues/new) (as this is unrelated to this one) and to list exactly what you would like to see there, since as developers, we are biaised and may think some details are obvious. Thanks!
