### ISSUE TITLE
make use of DNS throughout the documentation

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#471]
ATM the weaveDNS documentation is completely separate from the main documentation, with just the odd reference to it from the latter. This was desirable when weaveDNS was new and experimental, but now it actually hinders adoption.

The weave 1.0 walkthrough in #242 presents a much more integrated view of weaveDNS, and hence can serve as guidance for this issue, though we won't be able to go quite as far until a few more features have landed.

**Comment by rade** [comment]
What is happening with this?

**Comment by rade** [comment]
I've just noticed that our [main docs page](http://docs.weave.works) does not mention WeaveDNS at all!

**Comment by errordeveloper** [comment]
@rade I believe this should still be open, [as you said](https://github.com/weaveworks/weave/pull/651#issuecomment-101594629).

**Comment by rade** [comment]
Where we want to get to here is that pretty much all our examples in the docs use names instead of IP addresses for addressing containers.

Ideally we want to tackle this after #383, #749, #750, #762, #763.

It is also related to #869.
