### ISSUE TITLE
check that subnets aren't in use

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#480]
Several users have run into problems with weave by accidentally picking CIDRs in `weave run` or `weave expose` for networks which are in use by the host.

We could perform some basic checks to prevent common cases of that, i.e. check overlaps with other interfaces and routing table entries on the host.

I guess this may be partially superseded by #22.

**Comment by rade** [comment]
See also #437.

**Comment by unitymind** [comment]
In the same manner `weave run` or `weave expose` can execute on another peer host, using already allocated on another host CIDR.

**Comment by rade** [comment]
This is about preventing weave subnets from clashing with host subnets. It's not about IP addresses. IPAM (#22) takes care of ensuring uniqueness of IPs within the weave network.

**Comment by unitymind** [comment]
Okey, thanks for clarification
