### ISSUE TITLE
Is there any way to assign dns and search domain for weave interface?

### ISSUE THREAD

**Issue by kesavkolla** [weaveworks/weave#493]
I use weave expose on my existing ubuntu server and connect to weave network.  I've a DNS server that is in weave network and I want to use that DNS server for all my resolutions that are on weave network.  Is there any command in ubuntu or weave to attach DNS server and corresponding search domain for weave interface.

I don't want the regular internet traffic to be queried on this DNS server on weave

**Comment by awh** [comment]
Hi @kesavkolla - is your aim purely to allow contained services to find each other by name on the weave network? In that case you may find [weaveDNS](https://github.com/zettio/weave/tree/master/weavedns#readme) takes care of all the hard work for you - see what you think.

**Comment by rade** [comment]
@kesavkolla please elaborate on what you are trying to accomplish. Thanks.
