### ISSUE TITLE
`weave launch` failure reported incorrectly

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#522]
````
# weave launch -foo
Failure during network configuration for container 3b6d181fc93f96207976e102311ea49daf381d3927f06b0904c68cc31a78826b:
Cannot open network namespace "10107": No such file or directory
````
This should have reported "Container 3b6d181fc93f96207976e102311ea49daf381d3927f06b0904c68cc31a78826b died". And I am quite sure it used to. I even get the same problem when running with --local. I wonder whether something has changed in docker that delays the updating of the container's metadata on death, because inserting a 'sleep 1' just before we run `docker inspect` makes the issue go away.

**Comment by rade** [comment]
I guess we could dispense with `docker inspect` and directly check whether the $CONTAINER_PID is dead (`kill -0 $CONTAINER_PID`).

However, having just tried that, I still get the same result. Which is odd.

**Comment by bboreham** [comment]
It seems to me there has always been a race between the weave script doing its check on why network setup has failed and Docker finding out that the process has died. Your test with `kill -0` runs into the same problem: until the parent has waited on the dead process it still exists as a zombie.

**Comment by rade** [comment]
I must have been imagining things... The `kill -0` works for me all the time now. Whereas the original `docker inspect` consistently fails to detect the dead weave in time.
