### ISSUE TITLE
dealing with old dockers in the weavexec era

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#576]
Our README says we support Docker 0.9.1 or later. I am pretty sure that is not true anymore, since the weavexec image introduced in #388 contains Docker 1.3.1, so that ought to be the oldest daemon version it can work with.

`weave --local` can probably still cope with older versions, but that is not how the majority of user will run weave.

So I think we need to update the docs, to mandate >=1.3.1.  @squaremo correct?

But surely we should also amend the version checks in the script, since otherwise users will get obscure errors when running against older daemons. Or are these errors quite self-explanatory?

If we are going to amend the checks, we really want to only check that the version of the docker *daemon* we are running against is >=1.3.1. And only if we are running in the context of the weavexec image, since the existing checks are sufficient outside that. `docker version` does tell us the server version, but a) does that work when the server is an older version, and b) is the output format the same across server versions?

**Comment by squaremo** [comment]
Docker version requirements:

 * We cannot use docker client version 1.3.0, specifically, for any purpose, since it outputs things to stdout which it shouldn't
 * Using `--with-dns` requires docker client >=1.2.0, and since the server version needs to be >= the client version, a server >= 1.2.0. Unless `run --local` is used, this will be executed in weaveexec, which has docker client v1.3.1.

Without `--local`, the server needs to be >=1.3.1, and the client needs to be !=1.3.0. With `--local` and `--with-dns`, the client needs to be >=1.2.0.

If the docker server is <1.3.1, our embedded docker won't be able to talk to it, which might be confusing if the user's docker client is also <1.3.1, since they will get a message indicating that the versions are mismatched (which isn't true from their point of view). So we may want to head that off.

**Comment by rade** [comment]
Let's not worry about `--local run`.

We could decrease the docker version included in weavexec. No downside to that except for #582 and any bugs that might be in the client-side portion. I have no feel for the latter, unfortunately. Ideally we'd drop all the way back to 0.9.1 since that is in ubuntu trusty. trusty-updates has 1.0.1. utopic has 1.2.0. and vivid has 1.5.0.

Shall we go for 1.2.0? It's what the server needs to be for `--with-dns`. We are integrating weavedns more and more and want more folks to use it, and there is some merit to having just one version requirement. (i.e. server >= 1.2.0).

I think that's the only change I'd make for 0.10. If it turns out that several users are running into version compatible issues and are confused by the error messages, we can address that in a 0.10.1 or 0.11 release.

**Comment by rade** [comment]
Scratch the 1.2.0 plan. See #587. If we need 1.3.1 for DNS we might as well have that as a general requirement. So for 0.10 I'll simply update the docs.

**Comment by rade** [comment]
I've done some testing...
````
| client | server | launch | run |
|--------+--------+--------+-----|
|  1.6.0 |  1.6.0 | ok     | ok  |
|  1.2.0 |  1.6.0 | ok     | ok  |
|  1.6.0 |  1.2.0 | 1      | 2   |
|  1.2.0 |  1.2.0 | 3      | 3   |
````

1. `FATA[0000] Error response from daemon: client and server don't have same version (client : 1.18, server: 1.14)`
2. `time="2015-04-21T19:07:24Z" level=fatal msg="Error response from daemon: client and server don't have same version (client : 1.18, server: 1.14)"`
3. `2015/04/21 19:16:42 Error: client and server don't have same version (client : 1.15, server: 1.14)`

So, as @squaremo said, the problematic case is client_vsn<=server_version<1.3.1, since we end up with an error message that contains the weavexec docker version as the client version.

Ways of fixing this...

a. run `docker version` at the client, extract the `Server version` field, check that it is >=1.3.1 and complain otherwise

b. run `docker version` inside weavexec, this will produce the error, which we could catch and present differently.

c. as (b) but query the version-neutral Docker API instead, i.e. the equivalent of `curl dockerhost:dockerport/version`. This will give us the server version w/o an error.

The main downside of (a) is that it involves running more code at the client side, after we've just spent a fair amount of effort cutting that down. OTOH we already perform a client-side version check for `weave run`. Still, it's extra code and an extra (potentially remote) interaction with docker. Another issue is that we somehow need to know what to check for. Hard-coding the version into the script is kinda gross since then it appears in two places that need to be kept in sync - the script and the Makefile.

The main downside of (b) is that we are dispatching on the contents of an error message. OTOH the message format should be determined by the client, and thus pinned to the version embedded in weavexec. Or perhaps it's good enough to assume that when `docker version` fails then that is due to a version mismatch. Yes, that could go wrong, but commonly enough to be problematic? The other issue is that we cannot report the server version, only the server *API* version. OTOH that is all you get from docker version errors in general. I guess we could produce an error along the lines of "Error: docker server API version 1.14 too old; needs to be at least 1.15 (docker version 1.3.1)". Note that this is purely a rewriting of the version information+error we get; no extra info is required.

The main downside of (c) is that talking to docker over a unix domain socket from a shell script, and parsing the resulting json output, is not fun. I suppose we could write a small program to do that.
