### ISSUE TITLE
Need a new v1 walk though for the magical world of docker plugins

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#577]
Currently depends on docker deciding what the CLI will look like; but it will probably be something like:

````
# docker plugin load weave
# docker net create --driver=weave --name=foo
# docker run --network=foo ubuntu
````
........

Some immediate questions:
* Where do we pass other peers?  I'm suggesting this will be on docker plugin load --label peer=bar.  Or are we still planning to rely on bonjour?
* Docker might have a network-driver command, in which case peers will likely be delegated to that.
* Assume we should not need to specify IPs or subnets?

**Comment by bboreham** [comment]
Plugin usage was documented in #1738
