### ISSUE TITLE
Replace weaveexec procfs bind mount with docker run --pid=host

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#578]
Exposing the host process namespace to the weaveexec container will eliminate the need for the procfs bind mount and enable PID based invocations of `nsenter` and `ip link set ... setns ...`.

Requires Docker 1.5.

**Comment by rade** [comment]
It's a little bit too soon for us to require docker >=1.5 on the client. So let's put this on ice for now.

**Comment by awh** [comment]
We can do this once the fix to #1683 lands.
