### ISSUE TITLE
[ipam] mixing manual and automatic allocation in the same subnet

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#598]
The introduction of IPAM doesn't prevent users from assigning IPs themselves. However, it is currently impossible to mix the two approaches in the same subnet, i.e. place containers in the same subnet which have some IPs allocated automatically and some assigned manually.

We could a) constrain IPAM allocation to a designated portion of the subnet in which containers are placed, (e.g. allocate in a /24, but place the container in a /23), or b) carve out a reserved manual allocation portion of the subnet that IPAM allocates from (e.g. tell IPAM to allocate from a /23 but leave out a specific /24).

**Comment by errordeveloper** [comment]
This is also important for IP address mobility, let's say I start a container and get it's IP automatically in the first place, later find myself in a situation where I must move it to a different host. There could be a need for IP relocation manager, may be, but on the other hand users may be okay with ad-hoc solution to this specialised sort of case. I don't think proposed options A or B would actually cater for this, I think the kind functionality this needs is "random address stealing", which still matches the title of the issue.

**Comment by rade** [comment]
What you are describing is indeed different, and something we've discussed. Please raise a separate issue.

**Comment by rade** [comment]
actually, I'll raise an issue...

**Comment by rade** [comment]
> This is also important for IP address mobility

Different issue. #599

**Comment by bboreham** [comment]
I believe, post #827, this can now be done by starting weave with e.g. `-iprange 10.2.0.0/25`, use IPAM with `net:10.2.0.0/24` and manual addresses like `ip:10.2.0.129/24`

**Comment by rade** [comment]
right. slightly more readable version: `-iprange 10.2.0.0/24` and `net:10.2.0.0/23` and `ip:10.2.1.1/23`.

The problem is that this only works for *one* subnet.

**Comment by bboreham** [comment]
Closed by #1200
