### ISSUE TITLE
Inconsistent use of `-` vs `--` for long options in weave script

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#602]
For example `-password` vs `--with-dns`. `--` is the convention for long options on GNU/Linux, we should support it and deprecate the other forms.

**Comment by awh** [comment]
Docker is making this change:
````
$ docker run -privileged
Warning: '-privileged' is deprecated, it will be replaced by '--privileged' soon. See usage.
````

**Comment by squaremo** [comment]
Another worthwhile convention is separating arguments to a wrapped command with `--`; e.g.,

    weave run 10.2.0.4/24 -- -ti ubuntu

**Comment by paulbellamy** [comment]
Do we need to maintain backward compatibilty while deprecating (ala docker)? Or are we comfortable with dropping the old syntax?

**Comment by awh** [comment]
#307 might present an opportunity for a clean break...

**Comment by awh** [comment]
https://github.com/weaveworks/weave/pull/627#issuecomment-99023790

**Comment by paulbellamy** [comment]
@awh, agreed, that seems like a good time to fix it.

**Comment by squaremo** [comment]
I'm not totally sure how to do backwards compatibility, at least with go's built-in flag parser. We can add parallel vars:

    	flag.IntVar(&config.ConnLimit, "connlimit", 30, "connection limit (0 for unlimited) (deprecated; please use --conn-limit)")
	flag.IntVar(&config.ConnLimit, "conn-limit", 30, "connection limit (0 for unlimited)")

But this will mean usage output gets cluttered, unless we can filter it somehow.

(It also occurs to me that if we cannot have complete backwards compatibility, and we aspire to adhere to SemVer, we will probably need to bump the major version.)

**Comment by rade** [comment]
> I'm not totally sure how to do backwards compatibility, at least with go's built-in flag parser.

I wouldn't mind switching to getopt, which is what the proxy uses.

**Comment by squaremo** [comment]
> I wouldn't mind switching to getopt, which is what the proxy uses.

Does that have special support for backward-compatibility? (largely a case of conveniently being able to support the old version of an option, while keeping it out of usage)

**Comment by rade** [comment]
> Does that have special support for backward-compatibility?

No idea. But it seems closer, in terms of how options are parsed, to generally accepted usage. E.g. it has sensible semantics for specifying an option more than once (vs. "first one wins).

**Comment by squaremo** [comment]
Argh, OK maybe I should revise my idea of what deprecation should do. New rule: deprecated options get output in the usage message, just with "deprecated, please use ....".

By the way, I don't think I can use getopt without breaking backward compatibility, since it won't parse the old, single hyphen versions of the options. Piiiiiike!

**Comment by rade** [comment]
I'd be ok with a non-backward-compatible change.

**Comment by bboreham** [comment]
We could add some code in the `weave` script to translate old options to new ones and warn, for existing users.

**Comment by squaremo** [comment]
> We could add some code in the weave script to translate old options to new ones and warn, for existing users.

Easier said than done, now that I think about it. For one thing, the options are potentially context-sensitive -- it's possible (maybe?) that option-looking things appear as values.

**Comment by squaremo** [comment]
Oh and the other thing -- it couples the script to *all* executable options, even the ones it would splat through without looking at them.

Mainly for that reason, I'm now looking at doing the deprecation in the exes themselves instead.

**Comment by squaremo** [comment]
I am now thinking I should anticipate the merge of weaveDNS and weaver by prefixing weaveDNS options with `--dns-`

**Comment by rade** [comment]
> I am now thinking I should anticipate the merge of weaveDNS and weaver by prefixing weaveDNS options with `--dns-`

Most of the DNS options will go away. It's up to #826 to deal with the options.

**Comment by squaremo** [comment]
> It's up to #826 to deal with the options.

Sure; but I presume some will still remain (like `httpport`), and I'd rather not change their names twice. Although it is true that merging weave and weaveDNS will represent a bigger change, it's friendlier if people don't have to go back and change all the options too.

(Not that I expect many of them would be in use, to be honest)

**Comment by rade** [comment]
> `httpport`

will be the same as the weave http port.

There are currently [exactly *three*](https://github.com/weaveworks/weave/pull/1065/files#diff-b41a1f5904c7c8a5046e907bf8236bb2R79) options pertaining to DNS in the gossip-based implementation, and one of those (`nameserver`) should go.

**Comment by squaremo** [comment]
> There are currently exactly three options

What about

 * `--fallback` (`--dns-fallback`)
 * `--maxanswers` (`--dns-max-answers`)
 * `--watch` (?)
 * `--ttl`
 * `--negttl`
 * `udpbuf`

which are still arguably relevant?
?

**Comment by rade** [comment]
Well, that's really up to Tom. I suggest you don't try to second-guess what gossipDNS will end up looking like.

**Comment by squaremo** [comment]
> I suggest you don't try to second-guess what gossipDNS will end up looking like.

You mean phonetreeDNS

**Comment by squaremo** [comment]
> It's up to #826 to deal with the options.

Are you saying I should leave weaveDNS entirely alone and assume the new implementation will conform to the changes here? I've made a note in #826 suggesting that last.

**Comment by squaremo** [comment]
> Oh and the other thing -- it couples the script to all executable options, even the ones it would splat through without looking at them.
> 
> Mainly for that reason, I'm now looking at doing the deprecation in the exes themselves instead.

Of course, by doing it in the exes, the deprecation notices go to the logs, meaning almost no-one will see them. So perhaps I'll put deprecation notices in for the arguments that are explicitly mentioned in the script usage.

**Comment by rade** [comment]
From https://github.com/weaveworks/weave/issues/1035#issuecomment-118211327

> I have been thinking about the backward compatibility story... I reckon what users are most concerned about isn't substitutability, but interoperability - being able to run new and old in the same network, and thus being able to roll out and upgrade gradually. That requires protocol compatibility, not script compatibility.
>
> Renaming of commands & options is actually fine, though obviously if it is easy to retain the old ones in parallel then we should do so (but advise users in the release notes that they should really update their scripts, etc, since we won't retain the old version indefinitely).

Looking at the complications we are running into, and the time it's taken so far, I suggest we skip the deprecation.
