### ISSUE TITLE
prevent connections to self

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#611]
Now that we allow the 'standard Weave port' to be configured, there can be two Weave processes running on the same machine at different port numbers.

Suppose we have hosts 1.1.1.1 and 2.2.2.2, and we are running Weave on ports 3000 and 4000 - four processes in all.

During start-up, 1.1.1.1:3000 receives via gossip the information that 2.2.2.2:4000 has a connection to 1.1.1.1:4000.  It takes the endpoint 1.1.1.1:4000 and tries to connect to the address formed by adding its own standard port number to the IP address, i.e. 1.1.1.1:3000, which is itself.

**Comment by rade** [comment]
The only problem that this causes is unnecessary connection attempts and the associated log noise.

**Comment by bboreham** [comment]
Edited into the original comment.

**Comment by rade** [comment]
>  It takes the endpoint 1.1.1.1:4000 and tries to connect to the address formed by adding its own standard port number to the IP address

As of 61a5640a95dec850443af3d7406280bcedfd9f52 this only happens when that is the endpoint of an inbound connection. Which is of course possible.

The challenge in attempting to fix this is that weave peers generally do not know what their IP address is. Especially when running inside a container, which is the normal case.

We could look at what IP addresses other peers have seen for us. Or we could remember to never connect to a particular address once we have discovered that it leads to ourselves. So far we've deliberately avoided making any permanent associations between IPs and peers, since it is possible for that to change over time.

Overall, I don't think this is a pressing issue. -> icebox

**Comment by rade** [comment]
subsumed by #1305.
