### ISSUE TITLE
supply docker args for remote execution

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#626]
For example, one has to pass `--tlscert` and `--tlskey`, when the remote docker host uses self-signed certificate.

**Comment by rade** [comment]
This [isn't necessary](https://docs.docker.com/articles/https/#secure-by-default) for using tls.

What other use cases are there?

**Comment by grkvlt** [comment]
That doesn't work when you don't have a `ca.pem` file available, which is only required for client certificate authentication. Actually, this may be a bug in Docker itself, although the obvious workaround is just to add the `ca.pem` file and get on with my life...

**Comment by rade** [comment]
What shall we call this new env var? Note that it is quite different from `WEAVE[DNS]_DOCKER_ARGS`, since those supply args for `run`, i.e. coming after `run`, whereas here we want args for docker itself, i.e. coming *before* `run`.

**Comment by grkvlt** [comment]
@rade @errordeveloper what about `DOCKER_CLIENT_ARGS` or `LOCAL_DOCKER_ARGS` to distinguish them from the remote Docker command's arguments?

**Comment by rade** [comment]
I like `DOCKER_CLIENT_ARGS`. And we could, if we really felt the need, add a `WEAVEEXEC_DOCKER_ARGS` for supplying `run` parameters.

**Comment by errordeveloper** [comment]
I only wondered if this should passed in before all arguments or after... Docker favours the last occurrence of same argument, isn't it?

**Comment by errordeveloper** [comment]
My comment was regarding the placement `WEAVEEXEC_DOCKER_ARGS`, i.e.
```
@@ -53,6 +53,7 @@ exec_remote() {
         -e WEAVE_CONTAINER_NAME \
         -e DOCKER_BRIDGE \
         -e PROCFS=/hostproc --privileged --net=host \
+        $WEAVEEXEC_DOCKER_ARGS \
         $EXEC_IMAGE --local "$@"
 }
 ```

VS

```
@@ -53,6 +53,7 @@ exec_remote() {
+        $WEAVEEXEC_DOCKER_ARGS \
         -e WEAVE_CONTAINER_NAME \
         -e DOCKER_BRIDGE \
         -e PROCFS=/hostproc --privileged --net=host \
         $EXEC_IMAGE --local "$@"
 }
 ```

**Comment by rade** [comment]
The former. That's where `WEAVE_DOCKER_ARGS` is placed by the current script.
