### ISSUE TITLE
Example to use docker-compose with weave

### ISSUE THREAD

**Issue by stephanbuys** [weaveworks/weave#629]
Hi, created this demonstration of weave and docker-compose playing together. At the moment I use two instantiations of the compose tool because weave needs to run after the containers are started. 

Something like https://github.com/docker/compose/pull/686 might solve it later.

https://gist.github.com/stephanbuys/f16f793ef9373b9b28a6

**Comment by rade** [comment]
@squaremo

**Comment by errordeveloper** [comment]
@stephanbuys that's very interesting, let me look into it and I'll get back to you if I have any questions.

**Comment by stephanbuys** [comment]
@errordeveloper, your latest blog post ( https://github.com/errordeveloper/weave-demos/tree/master/quartet/app ), does the WEAVE_CIDR environment variable support multiple networks? I've got several containers that attach to frontends and backends with different networks.

FYI: https://github.com/docker/compose/pull/686

One of the things that weave could potentially support is a way for the "attach" container to wait/listen for the container in the argument for weave attach to appear, and then only attempt to run/attach (perhaps with a timeout), that will make the order in which containers are started (and weave commands are issued) independent.

**Comment by errordeveloper** [comment]
The blog post that will use compose with the `WEAVE_CIDR` is not ready yet, it's waiting for 0.11 release of Weave. I will have to check if this method will support multiple subnets, that's a very good question.

Regarding the container process startup after initialisation of Weave interface, it essentially depends on network plugin support in Docker itself, however the proxy method that my compose blog post will use should provide a basic solution to this.

**Comment by errordeveloper** [comment]
You can look at the proxy implementation in #655.

**Comment by stephanbuys** [comment]
@errordeveloper is there a way to test the proxy pre-release? I'm guessing it will be "swarm" compatible as long as you schedule a proxy instance on each of the nodes in the Swarm cluster. It's a great feature.

**Comment by errordeveloper** [comment]
> ... is there a way to test the proxy pre-release?

The 0.11 release is due this week, so you shouldn't have to wait for too long.

>  I'm guessing it will be "swarm" compatible as long as you schedule a proxy instance on each of the nodes in the Swarm cluster.

Yes, it will be. I'm in the process of writing a blog post on how it will work with Swarm and Compose.

> ...does the `WEAVE_CIDR` environment variable support multiple networks?

Yes, please see [the docs](https://github.com/paulbellamy/weave/blob/b7acf9e1535213b9b61f9fe1a5460ce83203510a/site/proxy.md#usage).

**Comment by errordeveloper** [comment]
http://blog.weave.works/2015/05/27/multi-host-docker-deployment-with-swarm-and-compose-using-weave-0-11/

**Comment by stephanbuys** [comment]
@errordeveloper nice going! Thanks for pointing me at the article.
