### ISSUE TITLE
[dns] permit removal of individual records

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#631]
ATM, the DELETE operation in the HTTP API, and the underlying `Zone.DeleteRecord` operation, take a container and IP address. They do *not* accept a name. So even though it is possible to add multiple records for the same container-IP combination, with different names, it is not possible to remove such entries individually.

This functionality is needed for #364 and #627.

**Comment by grkvlt** [comment]
It should also be possible to remove _all_ entries for a container with a single command, using wildcards, for example:

    http_call $DNS_CONTAINER_NAME $DNS_HTTP_PORT DELETE /name/$CONTAINER/* -d fqdn=*

I suggest allowing the `rm-name` (or whatever) and `detach` commands should be able to be called with _no_ CIDR specified, and they will then remove all addresses and/or DNS entries for a container.

**Comment by rade** [comment]
How would you express the first case in the command? Leaving out the fqdn should mean "use the container's host&domain as the fqdn", since that is what happens for `add-name`.

I also wonder whether it might be rather dangerous to make the no-CIDR case special. Imagine some UI or automated system that gets hold of a bunch of CIDRs and invokes the CLI. You'd want the no-CIDR case to be a no-op there, as it is now. Just like `add-name` is a no-op when given no CIDRs.

**Comment by inercia** [comment]
I think this should be part of #432: IMO, the underlying problem is that we need a better API in WeaveDNS...

**Comment by grkvlt** [comment]
@rade the use cases I'm thinking of are the following, with example commands:

1. remove _all_ DNS mappings from any IP to any hostname for a container:<br>
`weave rm-name --force <containerid>`
2. remove _all_ DNS mappings from any IP to some specific hostname for a container:<br>
`weave rm-name --force <containerid> -h <hostname>`
3. detach a container from _all_ weave IP addresses on the weave interface:<br>
`weave detach --force <containerid>`

I agree this is getting beyond the scope of this issue, and in any case needs better DNS API support before it could actually be implemented as @inercia says. Do you want me to raise a separate issue that describes this wildcard removal behaviour request?

**Comment by rade** [comment]
@grkvlt No need for a separate PR
@inercia I like the idea of focused PRs that resolve tangible problems. #432 is open ended. This issue is solvable *now* and does not require any JSON-ification of the API.

**Comment by awh** [comment]
Unless anyone objects, I'm going to go with the slightly simplified
````
DELETE /name/$CONTAINER
````
to remove all mappings for a container and
````
DELETE /name&fqdn=foo.weave.local
````
to remove a mapping from all containers - it's more RESTful and aligns with #432 better.

(BTW @grkvlt, did you mean `DELETE /name/* -d fqdn=test.weave.local` and not `DELETE /name/$CONTAINER/* -d fqdn=test.weave.local`?)

**Comment by rade** [comment]
Bear in mind the tile & description of this PR. It is about removal of individual records. That does not entail "wildcards". I suggest you defer that to additional PRs.

**Comment by rade** [comment]
and, fwiw, if you do do wildcards, you'd surely want to allow all combinations of wildcards for name, ip and container. including wildcards for all three :)

**Comment by awh** [comment]
Sorry, I took your comment
> @grkvlt No need for a separate PR
in response to
> Do you want me to raise a separate issue that describes this wildcard removal behaviour request?
as approval of extension of the scope of this PR to include wildcards...

**Comment by awh** [comment]
RE: name/ip/container wildcards indeed, and in fact I was just considering replacing `DeleteRecord` and `DeleteRecordsFor` with a single method that takes optional container/ip/name parameters...

**Comment by rade** [comment]
well, it's up to you. Am just worried about this getting bogged down.
