### ISSUE TITLE
[dns] list *all* records

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#645]
As of #465, `weave status` shows DNS records. But only records held in the zone db of the weaveDNS instance on the local host. Some users have requested a means by which to obtain a 'global' view.

**Comment by rade** [comment]
btw, I wouldn't expect this to be either efficient or guaranteed to be complete (even in the absence of partitions).

**Comment by rade** [comment]
This will be partially addressed by #826, though we need to bear in mind #1025.

**Comment by tomwilkie** [comment]
Yes I think we should remove the dns entries from weave status, and have a ./weave command to list them.  The http endpoint is there in gossipdns

Unfortunately the tests rely on the weave status output.
