### ISSUE TITLE
Old links to docs no longer work

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#648]
See this search https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=weave%20build%20in%20container

First link is to https://zettio.github.io/weave/building.html

We should put in a catch all and redirect, if possible.

**Comment by errordeveloper** [comment]
Unfortunately, GitHub doesn't support redirects for pages. I have contacted support and they could only help to clear cache, so now we have to wait for google to pickup new URLs. The only alternative we had was to live with stale docs, which would probably go away one day anyway.

**Comment by errordeveloper** [comment]
Just FYI, it has fixed itself now:
![screenshot 2015-05-20 13 25 38](https://cloud.githubusercontent.com/assets/251467/7725574/e670b11e-fef3-11e4-8622-78a54cb74092.png)
