### ISSUE TITLE
[dns] slight inefficiency in weave script tell_dns

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#654]
The function `tell_dns` is called in four places, two of which know the long-form container ID and two don't.  It would be more efficient to break out the part of tell_dns which re-fetches the long-form ID so we can bypass it in `weave run` and `weave start`.

**Comment by awh** [comment]
I'm replacing this part of the script for #631 so I'll make sure the new version handles this.

**Comment by bboreham** [comment]
Note I already made this improvement in `tell_ipam` which is called quite similarly.
