### ISSUE TITLE
[proxy] Add IPAM support

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#657]

**Comment by rade** [comment]
strawman:

1. make `-e WEAVE_CIDR=` (i.e. an empty `WEAVE_CIDR`) perform IPAM
2. add a `--ipam` flag to the proxy startup, which enables a mode in which all container starts without a `WEAVE_CIDR` will do IPAM

**Comment by paulbellamy** [comment]
@rade:
For 1, could make `-e WEAVE_CIDR=auto` perform IPAM, as blank var vs unset var could be confusing to users.

For 2, any reason not to make this the default? It is the default for the router, correct?

**Comment by paulbellamy** [comment]
Also for 2, is there a way for the proxy to ask the router if IPAM is enabled? Adds a bit of complexity around what to do if the router is unavailable, but we need to handle that anyway.

**Comment by rade** [comment]
The reason to go for blank vars is consistency with how IPAM gets triggered in weave commands. i.e. IPAM is used iff the user did not supply any IPs. I don't mind supporting `=auto` *too*.

I don't think automatic IPAM should be the default; just like `--with-dns` shouldn't be. Our proxy should be a null-op proxy unless the user does something special, i.e. adorn their containers with `WEAVE_CIDRs` or supply some flags on proxy launch.

I'd leave out the 'figure out whether IPAM is enabled'. Can do that later if we feel like it.

**Comment by paulbellamy** [comment]
Personally, I'd expect `docker run -e 'WEAVE_CIDR=' ubuntu` to have the same behaviour as `docker run ubuntu`. Which makes me favour option 2, with an eye to deprecating `--ipam` for auto-detection in the future.

**Comment by bboreham** [comment]
> is there a way for the proxy to ask the router if IPAM is enabled?

The /status http request will have a line beginning 'Allocator'. I don't think there is any more direct route, but one could easily be added.

**Comment by rade** [comment]
> I'd expect `docker run -e 'WEAVE_CIDR=' ubuntu` to have the same behaviour as `docker run ubuntu`.

I would not!

> with an eye to deprecating `--ipam` for auto-detection in the future.

Then you are left with no way of using the proxy for ordinary (non-weave) containers.

**Comment by paulbellamy** [comment]
Since being able to use the proxy for both weave and non-weave containers is quite important, then option 1 is probably a better choice.

So, let's make `WEAVE_CIDR=` enable IPAM for that container. With no support for "...=auto", as it adds one more thing for users to learn with no benefit.
