### ISSUE TITLE
add command line peers to status output

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#659]
Since command line peers can be modified with `weave connect/forget`, the `weave status` output should include the current list.

**Comment by paulbellamy** [comment]
Preference on a section title?
`Command-Line Peers`? `Seed Peers`? `Direct Peers`?

**Comment by abligh** [comment]
presumably not command-line peers as they can be modified using `weave connect/forget`, so that would be confusing. `Direct peers` is closest to what I wanted it for originally in #656.

**Comment by rade** [comment]
"Direct peers" it is. var names in code need changing accordingly.
