### ISSUE TITLE
Patch to help the weave cli work better with swarm 

### ISSUE THREAD

**Issue by fredead** [weaveworks/weave#661]
So I don't know if this is useful but hey it worked for me. There are some terrible things about this patch maybe it will help some people maybe it wont . 

```diff
--- weave	2015-05-14 17:27:25.855440962 +0100
+++ simon-weave	2015-05-14 15:18:49.434101735 +0100
@@ -82,6 +82,12 @@
     fi
 }

+switch_direct_container_hosts() {
+	DOCKER_HOST=`docker inspect -f '{{.Node.Addr}}' $1`
+}
+
+
+
 collect_cidr_args() {
     CIDR_ARGS=""
     CIDR_COUNT=0
@@ -109,6 +115,7 @@
     collect_cidr_args "$@"
     shift $CIDR_COUNT
     CONTAINER=$(docker run $DNS_ARGS -d "$@")
+    switch_direct_container_hosts $CONTAINER
     exec_remote attach $CIDR_ARGS $CONTAINER
     echo $CONTAINER
     exit 0
```

**Comment by rade** [comment]
This came out rather mangled. Mind submitting a pull request?

**Comment by errordeveloper** [comment]
I have updated the formatting to make it readable.

**Comment by errordeveloper** [comment]
@fredead I don't think you need this, you should just take a look at [my blog post from last week](http://blog.weave.works/2015/05/06/using-docker-machine-and-swarm-with-weave-0-10/).

**Comment by fredead** [comment]
I had a look at the blog this was easier for me :/

**Comment by errordeveloper** [comment]
Basically a more elegant solution is to use `WEAVEEXEC_DOCKER_ARGS="-e affinity:container==${c}"` with `weave attach`, like shown in [`weave-run-on-swarm.sh`](https://github.com/errordeveloper/weave-demos/blob/7cf3f75b7bd11996f9d7ac12163196b7a6d32c4e/quartet/scripts/weave-run-on-swarm.sh), which depends on 04ceb5620b1d11360aaf765aa7ecded949e9e650, so you need weave script from master.

**Comment by errordeveloper** [comment]
> I had a look at the blog this was easier for me :/

Would you mind to explain in which way this patch makes it easier for you? I certainly am all for improving the blog post :)

**Comment by fredead** [comment]
The Blog post was nice but I down load all the source to work out what is going on under the hood. 
At this point it becomes more complex with shell scripts sourcing defaults call functions with one letter vars and hardcoded values. It is not very readable to me. 
   As im not using docker-machine as well and the scripts which suggest something done to shown this can be done not an example to take away and use. I thought Id just go for it  and found quickly this change worked for me with little knowledge of the rest of weave required. This would suggest it is indeed not the best way to do it.

**Comment by errordeveloper** [comment]
Ok, in a nutshell all you want is:
```
sudo curl https://raw.githubusercontent.com/weaveworks/weave/master/weave -o /usr/local/bin/weave
chmod +x /usr/local/bin/weave
```

And then you can run a container on swarm with:

```
container=$(docker run -d --dns=172.17.42.1 <ARGS>)
env WEAVEEXEC_DOCKER_ARGS="-e affinity:container==$container" /usr/local/bin/weave attach <WEAVE_CIDR> $container
```

That's it.

**Comment by errordeveloper** [comment]
By the way, there will be even a better way with #655.
