### ISSUE TITLE
replace homegrown logging library with something off-the-shelf

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#664]

**Comment by tomwilkie** [comment]
Docker use logrus...

**Comment by paulbellamy** [comment]
Logrus is fine. https://github.com/inconshreveable/log15 is also ok.

**Comment by paulbellamy** [comment]
What advantages do we want from changing the logging library? structured logging?

The logging code we have is only 40 lines, and with either logrus, or log15 we'll need about the same amount of setup (maybe *slightly* less, but not enough of a saving to justify it alone).

**Comment by awh** [comment]
Support for ordered log levels (see #329). Right now we have four separate output streams (debug, info, warn, error) but they aren't really levels - implementing something like 'show me info or above' would be a bit of a faff...

**Comment by bboreham** [comment]
I took a look at the main results from a web search of 'best golang logger':

https://github.com/cihub/seelog seems extremely full-featured, probably much more than we need. Over 10,000 lines including tests.
https://github.com/Sirupsen/logrus is ~3200 lines.
https://github.com/inconshreveable/log15 is ~3000 lines.
https://github.com/op/go-logging is ~2000 lines.

Based on my reading so far, I could not find any slam-dunk reason to prefer one of the smaller ones, so am planning to just use the same as Docker - logrus.  It seems to be actively maintained.

**Comment by rade** [comment]
I think one requirement that we have is that we don't want our log statements to become much more unwieldy than they currently are, and without introducing our own custom wrapper functions.

**Comment by rade** [comment]
> don't want ... much more unwieldy

So on that note, if we do go with logrus then we shouldn't use its 'fields' feature, at least to start with.
