### ISSUE TITLE
wait_for_status can fail on busy machine

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#666]
I suppose there should be some option around this, either to disable timeout or make it much longer then the default. I have just seen it happening on a Kubernetes node where there was at least about a dozen containers running and I needed to start weave after it exited due to a Docker crash. The containers were all running already, just needed to start weaver back up, the crash is not exactly related to this.

**Comment by errordeveloper** [comment]
So the default timeout is approximately 3 seconds, which is probably reasonable, but evidently doesn't have to be hardcoded.

**Comment by rade** [comment]
Perhaps we should just wait forever.

**Comment by errordeveloper** [comment]
> Perhaps we should just wait forever.

Makes sense to me, as if things are screwed up, we should probably detect that container has died. If someone finds that it actually never exists, that would mean there is a much bigger problem.
