### ISSUE TITLE
coverage reporting for smoke tests

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#673]
It would be great to get coverage reports for the golang code exercised by our smoke tests.

**Comment by tomwilkie** [comment]
According to https://vagabond.github.io/rants/2015/06/05/a-year-with-go/ this is not possible.

**Comment by rade** [comment]
Hmm. That rant is rather ranty. What problems did you actually run into?

I've [managed] to get a statically compiled weave exe to start up normally and dump coverage on exit. It should be possible to build a weave container with that.
