### ISSUE TITLE
[proxy] make `weave run` work more like `docker run`

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#674]
We should change the implementation of `weave run` to use the proxy introduced in #655, thus making it work more like `docker run`, in particular permit running in the foreground and use of `--rm`. Plus ensuring that the weave network interface is available immediately on startup.

As a prequisite, the proxy must be universally usable, which requires addressing #506, at least.

**Comment by paulbellamy** [comment]
Isn't auto-launching the proxy to listen on all IPs a security risk?

**Comment by rade** [comment]
who said anything about auto-launching?

**Comment by paulbellamy** [comment]
Ok, so we have to auto-detect if the proxy is running, and how to talk to it, then?

**Comment by rade** [comment]
something like that.

**Comment by rade** [comment]
After further discussion... if a user is running the proxy, then there is no point in starting containers with `weave run` instead of `docker run` -> wontfix.
