### ISSUE TITLE
[ipam] manage allocation on multiple subnets

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#675]
ATM, IPAM can only allocate IPs in a single subnet. We should extend that to multiple subnets.

Strawman UI: When the IP address(es) given to `weave run` et al are the base address of the network then we allocate an IP address in that network. Note that this is compatible with existing usage.

The alternative is to use some sort of prefix or other indicator to distinguish the 'use this IP' and 'allocate me an IP in this network' cases. And check that the address given to the former is not a network address, and the latter is not a non-network address. IMO that is a worse UI.

Some implementation challenges...

1. Single ring or one ring per sub-net?
2. Should we permit overlapping ranges? non-ipam weave allows that. is there a compelling use case?
3. ATM the range from which IPAM allocates needs to be specified in `weave launch`. We don't want this here, since the subnets may not be known at launch time. The ip range given to weave launch on startup should essentially be treated as the default allocation range, i.e. what gets used when no range has been specified at the time of allocation.

**Comment by bboreham** [comment]
For part 3, istm that we would need a consensus approach to avoid multiple peers independently initializing a subnet.  Maybe split this feature into pre-specified subnets and dynamically-specified?

**Comment by rade** [comment]
yes, it would require consensus, but we already do that for the currently single subnet. why can't we repeat the process for others? It's still a 'one off' consensus, but *per subnet*.

**Comment by bboreham** [comment]
I was just thinking it could be a separate bit of engineering and documentation.  E.g. there will be new error conditions - allocating an address can hang in a partition, if it happens to be the first one in that subnet.

**Comment by rade** [comment]
That is no different to what happens now, for the single IPAM-managed subnet. Since, iirc, ring creation consensus is always deferred until an allocation is requested (and we haven't received a ring via gossip by them).

**Comment by bboreham** [comment]
Good point, well made.

**Comment by bboreham** [comment]
Proposed change to URL scheme to accommodate the strawman UI:

#### Current URL scheme

Alloc: POST /ip/name
Claim: PUT /ip/name/addr/prefixlen

#### Suggested change

Alloc: POST /ip/name/addr/prefixlen
 - if address part (after subnetmask) is 0 then this acts like Alloc; if non-zero then acts like Claim.
 - in both cases, returns (allocated or claimed) address in CIDR format
 - previous version (with no addr/prefixlen) is still allowed and acts as before

**Comment by tomwilkie** [comment]
How does this fit with the plugin work?  I think the plugin will want an operation to create a fresh subnet, so won't know the add to pass to alloc.

Also, having a function do two different things depending on the value of its arguments - yuk.

**Comment by bboreham** [comment]
Allocating subnets is #676

**Comment by squaremo** [comment]
From the plugin point of view, allocating an IP giving a subnet name is better; otherwise the plugin has to maintain (and possibly discover out-of-band) a map of name->CIDR.

**Comment by bboreham** [comment]
Names are also in #676

**Comment by bboreham** [comment]
Now thinking of having the user specify at start-up a superset range of IP addresses covering every address that might be managed, then subsequent requests must be within that range.  This makes restarts tractable, in that we know whether each IP address must have been automatically or manually allocated.

Say we use `-ipuniverse` for the superset, then `-iprange` can be the default subnet for requests that don't specify one a subnet.
