### ISSUE TITLE
Using weave in a mixed network

### ISSUE THREAD

**Issue by amirtuval** [weaveworks/weave#680]
I've been prototyping using weave and like it a lot.

It works great for a container-only environment.

I was wondering how difficult it would be to support a use case where I have a mixed network - parts of the environment are containers, but other parts are regular VMs or even bare metal servers.

What would it take to make all these machines communicate over a weave network?

**Comment by bboreham** [comment]
Hi @amirtuval, you can route traffic in and out of the weave network as described [here](http://docs.weave.works/weave/latest_release/features.html#host-network-integration).

You could do this either from another machine running weave that can route to the VMs/servers, or by running weave on the VMs/servers and linking it in to the weave network.

**Comment by amirtuval** [comment]
Hi @bboreham  and thank you for your answer.

Regarding "weave expose" command - works great. I can ping ip assigned to the VM from containers in the same subnet and vice-versa.
I am also using weave dns, and although the documentation says that using the -h flag, I can add an entry for the VM in weaveDNS, it does not seem to work. Any idea why or how to troubleshoot? The name I try to use is srv3.weave.local.

Regarding the second thing you said - "You could do this either from another machine running weave that can route to the VMs/servers" - I am a networking noob, so I am not sure how to route to the VM. Can you elaborate some more?

Thanks a lot!
Amir

**Comment by bboreham** [comment]
> using the -h flag, I can add an entry for the VM in weaveDNS, it does not seem to work. Any idea why or how to troubleshoot? 

Assuming you have weaveDNS running (with `weave launch-dns ...`), `weave status` should list the addresses known to weaveDNS on that host.

> I am not sure how to route to the VM

We walk through how to do a single port using NAT [here](http://docs.weave.works/weave/latest_release/features.html#service-import), but I think to do it more generally you would add routing rules on every machine, which requires quite detailed knowledge of Linux IP routing and also how your underlying network is set up.
