### ISSUE TITLE
[ipam][docs] document prohibition to manually allocate in ipam range

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#681]
AFAIK bad things can happen when a user manually assigns an IP in the range given to IPAM, until we address #598. The docs do not mention this prohibition. They should. And they should also state what happens when a user doesn't follow it. (I'm guessing the IP might get allocated by IPAM, but can any other badness occur? some assertions getting triggered?)

**Comment by bboreham** [comment]
The allocator isn't told about this address on first usage, so cannot trigger any assertions at that time.  However, if you restart weave, then the script will try to claim that address, and you can get a message like `Unable to claim IP address 10.2.1.5: Claimed address 10.2.1.5 is already owned by 4b9f69c5a48b`

Raised #687 to inform the user straight away.
