### ISSUE TITLE
"exec format error" for Raspberry PI

### ISSUE THREAD

**Issue by winsonsun** [weaveworks/weave#699]
Latest git repository of weave:

When I am building on Raspberry PI 2, I met the next error "exec format error", error is triggered by:
"RUN ["apk", "add", "--update", "ethtool", "conntrack-tools", "curl", "iptables", "iproute2", "util-linux"]".

Apparently, these packages are referencing with x86 or x64 based CPU. I am wondering, which is the best way to do Raspberry build without depending the official (while with armhf CPU)?

Many thanks

**Comment by errordeveloper** [comment]
If you run `make clean; make weave.tar`, you should be able to get just router built and then you can use `docker load -i weave.tar`.

Once built, you want to bypass usage of Alpine-based `weaveexec` image, for which you want to use `--local` flag (e.g.  `./weave --local launch`).

You will also need to make sure that the following packages are installed on the target device:

  - `ethtool`
  - `conntrack-tools`
  - `curl`
  - `iptables`
  - `iproute2`
  - `util-linux`

Hope this gets you going.
