### ISSUE TITLE
[proxy] `docker exec` sees interface as down

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#707]
Despite #703, I can still sometimes see the interface as `DOWN` when running `640_proxy_restart_reattaches_test.sh`. And I am definitely running the correct proxy version since I've added some debug logging to confirm that.

**Comment by rade** [comment]
In fact i'd like to question the entire premise of #703. "Bug came up in a test where we are restarting and doing an exec checking a network interface right away". Surely `docker restart` should only return after the proxy has run `weave attach`.

**Comment by paulbellamy** [comment]
Notes:
maybe use `cat /sys/class/net/ethwe/operstate | grep "^up$"` or `ifconfig ethwe | grep ??`, instead of ip link show.

**Comment by paulbellamy** [comment]
double-check that EnsureInterface is being called in this case.

**Comment by rade** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=809912 might be relevant. Note that there appears to be a difference between flags and state.

**Comment by rade** [comment]
From https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net
> What:		/sys/class/net/<iface>/carrier
Date:		April 2005
KernelVersion:	2.6.12
Contact:	netdev@vger.kernel.org
Description:
		Indicates the current physical link state of the interface.
		Posssible values are:
		0: physical link is down
		1: physical link is up

That is what the snippet in #47 is checking. And I've verified that my `lo` interface, which shows an `UP` flag but `UNKOWN` state, has this set to `1`.
