### ISSUE TITLE
[proxy] `exec` instead of `run` application process

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#708]
It seems odd to me that `weavewait` uses `Cmd.Run()` instead of [`syscall.Exec()`](https://gobyexample.com/execing-processes). Surely it would be better to "become" the application process, instead of spawning it as a separate process and waiting for its completion.

**Comment by paulbellamy** [comment]
Was also meaning to ask, about the intended weavewait behaviour when the network fails to attach. At the moment it logs an error, and runs the subcommand anyway. Should it do that, or exit early?

**Comment by rade** [comment]
> Should it do that, or exit early?

Either is reasonable. So let's leave it as is for now.
