### ISSUE TITLE
Reduce the number of times `weave` calls `docker inspect`

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#725]
Various parts of the weave script call `docker inspect` to fetch the container Pid, full ID, fqdn and running state.  Each call requires a process execution and Docker API round-trip, so by merging them all into one place that fetches everything at once we could make the script a little faster.

**Comment by awh** [comment]
Is this worth it?
````
$ time docker inspect --format='{{.State.Pid}}' weavedns
4097

real	0m0.009s
user	0m0.007s
sys	0m0.000s

````

**Comment by bboreham** [comment]
On AWS micro instance:

````
ubuntu@ip-172-31-15-157:~$ time docker inspect --format='{{.State.Pid}}' weavedns
Get http:///var/run/docker.sock/v1.19/images/weavedns/json: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?
real	0m0.248s
user	0m0.016s
sys	0m0.021s
````

**Comment by bboreham** [comment]
I think the script has evolved, and we are keener on fixing #307 now, so closing this.
