### ISSUE TITLE
[docs] Deployment / reboot docs could be improved

### ISSUE THREAD

**Issue by lukec** [weaveworks/weave#726]
Hi Weave,

I'm totally loving weave so far, it feels like magic!

I was hoping I could help improve the Reboots section on the Troubleshooting page - as this feels like a real key part of actually using weave on a live system.

The first paragraph is great - it helps me understand the tricky part of the problem.

The other two paragraphs left me confused about which approach to take.  Here's a stab at some clearer language...

If you use Docker's auto-restart feature, you'll need to restart weave after a reboot.  On system startup, create a script to restart the weave container: 
 
   weave stop 
   weave launch [--password=X] <peer> ... 
  
 After weave is restarted, use weave attach on your containers to bring them back on the weave network. 
 
 Alternately, if you use startup scripts to manage your containers, you can create scripts to launch weave and run application containers from your favourite process manager.  Your startup scripts can run  weave launch to ensure the weave container is running, and then start their main process.  Or use dependency checks to ensure weave is started first.
 
 
I hope this feedback is useful.  It was helpful for me to write out, so that's one good outcome.

Best,
Luke

**Comment by bboreham** [comment]
Related: https://github.com/weaveworks/guides/issues/10
