### ISSUE TITLE
[dns] implement a Lookup mechanism for names in the HTTP API

### ISSUE THREAD

**Issue by inercia** [weaveworks/weave#727]
We need a way to perform lookups for names through the HTTP API. The response would

* include all the IPs for the name
* trigger a local domain (eg, mDNS)  if no local answers are present

The DNS server could wait for some time until we get all possible answers, but this is an open issue...

**Comment by inercia** [comment]
@peterbourgon What about returning a JSON with all the IPs when you `GET /name/<somename>`?

**Comment by rade** [comment]
@tomwilkie how badly do you need this for weave 1.0?

**Comment by tomwilkie** [comment]
Did I ask for this?  It doesn't ring a bell.  Or is the intention to use this for Scope to discover its probes?

**Comment by awh** [comment]
> Or is the intention to use this for Scope to discover its probes?

This.

**Comment by tomwilkie** [comment]
@inercia JSON is preferable, yes.

@rade @awh  I wouldn't worry about this for v1, assuming dns is going to return a random subset of hosts for a given name, we'll eventually get all probes (we poll at regular intervals)

**Comment by peterbourgon** [comment]
^^ what @tomwilkie said :)

**Comment by awh** [comment]
Then I suggest we close this issue, as this will be addressed properly post 1.0 by #826. Does everyone agree?

**Comment by tomwilkie** [comment]
@awh We're always going to be limited by the DNS 'API' - we'll only ever be able to return a UDP packet's worth of IPs, for instance.  I think having a HTTP API for get would be useful. 

I don't mind closing this ticket now though, we can always open another if/when this becomes a problem.

**Comment by rade** [comment]
> assuming dns is going to return a random subset of hosts for a given name, we'll eventually get all probes (we poll at regular intervals)

http://en.wikipedia.org/wiki/Coupon_collector%27s_problem

**Comment by rade** [comment]
DNS can fall back on TCP for large answers. and, iirc, most resolvers do that.

**Comment by awh** [comment]
> we'll only ever be able to return a UDP packet's worth of IPs, for instance

Wouldn't DNS TCP fallback suffice?

**Comment by tomwilkie** [comment]
> http://en.wikipedia.org/wiki/Coupon_collector%27s_problem

I think what I said still holds...  Eventually.  nlogn isn't too bad.

> Wouldn't DNS TCP fallback suffice?

We should make sure the go dns client is doing that.  But if so, great.

**Comment by awh** [comment]
> We should make sure the go dns client is doing that. But if so, great.

https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L134
https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L154

**Comment by rade** [comment]
> We should make sure the go dns client is doing that. But if so, great.

The golang resolver [does](https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L134). The native resolver invokes `getaddrinfo`, unsurprisingly. I'd be surprised if that didn't handle TCP fallbacks.

**Comment by awh** [comment]
Closing as deemed unnecessary. Will probably provide the HTTP eventually as part of #432 anyway.
