### ISSUE TITLE
What is GitHub?

### ISSUE THREAD

**Issue by Logan13246** [weaveworks/weave#732]
Hi I have downloaded GitHub on my computer because I have started teaching myself Java programming. But I actually have no clue what GitHub is used for and what it does. So can someone please tell me wat it's used for and what I candles use it for?  Thank you.

**Comment by dpw** [comment]
The first half of the blog post at http://thestatsgeek.com/2015/05/16/a-statisticians-initial-experiences-of-gitgithub/ contains a good explanation the purpose of git and github (before it goes into details about their use with R).
