### ISSUE TITLE
[docs] docs.weave.works should have a favicon

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#734]
And a set of `link rel=icon`, for extra credit.

**Comment by errordeveloper** [comment]
There is [`<link rel=icon>`](https://github.com/weaveworks/weave/blob/2d701972211129ed6246d9d7b523a20dfb805e2d/site/_layouts/default.html#L26), there is no `favicon.ico` file though, which is just for old browsers really...

**Comment by fintanr** [comment]
Browser stats over the last month

Chrome 72%, Firefox 13%, Safari 11%. 
Versions Chrome everything >= 40,
Firefox - 82% >= 37, 
Safari - 83% >= 8, everything > 7.

**Comment by rade** [comment]
@bboreham you noticed this, presumably by looking at a browser. Does it look ok for you now?

@errordeveloper when did the `link rel=icon` get introduced? Before or after this got filed?

**Comment by errordeveloper** [comment]
> @errordeveloper when did the link rel=icon get introduced? Before or after this got filed?

It got introduce in #834, which is a bigger number then #734.
