### ISSUE TITLE
[ipam] have a default for -iprange

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#743]
In general, we don't know what IP address ranges are in use on the target, so we ask the user to pick a free range.

However, we could have a default, check whether that default is OK to use, and refuse to start if not.  The default might be 10.20.0.0/16; this is fairly large and steers clear of ranges like 10.0.2 which are used by virtualbox.

We can use the same approach that Docker does to check if a range is in use: see if there is any routing rule on the host that intersects the range.

Having just a single default is better than having several and picking the first one that is free, because the latter approach can lead to inconsistent choices across hosts which are much harder to diagnose.

**Comment by rade** [comment]
afaict virtualbox uses `10.0.2`.

Would be good to have something larger than /16, but might be tricky to pick one that has a low probability of clashing.

**Comment by bboreham** [comment]
After #675 is fixed, the requirement will be to pick both an overall range and a default subnet within that range.

Suggest 10.0.0.0/8 and 10.20.0.0/16, respectively.

**Comment by bboreham** [comment]
After discussion, we should probably insist that `-iprange` is completely available for ipam to allocate within, so 10/8 not so good.  How about 10.16.0.0/12 and 10.16.0.0/16 ?

**Comment by bboreham** [comment]
Do we need an option to turn ipam off (i.e. what used to happen if you didn't specify -iprange) ?
