### ISSUE TITLE
[proxy] entrypoint and dns not configured with `--with-ipam`

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave#744]
Looks like proxy should care about `withIPAM` flag in `proxy/create_container_interceptor.go`, and it currently doesn't.

Anyways, what user sees is this:

```
> docker run busybox cat /etc/resolv.conf 
nameserver 10.0.2.3
> docker run -e WEAVE_CIDR= busybox cat /etc/resolv.conf
nameserver 172.17.42.1
```

**Comment by rade** [comment]
So presumably you ran the proxy with `--with-ipam --with-dns`?

The more serious issue here is that the entrypoint isn't being set.

**Comment by errordeveloper** [comment]
@rade yes, forgot to mention, I did path both `--with-ipam` and `--with-dns`.

**Comment by paulbellamy** [comment]
Ah yes, the `--with-ipam` flag is assigning the IP on start, but not setting the entrypoint. Same bug in execs also. Thanks
