### ISSUE TITLE
don't hash gossip channel names

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#745]
Our gossip implementation currently uses a 32-bit hash of the channel name as the key to distinguish channels. We do this so we a) get a short, fixed-length field for transmission, and b) don't require a "channel numbering authority". The downside is that it makes debugging harder. This is going to become more of an issue if we permit routers with different channels to establish connections - something we are currently avoiding with protocol versioning.

Options:

1. give up on the "short, fixed-length" requirement and transmit the name instead
2. give up on the "no channel numbering authority" requirement and assign unique numbers to channels
3. expand the protocol to negotiate channel name <-> number mappings between peers

Option 1+2 are easy. Option 3 is quite fiddly.

I suggest we go with option 1; the extra few bytes and associated encoding/decoding cost, and the cost of a string-based instead of number-based hash lookup, is not going to have a noticeable performance impact.

**Comment by dpw** [comment]
I have an implementation of option 1 sitting around.

**Comment by rade** [comment]
great. can you extract it into a PR, please?
