### ISSUE TITLE
fragmentation test protocol is over-complicated and possibly wrong

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#746]
The fragmentation test protocol looks as follows:

1. A: conn.stackFrag = false
2. A->B: StartFragmentationTest
3. B->A: send large non-DF UDP packet
4. A->B: FragmentationReceived
5. B: conn.stackFrag = true

`conn.stackFrag = true` means "UDP packets sent to the other peer get correctly fragmented and re-assembled".

This is all a little odd.... A clears its own stackFrag flag, but the test establishes whether fragmentation works for B->A, and ends up setting stackFrag on B. Not only is this weird, it also means that if A previously had stackFrag=true, it will now start fragmenting packets until B initiates a fragmentation test.

**Comment by rade** [comment]
So IMO this should just be

1.  A: conn.stackFrag = false
2.  A->B: send large non-DF UDP packet
3.  B->A: FragmentationReceived
4.  A: conn.stackFrag = true

**Comment by dpw** [comment]
I have an implementation of this, although it is bound up in a complete overhaul of the UDP forwarding code.

**Comment by rade** [comment]
> I have an implementation of this

How much effort to extract and test this? I was hoping to get this addressed in the upcoming release.

**Comment by dpw** [comment]
As I said, it's bound up in a complete overhaul of the UDP forwarding code.  Unless you fancy including such a thing in the upcoming release, extraction would be equivalent to reimplementation.

**Comment by rade** [comment]
ok. I will re-implement.

**Comment by rade** [comment]
We remembered correctly: fragmentation is indeed broken for GCE, for inbound traffic.

I patched weave to a) pretend that frag is always working, and b) report when it frag test succeeds:

````patch
diff --git a/router/connection.go b/router/connection.go
index 980de45..cbe2d34 100644
--- a/router/connection.go
+++ b/router/connection.go
@@ -262,7 +262,7 @@ func (conn *LocalConnection) SetEstablished() {
                conn.fragTest = time.NewTicker(FragTestInterval)
                // avoid initial waits for timers to fire
                conn.Forward(true, conn.heartbeatFrame, nil)
-               conn.setStackFrag(false)
+               conn.setStackFrag(true)
                if err := conn.sendSimpleProtocolMsg(ProtocolStartFragmentationTest); err != nil {
                        return err
                }
@@ -386,7 +386,7 @@ func (conn *LocalConnection) actorLoop(actionChan <-chan ConnectionAction) (err
                case <-tickerChan(conn.heartbeat):
                        conn.Forward(true, conn.heartbeatFrame, nil)
                case <-tickerChan(conn.fragTest):
-                       conn.setStackFrag(false)
+                       conn.setStackFrag(true)
                        err = conn.sendSimpleProtocolMsg(ProtocolStartFragmentationTest)
                }
        }
@@ -481,6 +481,7 @@ func (conn *LocalConnection) handleProtocolMsg(tag ProtocolTag, payload []byte)
                        nil)
        case ProtocolFragmentationReceived:
                conn.setStackFrag(true)
+               conn.Log("network stack fragments packets correctly")
        case ProtocolPMTUVerified:
                conn.pmtuVerified(int(binary.BigEndian.Uint16(payload)))
        case ProtocolGossipUnicast, ProtocolGossipBroadcast, ProtocolGossip:
````

The steps to reproduce the problem are as follows:

1. GCE setup
    1. setup a VM on gce; I used the smallest there is - an `f1-micro` - with Ubuntu 14.04
    2. add a firewall rule to open port 6783 for tcp and udp
    3. install latest docker
    4. install weave; I did this by copying the image .tars and weave script and loading the former with `docker load -i ...`.
2. on GCE run
    - `weave launch`
    - `C=$(weave run 10.2.0.1/24 -ti ubuntu)`
    - `docker attach $C`
    - `nc -u -l 1122`
3. locally run
    - `weave launch <gce-ip>`
    - `C=$(weave run 10.2.0.2/24 -ti ubuntu)`
    - `nc 10.2.0.1 1122`
4. copy&paste a single line of >1600 characters into the local nc

With the stock weave the line appears in the GCE nc. With the patched weave it doesn't.
