### ISSUE TITLE
[dns] resolve names in `weave.local` by default unless hostname or search path is specified

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#749]
When starting a container with `weave run --with-dns` *without* specifying a host name or `--dns-search` arg, we should make `weave.local` the domain to search in, so that 'naked' names are resolved in that domain.

Gotcha: the weaveDNS domain can be overridden, so this should respect that. Which involves asking weaveDNS. Which may not be running yet, in which case we should just stick to `weave.local`.

**Comment by rade** [comment]
NB: this behaviour should also be implemented in the proxy.

**Comment by awh** [comment]
@paulbellamy I've assigned this to you since you started on it already. Do you mind handling the weave script part too?
