### ISSUE TITLE
[dns] set hostname based on container name

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#750]
Instead of

    weave run --name=foo -h foo.weave.local -ti ubuntu

it would be nice to be able to just write

    weave run --name=foo -ti ubuntu

for the same effect.

at least when `--with-dns` is specified.

i.e. if no hostname is specified it should be set to `<container-name>.<weavedns-domain>`.

Gotcha: the weaveDNS domain can be overridden, so this should respect that. Which involves asking weaveDNS. Which may not be running yet, in which case we should just stick to weave.local.

**Comment by rade** [comment]
NB: this needs to work with the proxy too, i.e. when the proxy is configured with `--with-dns`, then

    docker run --name=foo -ti ubuntu

should set the hostname as described above.

**Comment by peterbourgon** [comment]
+1

**Comment by awh** [comment]
> at least when --with-dns is specified.

This is different from the behaviour obtained from `-h <fqdn>`, which works without `--with-dns`. Furthermore, it's a fair bit more complicated, because DNS records are updated in many places other than `weave run` (e.g. `weave start`, `weave launch-dns`), and these would somehow have to find out whether the container was launched with `--with-dns` or not. I'm going to make the initial version follow the behaviour of `-h`.

**Comment by rade** [comment]
I disagree. We must not lose the ability to start named containers w/o weave setting the hostname.

What is wrong with just modifying `dns_args` to return a `-h ...` in the conditions specified?

**Comment by awh** [comment]
> What is wrong with just modifying dns_args to return a -h ... in the conditions specified?

I was hoping to avoid parsing the docker arguments upfront by altering `with_container_fqdn` to `docker inspect` the container and synthesise an FQDN according to the desired precedence.  Given

> I disagree

I'll follow your recommendation!

**Comment by paulbellamy** [comment]
Side-effect to keep in mind is that `--name=foo.bar` will become `foo.bar.weave.local.`

**Comment by rade** [comment]
> I was hoping to avoid parsing the docker arguments upfront

`dns_args` is already doing exactly that.

**Comment by rade** [comment]
and it needs to happen upfront because we cannot set the hostname after container creation time.

**Comment by awh** [comment]
> dns_args is already doing exactly that.

Very superficially. But I take your point.

> and it needs to happen upfront because we cannot set the hostname after container creation time.

I misunderstood the requirement here - I thought you just wanted the record inserted into weaveDNS, not that you wanted the omission of the `-h` parameter overridden.
