### ISSUE TITLE
[proxy] make `weave launch-proxy` return DOCKER_HOST settings

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#753]
This would be convenient:

````
DOCKER_HOST=$(weave launch-proxy)
docker run ...
````

**Comment by paulbellamy** [comment]
Could also do it the same way as boot2docker:
```
$ boot2docker up
$ eval "$(boot2docker shellinit)"
```

eval is less nice, but lets it a) return more output than just the docker_host, and b) set tls at the same time.

**Comment by rade** [comment]
I was rather trying to avoid eval.

@errordeveloper I believe swarm or compose have something in this area. Details?

**Comment by errordeveloper** [comment]
So Machine is the new `boot2docker`, one either used `eval $(docker-machine env)` or `docker $(docker-machine conf) ...`. Machine would also setup Swarm, if you pass it the right flags. With Compose, one actually has to use `eval` as it doesn't take flags that `docker-machine conf` outputs. With Machine you also get 3 variables that define host and port and TLS stuff.

**Comment by errordeveloper** [comment]
```
> docker-machine ls
NAME     ACTIVE   DRIVER       STATE     URL                         SWARM
test-1   *        virtualbox   Running   tcp://192.168.99.100:2376   

> docker-machine config
--tlsverify --tlscacert="/Users/ilya/.docker/machine/machines/test-1/ca.pem" --tlscert="/Users/ilya/.docker/machine/machines/test-1/cert.pem" --tlskey="/Users/ilya/.docker/machine/machines/test-1/key.pem" -H=tcp://192.168.99.100:2376
> docker-machine env
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="/Users/ilya/.docker/machine/machines/test-1"
export DOCKER_HOST=tcp://192.168.99.100:2376

# Run this command to configure your shell: eval "$(docker-machine env)"

```

**Comment by errordeveloper** [comment]
If you setup Swarm via passing flags to Machine, you then do `docker-machine config --swarm` or `docker-machine env --swarm` to talk to the Swarm endpoint.

**Comment by paulbellamy** [comment]
So, equivalent would be: `eval $(weave env)` and/or `docker $(weave config) run ...`

**Comment by paulbellamy** [comment]
Should inspect the `weaveproxy` container, and find the exposed port, also. Not worrying about TLS for now.

**Comment by rade** [comment]
NB: these commands would ideally not invoke weavexec.

**Comment by rade** [comment]
> NB: these commands would ideally not invoke weavexec.

What I meant is that ideally these commands would execute completely locally. But that isn't going to work since with #805 and #810 only the proxy knows how it was configured, so we have to ask it.

NB: the settings thus obtained aren't going to be correct in the presence of firewalls.

**Comment by paulbellamy** [comment]
Gets more interesting with TLS, as well.

**Comment by paulbellamy** [comment]
With TLS, we can't really figure out the client certs, as we would have to guess their location. We could potentially query the proxy and set DOCKER_TLS_VERIFY, based on that. Which means it would work for TLS, aside from the user would need to set DOCKER_CERT_PATH (or have their client certs in `~/.docker`).

Downside of querying the proxy to determine `--tlsverify` status is that the client computer will need curl/wget/telnet/netcat. (Since we want this to run locally, not through exec_remote).

**Comment by rade** [comment]
whether the client uses crypto, and if so what flavour and what certs, is a user choice, and not something that can be derived from the proxy / server config. And it's not unreasonable to ask users to set env vars / supply command line options to their docker invocations *using the same settings they'd use when not going via the proxy*. That's the point of #506.

So I think we should stick to determining a plausible value for `DOCKER_HOST` here.

**Comment by paulbellamy** [comment]
Ah, so you're saying usage with docker-machine would be:
```
$ eval $(docker-machine env)
$ eval $(weave proxy-env)
$ docker ps
```

Not sure how the `weave proxy-config` works with `docker-machine config` then...

**Comment by rade** [comment]
I wasn't saying anything about machine.

Surely in the proxy + machine setup, the chaining is client -> machine -> proxy -> docker. In which case machine needs to be made aware of anything that is *different* compared to talking to docker directly. And that should only be the DOCKER_HOST.
