### ISSUE TITLE
[dns][ipam] have a default subnet for DNS

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#763]
Similar to #743, and as an improvement on  #675, we should be able to launch DNS without specifying any network.

**Comment by rade** [comment]
I wonder whether we can get away with *not* having a default subnet specifically for DNS, i.e. just use the main default subnet.

Besides isolation, does anything actually break when apps share a subnet with DNS?

**Comment by rade** [comment]
> Besides isolation, does anything actually break when apps share a subnet with DNS?

#899 lists a few things. Anything else? In particular, are there possible *accidental* breakages, e.g. apps interfering with weaveDNS or vice versa? Obviously apps using multicast on port 53 would be problematic, but that's an edge case.

**Comment by bboreham** [comment]
mDNS is on port 5353. Not that that changes the argument.
