### ISSUE TITLE
weave launch fails to launch the container - without any valuable error or log. 

### ISSUE THREAD

**Issue by bdastur** [weaveworks/weave#766]
Summary:
Execuing "weave launch" returns 

Error response from daemon: Cannot start container c002839162262409e461872a126940beddc2833194388659cc2d5418a4ea07bc:

Some things to note:
1. The system is in the lab which is not able to access public network, so I had to manually get the weaveexec and weave images (get it on a jump host and then manually scp them on my host, and run docker load)

[root@gg34-11 ~]# docker images | grep weave
weaveworks/weaveexec                      0.11.0              e864c9749cbb        34 hours ago        43.17 MB
weaveworks/weave                          0.11.0              f859ec6b97bb        34 hours ago        14.03 MB

System Info:
[root@gg34-11 ~]# uname -a
Linux gg34-11 3.10.0-229.4.2.el7.x86_64 #1 SMP Fri Apr 24 15:26:38 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@gg34-11 ~]# 
[root@gg34-11 ~]# uname -r
3.10.0-229.4.2.el7.x86_64

How can I debug this further, or am I missing anything else.

**Comment by rade** [comment]
A few things to look at ...

1. run `docker logs` on the container id that appears in the error message of `weave launch`.
2. run `WEAVE_DEBUG=1 weave launch`
