### ISSUE TITLE
[proxy] talk to docker daemon over TLS

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#771]
In some setups the docker daemon is only reachable over TLS, even locally. We need to cater for that, mirroring the myriad of ways this can be configured in a docker client.

**Comment by withinboredom** [comment]
I second this, as the proxy does not function in a boot2docker vm, since it uses TLS by default.

**Comment by rade** [comment]
Isn't that addressed by #506?

**Comment by withinboredom** [comment]
Ah, didn't see that!

**Comment by paulbellamy** [comment]
Without the docker daemon listening on `/var/unix/docker.sock`, the weave script will not be able to boot the proxy (as the client certificates will not be available in the `weaveexec` image.

Therefore, the proxy will always have a `/var/unix/docker.sock` available, and there is no need for this.

Closed -> wontfix
