### ISSUE TITLE
IPAM not working on CoreOS

### ISSUE THREAD

**Issue by colebrumley** [weaveworks/weave#786]
I am trying to use dynamic IP allocation on CoreOS and the Weave nodes sync up, but never start IPAM allocation.  After trying a bunch of solutions on my current setup, I cloned https://github.com/fintanr/weave-gs/tree/master/coreos-simple and followed those instructions, adding `-iprange 10.0.0.0/16` to the weave launch args. 

No matter what I try, `weave status` returns
```
Allocator subnet 10.0.0.0/16
Awaiting consensus: Nodes known: 0, Quorum size: 1
```

The logs don't appear very helpful either:
```
weave 2015/05/28 15:57:24.853815 Command line options: map[iface:ethwe iprange:10.0.0.0/16 name:da:ca:67:19:5f:db nickname:weave-gs-02 port:6783 wait:20]
weave 2015/05/28 15:57:24.853921 Command line peers: [172.17.8.101]
weave 2015/05/28 15:57:24.854015 Communication between peers is unencrypted.
weave 2015/05/28 15:57:24.854061 Our name is da:ca:67:19:5f:db(weave-gs-02)
weave 2015/05/28 15:57:24.854076 Assuming quorum size of 2
INFO: 2015/05/28 15:57:24.855357 [updater] Using Docker API on unix:///var/run/docker.sock: &[GoVersion=go1.3.3 KernelVersion=4.0.1 Os=linux Version=1.5.0 ApiVersion=1.17 Arch=amd64 GitCommit=a8a31ef-dirty]
weave 2015/05/28 15:57:24.858979 Sniffing traffic on &{10 65535 ethwe 5a:1d:fd:02:36:0c up|broadcast|multicast}
weave 2015/05/28 15:57:24.859037 Discovered our MAC 5a:1d:fd:02:36:0c
weave 2015/05/28 15:57:24.859547 ->[172.17.8.101:6783] attempting connection
weave 2015/05/28 15:57:24.863744 ->[172.17.8.101:6783|12:0b:31:2b:57:ee(weave-gs-01)]: completed handshake
weave 2015/05/28 15:57:24.863946 ->[172.17.8.101:6783|12:0b:31:2b:57:ee(weave-gs-01)]: connection added (new peer)
weave 2015/05/28 15:57:24.867103 ->[172.17.8.101:6783|12:0b:31:2b:57:ee(weave-gs-01)]: connection fully established
weave 2015/05/28 15:57:24.868994 EMSGSIZE on send, expecting PMTU update (IP packet was 60064 bytes, payload was 60056 bytes)
weave 2015/05/28 15:57:24.869100 ->[172.17.8.101:6783|12:0b:31:2b:57:ee(weave-gs-01)]: Effective PMTU set to 1438
weave 2015/05/28 15:57:24.871700 ->[172.17.8.101:6783|12:0b:31:2b:57:ee(weave-gs-01)]: Effective PMTU verified at 1438
weave 2015/05/28 15:57:25.459939 Discovered local MAC b6:04:cd:a6:92:ca
weave 2015/05/28 15:57:25.478966 Discovered local MAC da:ca:67:19:5f:db
```

I'm running weave version 0.11

**Comment by rade** [comment]
What makes you think anything is wrong?

**Comment by rade** [comment]
To elaborate, weave won't attempt to reach a consensus on the initial IP allocation until something asks for an IP, and the status you are seeing would be shown until then.

**Comment by dpw** [comment]
> What makes you think anything is wrong?

I can certainly see how that `weave status` output could give the impression that it is not operational.

**Comment by rade** [comment]
agreed.

**Comment by colebrumley** [comment]
Yes, that's what it was - I assumed that it wasn't working because I was expecting to see the consensus immediately after all the nodes joined each other.  Once I started a container it allocated appropriately.

The reason I thought it wasn't working is that I am not getting cross host communication.  Although the 3 nodes are peered (AFAIK), I cannot reach containers on other hosts with either weave DNS or directly via the weave-assigned IP.

Here's the [cloud config I'm using](https://gist.github.com/colebrumley/7229da41c9f21aa08d13) (in Vagrant) in case it's helpful.  I ran an influxdb container on core-03 (with `weave run --with-dns -p 8083:8083 -p 8086:8086 --name influxdb -h influxdb.weave.local kubernetes/heapster_influxdb:v0.3`) and then started an ubuntu container on core-01 (`weave run --with-dns -i -t ubuntu`).

I couldn't ping the weave-assigned IP or DNS name of the influx container although core-03 says the DNS record is there (`Zone database: 2afb9e0aa310 10.99.64.2 influxdb.weave.local.`).

That's the log answer to why I opened this issue - unless I've missed something in the docs, I would expect the connectivity to be there after the above.

**Comment by tomwilkie** [comment]
After you have started these containers, what does weave status say?

**Comment by colebrumley** [comment]
The core-01 machine has:
```
core@core-01 ~ $ weave status
weave router 0.11.0
Encryption off
Our name is 5e:c3:c5:df:7e:6e(core-01)
Sniffing traffic on &{10 65535 ethwe de:e0:a1:37:12:40 up|broadcast|multicast}
MACs:
Peers:
2e:27:cc:ed:35:bc(core-02) (v6) (UID 5859142462138010367)
   -> 5e:c3:c5:df:7e:6e(core-01) [172.17.8.101:6783]
   -> 0a:7f:41:b8:dd:8e(core-03) [172.17.8.103:51423]
0a:7f:41:b8:dd:8e(core-03) (v6) (UID 7081446775549430671)
   -> 5e:c3:c5:df:7e:6e(core-01) [172.17.8.101:6783]
   -> 2e:27:cc:ed:35:bc(core-02) [172.17.8.102:6783]
5e:c3:c5:df:7e:6e(core-01) (v4) (UID 3939659049563670093)
   -> 2e:27:cc:ed:35:bc(core-02) [172.17.8.102:60146]
   -> 0a:7f:41:b8:dd:8e(core-03) [172.17.8.103:44767]
Routes:
unicast:
5e:c3:c5:df:7e:6e -> 00:00:00:00:00:00
2e:27:cc:ed:35:bc -> 2e:27:cc:ed:35:bc
0a:7f:41:b8:dd:8e -> 0a:7f:41:b8:dd:8e
broadcast:
5e:c3:c5:df:7e:6e -> [2e:27:cc:ed:35:bc 0a:7f:41:b8:dd:8e]
2e:27:cc:ed:35:bc -> []
0a:7f:41:b8:dd:8e -> []
Reconnects:

Allocator subnet 10.99.0.0/16
  Free IPs: ~100.0%, 16383 local, ~49147 remote
Owned Ranges:
  10.99.0.1 -> 5e:c3:c5:df:7e:6e (core-01) (v7)
  10.99.64.1 -> 0a:7f:41:b8:dd:8e (core-03) (v4)
  10.99.128.0 -> 2e:27:cc:ed:35:bc (core-02) (v1)

weave DNS 0.11.0
Local domain weave.local.
Listen address :53
mDNS interface &{14 65535 ethwe f6:7d:25:c4:97:30 up|broadcast|multicast}
Fallback DNS config &{[10.0.2.3] [] 53 1 5 2}
Zone database:
```

The core-03 node (running influx) has:
```
core@core-03 ~ $ weave status
weave router 0.11.0
Encryption off
Our name is 0a:7f:41:b8:dd:8e(core-03)
Sniffing traffic on &{10 65535 ethwe 12:15:bb:35:18:ea up|broadcast|multicast}
MACs:
Peers:
0a:7f:41:b8:dd:8e(core-03) (v6) (UID 7081446775549430671)
   -> 5e:c3:c5:df:7e:6e(core-01) [172.17.8.101:6783]
   -> 2e:27:cc:ed:35:bc(core-02) [172.17.8.102:6783]
5e:c3:c5:df:7e:6e(core-01) (v4) (UID 3939659049563670093)
   -> 2e:27:cc:ed:35:bc(core-02) [172.17.8.102:60146]
   -> 0a:7f:41:b8:dd:8e(core-03) [172.17.8.103:44767]
2e:27:cc:ed:35:bc(core-02) (v6) (UID 5859142462138010367)
   -> 5e:c3:c5:df:7e:6e(core-01) [172.17.8.101:6783]
   -> 0a:7f:41:b8:dd:8e(core-03) [172.17.8.103:51423]
Routes:
unicast:
0a:7f:41:b8:dd:8e -> 00:00:00:00:00:00
5e:c3:c5:df:7e:6e -> 5e:c3:c5:df:7e:6e
2e:27:cc:ed:35:bc -> 2e:27:cc:ed:35:bc
broadcast:
0a:7f:41:b8:dd:8e -> [5e:c3:c5:df:7e:6e 2e:27:cc:ed:35:bc]
5e:c3:c5:df:7e:6e -> []
2e:27:cc:ed:35:bc -> []
Reconnects:

Allocator subnet 10.99.0.0/16
  Free IPs: ~100.0%, 16381 local, ~49149 remote
Owned Ranges:
  10.99.0.1 -> 5e:c3:c5:df:7e:6e (core-01) (v7)
  10.99.64.1 -> 0a:7f:41:b8:dd:8e (core-03) (v4)
  10.99.128.0 -> 2e:27:cc:ed:35:bc (core-02) (v1)

weave DNS 0.11.0
Local domain weave.local.
Listen address :53
mDNS interface &{14 65535 ethwe 1e:ef:02:c6:68:f9 up|broadcast|multicast}
Fallback DNS config &{[10.0.2.3] [] 53 1 5 2}
Zone database:
2afb9e0aa310 10.99.64.2 influxdb.weave.local.
```

**Comment by tomwilkie** [comment]
If I read your script correctly (not that familiar with it) it looks like you might be starting weave dns wrong:
```
 ExecStartPre=/opt/bin/weave launch-dns 10.99.0.0/16
```

You need to give weave dns a separate subnet to ipam, and each weave dns needs a unique IP address.  We're working on having IPAM manage the weave dns subnet, but we're not there in 0.11.

**Comment by tomwilkie** [comment]
Also it might be safer to pass all hosts IP to every weave router start - one of you IPAMs thinks the quorum is one and will happily go off on its own in a split brain.  If they are all told about each other, this won't happen.

**Comment by colebrumley** [comment]
![i get it now](http://www.reactiongifs.us/wp-content/uploads/2013/11/i_like_that_doctor_who.gif)

That explains it, thanks for the quick answers all!

**Comment by rade** [comment]
Yes, the weavedns start is certainly wrong. From [the docs](http://docs.weave.works/weave/latest_release/weavedns.html#usage)
> Each weaveDNS container started with `launch-dns` needs to be given its own, unique, IP address, in a subnet that is a) common to all weaveDNS containers, b) disjoint from the application subnets, and c) not in use on any of the hosts.

I can't see why that would break cross-node pings though.

There is one other thing which is obviously wrong in the config: It pulls in a whole bunch of `zettio/` images. These do *not* contain the latest release (which is under `weaveworks/`). And some of the images in fact no longer exist in the latest version. None of this code should be necessary; just run `weave setup`, which does exactly what you are trying to do here, i.e. download the latest version of all the required images.

This doesn't explain any breakage either though since the weave script will simply pull in the correct images when it needs them.

It's worth running `weave ps` on all the machines, to check that you have all the containers hooked up to the weave network as expected.

**Comment by colebrumley** [comment]
@rade Yes, it's ugly and wrong - I was doing a significant amount of copypasta with the intent to clean it up once the functionality was working.  I am now off to the races - for some reason the cross node pings came back after I fixed the DNS setup.

**Comment by rade** [comment]
> for some reason the cross node pings came back after I fixed the DNS setup.

That's good to hear. I wonder whether the fact that DNS had been given a *network* address caused some interference.
