### ISSUE TITLE
[ipam] race condition in unit test

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#802]
In `TestAllocatorFuzz()`, it is possible for the `allocateAgain` action to select a target, then for that target's address to be freed on another goroutine, then to attempt the allocation and hence get a different result.

One possible fix at https://github.com/weaveworks/weave/commit/7aec12063187790bc6541f17d28d060fa6b4926c

**Comment by tomwilkie** [comment]
That fix LGTM

**Comment by rade** [comment]
@bboreham PR?
