### ISSUE TITLE
[proxy] Add support for custom port

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#805]

**Comment by rade** [comment]
It's probably worth tackling this together with #810. `-listen <ip> | :<port> | <ip>:<port>`? and a space separated list for specifying more than one.

**Comment by paulbellamy** [comment]
Docker uses multiple `-H` arguments for multiple listening ports, so let's match that: `weave launch-proxy -L <ip> -L :<port> -L <ip>:<port>`.

Would be nice to rename the `-H` and `-L` arguments to the proxy to closer match docker daemon's arguments, but, that will break backwards-compat.

**Comment by rade** [comment]
We can't match that w/o doing our own flag parsing since golang's flag parser processes multiple occurrences of the same flag by stomping on the old values.

 *That*'s why I suggested what I did.

> Would be nice to rename the `-H` and `-L` arguments to the proxy to closer match docker daemon's arguments, but, that will break backwards-compat.

backward compatibility is of no concern.

**Comment by paulbellamy** [comment]
We already do our own arg parsing using [this](https://godoc.org/code.google.com/p/getopt), at the moment. It would just be a case of swapping libraries to something that supports multi-args, (and maybe has nicer syntax for args, e.g. [http://godoc.org/github.com/codegangsta/cli#StringSlice](http://godoc.org/github.com/codegangsta/cli#StringSliceFlag))

**Comment by rade** [comment]
argh. I missed the esoteric option parsing library in the proxy review. Are you saying that isn't supporting multi-args either?

**Comment by paulbellamy** [comment]
No, it's just for the double-hyphen, at the moment.

**Comment by paulbellamy** [comment]
Actually, getopt does multi-args. Was hidden further down in the docs.

**Comment by rade** [comment]
I have just noticed that the proxy already has an (undocumented!) `-L` option to specify what address and port to listen on. So what actually needs doing here? Other than documentation.

**Comment by paulbellamy** [comment]
See https://github.com/weaveworks/weave/issues/810#issuecomment-109920081
