### ISSUE TITLE
[proxy] listen on specific IPs

### ISSUE THREAD

**Issue by Zaephor** [weaveworks/weave#810]
The proxy is configured for :12375 but it appears to end up binding on all host nics, which feels dangerous due to --privileged --net=host switches being used and TLS not being available/ready yet.

I know there's already a feature request for custom ports #805, would be nice to also be able to restrict responses to a specific nic.

For example only respond to eth0:12375, or lo:12375, or any combination of ethX:12375 and lo:12375 or other nic devices.

**Comment by rade** [comment]
Usually this is done by permitting the user to specify specific IP addresses, rather than interfaces, to listen on. So let's do that.

**Comment by Zaephor** [comment]
Good point, I've been trying to play in iptables for too long... :rage1:

**Comment by rade** [comment]
@paulbellamy I have just noticed that the proxy already has an (undocumented!) `-L` option to specify what address and port to listen on. So what actually needs doing here? Other than documentation.

**Comment by paulbellamy** [comment]
We need to configure the exported port binding from the container. And, ideally rename `-L` to `-H`, to match docker config options.

**Comment by Bregor** [comment]
Is it available for weave-1.5?

**Comment by bboreham** [comment]
@Bregor yes, you pass the `-H` flag - take a look at https://www.weave.works/docs/net/latest/weave-docker-api/

**Comment by Bregor** [comment]
@bboreham sorry, I confused it with router.
Is there any possibility to bind router to specific address instead of 0.0.0.0?

**Comment by Bregor** [comment]
I mean `weacer` process is always listening 0.0.0.0 like following:

    tcp        0      0 0.0.0.0:6783            0.0.0.0:*               LISTEN      8761/weaver

Is there any way to change this?

**Comment by bboreham** [comment]
Looking at the code, it accepts a `--host` argument which should take an IP address (and optional port number), like `172.31.20.13`.

Do you mind explaining why you want this?  The option is currently undocumented, and understanding what you want it for might help us to write the documentation.

**Comment by bboreham** [comment]
(note that changing the port almost certainly won't work without other changes.  this is probably connected with the fact that it's undocumented)

**Comment by Bregor** [comment]
@bboreham thank you very much!
`--host` is what I missed.

Explanation is simple: I want to run weave only on internal interfaces (I'm on bare metal) and be calm about external connections.

**Comment by bboreham** [comment]
OK, thanks!  

(Turns out I was just wrong about including a port in `--host` - we have an environment variable `$WEAVE_PORT` to do that).  Will remove it from earlier comments to save confusing anyone later.)
