### ISSUE TITLE
Use weave IP and static routes to reach weaveDNS

### ISSUE THREAD

**Issue by squaremo** [weaveworks/weave#811]
Per https://github.com/weaveworks/docker-plugin/issues/14#issuecomment-107641543, it is possible to supply the weave IP address of weaveDNS to containers, so long as they are given a static route to it (and it is given a route back to all containers).

This removes the need to use the docker bridge, so containers can run without it, which makes DNS with the plugin possible (and it improves isolation, for whatever that's worth).

**Comment by squaremo** [comment]
Potentially, this could run in conjunction with listening on the docker bridge (for legacy deployments). For example, the plugin could implement this mode, setting the static route on each container and the return route (for the subnet on which it's allocating IPs) for the weavedns container. This may even mean nothing needs to change here.

**Comment by squaremo** [comment]
Another note: using the weave IP means that this can only be set when that IP is discoverable, which more or less means when weaveDNS is running; and, it can change. Maybe it would be better, if possible, to use the IP of the weave bridge.

**Comment by rade** [comment]
subsumed by #1301.
