### ISSUE TITLE
Option to encrypt some links but not others

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#82]
E.g. if you want to encrypt traffic leaving your site, but not pay the overhead for intra-datacenter traffic.

**Comment by inercia** [comment]
Regarding the _zones_ idea, would it be something like _tags_ that users could assign to Weave instances? I guess users should then configure them by setting _properties_  for each zone. How would a zone configuration be distributed among nodes? Gossiping? And what about nodes in multiple zones?

**Comment by rade** [comment]
> Regarding the *zones* idea, would it be something like *tags* that users could assign to Weave instances

I don't see the need for that. As I said, "When launching a peer one could optionally specify a zone. Connections to peers in the same zone would be unencrypted, and across zones encrypted.". So it would simply be something like `weave launch --zone=my-aws`.

> I guess users should then configure them by setting *properties* for each zone.

No, zones don't have properties.

**Comment by rade** [comment]
In thinking about #646 I discovered a gotcha with the zones idea... just because two peers are the same zone, doesn't mean they will necessarily communicate with each other over a route that "stays inside" the zone. In particular, peers inside a data centre might be reachable via both public and private IPs, with communication over the former being insecure and the latter secure.

**Comment by fermayo** [comment]
Maybe you could specify a subnet where communications to other peers in that subnet won't be encrypted? `weave launch --local-subnet=172.77.64.0/18`

**Comment by rade** [comment]
Yes, I think specifying a list of trusted subnets would work.

> We'd probably have to conduct the handshake always encrypted, to prevent spoofing.

Note that currently the handshake is always unencrypted. So that would have to change.
