### ISSUE TITLE
Negative result cache does not expire if requeried within TTL

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#845]
Reported by @oscar-martin on #weavenetwork: negative cache results for local names can be kept alive indefinitely if a client queries for that name with a frequency that exceeds the default TTL (30s)

In these cases, if the name is unavailable on the first query, or a single mDNS response is dropped, the cache is poisoned until either the caching weaveDNS instance is restarted or the client process stopped long enough to let the entry expire.

**Comment by rade** [comment]
NB: make sure to branch off the 0.11 branch for the fix.

**Comment by rade** [comment]
Fixed by  #849 and https://github.com/weaveworks/weave/commit/bb3dd55a10e28b4acc2bc662de011bfe761bd25b
