### ISSUE TITLE
use Swarm discovery backends

### ISSUE THREAD

**Issue by inercia** [weaveworks/weave#850]
Weave could be instructed to connect to peers registered in a Swarm backend. For example, we could:
* launch the router with something like `weave launch --with-swarm=etcd://myhost.com/mycluster`.
* start a WeaveSwarm container if not running (in the same way we currently do with WeaveDNS)
* this container would run a daemon that would use the corresponding [Swarm discovery backend](https://github.com/docker/swarm/tree/master/discovery) for sending `/connect`/`/forget` requests to the router.

**Comment by Stellaverse** [comment]
+1

Excellent idea.

**Comment by inercia** [comment]
Moved to the [discovery repository](https://github.com/weaveworks/discovery).
