### ISSUE TITLE
`weave hide/detach` allocates a new address if called with no preceding `expose/attach`

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#860]
This is a conscious choice, to make the script simpler, but is strictly unnecessary, and could lead to failure cases, e.g. if ipam is out of addresses.

[note that, as of current state of #827, the same will apply to `detach` with no preceding `attach`]

**Comment by rade** [comment]
This can also result in hangs...
```
$ weave launch --init-peer-count=2
$ weave hide
...(waits forever)
```

**Comment by rade** [comment]
`detach` is similarly afflicted:

```
$ weave launch --init-peer-count=2
$ docker run --name=foo -dti ubuntu
5884f1daccb9e5821d82c30900f96720dbfda9001da5f5052a87a5bcb7b3c8bf
$ weave detach foo
```

**Comment by bboreham** [comment]
> This can also result in hangs

On a point of history, "could lead to failure cases, e.g. if ipam is out of addresses" was correct at the time of writing, but subsequently we decided that the behaviour of IPAM on out-of-addresses should be to wait until an address is available, which gives the behaviour you see.
