### ISSUE TITLE
`weave detach` with no CIDR args should detach automatically allocated IPs

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#862]
...though once we have #675, it should only detach from IPs allocated in the default subnet.

**Comment by bboreham** [comment]
This has been fixed on the #827 branch - https://github.com/bboreham/weave/commit/ae5b278d07849d1aea738284a89660aad5cfe7aa#diff-ed6579eaedd0e67b3ed51c7ee7071044R1064
