### ISSUE TITLE
gce destroy retries not working

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/weave#864]
https://circleci.com/gh/weaveworks/weave/690

The set -ex at the top is the problem, I think.

**Comment by rade** [comment]
@tomwilkie what's up with this? still broken?

**Comment by tomwilkie** [comment]
It hasn't done it since. There is still the 'bug' where if you cancel a
test run the Vms don't get cleared up.

**Comment by rade** [comment]
>  There is still the 'bug' where if you cancel a test run the Vms don't get cleared up.

That has since been fixed, hasn't it? So can this issue be closed?

**Comment by tomwilkie** [comment]
https://github.com/weaveworks/weave/blob/master/test/gce.sh#L39 still has an ```|| true``` in it, which I think is why its broken.

**Comment by bboreham** [comment]
Fixed by #1857
