### ISSUE TITLE
Issue with running a multicast-based simulation across weave

### ISSUE THREAD

**Issue by bergtwvd** [weaveworks/weave#868]
I want to run a portico-based containerized distributed simulation over weave.
The Portico RTI provides the simulation run time infrastructure (RTI) for communication and coordination between so called "federates". A federate corresponds in this case with a Docker container. The Portico RTI uses JGroups/multicast for internal messaging.

Running federates in a single Docker host over Weave works OK.
Running federates in multiple Docker hosts over Weave does not work.

If have logged this issue at Portico. For more information see https://github.com/openlvc/portico/issues/140

I appreciate any support I can get to solve this issue.

Rgds,
Tom van den Berg

**Comment by rade** [comment]
This is a bit too application specific for us to investigate further, and I doubt it is an issue with weave. Happy to re-open if more evidence emerges.
