### ISSUE TITLE
make use of default IPAM throughout documentation

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#869]
IPAM should be documented as an integral rather than separate feature. i.e. throughout the docs we should generally make use of IPAM. Usually with the default sub-net, i.e. not specifying any IP/network. And specifying a subnet (but no IP) should become the primary means to deal with multiple subnets. I reckon specifying individual IP addresses may well be something we only cover once, in a separate section.

We will still want to keep docs specifically about IPAM, to explain stuff about quorum and cover various exotic uses.

**Comment by rade** [comment]
Ideally we'd tackle this after #675, #762, #763, #862, #870.

**Comment by bboreham** [comment]
Following #900 we can update the `launch-dns` examples to remove any IP addresses.
