### ISSUE TITLE
Multicast not working

### ISSUE THREAD

**Issue by neilellis** [weaveworks/weave#87]
I am able to ping between hosts no problem but when I run Hazelcast no discovery occurs. I've tried various multicast tools, but nothing seems to work. This could well be my inexperience in this area; if so it would be nice to document multicast over Weave as this is obviously a very good use case for Weave.

**Comment by leslie-wang** [comment]
I tried to run below command at each host using my multicast applications. it works.
    C=$(weave run 10.0.2.160/8 -t -i cazcade/weave-multicast-test receive); docker-ns $C route add -net 224.0.0.0 netmask 240.0.0.0 dev ethwe; docker attach $C

However, the traffic flows from one container to another container, not from external to internal. Is there a way to enable multicast flow from external network to container.

**Comment by dpw** [comment]
@leslie-wang Please could you open a new issue for that? This issue has been closed.
