### ISSUE TITLE
gossip unit test failing intermittently

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave#885]
For example https://travis-ci.org/weaveworks/weave/builds/66049086:

````
--- FAIL: TestGossipTopology-2 (0.00s)
	util.go:134: Expected connections not found: from 02:00:00:02:00:00 to map[03:00:00:03:00:00:{}]
...
	github.com/weaveworks/weave/router.implTestGossipTopology(0xc2091082d0)
		/home/travis/gopath/src/github.com/weaveworks/weave/router/gossip_test.go:116 +0xc0b
````

Appears to be caused by topology updates being delivered on a different goroutine, which sometimes happens later than expected.  There is a 'FIXME' comment to the effect that `sendPendingGossip()` may not work.

`go test -race` reports many race conditions in this test, which may or may not be relevant.

**Comment by rade** [comment]
This [still seems to be happening](https://travis-ci.org/weaveworks/weave/builds/66352533)
