### ISSUE TITLE
operation from private docker registries

### ISSUE THREAD

**Issue by pacaletx** [weaveworks/weave#887]
Hi,

Is there a way to have weave working on non-internet environment ? I mean actually it downloads images from docker hub right ? Even weave setup does that, and I didn't see any parameters to specify a private local repo ? For example we can put weave images on this repo and with an argument make the scrip download images from this repo ?

Maybe I missed something, that's why I asking ?

Thanks

**Comment by rade** [comment]
You should be able to set up a private docker registry. I have never done that myself, so can't comment on how difficult that is.

Alternatively, run `weave setup` on an internet-connected docker, extract the three images with `docker save <image> > <image>.tar`, copy them to the non-connected machine, and load them there with `docker load -i <image>.tar`.

**Comment by pacaletx** [comment]
Yup this solution works but it's not very convenient :/

**Comment by rade** [comment]
What would you like to see for more convenience?

**Comment by pacaletx** [comment]
Well in the script there is this line:

DOCKERHUB_USER=weaveworks

All we need I suppose in an option to change this variable.
If I have a local repo on 172.16.116.81:80, I can put weave images on it, and then do:

weave launch --repo 172.16.116.81:80 and it does pull 172.16.116.81:80/weave

Obviously I can change it in my script, but maybe some other users will need the same thing ?

**Comment by rade** [comment]
We can make `DOCKERHUB_USER` settable. Is there anything else you need?

**Comment by pacaletx** [comment]
Nope thanks

**Comment by rade** [comment]
Done. [Give the latest script a whirl](http://docs.weave.works/weave/latest_release/troubleshooting.html#snapshots).
