### ISSUE TITLE
http handler listens on all interfaces, which is bad

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#899]
The DNS server's http handler is listening on all interfaces. In particular that means it is listening on the ethwe interface. That is bad since it makes sharing a subnet between the DNS servers and app containers more dangerous than it should be - apps could modify DNS entries.

The http handler should listen on eth0 / the docker-assigned IP only, at least by default.

Then, at least when full app isolation has been configured (see the bottom of the [isolation](http://docs.weave.works/weave/latest_release/features.html#application-isolation) section in our docs), the weaveDNS http interface is inaccessible to apps.

Even then apps on the same subnet as weaveDNS can modify it - by setting up an mdns responder that participates in the weaveDNS chatter. But that is more involved. And not easily preventable.

**Comment by awh** [comment]
> But that is more involved. And not easily preventable.

And becomes a non-issue once we move to gossip...

**Comment by rade** [comment]
Good point re gossip. The http handler will stay - so this issue is still relevant then - whereas all the mDNS machinery will go.

**Comment by awh** [comment]
> The http handler should listen on eth0 / the docker-assigned IP only

Is it safe to assume the relevant interface is named eth0?

**Comment by rade** [comment]
> Is it safe to assume the relevant interface is named eth0?

Safe enough. Though we may want to add an option to override that.
