### ISSUE TITLE
make UDP connectivity issues easier to spot

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#908]
One of our users and myself have just wasted a good few of hours trying to work out why their application wasn't working over weave. The issue was somewhat masked by the complicated setup, and some mistakes in the app config, but was in fact evident from the very first information provided.

The clue was in the `weave status` output:

````
Peers:
46:87:fd:fb:ff:48(dn1) (v21) (UID 3554973017093463412)
   -> ca:90:7b:25:3d:1c(dn2) [172.31.39.46:48515 (unestablished)]
ca:90:7b:25:3d:1c(dn2) (v21) (UID 7413542752086581333)
   -> 46:87:fd:fb:ff:48(dn1) [172.31.41.112:6783 (unestablished)]
````

I had scanned through that and completely missed the "unestablished". Inexcusable for me, but I can certainly see how users would not notice that. It's really not very apparent at all that something isn't quite right.

Examination of the log showed absence of UDP connectivity, which is the most likely cause of 'unestablished'.

**Comment by awh** [comment]
In the interests of getting #1248 merged I suggest we address the remaining comments separately in this issue:

https://github.com/weaveworks/weave/pull/1248#issuecomment-128306579
https://github.com/weaveworks/weave/pull/1248#issuecomment-128317482
https://github.com/weaveworks/weave/pull/1248#issuecomment-128323612
