### ISSUE TITLE
make the release script support non-mainline releases

### ISSUE THREAD

**Issue by dpw** [weaveworks/weave#909]
The release script contains various sanity checks for latest_release, and updates latest_release.  That's great... until you want to do a non-mainline release.

It also assumes that release tags start with 'v'.  That's conventional for mainline releases, but not necessarily what you want for preview releases etc.

I'm sure we all wish for preview releases to be a rarity, but if they do happen from time to time, it would be nice to use the release script for them with less brute force involved.

**Comment by rade** [comment]
A related issue... `make publish`, which is called from the release script, always sets the 'latest' tag on the published images. That too will generally be the wrong thing to do for non-mainline releases.

**Comment by awh** [comment]
We may wish to mark such releases with `github-release release --pre-release`...
