### ISSUE TITLE
simplify multicast detection

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#91]
Extracted from issue #87.

Currently weave detects multicast by checking for the specific the MAC address prefixes signifying IPv4 and IPv6 multicast frames, as per http://en.wikipedia.org/wiki/Multicast_address#Ethernet

However, weave does not care about protocols, so we could simply check for anything signifying _ethernet_ multicast, i.e. MACs with the LSB of the first octet set.

**Comment by chino** [comment]
@rade Does this code path imply that `every` multicast packet is sent up to the miss handler in user space where it gets replicated to out?  or does the replication get done in a flow?

**Comment by rade** [comment]
@chino you are commenting on an issue that was closed nearly three years ago; a time when Weave Net passed *all* packets through user space. These days, when Weave Net's fastdp mode is in operation, all packet routing, including for multicast, happens in kernel space.
