### ISSUE TITLE
configuring the router password more securely

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#945]
The router currently accepts a passphrase via command line argument or environment variable, neither of which are particularly secure. An option should be provided to read the passphrase from a file, and steps taken to avoid having it swapped back out to disc (e.g. by mmap'ing or mlock'ing it). We should also check the permissions on the file and refuse to read from it if they are too lax.

**Comment by rade** [comment]
The issue here is that the file would have to reside on the *docker host*.

I'd generally assume that if an attacker can gain access to the docker host then the security of the weave password is quite far down the list of concerns.

**Comment by rade** [comment]
> neither of which are particularly secure.

What particular attack vector are we trying to block here?

Also, would we want to ensure that the router does not keep the password in memory?

**Comment by rade** [comment]
Note that we, briefly, had a [`-passwordfile`](https://github.com/weaveworks/weave/pull/332) option but removed it because the way it was implemented provided no additional security over the `WEAVE_PASSWORD` env var.

**Comment by awh** [comment]
> What particular attack vector are we trying to block here?

Non-root accounts (which could be anything ranging from legitimate shell accounts to compromised services) having visibility of the password.

**Comment by rade** [comment]
Is that the case even when the password is set in the environment, as [shown in the 2nd example in our docs](http://docs.weave.works/weave/latest_release/features.html#security), i.e.
````
host1$ export WEAVE_PASSWORD=wEaVe
host1$ weave launch
````
?

**Comment by rade** [comment]
@awh ping

**Comment by rade** [comment]
Perhaps all that needs doing here is to improve our documentation.

**Comment by awh** [comment]
> Is that the case even when the password is set in the environment

This isn't quite as bad, because the actual value is not specified on the docker run command line that launches the router - the host environment value is exposed to the container with `-e WEAVE_PASSWORD`. In combination with a systemd `EnvironmentFile` entry I'd rate it as passable. Nevertheless, both examples as written in features#security facilitate misuse - you'll end up with the password value in your shell history either way!

[Reading the auth key from a file](https://github.com/awh/weave/blob/weaver-auth-key-file/prog/weaver/main.go#L328) and deprecating `--password`/`WEAVE_PASSWORD` is still my first choice, but that runs into the annoying host bind mount issue...

**Comment by awh** [comment]
> Note that we, briefly, had a -passwordfile option but removed it because the way it was implemented provided no additional security over the WEAVE_PASSWORD env var.

I'm assuming the weave script was reading the contents of the file into `WEAVE_PASSWORD`? It may not have provided additional security, but at least it doesn't lend itself as easily to misuse - there are a number of ways you can mishandle setting WEAVE_PASSWORD before launching weave...
