### ISSUE TITLE
Weave fails to launch through proxy with IPAM enabled

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/weave#950]
With IPAM enabled by default, the proxy will try to use IPAM to assign an IP to weave (and weaveDNS). Of course, it can't do this, because the router is not running.

```bash
vagrant@host1:~$ ./weave launch-proxy
23b976a992c9fa016b851b3a76bf8addad703e0ead638c0f2da8de43d75b4552
vagrant@host1:~$ eval "$(./weave proxy-env)"
vagrant@host1:~$ ./weave launch
FATA[0000] Error response from daemon: weave container is not present. Have you launched it?
```

Possible Solutions:
1) Special-case `weave`, `weavedns`, `weaveexec` containers.
2) Tell users to boot the proxy last.
3) Add a `-e WEAVE_CIDR=none`, to be passed with the `weave` container to explicitly skip IPAM.
4) Tell the proxy not to IPAM these containers some other way (maybe `net=*` type?)

**Comment by rade** [comment]
Presumably this bug also occurred previously, if the proxy was launched with `--with-ipam`.

Let's go with option 1. Ideally by image rather than container name, but only if the former is no more difficult to obtain than the latter.

**Comment by rade** [comment]
actually, I've changed my mind. Let's go with option 3.
