### ISSUE TITLE
Basic FAQ

### ISSUE THREAD

**Issue by inercia** [weaveworks/weave#957]
We should have a basic FAQ, covering the most common questions...

**Comment by inercia** [comment]
It should include the [cryptography FAQ](http://blog.weave.works/2015/06/16/weave-net-cryptography-faq/) that @awh wrote...

**Comment by rade** [comment]
> covering the most common questions

How is the commonality determined? TBH, I don't see many "common" questions int @awh's crypto FAQ. Nor do I think the questions you've added on the branch for this issue are "common".

**Comment by inercia** [comment]
@rade Well, I admit it is a guess... I think that this document should be something we write collaboratively, adding questions we see in emails, bug reports, etc. And, if a question in the current FAQ is considered not relevant, it will be removed...

**Comment by rade** [comment]
Have we been asked *any* of the questions in your current list more than once?

**Comment by awh** [comment]
> I don't see any "common" questions in @awh's crypto FAQ.

I would argue that the use of an 'FAQ' as a means to explain particular choices is a fairly well established rhetorical device. Whether that's what we want in this case is another matter...

**Comment by inercia** [comment]
I think @awh is right. A FAQ is just another way of documenting things, and many of the questions in FAQs are never really asked by users... So this is just a start, and it can evolve with time with real questions from users...

**Comment by rade** [comment]
>  just another way of documenting things

Why not just document them? I can see why there may be some things that don't have a natural place in our main documentation. But that should be the exception. And the FAQ certainly shouldn't *duplicate* other parts of the documentation; just link to them.

**Comment by inercia** [comment]
Maybe we could get in [this branch](https://github.com/weaveworks/weave/tree/issues/957-faq) some performance Q&As from @bboreham ...

**Comment by rade** [comment]
> performance Q&As

#37.

**Comment by abuehrle** [comment]
this is in progress...

**Comment by abuehrle** [comment]
should be able to close this @rade minus the cryptography faq, which I think is covered in our crypto sections in the docs?

**Comment by rade** [comment]
Q4 in https://github.com/weaveworks/weave/blob/master/site/faq.md needs updating.

**Comment by rade** [comment]
> should be able to close this @rade minus the cryptography faq, which I think is covered in our crypto sections in the docs?

Well, arguably *everything* in the FAQ should be (and, afaict, is) covered in other sections of the docs. 

\<rant\>
I honestly don't see the point of the FAQ. I am not aware of any genuine *frequently* asked questions. And if there were such questions we really should make sure that our main docs have the answer (and such answer is easy to find).
\</rant\>

Anyway, I have reviewed the FAQ and [made some corrections](https://github.com/weaveworks/weave/compare/671dddf...019a065).

**Comment by abuehrle** [comment]
I took the questions from our user's group. Agreed that perhaps some of these questions could be retired. 

We can revisit this for the next release.
