### ISSUE TITLE
make `weave launch` launch everything

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#962]
Running the weave router, dns and proxy is now the common case, rather than the exception. So we should make that more convient...

1. `weave launch` should launch all three
2. `weave stop` should stop all three
3. `weave launch-router` should launch just the router (i.e. it's the current `weave launch`)
4. `weave stop-router` should stop just the router (i.e. it's the current `weave stop`)

Rather than getting all clever about arg parsing, `weave launch` should simply pass all args to (just) the router. In the unusual cases where a user wants to pass arguments to the dns or proxy, they can launch all three separately instead.

`weave launch` should fail with a suitable "already running" error (as now) if *any* of the three are already running, and *not* start any of the others. And if starting any of them fails, it should exit with a failure.

`weave stop` should stop *any* containers running, report a "not running" error (as now), and *succeed*.

**Comment by rimusz** [comment]
+1

**Comment by awh** [comment]
> `weave launch` should launch all three

Should it still print out the container IDs, now that there will be three of them?

**Comment by rade** [comment]
> Should it still print out the container IDs, now that there will be three of them?

They have never been all that useful, I guess, so no.

**Comment by awh** [comment]
> And if starting any of them fails, any others already started should be stopped.

Does this imply that for `weave stop`, if stopping any of them fails that any others already stopped should be started?

**Comment by rade** [comment]
> Does this imply that for `weave stop`, if stopping any of them fails that any others already stopped should be started?

No.
