### ISSUE TITLE
600_proxy_docker_py_test failing on CircleCI

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#970]
CircleCI is continuously failing in `600_proxy_docker_py_test.sh`. See, for example, https://circleci.com/gh/weaveworks/weave/1089. I've run the test manually to see what's going wrong, but it didn't fail...
````
vagrant@host1:~$ docker run -e NOT_ON_HOST=true -e DOCKER_HOST=tcp://172.17.42.1:12375 -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock joffrey/docker-py python tests/integration_test.py
.............................s....................................
----------------------------------------------------------------------
Ran 66 tests in 108.432s

OK (skipped=1)
````

Ditto for doing it the "proper" way, i.e. with `./600_proxy_docker_py_test.sh`

Could just be some issue with image downloads - the joffrey/docker-py image is huge - or a race condition in the tests.

**Comment by rade** [comment]
Would be nice to see the stdout/err for when this fails.

**Comment by rade** [comment]
Hurray, I have cajoled the test to give us an [error output](https://circleci.com/gh/weaveworks/weave/1188)!
````
---= Running 600_proxy_docker_py_test.sh =---
Run docker-py test suite against the proxy
bc2950a2047ccdd27692fd7ee44f41e4a335253faaab97677ef22a4c6e4aa29d
Unable to find image 'joffrey/docker-py:latest' locally
latest: Pulling from joffrey/docker-py
Digest: sha256:13e19ed19327fdf08d8afe421d0e97ec12648bac0b446d7e1de2cdd6ba77945b
Status: Downloaded newer image for joffrey/docker-py:latest
Traceback (most recent call last):
  File "tests/integration_test.py", line 1473, in <module>
    c.pull('busybox')
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 918, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 120, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.19, server: 1.18)")
test #1 "true" failed:
	program terminated with code 0 instead of 1
1 of 1 tests failed in 29.762s.
````

I am guessing docker-py includes the latest (1.7.0) docker client, whereas the test VMs are on 1.6.2.

@tomwilkie how do we get the VMs updated?

**Comment by tomwilkie** [comment]
There is some code to do it in gce.sh, but mainly its a manual process.
I'll do it today if you like?

**Comment by rade** [comment]
> I'll do it today if you like?

yes, please.

**Comment by tomwilkie** [comment]
Done: https://github.com/weaveworks/weave/commit/3b4a47a9610640bbea718673b8ab9576cb5f5e76

**Comment by tomwilkie** [comment]
Passing now; closing ticket.
