### ISSUE TITLE
Checking IDs against containers should be explicitly optional

### ISSUE THREAD

**Issue by squaremo** [weaveworks/weave#971]
Not assigning an IP because a container is not running breaks the Docker plugin, because it cannot supply a container ID, only an endpoint ID.

**Comment by rade** [comment]
Simply feed ipam an id that syntactically isn't a full container id. As we do with `weave:expose`.

**Comment by squaremo** [comment]
Yes, I came to that conclusion. That seems pretty grubby.

**Comment by squaremo** [comment]
(not to mention undocumented?)

**Comment by rade** [comment]
None of the IPAM APIs are documented.

**Comment by squaremo** [comment]
How does that even work? If not by coincidence.

**Comment by rade** [comment]
where's the coincidence?

**Comment by squaremo** [comment]
OK I take it back. Just a grubby hack, not a coincidence.

**Comment by rade** [comment]
Suggestions for non-grubby non-hacks welcome. Feel free to repurpose this issue for that; otherwise close it.

**Comment by squaremo** [comment]
Repurposing: Instead of assuming anything that looks like a container ID (e.g., a libnetwork endpoint ID) is in fact a container ID, and refusing to issue an IP for it, IPAM should be told when it should do this and when not. The option could be supplied, for example, as a form field in the POST (or a querystring param, or either).

For the purposes of being a general API, it would make more sense if the default was not to check; but it is more convenient for the weave script (and not a terrible burden elsewise) if it defaults the other way.

**Comment by rade** [comment]
NB: this issue also applies to DNS.

**Comment by tomwilkie** [comment]
For DNS, can I assume all non-empty containerids are intended to be
containerids? Or is the intention to pass endpoint ids to DNS also?

**Comment by squaremo** [comment]
> Or is the intention to pass endpoint ids to DNS also?

At the minute the plugin has to watch docker for containers coming and going, so it uses container IDs. If service discovery is opened up as an extension point, it'll be an endpoint ID (or some other). I recommend the approach given above rather than trying to guess from the name, which was after all the original complaint.

**Comment by rade** [comment]
> For DNS, can I assume all non-empty containerids are intended to be containerids?

No, you cannot assume that. And the current DNS code doesn't.

**Comment by rade** [comment]
> I recommend the approach given above rather than trying to guess from the name

That is *this* issue. For #826, let us keep the API the same.
