### ISSUE TITLE
weaveWaitEntrypoint is appended multiple times

### ISSUE THREAD

**Issue by oldlam** [weaveworks/weave#979]
file: https://github.com/weaveworks/weave/blob/v1.0.1/proxy/create_container_interceptor.go
function: `setWeaveWaitEntrypoint`
line 92: `container.Entrypoint = append(weaveWaitEntrypoint, container.Entrypoint...)`

I haven't had any experiences with golang,
but I believe this line allows the `/w/w` entrypoint to be inserted at the front for multiple times.

I am using dokku-alt with weave & weave proxy,
I could see the entrypoint of container launching with dokku becomes `/w/w /w/w /w/w /w/w /bin/bash`.

It's probably because in `setWeaveWaitEntrypoint`,
it's trying to insert `/w/w` to the container's entrypoint from docker inspect,
however the container has already included `/w/w` before.

**Comment by rade** [comment]
How did get into this state? Do you have steps to reproduce this, ideally not involving dokku?

Seems to me that for this to happen the proxy would somehow have to end up talking to itself. But that would just be an infinite recursion.

**Comment by oldlam** [comment]
I could try to reproduce this for you but it's now being produced by dokku-alt.
Just FYI the node.js container I'm running is basically dead in this situation (returning 502)

**Comment by rade** [comment]
Is there a simple way to reproduce this *with* dokku-alt?

**Comment by paulbellamy** [comment]
I have managed to reproduce it via committing containers. Will have to verify this is what dokku is doing.

**Comment by oldlam** [comment]
https://github.com/dokku-alt/dokku-alt/blob/master/plugins/dokku_common
yes dokku-alt is committing containers in their building steps.

@rade @paulbellamy thanks so much for the responses! :+1:

**Comment by rade** [comment]
Fixed by #980.

@oldlam thanks for reporting this. The fix will be part of 1.0.2, but we are not going to release that imminently. I have however pushed new images, so it would be good if you tested the fix by installing weave following the [snapshot instructions](http://docs.weave.works/weave/latest_release/troubleshooting.html#snapshots).

**Comment by oldlam** [comment]
@rade I just installed the snapshot and tested that it's working well with dokku-alt now, thanks for the fix! :+1: :smile:
