### ISSUE TITLE
Register weaveDNS resolver address in weaveDNS

### ISSUE THREAD

**Issue by awh** [weaveworks/weave#984]
nginx can reverse proxy/load balance across servers by domain name as long as a resolver is specified explicitly in the configuration (system resolver cannot be used, presumably as it does not have a non-blocking API). At the moment this would require determining the IP address from `/etc/resolv.conf` and injecting it into the configuration, which is a little awkward. Fortunately the resolver address can itself be specified by hostname, and this is looked up (with the system resolver) when nginx starts. Consequently if each weaveDNS peer were to publish a well known name (e.g. `weavedns.weave.local`) pointing to the correct resolver IP, this name could be used in the nginx configuration and the system would bootstrap itself automatically with no need to preprocess configuration files.

**Comment by rade** [comment]
>  if each weaveDNS peer were to publish a well known name

A lookup of that would return a random weavedns instance (currently) and a random shuffle of all results (eventually), which is not what we'd what.

**Comment by awh** [comment]
By 'correct resolver IP' I mean the docker bridge IP in the current implementation - I am relying on this being the same on every node admittedly.

**Comment by rade** [comment]
perhaps publish `weavedns-$(hostname).weave.local`?

**Comment by awh** [comment]
Assuming you could construct an nginx configuration that did a similar interpolation such that the same config would work on any host, yes. Or perhaps you've found a use for (locally scoped) CNAMEs...

**Comment by rade** [comment]
Hmm. locally scoped CNAME. That's an interesting idea.

**Comment by awh** [comment]
Referencing #636.

**Comment by inercia** [comment]
We could add a special flag in the API that would hide a name from mDNS (a trivil change), so we could register _dns.weave.local._ from the _weave_ script when starting WeaveDNS...

**Comment by rade** [comment]
or have a naming scheme, e.g. `X.local.weave.local` would only ever return locally registered entries.

**Comment by inercia** [comment]
I would prefer a _ident_ naming scheme: it would be much easier to implement. We currently have two _fake_ idents: `weave:expose` and `weave:remote`. We could add something like `weave:local`, `weave:private`, etc

**Comment by rade** [comment]
Interesting idea.

I can see how the ident based scheme would work in the current mDNS implementation, e.g. we would not return records with a `weave:local` ident in response to an mDNS query. And I guess in the gossip based implementation we'd exclude such records from the gossip.

The advantage is that we are not overloading names even more. The disadvantage is that the selection is made at record creation rather than query time. i.e. we say "I want these records to be locally visible only" instead of asking "what local records are there for this name?"

**Comment by inercia** [comment]
So, if no one objects, I will add a _fake ident_ `weave:local` and I will register there a `dns.<local-domain>` that will not be exported via mDNS...

**Comment by rade** [comment]
See discussion in #1058 for why this isn't necessary, i.e. `docker run --add-host weavedns:$(weave docker-bridge-ip)` does the trick.
