### ISSUE TITLE
resolve unqualified names in weavedns domain

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#987]
musl/busybox/alpine's dns resolver [is broken](https://github.com/weaveworks/weave/issues/985#issuecomment-114448705); it doesn't handle the 'search' directive. As a result unqualified names won't resolve in containers derived from busybox/alpine.

We could patch over that by getting weavedns to resolve unqualified names in the weavedns domain.

**Comment by inercia** [comment]
@rade I guess we should add the local domain only for names with one component (eg, `somename`, but not for `some.unknown.name`)...

**Comment by awh** [comment]
http://www.openwall.com/lists/musl/2014/04/30/7
