### ISSUE TITLE
Manage nat networking as well

### ISSUE THREAD

**Issue by farcaller** [weaveworks/weave#99]
It would be quite handy if weave would be the only service that managed containers network topology (so that containers could be started with `--net none`.

For this, weave needs to have NAT support for specific containers that are allowed to access "external network".

**Comment by AlexAndrascu** [comment]
So if I understand this correctly it's not a good ideea to run weave / docker with --net="none". 
Instead, in order to achieve app isolation we have to set --icc=false.

Is that correct ? 

Asking because i'm only getting this when running with --net="none"
```
sudo weave run 10.0.1.2/24 --net="none" --link mysql:db -v /var/www:/var/www:rw -v /var/run -p 80:80 -d --name lempp nginx
time="2015-01-22T22:23:47Z" level="fatal" msg="Error response from daemon: Cannot start container 7b1592655949f512cc4983ed0162f01d1a80645ac71a51d5682aa08b503720c9:  (exit status 2)"
```

**Comment by bboreham** [comment]
Hi Alex,

There's no intrinsic reason why this wouldn't work, and what you are seeing is an internal error from the Docker daemon.  If I Google for similar messages I find people for whom the error went away when they restarted Docker - can you try that?

Separately, I don't think you should expect `--net=none` and `--link` to work on the same container.  But I don't think that's causing this error.

**Comment by AlexAndrascu** [comment]
Hi Bryan, 

Thanks for you swift reply. Indeed I think it's best to open a new one indeed. Looks like this isn't the only issue on my install.   

Alex
