### ISSUE TITLE
shorten launch time by reducing sleep

### ISSUE THREAD

**Issue by rade** [weaveworks/weave#992]
I have [discovered](https://github.com/weaveworks/weave/issues/942#issuecomment-112973008) that sleeping for 1 second in `wait_for_status` retries is slowing down `weave launch` a fair bit. Ideally we'd sleep for a fractional time, but that is non-POSIX so we need to find a way around that.

**Comment by dpw** [comment]
I think just trying a fractional time and seeing whether sleep dies with an error will be fine.  But an alternative would be to do `sleep --version` and look for an appropriate coreutils version (I doubt POSIX specifies what `--version` should do, but it is even less likely to cause a problem.)
