### ISSUE TITLE
Device "docker0" does not exist when running Docker with --bridge="weave"

### ISSUE THREAD

**Issue by arjanschaaf** [weaveworks/weave#995]
I'm running a CoreOS + Kubernetes + Weave setup based on the Kubernetes getting started guide created by @errordeveloper : https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides/coreos/azure

My configuration is loosely based in this setup, using for example the integration setup with Weave.
The approach used is to:
0. create a weave network device
1. start the docker daemon with the --bridge="weave"
2. start weave by running **weave setup** and **weave launch**

With such a bridge running there is no need to run **weave-proxy**

This approach seems to work fine up to weave version **0.11.2** but I just tried version **1.0.1**
and the running weave setup & weave launch suddenly results in an error:

```
Jun 24 07:33:43 k8-node-1 weave[1476]: Device "docker0" does not exist.
```

**Comment by rade** [comment]
Try `weave --local setup`

**Comment by arjanschaaf** [comment]
Now running this configuration:

```
    - name: weave.service
      enable: true
      content: |
        [Unit]
        After=install-weave.service
        After=docker.service
        Description=Weave Service
        Documentation=http://weaveworks.github.io/weave/
        Requires=docker.service
        [Service]
        TimeoutStartSec=0
        EnvironmentFile=/etc/weave.%H.env
        ExecStartPre=/opt/bin/weave --local setup
        ExecStartPre=/opt/bin/weave launch $WEAVE_PEERS
        ExecStartPre=/opt/bin/weave launch-dns
        ExecStart=/usr/bin/docker attach weave
        Restart=on-failure
        ExecStop=/opt/bin/weave stop
        [Install]
        WantedBy=weave-network.target
```

which still results in a docker0 does not exist error:

```
Jun 24 08:42:30 k8-node-1 weave[799]: Status: Downloaded newer image for weaveworks/weaveexec:1.0.1
Jun 24 08:42:59 k8-node-1 weave[1126]: b1b6eda1ea5209fb5a0955292c222ef608925de0347483fdce8aec7fe458d5a1
Jun 24 08:43:02 k8-node-1 weave[1500]: Device "docker0" does not exist.
```

**Comment by rade** [comment]
Where in that setup are you starting docker? It needs to be started after `weave --local setup`, surely. And what's `docker attach weave`?

**Comment by rade** [comment]
I see you have a `weave launch-dns`. That requires access to `docker0`. Always has; this is nothing new in 1.0.

**Comment by rade** [comment]
See [the weaveDNS docs](http://docs.weave.works/weave/latest_release/weavedns.html#how-it-works) for instructions on how to configure weaveDNS to use a different bridge.

**Comment by arjanschaaf** [comment]
Sorry about that @rade : missed that second change in my setup. I upgraded to 1.0.1 and added the weaveDNS line as well.
Now passing the ```DOCKER_BRIDGE="weave"``` argument to the launch-dns and everything works just fine. Thanks for the help!
